CREATE LOGIN [ApplicationCenter]
    WITH PASSWORD = N'ldsnjapstxmn}wjZxaX{xbyNmsFT7_&#$!~<xhndvfoguzIg', SID = 0x6C7FFE344536DE4A8486FA4522DA68AA, DEFAULT_DATABASE = [CFApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

