  CREATE PROCEDURE WS_SOTax_INSERT
            @CpnyID char(10),
            @Crtd_DateTime smalldatetime,
            @Crtd_Prog char(8),
            @Crtd_User char(10),
            @CuryFrtTax float,
            @CuryFrtTxbl float,
            @CuryMerchTax float,
            @CuryMerchTxbl float,
            @CuryMerchTxblLessTax float,
            @CuryMiscTax float,
            @CuryMiscTxbl float,
            @CuryTotTax float,
            @CuryTotTxbl float,
            @FrtTax float,
            @FrtTxbl float,
            @LUpd_DateTime smalldatetime,
            @LUpd_Prog char(8),
            @LUpd_User char(10),
            @MerchTax float,
            @MerchTxbl float,
            @MerchTxblLessTax float,
            @MiscTax float,
            @MiscTxbl float,
            @NoteID int,
            @OrdNbr char(15),
            @S4Future01 char(30),
            @S4Future02 char(30),
            @S4Future03 float,
            @S4Future04 float,
            @S4Future05 float,
            @S4Future06 float,
            @S4Future07 smalldatetime,
            @S4Future08 smalldatetime,
            @S4Future09 int,
            @S4Future10 int,
            @S4Future11 char(10),
            @S4Future12 char(10),
            @ShowTaxOnOrderTotal smallint,
            @TaxCat char(10),
            @TaxID char(10),
            @TaxRate float,
            @TotTax float,
            @TotTxbl float,
            @User1 char(30),
            @User10 smalldatetime,
            @User2 char(30),
            @User3 char(30),
            @User4 char(30),
            @User5 float,
            @User6 float,
            @User7 char(10),
            @User8 char(10),
            @User9 smalldatetime
            AS
            BEGIN
            INSERT INTO [SOTax]
            ([CpnyID],
            [Crtd_DateTime],
            [Crtd_Prog],
            [Crtd_User],
            [CuryFrtTax],
            [CuryFrtTxbl],
            [CuryMerchTax],
            [CuryMerchTxbl],
            [CuryMerchTxblLessTax],
            [CuryMiscTax],
            [CuryMiscTxbl],
            [CuryTotTax],
            [CuryTotTxbl],
            [FrtTax],
            [FrtTxbl],
            [LUpd_DateTime],
            [LUpd_Prog],
            [LUpd_User],
            [MerchTax],
            [MerchTxbl],
            [MerchTxblLessTax],
            [MiscTax],
            [MiscTxbl],
            [NoteID],
            [OrdNbr],
            [S4Future01],
            [S4Future02],
            [S4Future03],
            [S4Future04],
            [S4Future05],
            [S4Future06],
            [S4Future07],
            [S4Future08],
            [S4Future09],
            [S4Future10],
            [S4Future11],
            [S4Future12],
            [ShowTaxOnOrderTotal],
            [TaxCat],
            [TaxID],
            [TaxRate],
            [TotTax],
            [TotTxbl],
            [User1],
            [User10],
            [User2],
            [User3],
            [User4],
            [User5],
            [User6],
            [User7],
            [User8],
            [User9])
            VALUES
            (@CpnyID,
            @Crtd_DateTime,
            @Crtd_Prog,
            @Crtd_User,
            @CuryFrtTax,
            @CuryFrtTxbl,
            @CuryMerchTax,
            @CuryMerchTxbl,
            @CuryMerchTxblLessTax,
            @CuryMiscTax,
            @CuryMiscTxbl,
            @CuryTotTax,
            @CuryTotTxbl,
            @FrtTax,
            @FrtTxbl,
            @LUpd_DateTime,
            @LUpd_Prog,
            @LUpd_User,
            @MerchTax,
            @MerchTxbl,
            @MerchTxblLessTax,
            @MiscTax,
            @MiscTxbl,
            @NoteID,
            @OrdNbr,
            @S4Future01,
            @S4Future02,
            @S4Future03,
            @S4Future04,
            @S4Future05,
            @S4Future06,
            @S4Future07,
            @S4Future08,
            @S4Future09,
            @S4Future10,
            @S4Future11,
            @S4Future12,
            @ShowTaxOnOrderTotal,
            @TaxCat,
            @TaxID,
            @TaxRate,
            @TotTax,
            @TotTxbl,
            @User1,
            @User10,
            @User2,
            @User3,
            @User4,
            @User5,
            @User6,
            @User7,
            @User8,
            @User9);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_SOTax_INSERT] TO [MSDSL]
    AS [dbo];

