 Create Procedure SCM_Insert_INTran
	@Acct VarChar(10),
	@AcctDist SmallInt,
	@ARLineID Integer,
	@ARLineRef VarChar(5),
	@BatNbr VarChar(10),
	@BMICuryID VarChar(4),
	@BMIEffDate SmallDateTime,
	@BMIExtCost Float,
	@BMIMultDiv VarChar(1),
	@BMIRate Float,
	@BMIRtTp VarChar(6),
	@BMITranAmt Float,
	@BMIUnitPrice Float,
	@CmmnPct Float,
	@CnvFact Float,
	@COGSAcct VarChar(10),
	@COGSSub VarChar(24),
	@CostType VarChar(8),
	@CpnyID VarChar(10),
	@Crtd_DateTime SmallDateTime,
	@Crtd_Prog VarChar(8),
	@Crtd_User VarChar(10),
	@DrCr VarChar(1),
	@Excpt SmallInt,
	@ExtCost Float,
	@ExtRefNbr VarChar(15),
	@FiscYr VarChar(4),
	@ID VarChar(15),
	@InsuffQty SmallInt,
	@InvtAcct VarChar(10),
	@InvtID VarChar(30),
	@InvtMult SmallInt,
	@InvtSub VarChar(24),
	@JrnlType VarChar(3),
	@KitID VarChar(30),
	@LayerType Char(1),
	@LineID Integer,
	@LineNbr SmallInt,
	@LineRef VarChar(5),
	@LotSerCntr SmallInt,
	@LUpd_DateTime SmallDateTime,
	@LUpd_Prog VarChar(8),
	@LUpd_User VarChar(10),
	@NoteID Integer,
	@OrigLineRef Char(5),
	@OvrhdAmt Float,
	@OvrhdFlag SmallInt,
	@PC_Flag VarChar(1),
	@PC_ID VarChar(20),
	@PC_Status VarChar(1),
	@PerEnt VarChar(6),
	@PerPost VarChar(6),
	@ProjectID VarChar(16),
	@Qty Float,
	@QtyUnCosted Float,
	@RcptDate SmallDateTime,
	@RcptNbr VarChar(15),
	@ReasonCd VarChar(6),
	@RefNbr VarChar(15),
	@Rlsed SmallInt,
	@S4Future01 VarChar(30),
	@S4Future02 VarChar(30),
	@S4Future03 Float,
	@S4Future04 Float,
	@S4Future05 Float,
	@S4Future06 Float,
	@S4Future07 SmallDateTime,
	@S4Future08 SmallDateTime,
	@S4Future09 Integer,
	@S4Future10 Integer,
	@S4Future11 VarChar(10),
	@S4Future12 VarChar(10),
	@ShipperCpnyID VarChar(10),
	@ShipperID VarChar(15),
	@ShipperLineRef VarChar(5),
	@ShortQty Float,
	@SiteID VarChar(10),
	@SpecificCostID VarChar(25),
	@Sub VarChar(24),
	@TaskID VarChar(32),
	@ToSiteID VarChar(10),
	@ToWhseLoc VarChar(10),
	@TranAmt Float,
	@TranDate SmallDateTime,
	@TranDesc VarChar(30),
	@TranType VarChar(2),
	@UnitDesc VarChar(6),
	@UnitMultDiv VarChar(1),
	@UnitPrice Float,
	@User1 VarChar(30),
	@User2 VarChar(30),
	@User3 Float,
	@User4 Float,
	@User5 VarChar(10),
	@User6 VarChar(10),
	@User7 SmallDateTime,
	@User8 SmallDateTime,
	@WhseLoc VarChar(10)
As
	Set	NoCount On

	Insert	INTran
		(
		Acct, AcctDist, ARLineID, ARLineRef, BatNbr,
		BMICuryID, BMIEffDate, BMIExtCost, BMIMultDiv, BMIRate,
		BMIRtTp, BMITranAmt, BMIUnitPrice, CmmnPct, CnvFact,
		COGSAcct, COGSSub, CostType, CpnyID, Crtd_DateTime,
		Crtd_Prog, Crtd_User, DrCr, Excpt, ExtCost,
		ExtRefNbr, FiscYr, ID, InsuffQty, InvtAcct,
		InvtID, InvtMult, InvtSub, JrnlType, KitID, LayerType,
		LineID, LineNbr, LineRef, LotSerCntr, LUpd_DateTime,
		LUpd_Prog, LUpd_User, NoteID, OrigLineRef, OvrhdAmt, OvrhdFlag,
		PC_Flag, PC_ID, PC_Status, PerEnt, PerPost,
		ProjectID, Qty, QtyUnCosted, RcptDate, RcptNbr,
		ReasonCd, RefNbr, Rlsed, S4Future01, S4Future02,
		S4Future03, S4Future04, S4Future05, S4Future06, S4Future07,
		S4Future08, S4Future09, S4Future10, S4Future11, S4Future12,
		ShipperCpnyID, ShipperID, ShipperLineRef,
		ShortQty, SiteID, SlsperID, SpecificCostID, Sub,
		TaskID, ToSiteID, ToWhseLoc, TranAmt, TranDate,
		TranDesc, TranType, UnitDesc, UnitMultDiv, UnitPrice,
		User1, User2, User3, User4, User5,
		User6, User7, User8, WhseLoc
		)
		Values
		(
		@Acct, @AcctDist, @ARLineID, @ARLineRef, @BatNbr,
		@BMICuryID, @BMIEffDate, @BMIExtCost, @BMIMultDiv, @BMIRate,
		@BMIRtTp, @BMITranAmt, @BMIUnitPrice, @CmmnPct, @CnvFact,
		@COGSAcct, @COGSSub, @CostType, @CpnyID, @Crtd_DateTime,
		@Crtd_Prog, @Crtd_User, @DrCr, @Excpt, @ExtCost,
		@ExtRefNbr, @FiscYr, @ID, @InsuffQty, @InvtAcct,
		@InvtID, @InvtMult, @InvtSub, @JrnlType, @KitID, @LayerType,
		@LineID, @LineNbr, @LineRef, @LotSerCntr, @LUpd_DateTime,
		@LUpd_Prog, @LUpd_User, @NoteID, @OrigLineRef, @OvrhdAmt, @OvrhdFlag,
		@PC_Flag, @PC_ID, @PC_Status, @PerEnt, @PerPost,
		@ProjectID, @Qty, @QtyUnCosted, @RcptDate, @RcptNbr,
		@ReasonCd, @RefNbr, @Rlsed, @S4Future01, @S4Future02,
		@S4Future03, @S4Future04, @S4Future05, @S4Future06, @S4Future07,
		@S4Future08, @S4Future09, @S4Future10, @S4Future11, @S4Future12,
		@ShipperCpnyID,	@ShipperID, @ShipperLineRef,
		@ShortQty, @SiteID, '', @SpecificCostID, @Sub,
		@TaskID, @ToSiteID, @ToWhseLoc, @TranAmt, @TranDate,
		@TranDesc, @TranType, @UnitDesc, @UnitMultDiv, @UnitPrice,
		@User1, @User2, @User3, @User4, @User5,
		@User6, @User7, @User8, @WhseLoc
		)



GO
GRANT CONTROL
    ON OBJECT::[dbo].[SCM_Insert_INTran] TO [MSDSL]
    AS [dbo];

