 CREATE proc EDUOMFP_Decpl @PARM1 VARCHAR(3),@PARM2 VARCHAR(6) AS
SELECT Decpl FROM EDUOMFP WHERE DIMENSION = @PARM1 AND UOM LIKE @PARM2 ORDER BY DIMENSION,UOM



GO
GRANT CONTROL
    ON OBJECT::[dbo].[EDUOMFP_Decpl] TO [MSDSL]
    AS [dbo];

