CREATE PROC [dbo].[pClearGFTablesSpecificFarm]
	-- Stored procedures used by the PigChamp GF Data extract application
	-- Initial creation date 1/26/04 - TJones

	@PCFarmID varchar(8)
	As
	SET NOCOUNT ON

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroup WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupCarcassQualityEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupEndEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupFeedEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupFinancialEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupInventoryEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupGradeEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.PCGroupGeneralEvent WHERE PCFarmID = @PCFarmID
	COMMIT TRANSACTION

	SET NOCOUNT OFF

GO
GRANT CONTROL
    ON OBJECT::[dbo].[pClearGFTablesSpecificFarm] TO [MSDSL]
    AS [dbo];

