CREATE PROCEDURE WS_PJPENTEx_DELETE
@PJT_ENTITY char(32), @PROJECT char(16), @tstamp timestamp
AS
BEGIN
DELETE FROM [PJPENTEX]
WHERE [PJT_ENTITY] = @PJT_ENTITY AND 
[PROJECT] = @PROJECT AND 
[tstamp] = @tstamp;
END
