 CREATE PROC EDUOMFP_AllDMG
	@PARM1 VARCHAR(3),
	@PARM2 VARCHAR(6)
AS
	SELECT *
	FROM EDUOMFP
	WHERE 	Dimension LIKE @PARM1
		AND UOM LIKE @PARM2
	ORDER BY Dimension, UOM



GO
GRANT CONTROL
    ON OBJECT::[dbo].[EDUOMFP_AllDMG] TO [MSDSL]
    AS [dbo];

