
            CREATE PROCEDURE WS_PJExpDet_INSERT
            @amt_employ float,
            @amt_company float,
            @amt_tax float,
            @CpnyId_chrg char(10),
            @CpnyId_home char(10),
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @CuryId char(4),
            @CuryMultDiv char(1),
            @CuryRate float,
            @curyratetype char(6),
            @CuryTranamt float,
            @desc_detail char(40),
            @docnbr char(10),
            @exp_date smalldatetime,
            @exp_type char(4),
            @gl_acct char(10),
            @gl_subacct char(24),
            @linenbr smallint,
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @NoteId int,
            @payment_cd char(4),
            @pjt_entity char(32),
            @project char(16),
            @rate float,
            @status char(1),
            @tax_amount float,
            @tax_flag char(1),
            @taxcatid char(10),
            @taxid char(10),
            @taxitembasis float,
            @td_id01 char(30),
            @td_id02 char(30),
            @td_id03 char(16),
            @td_id04 char(16),
            @td_id05 char(4),
            @td_id06 float,
            @td_id07 float,
            @td_id08 smalldatetime,
            @td_id09 smalldatetime,
            @td_id10 int,
            @td_id11 char(30),
            @td_id12 char(20),
            @td_id13 char(10),
            @td_id14 char(4),
            @td_id15 float,
            @unit_of_measure char(10),
            @units float,
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float,
            @vendor_num char(15)
            AS
            BEGIN
            INSERT INTO [PJExpDet]
            ([amt_employ],
            [amt_company],
            [amt_tax],
            [CpnyId_chrg],
            [CpnyId_home],
            [crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [CuryId],
            [CuryMultDiv],
            [CuryRate],
            [curyratetype],
            [CuryTranamt],
            [desc_detail],
            [docnbr],
            [exp_date],
            [exp_type],
            [gl_acct],
            [gl_subacct],
            [linenbr],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [NoteId],
            [payment_cd],
            [pjt_entity],
            [project],
            [rate],
            [status],
            [tax_amount],
            [tax_flag],
            [taxcatid],
            [taxid],
            [taxitembasis],
            [td_id01],
            [td_id02],
            [td_id03],
            [td_id04],
            [td_id05],
            [td_id06],
            [td_id07],
            [td_id08],
            [td_id09],
            [td_id10],
            [td_id11],
            [td_id12],
            [td_id13],
            [td_id14],
            [td_id15],
            [unit_of_measure],
            [units],
            [user1],
            [user2],
            [user3],
            [user4],
            [vendor_num])
            VALUES
            (@amt_employ,
            @amt_company,
            @amt_tax,
            @CpnyId_chrg,
            @CpnyId_home,
            @crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @CuryId,
            @CuryMultDiv,
            @CuryRate,
            @curyratetype,
            @CuryTranamt,
            @desc_detail,
            @docnbr,
            @exp_date,
            @exp_type,
            @gl_acct,
            @gl_subacct,
            @linenbr,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @NoteId,
            @payment_cd,
            @pjt_entity,
            @project,
            @rate,
            @status,
            @tax_amount,
            @tax_flag,
            @taxcatid,
            @taxid,
            @taxitembasis,
            @td_id01,
            @td_id02,
            @td_id03,
            @td_id04,
            @td_id05,
            @td_id06,
            @td_id07,
            @td_id08,
            @td_id09,
            @td_id10,
            @td_id11,
            @td_id12,
            @td_id13,
            @td_id14,
            @td_id15,
            @unit_of_measure,
            @units,
            @user1,
            @user2,
            @user3,
            @user4,
            @vendor_num);
            End
            

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_PJExpDet_INSERT] TO [MSDSL]
    AS [dbo];

