CREATE PROCEDURE WS_SOLine_INSERT
            @AlternateID char(30),
            @AltIDType char(1),
            @AutoPO smallint,
            @AutoPOVendID char(15),
            @BlktOrdLineRef char(5),
            @BlktOrdQty float,
            @BMICost float,
            @BMICuryID char(4),
            @BMIEffDate smalldatetime,
            @BMIExtPriceInvc float,
            @BMIMultDiv char(1),
            @BMIRate float,
            @BMIRtTp char(6),
            @BMISlsPrice float,
            @BoundToWO smallint,
            @CancelDate smalldatetime,
            @ChainDisc char(15),
            @CmmnPct float,
            @CnvFact float,
            @COGSAcct char(10),
            @COGSSub char(24),
            @CommCost float,
            @Cost float,
            @CpnyID char(10),
            @Crtd_DateTime smalldatetime,
            @Crtd_Prog char(8),
            @Crtd_User char(10),
            @CuryCommCost float,
            @CuryCost float,
            @CuryListPrice float,
            @CurySlsPrice float,
            @CurySlsPriceOrig float,
            @CuryTotCommCost float,
            @CuryTotCost float,
            @CuryTotOrd float,
            @Descr char(60),
            @DescrLang char(30),
            @DiscAcct char(10),
            @DiscPct float,
            @DiscPrcType char(1),
            @DiscSub char(24),
            @Disp char(3),
            @DropShip smallint,
            @InclForecastUsageClc smallint,
            @InspID char(2),
            @InspNoteID int,
            @InvAcct char(10),
            @InvSub char(24),
            @InvtID char(30),
            @IRDemand smallint,
            @IRInvtID char(30),
            @IRProcessed smallint,
            @IRSiteID char(10),
            @ItemGLClassID char(4),
            @KitComponent smallint,
            @LineNbr smallint,
            @LineRef char(5),
            @ListPrice float,
            @LotSerialReq smallint,
            @LUpd_DateTime smalldatetime,
            @LUpd_Prog char(8),
            @LUpd_User char(10),
            @ManualCost smallint,
            @ManualPrice smallint,
            @NoteId int,
            @OrdNbr char(15),
            @OrigINBatNbr char(10),
            @OrigInvcNbr char(15),
            @OrigInvtID char(30),
            @OrigShipperCnvFact float,
            @OrigShipperID char(15),
            @OrigShipperLineQty float,
            @OrigShipperLineRef char(5),
            @OrigShipperUnitDesc char(6),
            @OrigShipperMultDiv char(1),
            @PC_Status char(1),
            @ProjectID char(16),
            @PromDate smalldatetime,
            @QtyBO float,
            @QtyCloseShip float,
            @QtyFuture float,
            @QtyOpenShip float,
            @QtyOrd float,
            @QtyShip float,
            @QtyToInvc float,
            @ReasonCd char(6),
            @RebateID char(10),
            @ReqDate smalldatetime,
            @S4Future01 char(30),
            @S4Future02 char(30),
            @S4Future03 float,
            @S4Future04 float,
            @S4Future05 float,
            @S4Future06 float,
            @S4Future07 smalldatetime,
            @S4Future08 smalldatetime,
            @S4Future09 int,
            @S4Future10 int,
            @S4Future11 char(10),
            @S4Future12 char(10),
            @SalesPriceID char(15),
            @Sample smallint,
            @SchedCntr smallint,
            @Service smallint,
            @ShipWght float,
            @SiteID char(10),
            @SlsAcct char(10),
            @SlsperID char(10),
            @SlsPrice float,
            @SlsPriceID char(15),
            @SlsPriceOrig float,
            @SlsSub char(24),
            @SplitLots smallint,
            @Status char(1),
            @TaskID char(32),
            @Taxable smallint,
            @TaxCat char(10),
            @TotCommCost float,
            @TotCost float,
            @TotOrd float,
            @TotShipWght float,
            @UnitDesc char(6),
            @UnitMultDiv char(1),
            @User1 char(30),
            @User10 smalldatetime,
            @User2 char(30),
            @User3 char(30),
            @User4 char(30),
            @User5 float,
            @User6 float,
            @User7 char(10),
            @User8 char(10),
            @User9 smalldatetime
            AS
            BEGIN
            INSERT INTO [SOLine]
            ([AlternateID],
            [AltIDType],
            [AutoPO],
            [AutoPOVendID],
            [BlktOrdLineRef],
            [BlktOrdQty],
            [BMICost],
            [BMICuryID],
            [BMIEffDate],
            [BMIExtPriceInvc],
            [BMIMultDiv],
            [BMIRate],
            [BMIRtTp],
            [BMISlsPrice],
            [BoundToWO],
            [CancelDate],
            [ChainDisc],
            [CmmnPct],
            [CnvFact],
            [COGSAcct],
            [COGSSub],
            [CommCost],
            [Cost],
            [CpnyID],
            [Crtd_DateTime],
            [Crtd_Prog],
            [Crtd_User],
            [CuryCommCost],
            [CuryCost],
            [CuryListPrice],
            [CurySlsPrice],
            [CurySlsPriceOrig],
            [CuryTotCommCost],
            [CuryTotCost],
            [CuryTotOrd],
            [Descr],
            [DescrLang],
            [DiscAcct],
            [DiscPct],
            [DiscPrcType],
            [DiscSub],
            [Disp],
            [DropShip],
            [InclForecastUsageClc],
            [InspID],
            [InspNoteID],
            [InvAcct],
            [InvSub],
            [InvtID],
            [IRDemand],
            [IRInvtID],
            [IRProcessed],
            [IRSiteID],
            [ItemGLClassID],
            [KitComponent],
            [LineNbr],
            [LineRef],
            [ListPrice],
            [LotSerialReq],
            [LUpd_DateTime],
            [LUpd_Prog],
            [LUpd_User],
            [ManualCost],
            [ManualPrice],
            [NoteId],
            [OrdNbr],
            [OrigINBatNbr],
            [OrigInvcNbr],
            [OrigInvtID],
            [OrigShipperCnvFact],
            [OrigShipperID],
            [OrigShipperLineQty],
            [OrigShipperLineRef],
            [OrigShipperUnitDesc],
            [OrigShipperMultDiv],
            [PC_Status],
            [ProjectID],
            [PromDate],
            [QtyBO],
            [QtyCloseShip],
            [QtyFuture],
            [QtyOpenShip],
            [QtyOrd],
            [QtyShip],
            [QtyToInvc],
            [ReasonCd],
            [RebateID],
            [ReqDate],
            [S4Future01],
            [S4Future02],
            [S4Future03],
            [S4Future04],
            [S4Future05],
            [S4Future06],
            [S4Future07],
            [S4Future08],
            [S4Future09],
            [S4Future10],
            [S4Future11],
            [S4Future12],
            [SalesPriceID],
            [Sample],
            [SchedCntr],
            [Service],
            [ShipWght],
            [SiteID],
            [SlsAcct],
            [SlsperID],
            [SlsPrice],
            [SlsPriceID],
            [SlsPriceOrig],
            [SlsSub],
            [SplitLots],
            [Status],
            [TaskID],
            [Taxable],
            [TaxCat],
            [TotCommCost],
            [TotCost],
            [TotOrd],
            [TotShipWght],
            [UnitDesc],
            [UnitMultDiv],
            [User1],
            [User10],
            [User2],
            [User3],
            [User4],
            [User5],
            [User6],
            [User7],
            [User8],
            [User9])
            VALUES
            (@AlternateID,
            @AltIDType,
            @AutoPO,
            @AutoPOVendID,
            @BlktOrdLineRef,
            @BlktOrdQty,
            @BMICost,
            @BMICuryID,
            @BMIEffDate,
            @BMIExtPriceInvc,
            @BMIMultDiv,
            @BMIRate,
            @BMIRtTp,
            @BMISlsPrice,
            @BoundToWO,
            @CancelDate,
            @ChainDisc,
            @CmmnPct,
            @CnvFact,
            @COGSAcct,
            @COGSSub,
            @CommCost,
            @Cost,
            @CpnyID,
            @Crtd_DateTime,
            @Crtd_Prog,
            @Crtd_User,
            @CuryCommCost,
            @CuryCost,
            @CuryListPrice,
            @CurySlsPrice,
            @CurySlsPriceOrig,
            @CuryTotCommCost,
            @CuryTotCost,
            @CuryTotOrd,
            @Descr,
            @DescrLang,
            @DiscAcct,
            @DiscPct,
            @DiscPrcType,
            @DiscSub,
            @Disp,
            @DropShip,
            @InclForecastUsageClc,
            @InspID,
            @InspNoteID,
            @InvAcct,
            @InvSub,
            @InvtID,
            @IRDemand,
            @IRInvtID,
            @IRProcessed,
            @IRSiteID,
            @ItemGLClassID,
            @KitComponent,
            @LineNbr,
            @LineRef,
            @ListPrice,
            @LotSerialReq,
            @LUpd_DateTime,
            @LUpd_Prog,
            @LUpd_User,
            @ManualCost,
            @ManualPrice,
            @NoteId,
            @OrdNbr,
            @OrigINBatNbr,
            @OrigInvcNbr,
            @OrigInvtID,
            @OrigShipperCnvFact,
            @OrigShipperID,
            @OrigShipperLineQty,
            @OrigShipperLineRef,
            @OrigShipperUnitDesc,
            @OrigShipperMultDiv,
            @PC_Status,
            @ProjectID,
            @PromDate,
            @QtyBO,
            @QtyCloseShip,
            @QtyFuture,
            @QtyOpenShip,
            @QtyOrd,
            @QtyShip,
            @QtyToInvc,
            @ReasonCd,
            @RebateID,
            @ReqDate,
            @S4Future01,
            @S4Future02,
            @S4Future03,
            @S4Future04,
            @S4Future05,
            @S4Future06,
            @S4Future07,
            @S4Future08,
            @S4Future09,
            @S4Future10,
            @S4Future11,
            @S4Future12,
            @SalesPriceID,
            @Sample,
            @SchedCntr,
            @Service,
            @ShipWght,
            @SiteID,
            @SlsAcct,
            @SlsperID,
            @SlsPrice,
            @SlsPriceID,
            @SlsPriceOrig,
            @SlsSub,
            @SplitLots,
            @Status,
            @TaskID,
            @Taxable,
            @TaxCat,
            @TotCommCost,
            @TotCost,
            @TotOrd,
            @TotShipWght,
            @UnitDesc,
            @UnitMultDiv,
            @User1,
            @User10,
            @User2,
            @User3,
            @User4,
            @User5,
            @User6,
            @User7,
            @User8,
            @User9);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_SOLine_INSERT] TO [MSDSL]
    AS [dbo];

