CREATE PROCEDURE WS_CustomerEDI_INSERT
	@AgreeNbrFlg smallint,
	@ApptNbrFlg smallint,
	@ArrivalDateFlg smallint,
	@BatchNbrFlg smallint,
	@BidNbrFlg smallint,
	@BOLFlg smallint,
	@BOLNoteID int,
	@BOLRptFormat char(30),
	@BuyerReqd smallint,
	@CertID char(2),
	@CheckShipToID smallint,
	@COGSAcct char(10),
	@COGSSub char(31),
	@ContractNbrFlg smallint,
	@ContTrackLevel char(10),
	@CreditMgrID char(10),
	@CreditRule char(2),
	@CrossDockFlg smallint,
	@Crtd_DateTime smalldatetime,
	@Crtd_Prog char(8),
	@Crtd_User char(10),
	@CustCommClassID char(10),
	@CustID char(15),
	@CustItemReqd smallint,
	@DeliveryDateFlg smallint,
	@DeptFlg smallint,
	@DfltBuyerID char(10),
	@DiscAcct char(10),
	@DiscSub char(31),
	@DivFlg smallint,
	@EDSOUser10Flg smallint,
	@EDSOUser1Flg smallint,
	@EDSOUser2Flg smallint,
	@EDSOUser3Flg smallint,
	@EDSOUser4Flg smallint,
	@EDSOUser5Flg smallint,
	@EDSOUser6Flg smallint,
	@EDSOUser7Flg smallint,
	@EDSOUser8Flg smallint,
	@EDSOUser9Flg smallint,
	@EquipNbrFlg smallint,
	@FOBFlg smallint,
	@FOBID char(15),
	@FOBLocQualFlg smallint,
	@FOBTranTypeFlg smallint,
	@FrtAcct char(10),
	@FrtAllowCd char(30),
	@FrtDiscCd char(30),
	@FrtSub char(31),
	@GeoCode char(10),
	@GLClassID char(4),
	@GracePer smallint,
	@GSA smallint,
	@HeightFlg smallint,
	@ImpConvMeth char(2),
	@InternalNoteID int,
	@IntVendorNbr char(30),
	@IntVendorNbrFlg smallint,
	@InvcNoteID int,
	@LabelReqd smallint,
	@LenFlg smallint,
	@LineItemEDIDiscCode char(5),
	@LUpd_DateTime smalldatetime,
	@LUpd_Prog char(8),
	@LUpd_User char(10),
	@MajorAccount char(15),
	@ManNoteID int,
	@MinOrder float,
	@MinWt float,
	@MiscAcct char(10),
	@MiscSub char(31),
	@MultiDestMeth char(3),
	@NbrCartonsFlg smallint,
	@NoteID int,
	@OrigSourceID char(10),
	@OutBndTemplate char(20),
	@PlanDateFlg smallint,
	@POReqd smallint,
	@PROFlg smallint,
	@PromoNbrFlg smallint,
	@PSNoteID int,
	@PTNoteID int,
	@QuoteNbrFlg smallint,
	@RegionID char(10),
	@RequestDateFlg smallint,
	@S4Future01 char(30),
	@S4Future02 char(30),
	@S4Future03 float,
	@S4Future04 float,
	@S4Future05 float,
	@S4Future06 float,
	@S4Future07 smalldatetime,
	@S4Future08 smalldatetime,
	@S4Future09 int,
	@S4Future10 int,
	@S4Future11 char(10),
	@S4Future12 char(10),
	@SalespersonFlg smallint,
	@SalesRegionFlg smallint,
	@SCACFlg smallint,
	@ScheduledDateFlg smallint,
	@SDQMarkForFlg smallint,
	@SendZeroInvc smallint,
	@SepDestOrd smallint,
	@ShipDateFlg smallint,
	@ShipmentLabel char(30),
	@ShipMthPayFlg smallint,
	@ShipNBDateFlg smallint,
	@ShipNLDateFlg smallint,
	@ShipToRefNbrFlg smallint,
	@ShipViaFlg smallint,
	@ShipWeekOfFlg smallint,
	@SingleContainer smallint,
	@SiteID char(10),
	@SlsAcct char(10),
	@SlsSub char(31),
	@SOTypeID char(4),
	@SOUser10Flg smallint,
	@SOUser1Flg smallint,
	@SOUser2Flg smallint,
	@SOUser3Flg smallint,
	@SOUser4Flg smallint,
	@SOUser5Flg smallint,
	@SOUser6Flg smallint,
	@SOUser7Flg smallint,
	@SOUser8Flg smallint,
	@SOUser9Flg smallint,
	@SplitPartialLineDisc smallint,
	@SubNbrFlg smallint,
	@SubstOK smallint,
	@TerritoryID char(10),
	@TrackingNbrFlg smallint,
	@UseEDIPrice smallint,
	@User1 char(30),
	@User10 smalldatetime,
	@User2 char(30),
	@User3 char(30),
	@User4 char(30),
	@User5 float,
	@User6 float,
	@User7 char(10),
	@User8 char(10),
	@User9 smalldatetime,
	@UserNoteID1 int,
	@UserNoteID2 int,
	@UserNoteID3 int,
	@VolumeFlg smallint,
	@WebSite char(40),
	@WeightFlg smallint,
	@WholeOrdEDIDiscCode char(5),
	@WidthFlg smallint
	AS
	BEGIN
	INSERT INTO [CustomerEDI]
	([AgreeNbrFlg],
	[ApptNbrFlg],
	[ArrivalDateFlg],
	[BatchNbrFlg],
	[BidNbrFlg],
	[BOLFlg],
	[BOLNoteID],
	[BOLRptFormat],
	[BuyerReqd],
	[CertID],
	[CheckShipToID],
	[COGSAcct],
	[COGSSub],
	[ContractNbrFlg],
	[ContTrackLevel],
	[CreditMgrID],
	[CreditRule],
	[CrossDockFlg],
	[Crtd_DateTime],
	[Crtd_Prog],
	[Crtd_User],
	[CustCommClassID],
	[CustID],
	[CustItemReqd],
	[DeliveryDateFlg],
	[DeptFlg],
	[DfltBuyerID],
	[DiscAcct],
	[DiscSub],
	[DivFlg],
	[EDSOUser10Flg],
	[EDSOUser1Flg],
	[EDSOUser2Flg],
	[EDSOUser3Flg],
	[EDSOUser4Flg],
	[EDSOUser5Flg],
	[EDSOUser6Flg],
	[EDSOUser7Flg],
	[EDSOUser8Flg],
	[EDSOUser9Flg],
	[EquipNbrFlg],
	[FOBFlg],
	[FOBID],
	[FOBLocQualFlg],
	[FOBTranTypeFlg],
	[FrtAcct],
	[FrtAllowCd],
	[FrtDiscCd],
	[FrtSub],
	[GeoCode],
	[GLClassID],
	[GracePer],
	[GSA],
	[HeightFlg],
	[ImpConvMeth],
	[InternalNoteID],
	[IntVendorNbr],
	[IntVendorNbrFlg],
	[InvcNoteID],
	[LabelReqd],
	[LenFlg],
	[LineItemEDIDiscCode],
	[LUpd_DateTime],
	[LUpd_Prog],
	[LUpd_User],
	[MajorAccount],
	[ManNoteID],
	[MinOrder],
	[MinWt],
	[MiscAcct],
	[MiscSub],
	[MultiDestMeth],
	[NbrCartonsFlg],
	[NoteID],
	[OrigSourceID],
	[OutBndTemplate],
	[PlanDateFlg],
	[POReqd],
	[PROFlg],
	[PromoNbrFlg],
	[PSNoteID],
	[PTNoteID],
	[QuoteNbrFlg],
	[RegionID],
	[RequestDateFlg],
	[S4Future01],
	[S4Future02],
	[S4Future03],
	[S4Future04],
	[S4Future05],
	[S4Future06],
	[S4Future07],
	[S4Future08],
	[S4Future09],
	[S4Future10],
	[S4Future11],
	[S4Future12],
	[SalespersonFlg],
	[SalesRegionFlg],
	[SCACFlg],
	[ScheduledDateFlg],
	[SDQMarkForFlg],
	[SendZeroInvc],
	[SepDestOrd],
	[ShipDateFlg],
	[ShipmentLabel],
	[ShipMthPayFlg],
	[ShipNBDateFlg],
	[ShipNLDateFlg],
	[ShipToRefNbrFlg],
	[ShipViaFlg],
	[ShipWeekOfFlg],
	[SingleContainer],
	[SiteID],
	[SlsAcct],
	[SlsSub],
	[SOTypeID],
	[SOUser10Flg],
	[SOUser1Flg],
	[SOUser2Flg],
	[SOUser3Flg],
	[SOUser4Flg],
	[SOUser5Flg],
	[SOUser6Flg],
	[SOUser7Flg],
	[SOUser8Flg],
	[SOUser9Flg],
	[SplitPartialLineDisc],
	[SubNbrFlg],
	[SubstOK],
	[TerritoryID],
	[TrackingNbrFlg],
	[UseEDIPrice],
	[User1],
	[User10],
	[User2],
	[User3],
	[User4],
	[User5],
	[User6],
	[User7],
	[User8],
	[User9],
	[UserNoteID1],
	[UserNoteID2],
	[UserNoteID3],
	[VolumeFlg],
	[WebSite],
	[WeightFlg],
	[WholeOrdEDIDiscCode],
	[WidthFlg])
	VALUES
	(@AgreeNbrFlg,
	@ApptNbrFlg,
	@ArrivalDateFlg,
	@BatchNbrFlg,
	@BidNbrFlg,
	@BOLFlg,
	@BOLNoteID,
	@BOLRptFormat,
	@BuyerReqd,
	@CertID,
	@CheckShipToID,
	@COGSAcct,
	@COGSSub,
	@ContractNbrFlg,
	@ContTrackLevel,
	@CreditMgrID,
	@CreditRule,
	@CrossDockFlg,
	@Crtd_DateTime,
	@Crtd_Prog,
	@Crtd_User,
	@CustCommClassID,
	@CustID,
	@CustItemReqd,
	@DeliveryDateFlg,
	@DeptFlg,
	@DfltBuyerID,
	@DiscAcct,
	@DiscSub,
	@DivFlg,
	@EDSOUser10Flg,
	@EDSOUser1Flg,
	@EDSOUser2Flg,
	@EDSOUser3Flg,
	@EDSOUser4Flg,
	@EDSOUser5Flg,
	@EDSOUser6Flg,
	@EDSOUser7Flg,
	@EDSOUser8Flg,
	@EDSOUser9Flg,
	@EquipNbrFlg,
	@FOBFlg,
	@FOBID,
	@FOBLocQualFlg,
	@FOBTranTypeFlg,
	@FrtAcct,
	@FrtAllowCd,
	@FrtDiscCd,
	@FrtSub,
	@GeoCode,
	@GLClassID,
	@GracePer,
	@GSA,
	@HeightFlg,
	@ImpConvMeth,
	@InternalNoteID,
	@IntVendorNbr,
	@IntVendorNbrFlg,
	@InvcNoteID,
	@LabelReqd,
	@LenFlg,
	@LineItemEDIDiscCode,
	@LUpd_DateTime,
	@LUpd_Prog,
	@LUpd_User,
	@MajorAccount,
	@ManNoteID,
	@MinOrder,
	@MinWt,
	@MiscAcct,
	@MiscSub,
	@MultiDestMeth,
	@NbrCartonsFlg,
	@NoteID,
	@OrigSourceID,
	@OutBndTemplate,
	@PlanDateFlg,
	@POReqd,
	@PROFlg,
	@PromoNbrFlg,
	@PSNoteID,
	@PTNoteID,
	@QuoteNbrFlg,
	@RegionID,
	@RequestDateFlg,
	@S4Future01,
	@S4Future02,
	@S4Future03,
	@S4Future04,
	@S4Future05,
	@S4Future06,
	@S4Future07,
	@S4Future08,
	@S4Future09,
	@S4Future10,
	@S4Future11,
	@S4Future12,
	@SalespersonFlg,
	@SalesRegionFlg,
	@SCACFlg,
	@ScheduledDateFlg,
	@SDQMarkForFlg,
	@SendZeroInvc,
	@SepDestOrd,
	@ShipDateFlg,
	@ShipmentLabel,
	@ShipMthPayFlg,
	@ShipNBDateFlg,
	@ShipNLDateFlg,
	@ShipToRefNbrFlg,
	@ShipViaFlg,
	@ShipWeekOfFlg,
	@SingleContainer,
	@SiteID,
	@SlsAcct,
	@SlsSub,
	@SOTypeID,
	@SOUser10Flg,
	@SOUser1Flg,
	@SOUser2Flg,
	@SOUser3Flg,
	@SOUser4Flg,
	@SOUser5Flg,
	@SOUser6Flg,
	@SOUser7Flg,
	@SOUser8Flg,
	@SOUser9Flg,
	@SplitPartialLineDisc,
	@SubNbrFlg,
	@SubstOK,
	@TerritoryID,
	@TrackingNbrFlg,
	@UseEDIPrice,
	@User1,
	@User10,
	@User2,
	@User3,
	@User4,
	@User5,
	@User6,
	@User7,
	@User8,
	@User9,
	@UserNoteID1,
	@UserNoteID2,
	@UserNoteID3,
	@VolumeFlg,
	@WebSite,
	@WeightFlg,
	@WholeOrdEDIDiscCode,
	@WidthFlg);
	END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_CustomerEDI_INSERT] TO [MSDSL]
    AS [dbo];

