CREATE PROCEDURE WS_APDoc_INSERT
     @Acct char(10), @AddlCost smallint, @ApplyAmt float, @ApplyDate smalldatetime, @ApplyRefNbr char(10), @BatNbr char(10), @BatSeq int,
     @BWAmt float, @CashAcct char(10), @CashSub char(24), @ClearAmt float, @ClearDate smalldatetime, @CodeType char(4), @CpnyID char(10),
     @Crtd_DateTime smalldatetime, @Crtd_Prog char(8), @Crtd_User char(10), @CurrentNbr smallint, @CuryBWAmt float, @CuryDiscBal float, @CuryDiscTkn float,
     @CuryDocBal float, @CuryEffDate smalldatetime, @CuryId char(4), @CuryMultDiv char(1), @CuryOrigDocAmt float, @CuryPmtAmt float, @CuryRate float,
     @CuryRateType char(6), @CuryTaxTot00 float, @CuryTaxTot01 float, @CuryTaxTot02 float, @CuryTaxTot03 float, @CuryTxblTot00 float, @CuryTxblTot01 float,
     @CuryTxblTot02 float, @CuryTxblTot03 float, @Cycle smallint, @DfltDetail smallint, @DirectDeposit char(1), @DiscBal float, @DiscDate smalldatetime,
     @DiscTkn float, @Doc1099 smallint, @DocBal float, @DocClass char(1), @DocDate smalldatetime, @DocDesc char(30), @DocType char(2),
     @DueDate smalldatetime, @Econfirm char(18), @Estatus char(1), @ExcludeFreight char(1), @FreightAmt float, @InstallNbr smallint, @InvcDate smalldatetime,
     @InvcNbr char(15), @LCCode char(10), @LineCntr int, @LUpd_DateTime smalldatetime, @LUpd_Prog char(8), @LUpd_User char(10), @MasterDocNbr char(10),
     @NbrCycle smallint, @NoteID int, @OpenDoc smallint, @OrigDocAmt float, @PayDate smalldatetime, @PayHoldDesc char(30), @PC_Status char(1),
     @PerClosed char(6), @PerEnt char(6), @PerPost char(6), @PmtAmt float, @PmtID char(10), @PmtMethod char(1), @PONbr char(10),
     @PrePay_RefNbr char(10), @ProjectID char(16), @RefNbr char(10), @Retention smallint, @RGOLAmt float, @Rlsed smallint,
     @S4Future01 char(30), @S4Future02 char(30), @S4Future03 float, @S4Future04 float, @S4Future05 float, @S4Future06 float, @S4Future07 smalldatetime,
     @S4Future08 smalldatetime, @S4Future09 int, @S4Future10 int, @S4Future11 char(10), @S4Future12 char(10), @Selected smallint, @Status char(1),
     @Sub char(24), @Subcontract char(16), @TaxCntr00 smallint, @TaxCntr01 smallint, @TaxCntr02 smallint, @TaxCntr03 smallint, @TaxId00 char(10),
     @TaxId01 char(10), @TaxId02 char(10), @TaxId03 char(10), @TaxTot00 float, @TaxTot01 float, @TaxTot02 float, @TaxTot03 float,
     @Terms char(2), @TxblTot00 float, @TxblTot01 float, @TxblTot02 float, @TxblTot03 float, @User1 char(30), @User2 char(30),
     @User3 float, @User4 float, @User5 char(10), @User6 char(10), @User7 smalldatetime, @User8 smalldatetime, @VendId char(15), @VendName char(60)
 AS
     BEGIN
      INSERT INTO [APDoc]
       ([Acct], [AddlCost], [ApplyAmt], [ApplyDate], [ApplyRefNbr], [BatNbr], [BatSeq],
        [BWAmt], [CashAcct], [CashSub], [ClearAmt], [ClearDate], [CodeType], [CpnyID],
        [Crtd_DateTime], [Crtd_Prog], [Crtd_User], [CurrentNbr], [CuryBWAmt], [CuryDiscBal], [CuryDiscTkn],
        [CuryDocBal], [CuryEffDate], [CuryId], [CuryMultDiv], [CuryOrigDocAmt], [CuryPmtAmt], [CuryRate],
        [CuryRateType], [CuryTaxTot00], [CuryTaxTot01], [CuryTaxTot02], [CuryTaxTot03], [CuryTxblTot00], [CuryTxblTot01],
        [CuryTxblTot02], [CuryTxblTot03], [Cycle], [DfltDetail], [DirectDeposit], [DiscBal], [DiscDate],
        [DiscTkn], [Doc1099], [DocBal], [DocClass], [DocDate], [DocDesc], [DocType],
        [DueDate], [Econfirm], [Estatus], [ExcludeFreight], [FreightAmt], [InstallNbr], [InvcDate],
        [InvcNbr], [LCCode], [LineCntr], [LUpd_DateTime], [LUpd_Prog], [LUpd_User], [MasterDocNbr],
        [NbrCycle], [NoteID], [OpenDoc], [OrigDocAmt], [PayDate], [PayHoldDesc], [PC_Status],
        [PerClosed], [PerEnt], [PerPost], [PmtAmt], [PmtID], [PmtMethod], [PONbr],
        [PrePay_RefNbr], [ProjectID], [RefNbr], [Retention], [RGOLAmt], [Rlsed],
        [S4Future01], [S4Future02], [S4Future03], [S4Future04], [S4Future05], [S4Future06], [S4Future07],
        [S4Future08], [S4Future09], [S4Future10], [S4Future11], [S4Future12], [Selected], [Status],
        [Sub], [Subcontract], [TaxCntr00], [TaxCntr01], [TaxCntr02], [TaxCntr03], [TaxId00],
        [TaxId01], [TaxId02], [TaxId03], [TaxTot00], [TaxTot01], [TaxTot02], [TaxTot03],
        [Terms], [TxblTot00], [TxblTot01], [TxblTot02], [TxblTot03], [User1], [User2],
        [User3], [User4], [User5], [User6], [User7], [User8], [VendId], [VendName])
      VALUES
       (@Acct, @AddlCost, @ApplyAmt, @ApplyDate, @ApplyRefNbr, @BatNbr, @BatSeq,
        @BWAmt, @CashAcct, @CashSub, @ClearAmt, @ClearDate, @CodeType, @CpnyID,
        @Crtd_DateTime, @Crtd_Prog, @Crtd_User, @CurrentNbr, @CuryBWAmt, @CuryDiscBal, @CuryDiscTkn,
        @CuryDocBal, @CuryEffDate, @CuryId, @CuryMultDiv, @CuryOrigDocAmt, @CuryPmtAmt, @CuryRate,
        @CuryRateType, @CuryTaxTot00, @CuryTaxTot01, @CuryTaxTot02, @CuryTaxTot03, @CuryTxblTot00, @CuryTxblTot01,
        @CuryTxblTot02, @CuryTxblTot03, @Cycle, @DfltDetail, @DirectDeposit, @DiscBal, @DiscDate,
        @DiscTkn, @Doc1099, @DocBal, @DocClass, @DocDate, @DocDesc, @DocType,
        @DueDate, @Econfirm, @Estatus, @ExcludeFreight, @FreightAmt, @InstallNbr, @InvcDate,
        @InvcNbr, @LCCode, @LineCntr, @LUpd_DateTime, @LUpd_Prog, @LUpd_User, @MasterDocNbr,
        @NbrCycle, @NoteID, @OpenDoc, @OrigDocAmt, @PayDate, @PayHoldDesc, @PC_Status,
        @PerClosed, @PerEnt, @PerPost, @PmtAmt, @PmtID, @PmtMethod, @PONbr,
        @PrePay_RefNbr, @ProjectID, @RefNbr, @Retention, @RGOLAmt, @Rlsed,
        @S4Future01, @S4Future02, @S4Future03, @S4Future04, @S4Future05, @S4Future06, @S4Future07,
        @S4Future08, @S4Future09, @S4Future10, @S4Future11, @S4Future12, @Selected, @Status,
        @Sub, @Subcontract, @TaxCntr00, @TaxCntr01, @TaxCntr02, @TaxCntr03, @TaxId00,
        @TaxId01, @TaxId02, @TaxId03, @TaxTot00, @TaxTot01, @TaxTot02, @TaxTot03,
        @Terms, @TxblTot00, @TxblTot01, @TxblTot02, @TxblTot03, @User1, @User2,
        @User3, @User4, @User5, @User6, @User7, @User8, @VendId, @VendName);
     END

