     CREATE PROCEDURE WS_processqueue_INSERT
            @ComputerName char(21),
            @CpnyID char(10),
            @CreateShipper smallint,
            @CreditInfoChanged smallint,
            @Crtd_DateTime smalldatetime,
            @Crtd_Prog char(8),
            @Crtd_User char(10),
            @CustID char(15),
            @InvtID char(30),
            @LUpd_DateTime smalldatetime,
            @LUpd_Prog char(8),
            @LUpd_User char(10),
            @MaintMode smallint,
            @NoteID int,
            @PlanEntireItem smallint,
            @POLineRef char(5),
            @PONbr char(10),
            @ProcessAt smalldatetime,
            @ProcessCPSOff smallint,
            @ProcessPriority smallint,
            @ProcessQueueID int,
            @ProcessType char(5),
            @S4Future01 char(30),
            @S4Future02 char(30),
            @S4Future03 float,
            @S4Future04 float,
            @S4Future05 float,
            @S4Future06 float,
            @S4Future07 smalldatetime,
            @S4Future08 smalldatetime,
            @S4Future09 int,
            @S4Future10 int,
            @S4Future11 char(10),
            @S4Future12 char(10),
            @SiteID char(10),
            @SOLineRef char(5),
            @SOOrdNbr char(15),
            @SOSchedRef char(5),
            @SOShipperID char(15),
            @SOShipperLineRef char(5),
            @User1 char(30),
            @User10 smalldatetime,
            @User2 char(30),
            @User3 char(30),
            @User4 char(30),
            @User5 float,
            @User6 float,
            @User7 char(10),
            @User8 char(10),
            @User9 smalldatetime,
            @WOLineRef char(5),
            @WONbr char(16),
            @WOTask char(32)
            AS
            BEGIN
            INSERT INTO [processqueue]
            ([ComputerName],
            [CpnyID],
            [CreateShipper],
            [CreditInfoChanged],
            [Crtd_DateTime],
            [Crtd_Prog],
            [Crtd_User],
            [CustID],
            [InvtID],
            [LUpd_DateTime],
            [LUpd_Prog],
            [LUpd_User],
            [MaintMode],
            [NoteID],
            [PlanEntireItem],
            [POLineRef],
            [PONbr],
            [ProcessAt],
            [ProcessCPSOff],
            [ProcessPriority],
            [ProcessQueueID],
            [ProcessType],
            [S4Future01],
            [S4Future02],
            [S4Future03],
            [S4Future04],
            [S4Future05],
            [S4Future06],
            [S4Future07],
            [S4Future08],
            [S4Future09],
            [S4Future10],
            [S4Future11],
            [S4Future12],
            [SiteID],
            [SOLineRef],
            [SOOrdNbr],
            [SOSchedRef],
            [SOShipperID],
            [SOShipperLineRef],
            [User1],
            [User10],
            [User2],
            [User3],
            [User4],
            [User5],
            [User6],
            [User7],
            [User8],
            [User9],
            [WOLineRef],
            [WONbr],
            [WOTask])
            VALUES
            (@ComputerName,
            @CpnyID,
            @CreateShipper,
            @CreditInfoChanged,
            @Crtd_DateTime,
            @Crtd_Prog,
            @Crtd_User,
            @CustID,
            @InvtID,
            @LUpd_DateTime,
            @LUpd_Prog,
            @LUpd_User,
            @MaintMode,
            @NoteID,
            @PlanEntireItem,
            @POLineRef,
            @PONbr,
            @ProcessAt,
            @ProcessCPSOff,
            @ProcessPriority,
            @ProcessQueueID,
            @ProcessType,
            @S4Future01,
            @S4Future02,
            @S4Future03,
            @S4Future04,
            @S4Future05,
            @S4Future06,
            @S4Future07,
            @S4Future08,
            @S4Future09,
            @S4Future10,
            @S4Future11,
            @S4Future12,
            @SiteID,
            @SOLineRef,
            @SOOrdNbr,
            @SOSchedRef,
            @SOShipperID,
            @SOShipperLineRef,
            @User1,
            @User10,
            @User2,
            @User3,
            @User4,
            @User5,
            @User6,
            @User7,
            @User8,
            @User9,
            @WOLineRef,
            @WONbr,
            @WOTask);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_processqueue_INSERT] TO [MSDSL]
    AS [dbo];

