 CREATE PROCEDURE WS_pjemppjt_INSERT
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @employee char(10),
            @ep_id01 char(30),
            @ep_id02 char(30),
            @ep_id03 char(16),
            @ep_id04 char(16),
            @ep_id05 char(4),
            @ep_id06 float,
            @ep_id07 float,
            @ep_id08 smalldatetime,
            @ep_id09 smalldatetime,
            @ep_id10 int,
            @effect_date smalldatetime,
            @labor_class_cd char(4),
            @labor_rate float,
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @noteid int,
            @project char(16),
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float
            AS
            BEGIN
            INSERT INTO [pjemppjt]
            ([crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [employee],
            [ep_id01],
            [ep_id02],
            [ep_id03],
            [ep_id04],
            [ep_id05],
            [ep_id06],
            [ep_id07],
            [ep_id08],
            [ep_id09],
            [ep_id10],
            [effect_date],
            [labor_class_cd],
            [labor_rate],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [noteid],
            [project],
            [user1],
            [user2],
            [user3],
            [user4])
            VALUES
            (@crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @employee,
            @ep_id01,
            @ep_id02,
            @ep_id03,
            @ep_id04,
            @ep_id05,
            @ep_id06,
            @ep_id07,
            @ep_id08,
            @ep_id09,
            @ep_id10,
            @effect_date,
            @labor_class_cd,
            @labor_rate,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @noteid,
            @project,
            @user1,
            @user2,
            @user3,
            @user4);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_pjemppjt_INSERT] TO [MSDSL]
    AS [dbo];

