CREATE PROCEDURE WSPObjExtension_INSERT
                @Crtd_DateTime smalldatetime,
                @Crtd_Prog char(8),
                @Crtd_User char(10),
                @DocOrSite char(1),
                @Lupd_DateTime smalldatetime,
                @Lupd_Prog char(8),
                @Lupd_User char(10),
                @S4Future01 char(30),
                @S4Future02 char(30),
                @S4Future03 float,
                @S4Future04 float,
                @S4Future05 float,
                @S4Future06 float,
                @S4Future07 smalldatetime,
                @S4Future08 smalldatetime,
                @S4Future09 int,
                @S4Future10 int,
                @S4Future11 char(10),
                @S4Future12 char(10),
                @Subsite char(150),
                @SLObjID char(60),
                @SLTypeID smallint,
                @User1 char(30),
                @User10 smalldatetime,
                @User2 char(30),
                @User3 char(30),
                @User4 char(30),
                @User5 float,
                @User6 float,
                @User7 char(10),
                @User8 char(10),
                @User9 smalldatetime,
                @UsersDocLibrary char(150),
                @UsersRootSiteURL char(150)
                AS
                BEGIN
                INSERT INTO [WSPObjExtension]
                ([Crtd_DateTime],
                [Crtd_Prog],
                [Crtd_User],
                [DocOrSite],
                [Lupd_DateTime],
                [Lupd_Prog],
                [Lupd_User],
                [S4Future01],
                [S4Future02],
                [S4Future03],
                [S4Future04],
                [S4Future05],
                [S4Future06],
                [S4Future07],
                [S4Future08],
                [S4Future09],
                [S4Future10],
                [S4Future11],
                [S4Future12],
                [Subsite],
                [SLObjID],
                [SLTypeID],
                [User1],
                [User10],
                [User2],
                [User3],
                [User4],
                [User5],
                [User6],
                [User7],
                [User8],
                [User9],
                [UsersDocLibrary],
                [UsersRootSiteURL])
                VALUES
                (@Crtd_DateTime,
                @Crtd_Prog,
                @Crtd_User,
                @DocOrSite,
                @Lupd_DateTime,
                @Lupd_Prog,
                @Lupd_User,
                @S4Future01,
                @S4Future02,
                @S4Future03,
                @S4Future04,
                @S4Future05,
                @S4Future06,
                @S4Future07,
                @S4Future08,
                @S4Future09,
                @S4Future10,
                @S4Future11,
                @S4Future12,
                @Subsite,
                @SLObjID,
                @SLTypeID,
                @User1,
                @User10,
                @User2,
                @User3,
                @User4,
                @User5,
                @User6,
                @User7,
                @User8,
                @User9,
                @UsersDocLibrary,
                @UsersRootSiteURL);
                End

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WSPObjExtension_INSERT] TO [MSDSL]
    AS [dbo];

