
            CREATE PROCEDURE WS_PJLabHdr_INSERT
            @Approver char(10),
            @BaseCuryId char(4),
            @CpnyId_home char(10),
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @CuryEffDate smalldatetime,
            @CuryId char(4),
            @CuryMultDiv char(1),
            @CuryRate float,
            @CuryRateType char(6),
            @docnbr char(10),
            @employee char(10),
            @fiscalno char(6),
            @le_id01 char(30),
            @le_id02 char(30),
            @le_id03 char(16),
            @le_id04 char(16),
            @le_id05 char(4),
            @le_id06 float,
            @le_id07 float,
            @le_id08 smalldatetime,
            @le_id09 smalldatetime,
            @le_id10 int,
            @le_key char(30),
            @le_status char(1),
            @le_type char(2),
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @noteid int,
            @period_num char(6),
            @pe_date smalldatetime,
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float,
            @week_num char(2)
            AS
            BEGIN
            INSERT INTO [PJLabHdr]
            ([Approver],
            [BaseCuryId],
            [CpnyId_home],
            [crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [CuryEffDate],
            [CuryId],
            [CuryMultDiv],
            [CuryRate],
            [CuryRateType],
            [docnbr],
            [employee],
            [fiscalno],
            [le_id01],
            [le_id02],
            [le_id03],
            [le_id04],
            [le_id05],
            [le_id06],
            [le_id07],
            [le_id08],
            [le_id09],
            [le_id10],
            [le_key],
            [le_status],
            [le_type],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [noteid],
            [period_num],
            [pe_date],
            [user1],
            [user2],
            [user3],
            [user4],
            [week_num])
            VALUES
            (@Approver,
            @BaseCuryId,
            @CpnyId_home,
            @crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @CuryEffDate,
            @CuryId,
            @CuryMultDiv,
            @CuryRate,
            @CuryRateType,
            @docnbr,
            @employee,
            @fiscalno,
            @le_id01,
            @le_id02,
            @le_id03,
            @le_id04,
            @le_id05,
            @le_id06,
            @le_id07,
            @le_id08,
            @le_id09,
            @le_id10,
            @le_key,
            @le_status,
            @le_type,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @noteid,
            @period_num,
            @pe_date,
            @user1,
            @user2,
            @user3,
            @user4,
            @week_num);
            End


GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_PJLabHdr_INSERT] TO [MSDSL]
    AS [dbo];

