CREATE PROCEDURE XBANKINFO_ALL @PARM1 varchar(10) , @PARM2 varchar(10) ,@PARM3 varchar (24)  AS SELECT * FROM XBANKINFO WHERE CNYID LIKE @PARM1 AND ACCT 
LIKE @PARM2 AND SUBACCT LIKE @PARM3 ORDER BY ACCT,SUBACCT 



GO
GRANT CONTROL
    ON OBJECT::[dbo].[XBANKINFO_ALL] TO [MSDSL]
    AS [dbo];

