
CREATE PROCEDURE WS_PJEMPLOY_INSERT
            @BaseCuryId char(4),
            @CpnyId char(10),
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @CuryId char(4),
            @CuryRateType char(6),
            @date_hired smalldatetime,
            @date_terminated smalldatetime,
            @employee char(10),
            @emp_name char(60),
            @emp_status char(1),
            @emp_type_cd char(4),
            @em_id01 char(30),
            @em_id02 char(30),
            @em_id03 char(50),
            @em_id04 char(16),
            @em_id05 char(4),
            @em_id06 float,
            @em_id07 float,
            @em_id08 smalldatetime,
            @em_id09 smalldatetime,
            @em_id10 int,
            @em_id11 char(30),
            @em_id12 char(30),
            @em_id13 char(20),
            @em_id14 char(20),
            @em_id15 char(10),
            @em_id16 char(10),
            @em_id17 char(4),
            @em_id18 float,
            @em_id19 smalldatetime,
            @em_id20 int,
            @em_id21 char(10),
            @em_id22 char(10),
            @em_id23 char(10),
            @em_id24 char(10),
            @em_id25 char(10),
            @exp_approval_max float,
            @gl_subacct char(24),
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @manager1 char(10),
            @manager2 char(10),
            @MSPData char(50),
            @MSPInterface char(1),
            @MSPRes_UID int,
            @MSPType char(1),
            @noteid int,
            @placeholder char(1),
            @projExec smallint,
            @stdday smallint,
            @Stdweek smallint,
            @Subcontractor char(1),
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float,
            @user_id char(50)
            AS
            BEGIN
            INSERT INTO [PJEMPLOY]
            ([BaseCuryId],
            [CpnyId],
            [crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [CuryId],
            [CuryRateType],
            [date_hired],
            [date_terminated],
            [employee],
            [emp_name],
            [emp_status],
            [emp_type_cd],
            [em_id01],
            [em_id02],
            [em_id03],
            [em_id04],
            [em_id05],
            [em_id06],
            [em_id07],
            [em_id08],
            [em_id09],
            [em_id10],
            [em_id11],
            [em_id12],
            [em_id13],
            [em_id14],
            [em_id15],
            [em_id16],
            [em_id17],
            [em_id18],
            [em_id19],
            [em_id20],
            [em_id21],
            [em_id22],
            [em_id23],
            [em_id24],
            [em_id25],
            [exp_approval_max],
            [gl_subacct],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [manager1],
            [manager2],
            [MSPData],
            [MSPInterface],
            [MSPRes_UID],
            [MSPType],
            [noteid],
            [placeholder],
            [projExec],
            [stdday],
            [Stdweek],
            [Subcontractor],
            [user1],
            [user2],
            [user3],
            [user4],
            [user_id])
            VALUES
            (@BaseCuryId,
            @CpnyId,
            @crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @CuryId,
            @CuryRateType,
            @date_hired,
            @date_terminated,
            @employee,
            @emp_name,
            @emp_status,
            @emp_type_cd,
            @em_id01,
            @em_id02,
            @em_id03,
            @em_id04,
            @em_id05,
            @em_id06,
            @em_id07,
            @em_id08,
            @em_id09,
            @em_id10,
            @em_id11,
            @em_id12,
            @em_id13,
            @em_id14,
            @em_id15,
            @em_id16,
            @em_id17,
            @em_id18,
            @em_id19,
            @em_id20,
            @em_id21,
            @em_id22,
            @em_id23,
            @em_id24,
            @em_id25,
            @exp_approval_max,
            @gl_subacct,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @manager1,
            @manager2,
            @MSPData,
            @MSPInterface,
            @MSPRes_UID,
            @MSPType,
            @noteid,
            @placeholder,
            @projExec,
            @stdday,
            @Stdweek,
            @Subcontractor,
            @user1,
            @user2,
            @user3,
            @user4,
            @user_id);
            End

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_PJEMPLOY_INSERT] TO [MSDSL]
    AS [dbo];

