  CREATE PROCEDURE WS_inventory_INSERT
            @ABCCode char(2),
            @ApprovedVendor smallint,
            @AutoPODropShip smallint,
            @AutoPOPolicy char(2),
            @BMIDirStdCost float,
            @BMIFOvhStdCost float,
            @BMILastCost float,
            @BMIPDirStdCost float,
            @BMIPFOvhStdCost float,
            @BMIPStdCost float,
            @BMIPVOvhStdCost float,
            @BMIStdCost float,
            @BMIVOvhStdCost float,
            @BOLCode char(10),
            @Buyer char(10),
            @ChkOrdQty char(1),
            @ClassID char(6),
            @COGSAcct char(10),
            @COGSSub char(24),
            @Color char(20),
            @CountStatus char(1),
            @Crtd_DateTime smalldatetime,
            @Crtd_Prog char(8),
            @Crtd_User char(10),
            @CuryListPrice float,
            @CuryMinPrice float,
            @CustomFtr smallint,
            @CycleID char(10),
            @Descr char(60),
            @DfltPickLoc char(10),
            @DfltPOUnit char(6),
            @DfltSalesAcct char(10),
            @DfltSalesSub char(24),
            @DfltShpnotInvAcct char(10),
            @DfltShpnotInvSub char(24),
            @DfltSite char(10),
            @DfltSOUnit char(6),
            @DfltWhseLoc char(10),
            @DirStdCost float,
            @DiscAcct char(10),
            @DiscPrc char(1),
            @DiscSub char(31),
            @EOQ float,
            @ExplInvoice smallint,
            @ExplOrder smallint,
            @ExplPackSlip smallint,
            @ExplPickList smallint,
            @ExplShipping smallint,
            @FOvhStdCost float,
            @FrtAcct char(10),
            @FrtSub char(24),
            @GLClassID char(4),
            @InvtAcct char(10),
            @InvtID char(30),
            @InvtSub char(24),
            @InvtType char(1),
            @IRCalcPolicy char(1),
            @IRDaysSupply float,
            @IRDemandID char(10),
            @IRFutureDate smalldatetime,
            @IRFuturePolicy char(1),
            @IRLeadTimeID char(10),
            @IRLinePtQty float,
            @IRMinOnHand float,
            @IRModelInvtID char(30),
            @IRRCycDays smallint,
            @IRSeasonEndDay smallint,
            @IRSeasonEndMon smallint,
            @IRSeasonStrtDay smallint,
            @IRSeasonStrtMon smallint,
            @IRServiceLevel float,
            @IRSftyStkDays float,
            @IRSftyStkPct float,
            @IRSftyStkPolicy char(1),
            @IRSourceCode char(1),
            @IRTargetOrdMethod char(1),
            @IRTargetOrdReq float,
            @IRTransferSiteID char(10),
            @ItemCommClassID char(10),
            @Kit smallint,
            @LastBookQty float,
            @LastCost float,
            @LastCountDate smalldatetime,
            @LastSiteID char(10),
            @LastStdCost float,
            @LastVarAmt float,
            @LastVarPct float,
            @LastVarQty float,
            @LCVarianceAcct char(10),
            @LCVarianceSub char(24),
            @LeadTime float,
            @LinkSpecId smallint,
            @LotSerFxdLen smallint,
            @LotSerFxdTyp char(1),
            @LotSerFxdVal char(12),
            @LotSerIssMthd char(1),
            @LotSerNumLen smallint,
            @LotSerNumVal char(25),
            @LotSerTrack char(2),
            @LUpd_DateTime smalldatetime,
            @LUpd_Prog char(8),
            @LUpd_User char(10),
            @MaterialType char(10),
            @MaxOnHand float,
            @MfgClassID char(10),
            @MfgLeadTime float,
            @MinGrossProfit float,
            @MoveClass char(10),
            @MSDS char(24),
            @NoteID int,
            @Pack char(6),
            @PDirStdCost float,
            @PerNbr char(6),
            @PFOvhStdCost float,
            @PPVAcct char(10),
            @PPVSub char(24),
            @PriceClassID char(6),
            @ProdMgrID char(10),
            @ProductionUnit char(6),
            @PStdCost float,
            @PStdCostDate smalldatetime,
            @PVOvhStdCost float,
            @ReordPt float,
            @ReOrdPtCalc float,
            @ReordQty float,
            @ReOrdQtyCalc float,
            @ReplMthd char(1),
            @RollupCost smallint,
            @RollupPrice smallint,
            @RvsdPrc smallint,
            @S4Future01 char(30),
            @S4Future02 char(30),
            @S4Future03 float,
            @S4Future04 float,
            @S4Future05 float,
            @S4Future06 float,
            @S4Future07 smalldatetime,
            @S4Future08 smalldatetime,
            @S4Future09 int,
            @S4Future10 int,
            @S4Future11 char(10),
            @S4Future12 char(10),
            @S4Future13 char(10),
            @SafetyStk float,
            @SafetyStkCalc float,
            @Selected smallint,
            @SerAssign char(1),
            @Service smallint,
            @ShelfLife smallint,
            @Size char(10),
            @Source char(1),
            @Status char(1),
            @StdCost float,
            @StdCostDate smalldatetime,
            @StkBasePrc float,
            @StkItem smallint,
            @StkRvsdPrc float,
            @StkTaxBasisPrc float,
            @StkUnit char(6),
            @StkVol float,
            @StkWt float,
            @StkWtUnit char(6),
            @Style char(10),
            @Supplr1 char(15),
            @Supplr2 char(15),
            @SupplrItem1 char(20),
            @SupplrItem2 char(20),
            @TaskID char(32),
            @TaxCat char(10),
            @TranStatusCode char(2),
            @Turns float,
            @UPCCode char(30),
            @UsageRate float,
            @User1 char(30),
            @User2 char(30),
            @User3 float,
            @User4 float,
            @User5 char(10),
            @User6 char(10),
            @User7 smalldatetime,
            @User8 smalldatetime,
            @ValMthd char(1),
            @VOvhStdCost float,
            @WarrantyDays smallint,
            @YTDUsage float
            AS
            BEGIN
            INSERT INTO [inventory]
            ([ABCCode],
            [ApprovedVendor],
            [AutoPODropShip],
            [AutoPOPolicy],
            [BMIDirStdCost],
            [BMIFOvhStdCost],
            [BMILastCost],
            [BMIPDirStdCost],
            [BMIPFOvhStdCost],
            [BMIPStdCost],
            [BMIPVOvhStdCost],
            [BMIStdCost],
            [BMIVOvhStdCost],
            [BOLCode],
            [Buyer],
            [ChkOrdQty],
            [ClassID],
            [COGSAcct],
            [COGSSub],
            [Color],
            [CountStatus],
            [Crtd_DateTime],
            [Crtd_Prog],
            [Crtd_User],
            [CuryListPrice],
            [CuryMinPrice],
            [CustomFtr],
            [CycleID],
            [Descr],
            [DfltPickLoc],
            [DfltPOUnit],
            [DfltSalesAcct],
            [DfltSalesSub],
            [DfltShpnotInvAcct],
            [DfltShpnotInvSub],
            [DfltSite],
            [DfltSOUnit],
            [DfltWhseLoc],
            [DirStdCost],
            [DiscAcct],
            [DiscPrc],
            [DiscSub],
            [EOQ],
            [ExplInvoice],
            [ExplOrder],
            [ExplPackSlip],
            [ExplPickList],
            [ExplShipping],
            [FOvhStdCost],
            [FrtAcct],
            [FrtSub],
            [GLClassID],
            [InvtAcct],
            [InvtID],
            [InvtSub],
            [InvtType],
            [IRCalcPolicy],
            [IRDaysSupply],
            [IRDemandID],
            [IRFutureDate],
            [IRFuturePolicy],
            [IRLeadTimeID],
            [IRLinePtQty],
            [IRMinOnHand],
            [IRModelInvtID],
            [IRRCycDays],
            [IRSeasonEndDay],
            [IRSeasonEndMon],
            [IRSeasonStrtDay],
            [IRSeasonStrtMon],
            [IRServiceLevel],
            [IRSftyStkDays],
            [IRSftyStkPct],
            [IRSftyStkPolicy],
            [IRSourceCode],
            [IRTargetOrdMethod],
            [IRTargetOrdReq],
            [IRTransferSiteID],
            [ItemCommClassID],
            [Kit],
            [LastBookQty],
            [LastCost],
            [LastCountDate],
            [LastSiteID],
            [LastStdCost],
            [LastVarAmt],
            [LastVarPct],
            [LastVarQty],
            [LCVarianceAcct],
            [LCVarianceSub],
            [LeadTime],
            [LinkSpecId],
            [LotSerFxdLen],
            [LotSerFxdTyp],
            [LotSerFxdVal],
            [LotSerIssMthd],
            [LotSerNumLen],
            [LotSerNumVal],
            [LotSerTrack],
            [LUpd_DateTime],
            [LUpd_Prog],
            [LUpd_User],
            [MaterialType],
            [MaxOnHand],
            [MfgClassID],
            [MfgLeadTime],
            [MinGrossProfit],
            [MoveClass],
            [MSDS],
            [NoteID],
            [Pack],
            [PDirStdCost],
            [PerNbr],
            [PFOvhStdCost],
            [PPVAcct],
            [PPVSub],
            [PriceClassID],
            [ProdMgrID],
            [ProductionUnit],
            [PStdCost],
            [PStdCostDate],
            [PVOvhStdCost],
            [ReordPt],
            [ReOrdPtCalc],
            [ReordQty],
            [ReOrdQtyCalc],
            [ReplMthd],
            [RollupCost],
            [RollupPrice],
            [RvsdPrc],
            [S4Future01],
            [S4Future02],
            [S4Future03],
            [S4Future04],
            [S4Future05],
            [S4Future06],
            [S4Future07],
            [S4Future08],
            [S4Future09],
            [S4Future10],
            [S4Future11],
            [S4Future12],
            [S4Future13],
            [SafetyStk],
            [SafetyStkCalc],
            [Selected],
            [SerAssign],
            [Service],
            [ShelfLife],
            [Size],
            [Source],
            [Status],
            [StdCost],
            [StdCostDate],
            [StkBasePrc],
            [StkItem],
            [StkRvsdPrc],
            [StkTaxBasisPrc],
            [StkUnit],
            [StkVol],
            [StkWt],
            [StkWtUnit],
            [Style],
            [Supplr1],
            [Supplr2],
            [SupplrItem1],
            [SupplrItem2],
            [TaskID],
            [TaxCat],
            [TranStatusCode],
            [Turns],
            [UPCCode],
            [UsageRate],
            [User1],
            [User2],
            [User3],
            [User4],
            [User5],
            [User6],
            [User7],
            [User8],
            [ValMthd],
            [VOvhStdCost],
            [WarrantyDays],
            [YTDUsage])
            VALUES
            (@ABCCode,
            @ApprovedVendor,
            @AutoPODropShip,
            @AutoPOPolicy,
            @BMIDirStdCost,
            @BMIFOvhStdCost,
            @BMILastCost,
            @BMIPDirStdCost,
            @BMIPFOvhStdCost,
            @BMIPStdCost,
            @BMIPVOvhStdCost,
            @BMIStdCost,
            @BMIVOvhStdCost,
            @BOLCode,
            @Buyer,
            @ChkOrdQty,
            @ClassID,
            @COGSAcct,
            @COGSSub,
            @Color,
            @CountStatus,
            @Crtd_DateTime,
            @Crtd_Prog,
            @Crtd_User,
            @CuryListPrice,
            @CuryMinPrice,
            @CustomFtr,
            @CycleID,
            @Descr,
            @DfltPickLoc,
            @DfltPOUnit,
            @DfltSalesAcct,
            @DfltSalesSub,
            @DfltShpnotInvAcct,
            @DfltShpnotInvSub,
            @DfltSite,
            @DfltSOUnit,
            @DfltWhseLoc,
            @DirStdCost,
            @DiscAcct,
            @DiscPrc,
            @DiscSub,
            @EOQ,
            @ExplInvoice,
            @ExplOrder,
            @ExplPackSlip,
            @ExplPickList,
            @ExplShipping,
            @FOvhStdCost,
            @FrtAcct,
            @FrtSub,
            @GLClassID,
            @InvtAcct,
            @InvtID,
            @InvtSub,
            @InvtType,
            @IRCalcPolicy,
            @IRDaysSupply,
            @IRDemandID,
            @IRFutureDate,
            @IRFuturePolicy,
            @IRLeadTimeID,
            @IRLinePtQty,
            @IRMinOnHand,
            @IRModelInvtID,
            @IRRCycDays,
            @IRSeasonEndDay,
            @IRSeasonEndMon,
            @IRSeasonStrtDay,
            @IRSeasonStrtMon,
            @IRServiceLevel,
            @IRSftyStkDays,
            @IRSftyStkPct,
            @IRSftyStkPolicy,
            @IRSourceCode,
            @IRTargetOrdMethod,
            @IRTargetOrdReq,
            @IRTransferSiteID,
            @ItemCommClassID,
            @Kit,
            @LastBookQty,
            @LastCost,
            @LastCountDate,
            @LastSiteID,
            @LastStdCost,
            @LastVarAmt,
            @LastVarPct,
            @LastVarQty,
            @LCVarianceAcct,
            @LCVarianceSub,
            @LeadTime,
            @LinkSpecId,
            @LotSerFxdLen,
            @LotSerFxdTyp,
            @LotSerFxdVal,
            @LotSerIssMthd,
            @LotSerNumLen,
            @LotSerNumVal,
            @LotSerTrack,
            @LUpd_DateTime,
            @LUpd_Prog,
            @LUpd_User,
            @MaterialType,
            @MaxOnHand,
            @MfgClassID,
            @MfgLeadTime,
            @MinGrossProfit,
            @MoveClass,
            @MSDS,
            @NoteID,
            @Pack,
            @PDirStdCost,
            @PerNbr,
            @PFOvhStdCost,
            @PPVAcct,
            @PPVSub,
            @PriceClassID,
            @ProdMgrID,
            @ProductionUnit,
            @PStdCost,
            @PStdCostDate,
            @PVOvhStdCost,
            @ReordPt,
            @ReOrdPtCalc,
            @ReordQty,
            @ReOrdQtyCalc,
            @ReplMthd,
            @RollupCost,
            @RollupPrice,
            @RvsdPrc,
            @S4Future01,
            @S4Future02,
            @S4Future03,
            @S4Future04,
            @S4Future05,
            @S4Future06,
            @S4Future07,
            @S4Future08,
            @S4Future09,
            @S4Future10,
            @S4Future11,
            @S4Future12,
            @S4Future13,
            @SafetyStk,
            @SafetyStkCalc,
            @Selected,
            @SerAssign,
            @Service,
            @ShelfLife,
            @Size,
            @Source,
            @Status,
            @StdCost,
            @StdCostDate,
            @StkBasePrc,
            @StkItem,
            @StkRvsdPrc,
            @StkTaxBasisPrc,
            @StkUnit,
            @StkVol,
            @StkWt,
            @StkWtUnit,
            @Style,
            @Supplr1,
            @Supplr2,
            @SupplrItem1,
            @SupplrItem2,
            @TaskID,
            @TaxCat,
            @TranStatusCode,
            @Turns,
            @UPCCode,
            @UsageRate,
            @User1,
            @User2,
            @User3,
            @User4,
            @User5,
            @User6,
            @User7,
            @User8,
            @ValMthd,
            @VOvhStdCost,
            @WarrantyDays,
            @YTDUsage);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_inventory_INSERT] TO [MSDSL]
    AS [dbo];

