CREATE PROCEDURE WS_CustContact_INSERT
                @Addr1 char(60),
                @Addr2 char(60),
                @City char(30),
                @ContactID char(10),
                @Country char(3),
                @Crtd_DateTime smalldatetime,
                @Crtd_Prog char(8),
                @Crtd_User char(10),
                @CustID char(15),
                @EmailAddr char(80),
                @Fax char(30),
                @LUpd_DateTime smalldatetime,
                @LUpd_Prog char(8),
                @LUpd_User char(10),
                @Name char(60),
                @NoteID int,
                @OrderLimit float,
                @Phone char(30),
                @POReqdAmt float,
                @S4Future01 char(30),
                @S4Future02 char(30),
                @S4Future03 float,
                @S4Future04 float,
                @S4Future05 float,
                @S4Future06 float,
                @S4Future07 smalldatetime,
                @S4Future08 smalldatetime,
                @S4Future09 int,
                @S4Future10 int,
                @S4Future11 char(10),
                @S4Future12 char(10),
                @Salut char(30),
                @State char(3),
                @Type char(2),
                @User1 char(30),
                @User10 smalldatetime,
                @User2 char(30),
                @User3 char(30),
                @User4 char(30),
                @User5 float,
                @User6 float,
                @User7 char(10),
                @User8 char(10),
                @User9 smalldatetime,
                @WebSite char(40),
                @Zip char(10)
                AS
                BEGIN
                INSERT INTO [CustContact]
                ([Addr1],
                [Addr2],
                [City],
                [ContactID],
                [Country],
                [Crtd_DateTime],
                [Crtd_Prog],
                [Crtd_User],
                [CustID],
                [EmailAddr],
                [Fax],
                [LUpd_DateTime],
                [LUpd_Prog],
                [LUpd_User],
                [Name],
                [NoteID],
                [OrderLimit],
                [Phone],
                [POReqdAmt],
                [S4Future01],
                [S4Future02],
                [S4Future03],
                [S4Future04],
                [S4Future05],
                [S4Future06],
                [S4Future07],
                [S4Future08],
                [S4Future09],
                [S4Future10],
                [S4Future11],
                [S4Future12],
                [Salut],
                [State],
                [Type],
                [User1],
                [User10],
                [User2],
                [User3],
                [User4],
                [User5],
                [User6],
                [User7],
                [User8],
                [User9],
                [WebSite],
                [Zip])
                VALUES
                (@Addr1,
                @Addr2,
                @City,
                @ContactID,
                @Country,
                @Crtd_DateTime,
                @Crtd_Prog,
                @Crtd_User,
                @CustID,
                @EmailAddr,
                @Fax,
                @LUpd_DateTime,
                @LUpd_Prog,
                @LUpd_User,
                @Name,
                @NoteID,
                @OrderLimit,
                @Phone,
                @POReqdAmt,
                @S4Future01,
                @S4Future02,
                @S4Future03,
                @S4Future04,
                @S4Future05,
                @S4Future06,
                @S4Future07,
                @S4Future08,
                @S4Future09,
                @S4Future10,
                @S4Future11,
                @S4Future12,
                @Salut,
                @State,
                @Type,
                @User1,
                @User10,
                @User2,
                @User3,
                @User4,
                @User5,
                @User6,
                @User7,
                @User8,
                @User9,
                @WebSite,
                @Zip);
                End

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_CustContact_INSERT] TO [MSDSL]
    AS [dbo];

