CREATE PROCEDURE WS_SOHeaderMark_INSERT
            @Addr1 char(60),
            @Addr2 char(60),
            @AddrID char(10),
            @AddrSpecial smallint,
            @Attn char(30),
            @City char(30),
            @Country char(3),
            @CpnyID char(10),
            @Crtd_DateTime smalldatetime,
            @Crtd_Prog char(8),
            @Crtd_User char(10),
            @CustID char(15),
            @LUpd_DateTime smalldatetime,
            @LUpd_Prog char(8),
            @LUpd_User char(10),
            @MarkForID char(10),
            @MarkForType char(1),
            @Name1 char(60),
            @Name2 char(60),
            @Name3 char(60),
            @NoteID int,
            @OrdNbr char(15),
            @S4Future01 char(30),
            @S4Future02 char(30),
            @S4Future03 float,
            @S4Future04 float,
            @S4Future05 float,
            @S4Future06 float,
            @S4Future07 smalldatetime,
            @S4Future08 smalldatetime,
            @S4Future09 int,
            @S4Future10 int,
            @S4Future11 char(10),
            @S4Future12 char(10),
            @ShipViaID char(15),
            @SiteID char(10),
            @State char(3),
            @User1 char(30),
            @User10 smalldatetime,
            @User2 char(30),
            @User3 char(30),
            @User4 char(30),
            @User5 float,
            @User6 float,
            @User7 char(10),
            @User8 char(10),
            @User9 smalldatetime,
            @VendAddrID char(10),
            @VendID char(15),
            @Zip char(10)
            AS
            BEGIN
            INSERT INTO [SOHeaderMark]
            ([Addr1],
            [Addr2],
            [AddrID],
            [AddrSpecial],
            [Attn],
            [City],
            [Country],
            [CpnyID],
            [Crtd_DateTime],
            [Crtd_Prog],
            [Crtd_User],
            [CustID],
            [LUpd_DateTime],
            [LUpd_Prog],
            [LUpd_User],
            [MarkForID],
            [MarkForType],
            [Name1],
            [Name2],
            [Name3],
            [NoteID],
            [OrdNbr],
            [S4Future01],
            [S4Future02],
            [S4Future03],
            [S4Future04],
            [S4Future05],
            [S4Future06],
            [S4Future07],
            [S4Future08],
            [S4Future09],
            [S4Future10],
            [S4Future11],
            [S4Future12],
            [ShipViaID],
            [SiteID],
            [State],
            [User1],
            [User10],
            [User2],
            [User3],
            [User4],
            [User5],
            [User6],
            [User7],
            [User8],
            [User9],
            [VendAddrID],
            [VendID],
            [Zip])
            VALUES
            (@Addr1,
            @Addr2,
            @AddrID,
            @AddrSpecial,
            @Attn,
            @City,
            @Country,
            @CpnyID,
            @Crtd_DateTime,
            @Crtd_Prog,
            @Crtd_User,
            @CustID,
            @LUpd_DateTime,
            @LUpd_Prog,
            @LUpd_User,
            @MarkForID,
            @MarkForType,
            @Name1,
            @Name2,
            @Name3,
            @NoteID,
            @OrdNbr,
            @S4Future01,
            @S4Future02,
            @S4Future03,
            @S4Future04,
            @S4Future05,
            @S4Future06,
            @S4Future07,
            @S4Future08,
            @S4Future09,
            @S4Future10,
            @S4Future11,
            @S4Future12,
            @ShipViaID,
            @SiteID,
            @State,
            @User1,
            @User10,
            @User2,
            @User3,
            @User4,
            @User5,
            @User6,
            @User7,
            @User8,
            @User9,
            @VendAddrID,
            @VendID,
            @Zip);
            END

GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_SOHeaderMark_INSERT] TO [MSDSL]
    AS [dbo];

