            CREATE PROCEDURE WS_PJUTGOAL_INSERT
            @available_hours float,
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @employee char(10),
            @fiscalno char(6),
            @hours_goal float,
            @hours_goal_percent float,
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @NoteId int,
            @rate float,
            @revenue_goal float,
            @ug_id01 char(30),
            @ug_id02 char(30),
            @ug_id03 char(20),
            @ug_id04 char(20),
            @ug_id05 char(10),
            @ug_id06 char(10),
            @ug_id07 char(4),
            @ug_id08 float,
            @ug_id09 smalldatetime,
            @ug_id10 int,
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float
            AS
            BEGIN
            INSERT INTO [PJUTGOAL]
            ([available_hours],
            [crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [employee],
            [fiscalno],
            [hours_goal],
            [hours_goal_percent],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [NoteId],
            [rate],
            [revenue_goal],
            [ug_id01],
            [ug_id02],
            [ug_id03],
            [ug_id04],
            [ug_id05],
            [ug_id06],
            [ug_id07],
            [ug_id08],
            [ug_id09],
            [ug_id10],
            [user1],
            [user2],
            [user3],
            [user4])
            VALUES(
            @available_hours,
            @crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @employee,
            @fiscalno,
            @hours_goal,
            @hours_goal_percent,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @NoteId,
            @rate,
            @revenue_goal,
            @ug_id01,
            @ug_id02,
            @ug_id03,
            @ug_id04,
            @ug_id05,
            @ug_id06,
            @ug_id07,
            @ug_id08,
            @ug_id09,
            @ug_id10,
            @user1,
            @user2,
            @user3,
            @user4);
END


GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_PJUTGOAL_INSERT] TO [MSDSL]
    AS [dbo];

