 CREATE PROCEDURE FMGWorkTableTruncate AS

   TRUNCATE TABLE AP03615_Wrk
   TRUNCATE TABLE AP03625_Wrk
   TRUNCATE TABLE AP03630mc_wrk
   TRUNCATE TABLE AP03650mc_wrk
   TRUNCATE TABLE AP03673_Wrk
   TRUNCATE TABLE AP03680_wrk
   TRUNCATE TABLE AP03681_Wrk
   TRUNCATE TABLE AP03730_Wrk
   TRUNCATE TABLE AR08600_Wrk
   TRUNCATE TABLE AR08620_Wrk
   TRUNCATE TABLE AR08690_Wrk
   TRUNCATE TABLE AR08820_Wrk
   TRUNCATE TABLE RptCompany
   TRUNCATE TABLE RptExtra
   TRUNCATE TABLE RptRuntime
   TRUNCATE TABLE Wrk_APTran
   TRUNCATE TABLE Wrk_GLTran
   TRUNCATE TABLE Wrk_SalesTax
   TRUNCATE TABLE Wrk_TimeRange
   TRUNCATE TABLE Wrk13610
   TRUNCATE TABLE WrkAcctHist
   TRUNCATE TABLE WrkAllocGrp
   TRUNCATE TABLE WrkAPDoc
   TRUNCATE TABLE WrkARDoc
   TRUNCATE TABLE WrkARTran
   TRUNCATE TABLE WrkBatch
   TRUNCATE TABLE WrkBudgetDetail
   TRUNCATE TABLE WrkCABalances
   TRUNCATE TABLE WrkCADetail
   TRUNCATE TABLE WrkCAForecast
   TRUNCATE TABLE WrkCheckSel
   TRUNCATE TABLE WrkCMUGL
   TRUNCATE TABLE WrkDefExpt
   TRUNCATE TABLE WrkDetInquiry
   TRUNCATE TABLE WrkFSTriBal
   TRUNCATE TABLE WrkIChk
   TRUNCATE TABLE WrkPost
   TRUNCATE TABLE WrkPostBad
   TRUNCATE TABLE WrkRelease
   TRUNCATE TABLE WrkRelease_PO
   TRUNCATE TABLE WrkReleaseBad
   TRUNCATE TABLE WrkSubAcct
   TRUNCATE TABLE WrkSumInquiry
   TRUNCATE TABLE WrkTrslDet
   TRUNCATE TABLE WrkTrslHdr



GO
GRANT CONTROL
    ON OBJECT::[dbo].[FMGWorkTableTruncate] TO [MSDSL]
    AS [dbo];

