 CREATE PROCEDURE DMG_UNRELEASED_BATCHES
	@MODULE		VARCHAR(2)
AS
	SELECT	*
		FROM	BATCH
		WHERE	(MODULE = @MODULE
			AND STATUS IN ('B', 'S', 'I', 'H'))
			OR (MODULE = 'PO'
			AND STATUS IN ('C')
			AND BATNBR IN (SELECT BATNBR FROM INTRAN WHERE JRNLTYPE = 'PO' AND RLSED = 0))
		ORDER BY BATNBR, MODULE


