
            CREATE PROCEDURE WS_PJLabDet_INSERT
            @CpnyId_chrg char(10),
            @CpnyId_home char(10),
            @crtd_datetime smalldatetime,
            @crtd_prog char(8),
            @crtd_user char(10),
            @day1_hr1 float,
            @day1_hr2 float,
            @day1_hr3 float,
            @day2_hr1 float,
            @day2_hr2 float,
            @day2_hr3 float,
            @day3_hr1 float,
            @day3_hr2 float,
            @day3_hr3 float,
            @day4_hr1 float,
            @day4_hr2 float,
            @day4_hr3 float,
            @day5_hr1 float,
            @day5_hr2 float,
            @day5_hr3 float,
            @day6_hr1 float,
            @day6_hr2 float,
            @day6_hr3 float,
            @day7_hr1 float,
            @day7_hr2 float,
            @day7_hr3 float,
            @docnbr char(10),
            @earn_type_id char(10),
            @gl_acct char(10),
            @gl_subacct char(24),
            @labor_class_cd char(4),
            @labor_stdcost float,
            @ld_desc char(30),
            @ld_id01 char(30),
            @ld_id02 char(30),
            @ld_id03 char(16),
            @ld_id04 char(16),
            @ld_id05 char(4),
            @ld_id06 float,
            @ld_id07 float,
            @ld_id08 smalldatetime,
            @ld_id09 smalldatetime,
            @ld_id10 int,
            @ld_id11 char(30),
            @ld_id12 char(30),
            @ld_id13 char(20),
            @ld_id14 char(20),
            @ld_id15 char(10),
            @ld_id16 char(10),
            @ld_id17 char(4),
            @ld_id18 float,
            @ld_id19 float,
            @ld_id20 smalldatetime,
            @ld_status char(1),
            @linenbr smallint,
            @lupd_datetime smalldatetime,
            @lupd_prog char(8),
            @lupd_user char(10),
            @noteid int,
            @pjt_entity char(32),
            @project char(16),
            @rate_source char(1),
            @shift char(7),
            @SubTask_Name char(50),
            @SubTask_UID int,
            @total_amount float,
            @total_hrs float,
            @union_cd char(10),
            @user1 char(30),
            @user2 char(30),
            @user3 float,
            @user4 float,
            @work_comp_cd char(6),
            @work_type char(2)
            AS
            BEGIN
            INSERT INTO [PJLabDet]
            ([CpnyId_chrg],
            [CpnyId_home],
            [crtd_datetime],
            [crtd_prog],
            [crtd_user],
            [day1_hr1],
            [day1_hr2],
            [day1_hr3],
            [day2_hr1],
            [day2_hr2],
            [day2_hr3],
            [day3_hr1],
            [day3_hr2],
            [day3_hr3],
            [day4_hr1],
            [day4_hr2],
            [day4_hr3],
            [day5_hr1],
            [day5_hr2],
            [day5_hr3],
            [day6_hr1],
            [day6_hr2],
            [day6_hr3],
            [day7_hr1],
            [day7_hr2],
            [day7_hr3],
            [docnbr],
            [earn_type_id],
            [gl_acct],
            [gl_subacct],
            [labor_class_cd],
            [labor_stdcost],
            [ld_desc],
            [ld_id01],
            [ld_id02],
            [ld_id03],
            [ld_id04],
            [ld_id05],
            [ld_id06],
            [ld_id07],
            [ld_id08],
            [ld_id09],
            [ld_id10],
            [ld_id11],
            [ld_id12],
            [ld_id13],
            [ld_id14],
            [ld_id15],
            [ld_id16],
            [ld_id17],
            [ld_id18],
            [ld_id19],
            [ld_id20],
            [ld_status],
            [linenbr],
            [lupd_datetime],
            [lupd_prog],
            [lupd_user],
            [noteid],
            [pjt_entity],
            [project],
            [rate_source],
            [shift],
            [SubTask_Name],
            [SubTask_UID],
            [total_amount],
            [total_hrs],
            [union_cd],
            [user1],
            [user2],
            [user3],
            [user4],
            [work_comp_cd],
            [work_type])
            VALUES
            (@CpnyId_chrg,
            @CpnyId_home,
            @crtd_datetime,
            @crtd_prog,
            @crtd_user,
            @day1_hr1,
            @day1_hr2,
            @day1_hr3,
            @day2_hr1,
            @day2_hr2,
            @day2_hr3,
            @day3_hr1,
            @day3_hr2,
            @day3_hr3,
            @day4_hr1,
            @day4_hr2,
            @day4_hr3,
            @day5_hr1,
            @day5_hr2,
            @day5_hr3,
            @day6_hr1,
            @day6_hr2,
            @day6_hr3,
            @day7_hr1,
            @day7_hr2,
            @day7_hr3,
            @docnbr,
            @earn_type_id,
            @gl_acct,
            @gl_subacct,
            @labor_class_cd,
            @labor_stdcost,
            @ld_desc,
            @ld_id01,
            @ld_id02,
            @ld_id03,
            @ld_id04,
            @ld_id05,
            @ld_id06,
            @ld_id07,
            @ld_id08,
            @ld_id09,
            @ld_id10,
            @ld_id11,
            @ld_id12,
            @ld_id13,
            @ld_id14,
            @ld_id15,
            @ld_id16,
            @ld_id17,
            @ld_id18,
            @ld_id19,
            @ld_id20,
            @ld_status,
            @linenbr,
            @lupd_datetime,
            @lupd_prog,
            @lupd_user,
            @noteid,
            @pjt_entity,
            @project,
            @rate_source,
            @shift,
            @SubTask_Name,
            @SubTask_UID,
            @total_amount,
            @total_hrs,
            @union_cd,
            @user1,
            @user2,
            @user3,
            @user4,
            @work_comp_cd,
            @work_type);
            END


GO
GRANT CONTROL
    ON OBJECT::[dbo].[WS_PJLabDet_INSERT] TO [MSDSL]
    AS [dbo];

