CREATE TABLE [stage].[CFT_ANIMALTAG] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      CONSTRAINT [DF__CFT_ANIMA__CREAT__21D600EE] DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      CONSTRAINT [DF__CFT_ANIMA__LAST___22CA2527] DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        CONSTRAINT [DF__CFT_ANIMA__CREAT__23BE4960] DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        CONSTRAINT [DF__CFT_ANIMA__LAST___24B26D99] DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        CONSTRAINT [DF__CFT_ANIMA__DELET__25A691D2] DEFAULT ((-1)) NOT NULL,
    [ANIMALID]        NVARCHAR (36) NULL,
    [TAGNBR]          NVARCHAR (20) NULL,
    [TAGDATE]         DATETIME      NULL,
    [PRIMARYTAG]      INT           NULL,
    [ISCURRENT]       INT           NULL,
    CONSTRAINT [CFT_ANIMALTAG_PK] PRIMARY KEY CLUSTERED ([ID] ASC)
);



