CREATE LOGIN [ApplicationCenter]
    WITH PASSWORD = N'xvv?Emhx3qmly_YohAPwxw3|msFT7_&#$!~<Dwt,agB>v{xS', SID = 0x6C7FFE344536DE4A8486FA4522DA68AA, DEFAULT_DATABASE = [CFApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

