CREATE LOGIN [CornPurchApp]
    WITH PASSWORD = N'vxvmhxbq:mlTyo#w 6uw|WwFmsFT7_&#$!~<Wtfagv`x9xel', SID = 0x1C040DEE9D9A3E47B838D3D9FFF4A4DC, DEFAULT_DATABASE = [CFApp_CornPurch], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

