CREATE LOGIN [ApplicationCenter]
    WITH PASSWORD = N'x9oJcy|E?E:h{nuizprt`gvemsFT7_&#$!~<,ypfp_eb|s5,', SID = 0x6C7FFE344536DE4A8486FA4522DA68AA, DEFAULT_DATABASE = [CFApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

