CREATE LOGIN [CornPurchApp]
    WITH PASSWORD = N'xoacy|nhN{n2uiRzprrt$RgvmsFT7_&#$!~<e$Layppfpeb{', SID = 0x1C040DEE9D9A3E47B838D3D9FFF4A4DC, DEFAULT_DATABASE = [CFApp_CornPurch], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

