CREATE TABLE [caredata].[cft_originid_HDR_SOWS] (
    [identity_id]      INT          NOT NULL,
    [genetics_id]      INT          NULL,
    [herd_category_id] INT          NULL,
    [date_of_birth]    DATETIME     NULL,
    [name]             VARCHAR (30) NULL,
    [notch]            VARCHAR (30) NULL,
    [sire_identity]    VARCHAR (15) NULL,
    [dam_identity]     VARCHAR (15) NULL,
    [halothane]        VARCHAR (1)  NULL,
    [value]            FLOAT (53)   NULL,
    [weight]           FLOAT (53)   NULL,
    [ebv]              FLOAT (53)   NULL,
    [prior_liveborn]   SMALLINT     NULL,
    [prior_stillborn]  SMALLINT     NULL,
    [prior_weaned]     SMALLINT     NULL,
    [starting_parity]  TINYINT      NULL,
    [service_date]     DATETIME     NULL,
    [weaning_date]     DATETIME     NULL,
    [origin_id]        INT          NULL,
    [ticket_id]        INT          NULL,
    [UDF70434]         INT          NULL,
    [UDF67285]         INT          NULL,
    [UDF74313]         VARCHAR (12) NULL,
    [UDF62226]         INT          NULL,
    [UDF27057]         VARCHAR (12) NULL,
    [UDF16518]         VARCHAR (8)  NULL,
    [UDF39326]         VARCHAR (8)  NULL,
    [UDF74939]         INT          NULL,
    [UDF64769]         VARCHAR (12) NULL,
    [UDF54949]         DATETIME     NULL,
    [UDF35976]         VARCHAR (12) NULL,
    [UDF84003]         VARCHAR (30) NULL,
    [UDF38334]         VARCHAR (12) NULL,
    [UDF94578]         INT          NULL,
    [UDF76703]         VARCHAR (30) NULL,
    [UDF82935]         VARCHAR (30) NULL,
    [UDF8646]          INT          NULL,
    [UDF27400]         DATETIME     NULL,
    [UDF21600]         VARCHAR (10) NULL,
    [UDF33799]         VARCHAR (10) NULL,
    [UDF3682]          VARCHAR (15) NULL,
    [UDF82504]         VARCHAR (15) NULL,
    [UDF89984]         VARCHAR (12) NULL
);

