CREATE TABLE [caredata].[MAP_FEED_MEDICATION_RATIONS] (
    [budget_id]    INT NOT NULL,
    [ration_id]    INT NOT NULL,
    [treatment_id] INT NOT NULL,
    CONSTRAINT [PK_MAP_FEED_MEDICATION_RATIONS] PRIMARY KEY CLUSTERED ([budget_id] ASC, [ration_id] ASC, [treatment_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MAP_FEED_MEDICATION_RATIONS_HDR_FEED_RATIONS_1] FOREIGN KEY ([ration_id]) REFERENCES [caredata].[HDR_FEED_RATIONS] ([ration_id]),
    CONSTRAINT [FK_MAP_FEED_MEDICATION_RATIONS_HDR_MEDICATION_BUDGETS_0] FOREIGN KEY ([budget_id]) REFERENCES [caredata].[HDR_MEDICATION_BUDGETS] ([budget_id]),
    CONSTRAINT [FK_MAP_FEED_MEDICATION_RATIONS_TREATMENTS_2] FOREIGN KEY ([treatment_id]) REFERENCES [caredata].[TREATMENTS] ([treatment_id]) ON UPDATE CASCADE
);

