CREATE TABLE [caredata].[SHIPMENT_SALES] (
    [ticket_id]        INT           NOT NULL,
    [packer_id]        INT           NULL,
    [pig_type_id]      INT           NULL,
    [receipt_date]     DATETIME      NULL,
    [tattoo]           VARCHAR (15)  NULL,
    [market]           VARCHAR (15)  NULL,
    [pigs_received]    SMALLINT      NULL,
    [pigs_rejected]    SMALLINT      NULL,
    [pigs_doa]         SMALLINT      NULL,
    [pigs_substandard] SMALLINT      NULL,
    [amount_received]  FLOAT (53)    NULL,
    [currency_unit]    VARCHAR (3)   NULL,
    [carcass_weight]   FLOAT (53)    NULL,
    [total_liveweight] FLOAT (53)    NULL,
    [contract_base]    FLOAT (53)    NULL,
    [pH]               FLOAT (53)    NULL,
    [percent_lean]     FLOAT (53)    NULL,
    [backfat]          FLOAT (53)    NULL,
    [sort_loss]        FLOAT (53)    NULL,
    [av_loin_depth]    FLOAT (53)    NULL,
    [check_number]     VARCHAR (20)  NULL,
    [note]             VARCHAR (300) NULL,
    [creation_date]    DATETIME      CONSTRAINT [DF_SHIPMENT_SALES_creation_date] DEFAULT (getdate()) NOT NULL,
    [created_by]       VARCHAR (15)  CONSTRAINT [DF_SHIPMENT_SALES_created_by] DEFAULT ('SYSTEM') NOT NULL,
    [last_update_date] DATETIME      NULL,
    [last_update_by]   VARCHAR (15)  NULL,
    [deletion_date]    DATETIME      NULL,
    [deleted_by]       VARCHAR (15)  NULL,
    CONSTRAINT [PK_SHIPMENT_SALES] PRIMARY KEY NONCLUSTERED ([ticket_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SHIPMENT_SALES_COMMON_LOOKUPS_2] FOREIGN KEY ([pig_type_id]) REFERENCES [caredata].[COMMON_LOOKUPS] ([lookup_id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_SHIPMENT_SALES_PACKING_PLANTS_1] FOREIGN KEY ([packer_id]) REFERENCES [caredata].[PACKING_PLANTS] ([packer_id]) ON UPDATE CASCADE,
    CONSTRAINT [FK_SHIPMENT_SALES_SHIPMENT_TICKETS_0] FOREIGN KEY ([ticket_id]) REFERENCES [caredata].[SHIPMENT_TICKETS] ([ticket_id]) ON DELETE CASCADE
);

