CREATE TABLE [caredata].[EV_LOCATION_CHANGE] (
    [event_id]    INT         NOT NULL,
    [identity_id] INT         NOT NULL,
    [UDF40992]    VARCHAR (8) NULL,
    CONSTRAINT [PK_EV_LOCATION_CHANGE] PRIMARY KEY CLUSTERED ([identity_id] ASC, [event_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EV_LOCATION_CHANGE_BH_EVENTS_0] FOREIGN KEY ([event_id]) REFERENCES [caredata].[BH_EVENTS] ([event_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_EV_LOCATION_CHANGE_BH_IDENTITIES_1] FOREIGN KEY ([identity_id]) REFERENCES [caredata].[BH_IDENTITIES] ([identity_id])
);

