CREATE TABLE [caredata].[MAP_FEED_NUTRIENT_RATION] (
    [ration_id]   INT        NOT NULL,
    [nutrient_id] INT        NOT NULL,
    [pcent]       FLOAT (53) NOT NULL,
    CONSTRAINT [PK_MAP_FEED_NUTRIENT_RATION] PRIMARY KEY CLUSTERED ([ration_id] ASC, [nutrient_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MAP_FEED_NUTRIENT_RATION_HDR_FEED_NUTRIENTS_1] FOREIGN KEY ([nutrient_id]) REFERENCES [caredata].[HDR_FEED_NUTRIENTS] ([nutrient_id]),
    CONSTRAINT [FK_MAP_FEED_NUTRIENT_RATION_HDR_FEED_RATIONS_0] FOREIGN KEY ([ration_id]) REFERENCES [caredata].[HDR_FEED_RATIONS] ([ration_id]) ON DELETE CASCADE
);

