CREATE TABLE [caredata].[MAP_FEED_INGREDIENT_RATION] (
    [ration_id]     INT        NOT NULL,
    [ingredient_id] INT        NOT NULL,
    [pcent]         FLOAT (53) NOT NULL,
    CONSTRAINT [PK_MAP_FEED_INGREDIENT_RATION] PRIMARY KEY CLUSTERED ([ration_id] ASC, [ingredient_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MAP_FEED_INGREDIENT_RATION_HDR_FEED_INGREDIENTS_1] FOREIGN KEY ([ingredient_id]) REFERENCES [caredata].[HDR_FEED_INGREDIENTS] ([ingredient_id]),
    CONSTRAINT [FK_MAP_FEED_INGREDIENT_RATION_HDR_FEED_RATIONS_0] FOREIGN KEY ([ration_id]) REFERENCES [caredata].[HDR_FEED_RATIONS] ([ration_id]) ON DELETE CASCADE
);

