CREATE TABLE [caredata].[MAP_FEED_LOCATION_BINS] (
    [location_id] INT NOT NULL,
    [bin_id]      INT NOT NULL,
    CONSTRAINT [PK_MAP_FEED_LOCATION_BINS] PRIMARY KEY CLUSTERED ([location_id] ASC, [bin_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MAP_FEED_LOCATION_BINS_HDR_FEED_BINS_1] FOREIGN KEY ([bin_id]) REFERENCES [caredata].[HDR_FEED_BINS] ([bin_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_MAP_FEED_LOCATION_BINS_HDR_FEED_LOCATIONS_0] FOREIGN KEY ([location_id]) REFERENCES [caredata].[HDR_FEED_LOCATIONS] ([location_id]) ON DELETE CASCADE
);

