CREATE TABLE [caredata].[EV_SEMEN_COLLECTIONS] (
    [event_id]          INT NOT NULL,
    [identity_id]       INT NOT NULL,
    [batch_identity_id] INT NOT NULL,
    CONSTRAINT [PK_EV_SEMEN_COLLECTIONS] PRIMARY KEY CLUSTERED ([identity_id] ASC, [event_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EV_SEMEN_COLLECTIONS_BH_EVENTS_0] FOREIGN KEY ([event_id]) REFERENCES [caredata].[BH_EVENTS] ([event_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_EV_SEMEN_COLLECTIONS_BH_IDENTITIES_1] FOREIGN KEY ([identity_id]) REFERENCES [caredata].[BH_IDENTITIES] ([identity_id]),
    CONSTRAINT [FK_EV_SEMEN_COLLECTIONS_BH_IDENTITIES_2] FOREIGN KEY ([batch_identity_id]) REFERENCES [caredata].[BH_IDENTITIES] ([identity_id])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_EV_SEMEN_COLLECTIONS_0]
    ON [caredata].[EV_SEMEN_COLLECTIONS]([batch_identity_id] ASC)
    INCLUDE([identity_id]) WITH (FILLFACTOR = 80);

