CREATE TABLE [careglobal].[FARMS] (
    [site_id]               INT              NOT NULL,
    [farm_number]           VARCHAR (4)      CONSTRAINT [DF_FARMS_farm_number] DEFAULT ('0000') NOT NULL,
    [farm_name]             VARCHAR (30)     NULL,
    [premise_name]          VARCHAR (30)     NULL,
    [farm_type]             TINYINT          CONSTRAINT [DF_FARMS_farm_type] DEFAULT ((0)) NOT NULL,
    [company_id]            INT              NULL,
    [owner]                 VARCHAR (30)     NULL,
    [owner_phone]           VARCHAR (15)     NULL,
    [owner_email]           VARCHAR (50)     NULL,
    [manager]               VARCHAR (30)     NULL,
    [manager_phone]         VARCHAR (15)     NULL,
    [manager_email]         VARCHAR (50)     NULL,
    [address1]              NVARCHAR (35)    NULL,
    [address2]              NVARCHAR (35)    NULL,
    [address3]              NVARCHAR (35)    NULL,
    [address4]              NVARCHAR (35)    NULL,
    [address5]              NVARCHAR (35)    NULL,
    [phone]                 VARCHAR (30)     NULL,
    [sex_liveborn]          BIT              CONSTRAINT [DF_FARMS_sex_liveborn] DEFAULT ((0)) NOT NULL,
    [sex_weaned]            BIT              CONSTRAINT [DF_FARMS_sex_weaned] DEFAULT ((0)) NOT NULL,
    [tattoo_unique]         BIT              CONSTRAINT [DF_FARMS_tattoo_unique] DEFAULT ((0)) NOT NULL,
    [tattoo_length]         TINYINT          CONSTRAINT [DF_FARMS_tattoo_length] DEFAULT ((15)) NOT NULL,
    [tattoo_unique_start]   INT              NULL,
    [tattoo_unique_length]  INT              NULL,
    [reportonly]            BIT              CONSTRAINT [DF_FARMS_reportonly] DEFAULT ((0)) NOT NULL,
    [main_site_id]          INT              NOT NULL,
    [farm_guid]             UNIQUEIDENTIFIER NOT NULL,
    [piglet_identity_match] TINYINT          CONSTRAINT [DF_FARMS_piglet_identity_match] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_FARMS] PRIMARY KEY CLUSTERED ([site_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_FARMS_FARM_COMPANIES_1] FOREIGN KEY ([company_id]) REFERENCES [careglobal].[FARM_COMPANIES] ([site_id]),
    CONSTRAINT [FK_FARMS_SITES_0] FOREIGN KEY ([site_id]) REFERENCES [careglobal].[SITES] ([site_id]) ON DELETE CASCADE
);

