CREATE TABLE [dbo].[CFT_ANIMALTAG](
	[ID] [nvarchar](36) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL CONSTRAINT [DF__CFT_ANIMA__CREAT__21D600EE]  DEFAULT (getutcdate()),
	[LAST_UPDATE] [datetime] NOT NULL CONSTRAINT [DF__CFT_ANIMA__LAST___22CA2527]  DEFAULT (getutcdate()),
	[CREATED_BY] [bigint] NOT NULL CONSTRAINT [DF__CFT_ANIMA__CREAT__23BE4960]  DEFAULT ((0)),
	[LAST_UPDATED_BY] [bigint] NOT NULL CONSTRAINT [DF__CFT_ANIMA__LAST___24B26D99]  DEFAULT ((0)),
	[DELETED_BY] [bigint] NOT NULL CONSTRAINT [DF__CFT_ANIMA__DELET__25A691D2]  DEFAULT ((-1)),
	[ANIMALID] [nvarchar](36) NULL,
	[TAGNBR] [nvarchar](20) NULL,
	[TAGDATE] [datetime] NULL,
	[PRIMARYTAG] [int] NULL,
	[MFSYNC] [nvarchar](1) NULL,
	[ISCURRENT] [int] NULL,
	[QRCODE] [image] NULL,
	[QRCODETYPE] [nvarchar](20) NULL,
 CONSTRAINT [CFT_ANIMALTAG_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
