CREATE TABLE [dbo].[cftASOSaleQty_eb] (
    [Year]           CHAR (10)    NOT NULL,
    [Time]           CHAR (10)    NOT NULL,
    [LocNbr]         VARCHAR (7)  NULL,
    [SiteName]       VARCHAR (50) NULL,
    [PigGroupName]   CHAR (32)    NULL,
    [GroupAlias]     VARCHAR (84) NULL,
    [PM]             CHAR (13)    NULL,
    [PodName]        CHAR (30)    NULL,
    [Packer]         CHAR (50)    NULL,
    [Trucker]        CHAR (55)    NULL,
    [FeedAdditive]   VARCHAR (9)  NULL,
    [ServiceManager] VARCHAR (50) NULL,
    [LoadCrew]       CHAR (55)    NULL,
    [DaysonPaylean]  INT          NULL,
    [MilestoPacker]  FLOAT (53)   NULL,
    [AB_Qty]         FLOAT (53)   NULL,
    [BB_Qty]         FLOAT (53)   NULL,
    [BO_Qty]         FLOAT (53)   NULL,
    [CD_Qty]         FLOAT (53)   NULL,
    [CP_Qty]         FLOAT (53)   NULL,
    [DT_Qty]         FLOAT (53)   NULL,
    [DY_Qty]         FLOAT (53)   NULL,
    [HV_Qty]         FLOAT (53)   NULL,
    [IB_Qty]         FLOAT (53)   NULL,
    [LM_QTY]         FLOAT (53)   NULL,
    [LT_QTY]         FLOAT (53)   NULL,
    [MR_QTY]         FLOAT (53)   NULL,
    [OW_QTY]         FLOAT (53)   NULL,
    [PQ_QTY]         FLOAT (53)   NULL,
    [RR_Qty]         FLOAT (53)   NULL,
    [SB_Qty]         FLOAT (53)   NULL,
    [TB_Qty]         FLOAT (53)   NULL,
    [SS_Qty]         FLOAT (53)   NULL,
    [MktManger]      CHAR (50)    NULL
);
