CREATE TABLE [dbo].[cft_SSIS_SETTINGS] (
    [SSISSettingsID]  INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ConnectionName]  VARCHAR (100)  NOT NULL,
    [ConnectionValue] VARCHAR (4000) NULL,
    CONSTRAINT [PK_cft_SSIS_SETTINGS] PRIMARY KEY CLUSTERED ([SSISSettingsID] ASC) WITH (FILLFACTOR = 90)
);

