CREATE TABLE [dbo].[cft_PIG_GROUP_ROLLUP] (
    [TaskID]                     CHAR (32)       NOT NULL,
    [SiteContactID]              CHAR (6)        NULL,
    [MasterGroup]                CHAR (10)       NULL,
    [PigFlowID]                  INT             NULL,
    [ActCloseDate]               SMALLDATETIME   NULL,
    [ActStartDate]               SMALLDATETIME   NULL,
    [MasterActCloseDate]         SMALLDATETIME   NULL,
    [MasterActStartDate]         SMALLDATETIME   NULL,
    [BarnNbr]                    CHAR (16)       NULL,
    [Description]                CHAR (30)       NULL,
    [PodDescription]             CHAR (30)       NULL,
    [PGStatusID]                 CHAR (2)        NULL,
    [PigGenderTypeID]            CHAR (6)        NULL,
    [Phase]                      VARCHAR (30)    NULL,
    [PhaseDesc]                  VARCHAR (30)    NULL,
    [SvcManager]                 VARCHAR (100)   NULL,
    [SrSvcManager]               VARCHAR (100)   NULL,
    [MasterSvcManager]           VARCHAR (100)   NULL,
    [MasterSrSvcManager]         VARCHAR (100)   NULL,
    [LivePigDays]                BIGINT          NULL,
    [DeadPigDays]                BIGINT          NULL,
    [TotalPigDays]               BIGINT          NULL,
    [Feed_Qty]                   NUMERIC (14, 2) NULL,
    [TransferIn_Qty]             INT             NULL,
    [MoveIn_Qty]                 INT             NULL,
    [MoveOut_Qty]                INT             NULL,
    [PigDeath_Qty]               INT             NULL,
    [TransferOut_Qty]            INT             NULL,
    [TransferToTailender_Qty]    INT             NULL,
    [Prim_Qty]                   INT             NULL,
    [Cull_Qty]                   INT             NULL,
    [DeadPigsToPacker_Qty]       INT             NULL,
    [TransportDeath_Qty]         INT             NULL,
    [InventoryAdjustment_Qty]    INT             NULL,
    [Top_Qty]                    INT             NULL,
    [TransferIn_Wt]              NUMERIC (14, 2) NULL,
    [MoveIn_Wt]                  NUMERIC (14, 2) NULL,
    [MoveOut_Wt]                 NUMERIC (14, 2) NULL,
    [TransferOut_Wt]             NUMERIC (14, 2) NULL,
    [TransferToTailender_Wt]     NUMERIC (14, 2) NULL,
    [Prim_Wt]                    NUMERIC (14, 2) NULL,
    [Cull_Wt]                    NUMERIC (14, 2) NULL,
    [DeadPigsToPacker_Wt]        NUMERIC (14, 2) NULL,
    [TransportDeath_Wt]          NUMERIC (14, 2) NULL,
    [Top_Wt]                     NUMERIC (14, 2) NULL,
    [MedicationCost]             NUMERIC (14, 2) NULL,
    [WeightGained]               NUMERIC (14, 2) NULL,
    [HeadStarted]                INT             NULL,
    [TotalHeadProduced]          INT             NULL,
    [AverageDailyGain]           NUMERIC (14, 3) NULL,
    [FeedToGain]                 NUMERIC (14, 3) NULL,
    [AdjFeedToGain]              NUMERIC (14, 3) NULL,
    [Mortality]                  NUMERIC (14, 2) NULL,
    [AveragePurchase_Wt]         NUMERIC (14, 1) NULL,
    [AverageOut_Wt]              NUMERIC (14, 1) NULL,
    [AverageDailyFeedIntake]     NUMERIC (14, 2) NULL,
    [Tailender_Pct]              NUMERIC (5, 2)  NULL,
    [DeadPigsToPacker_Pct]       NUMERIC (5, 2)  NULL,
    [Cull_Pct]                   NUMERIC (5, 2)  NULL,
    [NoValue_Pct]                NUMERIC (5, 2)  NULL,
    [MedicationCostPerHead]      NUMERIC (14, 2) NULL,
    [VaccinationCost]            NUMERIC (14, 2) NULL,
    [FeedCost]                   NUMERIC (14, 2) NULL,
    [HeadCapacity]               INT             NULL,
    [PigStartDate]               DATETIME        NULL,
    [PigEndDate]                 DATETIME        NULL,
    [HeadSold]                   INT             NULL,
    [AverageMarket_Wt]           NUMERIC (14, 2) NULL,
    [DaysInGroup]                INT             NULL,
    [PigCapacityDays]            INT             NULL,
    [EmptyDays]                  INT             NULL,
    [EmptyCapacityDays]          INT             NULL,
    [CapacityDays]               INT             NULL,
    [TotalCapacityDays]          INT             NULL,
    [AverageDaysInGroup]         INT             NULL,
    [AverageEmptyDays]           INT             NULL,
    [Utilization]                DECIMAL (6, 2)  NULL,
    [MedicationCostPerHeadSold]  NUMERIC (8, 2)  NULL,
    [VaccinationCostPerHeadSold] NUMERIC (8, 2)  NULL,
    [FeedCostPerHundredGain]     NUMERIC (8, 2)  NULL,
    [AdjAverageDailyGain]        NUMERIC (14, 3) NULL,
    [DeadOnTruck_qty]            INT             NULL,
    [DeadInYard_qty]             INT             NULL,
    [CondemnedByPacker_qty]      INT             NULL,
    [Condemned_qty]              INT             NULL,
    [DeadOnTruck_wt]             DECIMAL (14, 2) NULL,
    [DeadInYard_wt]              DECIMAL (14, 2) NULL,
    [CondemnedByPacker_wt]       DECIMAL (14, 2) NULL,
    [Condemned_wt]               DECIMAL (14, 2) NULL,
    [euthanized_Qty]             INT             NULL,
    [Deadb4Grade_Death_Qty]      INT             NULL,
    [euthanized_wt]              NUMERIC (14, 2) NULL,
    [Deadb4Grade_Death_wt]       NUMERIC (14, 2) NULL,
    [ReportingGroupID]           INT             NULL,
    CONSTRAINT [PK__cft_PIG_GROUP_RO__76CBA758] PRIMARY KEY CLUSTERED ([TaskID] ASC) WITH (FILLFACTOR = 100)
);

