CREATE TABLE [dbo].[cft_AR_CORN_TICKET] (
    [ARTicketID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TicketID]                   INT             NULL,
    [TicketNumber]               VARCHAR (20)    NULL,
    [TicketStatusID]             INT             NULL,
    [FeedMillID]                 CHAR (10)       NULL,
    [CornProducerID]             VARCHAR (15)    NULL,
    [DeliveryDate]               DATETIME        NULL,
    [SourceFarm]                 VARCHAR (20)    NULL,
    [SourceFarmBin]              VARCHAR (20)    NULL,
    [DestinationFarmBin]         VARCHAR (20)    NULL,
    [Status]                     VARCHAR (20)    NULL,
    [PaymentTypeID]              INT             NULL,
    [Commodity]                  VARCHAR (20)    NULL,
    [Moisture]                   DECIMAL (18, 4) NULL,
    [ForeignMaterial]            DECIMAL (18, 4) NULL,
    [OilContent]                 DECIMAL (18, 4) NULL,
    [TestWeight]                 DECIMAL (18, 4) NULL,
    [Gross]                      DECIMAL (18, 4) NULL,
    [Net]                        DECIMAL (18, 4) NULL,
    [Comments]                   VARCHAR (2000)  NULL,
    [ManuallyEntered]            BIT             NULL,
    [SentToDryer]                BIT             NULL,
    [MoistureRateVersion]        INT             NULL,
    [ForeignMaterialRateVersion] INT             NULL,
    [OilContentRateVersion]      INT             NULL,
    [TestWeightRateVersion]      INT             NULL,
    [DryingRateVersion]          INT             NULL,
    [HandlingFeeVersion]         INT             NULL,
    [DeferredPaymentVersion]     INT             NULL,
    [CornCheckOffVersion]        INT             NULL,
    [EthanolCheckOffVersion]     INT             NULL,
    [ShrinkVersion]              INT             NULL,
    [TicketReminderNote]         VARCHAR (2000)  NULL,
    [CornProducerComments]       VARCHAR (2000)  NULL,
    [CreatedDateTime]            DATETIME        NULL,
    [CreatedBy]                  VARCHAR (50)    NULL,
    [UpdatedDateTime]            DATETIME        NULL,
    [UpdatedBy]                  VARCHAR (50)    NULL,
    [RowChangeTypeID]            TINYINT         NOT NULL,
    [UserName]                   NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CORN_TICKET_UserName] DEFAULT (suser_sname()) NOT NULL,
    [HostName]                   NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CORN_TICKET_HostName] DEFAULT (host_name()) NOT NULL,
    [AppName]                    NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CORN_TICKET_AppName] DEFAULT (app_name()) NOT NULL,
    [TimeStamp]                  DATETIME        CONSTRAINT [DF_cft_AR_CORN_TICKET_TimeStamp] DEFAULT (getdate()) NOT NULL,
    [CommodityID]                TINYINT         NULL,
    CONSTRAINT [PK_AR_CORN_TICKET] PRIMARY KEY CLUSTERED ([ARTicketID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_cft_AR_CORN_TICKET_cft_ROW_CHANGE_TYPE] FOREIGN KEY ([RowChangeTypeID]) REFERENCES [dbo].[cft_ROW_CHANGE_TYPE] ([RowChangeTypeID])
);

