CREATE TABLE [dbo].[cft_AR_CONTRACT] (
    [AR_ContractID]          INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ContractID]             INT             NULL,
    [FeedMillID]             CHAR (10)       NULL,
    [CornProducerID]         VARCHAR (30)    NULL,
    [ContractNumber]         VARCHAR (100)   NULL,
    [SequenceNumber]         INT             NULL,
    [SubsequenceNumber]      TINYINT         NULL,
    [CommodityID]            TINYINT         NULL,
    [Priority]               INT             NULL,
    [DateEstablished]        SMALLDATETIME   NULL,
    [DueDateFrom]            SMALLDATETIME   NULL,
    [DueDateTo]              SMALLDATETIME   NULL,
    [Bushels]                DECIMAL (18, 4) NOT NULL,
    [Cash]                   MONEY           NULL,
    [Premium_Deduct]         MONEY           NULL,
    [PricedBasis]            MONEY           NULL,
    [FuturesBasis]           MONEY           NULL,
    [Comments]               VARCHAR (60)    NULL,
    [PayToCornProducerID]    VARCHAR (15)    NULL,
    [Returned]               BIT             NULL,
    [ContractStatusID]       TINYINT         NULL,
    [ContractTypeID]         TINYINT         NULL,
    [Futures]                MONEY           NULL,
    [BasisYear]              SMALLINT        NULL,
    [BasisMonth]             TINYINT         NULL,
    [FuturesYear]            SMALLINT        NULL,
    [FuturesMonth]           TINYINT         NULL,
    [CRMContractID]          VARCHAR (10)    NULL,
    [ChangeReasonID]         TINYINT         NULL,
    [ContractAdjustment]     MONEY           NULL,
    [SettlementDate]         DATETIME        NULL,
    [Offer]                  MONEY           NULL,
    [_RowVersion]            INT             NULL,
    [RowChangeTypeID]        TINYINT         NOT NULL,
    [CreatedDateTime]        DATETIME        NULL,
    [CreatedBy]              VARCHAR (50)    NULL,
    [UpdatedDateTime]        DATETIME        NULL,
    [UpdatedBy]              VARCHAR (50)    NULL,
    [UserName]               NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CONTRACT_UserName] DEFAULT (suser_sname()) NOT NULL,
    [HostName]               NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CONTRACT_HostName] DEFAULT (host_name()) NOT NULL,
    [AppName]                NVARCHAR (128)  CONSTRAINT [DF_cft_AR_CONTRACT_AppName] DEFAULT (app_name()) NOT NULL,
    [TimeStamp]              DATETIME        CONSTRAINT [DF_cft_AR_CONTRACT_TimeStamp] DEFAULT (getdate()) NOT NULL,
    [LastContractTypeID]     INT             NULL,
    [ContractTypeChangeDate] DATETIME        NULL,
    [DeferredPaymentDate]    DATETIME        NULL,
    [OriginalContractNumber] VARCHAR (50)    NULL,
    [PricingStartDate]       SMALLDATETIME   NULL,
    CONSTRAINT [PK_cft_AR_CONTRACT] PRIMARY KEY CLUSTERED ([AR_ContractID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_cft_AR_CONTRACT_cft_ROW_CHANGE_TYPE] FOREIGN KEY ([RowChangeTypeID]) REFERENCES [dbo].[cft_ROW_CHANGE_TYPE] ([RowChangeTypeID])
);

