CREATE TABLE [dbo].[cft_AR_DAILY_PRICE_DETAIL] (
    [ARDailyPriceDetailID] INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DailyPriceDetailID]   INT             NULL,
    [DailyPriceID]         INT             NULL,
    [DeliveryMonth]        TINYINT         NULL,
    [DeliveryYear]         SMALLINT        NULL,
    [OptionMonth]          TINYINT         NULL,
    [NonClassicalTrade]    BIT             NULL,
    [CBOTCornClose]        DECIMAL (20, 4) NULL,
    [CBOTChange]           DECIMAL (20, 4) NULL,
    [CompetitorBasis]      DECIMAL (20, 4) NULL,
    [CompetitorFreight]    DECIMAL (20, 4) NULL,
    [Adj]                  DECIMAL (20, 4) NULL,
    [NoBid]                BIT             NULL,
    [DeliveryDate]         VARCHAR (50)    NULL,
    [CreatedDateTime]      DATETIME        NULL,
    [CreatedBy]            VARCHAR (50)    NULL,
    [UpdatedDateTime]      DATETIME        NULL,
    [UpdatedBy]            VARCHAR (50)    NULL,
    [RowChangeTypeID]      TINYINT         NOT NULL,
    [UserName]             NVARCHAR (128)  CONSTRAINT [DF_cft_AR_DAILY_PRICE_DETAIL_UserName] DEFAULT (suser_sname()) NOT NULL,
    [HostName]             NVARCHAR (128)  CONSTRAINT [DF_cft_AR_DAILY_PRICE_DETAIL_HostName] DEFAULT (host_name()) NOT NULL,
    [AppName]              NVARCHAR (128)  CONSTRAINT [DF_cft_AR_DAILY_PRICE_DETAIL_AppName] DEFAULT (app_name()) NOT NULL,
    [TimeStamp]            DATETIME        CONSTRAINT [DF_cft_AR_DAILY_PRICE_DETAIL_TimeStamp] DEFAULT (getdate()) NOT NULL,
    [Price]                DECIMAL (20, 4) NULL,
    [DeliveryDateFrom]     DATETIME        NULL,
    [DeliveryDateTo]       DATETIME        NULL,
    CONSTRAINT [PK_cft_AR_DAILY_PRICE_DETAIL] PRIMARY KEY CLUSTERED ([ARDailyPriceDetailID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_cft_AR_DAILY_PRICE_DETAIL_cft_ROW_CHANGE_TYPE] FOREIGN KEY ([RowChangeTypeID]) REFERENCES [dbo].[cft_ROW_CHANGE_TYPE] ([RowChangeTypeID])
);

