CREATE LOGIN [SLWSAPP]
    WITH PASSWORD = N'teu|mwUznvvjbzbtqjrVvcfvmsFT7_&#$!~<Iz Gaelpfrnn', SID = 0x8CE3100BD929FD4794944EDF0CBFB9DB, DEFAULT_DATABASE = [SolomonApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

