CREATE LOGIN [ApplicationCenter]
    WITH PASSWORD = N'zgpCn@fjLnZjwsoxlLdccpjEmsFT7_&#$!~<i~q7vdXhvx+U', SID = 0x6C7FFE344536DE4A8486FA4522DA68AA, DEFAULT_DATABASE = [CFApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

