CREATE LOGIN [SLWSAPP]
    WITH PASSWORD = N'=Brvrbs|7mGffkkmxkzx~CsPmsFT7_&#$!~<zbocuqo3imPm', SID = 0x8CE3100BD929FD4794944EDF0CBFB9DB, DEFAULT_DATABASE = [SolomonApp], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

