CREATE TABLE [deleted].[CFT_FARMANIMAL](
	[ID] [nvarchar](36) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[CREATED_BY] [bigint] NOT NULL,
	[LAST_UPDATED_BY] [bigint] NOT NULL,
	[DELETED_BY] [bigint] NOT NULL,
	[FARMID] [nvarchar](36) NULL,
	[ANIMALID] [nvarchar](36) NULL,
	[ENTRYDATE] [datetime] NULL,
	[REMOVALDATE] [datetime] NULL,
 CONSTRAINT [CFT_FARMANIMAL_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO