CREATE TABLE [deleted].[CFT_ANIMALTAG](
	[ID] [nvarchar](36) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[LAST_UPDATE] [datetime] NOT NULL,
	[CREATED_BY] [bigint] NOT NULL,
	[LAST_UPDATED_BY] [bigint] NOT NULL,
	[DELETED_BY] [bigint] NOT NULL,
	[ANIMALID] [nvarchar](36) NULL,
	[TAGNBR] [nvarchar](20) NULL,
	[TAGDATE] [datetime] NULL,
	[PRIMARYTAG] [int] NULL,
	[ISCURRENT] [int] NULL,
	[QRCODE] [image] NULL,
	[QRCODETYPE] [nvarchar](20) NULL,
	[DEVICEFARMID] [nvarchar](36) NULL,
 CONSTRAINT [CFT_ANIMALTAG_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



