CREATE TABLE [dbo].[AppModule] (
    [AppModuleID] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Description] VARCHAR (30) NULL,
    CONSTRAINT [PK_AppModule] PRIMARY KEY CLUSTERED ([AppModuleID] ASC) WITH (FILLFACTOR = 90)
);

