CREATE VIEW [caredata].[ARRIVAL_DISPOSAL_DATE_VW]
AS
SELECT * FROM [caredata].[ARRIVAL_DISPOSAL_DATE_SEMEN_COLLECTIONS_VW] 
UNION 
SELECT * FROM [caredata].[ARRIVAL_DISPOSAL_DATE_SEMEN_DELIVERIES_VW] 
UNION 
SELECT * FROM [caredata].[ARRIVAL_DISPOSAL_REPRODUCTIVE_VW] 
