CREATE TABLE [dbo].[cft_PARTIAL_TICKET] (
    [PartialTicketID]        INT             IDENTITY (1, 1) NOT NULL,
    [TicketNumber]           VARCHAR (20)    NOT NULL,
    [FullTicketID]           INT             NOT NULL,
    [ContractID]             INT             NULL,
    [DeliveryDate]           DATETIME        NOT NULL,
    [DryBushels]             DECIMAL (18, 4) NOT NULL,
    [MoistureRateAdj]        MONEY           NULL,
    [ForeignMaterialRateAdj] MONEY           NULL,
    [TestWeightRateAdj]      MONEY           NULL,
    [DryingRateAdj]          MONEY           NULL,
    [HandlingRateAdj]        MONEY           NULL,
    [DeferredPaymentRateAdj] MONEY           NULL,
    [MiscAdj]                MONEY           NULL,
    [MiscAdjNote]            VARCHAR (60)    NULL,
    [ContractAdjustmentRate] MONEY           NULL,
    [PaymentTypeID]          INT             NULL,
    [QuoteID]                INT             NULL,
    [PaymentTermsID]         CHAR (2)        NULL,
    [TicketAdjNote]          VARCHAR (1000)  NULL,
    [CornProducerID]         VARCHAR (15)    NOT NULL,
    [ReadyToBeReleased]      BIT             NOT NULL,
    [CreatedDateTime]        DATETIME        NOT NULL,
    [CreatedBy]              VARCHAR (50)    NOT NULL,
    [UpdatedDateTime]        DATETIME        NULL,
    [UpdatedBy]              VARCHAR (50)    NULL,
    [DeliveryCornProducerID] VARCHAR (15)    NULL,
    [PartialTicketStatusID]  INT             NOT NULL,
    [SentToInventory]        BIT             NOT NULL,
    [SentToAccountsPayable]  BIT             NOT NULL,
    [WetBushels]             DECIMAL (20, 4) NOT NULL,
    [DailyPriceDetailID]     INT             NULL
);

