CREATE TABLE [dbo].[cft_CORN_TICKET] (
    [TicketID]                   INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TicketNumber]               VARCHAR (20)    NOT NULL,
    [TicketStatusID]             INT             NOT NULL,
    [FeedMillID]                 CHAR (10)       NULL,
    [CornProducerID]             VARCHAR (15)    NOT NULL,
    [DeliveryDate]               DATETIME        NULL,
    [SourceFarm]                 VARCHAR (20)    NULL,
    [SourceFarmBin]              VARCHAR (20)    NULL,
    [DestinationFarmBin]         VARCHAR (20)    NULL,
    [Status]                     VARCHAR (20)    NULL,
    [PaymentTypeID]              INT             NULL,
    [Commodity]                  VARCHAR (20)    NULL,
    [CommodityID]                TINYINT         NULL,
    [Moisture]                   DECIMAL (18, 4) NULL,
    [ForeignMaterial]            DECIMAL (18, 4) NULL,
    [OilContent]                 DECIMAL (18, 4) NULL,
    [TestWeight]                 DECIMAL (18, 4) NULL,
    [Gross]                      DECIMAL (18, 4) NULL,
    [Net]                        DECIMAL (18, 4) NULL,
    [Comments]                   VARCHAR (2000)  NULL,
    [ManuallyEntered]            BIT             NULL,
    [SentToDryer]                BIT             NULL,
    [MoistureRateVersion]        INT             NULL,
    [ForeignMaterialRateVersion] INT             NULL,
    [OilContentRateVersion]      INT             NULL,
    [TestWeightRateVersion]      INT             NULL,
    [DryingRateVersion]          INT             NULL,
    [HandlingFeeVersion]         INT             NULL,
    [DeferredPaymentVersion]     INT             NULL,
    [CornCheckOffVersion]        INT             NULL,
    [EthanolCheckOffVersion]     INT             NULL,
    [ShrinkVersion]              INT             NULL,
    [TicketReminderNote]         VARCHAR (2000)  NULL,
    [CornProducerComments]       VARCHAR (2000)  NULL,
    [CreatedDateTime]            DATETIME        NOT NULL,
    [CreatedBy]                  VARCHAR (50)    NOT NULL,
    [UpdatedDateTime]            DATETIME        NULL,
    [UpdatedBy]                  VARCHAR (50)    NULL,
    CONSTRAINT [PK_CORN_TICKET] PRIMARY KEY CLUSTERED ([TicketID] ASC) WITH (FILLFACTOR = 80)
);

