CREATE TABLE [dbo].[smManufacturer] (
    [Addr1]              CHAR (60)     NOT NULL,
    [Addr2]              CHAR (60)     NOT NULL,
    [Auth]               SMALLINT      NOT NULL,
    [AuthorizationLimit] FLOAT (53)    NOT NULL,
    [City]               CHAR (30)     NOT NULL,
    [Contact]            CHAR (30)     NOT NULL,
    [Country]            CHAR (3)      NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME NOT NULL,
    [Crtd_Prog]          CHAR (8)      NOT NULL,
    [Crtd_User]          CHAR (10)     NOT NULL,
    [Fax]                CHAR (15)     NOT NULL,
    [Labor]              SMALLINT      NOT NULL,
    [LaborIncluded]      SMALLINT      NOT NULL,
    [LaborType]          CHAR (1)      NOT NULL,
    [Lupd_DateTime]      SMALLDATETIME NOT NULL,
    [Lupd_Prog]          CHAR (8)      NOT NULL,
    [Lupd_User]          CHAR (10)     NOT NULL,
    [ManufId]            CHAR (10)     NOT NULL,
    [Material]           SMALLINT      NOT NULL,
    [MaterialType]       CHAR (1)      NOT NULL,
    [Name]               CHAR (60)     NOT NULL,
    [NoteId]             INT           NOT NULL,
    [PartsIncluded]      SMALLINT      NOT NULL,
    [Phone]              CHAR (15)     NOT NULL,
    [RmaRequired]        SMALLINT      NOT NULL,
    [State]              CHAR (3)      NOT NULL,
    [User1]              CHAR (30)     NOT NULL,
    [User2]              CHAR (30)     NOT NULL,
    [User3]              FLOAT (53)    NOT NULL,
    [User4]              FLOAT (53)    NOT NULL,
    [User5]              CHAR (10)     NOT NULL,
    [User6]              CHAR (10)     NOT NULL,
    [User7]              SMALLDATETIME NOT NULL,
    [User8]              SMALLDATETIME NOT NULL,
    [Vendid]             CHAR (15)     NOT NULL,
    [WarrantyMonths]     SMALLINT      NOT NULL,
    [Zip]                CHAR (10)     NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [smManufacturer0] PRIMARY KEY CLUSTERED ([ManufId] ASC) WITH (FILLFACTOR = 90)
);

