CREATE TABLE [dbo].[smModel] (
    [AgeCode]       CHAR (10)     NOT NULL,
    [COGSAcct]      CHAR (10)     NOT NULL,
    [COGSSubAcct]   CHAR (24)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Depth]         FLOAT (53)    NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [EquipmentType] CHAR (10)     NOT NULL,
    [Height]        FLOAT (53)    NOT NULL,
    [Labor]         SMALLINT      NOT NULL,
    [LaborIncl]     SMALLINT      NOT NULL,
    [LaborType]     CHAR (1)      NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [ManufId]       CHAR (10)     NOT NULL,
    [Material]      SMALLINT      NOT NULL,
    [MaterialIncl]  SMALLINT      NOT NULL,
    [MaterialType]  CHAR (1)      NOT NULL,
    [ModelId]       CHAR (40)     NOT NULL,
    [NoteId]        INT           NOT NULL,
    [PMCode]        CHAR (10)     NOT NULL,
    [Price]         FLOAT (53)    NOT NULL,
    [RevAcct]       CHAR (10)     NOT NULL,
    [RevSubAcct]    CHAR (24)     NOT NULL,
    [RMARequired]   SMALLINT      NOT NULL,
    [SkillId]       CHAR (10)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [Weight]        FLOAT (53)    NOT NULL,
    [Width]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smModel0] PRIMARY KEY CLUSTERED ([ManufId] ASC, [ModelId] ASC) WITH (FILLFACTOR = 90)
);

