CREATE TABLE [dbo].[BUSetup] (
    [AllowMasking]   SMALLINT      NOT NULL,
    [BudgetLedgerID] CHAR (10)     NOT NULL,
    [BudgetYear]     CHAR (4)      NOT NULL,
    [CpnyID]         CHAR (10)     NOT NULL,
    [CreateSubAccts] SMALLINT      NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Descr]          CHAR (30)     NOT NULL,
    [Include13]      SMALLINT      NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [NumberSegments] SMALLINT      NOT NULL,
    [S4Future01]     CHAR (30)     NOT NULL,
    [S4Future02]     CHAR (30)     NOT NULL,
    [S4Future03]     CHAR (10)     NOT NULL,
    [S4Future04]     CHAR (10)     NOT NULL,
    [S4Future05]     SMALLINT      NOT NULL,
    [S4Future06]     SMALLINT      NOT NULL,
    [S4Future07]     SMALLDATETIME NOT NULL,
    [S4Future08]     SMALLDATETIME NOT NULL,
    [S4Future09]     CHAR (1)      NOT NULL,
    [S4Future10]     CHAR (1)      NOT NULL,
    [SubSeg00]       SMALLINT      NOT NULL,
    [SubSeg01]       SMALLINT      NOT NULL,
    [SubSeg02]       SMALLINT      NOT NULL,
    [SubSeg03]       SMALLINT      NOT NULL,
    [SubSeg04]       SMALLINT      NOT NULL,
    [SubSeg05]       SMALLINT      NOT NULL,
    [SubSeg06]       SMALLINT      NOT NULL,
    [SubSeg07]       SMALLINT      NOT NULL,
    [SubSegMask00]   CHAR (24)     NOT NULL,
    [SubSegMask01]   CHAR (24)     NOT NULL,
    [SubSegMask02]   CHAR (24)     NOT NULL,
    [SubSegMask03]   CHAR (24)     NOT NULL,
    [SubSegMask04]   CHAR (24)     NOT NULL,
    [SubSegMask05]   CHAR (24)     NOT NULL,
    [SubSegMask06]   CHAR (24)     NOT NULL,
    [SubSegMask07]   CHAR (24)     NOT NULL,
    [Type]           CHAR (1)      NOT NULL,
    [UseBdgtGroups]  SMALLINT      NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLINT      NOT NULL,
    [User8]          SMALLINT      NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [BUSetup0] PRIMARY KEY NONCLUSTERED ([CpnyID] ASC, [BudgetLedgerID] ASC) WITH (FILLFACTOR = 90)
);

