CREATE TABLE [dbo].[RQSetup] (
    [AutoNbrItem]   SMALLINT      NOT NULL,
    [AutoNbrReq]    SMALLINT      NOT NULL,
    [BillAddr1]     CHAR (60)     NOT NULL,
    [BillAddr2]     CHAR (60)     NOT NULL,
    [BillAttn]      CHAR (30)     NOT NULL,
    [BillCity]      CHAR (30)     NOT NULL,
    [BillCountry]   CHAR (3)      NOT NULL,
    [BillEmail]     CHAR (80)     NOT NULL,
    [BillFax]       CHAR (30)     NOT NULL,
    [BillName]      CHAR (60)     NOT NULL,
    [BillPhone]     CHAR (30)     NOT NULL,
    [BillState]     CHAR (3)      NOT NULL,
    [BillZip]       CHAR (10)     NOT NULL,
    [BudgetWarn]    CHAR (1)      NOT NULL,
    [CRPercent]     SMALLINT      NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [EMailType]     CHAR (1)      NOT NULL,
    [Init]          SMALLINT      NOT NULL,
    [LastItemReq]   CHAR (10)     NOT NULL,
    [LastReqNbr]    CHAR (10)     NOT NULL,
    [LedgerId]      CHAR (10)     NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [PerRetItm]     SMALLINT      NOT NULL,
    [PerRetReq]     SMALLINT      NOT NULL,
    [S4Future1]     CHAR (30)     NOT NULL,
    [S4Future2]     CHAR (30)     NOT NULL,
    [S4Future3]     FLOAT (53)    NOT NULL,
    [S4Future4]     FLOAT (53)    NOT NULL,
    [S4Future5]     FLOAT (53)    NOT NULL,
    [S4Future6]     FLOAT (53)    NOT NULL,
    [S4Future7]     SMALLDATETIME NOT NULL,
    [S4Future8]     SMALLDATETIME NOT NULL,
    [S4Future9]     INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [SetupID]       CHAR (2)      NOT NULL,
    [ShipAddr1]     CHAR (60)     NOT NULL,
    [ShipAddr2]     CHAR (60)     NOT NULL,
    [ShipAttn]      CHAR (30)     NOT NULL,
    [ShipCity]      CHAR (30)     NOT NULL,
    [ShipCountry]   CHAR (3)      NOT NULL,
    [ShipEmail]     CHAR (80)     NOT NULL,
    [ShipFax]       CHAR (30)     NOT NULL,
    [ShipName]      CHAR (60)     NOT NULL,
    [ShipPhone]     CHAR (30)     NOT NULL,
    [ShipState]     CHAR (3)      NOT NULL,
    [ShipZip]       CHAR (10)     NOT NULL,
    [SolomonEMail]  CHAR (80)     NOT NULL,
    [SubAcctSeg]    CHAR (2)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [ZUser1]        CHAR (1)      NOT NULL,
    [ZUser2]        CHAR (1)      NOT NULL,
    [ZUser3]        CHAR (1)      NOT NULL,
    [ZUser4]        CHAR (1)      NOT NULL,
    [ZUser5]        CHAR (1)      NOT NULL,
    [ZUser6]        CHAR (1)      NOT NULL,
    [ZUser7]        CHAR (1)      NOT NULL,
    [ZUser8]        CHAR (1)      NOT NULL,
    [ZUserDet1]     CHAR (1)      NOT NULL,
    [ZUserDet2]     CHAR (1)      NOT NULL,
    [ZUserDet3]     CHAR (1)      NOT NULL,
    [ZUserDet4]     CHAR (1)      NOT NULL,
    [ZUserDet5]     CHAR (1)      NOT NULL,
    [ZUserDet6]     CHAR (1)      NOT NULL,
    [ZUserDet7]     CHAR (1)      NOT NULL,
    [ZUserDet8]     CHAR (1)      NOT NULL,
    [ZZAccount]     CHAR (1)      NOT NULL,
    [ZZAllowVend]   CHAR (1)      NOT NULL,
    [ZZAppvType]    CHAR (1)      NOT NULL,
    [ZZDeptMaint]   CHAR (1)      NOT NULL,
    [ZZEnableBid]   CHAR (1)      NOT NULL,
    [ZZSubAccount]  CHAR (1)      NOT NULL,
    [ZZUseWinFax]   CHAR (1)      NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RQSetup0]
    ON [dbo].[RQSetup]([SetupID] ASC);

