CREATE TABLE [dbo].[PJRTAB] (
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [l1_rate_key1_cd] CHAR (4)      NOT NULL,
    [l1_rate_key2_cd] CHAR (4)      NOT NULL,
    [l1_rate_key3_cd] CHAR (4)      NOT NULL,
    [l2_rate_key1_cd] CHAR (4)      NOT NULL,
    [l2_rate_key2_cd] CHAR (4)      NOT NULL,
    [l2_rate_key3_cd] CHAR (4)      NOT NULL,
    [l3_rate_key1_cd] CHAR (4)      NOT NULL,
    [l3_rate_key2_cd] CHAR (4)      NOT NULL,
    [l3_rate_key3_cd] CHAR (4)      NOT NULL,
    [l4_rate_key1_cd] CHAR (4)      NOT NULL,
    [l4_rate_key2_cd] CHAR (4)      NOT NULL,
    [l4_rate_key3_cd] CHAR (4)      NOT NULL,
    [l5_rate_key1_cd] CHAR (4)      NOT NULL,
    [l5_rate_key2_cd] CHAR (4)      NOT NULL,
    [l5_rate_key3_cd] CHAR (4)      NOT NULL,
    [l6_rate_key1_cd] CHAR (4)      NOT NULL,
    [l6_rate_key2_cd] CHAR (4)      NOT NULL,
    [l6_rate_key3_cd] CHAR (4)      NOT NULL,
    [l7_rate_key1_cd] CHAR (4)      NOT NULL,
    [l7_rate_key2_cd] CHAR (4)      NOT NULL,
    [l7_rate_key3_cd] CHAR (4)      NOT NULL,
    [l8_rate_key1_cd] CHAR (4)      NOT NULL,
    [l8_rate_key2_cd] CHAR (4)      NOT NULL,
    [l8_rate_key3_cd] CHAR (4)      NOT NULL,
    [l9_rate_key1_cd] CHAR (4)      NOT NULL,
    [l9_rate_key2_cd] CHAR (4)      NOT NULL,
    [l9_rate_key3_cd] CHAR (4)      NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [rate_table_id]   CHAR (4)      NOT NULL,
    [rate_type_cd]    CHAR (2)      NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjrtab0] PRIMARY KEY CLUSTERED ([rate_table_id] ASC, [rate_type_cd] ASC) WITH (FILLFACTOR = 90)
);

