CREATE TABLE [dbo].[EmpTimeApprove] (
    [Action]           CHAR (20)      NOT NULL,
    [Action_DateTime]  SMALLDATETIME  NOT NULL,
    [Approver]         CHAR (10)      NOT NULL,
    [Billable]         CHAR (1)       NOT NULL,
    [ChkSeq]           CHAR (2)       NOT NULL,
    [Comment]          VARCHAR (1000) NOT NULL,
    [CpnyID]           CHAR (10)      NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME  NOT NULL,
    [Crtd_Prog]        CHAR (8)       NOT NULL,
    [Crtd_User]        CHAR (10)      NOT NULL,
    [EarnType]         CHAR (10)      NOT NULL,
    [EmpId]            CHAR (10)      NOT NULL,
    [EmpName]          CHAR (30)      NOT NULL,
    [LineId]           INT            NOT NULL,
    [LineNbr]          SMALLINT       NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME  NOT NULL,
    [LUpd_Prog]        CHAR (8)       NOT NULL,
    [LUpd_User]        CHAR (10)      NOT NULL,
    [ProjectID]        CHAR (16)      NOT NULL,
    [Qty]              FLOAT (53)     NOT NULL,
    [RateMult]         FLOAT (53)     NOT NULL,
    [RecordID]         INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RefNbr]           CHAR (10)      NOT NULL,
    [S4Future01]       CHAR (30)      NOT NULL,
    [S4Future02]       CHAR (30)      NOT NULL,
    [S4Future03]       FLOAT (53)     NOT NULL,
    [S4Future04]       FLOAT (53)     NOT NULL,
    [S4Future05]       FLOAT (53)     NOT NULL,
    [S4Future06]       FLOAT (53)     NOT NULL,
    [S4Future07]       SMALLDATETIME  NOT NULL,
    [S4Future08]       SMALLDATETIME  NOT NULL,
    [S4Future09]       INT            NOT NULL,
    [S4Future10]       INT            NOT NULL,
    [S4Future11]       CHAR (10)      NOT NULL,
    [S4Future12]       CHAR (10)      NOT NULL,
    [SS_BillableHours] FLOAT (53)     NOT NULL,
    [SS_ContractID]    CHAR (10)      NOT NULL,
    [SS_EquipmentID]   CHAR (10)      NOT NULL,
    [SS_ExtPrice]      FLOAT (53)     NOT NULL,
    [SS_InvtLocId]     CHAR (10)      NOT NULL,
    [SS_LineTypes]     CHAR (1)       NOT NULL,
    [SS_LineItemID]    CHAR (30)      NOT NULL,
    [SS_PostFlag]      CHAR (1)       NOT NULL,
    [SS_ServiceCallID] CHAR (10)      NOT NULL,
    [SS_UnitPrice]     FLOAT (53)     NOT NULL,
    [StdUnitRate]      FLOAT (53)     NOT NULL,
    [TaskID]           CHAR (32)      NOT NULL,
    [TranDate]         SMALLDATETIME  NOT NULL,
    [User1]            CHAR (30)      NOT NULL,
    [User2]            CHAR (30)      NOT NULL,
    [User3]            FLOAT (53)     NOT NULL,
    [User4]            FLOAT (53)     NOT NULL,
    [User5]            CHAR (10)      NOT NULL,
    [User6]            CHAR (10)      NOT NULL,
    [User7]            SMALLDATETIME  NOT NULL,
    [User8]            SMALLDATETIME  NOT NULL,
    [WorkComp]         CHAR (6)       NOT NULL,
    [WrkLocId]         CHAR (6)       NOT NULL,
    [tstamp]           ROWVERSION     NOT NULL,
    CONSTRAINT [EmpTimeApprove0] PRIMARY KEY CLUSTERED ([RecordID] ASC)
);

