CREATE TABLE [dbo].[BRBatTran] (
    [BatTranID]     CHAR (40)     NOT NULL,
    [Transfered]    SMALLINT      NOT NULL,
    [ARBatNbr]      CHAR (10)     NOT NULL,
    [AcctID]        CHAR (10)     NOT NULL,
    [ClearDate]     SMALLDATETIME NOT NULL,
    [Cleared]       SMALLINT      NOT NULL,
    [CpnyId]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CurrPerNbr]    CHAR (6)      NOT NULL,
    [CuryId]        CHAR (4)      NOT NULL,
    [CuryMultDiv]   CHAR (1)      NOT NULL,
    [CuryRate]      FLOAT (53)    NOT NULL,
    [CuryTranAmt]   FLOAT (53)    NOT NULL,
    [FutureC1]      CHAR (30)     NOT NULL,
    [FutureD1]      SMALLDATETIME NOT NULL,
    [FutureF1]      FLOAT (53)    NOT NULL,
    [FutureI1]      INT           NOT NULL,
    [FutureL1]      SMALLINT      NOT NULL,
    [LineNbr]       SMALLINT      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [MainKey]       CHAR (40)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [OrigBatNbr]    CHAR (10)     NOT NULL,
    [OrigID]        CHAR (10)     NOT NULL,
    [OrigLineNbr]   SMALLINT      NOT NULL,
    [OrigModule]    CHAR (2)      NOT NULL,
    [OrigRefNbr]    CHAR (10)     NOT NULL,
    [PerClosed]     CHAR (6)      NOT NULL,
    [PerEnt]        CHAR (6)      NOT NULL,
    [PerPost]       CHAR (6)      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [SetUpID]       CHAR (4)      NOT NULL,
    [TranAmt]       FLOAT (53)    NOT NULL,
    [TranDate]      SMALLDATETIME NOT NULL,
    [TranDescr]     CHAR (30)     NOT NULL,
    [UserC1]        CHAR (30)     NOT NULL,
    [UserC2]        CHAR (30)     NOT NULL,
    [UserC3]        CHAR (10)     NOT NULL,
    [UserC4]        CHAR (10)     NOT NULL,
    [UserD1]        SMALLDATETIME NOT NULL,
    [UserD2]        SMALLDATETIME NOT NULL,
    [UserF1]        FLOAT (53)    NOT NULL,
    [UserF2]        FLOAT (53)    NOT NULL,
    [UserI1]        INT           NOT NULL,
    [UserI2]        INT           NOT NULL,
    [UserL1]        SMALLINT      NOT NULL,
    [UserL2]        SMALLINT      NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [BRBatTran0] PRIMARY KEY CLUSTERED ([AcctID] ASC, [CurrPerNbr] ASC, [MainKey] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BRBatTran1]
    ON [dbo].[BRBatTran]([AcctID] ASC, [ARBatNbr] ASC, [MainKey] ASC) WITH (FILLFACTOR = 90);

