CREATE TABLE [dbo].[INTranHoldPICT] (
    [Acct]            CHAR (10)     NOT NULL,
    [AcctDist]        SMALLINT      NOT NULL,
    [ARLineID]        INT           NOT NULL,
    [ARLineRef]       CHAR (5)      NOT NULL,
    [BatNbr]          CHAR (10)     NOT NULL,
    [BMICuryID]       CHAR (4)      NOT NULL,
    [BMIEffDate]      SMALLDATETIME NOT NULL,
    [BMIExtCost]      FLOAT (53)    NOT NULL,
    [BMIMultDiv]      CHAR (1)      NOT NULL,
    [BMIRate]         FLOAT (53)    NOT NULL,
    [BMIRtTp]         CHAR (6)      NOT NULL,
    [BMITranAmt]      FLOAT (53)    NOT NULL,
    [BMIUnitPrice]    FLOAT (53)    NOT NULL,
    [CmmnPct]         FLOAT (53)    NOT NULL,
    [CnvFact]         FLOAT (53)    NOT NULL,
    [COGSAcct]        CHAR (10)     NOT NULL,
    [COGSSub]         CHAR (24)     NOT NULL,
    [CostType]        CHAR (8)      NOT NULL,
    [CpnyID]          CHAR (10)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [DrCr]            CHAR (1)      NOT NULL,
    [Excpt]           SMALLINT      NOT NULL,
    [ExtCost]         FLOAT (53)    NOT NULL,
    [ExtRefNbr]       CHAR (15)     NOT NULL,
    [FiscYr]          CHAR (4)      NOT NULL,
    [FlatRateLineNbr] SMALLINT      NOT NULL,
    [ID]              CHAR (10)     NOT NULL,
    [InsuffQty]       SMALLINT      NOT NULL,
    [InvtAcct]        CHAR (10)     NOT NULL,
    [InvtID]          CHAR (30)     NOT NULL,
    [InvtMult]        SMALLINT      NOT NULL,
    [InvtSub]         CHAR (24)     NOT NULL,
    [IRProcessed]     SMALLINT      NOT NULL,
    [JrnlType]        CHAR (3)      NOT NULL,
    [KitID]           CHAR (30)     NOT NULL,
    [KitStdQty]       FLOAT (53)    NOT NULL,
    [LayerType]       CHAR (1)      NOT NULL,
    [LineID]          INT           NOT NULL,
    [LineNbr]         SMALLINT      NOT NULL,
    [LineRef]         CHAR (5)      NOT NULL,
    [LotSerCntr]      SMALLINT      NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [OrigBatNbr]      CHAR (10)     NOT NULL,
    [OrigJrnlType]    CHAR (3)      NOT NULL,
    [OrigLineRef]     CHAR (5)      NOT NULL,
    [OrigRefNbr]      CHAR (10)     NOT NULL,
    [OvrhdAmt]        FLOAT (53)    NOT NULL,
    [OvrhdFlag]       SMALLINT      NOT NULL,
    [PC_Flag]         CHAR (1)      NOT NULL,
    [PC_ID]           CHAR (20)     NOT NULL,
    [PC_Status]       CHAR (1)      NOT NULL,
    [PerEnt]          CHAR (6)      NOT NULL,
    [PerPost]         CHAR (6)      NOT NULL,
    [PostingOption]   SMALLINT      NOT NULL,
    [ProjectID]       CHAR (16)     NOT NULL,
    [Qty]             FLOAT (53)    NOT NULL,
    [QtyUnCosted]     FLOAT (53)    NOT NULL,
    [RcptDate]        SMALLDATETIME NOT NULL,
    [RcptNbr]         CHAR (15)     NOT NULL,
    [ReasonCd]        CHAR (6)      NOT NULL,
    [RecordID]        INT           NOT NULL,
    [RefNbr]          CHAR (15)     NOT NULL,
    [Retired]         SMALLINT      NOT NULL,
    [Rlsed]           SMALLINT      NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [ServiceCallID]   CHAR (10)     NOT NULL,
    [ShortQty]        FLOAT (53)    NOT NULL,
    [SiteID]          CHAR (10)     NOT NULL,
    [SlsperID]        CHAR (10)     NOT NULL,
    [SpecificCostID]  CHAR (25)     NOT NULL,
    [StdTotalQty]     FLOAT (53)    NOT NULL,
    [Sub]             CHAR (24)     NOT NULL,
    [SvcContractID]   CHAR (10)     NOT NULL,
    [SvcLineNbr]      SMALLINT      NOT NULL,
    [TaskID]          CHAR (32)     NOT NULL,
    [ToSiteID]        CHAR (10)     NOT NULL,
    [ToWhseLoc]       CHAR (10)     NOT NULL,
    [TranAmt]         FLOAT (53)    NOT NULL,
    [TranDate]        SMALLDATETIME NOT NULL,
    [TranDesc]        CHAR (30)     NOT NULL,
    [TranType]        CHAR (2)      NOT NULL,
    [UnitCost]        FLOAT (53)    NOT NULL,
    [UnitDesc]        CHAR (6)      NOT NULL,
    [UnitMultDiv]     CHAR (1)      NOT NULL,
    [UnitPrice]       FLOAT (53)    NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [UseTranCost]     SMALLINT      NOT NULL,
    [WhseLoc]         CHAR (10)     NOT NULL,
    [tstamp]          BINARY (8)    NOT NULL,
    [Applied]         SMALLINT      NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [INTranHoldPICT1]
    ON [dbo].[INTranHoldPICT]([Applied] ASC, [RecordID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [INTranHoldPICT2]
    ON [dbo].[INTranHoldPICT]([Applied] ASC, [BatNbr] ASC, [RefNbr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90);

