CREATE TABLE [dbo].[smProServSetup] (
    [AutoBranchPrefix]     SMALLINT      NOT NULL,
    [AutoContract]         SMALLINT      NOT NULL,
    [AutoContractCalc]     SMALLINT      NOT NULL,
    [AutoCust]             SMALLINT      NOT NULL,
    [AutoEquipment]        SMALLINT      NOT NULL,
    [AutoRef]              SMALLINT      NOT NULL,
    [chkboxOdoReading]     SMALLINT      NOT NULL,
    [ColorPHigh]           CHAR (15)     NOT NULL,
    [ColorPLow]            CHAR (15)     NOT NULL,
    [ColorPMedium]         CHAR (15)     NOT NULL,
    [ColorPPremium]        CHAR (15)     NOT NULL,
    [ColorTEarlierToday]   CHAR (15)     NOT NULL,
    [ColorTFutureDate]     CHAR (15)     NOT NULL,
    [ColorTLaterToday]     CHAR (15)     NOT NULL,
    [ColorTPastDate]       CHAR (15)     NOT NULL,
    [ColorTWithinMinutes]  CHAR (15)     NOT NULL,
    [comboPONumber]        CHAR (1)      NOT NULL,
    [ContractMonths]       SMALLINT      NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME NOT NULL,
    [Crtd_Prog]            CHAR (8)      NOT NULL,
    [Crtd_User]            CHAR (10)     NOT NULL,
    [EquipmentMonths]      SMALLINT      NOT NULL,
    [FlatRateOption]       CHAR (1)      NOT NULL,
    [Future1Int]           SMALLINT      NOT NULL,
    [Future2Int]           SMALLINT      NOT NULL,
    [Future3Str]           CHAR (10)     NOT NULL,
    [Future4Str]           CHAR (10)     NOT NULL,
    [Future5Str]           CHAR (10)     NOT NULL,
    [Future6Str]           CHAR (10)     NOT NULL,
    [Future7Str]           CHAR (10)     NOT NULL,
    [Future8Int]           SMALLINT      NOT NULL,
    [Future9str]           CHAR (10)     NOT NULL,
    [HoursOprFrom]         CHAR (4)      NOT NULL,
    [HoursOprFromAMPM]     CHAR (1)      NOT NULL,
    [HoursOprFromMi]       CHAR (4)      NOT NULL,
    [HoursOprTo]           CHAR (4)      NOT NULL,
    [HoursOprToAMPM]       CHAR (1)      NOT NULL,
    [HoursOprToMi]         CHAR (4)      NOT NULL,
    [InclNBLabor]          SMALLINT      NOT NULL,
    [InclNBTM]             SMALLINT      NOT NULL,
    [Invoicing]            SMALLINT      NOT NULL,
    [LabPricing]           CHAR (1)      NOT NULL,
    [LastContractNbr]      CHAR (10)     NOT NULL,
    [LastCustId]           CHAR (15)     NOT NULL,
    [LastEquipmentNbr]     CHAR (10)     NOT NULL,
    [LastInvBatNbr]        CHAR (10)     NOT NULL,
    [LastOrdNbr]           CHAR (10)     NOT NULL,
    [LastRevCalDate]       SMALLDATETIME NOT NULL,
    [LastServiceCall]      CHAR (10)     NOT NULL,
    [Lupd_DateTime]        SMALLDATETIME NOT NULL,
    [Lupd_Prog]            CHAR (8)      NOT NULL,
    [Lupd_User]            CHAR (10)     NOT NULL,
    [MatPricing]           CHAR (1)      NOT NULL,
    [Mobile]               SMALLINT      NOT NULL,
    [OpnCallsAlrt]         SMALLINT      NOT NULL,
    [PagerPath]            CHAR (255)    NOT NULL,
    [PayrollInterface]     CHAR (1)      NOT NULL,
    [POReceipts]           SMALLINT      NOT NULL,
    [RentalMonths]         SMALLINT      NOT NULL,
    [RevenueCalOption]     CHAR (1)      NOT NULL,
    [SD_ID01]              CHAR (30)     NOT NULL,
    [SD_ID02]              CHAR (30)     NOT NULL,
    [SD_ID03]              CHAR (20)     NOT NULL,
    [SD_ID04]              CHAR (20)     NOT NULL,
    [SD_ID05]              CHAR (10)     NOT NULL,
    [SD_ID06]              CHAR (10)     NOT NULL,
    [SD_ID07]              CHAR (4)      NOT NULL,
    [SD_ID08]              FLOAT (53)    NOT NULL,
    [SD_ID09]              SMALLDATETIME NOT NULL,
    [SD_ID10]              SMALLINT      NOT NULL,
    [SD_ID11]              CHAR (30)     NOT NULL,
    [SD_ID12]              CHAR (30)     NOT NULL,
    [SD_ID13]              CHAR (20)     NOT NULL,
    [SD_ID14]              CHAR (20)     NOT NULL,
    [SD_ID15]              CHAR (10)     NOT NULL,
    [SD_ID16]              CHAR (10)     NOT NULL,
    [SD_ID17]              CHAR (4)      NOT NULL,
    [SD_ID18]              FLOAT (53)    NOT NULL,
    [SD_ID19]              SMALLDATETIME NOT NULL,
    [SD_ID20]              SMALLINT      NOT NULL,
    [ServCallMonths]       SMALLINT      NOT NULL,
    [ServiceCallLeadTime]  CHAR (4)      NOT NULL,
    [ServiceCallRangeTime] CHAR (4)      NOT NULL,
    [SetupID]              CHAR (10)     NOT NULL,
    [SplitCommEqual100]    SMALLINT      NOT NULL,
    [user1]                CHAR (30)     NOT NULL,
    [user2]                CHAR (30)     NOT NULL,
    [user3]                FLOAT (53)    NOT NULL,
    [user4]                FLOAT (53)    NOT NULL,
    [User5]                CHAR (10)     NOT NULL,
    [User6]                CHAR (10)     NOT NULL,
    [User7]                SMALLDATETIME NOT NULL,
    [User8]                SMALLDATETIME NOT NULL,
    [VersionNbr]           CHAR (20)     NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [smProServSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

