CREATE TABLE [dbo].[PJBSREV] (
    [amount]         FLOAT (53)    NOT NULL,
    [CpnyId]         CHAR (10)     NOT NULL,
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [gl_acct]        CHAR (10)     NOT NULL,
    [gl_comment]     CHAR (30)     NOT NULL,
    [gl_subacct]     CHAR (24)     NOT NULL,
    [linenbr]        SMALLINT      NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [percent_detail] FLOAT (53)    NOT NULL,
    [pjt_entity]     CHAR (32)     NOT NULL,
    [post_date]      SMALLDATETIME NOT NULL,
    [post_date_est]  SMALLDATETIME NOT NULL,
    [post_period]    CHAR (6)      NOT NULL,
    [project]        CHAR (16)     NOT NULL,
    [rel_status]     CHAR (1)      NOT NULL,
    [rd_id01]        CHAR (30)     NOT NULL,
    [rd_id02]        CHAR (30)     NOT NULL,
    [rd_id03]        CHAR (20)     NOT NULL,
    [rd_id04]        CHAR (20)     NOT NULL,
    [rd_id05]        CHAR (10)     NOT NULL,
    [rd_id06]        CHAR (10)     NOT NULL,
    [rd_id07]        CHAR (4)      NOT NULL,
    [rd_id08]        FLOAT (53)    NOT NULL,
    [rd_id09]        SMALLDATETIME NOT NULL,
    [rd_id10]        INT           NOT NULL,
    [rd_id11]        CHAR (30)     NOT NULL,
    [rd_id12]        CHAR (30)     NOT NULL,
    [rd_id13]        CHAR (20)     NOT NULL,
    [rd_id14]        CHAR (20)     NOT NULL,
    [rd_id15]        CHAR (10)     NOT NULL,
    [rd_id16]        CHAR (10)     NOT NULL,
    [rd_id17]        CHAR (4)      NOT NULL,
    [rd_id18]        FLOAT (53)    NOT NULL,
    [rd_id19]        SMALLDATETIME NOT NULL,
    [rd_id20]        INT           NOT NULL,
    [schednbr]       CHAR (6)      NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjbsrev0] PRIMARY KEY CLUSTERED ([project] ASC, [schednbr] ASC, [linenbr] ASC)
);

