CREATE TABLE [dbo].[XDDEBFile] (
    [AmtApprvLvl1_A_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_A_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_B_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_B_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_C_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_C_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_D_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_D_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_E_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl1_E_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_A_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_A_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_B_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_B_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_C_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_C_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_D_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_D_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_E_User] CHAR (47)     DEFAULT ('') NOT NULL,
    [AmtApprvLvl2_E_PW]   CHAR (15)     DEFAULT ('') NOT NULL,
    [AREFTInvoices]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTTotal]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [Batch_PreNote]       CHAR (1)      DEFAULT ('') NOT NULL,
    [BatchCount]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [BatchTotal]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CpnyID]              CHAR (10)     DEFAULT ('') NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_Time]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [EBFileNbr]           CHAR (6)      DEFAULT ('') NOT NULL,
    [EffDate]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [FileName]            CHAR (80)     DEFAULT ('') NOT NULL,
    [FilePath]            CHAR (128)    DEFAULT ('') NOT NULL,
    [FileType]            CHAR (1)      DEFAULT ('') NOT NULL,
    [FormatID]            CHAR (15)     DEFAULT ('') NOT NULL,
    [KeepDelete]          CHAR (1)      DEFAULT ('') NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_Time]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [Module]              CHAR (2)      DEFAULT ('') NOT NULL,
    [NoteID]              INT           DEFAULT ((0)) NOT NULL,
    [PPAP]                SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPAPVoid]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPPR]                SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPPRVoid]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [Ret_CommType]        CHAR (1)      DEFAULT ('') NOT NULL,
    [Ret_CommUserProg]    CHAR (128)    DEFAULT ('') NOT NULL,
    [Ret_DelFile]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [Ret_GoodRecs]        INT           DEFAULT ((0)) NOT NULL,
    [Ret_WrkAcct]         CHAR (10)     DEFAULT ('') NOT NULL,
    [Ret_WrkCpnyID]       CHAR (10)     DEFAULT ('') NOT NULL,
    [Ret_WrkSub]          CHAR (24)     DEFAULT ('') NOT NULL,
    [Sequence]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [SKFuture01]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]          CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]          CHAR (10)     DEFAULT ('') NOT NULL,
    [TransmitDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [UnbalancedFile]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [User1]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]               CHAR (30)     DEFAULT ('') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [XDDEBFile0] PRIMARY KEY CLUSTERED ([FileType] ASC, [EBFileNbr] ASC)
);

