CREATE TABLE [dbo].[DDSetup] (
    [ACHCompanyID]    CHAR (10)     NOT NULL,
    [AchCrLf]         CHAR (1)      NOT NULL,
    [ACHFileName]     CHAR (255)    NOT NULL,
    [ACHFillBlock]    CHAR (1)      NOT NULL,
    [ACHImmDest]      CHAR (10)     NOT NULL,
    [ACHImmDestN]     CHAR (23)     NOT NULL,
    [ACHImmOrig]      CHAR (10)     NOT NULL,
    [ACHImmOrigN]     CHAR (23)     NOT NULL,
    [ACHInclDR]       CHAR (1)      NOT NULL,
    [CommMAnswer]     CHAR (30)     NOT NULL,
    [CommMAttn]       CHAR (30)     NOT NULL,
    [CommMBusy]       CHAR (30)     NOT NULL,
    [CommMConnect]    CHAR (40)     NOT NULL,
    [CommMDialPrefix] CHAR (30)     NOT NULL,
    [CommMHangUp]     CHAR (50)     NOT NULL,
    [CommMHighBaud]   INT           NOT NULL,
    [CommMInit]       CHAR (128)    NOT NULL,
    [CommMMake]       CHAR (25)     NOT NULL,
    [CommMModel]      CHAR (40)     NOT NULL,
    [CommMNum]        INT           NOT NULL,
    [CommMReset]      CHAR (30)     NOT NULL,
    [CommPBaud]       INT           NOT NULL,
    [CommPCommPort]   SMALLINT      NOT NULL,
    [CommPDataBit]    CHAR (1)      NOT NULL,
    [CommPDTR]        SMALLINT      NOT NULL,
    [CommPEcho]       SMALLINT      NOT NULL,
    [CommPHandShake]  SMALLINT      NOT NULL,
    [CommPhone]       CHAR (30)     NOT NULL,
    [CommPParity]     CHAR (1)      NOT NULL,
    [CommPRTS]        SMALLINT      NOT NULL,
    [CommPStopBit]    CHAR (1)      NOT NULL,
    [CommPXferProto]  SMALLINT      NOT NULL,
    [CommType]        CHAR (1)      NOT NULL,
    [CommUserProg]    CHAR (255)    NOT NULL,
    [CpnyID]          CHAR (10)     NOT NULL,
    [CpnyName]        CHAR (30)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [DistTypeDflt]    CHAR (1)      NOT NULL,
    [Init]            CHAR (1)      NOT NULL,
    [LowPayDflt]      CHAR (1)      NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [PathACHScript]   CHAR (255)    NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [SetupID]         CHAR (2)      NOT NULL,
    [TestMode]        CHAR (1)      NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [DDSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC, [CpnyID] ASC) WITH (FILLFACTOR = 90)
);

