CREATE TABLE [dbo].[cftPigGroupMaster] (
    [CF01]                CHAR (30)     NOT NULL,
    [CF02]                CHAR (30)     NOT NULL,
    [CF03]                CHAR (10)     NOT NULL,
    [CF04]                CHAR (10)     NOT NULL,
    [CF05]                SMALLDATETIME NOT NULL,
    [CF06]                SMALLDATETIME NOT NULL,
    [CF07]                INT           NOT NULL,
    [CF08]                INT           NOT NULL,
    [CF09]                SMALLINT      NOT NULL,
    [CF10]                SMALLINT      NOT NULL,
    [CF11]                FLOAT (53)    NOT NULL,
    [CF12]                FLOAT (53)    NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MActCloseDate]       SMALLDATETIME NOT NULL,
    [MActStartDate]       SMALLDATETIME NOT NULL,
    [MBarnNbr]            CHAR (6)      NOT NULL,
    [MCostFlag]           SMALLINT      NOT NULL,
    [MCpnyID]             CHAR (10)     NOT NULL,
    [MDescription]        CHAR (30)     NOT NULL,
    [MEstCloseDate]       SMALLDATETIME NOT NULL,
    [MEstInventory]       INT           NOT NULL,
    [MEstStartDate]       SMALLDATETIME NOT NULL,
    [MEstStartWeight]     INT           NOT NULL,
    [MEstTopDate]         SMALLDATETIME NOT NULL,
    [MInitialPigValue]    FLOAT (53)    NOT NULL,
    [MPGStatusID]         CHAR (2)      NOT NULL,
    [MPigFlowTypeID]      CHAR (3)      NOT NULL,
    [MPigGenderTypeID]    CHAR (6)      NOT NULL,
    [MPigGroupID]         CHAR (10)     NOT NULL,
    [MPigProdPhaseID]     CHAR (3)      NOT NULL,
    [MPigProdPodID]       CHAR (3)      NOT NULL,
    [MPigSystemID]        CHAR (10)     NOT NULL,
    [MPriorFeedQty]       FLOAT (53)    NOT NULL,
    [MProjectID]          CHAR (16)     NOT NULL,
    [MPurchCountry]       CHAR (3)      NOT NULL,
    [MPurchFlag]          SMALLINT      NOT NULL,
    [MSplitSrcPigGroupID] CHAR (10)     NOT NULL,
    [MSiteContactID]      CHAR (6)      NOT NULL,
    [MSvcMgrContactID]    CHAR (6)      NOT NULL,
    [MTaskID]             CHAR (32)     NOT NULL,
    CONSTRAINT [cftPigGroupMaster0] PRIMARY KEY CLUSTERED ([MPigGroupID] ASC) WITH (FILLFACTOR = 90)
);

