CREATE TABLE [dbo].[PCSetup] (
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CurrPerNbr]    CHAR (6)      NOT NULL,
    [Init]          SMALLINT      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NoteId]        INT           NOT NULL,
    [PCAE_Install]  CHAR (1)      NOT NULL,
    [PC_Install]    CHAR (1)      NOT NULL,
    [PerNbr]        CHAR (6)      NOT NULL,
    [S4Future1]     CHAR (10)     NOT NULL,
    [S4Future10]    SMALLINT      NOT NULL,
    [S4Future11]    SMALLINT      NOT NULL,
    [S4Future12]    SMALLINT      NOT NULL,
    [S4Future13]    FLOAT (53)    NOT NULL,
    [S4Future14]    FLOAT (53)    NOT NULL,
    [S4Future2]     CHAR (10)     NOT NULL,
    [S4Future3]     CHAR (1)      NOT NULL,
    [S4Future4]     CHAR (1)      NOT NULL,
    [S4Future5]     CHAR (1)      NOT NULL,
    [S4Future6]     CHAR (1)      NOT NULL,
    [S4Future7]     SMALLINT      NOT NULL,
    [S4Future8]     SMALLINT      NOT NULL,
    [S4Future9]     SMALLINT      NOT NULL,
    [SetupId]       CHAR (2)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [PCSetup0] PRIMARY KEY CLUSTERED ([SetupId] ASC) WITH (FILLFACTOR = 90)
);

