CREATE TABLE [dbo].[SIMatlTypes] (
    [Buyer]             CHAR (10)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [Descr]             CHAR (60)     NOT NULL,
    [IRCalcPolicy]      CHAR (1)      NOT NULL,
    [IRDaysSupply]      FLOAT (53)    NOT NULL,
    [IRDemandID]        CHAR (10)     NOT NULL,
    [IRFutureDate]      SMALLDATETIME NOT NULL,
    [IRFuturePolicy]    CHAR (1)      NOT NULL,
    [IRLeadTimeID]      CHAR (10)     NOT NULL,
    [IRPrimaryVendID]   CHAR (15)     NOT NULL,
    [IRSeasonEndDay]    SMALLINT      NOT NULL,
    [IRSeasonEndMon]    SMALLINT      NOT NULL,
    [IRSeasonStrtDay]   SMALLINT      NOT NULL,
    [IRSeasonStrtMon]   SMALLINT      NOT NULL,
    [IRServiceLevel]    FLOAT (53)    NOT NULL,
    [IRSftyStkDays]     FLOAT (53)    NOT NULL,
    [IRSftyStkPct]      FLOAT (53)    NOT NULL,
    [IRSftyStkPolicy]   CHAR (1)      NOT NULL,
    [IRSourceCode]      CHAR (1)      NOT NULL,
    [IRTargetOrdMethod] CHAR (1)      NOT NULL,
    [IRTargetOrdReq]    FLOAT (53)    NOT NULL,
    [IRTransferSiteID]  CHAR (10)     NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME NOT NULL,
    [LUpd_Prog]         CHAR (8)      NOT NULL,
    [LUpd_User]         CHAR (10)     NOT NULL,
    [MaterialType]      CHAR (10)     NOT NULL,
    [NoteID]            INT           NOT NULL,
    [ReplMthd]          CHAR (1)      NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [Status]            CHAR (1)      NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [SIMatlTypes0] PRIMARY KEY CLUSTERED ([MaterialType] ASC) WITH (FILLFACTOR = 90)
);

