CREATE TABLE [dbo].[smSCQueue] (
    [CallStatusID]      CHAR (10)     NOT NULL,
    [CallTypeID]        CHAR (10)     NOT NULL,
    [Comments]          CHAR (60)     NOT NULL,
    [CompletedDate]     SMALLDATETIME NOT NULL,
    [CompletedTime]     CHAR (4)      NOT NULL,
    [CompletedUserID]   CHAR (47)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [CustomerId]        CHAR (15)     NOT NULL,
    [DateCalled]        SMALLDATETIME NOT NULL,
    [DateSchedule]      SMALLDATETIME NOT NULL,
    [EmployeeID]        CHAR (10)     NOT NULL,
    [GeographicID]      CHAR (10)     NOT NULL,
    [Lupd_DateTime]     SMALLDATETIME NOT NULL,
    [Lupd_Prog]         CHAR (8)      NOT NULL,
    [Lupd_User]         CHAR (10)     NOT NULL,
    [PriorityHigh]      SMALLINT      NOT NULL,
    [PriorityLow]       SMALLINT      NOT NULL,
    [PriorityMedium]    SMALLINT      NOT NULL,
    [ServCallCompleted] SMALLINT      NOT NULL,
    [ServiceCallID]     CHAR (10)     NOT NULL,
    [ShiptoId]          CHAR (10)     NOT NULL,
    [StartDate]         SMALLDATETIME NOT NULL,
    [StartTime]         CHAR (4)      NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [smSCQueue0] PRIMARY KEY CLUSTERED ([ServiceCallID] ASC) WITH (FILLFACTOR = 90)
);

