CREATE TABLE [dbo].[PJEMPPJT] (
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [employee]       CHAR (10)     NOT NULL,
    [ep_id01]        CHAR (30)     NOT NULL,
    [ep_id02]        CHAR (30)     NOT NULL,
    [ep_id03]        CHAR (16)     NOT NULL,
    [ep_id04]        CHAR (16)     NOT NULL,
    [ep_id05]        CHAR (4)      NOT NULL,
    [ep_id06]        FLOAT (53)    NOT NULL,
    [ep_id07]        FLOAT (53)    NOT NULL,
    [ep_id08]        SMALLDATETIME NOT NULL,
    [ep_id09]        SMALLDATETIME NOT NULL,
    [ep_id10]        INT           NOT NULL,
    [effect_date]    SMALLDATETIME NOT NULL,
    [labor_class_cd] CHAR (4)      NOT NULL,
    [labor_rate]     FLOAT (53)    NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [project]        CHAR (16)     NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjemppjt0] PRIMARY KEY CLUSTERED ([employee] ASC, [project] ASC, [effect_date] ASC) WITH (FILLFACTOR = 90)
);

