CREATE TABLE [dbo].[cft_scribe_CRM_f1_productinventoryBase] (
    [f1_productinventoryId]     UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                 DATETIME         NULL,
    [CreatedBy]                 UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                DATETIME         NULL,
    [ModifiedBy]                UNIQUEIDENTIFIER NULL,
    [CreatedOnBehalfBy]         UNIQUEIDENTIFIER NULL,
    [ModifiedOnBehalfBy]        UNIQUEIDENTIFIER NULL,
    [OrganizationId]            UNIQUEIDENTIFIER NULL,
    [statecode]                 INT              NOT NULL,
    [statuscode]                INT              NULL,
    [VersionNumber]             ROWVERSION       NULL,
    [ImportSequenceNumber]      INT              NULL,
    [OverriddenCreatedOn]       DATETIME         NULL,
    [TimeZoneRuleVersionNumber] INT              NULL,
    [UTCConversionTimeZoneCode] INT              NULL,
    [f1_QtyAllocated]           FLOAT (53)       NULL,
    [f1_Product]                UNIQUEIDENTIFIER NULL,
    [f1_QtyOnHand]              FLOAT (53)       NULL,
    [f1_QtyOnOrder]             FLOAT (53)       NULL,
    [f1_Bin]                    NVARCHAR (100)   NULL,
    [f1_ReorderPoint]           FLOAT (53)       NULL,
    [f1_Row]                    NVARCHAR (100)   NULL,
    [f1_IsChangedViaTheJournal] BIT              NULL,
    [f1_name]                   NVARCHAR (100)   NULL,
    [f1_Unit]                   UNIQUEIDENTIFIER NULL,
    [f1_QtyAvailable]           FLOAT (53)       NULL,
    [f1_Warehouse]              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_cft_scribe_CRM_f1_productinventoryBase] PRIMARY KEY CLUSTERED ([f1_productinventoryId] ASC) WITH (FILLFACTOR = 80)
);

