CREATE TABLE [dbo].[WrkARDoc] (
    [Acct]            CHAR (10)     NULL,
    [ApplAmt]         FLOAT (53)    NULL,
    [ApplBatNbr]      CHAR (10)     NULL,
    [ApplBatSeq]      INT           NULL,
    [BankAcct]        CHAR (10)     NULL,
    [BankSub]         CHAR (24)     NULL,
    [BatNbr]          CHAR (10)     NOT NULL,
    [BatSeq]          INT           NULL,
    [ClearDate]       SMALLDATETIME NULL,
    [CmmnAmt]         FLOAT (53)    NULL,
    [CmmnPct]         FLOAT (53)    NULL,
    [CpnyID]          CHAR (10)     NULL,
    [CurrentNbr]      SMALLINT      NULL,
    [CuryApplAmt]     FLOAT (53)    NULL,
    [CuryClearAmt]    FLOAT (53)    NULL,
    [CuryCmmnAmt]     FLOAT (53)    NULL,
    [CuryDiscApplAmt] FLOAT (53)    NULL,
    [CuryDiscBal]     FLOAT (53)    NULL,
    [CuryDocBal]      FLOAT (53)    NULL,
    [CuryEffDate]     SMALLDATETIME NULL,
    [CuryID]          CHAR (4)      NULL,
    [CuryMultDiv]     CHAR (1)      NULL,
    [CuryOrigDocAmt]  FLOAT (53)    NULL,
    [CuryRate]        FLOAT (53)    NULL,
    [CuryRateType]    CHAR (6)      NULL,
    [CuryStmtBal]     FLOAT (53)    NULL,
    [CuryTaxTot00]    FLOAT (53)    NULL,
    [CuryTaxTot01]    FLOAT (53)    NULL,
    [CuryTaxTot02]    FLOAT (53)    NULL,
    [CuryTaxTot03]    FLOAT (53)    NULL,
    [CuryTxblTot00]   FLOAT (53)    NULL,
    [CuryTxblTot01]   FLOAT (53)    NULL,
    [CuryTxblTot02]   FLOAT (53)    NULL,
    [CuryTxblTot03]   FLOAT (53)    NULL,
    [CustID]          CHAR (15)     NOT NULL,
    [CustOrdNbr]      CHAR (15)     NULL,
    [Cycle]           SMALLINT      NULL,
    [DiscApplAmt]     FLOAT (53)    NULL,
    [DiscBal]         FLOAT (53)    NULL,
    [DiscDate]        SMALLDATETIME NULL,
    [DocBal]          FLOAT (53)    NULL,
    [DocClass]        CHAR (1)      NULL,
    [DocDate]         SMALLDATETIME NULL,
    [DocDesc]         CHAR (30)     NULL,
    [DocType]         CHAR (2)      NOT NULL,
    [DueDate]         SMALLDATETIME NULL,
    [JobCntr]         SMALLINT      NULL,
    [LineCntr]        INT           NULL,
    [NbrCycle]        SMALLINT      NULL,
    [NoteID]          INT           NULL,
    [OpenDoc]         SMALLINT      NULL,
    [OrdNbr]          CHAR (10)     NULL,
    [OrigDocAmt]      FLOAT (53)    NULL,
    [PC_Status]       CHAR (1)      NULL,
    [PerClosed]       CHAR (6)      NULL,
    [PerEnt]          CHAR (6)      NULL,
    [PerPost]         CHAR (6)      NULL,
    [ProjectID]       CHAR (16)     NULL,
    [RefNbr]          CHAR (10)     NOT NULL,
    [RGOLAmt]         FLOAT (53)    NULL,
    [RI_ID]           SMALLINT      NOT NULL,
    [Rlsed]           SMALLINT      NULL,
    [ShipmentNbr]     SMALLINT      NULL,
    [SlsPerID]        CHAR (10)     NULL,
    [Status]          CHAR (1)      NULL,
    [StmtBal]         FLOAT (53)    NULL,
    [StmtDate]        SMALLDATETIME NULL,
    [Sub]             CHAR (24)     NULL,
    [TaskID]          CHAR (32)     NULL,
    [TaxCntr00]       SMALLINT      NULL,
    [TaxCntr01]       SMALLINT      NULL,
    [TaxCntr02]       SMALLINT      NULL,
    [TaxCntr03]       SMALLINT      NULL,
    [TaxDate]         SMALLDATETIME NULL,
    [TaxID00]         CHAR (10)     NULL,
    [TaxID01]         CHAR (10)     NULL,
    [TaxID02]         CHAR (10)     NULL,
    [TaxID03]         CHAR (10)     NULL,
    [TaxTot00]        FLOAT (53)    NULL,
    [TaxTot01]        FLOAT (53)    NULL,
    [TaxTot02]        FLOAT (53)    NULL,
    [TaxTot03]        FLOAT (53)    NULL,
    [Terms]           CHAR (2)      NULL,
    [TxblTot00]       FLOAT (53)    NULL,
    [TxblTot01]       FLOAT (53)    NULL,
    [TxblTot02]       FLOAT (53)    NULL,
    [TxblTot03]       FLOAT (53)    NULL,
    [User1]           CHAR (30)     NULL,
    [User2]           CHAR (30)     NULL,
    [User3]           FLOAT (53)    NULL,
    [User4]           FLOAT (53)    NULL,
    [User5]           CHAR (10)     NULL,
    [User6]           CHAR (10)     NULL,
    [User7]           SMALLDATETIME NULL,
    [User8]           SMALLDATETIME NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [WrkARDoc0] PRIMARY KEY CLUSTERED ([RI_ID] ASC, [BatNbr] ASC, [CustID] ASC, [DocType] ASC, [RefNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [WrkARDoc1]
    ON [dbo].[WrkARDoc]([ApplBatNbr] ASC, [CustID] ASC, [DocType] ASC, [RefNbr] ASC) WITH (FILLFACTOR = 90);

