CREATE TABLE [dbo].[smEmp] (
    [Cetrtified]          CHAR (1)      NOT NULL,
    [CommLaborPct]        FLOAT (53)    NOT NULL,
    [CommMaterialPct]     FLOAT (53)    NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [EarnType]            CHAR (10)     NOT NULL,
    [EM_ID01]             CHAR (30)     NOT NULL,
    [EM_ID02]             CHAR (30)     NOT NULL,
    [EM_ID03]             CHAR (20)     NOT NULL,
    [EM_ID04]             CHAR (20)     NOT NULL,
    [EM_ID05]             CHAR (10)     NOT NULL,
    [EM_ID06]             CHAR (10)     NOT NULL,
    [EM_ID07]             CHAR (4)      NOT NULL,
    [EM_ID08]             FLOAT (53)    NOT NULL,
    [EM_ID09]             SMALLDATETIME NOT NULL,
    [EM_ID10]             SMALLINT      NOT NULL,
    [EM_ID11]             CHAR (30)     NOT NULL,
    [EM_ID12]             CHAR (30)     NOT NULL,
    [EM_ID13]             CHAR (20)     NOT NULL,
    [EM_ID14]             CHAR (20)     NOT NULL,
    [EM_ID15]             CHAR (10)     NOT NULL,
    [EM_ID16]             CHAR (10)     NOT NULL,
    [EM_ID17]             CHAR (4)      NOT NULL,
    [EM_ID18]             FLOAT (53)    NOT NULL,
    [EM_ID19]             SMALLDATETIME NOT NULL,
    [EM_ID20]             SMALLINT      NOT NULL,
    [EmailAddr]           CHAR (80)     NOT NULL,
    [EmployeeActive]      SMALLINT      NOT NULL,
    [employeeaddress1]    CHAR (60)     NOT NULL,
    [employeeaddress2]    CHAR (60)     NOT NULL,
    [employeeBdate]       SMALLDATETIME NOT NULL,
    [EmployeeBranchID]    CHAR (10)     NOT NULL,
    [EmployeeCellPhone]   CHAR (16)     NOT NULL,
    [EmployeeCity]        CHAR (30)     NOT NULL,
    [EmployeeCommPlan]    CHAR (10)     NOT NULL,
    [EmployeeDept]        CHAR (10)     NOT NULL,
    [EmployeeDLClass]     CHAR (16)     NOT NULL,
    [employeeDLExpDate]   SMALLDATETIME NOT NULL,
    [EmployeeDLNo]        CHAR (16)     NOT NULL,
    [EmployeeDLState]     CHAR (3)      NOT NULL,
    [EmployeeExemption]   SMALLINT      NOT NULL,
    [EmployeeFaxNo]       CHAR (16)     NOT NULL,
    [EmployeeFirstName]   CHAR (60)     NOT NULL,
    [EmployeeHiredate]    SMALLDATETIME NOT NULL,
    [EmployeeHomePhone]   CHAR (16)     NOT NULL,
    [EmployeeId]          CHAR (10)     NOT NULL,
    [EmployeeLastName]    CHAR (60)     NOT NULL,
    [EmployeeMarital]     CHAR (1)      NOT NULL,
    [EmployeeMiddleInit]  CHAR (2)      NOT NULL,
    [EmployeeOffPhoneExt] CHAR (4)      NOT NULL,
    [EmployeePagerNo]     CHAR (16)     NOT NULL,
    [EmployeePayRollId]   CHAR (10)     NOT NULL,
    [EmployeePayType]     CHAR (1)      NOT NULL,
    [EmployeeQuota]       FLOAT (53)    NOT NULL,
    [EmployeeRaiseDate]   SMALLDATETIME NOT NULL,
    [EmployeeRate]        FLOAT (53)    NOT NULL,
    [EmployeeSex]         CHAR (1)      NOT NULL,
    [EmployeeSSNo]        CHAR (12)     NOT NULL,
    [EmployeeState]       CHAR (3)      NOT NULL,
    [EmployeeTermDate]    SMALLDATETIME NOT NULL,
    [EmployeeType]        CHAR (10)     NOT NULL,
    [EmployeeVehicleId]   CHAR (10)     NOT NULL,
    [EmployeeWorkerDept]  CHAR (10)     NOT NULL,
    [EmployeeZip]         CHAR (10)     NOT NULL,
    [InvtSiteID]          CHAR (10)     NOT NULL,
    [LaborClass]          CHAR (4)      NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [NoteID]              INT           NOT NULL,
    [OvhdFringe]          FLOAT (53)    NOT NULL,
    [OvhdFringeType]      CHAR (1)      NOT NULL,
    [OvhdInsur]           FLOAT (53)    NOT NULL,
    [OvhdInsurType]       CHAR (1)      NOT NULL,
    [OvhdOther]           FLOAT (53)    NOT NULL,
    [OvhdOtherType]       CHAR (1)      NOT NULL,
    [OvhdTaxes]           FLOAT (53)    NOT NULL,
    [OvhdTaxesType]       CHAR (1)      NOT NULL,
    [ShiftCode]           CHAR (7)      NOT NULL,
    [Supervisor]          CHAR (10)     NOT NULL,
    [TemplateID]          CHAR (10)     NOT NULL,
    [TimeZone]            CHAR (10)     NOT NULL,
    [UnionCode]           CHAR (10)     NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [WageCode]            CHAR (4)      NOT NULL,
    [WageGroup]           CHAR (2)      NOT NULL,
    [WorkersComp]         CHAR (6)      NOT NULL,
    [WorkLoc]             CHAR (6)      NOT NULL,
    [WorkType]            CHAR (2)      NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smEmp0] PRIMARY KEY CLUSTERED ([EmployeeId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [smEmp1]
    ON [dbo].[smEmp]([Supervisor] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [smEmp2]
    ON [dbo].[smEmp]([EmployeeActive] ASC, [EmployeeType] ASC, [EmployeeBranchID] ASC, [EmployeeId] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [smEmp3]
    ON [dbo].[smEmp]([EmployeeId] ASC, [EM_ID07] ASC) WITH (FILLFACTOR = 90);

