CREATE TABLE [dbo].[Benefit] (
    [AccrLiab]         SMALLINT      NOT NULL,
    [AccrMthd]         CHAR (1)      NOT NULL,
    [AvailMthd]        CHAR (1)      NOT NULL,
    [BenId]            CHAR (10)     NOT NULL,
    [ClassId]          CHAR (10)     NOT NULL,
    [CpnyID]           CHAR (10)     NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [Descr]            CHAR (30)     NOT NULL,
    [ExpAcct]          CHAR (10)     NOT NULL,
    [ExpDate]          SMALLDATETIME NOT NULL,
    [ExpSub]           CHAR (24)     NOT NULL,
    [LiabAcct]         CHAR (10)     NOT NULL,
    [LiabSub]          CHAR (24)     NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME NOT NULL,
    [LUpd_Prog]        CHAR (8)      NOT NULL,
    [LUpd_User]        CHAR (10)     NOT NULL,
    [NoteId]           INT           NOT NULL,
    [PlanYrBegin]      CHAR (4)      NOT NULL,
    [PrtOnStub]        SMALLINT      NOT NULL,
    [S4Future01]       CHAR (30)     NOT NULL,
    [S4Future02]       CHAR (30)     NOT NULL,
    [S4Future03]       FLOAT (53)    NOT NULL,
    [S4Future04]       FLOAT (53)    NOT NULL,
    [S4Future05]       FLOAT (53)    NOT NULL,
    [S4Future06]       FLOAT (53)    NOT NULL,
    [S4Future07]       SMALLDATETIME NOT NULL,
    [S4Future08]       SMALLDATETIME NOT NULL,
    [S4Future09]       INT           NOT NULL,
    [S4Future10]       INT           NOT NULL,
    [S4Future11]       CHAR (10)     NOT NULL,
    [S4Future12]       CHAR (10)     NOT NULL,
    [TrnsBenId]        CHAR (10)     NOT NULL,
    [TrnsCarryFwdHist] SMALLINT      NOT NULL,
    [TrnsDate]         SMALLDATETIME NOT NULL,
    [TrnsMthd]         CHAR (1)      NOT NULL,
    [TrnsUnits]        SMALLINT      NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [YearType]         CHAR (1)      NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [Benefit0] PRIMARY KEY CLUSTERED ([BenId] ASC) WITH (FILLFACTOR = 90)
);

