CREATE TABLE [dbo].[PJUTGOAL] (
    [available_hours]    FLOAT (53)    NOT NULL,
    [crtd_datetime]      SMALLDATETIME NOT NULL,
    [crtd_prog]          CHAR (8)      NOT NULL,
    [crtd_user]          CHAR (10)     NOT NULL,
    [employee]           CHAR (10)     NOT NULL,
    [fiscalno]           CHAR (6)      NOT NULL,
    [hours_goal]         FLOAT (53)    NOT NULL,
    [hours_goal_percent] FLOAT (53)    NOT NULL,
    [lupd_datetime]      SMALLDATETIME NOT NULL,
    [lupd_prog]          CHAR (8)      NOT NULL,
    [lupd_user]          CHAR (10)     NOT NULL,
    [NoteId]             INT           NOT NULL,
    [rate]               FLOAT (53)    NOT NULL,
    [revenue_goal]       FLOAT (53)    NOT NULL,
    [ug_id01]            CHAR (30)     NOT NULL,
    [ug_id02]            CHAR (30)     NOT NULL,
    [ug_id03]            CHAR (20)     NOT NULL,
    [ug_id04]            CHAR (20)     NOT NULL,
    [ug_id05]            CHAR (10)     NOT NULL,
    [ug_id06]            CHAR (10)     NOT NULL,
    [ug_id07]            CHAR (4)      NOT NULL,
    [ug_id08]            FLOAT (53)    NOT NULL,
    [ug_id09]            SMALLDATETIME NOT NULL,
    [ug_id10]            INT           NOT NULL,
    [user1]              CHAR (30)     NOT NULL,
    [user2]              CHAR (30)     NOT NULL,
    [user3]              FLOAT (53)    NOT NULL,
    [user4]              FLOAT (53)    NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [pjutgoal0] PRIMARY KEY CLUSTERED ([employee] ASC, [fiscalno] ASC) WITH (FILLFACTOR = 90)
);

