CREATE TABLE [dbo].[smPMMSchedule] (
    [Calendar]         SMALLINT      NOT NULL,
    [CalendarCode]     CHAR (10)     NOT NULL,
    [CalendarInterval] FLOAT (53)    NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [EstTime]          CHAR (4)      NOT NULL,
    [IntervalCode]     CHAR (10)     NOT NULL,
    [Lupd_DateTime]    SMALLDATETIME NOT NULL,
    [Lupd_Prog]        CHAR (8)      NOT NULL,
    [Lupd_User]        CHAR (10)     NOT NULL,
    [ManufID]          CHAR (10)     NOT NULL,
    [MeterTypeID]      CHAR (10)     NOT NULL,
    [ModelID]          CHAR (40)     NOT NULL,
    [NoteId]           INT           NOT NULL,
    [PMType]           CHAR (10)     NOT NULL,
    [Usage]            SMALLINT      NOT NULL,
    [UsageInterval]    FLOAT (53)    NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [smPMMSchedule0] PRIMARY KEY CLUSTERED ([PMType] ASC, [ManufID] ASC, [ModelID] ASC) WITH (FILLFACTOR = 90)
);

