CREATE TABLE [dbo].[PJPOOLS] (
    [amount_ptd]    FLOAT (53)    NOT NULL,
    [amount_ytd]    FLOAT (53)    NOT NULL,
    [cpnyid]        CHAR (10)     NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [gl_acct]       CHAR (10)     NOT NULL,
    [gl_subacct]    CHAR (24)     NOT NULL,
    [grpid]         CHAR (6)      NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [noteid]        INT           NOT NULL,
    [period]        CHAR (6)      NOT NULL,
    [ps_id01]       CHAR (30)     NOT NULL,
    [ps_id02]       CHAR (16)     NOT NULL,
    [ps_id03]       FLOAT (53)    NOT NULL,
    [ps_id04]       FLOAT (53)    NOT NULL,
    [ps_id05]       SMALLDATETIME NOT NULL,
    [ps_id06]       INT           NOT NULL,
    [recnbr]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [user1]         CHAR (30)     NOT NULL,
    [user2]         CHAR (30)     NOT NULL,
    [user3]         FLOAT (53)    NOT NULL,
    [user4]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [pjpools0] PRIMARY KEY CLUSTERED ([grpid] ASC, [period] ASC, [recnbr] ASC) WITH (FILLFACTOR = 90)
);

