CREATE TABLE [dbo].[smcondepapplied] (
    [AmtApplied]    FLOAT (53)    NOT NULL,
    [ARBatch]       VARCHAR (10)  NOT NULL,
    [BatNbr]        VARCHAR (10)  NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     VARCHAR (8)   NOT NULL,
    [Crtd_User]     VARCHAR (10)  NOT NULL,
    [InvoiceDate]   SMALLDATETIME NOT NULL,
    [InvoiceNbr]    VARCHAR (10)  NOT NULL,
    [LineNbr]       SMALLINT      NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     VARCHAR (8)   NOT NULL,
    [Lupd_User]     VARCHAR (10)  NOT NULL,
    [RecordID]      INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [S4Future01]    VARCHAR (30)  NOT NULL,
    [S4Future02]    VARCHAR (30)  NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    VARCHAR (10)  NOT NULL,
    [S4Future12]    VARCHAR (10)  NOT NULL,
    [User1]         VARCHAR (30)  NOT NULL,
    [User2]         VARCHAR (30)  NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         VARCHAR (10)  NOT NULL,
    [User6]         VARCHAR (10)  NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smcondepapplied0] PRIMARY KEY CLUSTERED ([BatNbr] ASC, [LineNbr] ASC, [RecordID] ASC) WITH (FILLFACTOR = 90)
);

