CREATE TABLE [dbo].[Budget_Dist_Type] (
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [DistType]      CHAR (8)      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [Pct00]         FLOAT (53)    NOT NULL,
    [Pct01]         FLOAT (53)    NOT NULL,
    [Pct02]         FLOAT (53)    NOT NULL,
    [Pct03]         FLOAT (53)    NOT NULL,
    [Pct04]         FLOAT (53)    NOT NULL,
    [Pct05]         FLOAT (53)    NOT NULL,
    [Pct06]         FLOAT (53)    NOT NULL,
    [Pct07]         FLOAT (53)    NOT NULL,
    [Pct08]         FLOAT (53)    NOT NULL,
    [Pct09]         FLOAT (53)    NOT NULL,
    [Pct10]         FLOAT (53)    NOT NULL,
    [Pct11]         FLOAT (53)    NOT NULL,
    [PctTot]        FLOAT (53)    NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [Budget_Dist_Type0] PRIMARY KEY NONCLUSTERED ([DistType] ASC) WITH (FILLFACTOR = 90)
);

