CREATE TABLE [dbo].[POReceipt] (
    [APRefno]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [BatNbr]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [CpnyID]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [CreateAD]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [CuryEffDate]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [CuryFreight]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryID]            CHAR (4)      DEFAULT (' ') NOT NULL,
    [CuryMultDiv]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [CuryRate]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRateType]      CHAR (6)      DEFAULT (' ') NOT NULL,
    [CuryRcptAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRcptAmtTot]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRcptCtrlAmt]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRcptItemTotal] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DfltFromPO]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [ExcludeFreight]    CHAR (1)      DEFAULT (' ') NOT NULL,
    [Freight]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [InBal]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [LineCntr]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [NoteID]            INT           DEFAULT ((0)) NOT NULL,
    [OpenDoc]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [PC_Status]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [PerClosed]         CHAR (6)      DEFAULT (' ') NOT NULL,
    [PerEnt]            CHAR (6)      DEFAULT (' ') NOT NULL,
    [PONbr]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [ProjectID]         CHAR (16)     DEFAULT (' ') NOT NULL,
    [RcptAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptAmtTot]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptCtrlAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptCtrlQty]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptDate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [RcptItemTotal]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptNbr]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [RcptQty]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptQtyTot]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptType]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [ReopenPO]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [Rlsed]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [RMAID]             CHAR (15)     DEFAULT (' ') NOT NULL,
    [S4Future01]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [ServiceCallID]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipperID]         CHAR (15)     DEFAULT (' ') NOT NULL,
    [Status]            CHAR (1)      DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VendID]            CHAR (15)     DEFAULT (' ') NOT NULL,
    [VendInvcNbr]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [VouchStage]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [WayBillNbr]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [POReceipt0] PRIMARY KEY CLUSTERED ([RcptNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [POReceipt1]
    ON [dbo].[POReceipt]([BatNbr] ASC, [RcptNbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [POReceipt2]
    ON [dbo].[POReceipt]([PONbr] ASC, [RcptNbr] ASC) WITH (FILLFACTOR = 100);

