CREATE TABLE [dbo].[BCPOReceipts] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_BCPOReceipts_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_BCPOReceipts_Crtd_User] DEFAULT (' ') NOT NULL,
    [Freight]       FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_Freight] DEFAULT ((0)) NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_BCPOReceipts_InvtID] DEFAULT (' ') NOT NULL,
    [LineID]        SMALLINT      CONSTRAINT [DF_BCPOReceipts_LineID] DEFAULT ((0)) NOT NULL,
    [LotSerNbr]     CHAR (15)     CONSTRAINT [DF_BCPOReceipts_LotSerNbr] DEFAULT (' ') NOT NULL,
    [LotSerTrack]   CHAR (1)      CONSTRAINT [DF_BCPOReceipts_LotSerTrack] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_BCPOReceipts_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_BCPOReceipts_LUpd_User] DEFAULT (' ') NOT NULL,
    [PONumber]      CHAR (10)     CONSTRAINT [DF_BCPOReceipts_PONumber] DEFAULT (' ') NOT NULL,
    [Qty]           FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_Qty] DEFAULT ((0)) NOT NULL,
    [ReceiptNbr]    CHAR (10)     CONSTRAINT [DF_BCPOReceipts_ReceiptNbr] DEFAULT (' ') NOT NULL,
    [RefNbr]        CHAR (6)      CONSTRAINT [DF_BCPOReceipts_RefNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_BCPOReceipts_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_BCPOReceipts_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_BCPOReceipts_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_BCPOReceipts_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_BCPOReceipts_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_BCPOReceipts_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]        CHAR (6)      CONSTRAINT [DF_BCPOReceipts_SiteID] DEFAULT (' ') NOT NULL,
    [Status]        CHAR (2)      CONSTRAINT [DF_BCPOReceipts_Status] DEFAULT (' ') NOT NULL,
    [sUser]         CHAR (10)     CONSTRAINT [DF_BCPOReceipts_sUser] DEFAULT (' ') NOT NULL,
    [UnitCost]      FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_UnitCost] DEFAULT ((0)) NOT NULL,
    [UnitDesc]      CHAR (6)      CONSTRAINT [DF_BCPOReceipts_UnitDesc] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_BCPOReceipts_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_BCPOReceipts_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_BCPOReceipts_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_BCPOReceipts_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_BCPOReceipts_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_BCPOReceipts_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VendorItemID]  CHAR (15)     CONSTRAINT [DF_BCPOReceipts_VendorItemID] DEFAULT (' ') NOT NULL,
    [WhseLoc]       CHAR (10)     CONSTRAINT [DF_BCPOReceipts_WhseLoc] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL
);

