CREATE TABLE [dbo].[VendorRebate] (
    [AuthBy]        CHAR (30)     CONSTRAINT [DF_VendorRebate_AuthBy] DEFAULT (' ') NOT NULL,
    [AuthDate]      SMALLDATETIME CONSTRAINT [DF_VendorRebate_AuthDate] DEFAULT ('01/01/1900') NOT NULL,
    [AuthNbr]       CHAR (30)     CONSTRAINT [DF_VendorRebate_AuthNbr] DEFAULT (' ') NOT NULL,
    [ContractNbr]   CHAR (30)     CONSTRAINT [DF_VendorRebate_ContractNbr] DEFAULT (' ') NOT NULL,
    [CostAdj]       FLOAT (53)    CONSTRAINT [DF_VendorRebate_CostAdj] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_VendorRebate_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_VendorRebate_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_VendorRebate_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCostAdj]   FLOAT (53)    CONSTRAINT [DF_VendorRebate_CuryCostAdj] DEFAULT ((0)) NOT NULL,
    [CuryEffDate]   SMALLDATETIME CONSTRAINT [DF_VendorRebate_CuryEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryID]        CHAR (4)      CONSTRAINT [DF_VendorRebate_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]   CHAR (1)      CONSTRAINT [DF_VendorRebate_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]      FLOAT (53)    CONSTRAINT [DF_VendorRebate_CuryRate] DEFAULT ((0)) NOT NULL,
    [CuryRateType]  CHAR (6)      CONSTRAINT [DF_VendorRebate_CuryRateType] DEFAULT (' ') NOT NULL,
    [CustID]        CHAR (15)     CONSTRAINT [DF_VendorRebate_CustID] DEFAULT (' ') NOT NULL,
    [ExpireDate]    SMALLDATETIME CONSTRAINT [DF_VendorRebate_ExpireDate] DEFAULT ('01/01/1900') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_VendorRebate_InvtID] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_VendorRebate_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_VendorRebate_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_VendorRebate_LUpd_User] DEFAULT (' ') NOT NULL,
    [MaxQty]        FLOAT (53)    CONSTRAINT [DF_VendorRebate_MaxQty] DEFAULT ((0)) NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_VendorRebate_NoteID] DEFAULT ((0)) NOT NULL,
    [RebateID]      CHAR (10)     CONSTRAINT [DF_VendorRebate_RebateID] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_VendorRebate_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_VendorRebate_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_VendorRebate_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_VendorRebate_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_VendorRebate_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_VendorRebate_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_VendorRebate_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_VendorRebate_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_VendorRebate_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_VendorRebate_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_VendorRebate_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_VendorRebate_S4Future12] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_VendorRebate_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_VendorRebate_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_VendorRebate_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_VendorRebate_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_VendorRebate_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_VendorRebate_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_VendorRebate_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_VendorRebate_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_VendorRebate_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_VendorRebate_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]        CHAR (15)     CONSTRAINT [DF_VendorRebate_VendID] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [VendorRebate0] PRIMARY KEY CLUSTERED ([RebateID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [VendorRebate1]
    ON [dbo].[VendorRebate]([CustID] ASC, [InvtID] ASC, [ExpireDate] ASC) WITH (FILLFACTOR = 90);

