CREATE TABLE [dbo].[BM11600_Wrk] (
    [CmpnentSiteID] CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_CmpnentSiteID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_BM11600_Wrk_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (47)     CONSTRAINT [DF_BM11600_Wrk_Crtd_User] DEFAULT (' ') NOT NULL,
    [CSequence]     CHAR (40)     CONSTRAINT [DF_BM11600_Wrk_CSequence] DEFAULT (' ') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_InvtID] DEFAULT (' ') NOT NULL,
    [ISequence]     INT           CONSTRAINT [DF_BM11600_Wrk_ISequence] DEFAULT ((0)) NOT NULL,
    [KitID]         CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_KitID] DEFAULT (' ') NOT NULL,
    [KitNbr]        INT           CONSTRAINT [DF_BM11600_Wrk_KitNbr] DEFAULT ((0)) NOT NULL,
    [KitStatus]     CHAR (1)      CONSTRAINT [DF_BM11600_Wrk_KitStatus] DEFAULT (' ') NOT NULL,
    [LevelNbr]      INT           CONSTRAINT [DF_BM11600_Wrk_LevelNbr] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_BM11600_Wrk_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (47)     CONSTRAINT [DF_BM11600_Wrk_LUpd_User] DEFAULT (' ') NOT NULL,
    [Quantity]      FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_Quantity] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_BM11600_Wrk_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_BM11600_Wrk_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_S4Future12] DEFAULT (' ') NOT NULL,
    [Sequence]      CHAR (5)      CONSTRAINT [DF_BM11600_Wrk_Sequence] DEFAULT (' ') NOT NULL,
    [SiteID]        CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_SiteID] DEFAULT (' ') NOT NULL,
    [StartKit]      CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_StartKit] DEFAULT (' ') NOT NULL,
    [Status]        CHAR (1)      CONSTRAINT [DF_BM11600_Wrk_Status] DEFAULT (' ') NOT NULL,
    [SubKitStatus]  CHAR (1)      CONSTRAINT [DF_BM11600_Wrk_SubKitStatus] DEFAULT (' ') NOT NULL,
    [TotQuantity]   FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_TotQuantity] DEFAULT ((0)) NOT NULL,
    [TotStdQty]     FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_TotStdQty] DEFAULT ((0)) NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_BM11600_Wrk_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_BM11600_Wrk_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_BM11600_Wrk_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_BM11600_Wrk_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [BM11600_Wrk0] PRIMARY KEY CLUSTERED ([ISequence] ASC, [LUpd_Prog] ASC, [LUpd_User] ASC) WITH (FILLFACTOR = 90)
);

