CREATE TABLE [dbo].[INSetup] (
    [ActivateLang]        SMALLINT      CONSTRAINT [DF_INSetup_ActivateLang] DEFAULT ((0)) NOT NULL,
    [AdjustmentsAcct]     CHAR (10)     CONSTRAINT [DF_INSetup_AdjustmentsAcct] DEFAULT (' ') NOT NULL,
    [AdjustmentsSub]      CHAR (24)     CONSTRAINT [DF_INSetup_AdjustmentsSub] DEFAULT (' ') NOT NULL,
    [AllowCostEntry]      SMALLINT      CONSTRAINT [DF_INSetup_AllowCostEntry] DEFAULT ((0)) NOT NULL,
    [APClearingAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_APClearingAcct] DEFAULT (' ') NOT NULL,
    [APClearingSub]       CHAR (24)     CONSTRAINT [DF_INSetup_APClearingSub] DEFAULT (' ') NOT NULL,
    [ARClearingAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_ARClearingAcct] DEFAULT (' ') NOT NULL,
    [ARClearingSub]       CHAR (24)     CONSTRAINT [DF_INSetup_ARClearingSub] DEFAULT (' ') NOT NULL,
    [AutoAdjustEntry]     SMALLINT      CONSTRAINT [DF_INSetup_AutoAdjustEntry] DEFAULT ((0)) NOT NULL,
    [AutoBatRpt]          SMALLINT      CONSTRAINT [DF_INSetup_AutoBatRpt] DEFAULT ((0)) NOT NULL,
    [AutoRelease]         CHAR (1)      CONSTRAINT [DF_INSetup_AutoRelease] DEFAULT (' ') NOT NULL,
    [BMICuryID]           CHAR (4)      CONSTRAINT [DF_INSetup_BMICuryID] DEFAULT (' ') NOT NULL,
    [BMIDfltRtTp]         CHAR (6)      CONSTRAINT [DF_INSetup_BMIDfltRtTp] DEFAULT (' ') NOT NULL,
    [BMIEnabled]          SMALLINT      CONSTRAINT [DF_INSetup_BMIEnabled] DEFAULT ((0)) NOT NULL,
    [CPSOnOff]            SMALLINT      CONSTRAINT [DF_INSetup_CPSOnOff] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_INSetup_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_INSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_INSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [CurrPerNbr]          CHAR (6)      CONSTRAINT [DF_INSetup_CurrPerNbr] DEFAULT (' ') NOT NULL,
    [DecPlPrcCst]         SMALLINT      CONSTRAINT [DF_INSetup_DecPlPrcCst] DEFAULT ((0)) NOT NULL,
    [DecPlQty]            SMALLINT      CONSTRAINT [DF_INSetup_DecPlQty] DEFAULT ((0)) NOT NULL,
    [DfltChkOrdQty]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltChkOrdQty] DEFAULT (' ') NOT NULL,
    [DfltCOGSAcct]        CHAR (10)     CONSTRAINT [DF_INSetup_DfltCOGSAcct] DEFAULT (' ') NOT NULL,
    [DfltCOGSSub]         CHAR (24)     CONSTRAINT [DF_INSetup_DfltCOGSSub] DEFAULT (' ') NOT NULL,
    [DfltDIscPrc]         CHAR (1)      CONSTRAINT [DF_INSetup_DfltDIscPrc] DEFAULT (' ') NOT NULL,
    [DfltInvtAcct]        CHAR (10)     CONSTRAINT [DF_INSetup_DfltInvtAcct] DEFAULT (' ') NOT NULL,
    [DfltInvtLeadTime]    FLOAT (53)    CONSTRAINT [DF_INSetup_DfltInvtLeadTime] DEFAULT ((0)) NOT NULL,
    [DfltInvtMfgLeadTime] FLOAT (53)    CONSTRAINT [DF_INSetup_DfltInvtMfgLeadTime] DEFAULT ((0)) NOT NULL,
    [DfltInvtSub]         CHAR (24)     CONSTRAINT [DF_INSetup_DfltInvtSub] DEFAULT (' ') NOT NULL,
    [DfltInvtType]        CHAR (1)      CONSTRAINT [DF_INSetup_DfltInvtType] DEFAULT (' ') NOT NULL,
    [DfltItmSiteAcct]     CHAR (10)     CONSTRAINT [DF_INSetup_DfltItmSiteAcct] DEFAULT (' ') NOT NULL,
    [DfltLCVarianceAcct]  CHAR (10)     CONSTRAINT [DF_INSetup_DfltLCVarianceAcct] DEFAULT (' ') NOT NULL,
    [DfltLCVarianceSub]   CHAR (24)     CONSTRAINT [DF_INSetup_DfltLCVarianceSub] DEFAULT (' ') NOT NULL,
    [DfltLotAssign]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltLotAssign] DEFAULT (' ') NOT NULL,
    [DfltlotFxdLen]       SMALLINT      CONSTRAINT [DF_INSetup_DfltlotFxdLen] DEFAULT ((0)) NOT NULL,
    [DfltLotFxdTyp]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltLotFxdTyp] DEFAULT (' ') NOT NULL,
    [DfltLotFxdVal]       CHAR (12)     CONSTRAINT [DF_INSetup_DfltLotFxdVal] DEFAULT (' ') NOT NULL,
    [DfltLotMthd]         CHAR (1)      CONSTRAINT [DF_INSetup_DfltLotMthd] DEFAULT (' ') NOT NULL,
    [DfltLotNumLen]       SMALLINT      CONSTRAINT [DF_INSetup_DfltLotNumLen] DEFAULT ((0)) NOT NULL,
    [DfltLotNumVal]       CHAR (25)     CONSTRAINT [DF_INSetup_DfltLotNumVal] DEFAULT (' ') NOT NULL,
    [DfltLotSerTrack]     CHAR (1)      CONSTRAINT [DF_INSetup_DfltLotSerTrack] DEFAULT (' ') NOT NULL,
    [DfltLotShelfLife]    SMALLINT      CONSTRAINT [DF_INSetup_DfltLotShelfLife] DEFAULT ((0)) NOT NULL,
    [DfltPhysQty]         SMALLINT      CONSTRAINT [DF_INSetup_DfltPhysQty] DEFAULT ((0)) NOT NULL,
    [DfltPPVAcct]         CHAR (10)     CONSTRAINT [DF_INSetup_DfltPPVAcct] DEFAULT (' ') NOT NULL,
    [DfltPPVSub]          CHAR (24)     CONSTRAINT [DF_INSetup_DfltPPVSub] DEFAULT (' ') NOT NULL,
    [DfltProdClass]       CHAR (6)      CONSTRAINT [DF_INSetup_DfltProdClass] DEFAULT (' ') NOT NULL,
    [DfltSalesAcct]       CHAR (10)     CONSTRAINT [DF_INSetup_DfltSalesAcct] DEFAULT (' ') NOT NULL,
    [DfltSalesSub]        CHAR (24)     CONSTRAINT [DF_INSetup_DfltSalesSub] DEFAULT (' ') NOT NULL,
    [DfltSerAssign]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltSerAssign] DEFAULT (' ') NOT NULL,
    [DfltSerFxdLen]       SMALLINT      CONSTRAINT [DF_INSetup_DfltSerFxdLen] DEFAULT ((0)) NOT NULL,
    [DfltSerFxdTyp]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltSerFxdTyp] DEFAULT (' ') NOT NULL,
    [DfltSerFxdVal]       CHAR (12)     CONSTRAINT [DF_INSetup_DfltSerFxdVal] DEFAULT (' ') NOT NULL,
    [DfltSerMethod]       CHAR (1)      CONSTRAINT [DF_INSetup_DfltSerMethod] DEFAULT (' ') NOT NULL,
    [DfltSerNumLen]       SMALLINT      CONSTRAINT [DF_INSetup_DfltSerNumLen] DEFAULT ((0)) NOT NULL,
    [DfltSerNumVal]       CHAR (25)     CONSTRAINT [DF_INSetup_DfltSerNumVal] DEFAULT (' ') NOT NULL,
    [DfltSerShelfLife]    SMALLINT      CONSTRAINT [DF_INSetup_DfltSerShelfLife] DEFAULT ((0)) NOT NULL,
    [DfltShpnotInvAcct]   CHAR (10)     CONSTRAINT [DF_INSetup_DfltShpnotInvAcct] DEFAULT (' ') NOT NULL,
    [DfltShpnotInvSub]    CHAR (24)     CONSTRAINT [DF_INSetup_DfltShpnotInvSub] DEFAULT (' ') NOT NULL,
    [DfltSite]            CHAR (10)     CONSTRAINT [DF_INSetup_DfltSite] DEFAULT (' ') NOT NULL,
    [DfltSlsTaxCat]       CHAR (10)     CONSTRAINT [DF_INSetup_DfltSlsTaxCat] DEFAULT (' ') NOT NULL,
    [DfltSource]          CHAR (1)      CONSTRAINT [DF_INSetup_DfltSource] DEFAULT (' ') NOT NULL,
    [DfltStatus]          CHAR (1)      CONSTRAINT [DF_INSetup_DfltStatus] DEFAULT (' ') NOT NULL,
    [DfltStatusQtyZero]   CHAR (1)      CONSTRAINT [DF_INSetup_DfltStatusQtyZero] DEFAULT (' ') NOT NULL,
    [DfltStkItem]         SMALLINT      CONSTRAINT [DF_INSetup_DfltStkItem] DEFAULT ((0)) NOT NULL,
    [DfltValMthd]         CHAR (1)      CONSTRAINT [DF_INSetup_DfltValMthd] DEFAULT (' ') NOT NULL,
    [DfltVarAcct]         CHAR (10)     CONSTRAINT [DF_INSetup_DfltVarAcct] DEFAULT (' ') NOT NULL,
    [DfltVarSub]          CHAR (24)     CONSTRAINT [DF_INSetup_DfltVarSub] DEFAULT (' ') NOT NULL,
    [ExplInvoice]         SMALLINT      CONSTRAINT [DF_INSetup_ExplInvoice] DEFAULT ((0)) NOT NULL,
    [ExplOrder]           SMALLINT      CONSTRAINT [DF_INSetup_ExplOrder] DEFAULT ((0)) NOT NULL,
    [ExplPackSlip]        SMALLINT      CONSTRAINT [DF_INSetup_ExplPackSlip] DEFAULT ((0)) NOT NULL,
    [ExplPickList]        SMALLINT      CONSTRAINT [DF_INSetup_ExplPickList] DEFAULT ((0)) NOT NULL,
    [ExplShipping]        SMALLINT      CONSTRAINT [DF_INSetup_ExplShipping] DEFAULT ((0)) NOT NULL,
    [ExprdLotNbrs]        SMALLINT      CONSTRAINT [DF_INSetup_ExprdLotNbrs] DEFAULT ((0)) NOT NULL,
    [ExprdSerNbrs]        SMALLINT      CONSTRAINT [DF_INSetup_ExprdSerNbrs] DEFAULT ((0)) NOT NULL,
    [GLPostOpt]           CHAR (1)      CONSTRAINT [DF_INSetup_GLPostOpt] DEFAULT (' ') NOT NULL,
    [InclAllocQty]        SMALLINT      CONSTRAINT [DF_INSetup_InclAllocQty] DEFAULT ((0)) NOT NULL,
    [INClearingAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_INClearingAcct] DEFAULT (' ') NOT NULL,
    [INClearingSub]       CHAR (24)     CONSTRAINT [DF_INSetup_INClearingSub] DEFAULT (' ') NOT NULL,
    [InclQtyAllocWO]      SMALLINT      CONSTRAINT [DF_INSetup_InclQtyAllocWO] DEFAULT ((0)) NOT NULL,
    [InclQtyCustOrd]      SMALLINT      CONSTRAINT [DF_INSetup_InclQtyCustOrd] DEFAULT ((0)) NOT NULL,
    [InclQtyInTransit]    SMALLINT      CONSTRAINT [DF_INSetup_InclQtyInTransit] DEFAULT ((0)) NOT NULL,
    [InclQtyOnBO]         SMALLINT      CONSTRAINT [DF_INSetup_InclQtyOnBO] DEFAULT ((0)) NOT NULL,
    [InclQtyOnPO]         SMALLINT      CONSTRAINT [DF_INSetup_InclQtyOnPO] DEFAULT ((0)) NOT NULL,
    [InclQtyOnWO]         SMALLINT      CONSTRAINT [DF_INSetup_InclQtyOnWO] DEFAULT ((0)) NOT NULL,
    [InclWOFirmDemand]    SMALLINT      CONSTRAINT [DF_INSetup_InclWOFirmDemand] DEFAULT ((0)) NOT NULL,
    [InclWOFirmSupply]    SMALLINT      CONSTRAINT [DF_INSetup_InclWOFirmSupply] DEFAULT ((0)) NOT NULL,
    [InclWORlsedDemand]   SMALLINT      CONSTRAINT [DF_INSetup_InclWORlsedDemand] DEFAULT ((0)) NOT NULL,
    [InclWORlsedSupply]   SMALLINT      CONSTRAINT [DF_INSetup_InclWORlsedSupply] DEFAULT ((0)) NOT NULL,
    [Init]                SMALLINT      CONSTRAINT [DF_INSetup_Init] DEFAULT ((0)) NOT NULL,
    [InTransitAcct]       CHAR (10)     CONSTRAINT [DF_INSetup_InTransitAcct] DEFAULT (' ') NOT NULL,
    [InTransitSub]        CHAR (24)     CONSTRAINT [DF_INSetup_InTransitSub] DEFAULT (' ') NOT NULL,
    [IssuesAcct]          CHAR (10)     CONSTRAINT [DF_INSetup_IssuesAcct] DEFAULT (' ') NOT NULL,
    [IssuesSub]           CHAR (24)     CONSTRAINT [DF_INSetup_IssuesSub] DEFAULT (' ') NOT NULL,
    [LanguageID]          CHAR (4)      CONSTRAINT [DF_INSetup_LanguageID] DEFAULT (' ') NOT NULL,
    [LastArchiveDate]     SMALLDATETIME CONSTRAINT [DF_INSetup_LastArchiveDate] DEFAULT ('01/01/1900') NOT NULL,
    [LastBatNbr]          CHAR (10)     CONSTRAINT [DF_INSetup_LastBatNbr] DEFAULT (' ') NOT NULL,
    [LastCountDate]       SMALLDATETIME CONSTRAINT [DF_INSetup_LastCountDate] DEFAULT ('01/01/1900') NOT NULL,
    [LastTagNbr]          INT           CONSTRAINT [DF_INSetup_LastTagNbr] DEFAULT ((0)) NOT NULL,
    [LotSerRetHist]       SMALLINT      CONSTRAINT [DF_INSetup_LotSerRetHist] DEFAULT ((0)) NOT NULL,
    [LstSlsPrcID]         CHAR (10)     CONSTRAINT [DF_INSetup_LstSlsPrcID] DEFAULT (' ') NOT NULL,
    [LstTrnsfrDocNbr]     CHAR (10)     CONSTRAINT [DF_INSetup_LstTrnsfrDocNbr] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME CONSTRAINT [DF_INSetup_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      CONSTRAINT [DF_INSetup_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]           CHAR (10)     CONSTRAINT [DF_INSetup_LUpd_User] DEFAULT (' ') NOT NULL,
    [MaterialType]        CHAR (10)     CONSTRAINT [DF_INSetup_MaterialType] DEFAULT (' ') NOT NULL,
    [MatlOvhCalc]         CHAR (1)      CONSTRAINT [DF_INSetup_MatlOvhCalc] DEFAULT (' ') NOT NULL,
    [MatlOvhOffAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_MatlOvhOffAcct] DEFAULT (' ') NOT NULL,
    [MatlOvhOffSub]       CHAR (24)     CONSTRAINT [DF_INSetup_MatlOvhOffSub] DEFAULT (' ') NOT NULL,
    [MatlOvhRatePct]      CHAR (1)      CONSTRAINT [DF_INSetup_MatlOvhRatePct] DEFAULT (' ') NOT NULL,
    [MatlOvhVarAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_MatlOvhVarAcct] DEFAULT (' ') NOT NULL,
    [MatlOvhVarSub]       CHAR (24)     CONSTRAINT [DF_INSetup_MatlOvhVarSub] DEFAULT (' ') NOT NULL,
    [MfgClassID]          CHAR (10)     CONSTRAINT [DF_INSetup_MfgClassID] DEFAULT (' ') NOT NULL,
    [MinGrossProfit]      FLOAT (53)    CONSTRAINT [DF_INSetup_MinGrossProfit] DEFAULT ((0)) NOT NULL,
    [MultWhse]            SMALLINT      CONSTRAINT [DF_INSetup_MultWhse] DEFAULT ((0)) NOT NULL,
    [NbrCounts]           SMALLINT      CONSTRAINT [DF_INSetup_NbrCounts] DEFAULT ((0)) NOT NULL,
    [NbrCycleCounts]      SMALLINT      CONSTRAINT [DF_INSetup_NbrCycleCounts] DEFAULT ((0)) NOT NULL,
    [NegQty]              SMALLINT      CONSTRAINT [DF_INSetup_NegQty] DEFAULT ((0)) NOT NULL,
    [NonKitAssy]          SMALLINT      CONSTRAINT [DF_INSetup_NonKitAssy] DEFAULT ((0)) NOT NULL,
    [NoteID]              INT           CONSTRAINT [DF_INSetup_NoteID] DEFAULT ((0)) NOT NULL,
    [OverSoldCostLayers]  SMALLINT      CONSTRAINT [DF_INSetup_OverSoldCostLayers] DEFAULT ((0)) NOT NULL,
    [PerNbr]              CHAR (6)      CONSTRAINT [DF_INSetup_PerNbr] DEFAULT (' ') NOT NULL,
    [PerRetPITrans]       SMALLINT      CONSTRAINT [DF_INSetup_PerRetPITrans] DEFAULT ((0)) NOT NULL,
    [PerRetTran]          SMALLINT      CONSTRAINT [DF_INSetup_PerRetTran] DEFAULT ((0)) NOT NULL,
    [PhysAdjVarAcct]      CHAR (10)     CONSTRAINT [DF_INSetup_PhysAdjVarAcct] DEFAULT (' ') NOT NULL,
    [PhysAdjVarSub]       CHAR (24)     CONSTRAINT [DF_INSetup_PhysAdjVarSub] DEFAULT (' ') NOT NULL,
    [PIABC]               CHAR (1)      CONSTRAINT [DF_INSetup_PIABC] DEFAULT (' ') NOT NULL,
    [PMAvail]             SMALLINT      CONSTRAINT [DF_INSetup_PMAvail] DEFAULT ((0)) NOT NULL,
    [RollBackBatches]     SMALLINT      CONSTRAINT [DF_INSetup_RollBackBatches] DEFAULT ((0)) NOT NULL,
    [RollupCost]          SMALLINT      CONSTRAINT [DF_INSetup_RollupCost] DEFAULT ((0)) NOT NULL,
    [RollupPrice]         SMALLINT      CONSTRAINT [DF_INSetup_RollupPrice] DEFAULT ((0)) NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_INSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_INSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_INSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_INSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_INSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_INSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_INSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_INSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_INSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_INSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_INSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_INSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [SerAssign]           CHAR (1)      CONSTRAINT [DF_INSetup_SerAssign] DEFAULT (' ') NOT NULL,
    [SetupId]             CHAR (2)      CONSTRAINT [DF_INSetup_SetupId] DEFAULT (' ') NOT NULL,
    [SiteID]              CHAR (10)     CONSTRAINT [DF_INSetup_SiteID] DEFAULT (' ') NOT NULL,
    [SpecChar]            CHAR (24)     CONSTRAINT [DF_INSetup_SpecChar] DEFAULT (' ') NOT NULL,
    [StdCstRevalAcct]     CHAR (10)     CONSTRAINT [DF_INSetup_StdCstRevalAcct] DEFAULT (' ') NOT NULL,
    [StdCstRevalSub]      CHAR (24)     CONSTRAINT [DF_INSetup_StdCstRevalSub] DEFAULT (' ') NOT NULL,
    [TableBypass]         SMALLINT      CONSTRAINT [DF_INSetup_TableBypass] DEFAULT ((0)) NOT NULL,
    [Tagged]              SMALLINT      CONSTRAINT [DF_INSetup_Tagged] DEFAULT ((0)) NOT NULL,
    [TranCOGSSub]         CHAR (1)      CONSTRAINT [DF_INSetup_TranCOGSSub] DEFAULT (' ') NOT NULL,
    [UpdateGL]            SMALLINT      CONSTRAINT [DF_INSetup_UpdateGL] DEFAULT ((0)) NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_INSetup_User1] DEFAULT (' ') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_INSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]               FLOAT (53)    CONSTRAINT [DF_INSetup_User3] DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    CONSTRAINT [DF_INSetup_User4] DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     CONSTRAINT [DF_INSetup_User5] DEFAULT (' ') NOT NULL,
    [User6]               CHAR (10)     CONSTRAINT [DF_INSetup_User6] DEFAULT (' ') NOT NULL,
    [User7]               SMALLDATETIME CONSTRAINT [DF_INSetup_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME CONSTRAINT [DF_INSetup_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VolUnit]             CHAR (6)      CONSTRAINT [DF_INSetup_VolUnit] DEFAULT (' ') NOT NULL,
    [WhseLocValid]        CHAR (1)      CONSTRAINT [DF_INSetup_WhseLocValid] DEFAULT (' ') NOT NULL,
    [WtUnit]              CHAR (6)      CONSTRAINT [DF_INSetup_WtUnit] DEFAULT (' ') NOT NULL,
    [YrsRetArchTran]      SMALLINT      CONSTRAINT [DF_INSetup_YrsRetArchTran] DEFAULT ((0)) NOT NULL,
    [YrsRetHist]          SMALLINT      CONSTRAINT [DF_INSetup_YrsRetHist] DEFAULT ((0)) NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [INSetup0] PRIMARY KEY CLUSTERED ([SetupId] ASC) WITH (FILLFACTOR = 90)
);

