CREATE TABLE [dbo].[PJBillCh] (
    [appnbr]             CHAR (6)      NOT NULL,
    [arch_pjt]           CHAR (16)     NOT NULL,
    [BaseCuryID]         CHAR (4)      NOT NULL,
    [bh_01]              CHAR (30)     NOT NULL,
    [bh_02]              CHAR (30)     NOT NULL,
    [bh_03]              CHAR (16)     NOT NULL,
    [bh_04]              CHAR (16)     NOT NULL,
    [bh_05]              CHAR (4)      NOT NULL,
    [bh_06]              FLOAT (53)    NOT NULL,
    [bh_07]              FLOAT (53)    NOT NULL,
    [bh_08]              SMALLDATETIME NOT NULL,
    [bh_09]              SMALLDATETIME NOT NULL,
    [bh_10]              INT           NOT NULL,
    [bh_11]              CHAR (30)     NOT NULL,
    [bh_12]              CHAR (30)     NOT NULL,
    [bh_13]              CHAR (16)     NOT NULL,
    [bh_14]              CHAR (16)     NOT NULL,
    [bh_15]              CHAR (4)      NOT NULL,
    [bh_16]              FLOAT (53)    NOT NULL,
    [bh_17]              FLOAT (53)    NOT NULL,
    [bh_18]              SMALLDATETIME NOT NULL,
    [bh_19]              SMALLDATETIME NOT NULL,
    [bh_20]              INT           NOT NULL,
    [CpnyId]             CHAR (10)     NOT NULL,
    [crtd_datetime]      SMALLDATETIME NOT NULL,
    [crtd_prog]          CHAR (8)      NOT NULL,
    [crtd_user]          CHAR (10)     NOT NULL,
    [CuryEffDate]        SMALLDATETIME NOT NULL,
    [CuryId]             CHAR (4)      NOT NULL,
    [CuryMultDiv]        CHAR (1)      NOT NULL,
    [CuryRate]           FLOAT (53)    NOT NULL,
    [CuryRateType]       CHAR (6)      NOT NULL,
    [date_app]           SMALLDATETIME NOT NULL,
    [date_from]          SMALLDATETIME NOT NULL,
    [date_to]            SMALLDATETIME NOT NULL,
    [draft_num]          CHAR (10)     NOT NULL,
    [invoice_num]        CHAR (10)     NOT NULL,
    [lupd_datetime]      SMALLDATETIME NOT NULL,
    [lupd_prog]          CHAR (8)      NOT NULL,
    [lupd_user]          CHAR (10)     NOT NULL,
    [noteid]             INT           NOT NULL,
    [project]            CHAR (16)     NOT NULL,
    [retention_method]   CHAR (2)      NOT NULL,
    [retention_percent1] FLOAT (53)    NOT NULL,
    [retention_percent2] FLOAT (53)    NOT NULL,
    [status]             CHAR (1)      NOT NULL,
    [user1]              CHAR (30)     NOT NULL,
    [user2]              CHAR (30)     NOT NULL,
    [user3]              FLOAT (53)    NOT NULL,
    [user4]              FLOAT (53)    NOT NULL,
    [user5]              CHAR (30)     NOT NULL,
    [user6]              CHAR (30)     NOT NULL,
    [user7]              FLOAT (53)    NOT NULL,
    [user8]              FLOAT (53)    NOT NULL,
    [wsid]               INT           NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [pjbillch0] PRIMARY KEY CLUSTERED ([project] ASC, [appnbr] ASC)
);

