CREATE TABLE [dbo].[BRImportSetup] (
    [AcctLen]       SMALLINT      NOT NULL,
    [AcctPos]       SMALLINT      NOT NULL,
    [AmtLen]        SMALLINT      NOT NULL,
    [AmtPos]        SMALLINT      NOT NULL,
    [CpnyId]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DateLen]       SMALLINT      NOT NULL,
    [DatePos]       SMALLINT      NOT NULL,
    [DecimalPt]     CHAR (1)      NOT NULL,
    [DescrLen]      SMALLINT      NOT NULL,
    [DescrPos]      SMALLINT      NOT NULL,
    [Format]        SMALLINT      NOT NULL,
    [Future01]      CHAR (30)     NOT NULL,
    [Future02]      CHAR (10)     NOT NULL,
    [Future03]      SMALLDATETIME NOT NULL,
    [Future04]      FLOAT (53)    NOT NULL,
    [Future05]      INT           NOT NULL,
    [Future06]      SMALLINT      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [Process]       CHAR (1)      NOT NULL,
    [RefLen]        SMALLINT      NOT NULL,
    [RefPos]        SMALLINT      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [SetupID]       CHAR (4)      NOT NULL,
    [User01]        CHAR (30)     NOT NULL,
    [User02]        CHAR (10)     NOT NULL,
    [User03]        SMALLDATETIME NOT NULL,
    [User04]        FLOAT (53)    NOT NULL,
    [User05]        INT           NOT NULL,
    [User06]        SMALLINT      NOT NULL,
    [TStamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [BRImportSetup0] PRIMARY KEY CLUSTERED ([CpnyId] ASC) WITH (FILLFACTOR = 90)
);

