CREATE TABLE [dbo].[PJWAGEUN] (
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [effect_date]    SMALLDATETIME NOT NULL,
    [labor_class_cd] CHAR (4)      NOT NULL,
    [labor_rate]     FLOAT (53)    NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [un_id01]        CHAR (30)     NOT NULL,
    [un_id02]        CHAR (30)     NOT NULL,
    [un_id03]        CHAR (16)     NOT NULL,
    [un_id04]        CHAR (16)     NOT NULL,
    [un_id05]        CHAR (4)      NOT NULL,
    [un_id06]        FLOAT (53)    NOT NULL,
    [un_id07]        FLOAT (53)    NOT NULL,
    [un_id08]        SMALLDATETIME NOT NULL,
    [un_id09]        SMALLDATETIME NOT NULL,
    [un_id10]        INT           NOT NULL,
    [un_id11]        CHAR (30)     NOT NULL,
    [un_id12]        CHAR (30)     NOT NULL,
    [un_id13]        CHAR (16)     NOT NULL,
    [un_id14]        CHAR (16)     NOT NULL,
    [un_id15]        CHAR (4)      NOT NULL,
    [un_id16]        FLOAT (53)    NOT NULL,
    [un_id17]        FLOAT (53)    NOT NULL,
    [un_id18]        SMALLDATETIME NOT NULL,
    [un_id19]        SMALLDATETIME NOT NULL,
    [un_id20]        INT           NOT NULL,
    [union_cd]       CHAR (10)     NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [work_type]      CHAR (2)      NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjwageun0] PRIMARY KEY CLUSTERED ([union_cd] ASC, [labor_class_cd] ASC, [work_type] ASC, [effect_date] ASC) WITH (FILLFACTOR = 90)
);

