CREATE TABLE [dbo].[SOAcctSubErr] (
    [Acct]          CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_Acct] DEFAULT (' ') NOT NULL,
    [AcctDesc]      CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_AcctDesc] DEFAULT (' ') NOT NULL,
    [Amount]        FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_Amount] DEFAULT ((0)) NOT NULL,
    [CpnyID]        CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_SOAcctSubErr_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_Crtd_User] DEFAULT (' ') NOT NULL,
    [ErrorAcct]     CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_ErrorAcct] DEFAULT (' ') NOT NULL,
    [ErrorRef]      CHAR (5)      CONSTRAINT [DF_SOAcctSubErr_ErrorRef] DEFAULT (' ') NOT NULL,
    [ErrorSub]      CHAR (24)     CONSTRAINT [DF_SOAcctSubErr_ErrorSub] DEFAULT (' ') NOT NULL,
    [LineRef]       CHAR (5)      CONSTRAINT [DF_SOAcctSubErr_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_SOAcctSubErr_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_SOAcctSubErr_NoteID] DEFAULT ((0)) NOT NULL,
    [RI_ID]         SMALLINT      CONSTRAINT [DF_SOAcctSubErr_RI_ID] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_SOAcctSubErr_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_SOAcctSubErr_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipperID]     CHAR (15)     CONSTRAINT [DF_SOAcctSubErr_ShipperID] DEFAULT (' ') NOT NULL,
    [Sub]           CHAR (31)     CONSTRAINT [DF_SOAcctSubErr_Sub] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_SOAcctSubErr_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_SOAcctSubErr_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_SOAcctSubErr_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_SOAcctSubErr_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SOAcctSubErr0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [Acct] ASC, [Sub] ASC, [ShipperID] ASC, [ErrorRef] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [SOAcctSubErr1]
    ON [dbo].[SOAcctSubErr]([RI_ID] ASC) WITH (FILLFACTOR = 90);

