CREATE TABLE [dbo].[Location] (
    [CountStatus]        CHAR (1)      DEFAULT ('A') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [InvtID]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [NoteID]             INT           DEFAULT ((0)) NOT NULL,
    [PrjINQtyAlloc]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PrjINQtyAllocIN]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PrjINQtyAllocPORet] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PrjINQtyAllocSO]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PrjINQtyShipNotInv] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAlloc]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocBM]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocIN]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocOther]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocPORet]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocProjIN]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocSD]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAllocSO]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyAvail]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyOnHand]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyShipNotInv]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyWORlsedDemand]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future01]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [Selected]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [ShipConfirmQty]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SiteID]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]              CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [WhseLoc]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [Location0] PRIMARY KEY CLUSTERED ([InvtID] ASC, [SiteID] ASC, [WhseLoc] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE NONCLUSTERED INDEX [Location1]
    ON [dbo].[Location]([SiteID] ASC, [WhseLoc] ASC) WITH (FILLFACTOR = 90);

