CREATE TABLE [dbo].[AP03625_wrk] (
    [RI_ID]                SMALLINT      NOT NULL,
    [Acct]                 CHAR (10)     NULL,
    [BatNbr]               CHAR (10)     NULL,
    [CpnyID]               CHAR (10)     NULL,
    [DocClass]             CHAR (1)      NULL,
    [DocCnt]               FLOAT (53)    NULL,
    [DocDate]              SMALLDATETIME NULL,
    [DocType]              CHAR (2)      NULL,
    [OrigDocAmt]           FLOAT (53)    NULL,
    [RefNbr]               CHAR (10)     NULL,
    [Sub]                  CHAR (24)     NULL,
    [VendId]               CHAR (15)     NULL,
    [CuryID]               CHAR (4)      NULL,
    [CuryOrigDocAmt]       FLOAT (53)    NULL,
    [Vendor_Name]          CHAR (60)     NOT NULL,
    [Batch_Module]         CHAR (2)      NULL,
    [Batch_Status]         CHAR (1)      NULL,
    [APAdjust_AdjAmt]      FLOAT (53)    NULL,
    [APAdjust_AdjdDocType] CHAR (2)      NULL,
    [APAdjust_AdjDiscAmt]  FLOAT (53)    NULL,
    [APAdjust_AdjdRefNbr]  CHAR (10)     NULL,
    [APAdjust_CuryAdjGAmt] FLOAT (53)    NULL,
    [APAdj_CuryAdjGDscAmt] FLOAT (53)    NULL,
    [APDocVO_CpnyID]       CHAR (10)     NULL,
    [APDocVO_DiscBal]      FLOAT (53)    NULL,
    [APDocVO_DiscDate]     SMALLDATETIME NULL,
    [APDocVO_DueDate]      SMALLDATETIME NULL,
    [APDocVO_InvcDate]     SMALLDATETIME NULL,
    [APDocVO_InvcNbr]      CHAR (15)     NULL,
    [APDocVO_OrigDocAmt]   FLOAT (53)    NULL,
    [APDocVO_PayDate]      SMALLDATETIME NULL,
    [APDocVO_RefNbr]       CHAR (10)     NULL,
    [APDocVO_Status]       CHAR (2)      NULL,
    [APDocVO_DocType]      CHAR (2)      NULL,
    [APDocVO_CuryDiscBal]  FLOAT (53)    NULL,
    [APDVO_CuryOrigDocAmt] FLOAT (53)    NULL,
    [BWAmt]                FLOAT (53)    NULL,
    [CuryAdjGBkupWthld]    FLOAT (53)    NULL,
    [tstamp]               ROWVERSION    NOT NULL
);

