CREATE TABLE [dbo].[cftFeedTruck] (
    [Active]         INT           NULL,
    [CF01]           CHAR (30)     NOT NULL,
    [CF02]           CHAR (30)     NOT NULL,
    [CF03]           CHAR (10)     NOT NULL,
    [CF04]           CHAR (10)     NOT NULL,
    [CF05]           SMALLDATETIME NOT NULL,
    [CF06]           SMALLDATETIME NOT NULL,
    [CF07]           SMALLINT      NOT NULL,
    [CF08]           SMALLINT      NOT NULL,
    [CF09]           INT           NOT NULL,
    [CF10]           INT           NOT NULL,
    [CF11]           FLOAT (53)    NOT NULL,
    [CF12]           FLOAT (53)    NOT NULL,
    [Color]          CHAR (15)     NOT NULL,
    [Comment]        CHAR (30)     NOT NULL,
    [Comp1No]        CHAR (5)      NOT NULL,
    [Comp1Cap]       FLOAT (53)    NOT NULL,
    [Comp2No]        CHAR (5)      NOT NULL,
    [Comp2Cap]       FLOAT (53)    NOT NULL,
    [Comp3No]        CHAR (5)      NOT NULL,
    [Comp3Cap]       FLOAT (53)    NOT NULL,
    [Comp4No]        CHAR (5)      NOT NULL,
    [Comp4Cap]       FLOAT (53)    NOT NULL,
    [Comp5No]        CHAR (5)      NOT NULL,
    [Comp5Cap]       FLOAT (53)    NOT NULL,
    [Comp6No]        CHAR (5)      NOT NULL,
    [Comp6Cap]       FLOAT (53)    NOT NULL,
    [Comp7No]        CHAR (5)      NOT NULL,
    [Comp7Cap]       FLOAT (53)    NOT NULL,
    [Comp8No]        CHAR (5)      NOT NULL,
    [Comp8Cap]       FLOAT (53)    NOT NULL,
    [Comp9No]        CHAR (5)      NOT NULL,
    [Comp9Cap]       FLOAT (53)    NOT NULL,
    [Comp10No]       CHAR (5)      NOT NULL,
    [Comp10Cap]      FLOAT (53)    NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Location]       CHAR (30)     NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [Manufacturer]   CHAR (10)     NOT NULL,
    [MaxLoad]        FLOAT (53)    NOT NULL,
    [Model]          CHAR (10)     NOT NULL,
    [NoCompartments] INT           NOT NULL,
    [NoteID]         INT           NOT NULL,
    [TruckID]        CHAR (6)      NOT NULL,
    [VendorID]       CHAR (15)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [cftFeedTruck0] PRIMARY KEY CLUSTERED ([TruckID] ASC, [Location] ASC) WITH (FILLFACTOR = 90)
);

