CREATE TABLE [dbo].[EarnDed] (
    [AddlCrAmt]           FLOAT (53)    NOT NULL,
    [AddlExmptAmt]        FLOAT (53)    NOT NULL,
    [ArrgCurr]            FLOAT (53)    NOT NULL,
    [ArrgEmpAllow]        SMALLINT      NOT NULL,
    [ArrgYTD]             FLOAT (53)    NOT NULL,
    [CalMaxYtdDed]        FLOAT (53)    NOT NULL,
    [CalYr]               CHAR (4)      NOT NULL,
    [CalYtdEarnDed]       FLOAT (53)    NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [CurrEarnDedAmt]      FLOAT (53)    NOT NULL,
    [CurrRptEarnSubjDed]  FLOAT (53)    NOT NULL,
    [CurrUnits]           FLOAT (53)    NOT NULL,
    [DedSequence]         SMALLINT      NOT NULL,
    [EarnDedId]           CHAR (10)     NOT NULL,
    [EarnDedType]         CHAR (1)      NOT NULL,
    [EDType]              CHAR (1)      NOT NULL,
    [EmpId]               CHAR (10)     NOT NULL,
    [Exmpt]               SMALLINT      NOT NULL,
    [FxdPctRate]          FLOAT (53)    NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME NOT NULL,
    [LUpd_Prog]           CHAR (8)      NOT NULL,
    [LUpd_User]           CHAR (10)     NOT NULL,
    [MtdEarnDed00]        FLOAT (53)    NOT NULL,
    [MtdEarnDed01]        FLOAT (53)    NOT NULL,
    [MtdEarnDed02]        FLOAT (53)    NOT NULL,
    [MtdEarnDed03]        FLOAT (53)    NOT NULL,
    [MtdEarnDed04]        FLOAT (53)    NOT NULL,
    [MtdEarnDed05]        FLOAT (53)    NOT NULL,
    [MtdEarnDed06]        FLOAT (53)    NOT NULL,
    [MtdEarnDed07]        FLOAT (53)    NOT NULL,
    [MtdEarnDed08]        FLOAT (53)    NOT NULL,
    [MtdEarnDed09]        FLOAT (53)    NOT NULL,
    [MtdEarnDed10]        FLOAT (53)    NOT NULL,
    [MtdEarnDed11]        FLOAT (53)    NOT NULL,
    [MtdUnits00]          FLOAT (53)    NOT NULL,
    [MtdUnits01]          FLOAT (53)    NOT NULL,
    [MtdUnits02]          FLOAT (53)    NOT NULL,
    [MtdUnits03]          FLOAT (53)    NOT NULL,
    [MtdUnits04]          FLOAT (53)    NOT NULL,
    [MtdUnits05]          FLOAT (53)    NOT NULL,
    [MtdUnits06]          FLOAT (53)    NOT NULL,
    [MtdUnits07]          FLOAT (53)    NOT NULL,
    [MtdUnits08]          FLOAT (53)    NOT NULL,
    [MtdUnits09]          FLOAT (53)    NOT NULL,
    [MtdUnits10]          FLOAT (53)    NOT NULL,
    [MtdUnits11]          FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed00] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed01] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed02] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed03] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed04] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed05] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed06] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed07] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed08] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed09] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed10] FLOAT (53)    NOT NULL,
    [MtdRptEarnSubjDed11] FLOAT (53)    NOT NULL,
    [NbrOthrExmpt]        SMALLINT      NOT NULL,
    [NbrPersExmpt]        SMALLINT      NOT NULL,
    [NoteId]              INT           NOT NULL,
    [QtdEarnDed00]        FLOAT (53)    NOT NULL,
    [QtdEarnDed01]        FLOAT (53)    NOT NULL,
    [QtdEarnDed02]        FLOAT (53)    NOT NULL,
    [QtdEarnDed03]        FLOAT (53)    NOT NULL,
    [QtdRptEarnSubjDed00] FLOAT (53)    NOT NULL,
    [QtdRptEarnSubjDed01] FLOAT (53)    NOT NULL,
    [QtdRptEarnSubjDed02] FLOAT (53)    NOT NULL,
    [QtdRptEarnSubjDed03] FLOAT (53)    NOT NULL,
    [S4Future01]          CHAR (30)     NOT NULL,
    [S4Future02]          CHAR (30)     NOT NULL,
    [S4Future03]          FLOAT (53)    NOT NULL,
    [S4Future04]          FLOAT (53)    NOT NULL,
    [S4Future05]          FLOAT (53)    NOT NULL,
    [S4Future06]          FLOAT (53)    NOT NULL,
    [S4Future07]          SMALLDATETIME NOT NULL,
    [S4Future08]          SMALLDATETIME NOT NULL,
    [S4Future09]          INT           NOT NULL,
    [S4Future10]          INT           NOT NULL,
    [S4Future11]          CHAR (10)     NOT NULL,
    [S4Future12]          CHAR (10)     NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [WrkLocId]            CHAR (6)      NOT NULL,
    [YtdPerTkn]           SMALLINT      NOT NULL,
    [YtdRptEarnSubjDed]   FLOAT (53)    NOT NULL,
    [YtdUnits]            FLOAT (53)    NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [EarnDed0] PRIMARY KEY CLUSTERED ([EmpId] ASC, [CalYr] ASC, [EDType] ASC, [WrkLocId] ASC, [EarnDedId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [EarnDed1]
    ON [dbo].[EarnDed]([EmpId] ASC, [CalYr] ASC, [EDType] ASC, [WrkLocId] ASC, [EarnDedType] ASC, [EarnDedId] ASC) WITH (FILLFACTOR = 90);

