CREATE TABLE [dbo].[smLicense] (
    [AgencyDescription]   CHAR (30)     NOT NULL,
    [BusActiveFlag]       SMALLINT      NOT NULL,
    [BusEffectiveDate]    SMALLDATETIME NOT NULL,
    [BusExpiredDate]      SMALLDATETIME NOT NULL,
    [CertificateRequired] SMALLINT      NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [Ctrd_DateTime]       SMALLDATETIME NOT NULL,
    [Description]         CHAR (30)     NOT NULL,
    [InitialAmount]       FLOAT (53)    NOT NULL,
    [InitialTerm]         SMALLINT      NOT NULL,
    [InitialTermType]     CHAR (1)      NOT NULL,
    [IssuingAgency]       CHAR (10)     NOT NULL,
    [LicenseID]           CHAR (10)     NOT NULL,
    [LicenseType]         CHAR (1)      NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [RenewalAmount]       FLOAT (53)    NOT NULL,
    [RenewalTerm]         SMALLINT      NOT NULL,
    [RenewalTermType]     CHAR (1)      NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smLicense0] PRIMARY KEY CLUSTERED ([LicenseID] ASC) WITH (FILLFACTOR = 90)
);

