CREATE TABLE [dbo].[ED810LineItem] (
    [CpnyID]         CHAR (10)     CONSTRAINT [DF_ED810LineItem_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME CONSTRAINT [DF_ED810LineItem_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]      CHAR (8)      CONSTRAINT [DF_ED810LineItem_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]      CHAR (10)     CONSTRAINT [DF_ED810LineItem_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryEffDate]    SMALLDATETIME CONSTRAINT [DF_ED810LineItem_CuryEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryID]         CHAR (4)      CONSTRAINT [DF_ED810LineItem_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]    CHAR (1)      CONSTRAINT [DF_ED810LineItem_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryPrice]      FLOAT (53)    CONSTRAINT [DF_ED810LineItem_CuryPrice] DEFAULT ((0)) NOT NULL,
    [CuryPriceExt]   FLOAT (53)    CONSTRAINT [DF_ED810LineItem_CuryPriceExt] DEFAULT ((0)) NOT NULL,
    [CuryRate]       FLOAT (53)    CONSTRAINT [DF_ED810LineItem_CuryRate] DEFAULT ((0)) NOT NULL,
    [CuryRateType]   CHAR (6)      CONSTRAINT [DF_ED810LineItem_CuryRateType] DEFAULT (' ') NOT NULL,
    [Descr]          CHAR (60)     CONSTRAINT [DF_ED810LineItem_Descr] DEFAULT (' ') NOT NULL,
    [EAN]            CHAR (48)     CONSTRAINT [DF_ED810LineItem_EAN] DEFAULT (' ') NOT NULL,
    [EDIInvID]       CHAR (10)     CONSTRAINT [DF_ED810LineItem_EDIInvID] DEFAULT (' ') NOT NULL,
    [Height]         FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]      CHAR (6)      CONSTRAINT [DF_ED810LineItem_HeightUOM] DEFAULT (' ') NOT NULL,
    [InvtID]         CHAR (30)     CONSTRAINT [DF_ED810LineItem_InvtID] DEFAULT (' ') NOT NULL,
    [ISBN]           CHAR (48)     CONSTRAINT [DF_ED810LineItem_ISBN] DEFAULT (' ') NOT NULL,
    [ItemColor]      CHAR (30)     CONSTRAINT [DF_ED810LineItem_ItemColor] DEFAULT (' ') NOT NULL,
    [ItemSize]       CHAR (30)     CONSTRAINT [DF_ED810LineItem_ItemSize] DEFAULT (' ') NOT NULL,
    [Len]            FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]         CHAR (6)      CONSTRAINT [DF_ED810LineItem_LenUOM] DEFAULT (' ') NOT NULL,
    [LineID]         INT           CONSTRAINT [DF_ED810LineItem_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]        SMALLINT      CONSTRAINT [DF_ED810LineItem_LineNbr] DEFAULT ((0)) NOT NULL,
    [LotSerNbr]      CHAR (25)     CONSTRAINT [DF_ED810LineItem_LotSerNbr] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME CONSTRAINT [DF_ED810LineItem_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]      CHAR (8)      CONSTRAINT [DF_ED810LineItem_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]      CHAR (10)     CONSTRAINT [DF_ED810LineItem_Lupd_User] DEFAULT (' ') NOT NULL,
    [MemaCode]       CHAR (48)     CONSTRAINT [DF_ED810LineItem_MemaCode] DEFAULT (' ') NOT NULL,
    [MfgPart]        CHAR (48)     CONSTRAINT [DF_ED810LineItem_MfgPart] DEFAULT (' ') NOT NULL,
    [MilSpec]        CHAR (48)     CONSTRAINT [DF_ED810LineItem_MilSpec] DEFAULT (' ') NOT NULL,
    [NDC]            CHAR (48)     CONSTRAINT [DF_ED810LineItem_NDC] DEFAULT (' ') NOT NULL,
    [NoteID]         INT           CONSTRAINT [DF_ED810LineItem_NoteID] DEFAULT ((0)) NOT NULL,
    [Pack]           SMALLINT      CONSTRAINT [DF_ED810LineItem_Pack] DEFAULT ((0)) NOT NULL,
    [PackSize]       SMALLINT      CONSTRAINT [DF_ED810LineItem_PackSize] DEFAULT ((0)) NOT NULL,
    [PackUOM]        CHAR (6)      CONSTRAINT [DF_ED810LineItem_PackUOM] DEFAULT (' ') NOT NULL,
    [POLineRef]      CHAR (5)      CONSTRAINT [DF_ED810LineItem_POLineRef] DEFAULT (' ') NOT NULL,
    [Price]          FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Price] DEFAULT ((0)) NOT NULL,
    [PriceExt]       FLOAT (53)    CONSTRAINT [DF_ED810LineItem_PriceExt] DEFAULT ((0)) NOT NULL,
    [PrintNbr]       CHAR (48)     CONSTRAINT [DF_ED810LineItem_PrintNbr] DEFAULT (' ') NOT NULL,
    [ProjectID]      CHAR (16)     CONSTRAINT [DF_ED810LineItem_ProjectID] DEFAULT (' ') NOT NULL,
    [QtyInvoiced]    FLOAT (53)    CONSTRAINT [DF_ED810LineItem_QtyInvoiced] DEFAULT ((0)) NOT NULL,
    [QtyInvoicedUOM] CHAR (6)      CONSTRAINT [DF_ED810LineItem_QtyInvoicedUOM] DEFAULT (' ') NOT NULL,
    [QtyOrdered]     FLOAT (53)    CONSTRAINT [DF_ED810LineItem_QtyOrdered] DEFAULT ((0)) NOT NULL,
    [QtyOrderedUOM]  CHAR (6)      CONSTRAINT [DF_ED810LineItem_QtyOrderedUOM] DEFAULT (' ') NOT NULL,
    [S4Future01]     CHAR (30)     CONSTRAINT [DF_ED810LineItem_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]     CHAR (30)     CONSTRAINT [DF_ED810LineItem_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]     FLOAT (53)    CONSTRAINT [DF_ED810LineItem_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]     FLOAT (53)    CONSTRAINT [DF_ED810LineItem_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]     FLOAT (53)    CONSTRAINT [DF_ED810LineItem_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]     FLOAT (53)    CONSTRAINT [DF_ED810LineItem_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]     SMALLDATETIME CONSTRAINT [DF_ED810LineItem_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]     SMALLDATETIME CONSTRAINT [DF_ED810LineItem_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]     INT           CONSTRAINT [DF_ED810LineItem_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]     INT           CONSTRAINT [DF_ED810LineItem_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]     CHAR (10)     CONSTRAINT [DF_ED810LineItem_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]     CHAR (10)     CONSTRAINT [DF_ED810LineItem_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipToSite]     CHAR (10)     CONSTRAINT [DF_ED810LineItem_ShipToSite] DEFAULT (' ') NOT NULL,
    [SKU]            CHAR (48)     CONSTRAINT [DF_ED810LineItem_SKU] DEFAULT (' ') NOT NULL,
    [Style]          CHAR (20)     CONSTRAINT [DF_ED810LineItem_Style] DEFAULT (' ') NOT NULL,
    [TaskID]         CHAR (32)     CONSTRAINT [DF_ED810LineItem_TaskID] DEFAULT (' ') NOT NULL,
    [UCC]            CHAR (48)     CONSTRAINT [DF_ED810LineItem_UCC] DEFAULT (' ') NOT NULL,
    [UnitPriceBasis] CHAR (5)      CONSTRAINT [DF_ED810LineItem_UnitPriceBasis] DEFAULT (' ') NOT NULL,
    [UPC]            CHAR (48)     CONSTRAINT [DF_ED810LineItem_UPC] DEFAULT (' ') NOT NULL,
    [User1]          CHAR (30)     CONSTRAINT [DF_ED810LineItem_User1] DEFAULT (' ') NOT NULL,
    [User10]         SMALLDATETIME CONSTRAINT [DF_ED810LineItem_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]          CHAR (30)     CONSTRAINT [DF_ED810LineItem_User2] DEFAULT (' ') NOT NULL,
    [User3]          CHAR (30)     CONSTRAINT [DF_ED810LineItem_User3] DEFAULT (' ') NOT NULL,
    [User4]          CHAR (30)     CONSTRAINT [DF_ED810LineItem_User4] DEFAULT (' ') NOT NULL,
    [User5]          FLOAT (53)    CONSTRAINT [DF_ED810LineItem_User5] DEFAULT ((0)) NOT NULL,
    [User6]          FLOAT (53)    CONSTRAINT [DF_ED810LineItem_User6] DEFAULT ((0)) NOT NULL,
    [User7]          CHAR (10)     CONSTRAINT [DF_ED810LineItem_User7] DEFAULT (' ') NOT NULL,
    [User8]          CHAR (10)     CONSTRAINT [DF_ED810LineItem_User8] DEFAULT (' ') NOT NULL,
    [User9]          SMALLDATETIME CONSTRAINT [DF_ED810LineItem_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendorLineRef]  CHAR (20)     CONSTRAINT [DF_ED810LineItem_VendorLineRef] DEFAULT (' ') NOT NULL,
    [VendorPartNbr]  CHAR (48)     CONSTRAINT [DF_ED810LineItem_VendorPartNbr] DEFAULT (' ') NOT NULL,
    [Volume]         FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Volume] DEFAULT ((0)) NOT NULL,
    [VolumeUOM]      CHAR (6)      CONSTRAINT [DF_ED810LineItem_VolumeUOM] DEFAULT (' ') NOT NULL,
    [Weight]         FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]      CHAR (6)      CONSTRAINT [DF_ED810LineItem_WeightUOM] DEFAULT (' ') NOT NULL,
    [WhseLoc]        CHAR (10)     CONSTRAINT [DF_ED810LineItem_WhseLoc] DEFAULT (' ') NOT NULL,
    [Width]          FLOAT (53)    CONSTRAINT [DF_ED810LineItem_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]       CHAR (6)      CONSTRAINT [DF_ED810LineItem_WidthUOM] DEFAULT (' ') NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [ED810LineItem0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [EDIInvID] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

