CREATE TABLE [dbo].[EDSTCustomer] (
    [AddressType]        CHAR (1)      CONSTRAINT [DF_EDSTCustomer_AddressType] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_EDSTCustomer_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_EDSTCustomer_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]             CHAR (15)     CONSTRAINT [DF_EDSTCustomer_CustID] DEFAULT (' ') NOT NULL,
    [DistCenterShipToID] CHAR (10)     CONSTRAINT [DF_EDSTCustomer_DistCenterShipToID] DEFAULT (' ') NOT NULL,
    [EdiDistCenterRef]   CHAR (20)     CONSTRAINT [DF_EDSTCustomer_EdiDistCenterRef] DEFAULT (' ') NOT NULL,
    [EdiShipToRef]       CHAR (17)     CONSTRAINT [DF_EDSTCustomer_EdiShipToRef] DEFAULT (' ') NOT NULL,
    [FSFlag]             INT           CONSTRAINT [DF_EDSTCustomer_FSFlag] DEFAULT ((0)) NOT NULL,
    [Lupd_DateTime]      SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]          CHAR (8)      CONSTRAINT [DF_EDSTCustomer_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]          CHAR (10)     CONSTRAINT [DF_EDSTCustomer_Lupd_User] DEFAULT (' ') NOT NULL,
    [MaxBillZone]        CHAR (5)      CONSTRAINT [DF_EDSTCustomer_MaxBillZone] DEFAULT (' ') NOT NULL,
    [RegionID]           CHAR (10)     CONSTRAINT [DF_EDSTCustomer_RegionID] DEFAULT (' ') NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_EDSTCustomer_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_EDSTCustomer_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_EDSTCustomer_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_EDSTCustomer_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_EDSTCustomer_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_EDSTCustomer_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipToID]           CHAR (10)     CONSTRAINT [DF_EDSTCustomer_ShipToID] DEFAULT (' ') NOT NULL,
    [TerritoryID]        CHAR (10)     CONSTRAINT [DF_EDSTCustomer_TerritoryID] DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_EDSTCustomer_User1] DEFAULT (' ') NOT NULL,
    [User10]             SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_EDSTCustomer_User2] DEFAULT (' ') NOT NULL,
    [User3]              CHAR (30)     CONSTRAINT [DF_EDSTCustomer_User3] DEFAULT (' ') NOT NULL,
    [User4]              CHAR (30)     CONSTRAINT [DF_EDSTCustomer_User4] DEFAULT (' ') NOT NULL,
    [User5]              FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_User5] DEFAULT ((0)) NOT NULL,
    [User6]              FLOAT (53)    CONSTRAINT [DF_EDSTCustomer_User6] DEFAULT ((0)) NOT NULL,
    [User7]              CHAR (10)     CONSTRAINT [DF_EDSTCustomer_User7] DEFAULT (' ') NOT NULL,
    [User8]              CHAR (10)     CONSTRAINT [DF_EDSTCustomer_User8] DEFAULT (' ') NOT NULL,
    [User9]              SMALLDATETIME CONSTRAINT [DF_EDSTCustomer_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [EDSTCustomer0] PRIMARY KEY CLUSTERED ([CustID] ASC, [ShipToID] ASC) WITH (FILLFACTOR = 90)
);

