CREATE TABLE [dbo].[PJUTTYPE] (
    [available]        CHAR (1)      NOT NULL,
    [column_nbr]       SMALLINT      NOT NULL,
    [crtd_datetime]    SMALLDATETIME NOT NULL,
    [crtd_prog]        CHAR (8)      NOT NULL,
    [crtd_user]        CHAR (10)     NOT NULL,
    [direct]           CHAR (1)      NOT NULL,
    [lupd_datetime]    SMALLDATETIME NOT NULL,
    [lupd_prog]        CHAR (8)      NOT NULL,
    [lupd_user]        CHAR (10)     NOT NULL,
    [NoteId]           INT           NOT NULL,
    [user1]            CHAR (30)     NOT NULL,
    [user2]            CHAR (30)     NOT NULL,
    [user3]            FLOAT (53)    NOT NULL,
    [user4]            FLOAT (53)    NOT NULL,
    [ut_id01]          CHAR (30)     NOT NULL,
    [ut_id02]          CHAR (30)     NOT NULL,
    [ut_id03]          CHAR (20)     NOT NULL,
    [ut_id04]          CHAR (20)     NOT NULL,
    [ut_id05]          CHAR (10)     NOT NULL,
    [ut_id06]          CHAR (10)     NOT NULL,
    [ut_id07]          CHAR (4)      NOT NULL,
    [ut_id08]          FLOAT (53)    NOT NULL,
    [ut_id09]          SMALLDATETIME NOT NULL,
    [ut_id10]          INT           NOT NULL,
    [utilization_desc] CHAR (30)     NOT NULL,
    [utilization_type] CHAR (4)      NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [pjuttype0] PRIMARY KEY CLUSTERED ([utilization_type] ASC) WITH (FILLFACTOR = 90)
);

