CREATE TABLE [dbo].[smConEquipment] (
    [AmtBilled]     FLOAT (53)    NOT NULL,
    [AmtBooked]     FLOAT (53)    NOT NULL,
    [AmtContract]   FLOAT (53)    NOT NULL,
    [AmtRevenue]    FLOAT (53)    NOT NULL,
    [AssetNbr]      CHAR (15)     NOT NULL,
    [BasePrice]     FLOAT (53)    NOT NULL,
    [Booked]        SMALLINT      NOT NULL,
    [BookReversed]  SMALLINT      NOT NULL,
    [CE_ID01]       CHAR (30)     NOT NULL,
    [CE_ID02]       CHAR (30)     NOT NULL,
    [CE_ID03]       CHAR (20)     NOT NULL,
    [CE_ID04]       CHAR (20)     NOT NULL,
    [CE_ID05]       CHAR (10)     NOT NULL,
    [CE_ID06]       CHAR (10)     NOT NULL,
    [CE_ID07]       CHAR (4)      NOT NULL,
    [CE_ID08]       FLOAT (53)    NOT NULL,
    [CE_ID09]       SMALLDATETIME NOT NULL,
    [CE_ID10]       SMALLINT      NOT NULL,
    [CE_ID11]       CHAR (30)     NOT NULL,
    [CE_ID12]       CHAR (30)     NOT NULL,
    [CE_ID13]       CHAR (20)     NOT NULL,
    [CE_ID14]       CHAR (20)     NOT NULL,
    [CE_ID15]       CHAR (10)     NOT NULL,
    [CE_ID16]       CHAR (10)     NOT NULL,
    [CE_ID17]       CHAR (4)      NOT NULL,
    [CE_ID18]       FLOAT (53)    NOT NULL,
    [CE_ID19]       SMALLDATETIME NOT NULL,
    [CE_ID20]       SMALLINT      NOT NULL,
    [ContractId]    CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [EndDate]       SMALLDATETIME NOT NULL,
    [EndWarranty]   SMALLDATETIME NOT NULL,
    [EquipID]       CHAR (10)     NOT NULL,
    [EquipTypeID]   CHAR (10)     NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [PmCode]        CHAR (10)     NOT NULL,
    [PMFlag]        CHAR (1)      NOT NULL,
    [PrimaryKey]    CHAR (30)     NOT NULL,
    [Qty]           FLOAT (53)    NOT NULL,
    [Retired]       SMALLINT      NOT NULL,
    [RetireDate]    SMALLDATETIME NOT NULL,
    [RevAccount]    CHAR (10)     NOT NULL,
    [RevSub]        CHAR (24)     NOT NULL,
    [ScreenID]      CHAR (7)      NOT NULL,
    [SerialNbr]     CHAR (30)     NOT NULL,
    [SSNOteID]      INT           NOT NULL,
    [StartDate]     SMALLDATETIME NOT NULL,
    [StartWarranty] SMALLDATETIME NOT NULL,
    [Status]        CHAR (2)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [User9]         SMALLINT      NOT NULL,
    [Void]          SMALLINT      NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smConEquipment0] PRIMARY KEY CLUSTERED ([ContractId] ASC, [EquipID] ASC, [PmCode] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [smConEquipment1]
    ON [dbo].[smConEquipment]([ContractId] ASC, [EquipID] ASC) WITH (FILLFACTOR = 90);

