CREATE TABLE [dbo].[PJPTDROL] (
    [acct]                 CHAR (16)     NOT NULL,
    [act_amount]           FLOAT (53)    NOT NULL,
    [act_units]            FLOAT (53)    NOT NULL,
    [com_amount]           FLOAT (53)    NOT NULL,
    [com_units]            FLOAT (53)    NOT NULL,
    [crtd_datetime]        SMALLDATETIME NOT NULL,
    [crtd_prog]            CHAR (8)      NOT NULL,
    [crtd_user]            CHAR (10)     NOT NULL,
    [data1]                CHAR (16)     NOT NULL,
    [data2]                FLOAT (53)    NOT NULL,
    [data3]                FLOAT (53)    NOT NULL,
    [data4]                FLOAT (53)    NOT NULL,
    [data5]                FLOAT (53)    NOT NULL,
    [eac_amount]           FLOAT (53)    NOT NULL,
    [eac_units]            FLOAT (53)    NOT NULL,
    [fac_amount]           FLOAT (53)    NOT NULL,
    [fac_units]            FLOAT (53)    NOT NULL,
    [lupd_datetime]        SMALLDATETIME NOT NULL,
    [lupd_prog]            CHAR (8)      NOT NULL,
    [lupd_user]            CHAR (10)     NOT NULL,
    [ProjCury_act_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_com_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_eac_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_fac_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_rate]        FLOAT (53)    NOT NULL,
    [ProjCury_tot_bud_amt] FLOAT (53)    NOT NULL,
    [project]              CHAR (16)     NOT NULL,
    [rate]                 FLOAT (53)    NOT NULL,
    [total_budget_amount]  FLOAT (53)    NOT NULL,
    [total_budget_units]   FLOAT (53)    NOT NULL,
    [user1]                CHAR (30)     NOT NULL,
    [user2]                CHAR (30)     NOT NULL,
    [user3]                FLOAT (53)    NOT NULL,
    [user4]                FLOAT (53)    NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [pjptdrol0] PRIMARY KEY CLUSTERED ([project] ASC, [acct] ASC) WITH (FILLFACTOR = 100)
);

