CREATE TABLE [dbo].[DDDepositor] (
    [AcctType00]    CHAR (1)      NOT NULL,
    [AcctType01]    CHAR (1)      NOT NULL,
    [AcctType02]    CHAR (1)      NOT NULL,
    [AcctType03]    CHAR (1)      NOT NULL,
    [AcctType04]    CHAR (1)      NOT NULL,
    [AcctType05]    CHAR (1)      NOT NULL,
    [Amount00]      FLOAT (53)    NOT NULL,
    [Amount01]      FLOAT (53)    NOT NULL,
    [Amount02]      FLOAT (53)    NOT NULL,
    [Amount03]      FLOAT (53)    NOT NULL,
    [Amount04]      FLOAT (53)    NOT NULL,
    [BankAcct00]    CHAR (17)     NOT NULL,
    [BankAcct01]    CHAR (17)     NOT NULL,
    [BankAcct02]    CHAR (17)     NOT NULL,
    [BankAcct03]    CHAR (17)     NOT NULL,
    [BankAcct04]    CHAR (17)     NOT NULL,
    [BankAcct05]    CHAR (17)     NOT NULL,
    [BankID]        CHAR (6)      NOT NULL,
    [BankTransit00] CHAR (9)      NOT NULL,
    [BankTransit01] CHAR (9)      NOT NULL,
    [BankTransit02] CHAR (9)      NOT NULL,
    [BankTransit03] CHAR (9)      NOT NULL,
    [BankTransit04] CHAR (9)      NOT NULL,
    [BankTransit05] CHAR (9)      NOT NULL,
    [CpnyID]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DistType]      CHAR (1)      NOT NULL,
    [EmpID]         CHAR (10)     NOT NULL,
    [LowPay]        CHAR (1)      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [PNStatus00]    CHAR (1)      NOT NULL,
    [PNStatus01]    CHAR (1)      NOT NULL,
    [PNStatus02]    CHAR (1)      NOT NULL,
    [PNStatus03]    CHAR (1)      NOT NULL,
    [PNStatus04]    CHAR (1)      NOT NULL,
    [PNStatus05]    CHAR (1)      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [DDDepositor0] PRIMARY KEY CLUSTERED ([EmpID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [DDDepositor1]
    ON [dbo].[DDDepositor]([BankID] ASC, [EmpID] ASC) WITH (FILLFACTOR = 90);

