CREATE TABLE [dbo].[PJLABAUD] (
    [CpnyId_chrg]    CHAR (10)     NOT NULL,
    [CpnyId_home]    CHAR (10)     NOT NULL,
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [day1_hr1]       FLOAT (53)    NOT NULL,
    [day1_hr2]       FLOAT (53)    NOT NULL,
    [day1_hr3]       FLOAT (53)    NOT NULL,
    [day2_hr1]       FLOAT (53)    NOT NULL,
    [day2_hr2]       FLOAT (53)    NOT NULL,
    [day2_hr3]       FLOAT (53)    NOT NULL,
    [day3_hr1]       FLOAT (53)    NOT NULL,
    [day3_hr2]       FLOAT (53)    NOT NULL,
    [day3_hr3]       FLOAT (53)    NOT NULL,
    [day4_hr1]       FLOAT (53)    NOT NULL,
    [day4_hr2]       FLOAT (53)    NOT NULL,
    [day4_hr3]       FLOAT (53)    NOT NULL,
    [day5_hr1]       FLOAT (53)    NOT NULL,
    [day5_hr2]       FLOAT (53)    NOT NULL,
    [day5_hr3]       FLOAT (53)    NOT NULL,
    [day6_hr1]       FLOAT (53)    NOT NULL,
    [day6_hr2]       FLOAT (53)    NOT NULL,
    [day6_hr3]       FLOAT (53)    NOT NULL,
    [day7_hr1]       FLOAT (53)    NOT NULL,
    [day7_hr2]       FLOAT (53)    NOT NULL,
    [day7_hr3]       FLOAT (53)    NOT NULL,
    [docnbr]         CHAR (10)     NOT NULL,
    [earn_type_id]   CHAR (10)     NOT NULL,
    [gl_acct]        CHAR (10)     NOT NULL,
    [gl_subacct]     CHAR (24)     NOT NULL,
    [labor_class_cd] CHAR (4)      NOT NULL,
    [labor_stdcost]  FLOAT (53)    NOT NULL,
    [ld_desc]        CHAR (30)     NOT NULL,
    [ld_id01]        CHAR (30)     NOT NULL,
    [ld_id02]        CHAR (30)     NOT NULL,
    [ld_id03]        CHAR (16)     NOT NULL,
    [ld_id04]        CHAR (16)     NOT NULL,
    [ld_id05]        CHAR (4)      NOT NULL,
    [ld_id06]        FLOAT (53)    NOT NULL,
    [ld_id07]        FLOAT (53)    NOT NULL,
    [ld_id08]        SMALLDATETIME NOT NULL,
    [ld_id09]        SMALLDATETIME NOT NULL,
    [ld_id10]        INT           NOT NULL,
    [ld_id11]        CHAR (30)     NOT NULL,
    [ld_id12]        CHAR (30)     NOT NULL,
    [ld_id13]        CHAR (20)     NOT NULL,
    [ld_id14]        CHAR (20)     NOT NULL,
    [ld_id15]        CHAR (10)     NOT NULL,
    [ld_id16]        CHAR (10)     NOT NULL,
    [ld_id17]        CHAR (4)      NOT NULL,
    [ld_id18]        FLOAT (53)    NOT NULL,
    [ld_id19]        FLOAT (53)    NOT NULL,
    [ld_id20]        SMALLDATETIME NOT NULL,
    [ld_status]      CHAR (1)      NOT NULL,
    [linenbr]        SMALLINT      NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [pjt_entity]     CHAR (32)     NOT NULL,
    [project]        CHAR (16)     NOT NULL,
    [rate_source]    CHAR (1)      NOT NULL,
    [shift]          CHAR (7)      NOT NULL,
    [SubTask_Name]   CHAR (50)     NOT NULL,
    [SubTask_UID]    INT           NOT NULL,
    [total_amount]   FLOAT (53)    NOT NULL,
    [total_hrs]      FLOAT (53)    NOT NULL,
    [union_cd]       CHAR (10)     NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [work_comp_cd]   CHAR (6)      NOT NULL,
    [work_type]      CHAR (2)      NOT NULL,
    [zaudit_seq]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [zaudit_type]    CHAR (2)      NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjlabaud0] PRIMARY KEY CLUSTERED ([docnbr] ASC, [linenbr] ASC, [zaudit_seq] ASC) WITH (FILLFACTOR = 90)
);

