CREATE TABLE [dbo].[WOHeader] (
    [BackFlush]          CHAR (1)      CONSTRAINT [DF_WOHeader_BackFlush] DEFAULT (' ') NOT NULL,
    [BackflushLabor]     CHAR (1)      CONSTRAINT [DF_WOHeader_BackflushLabor] DEFAULT (' ') NOT NULL,
    [BackflushMaterial]  CHAR (1)      CONSTRAINT [DF_WOHeader_BackflushMaterial] DEFAULT (' ') NOT NULL,
    [BOMStatus]          CHAR (1)      CONSTRAINT [DF_WOHeader_BOMStatus] DEFAULT (' ') NOT NULL,
    [BTLineCntr]         SMALLINT      CONSTRAINT [DF_WOHeader_BTLineCntr] DEFAULT ((0)) NOT NULL,
    [BuildToProj]        CHAR (16)     CONSTRAINT [DF_WOHeader_BuildToProj] DEFAULT (' ') NOT NULL,
    [BuildToTask]        CHAR (32)     CONSTRAINT [DF_WOHeader_BuildToTask] DEFAULT (' ') NOT NULL,
    [BuildToType]        CHAR (3)      CONSTRAINT [DF_WOHeader_BuildToType] DEFAULT (' ') NOT NULL,
    [BuildToWO]          CHAR (16)     CONSTRAINT [DF_WOHeader_BuildToWO] DEFAULT (' ') NOT NULL,
    [CompCostMethod]     CHAR (1)      CONSTRAINT [DF_WOHeader_CompCostMethod] DEFAULT (' ') NOT NULL,
    [CompDfltSite]       CHAR (1)      CONSTRAINT [DF_WOHeader_CompDfltSite] DEFAULT (' ') NOT NULL,
    [CpnyID]             CHAR (10)     CONSTRAINT [DF_WOHeader_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME CONSTRAINT [DF_WOHeader_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_WOHeader_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_Time]          SMALLDATETIME CONSTRAINT [DF_WOHeader_Crtd_Time] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_WOHeader_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]             CHAR (15)     CONSTRAINT [DF_WOHeader_CustID] DEFAULT (' ') NOT NULL,
    [DBProcessStatus]    SMALLINT      CONSTRAINT [DF_WOHeader_DBProcessStatus] DEFAULT ((0)) NOT NULL,
    [InvtID]             CHAR (30)     CONSTRAINT [DF_WOHeader_InvtID] DEFAULT (' ') NOT NULL,
    [Labor_Acct]         CHAR (16)     CONSTRAINT [DF_WOHeader_Labor_Acct] DEFAULT (' ') NOT NULL,
    [LaborBdgUpdate]     CHAR (1)      CONSTRAINT [DF_WOHeader_LaborBdgUpdate] DEFAULT (' ') NOT NULL,
    [LastRoutingStepNbr] SMALLINT      CONSTRAINT [DF_WOHeader_LastRoutingStepNbr] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME CONSTRAINT [DF_WOHeader_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      CONSTRAINT [DF_WOHeader_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUPd_Time]          SMALLDATETIME CONSTRAINT [DF_WOHeader_LUPd_Time] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]          CHAR (10)     CONSTRAINT [DF_WOHeader_LUpd_User] DEFAULT (' ') NOT NULL,
    [Material_Acct]      CHAR (16)     CONSTRAINT [DF_WOHeader_Material_Acct] DEFAULT (' ') NOT NULL,
    [MaterialBdgUpdate]  CHAR (1)      CONSTRAINT [DF_WOHeader_MaterialBdgUpdate] DEFAULT (' ') NOT NULL,
    [MRLineCntr]         SMALLINT      CONSTRAINT [DF_WOHeader_MRLineCntr] DEFAULT ((0)) NOT NULL,
    [NoteID]             INT           CONSTRAINT [DF_WOHeader_NoteID] DEFAULT ((0)) NOT NULL,
    [OrdNbr]             CHAR (15)     CONSTRAINT [DF_WOHeader_OrdNbr] DEFAULT (' ') NOT NULL,
    [PlanEnd]            SMALLDATETIME CONSTRAINT [DF_WOHeader_PlanEnd] DEFAULT ('01/01/1900') NOT NULL,
    [PlanStart]          SMALLDATETIME CONSTRAINT [DF_WOHeader_PlanStart] DEFAULT ('01/01/1900') NOT NULL,
    [Priority]           SMALLINT      CONSTRAINT [DF_WOHeader_Priority] DEFAULT ((0)) NOT NULL,
    [PrjWoGLIM]          CHAR (1)      CONSTRAINT [DF_WOHeader_PrjWoGLIM] DEFAULT (' ') NOT NULL,
    [ProcStage]          CHAR (1)      CONSTRAINT [DF_WOHeader_ProcStage] DEFAULT (' ') NOT NULL,
    [QtyComplete]        FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyComplete] DEFAULT ((0)) NOT NULL,
    [QtyCurrent]         FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyCurrent] DEFAULT ((0)) NOT NULL,
    [QtyGridPopToDate]   FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyGridPopToDate] DEFAULT ((0)) NOT NULL,
    [QtyOrig]            FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyOrig] DEFAULT ((0)) NOT NULL,
    [QtyQCHold]          FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyQCHold] DEFAULT ((0)) NOT NULL,
    [QtyRemaining]       FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyRemaining] DEFAULT ((0)) NOT NULL,
    [QtyRework]          FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyRework] DEFAULT ((0)) NOT NULL,
    [QtyReworkComp]      FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyReworkComp] DEFAULT ((0)) NOT NULL,
    [QtyScrap]           FLOAT (53)    CONSTRAINT [DF_WOHeader_QtyScrap] DEFAULT ((0)) NOT NULL,
    [RLineCntr]          SMALLINT      CONSTRAINT [DF_WOHeader_RLineCntr] DEFAULT ((0)) NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_WOHeader_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_WOHeader_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_WOHeader_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_WOHeader_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_WOHeader_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_WOHeader_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_WOHeader_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_WOHeader_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_WOHeader_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_WOHeader_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_WOHeader_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_WOHeader_S4Future12] DEFAULT (' ') NOT NULL,
    [ScheduleMaterials]  CHAR (1)      CONSTRAINT [DF_WOHeader_ScheduleMaterials] DEFAULT (' ') NOT NULL,
    [ScheduleOption]     CHAR (1)      CONSTRAINT [DF_WOHeader_ScheduleOption] DEFAULT (' ') NOT NULL,
    [SiteID]             CHAR (10)     CONSTRAINT [DF_WOHeader_SiteID] DEFAULT (' ') NOT NULL,
    [Status]             CHAR (1)      CONSTRAINT [DF_WOHeader_Status] DEFAULT (' ') NOT NULL,
    [StdCostLast]        FLOAT (53)    CONSTRAINT [DF_WOHeader_StdCostLast] DEFAULT ((0)) NOT NULL,
    [StdCostOrig]        FLOAT (53)    CONSTRAINT [DF_WOHeader_StdCostOrig] DEFAULT ((0)) NOT NULL,
    [StdCostWO]          FLOAT (53)    CONSTRAINT [DF_WOHeader_StdCostWO] DEFAULT ((0)) NOT NULL,
    [StdLotSize]         FLOAT (53)    CONSTRAINT [DF_WOHeader_StdLotSize] DEFAULT ((0)) NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_WOHeader_User1] DEFAULT (' ') NOT NULL,
    [User10]             CHAR (30)     CONSTRAINT [DF_WOHeader_User10] DEFAULT (' ') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_WOHeader_User2] DEFAULT (' ') NOT NULL,
    [User3]              FLOAT (53)    CONSTRAINT [DF_WOHeader_User3] DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    CONSTRAINT [DF_WOHeader_User4] DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     CONSTRAINT [DF_WOHeader_User5] DEFAULT (' ') NOT NULL,
    [User6]              CHAR (10)     CONSTRAINT [DF_WOHeader_User6] DEFAULT (' ') NOT NULL,
    [User7]              SMALLDATETIME CONSTRAINT [DF_WOHeader_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME CONSTRAINT [DF_WOHeader_User8] DEFAULT ('01/01/1900') NOT NULL,
    [User9]              CHAR (30)     CONSTRAINT [DF_WOHeader_User9] DEFAULT (' ') NOT NULL,
    [WhseLoc]            CHAR (10)     CONSTRAINT [DF_WOHeader_WhseLoc] DEFAULT (' ') NOT NULL,
    [WIPIntegrity]       SMALLINT      CONSTRAINT [DF_WOHeader_WIPIntegrity] DEFAULT ((0)) NOT NULL,
    [WODescr]            CHAR (60)     CONSTRAINT [DF_WOHeader_WODescr] DEFAULT (' ') NOT NULL,
    [WONbr]              CHAR (16)     CONSTRAINT [DF_WOHeader_WONbr] DEFAULT (' ') NOT NULL,
    [WOType]             CHAR (1)      CONSTRAINT [DF_WOHeader_WOType] DEFAULT (' ') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [WOHeader0] PRIMARY KEY CLUSTERED ([WONbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [WOHeader1]
    ON [dbo].[WOHeader]([InvtID] ASC, [WONbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [WOHeader2]
    ON [dbo].[WOHeader]([WONbr] ASC, [ProcStage] ASC) WITH (FILLFACTOR = 90);

