CREATE TABLE [dbo].[EDSetup] (
    [Crtd_DateTime]      SMALLDATETIME CONSTRAINT [DF_EDSetup_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_EDSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_EDSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [DecPlPct]           SMALLINT      CONSTRAINT [DF_EDSetup_DecPlPct] DEFAULT ((0)) NOT NULL,
    [DecPlPrcCst]        SMALLINT      CONSTRAINT [DF_EDSetup_DecPlPrcCst] DEFAULT ((0)) NOT NULL,
    [DecPlqty]           SMALLINT      CONSTRAINT [DF_EDSetup_DecPlqty] DEFAULT ((0)) NOT NULL,
    [DeleteDta]          SMALLINT      CONSTRAINT [DF_EDSetup_DeleteDta] DEFAULT ((0)) NOT NULL,
    [EmailAddr]          CHAR (255)    CONSTRAINT [DF_EDSetup_EmailAddr] DEFAULT (' ') NOT NULL,
    [EmailRptLevel]      SMALLINT      CONSTRAINT [DF_EDSetup_EmailRptLevel] DEFAULT ((0)) NOT NULL,
    [EngineIn]           CHAR (255)    CONSTRAINT [DF_EDSetup_EngineIn] DEFAULT (' ') NOT NULL,
    [EngineOut]          CHAR (255)    CONSTRAINT [DF_EDSetup_EngineOut] DEFAULT (' ') NOT NULL,
    [InDataDir]          CHAR (255)    CONSTRAINT [DF_EDSetup_InDataDir] DEFAULT (' ') NOT NULL,
    [InTranslatorVerify] SMALLINT      CONSTRAINT [DF_EDSetup_InTranslatorVerify] DEFAULT ((0)) NOT NULL,
    [InvcCustomObj]      CHAR (255)    CONSTRAINT [DF_EDSetup_InvcCustomObj] DEFAULT (' ') NOT NULL,
    [InvcRecheck]        SMALLINT      CONSTRAINT [DF_EDSetup_InvcRecheck] DEFAULT ((0)) NOT NULL,
    [InvcRunUserEXE]     SMALLINT      CONSTRAINT [DF_EDSetup_InvcRunUserEXE] DEFAULT ((0)) NOT NULL,
    [InvcTranControl]    CHAR (255)    CONSTRAINT [DF_EDSetup_InvcTranControl] DEFAULT (' ') NOT NULL,
    [InvcUserEXE]        CHAR (255)    CONSTRAINT [DF_EDSetup_InvcUserEXE] DEFAULT (' ') NOT NULL,
    [InvcUseTI]          SMALLINT      CONSTRAINT [DF_EDSetup_InvcUseTI] DEFAULT ((0)) NOT NULL,
    [LastEDIInvID]       CHAR (10)     CONSTRAINT [DF_EDSetup_LastEDIInvID] DEFAULT (' ') NOT NULL,
    [LastEDIPOID]        CHAR (10)     CONSTRAINT [DF_EDSetup_LastEDIPOID] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]      SMALLDATETIME CONSTRAINT [DF_EDSetup_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]          CHAR (8)      CONSTRAINT [DF_EDSetup_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]          CHAR (10)     CONSTRAINT [DF_EDSetup_Lupd_User] DEFAULT (' ') NOT NULL,
    [ObjectConnectStr]   CHAR (255)    CONSTRAINT [DF_EDSetup_ObjectConnectStr] DEFAULT (' ') NOT NULL,
    [OutDataDir]         CHAR (255)    CONSTRAINT [DF_EDSetup_OutDataDir] DEFAULT (' ') NOT NULL,
    [PerNbr]             CHAR (6)      CONSTRAINT [DF_EDSetup_PerNbr] DEFAULT (' ') NOT NULL,
    [POCustomObj]        CHAR (255)    CONSTRAINT [DF_EDSetup_POCustomObj] DEFAULT (' ') NOT NULL,
    [PORecheck]          SMALLINT      CONSTRAINT [DF_EDSetup_PORecheck] DEFAULT ((0)) NOT NULL,
    [PORunUserEXE]       SMALLINT      CONSTRAINT [DF_EDSetup_PORunUserEXE] DEFAULT ((0)) NOT NULL,
    [POTranControl]      CHAR (255)    CONSTRAINT [DF_EDSetup_POTranControl] DEFAULT (' ') NOT NULL,
    [POUserEXE]          CHAR (255)    CONSTRAINT [DF_EDSetup_POUserEXE] DEFAULT (' ') NOT NULL,
    [POUseTI]            SMALLINT      CONSTRAINT [DF_EDSetup_POUseTI] DEFAULT ((0)) NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_EDSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_EDSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_EDSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_EDSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_EDSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_EDSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_EDSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_EDSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_EDSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_EDSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_EDSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_EDSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [SendEmail]          SMALLINT      CONSTRAINT [DF_EDSetup_SendEmail] DEFAULT ((0)) NOT NULL,
    [SetupID]            CHAR (2)      CONSTRAINT [DF_EDSetup_SetupID] DEFAULT (' ') NOT NULL,
    [TranLog]            CHAR (255)    CONSTRAINT [DF_EDSetup_TranLog] DEFAULT (' ') NOT NULL,
    [TranOutput]         CHAR (255)    CONSTRAINT [DF_EDSetup_TranOutput] DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_EDSetup_User1] DEFAULT (' ') NOT NULL,
    [User10]             SMALLDATETIME CONSTRAINT [DF_EDSetup_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_EDSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]              CHAR (30)     CONSTRAINT [DF_EDSetup_User3] DEFAULT (' ') NOT NULL,
    [User4]              CHAR (30)     CONSTRAINT [DF_EDSetup_User4] DEFAULT (' ') NOT NULL,
    [User5]              FLOAT (53)    CONSTRAINT [DF_EDSetup_User5] DEFAULT ((0)) NOT NULL,
    [User6]              FLOAT (53)    CONSTRAINT [DF_EDSetup_User6] DEFAULT ((0)) NOT NULL,
    [User7]              CHAR (10)     CONSTRAINT [DF_EDSetup_User7] DEFAULT (' ') NOT NULL,
    [User8]              CHAR (10)     CONSTRAINT [DF_EDSetup_User8] DEFAULT (' ') NOT NULL,
    [User9]              SMALLDATETIME CONSTRAINT [DF_EDSetup_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [EDSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

