CREATE TABLE [dbo].[IFGRower] (
    [CODE]    NVARCHAR (255) NULL,
    [NAME]    NVARCHAR (255) NULL,
    [TYPE]    NVARCHAR (255) NULL,
    [DISEASE] NVARCHAR (255) NULL,
    [INFO1]   NVARCHAR (255) NULL,
    [INFO2]   NVARCHAR (255) NULL,
    [INFO3]   NVARCHAR (255) NULL,
    [INFO4]   NVARCHAR (255) NULL
);

