CREATE TABLE [dbo].[PJPAYHDR] (
    [approver]           CHAR (10)     NOT NULL,
    [BaseCuryId]         CHAR (4)      NOT NULL,
    [batnbr]             CHAR (10)     NOT NULL,
    [bill_inv_num]       CHAR (10)     NOT NULL,
    [crtd_datetime]      SMALLDATETIME NOT NULL,
    [crtd_prog]          CHAR (8)      NOT NULL,
    [crtd_user]          CHAR (10)     NOT NULL,
    [curr_net_amt]       FLOAT (53)    NOT NULL,
    [curr_ret_amt]       FLOAT (53)    NOT NULL,
    [curr_total_amt]     FLOAT (53)    NOT NULL,
    [curr_units]         FLOAT (53)    NOT NULL,
    [Curycurr_net_amt]   FLOAT (53)    NOT NULL,
    [Curycurr_ret_amt]   FLOAT (53)    NOT NULL,
    [Curycurr_total_amt] FLOAT (53)    NOT NULL,
    [CuryEffDate]        SMALLDATETIME NOT NULL,
    [CuryId]             CHAR (4)      NOT NULL,
    [CuryMultDiv]        CHAR (1)      NOT NULL,
    [CuryRate]           FLOAT (53)    NOT NULL,
    [CuryRateType]       CHAR (6)      NOT NULL,
    [date_submitted]     SMALLDATETIME NOT NULL,
    [inv_paid_flag]      CHAR (1)      NOT NULL,
    [invoice_date]       SMALLDATETIME NOT NULL,
    [lupd_datetime]      SMALLDATETIME NOT NULL,
    [lupd_prog]          CHAR (8)      NOT NULL,
    [lupd_user]          CHAR (10)     NOT NULL,
    [noteid]             INT           NOT NULL,
    [override_reason]    CHAR (30)     NOT NULL,
    [override_vendid]    CHAR (15)     NOT NULL,
    [payreq_desc]        CHAR (60)     NOT NULL,
    [payreq_type_cd]     CHAR (4)      NOT NULL,
    [payreqnbr]          CHAR (4)      NOT NULL,
    [preparer]           CHAR (10)     NOT NULL,
    [project]            CHAR (16)     NOT NULL,
    [py_id01]            CHAR (30)     NOT NULL,
    [py_id02]            CHAR (30)     NOT NULL,
    [py_id03]            CHAR (16)     NOT NULL,
    [py_id04]            CHAR (16)     NOT NULL,
    [py_id05]            CHAR (4)      NOT NULL,
    [py_id06]            FLOAT (53)    NOT NULL,
    [py_id07]            FLOAT (53)    NOT NULL,
    [py_id08]            SMALLDATETIME NOT NULL,
    [py_id09]            SMALLDATETIME NOT NULL,
    [py_id10]            INT           NOT NULL,
    [py_id11]            CHAR (30)     NOT NULL,
    [py_id12]            CHAR (30)     NOT NULL,
    [py_id13]            CHAR (16)     NOT NULL,
    [py_id14]            CHAR (16)     NOT NULL,
    [py_id15]            CHAR (4)      NOT NULL,
    [py_id16]            FLOAT (53)    NOT NULL,
    [py_id17]            FLOAT (53)    NOT NULL,
    [py_id18]            SMALLDATETIME NOT NULL,
    [py_id19]            SMALLDATETIME NOT NULL,
    [py_id20]            INT           NOT NULL,
    [refnbr]             CHAR (10)     NOT NULL,
    [refnbr_ret]         CHAR (10)     NOT NULL,
    [status1]            CHAR (1)      NOT NULL,
    [status2]            CHAR (1)      NOT NULL,
    [subcontract]        CHAR (16)     NOT NULL,
    [user1]              CHAR (30)     NOT NULL,
    [user2]              CHAR (30)     NOT NULL,
    [user3]              FLOAT (53)    NOT NULL,
    [user4]              FLOAT (53)    NOT NULL,
    [user5]              CHAR (30)     NOT NULL,
    [user6]              CHAR (30)     NOT NULL,
    [user7]              FLOAT (53)    NOT NULL,
    [user8]              FLOAT (53)    NOT NULL,
    [vendid]             CHAR (15)     NOT NULL,
    [vendor_invref]      CHAR (15)     NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [pjpayhdr0] PRIMARY KEY CLUSTERED ([project] ASC, [subcontract] ASC, [payreqnbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [PJPAYHDR1]
    ON [dbo].[PJPAYHDR]([batnbr] ASC, [refnbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [PJPAYHDR2]
    ON [dbo].[PJPAYHDR]([batnbr] ASC, [refnbr_ret] ASC) WITH (FILLFACTOR = 90);

