CREATE TABLE [dbo].[XDDFileFormat] (
    [AcctNbrNotReqd]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [AcctTypeTitle]       CHAR (30)     DEFAULT ('') NOT NULL,
    [BankAcctLen]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [BankTransitCDigit]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [BankTransitLen]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [BankTransitNotReqd]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [BankTransitTitle]    CHAR (30)     DEFAULT ('') NOT NULL,
    [BEDesc01]            CHAR (30)     DEFAULT ('') NOT NULL,
    [BEDesc02]            CHAR (30)     DEFAULT ('') NOT NULL,
    [BEMask01]            CHAR (30)     DEFAULT ('') NOT NULL,
    [BEMask02]            CHAR (30)     DEFAULT ('') NOT NULL,
    [BlockFill]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [CompanyIDMask]       CHAR (30)     DEFAULT ('') NOT NULL,
    [CompanyIDTitle]      CHAR (30)     DEFAULT ('') NOT NULL,
    [CompanyNameMask]     CHAR (30)     DEFAULT ('') NOT NULL,
    [CompanyNameTitle]    CHAR (30)     DEFAULT ('') NOT NULL,
    [CrLf]                SMALLINT      DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [Descr]               CHAR (60)     DEFAULT ('') NOT NULL,
    [EffDateOffSet]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [EntryClassTitle]     CHAR (30)     DEFAULT ((0)) NOT NULL,
    [EntryClassDescrMask] CHAR (20)     DEFAULT ('') NOT NULL,
    [EntryClassUserField] SMALLINT      DEFAULT ((0)) NOT NULL,
    [EntryClassUserFldAR] SMALLINT      DEFAULT ((0)) NOT NULL,
    [FormatID]            CHAR (15)     DEFAULT ('') NOT NULL,
    [FormatType]          CHAR (1)      DEFAULT ('') NOT NULL,
    [HTNotes]             CHAR (255)    DEFAULT ('') NOT NULL,
    [HTRecord]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [ImmDestMask]         CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmDestNameMask]     CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmDestNameTitle]    CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmDestTitle]        CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmOrigNameMask]     CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmOrigNameTitle]    CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmOrigMask]         CHAR (30)     DEFAULT ('') NOT NULL,
    [ImmOrigTitle]        CHAR (30)     DEFAULT ('') NOT NULL,
    [InclCOCredit]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [InclCODebit]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [KeepDelete]          CHAR (1)      DEFAULT ('') NOT NULL,
    [LastEffDate]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [MultiLineToken]      CHAR (1)      DEFAULT ('') NOT NULL,
    [NextDailyReset]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [NextDailyResetDate]  SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [NextFileID]          INT           DEFAULT ((0)) NOT NULL,
    [NextSeqNum]          INT           DEFAULT ((0)) NOT NULL,
    [NoteID]              INT           DEFAULT ((0)) NOT NULL,
    [PreNote]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [PreNoteDays]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [RecordLen]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [Selected]            CHAR (1)      DEFAULT ('') NOT NULL,
    [SKFuture01]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]          CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]          CHAR (10)     DEFAULT ('') NOT NULL,
    [TaxPayment]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [TrimRecord]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [TwoFileNameAddition] CHAR (10)     DEFAULT ('') NOT NULL,
    [TwoFileSepString]    CHAR (20)     DEFAULT ('') NOT NULL,
    [UpdatedMVA]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [User1]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]               CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank01Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank01Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank01Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank02Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank02Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank02Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank03Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank03Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank03Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank04Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank04Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank04Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank05Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank05Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank05Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank06Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank06Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank06Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank07Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank07Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank07Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBank08Descr]        CHAR (30)     DEFAULT ('') NOT NULL,
    [WBank08Mask]         CHAR (35)     DEFAULT ('') NOT NULL,
    [WBank08Reqd]         SMALLINT      DEFAULT ('') NOT NULL,
    [WBenAdvicePV]        CHAR (100)    DEFAULT ('') NOT NULL,
    [WBenBankAcctTypePV]  CHAR (255)    DEFAULT ('') NOT NULL,
    [WBenBankAdvicePV]    CHAR (100)    DEFAULT ('') NOT NULL,
    [WBenBankInstCodePV]  CHAR (100)    DEFAULT ('') NOT NULL,
    [WBenBankQualPV]      CHAR (255)    DEFAULT ('') NOT NULL,
    [WBeneAcctTypePV]     CHAR (255)    DEFAULT ('') NOT NULL,
    [WBenMailHandlePV]    CHAR (100)    DEFAULT ('') NOT NULL,
    [WChargesIndicPV]     CHAR (100)    DEFAULT ('') NOT NULL,
    [WChkCrossCodePV]     CHAR (100)    DEFAULT ('') NOT NULL,
    [WChkForwardCodePV]   CHAR (100)    DEFAULT ('') NOT NULL,
    [WCorresCostCodePV]   CHAR (100)    DEFAULT ('') NOT NULL,
    [WCrePartyAdvicePV]   CHAR (100)    DEFAULT ('') NOT NULL,
    [WCrePartyAcctTypePV] CHAR (100)    DEFAULT ('') NOT NULL,
    [WCtryQualifierPV]    CHAR (100)    DEFAULT ('') NOT NULL,
    [WDomCostCodePV]      CHAR (100)    DEFAULT ('') NOT NULL,
    [WIntBankQualifierPV] CHAR (255)    DEFAULT ('') NOT NULL,
    [WMultiCpnySel]       SMALLINT      DEFAULT ('') NOT NULL,
    [WOtherPriorityPV]    CHAR (100)    DEFAULT ('') NOT NULL,
    [WPmtCategCodePV]     CHAR (100)    DEFAULT ('') NOT NULL,
    [WPmtMethodCodePV]    CHAR (100)    DEFAULT ('') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [XDDFileFormat0] PRIMARY KEY CLUSTERED ([FormatID] ASC)
);

