CREATE TABLE [dbo].[Salesperson] (
    [Addr1]         CHAR (60)     NOT NULL,
    [Addr2]         CHAR (60)     NOT NULL,
    [Attn]          CHAR (30)     NOT NULL,
    [City]          CHAR (30)     NOT NULL,
    [CmmnPct]       FLOAT (53)    NOT NULL,
    [Country]       CHAR (3)      NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [EMailAddr]     CHAR (80)     NOT NULL,
    [Fax]           CHAR (30)     NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [Name]          CHAR (60)     NOT NULL,
    [NoteId]        INT           NOT NULL,
    [PerNbr]        CHAR (6)      NOT NULL,
    [Phone]         CHAR (30)     NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [Salut]         CHAR (30)     NOT NULL,
    [SlsperId]      CHAR (10)     NOT NULL,
    [State]         CHAR (3)      NOT NULL,
    [Territory]     CHAR (10)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [Zip]           CHAR (10)     NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [salesperson0] PRIMARY KEY CLUSTERED ([SlsperId] ASC) WITH (FILLFACTOR = 90)
);

