CREATE TABLE [dbo].[CustomFtr] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustomFtr_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_CustomFtr_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_CustomFtr_Crtd_User] DEFAULT (' ') NOT NULL,
    [Dependencies]  SMALLINT      CONSTRAINT [DF_CustomFtr_Dependencies] DEFAULT ((0)) NOT NULL,
    [Exclusions]    SMALLINT      CONSTRAINT [DF_CustomFtr_Exclusions] DEFAULT ((0)) NOT NULL,
    [FeatureDesc]   CHAR (30)     CONSTRAINT [DF_CustomFtr_FeatureDesc] DEFAULT (' ') NOT NULL,
    [FeatureNbr]    CHAR (4)      CONSTRAINT [DF_CustomFtr_FeatureNbr] DEFAULT (' ') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_CustomFtr_InvtID] DEFAULT (' ') NOT NULL,
    [LineID]        INT           CONSTRAINT [DF_CustomFtr_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]       SMALLINT      CONSTRAINT [DF_CustomFtr_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]       CHAR (5)      CONSTRAINT [DF_CustomFtr_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustomFtr_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_CustomFtr_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_CustomFtr_LUpd_User] DEFAULT (' ') NOT NULL,
    [MaxQty]        FLOAT (53)    CONSTRAINT [DF_CustomFtr_MaxQty] DEFAULT ((0)) NOT NULL,
    [MinQty]        FLOAT (53)    CONSTRAINT [DF_CustomFtr_MinQty] DEFAULT ((0)) NOT NULL,
    [MultiOpt]      SMALLINT      CONSTRAINT [DF_CustomFtr_MultiOpt] DEFAULT ((0)) NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_CustomFtr_NoteID] DEFAULT ((0)) NOT NULL,
    [Required]      SMALLINT      CONSTRAINT [DF_CustomFtr_Required] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_CustomFtr_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_CustomFtr_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_CustomFtr_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_CustomFtr_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_CustomFtr_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_CustomFtr_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_CustomFtr_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_CustomFtr_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_CustomFtr_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_CustomFtr_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_CustomFtr_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_CustomFtr_S4Future12] DEFAULT (' ') NOT NULL,
    [StartDate]     SMALLDATETIME CONSTRAINT [DF_CustomFtr_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Status]        CHAR (1)      CONSTRAINT [DF_CustomFtr_Status] DEFAULT (' ') NOT NULL,
    [StopDate]      SMALLDATETIME CONSTRAINT [DF_CustomFtr_StopDate] DEFAULT ('01/01/1900') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_CustomFtr_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_CustomFtr_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_CustomFtr_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_CustomFtr_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_CustomFtr_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_CustomFtr_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_CustomFtr_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_CustomFtr_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CustomFtr0] PRIMARY KEY CLUSTERED ([InvtID] ASC, [FeatureNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [CustomFtr1]
    ON [dbo].[CustomFtr]([InvtID] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);

