CREATE TABLE [dbo].[SOShipLine] (
    [AlternateID]        CHAR (30)     CONSTRAINT [DF_SOShipLine_AlternateID] DEFAULT (' ') NOT NULL,
    [AltIDType]          CHAR (1)      CONSTRAINT [DF_SOShipLine_AltIDType] DEFAULT (' ') NOT NULL,
    [AvgCost]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_AvgCost] DEFAULT ((0)) NOT NULL,
    [BMICost]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_BMICost] DEFAULT ((0)) NOT NULL,
    [BMICuryID]          CHAR (4)      CONSTRAINT [DF_SOShipLine_BMICuryID] DEFAULT (' ') NOT NULL,
    [BMIEffDate]         SMALLDATETIME CONSTRAINT [DF_SOShipLine_BMIEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [BMIExtPriceInvc]    FLOAT (53)    CONSTRAINT [DF_SOShipLine_BMIExtPriceInvc] DEFAULT ((0)) NOT NULL,
    [BMIMultDiv]         CHAR (1)      CONSTRAINT [DF_SOShipLine_BMIMultDiv] DEFAULT (' ') NOT NULL,
    [BMIRate]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_BMIRate] DEFAULT ((0)) NOT NULL,
    [BMIRtTp]            CHAR (6)      CONSTRAINT [DF_SOShipLine_BMIRtTp] DEFAULT (' ') NOT NULL,
    [BMISlsPrice]        FLOAT (53)    CONSTRAINT [DF_SOShipLine_BMISlsPrice] DEFAULT ((0)) NOT NULL,
    [ChainDisc]          CHAR (15)     CONSTRAINT [DF_SOShipLine_ChainDisc] DEFAULT (' ') NOT NULL,
    [CmmnPct]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_CmmnPct] DEFAULT ((0)) NOT NULL,
    [CnvFact]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_CnvFact] DEFAULT ((0)) NOT NULL,
    [COGSAcct]           CHAR (10)     CONSTRAINT [DF_SOShipLine_COGSAcct] DEFAULT (' ') NOT NULL,
    [COGSSub]            CHAR (24)     CONSTRAINT [DF_SOShipLine_COGSSub] DEFAULT (' ') NOT NULL,
    [CommCost]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_CommCost] DEFAULT ((0)) NOT NULL,
    [Cost]               FLOAT (53)    CONSTRAINT [DF_SOShipLine_Cost] DEFAULT ((0)) NOT NULL,
    [CpnyID]             CHAR (10)     CONSTRAINT [DF_SOShipLine_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME CONSTRAINT [DF_SOShipLine_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_SOShipLine_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_SOShipLine_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCommCost]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryCommCost] DEFAULT ((0)) NOT NULL,
    [CuryCost]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryCost] DEFAULT ((0)) NOT NULL,
    [CuryListPrice]      FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryListPrice] DEFAULT ((0)) NOT NULL,
    [CurySlsPrice]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CurySlsPrice] DEFAULT ((0)) NOT NULL,
    [CuryTaxAmt00]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTaxAmt00] DEFAULT ((0)) NOT NULL,
    [CuryTaxAmt01]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTaxAmt01] DEFAULT ((0)) NOT NULL,
    [CuryTaxAmt02]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTaxAmt02] DEFAULT ((0)) NOT NULL,
    [CuryTaxAmt03]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTaxAmt03] DEFAULT ((0)) NOT NULL,
    [CuryTotCommCost]    FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTotCommCost] DEFAULT ((0)) NOT NULL,
    [CuryTotCost]        FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTotCost] DEFAULT ((0)) NOT NULL,
    [CuryTotInvc]        FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTotInvc] DEFAULT ((0)) NOT NULL,
    [CuryTotMerch]       FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTotMerch] DEFAULT ((0)) NOT NULL,
    [CuryTxblAmt00]      FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTxblAmt00] DEFAULT ((0)) NOT NULL,
    [CuryTxblAmt01]      FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTxblAmt01] DEFAULT ((0)) NOT NULL,
    [CuryTxblAmt02]      FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTxblAmt02] DEFAULT ((0)) NOT NULL,
    [CuryTxblAmt03]      FLOAT (53)    CONSTRAINT [DF_SOShipLine_CuryTxblAmt03] DEFAULT ((0)) NOT NULL,
    [Descr]              CHAR (60)     CONSTRAINT [DF_SOShipLine_Descr] DEFAULT (' ') NOT NULL,
    [DescrLang]          CHAR (30)     CONSTRAINT [DF_SOShipLine_DescrLang] DEFAULT (' ') NOT NULL,
    [DiscAcct]           CHAR (10)     CONSTRAINT [DF_SOShipLine_DiscAcct] DEFAULT (' ') NOT NULL,
    [DiscPct]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_DiscPct] DEFAULT ((0)) NOT NULL,
    [DiscSub]            CHAR (24)     CONSTRAINT [DF_SOShipLine_DiscSub] DEFAULT (' ') NOT NULL,
    [Disp]               CHAR (3)      CONSTRAINT [DF_SOShipLine_Disp] DEFAULT (' ') NOT NULL,
    [InspID]             CHAR (2)      CONSTRAINT [DF_SOShipLine_InspID] DEFAULT (' ') NOT NULL,
    [InspNoteID]         INT           CONSTRAINT [DF_SOShipLine_InspNoteID] DEFAULT ((0)) NOT NULL,
    [InvAcct]            CHAR (10)     CONSTRAINT [DF_SOShipLine_InvAcct] DEFAULT (' ') NOT NULL,
    [InvSub]             CHAR (24)     CONSTRAINT [DF_SOShipLine_InvSub] DEFAULT (' ') NOT NULL,
    [InvtID]             CHAR (30)     CONSTRAINT [DF_SOShipLine_InvtID] DEFAULT (' ') NOT NULL,
    [IRDemand]           SMALLINT      CONSTRAINT [DF_SOShipLine_IRDemand] DEFAULT ((0)) NOT NULL,
    [IRInvtID]           CHAR (30)     CONSTRAINT [DF_SOShipLine_IRInvtID] DEFAULT (' ') NOT NULL,
    [IRSiteID]           CHAR (10)     CONSTRAINT [DF_SOShipLine_IRSiteID] DEFAULT (' ') NOT NULL,
    [ItemGLClassID]      CHAR (4)      CONSTRAINT [DF_SOShipLine_ItemGLClassID] DEFAULT (' ') NOT NULL,
    [LineNbr]            SMALLINT      CONSTRAINT [DF_SOShipLine_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]            CHAR (5)      CONSTRAINT [DF_SOShipLine_LineRef] DEFAULT (' ') NOT NULL,
    [ListPrice]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_ListPrice] DEFAULT ((0)) NOT NULL,
    [LotSerCntr]         SMALLINT      CONSTRAINT [DF_SOShipLine_LotSerCntr] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME CONSTRAINT [DF_SOShipLine_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      CONSTRAINT [DF_SOShipLine_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]          CHAR (10)     CONSTRAINT [DF_SOShipLine_LUpd_User] DEFAULT (' ') NOT NULL,
    [ManualCost]         SMALLINT      CONSTRAINT [DF_SOShipLine_ManualCost] DEFAULT ((0)) NOT NULL,
    [ManualPrice]        SMALLINT      CONSTRAINT [DF_SOShipLine_ManualPrice] DEFAULT ((0)) NOT NULL,
    [NoteID]             INT           CONSTRAINT [DF_SOShipLine_NoteID] DEFAULT ((0)) NOT NULL,
    [OrdLineRef]         CHAR (5)      CONSTRAINT [DF_SOShipLine_OrdLineRef] DEFAULT (' ') NOT NULL,
    [OrdNbr]             CHAR (15)     CONSTRAINT [DF_SOShipLine_OrdNbr] DEFAULT (' ') NOT NULL,
    [OrigBO]             FLOAT (53)    CONSTRAINT [DF_SOShipLine_OrigBO] DEFAULT ((0)) NOT NULL,
    [OrigINBatNbr]       CHAR (10)     CONSTRAINT [DF_SOShipLine_OrigINBatNbr] DEFAULT (' ') NOT NULL,
    [OrigInvcNbr]        CHAR (15)     CONSTRAINT [DF_SOShipLine_OrigInvcNbr] DEFAULT (' ') NOT NULL,
    [OrigInvtID]         CHAR (30)     CONSTRAINT [DF_SOShipLine_OrigInvtID] DEFAULT (' ') NOT NULL,
    [OrigShipperID]      CHAR (15)     CONSTRAINT [DF_SOShipLine_OrigShipperID] DEFAULT (' ') NOT NULL,
    [OrigShipperLineRef] CHAR (5)      CONSTRAINT [DF_SOShipLine_OrigShipperLineRef] DEFAULT (' ') NOT NULL,
    [ProjectID]          CHAR (16)     CONSTRAINT [DF_SOShipLine_ProjectID] DEFAULT (' ') NOT NULL,
    [QtyBO]              FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyBO] DEFAULT ((0)) NOT NULL,
    [QtyFuture]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyFuture] DEFAULT ((0)) NOT NULL,
    [QtyOrd]             FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyOrd] DEFAULT ((0)) NOT NULL,
    [QtyPick]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyPick] DEFAULT ((0)) NOT NULL,
    [QtyPrevShip]        FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyPrevShip] DEFAULT ((0)) NOT NULL,
    [QtyShip]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_QtyShip] DEFAULT ((0)) NOT NULL,
    [RebateID]           CHAR (10)     CONSTRAINT [DF_SOShipLine_RebateID] DEFAULT (' ') NOT NULL,
    [RebatePer]          CHAR (6)      CONSTRAINT [DF_SOShipLine_RebatePer] DEFAULT (' ') NOT NULL,
    [RebateRefNbr]       CHAR (10)     CONSTRAINT [DF_SOShipLine_RebateRefNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_SOShipLine_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_SOShipLine_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_SOShipLine_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_SOShipLine_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_SOShipLine_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_SOShipLine_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_SOShipLine_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_SOShipLine_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_SOShipLine_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_SOShipLine_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_SOShipLine_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_SOShipLine_S4Future12] DEFAULT (' ') NOT NULL,
    [Sample]             SMALLINT      CONSTRAINT [DF_SOShipLine_Sample] DEFAULT ((0)) NOT NULL,
    [Service]            SMALLINT      CONSTRAINT [DF_SOShipLine_Service] DEFAULT ((0)) NOT NULL,
    [ShipperID]          CHAR (15)     CONSTRAINT [DF_SOShipLine_ShipperID] DEFAULT (' ') NOT NULL,
    [ShipWght]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_ShipWght] DEFAULT ((0)) NOT NULL,
    [SiteID]             CHAR (10)     CONSTRAINT [DF_SOShipLine_SiteID] DEFAULT (' ') NOT NULL,
    [SlsAcct]            CHAR (10)     CONSTRAINT [DF_SOShipLine_SlsAcct] DEFAULT (' ') NOT NULL,
    [SlsperID]           CHAR (10)     CONSTRAINT [DF_SOShipLine_SlsperID] DEFAULT (' ') NOT NULL,
    [SlsPrice]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_SlsPrice] DEFAULT ((0)) NOT NULL,
    [SlsPriceID]         CHAR (15)     CONSTRAINT [DF_SOShipLine_SlsPriceID] DEFAULT (' ') NOT NULL,
    [SlsSub]             CHAR (24)     CONSTRAINT [DF_SOShipLine_SlsSub] DEFAULT (' ') NOT NULL,
    [SplitLots]          SMALLINT      CONSTRAINT [DF_SOShipLine_SplitLots] DEFAULT ((0)) NOT NULL,
    [Status]             CHAR (1)      CONSTRAINT [DF_SOShipLine_Status] DEFAULT (' ') NOT NULL,
    [TaskID]             CHAR (32)     CONSTRAINT [DF_SOShipLine_TaskID] DEFAULT (' ') NOT NULL,
    [Taxable]            SMALLINT      CONSTRAINT [DF_SOShipLine_Taxable] DEFAULT ((0)) NOT NULL,
    [TaxAmt00]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_TaxAmt00] DEFAULT ((0)) NOT NULL,
    [TaxAmt01]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_TaxAmt01] DEFAULT ((0)) NOT NULL,
    [TaxAmt02]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_TaxAmt02] DEFAULT ((0)) NOT NULL,
    [TaxAmt03]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_TaxAmt03] DEFAULT ((0)) NOT NULL,
    [TaxCat]             CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxCat] DEFAULT (' ') NOT NULL,
    [TaxID00]            CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxID00] DEFAULT (' ') NOT NULL,
    [TaxID01]            CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxID01] DEFAULT (' ') NOT NULL,
    [TaxID02]            CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxID02] DEFAULT (' ') NOT NULL,
    [TaxID03]            CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxID03] DEFAULT (' ') NOT NULL,
    [TaxIDDflt]          CHAR (10)     CONSTRAINT [DF_SOShipLine_TaxIDDflt] DEFAULT (' ') NOT NULL,
    [TotCommCost]        FLOAT (53)    CONSTRAINT [DF_SOShipLine_TotCommCost] DEFAULT ((0)) NOT NULL,
    [TotCost]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_TotCost] DEFAULT ((0)) NOT NULL,
    [TotInvc]            FLOAT (53)    CONSTRAINT [DF_SOShipLine_TotInvc] DEFAULT ((0)) NOT NULL,
    [TotMerch]           FLOAT (53)    CONSTRAINT [DF_SOShipLine_TotMerch] DEFAULT ((0)) NOT NULL,
    [TxblAmt00]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_TxblAmt00] DEFAULT ((0)) NOT NULL,
    [TxblAmt01]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_TxblAmt01] DEFAULT ((0)) NOT NULL,
    [TxblAmt02]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_TxblAmt02] DEFAULT ((0)) NOT NULL,
    [TxblAmt03]          FLOAT (53)    CONSTRAINT [DF_SOShipLine_TxblAmt03] DEFAULT ((0)) NOT NULL,
    [UnitDesc]           CHAR (6)      CONSTRAINT [DF_SOShipLine_UnitDesc] DEFAULT (' ') NOT NULL,
    [UnitMultDiv]        CHAR (1)      CONSTRAINT [DF_SOShipLine_UnitMultDiv] DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_SOShipLine_User1] DEFAULT (' ') NOT NULL,
    [User10]             SMALLDATETIME CONSTRAINT [DF_SOShipLine_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_SOShipLine_User2] DEFAULT (' ') NOT NULL,
    [User3]              CHAR (30)     CONSTRAINT [DF_SOShipLine_User3] DEFAULT (' ') NOT NULL,
    [User4]              CHAR (30)     CONSTRAINT [DF_SOShipLine_User4] DEFAULT (' ') NOT NULL,
    [User5]              FLOAT (53)    CONSTRAINT [DF_SOShipLine_User5] DEFAULT ((0)) NOT NULL,
    [User6]              FLOAT (53)    CONSTRAINT [DF_SOShipLine_User6] DEFAULT ((0)) NOT NULL,
    [User7]              CHAR (10)     CONSTRAINT [DF_SOShipLine_User7] DEFAULT (' ') NOT NULL,
    [User8]              CHAR (10)     CONSTRAINT [DF_SOShipLine_User8] DEFAULT (' ') NOT NULL,
    [User9]              SMALLDATETIME CONSTRAINT [DF_SOShipLine_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [SOShipLine0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [ShipperID] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [SOShipLine2]
    ON [dbo].[SOShipLine]([ShipperID] ASC, [LineRef] ASC, [CpnyID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOShipLine1]
    ON [dbo].[SOShipLine]([Status] ASC, [InvtID] ASC, [SiteID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOShipLine3]
    ON [dbo].[SOShipLine]([CpnyID] ASC, [OrdNbr] ASC, [OrdLineRef] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOShipLine4]
    ON [dbo].[SOShipLine]([CpnyID] ASC, [ShipperID] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);

