CREATE TABLE [dbo].[List] (
    [Description00] CHAR (30)  NOT NULL,
    [Description01] CHAR (30)  NOT NULL,
    [Description02] CHAR (30)  NOT NULL,
    [Description03] CHAR (30)  NOT NULL,
    [Description04] CHAR (30)  NOT NULL,
    [Description05] CHAR (30)  NOT NULL,
    [Description06] CHAR (30)  NOT NULL,
    [Description07] CHAR (30)  NOT NULL,
    [Description08] CHAR (30)  NOT NULL,
    [Description09] CHAR (30)  NOT NULL,
    [Description10] CHAR (30)  NOT NULL,
    [Description11] CHAR (30)  NOT NULL,
    [Description12] CHAR (30)  NOT NULL,
    [Description13] CHAR (30)  NOT NULL,
    [Description14] CHAR (30)  NOT NULL,
    [Description15] CHAR (30)  NOT NULL,
    [Description16] CHAR (30)  NOT NULL,
    [Description17] CHAR (30)  NOT NULL,
    [Description18] CHAR (30)  NOT NULL,
    [Description19] CHAR (30)  NOT NULL,
    [ListID]        CHAR (40)  NOT NULL,
    [User1]         CHAR (30)  NOT NULL,
    [User2]         CHAR (30)  NOT NULL,
    [User3]         FLOAT (53) NOT NULL,
    [User4]         FLOAT (53) NOT NULL,
    [User5]         CHAR (10)  NOT NULL,
    [User6]         CHAR (10)  NOT NULL,
    [Value00]       CHAR (4)   NOT NULL,
    [Value01]       CHAR (4)   NOT NULL,
    [Value02]       CHAR (4)   NOT NULL,
    [Value03]       CHAR (4)   NOT NULL,
    [Value04]       CHAR (4)   NOT NULL,
    [Value05]       CHAR (4)   NOT NULL,
    [Value06]       CHAR (4)   NOT NULL,
    [Value07]       CHAR (4)   NOT NULL,
    [Value08]       CHAR (4)   NOT NULL,
    [Value09]       CHAR (4)   NOT NULL,
    [Value10]       CHAR (4)   NOT NULL,
    [Value11]       CHAR (4)   NOT NULL,
    [Value12]       CHAR (4)   NOT NULL,
    [Value13]       CHAR (4)   NOT NULL,
    [Value14]       CHAR (4)   NOT NULL,
    [Value15]       CHAR (4)   NOT NULL,
    [Value16]       CHAR (4)   NOT NULL,
    [Value17]       CHAR (4)   NOT NULL,
    [Value18]       CHAR (4)   NOT NULL,
    [Value19]       CHAR (4)   NOT NULL,
    [tstamp]        ROWVERSION NOT NULL,
    CONSTRAINT [List0] PRIMARY KEY CLUSTERED ([ListID] ASC) WITH (FILLFACTOR = 90)
);

