CREATE TABLE [dbo].[RcptAddlCost] (
    [AddlCostAccrAcct]  CHAR (10)     CONSTRAINT [DF_RcptAddlCost_AddlCostAccrAcct] DEFAULT (' ') NOT NULL,
    [AddlCostAccrSub]   CHAR (24)     CONSTRAINT [DF_RcptAddlCost_AddlCostAccrSub] DEFAULT (' ') NOT NULL,
    [AddlCostExpAcct]   CHAR (10)     CONSTRAINT [DF_RcptAddlCost_AddlCostExpAcct] DEFAULT (' ') NOT NULL,
    [AddlCostExpSub]    CHAR (24)     CONSTRAINT [DF_RcptAddlCost_AddlCostExpSub] DEFAULT (' ') NOT NULL,
    [AddlCostTypeID]    CHAR (10)     CONSTRAINT [DF_RcptAddlCost_AddlCostTypeID] DEFAULT (' ') NOT NULL,
    [APBatNbr]          CHAR (10)     CONSTRAINT [DF_RcptAddlCost_APBatNbr] DEFAULT (' ') NOT NULL,
    [APRefNo]           CHAR (10)     CONSTRAINT [DF_RcptAddlCost_APRefNo] DEFAULT (' ') NOT NULL,
    [BatNbr]            CHAR (10)     CONSTRAINT [DF_RcptAddlCost_BatNbr] DEFAULT (' ') NOT NULL,
    [CostVouched]       FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_CostVouched] DEFAULT ((0)) NOT NULL,
    [CpnyID]            CHAR (10)     CONSTRAINT [DF_RcptAddlCost_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      CONSTRAINT [DF_RcptAddlCost_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     CONSTRAINT [DF_RcptAddlCost_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCostVouched]   FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_CuryCostVouched] DEFAULT ((0)) NOT NULL,
    [CuryExpectedCost]  FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_CuryExpectedCost] DEFAULT ((0)) NOT NULL,
    [CuryID]            CHAR (4)      CONSTRAINT [DF_RcptAddlCost_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]       CHAR (1)      CONSTRAINT [DF_RcptAddlCost_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]          FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_CuryRate] DEFAULT ((0)) NOT NULL,
    [Descr]             CHAR (30)     CONSTRAINT [DF_RcptAddlCost_Descr] DEFAULT (' ') NOT NULL,
    [DfltPct]           FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_DfltPct] DEFAULT ((0)) NOT NULL,
    [ExpectedCost]      FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_ExpectedCost] DEFAULT ((0)) NOT NULL,
    [Labor_Class_CD]    CHAR (4)      CONSTRAINT [DF_RcptAddlCost_Labor_Class_CD] DEFAULT (' ') NOT NULL,
    [LineID]            INT           CONSTRAINT [DF_RcptAddlCost_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]           SMALLINT      CONSTRAINT [DF_RcptAddlCost_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]           CHAR (5)      CONSTRAINT [DF_RcptAddlCost_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      CONSTRAINT [DF_RcptAddlCost_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     CONSTRAINT [DF_RcptAddlCost_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]            INT           CONSTRAINT [DF_RcptAddlCost_NoteID] DEFAULT ((0)) NOT NULL,
    [OrigAddlCostLine]  SMALLINT      CONSTRAINT [DF_RcptAddlCost_OrigAddlCostLine] DEFAULT ((0)) NOT NULL,
    [PC_Flag]           CHAR (1)      CONSTRAINT [DF_RcptAddlCost_PC_Flag] DEFAULT (' ') NOT NULL,
    [PC_Status]         CHAR (1)      CONSTRAINT [DF_RcptAddlCost_PC_Status] DEFAULT (' ') NOT NULL,
    [POAddlCostLineRef] CHAR (5)      CONSTRAINT [DF_RcptAddlCost_POAddlCostLineRef] DEFAULT (' ') NOT NULL,
    [PONbr]             CHAR (10)     CONSTRAINT [DF_RcptAddlCost_PONbr] DEFAULT (' ') NOT NULL,
    [ProjectID]         CHAR (16)     CONSTRAINT [DF_RcptAddlCost_ProjectID] DEFAULT (' ') NOT NULL,
    [ProrateMthd]       CHAR (1)      CONSTRAINT [DF_RcptAddlCost_ProrateMthd] DEFAULT (' ') NOT NULL,
    [RcptNbr]           CHAR (10)     CONSTRAINT [DF_RcptAddlCost_RcptNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]        CHAR (30)     CONSTRAINT [DF_RcptAddlCost_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     CONSTRAINT [DF_RcptAddlCost_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           CONSTRAINT [DF_RcptAddlCost_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           CONSTRAINT [DF_RcptAddlCost_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     CONSTRAINT [DF_RcptAddlCost_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     CONSTRAINT [DF_RcptAddlCost_S4Future12] DEFAULT (' ') NOT NULL,
    [SeparateVoucher]   SMALLINT      CONSTRAINT [DF_RcptAddlCost_SeparateVoucher] DEFAULT ((0)) NOT NULL,
    [TaskID]            CHAR (32)     CONSTRAINT [DF_RcptAddlCost_TaskID] DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     CONSTRAINT [DF_RcptAddlCost_User1] DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     CONSTRAINT [DF_RcptAddlCost_User2] DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_User3] DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    CONSTRAINT [DF_RcptAddlCost_User4] DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     CONSTRAINT [DF_RcptAddlCost_User5] DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     CONSTRAINT [DF_RcptAddlCost_User6] DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME CONSTRAINT [DF_RcptAddlCost_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]            CHAR (15)     CONSTRAINT [DF_RcptAddlCost_VendID] DEFAULT (' ') NOT NULL,
    [VouchStatus]       CHAR (1)      CONSTRAINT [DF_RcptAddlCost_VouchStatus] DEFAULT (' ') NOT NULL,
    [WaybillNbr]        CHAR (30)     CONSTRAINT [DF_RcptAddlCost_WaybillNbr] DEFAULT (' ') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [RcptAddlCost0] PRIMARY KEY CLUSTERED ([RcptNbr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);

