CREATE TABLE [dbo].[cft_VFDDispatch] (
    [ContactID]       VARCHAR (6)   NOT NULL,
    [Crtd_DateTime]   DATETIME      NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (20)     NOT NULL,
    [DrugID]          INT           NOT NULL,
    [Eff_DT]          SMALLDATETIME NOT NULL,
    [Expire_DT]       SMALLDATETIME NOT NULL,
    [FormId]          INT           NOT NULL,
    [IDVFDDispatch]   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Lupd_DateTime]   SMALLDATETIME NULL,
    [Lupd_Prog]       CHAR (8)      NULL,
    [Lupd_User]       CHAR (20)     NULL,
    [MillID]          VARCHAR (6)   NOT NULL,
    [NBRToFeed]       INT           NOT NULL,
    [PigGroupID]      VARCHAR (15)  NULL,
    [ReferenceNumber] VARCHAR (25)  NULL,
    [Results_Msg]     VARCHAR (255) NULL,
    [SiteID]          VARCHAR (4)   NOT NULL,
    [SPInstructions]  VARCHAR (255) NULL,
    [UserId]          INT           NOT NULL,
    [VetID]           VARCHAR (6)   NOT NULL,
    [Void]            BIT           NOT NULL,
    [Void_DateTime]   SMALLDATETIME NULL,
    [Void_User]       CHAR (20)     NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [cft_VFDDispatch0] PRIMARY KEY CLUSTERED ([IDVFDDispatch] ASC) WITH (FILLFACTOR = 100)
);

