CREATE TABLE [dbo].[SHShipPack] (
    [BaseCost]      FLOAT (53)    NOT NULL,
    [BoxRef]        CHAR (5)      NOT NULL,
    [CartonID]      CHAR (20)     NOT NULL,
    [CODAmt]        FLOAT (53)    NOT NULL,
    [CODCost]       FLOAT (53)    NOT NULL,
    [ContainerID]   CHAR (10)     NOT NULL,
    [CpnyID]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CuryID]        CHAR (4)      NOT NULL,
    [HandlingChg]   FLOAT (53)    NOT NULL,
    [InsureCost]    FLOAT (53)    NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [OtherCost]     FLOAT (53)    NOT NULL,
    [OversizeCost]  FLOAT (53)    NOT NULL,
    [PackageID]     CHAR (15)     NOT NULL,
    [PalletID]      CHAR (20)     NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [ShipperID]     CHAR (15)     NOT NULL,
    [TrackingNbr]   CHAR (20)     NOT NULL,
    [TruckID]       CHAR (18)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User10]        SMALLDATETIME NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         CHAR (30)     NOT NULL,
    [User4]         CHAR (30)     NOT NULL,
    [User5]         FLOAT (53)    NOT NULL,
    [User6]         FLOAT (53)    NOT NULL,
    [User7]         CHAR (10)     NOT NULL,
    [User8]         CHAR (10)     NOT NULL,
    [User9]         SMALLDATETIME NOT NULL,
    [Volume]        FLOAT (53)    NOT NULL,
    [Wght]          FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SHShipPack0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [ShipperID] ASC, [BoxRef] ASC) WITH (FILLFACTOR = 90)
);

