CREATE TABLE [dbo].[smModPMBase] (
    [BasePrice]      FLOAT (53)    NOT NULL,
    [ContractTypeId] CHAR (10)     NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Descr]          CHAR (30)     NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [ManufId]        CHAR (10)     NOT NULL,
    [ModelId]        CHAR (40)     NOT NULL,
    [NoteID]         INT           NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [smModPMBase0] PRIMARY KEY CLUSTERED ([ManufId] ASC, [ModelId] ASC, [ContractTypeId] ASC) WITH (FILLFACTOR = 90)
);

