CREATE TABLE [dbo].[xContract] (
    [ChkOffNeed]    SMALLINT      NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CtrctDate]     SMALLDATETIME NOT NULL,
    [CtrctNbr]      CHAR (10)     NOT NULL,
    [DelivDate]     SMALLDATETIME NOT NULL,
    [DmgKey]        CHAR (2)      NOT NULL,
    [FrtRate]       FLOAT (53)    NOT NULL,
    [FwdFlg]        SMALLINT      NOT NULL,
    [GrossPrice]    FLOAT (53)    NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [MstKey]        CHAR (2)      NOT NULL,
    [NetPrice]      FLOAT (53)    NOT NULL,
    [NoteId]        INT           NOT NULL,
    [Qty]           FLOAT (53)    NOT NULL,
    [Seller]        CHAR (15)     NOT NULL,
    [Status]        CHAR (1)      NOT NULL,
    [TWKey]         CHAR (2)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (10)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NULL,
    CONSTRAINT [xContract0] PRIMARY KEY CLUSTERED ([CtrctNbr] ASC) WITH (FILLFACTOR = 90)
);

