CREATE TABLE [dbo].[ar08600_wrk] (
    [RI_ID]                SMALLINT      NULL,
    [RecordID]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CpnyID]               CHAR (10)     NULL,
    [CuryDocBal]           FLOAT (53)    NULL,
    [CuryID]               CHAR (4)      NULL,
    [CuryOrigDocAmt]       FLOAT (53)    NULL,
    [CuryStmtBal]          FLOAT (53)    NULL,
    [CustID]               CHAR (15)     NOT NULL,
    [DocBal]               FLOAT (53)    NULL,
    [DocClass]             CHAR (1)      NULL,
    [DocDate]              SMALLDATETIME NULL,
    [DocDesc]              CHAR (30)     NULL,
    [DocType]              CHAR (2)      NULL,
    [OrigDocAmt]           FLOAT (53)    NULL,
    [RefNbr]               CHAR (10)     NULL,
    [Rlsed]                SMALLINT      NULL,
    [StmtBal]              FLOAT (53)    NULL,
    [StmtDate]             SMALLDATETIME NULL,
    [Customer_AgeBal01]    FLOAT (53)    NULL,
    [Customer_AgeBal02]    FLOAT (53)    NULL,
    [Customer_AgeBal03]    FLOAT (53)    NULL,
    [Customer_AgeBal04]    FLOAT (53)    NULL,
    [Customer_BillAddr1]   CHAR (60)     NOT NULL,
    [Customer_BillAddr2]   CHAR (60)     NOT NULL,
    [Customer_BillAttn]    CHAR (30)     NULL,
    [Customer_BillCity]    CHAR (30)     NULL,
    [Customer_BillCountry] CHAR (3)      NULL,
    [Customer_BillName]    CHAR (60)     NOT NULL,
    [Customer_BillState]   CHAR (3)      NULL,
    [Customer_BillZip]     CHAR (10)     NULL,
    [Customer_DunMsg]      SMALLINT      NULL,
    [Cust_TotStmtBal]      FLOAT (53)    NULL,
    [Cust_LastStmtBal00]   FLOAT (53)    NULL,
    [Cust_LastStmtBal01]   FLOAT (53)    NULL,
    [Cust_LastStmtBal02]   FLOAT (53)    NULL,
    [Cust_LastStmtBal03]   FLOAT (53)    NULL,
    [Cust_LastStmtBal04]   FLOAT (53)    NULL,
    [Cust_LastStmtBegBal]  FLOAT (53)    NULL,
    [Cust_LastStmtDate]    SMALLDATETIME NULL,
    [Customer_PrtStmt]     SMALLINT      NULL,
    [Customer_StmtCycleID] CHAR (2)      NOT NULL,
    [Customer_StmtType]    CHAR (1)      NULL,
    [ARAdjust_AdjgDocType] CHAR (2)      NULL,
    [ARAdjust_AdjgRefNbr]  CHAR (10)     NULL,
    [ARAdjust_AdjAmt]      FLOAT (53)    NULL,
    [ARAdjust_AdjDiscAmt]  FLOAT (53)    NULL,
    [ARAdjust_CuryAdjDAmt] FLOAT (53)    NULL,
    [ARAdj_CuryAdjDiscAmt] FLOAT (53)    NULL,
    [ARAdjust_CustId]      CHAR (15)     NULL,
    [CountryC_Descr]       CHAR (30)     NULL,
    [CountryB_Descr]       CHAR (30)     NULL,
    [ARStmt_AgeDays00]     SMALLINT      NULL,
    [ARStmt_AgeDays01]     SMALLINT      NULL,
    [ARStmt_AgeDays02]     SMALLINT      NULL,
    [ARStmt_AgeMsg00]      CHAR (50)     NULL,
    [ARStmt_AgeMsg01]      CHAR (50)     NULL,
    [ARStmt_AgeMsg02]      CHAR (50)     NULL,
    [ARStmt_AgeMsg03]      CHAR (50)     NULL,
    [ARStmt_LastStmtDate]  SMALLDATETIME NULL,
    [ARDoc1_DocDate]       SMALLDATETIME NULL,
    [ARDoc1_DocType]       CHAR (2)      NULL,
    [ARDoc1_RefNbr]        CHAR (10)     NULL,
    [ARDoc1_StmtDate]      SMALLDATETIME NULL,
    [ASID]                 INT           NULL,
    [PerQSent]             CHAR (6)      NULL,
    [WSID]                 INT           NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [AR08600_Wrk0] PRIMARY KEY CLUSTERED ([RecordID] ASC, [CustID] ASC, [Customer_StmtCycleID] ASC) WITH (FILLFACTOR = 90)
);

