CREATE TABLE [dbo].[CSStatement] (
    [BatNbr]         CHAR (10)     CONSTRAINT [DF_CSStatement_BatNbr] DEFAULT (' ') NOT NULL,
    [CommPerNbr]     CHAR (6)      CONSTRAINT [DF_CSStatement_CommPerNbr] DEFAULT (' ') NOT NULL,
    [CpnyID]         CHAR (10)     CONSTRAINT [DF_CSStatement_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME CONSTRAINT [DF_CSStatement_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]      CHAR (8)      CONSTRAINT [DF_CSStatement_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]      CHAR (10)     CONSTRAINT [DF_CSStatement_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryEffDate]    SMALLDATETIME CONSTRAINT [DF_CSStatement_CuryEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryID]         CHAR (4)      CONSTRAINT [DF_CSStatement_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]    CHAR (1)      CONSTRAINT [DF_CSStatement_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]       FLOAT (53)    CONSTRAINT [DF_CSStatement_CuryRate] DEFAULT ((0)) NOT NULL,
    [CuryRateType]   CHAR (6)      CONSTRAINT [DF_CSStatement_CuryRateType] DEFAULT (' ') NOT NULL,
    [CuryStmntTotal] FLOAT (53)    CONSTRAINT [DF_CSStatement_CuryStmntTotal] DEFAULT ((0)) NOT NULL,
    [CycleID]        CHAR (10)     CONSTRAINT [DF_CSStatement_CycleID] DEFAULT (' ') NOT NULL,
    [DrawAmt]        FLOAT (53)    CONSTRAINT [DF_CSStatement_DrawAmt] DEFAULT ((0)) NOT NULL,
    [DrawRecover]    FLOAT (53)    CONSTRAINT [DF_CSStatement_DrawRecover] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME CONSTRAINT [DF_CSStatement_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]      CHAR (8)      CONSTRAINT [DF_CSStatement_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]      CHAR (10)     CONSTRAINT [DF_CSStatement_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]         INT           CONSTRAINT [DF_CSStatement_NoteID] DEFAULT ((0)) NOT NULL,
    [PerNbr]         CHAR (6)      CONSTRAINT [DF_CSStatement_PerNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]     CHAR (30)     CONSTRAINT [DF_CSStatement_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]     CHAR (30)     CONSTRAINT [DF_CSStatement_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]     FLOAT (53)    CONSTRAINT [DF_CSStatement_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]     FLOAT (53)    CONSTRAINT [DF_CSStatement_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]     FLOAT (53)    CONSTRAINT [DF_CSStatement_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]     FLOAT (53)    CONSTRAINT [DF_CSStatement_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]     SMALLDATETIME CONSTRAINT [DF_CSStatement_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]     SMALLDATETIME CONSTRAINT [DF_CSStatement_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]     INT           CONSTRAINT [DF_CSStatement_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]     INT           CONSTRAINT [DF_CSStatement_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]     CHAR (10)     CONSTRAINT [DF_CSStatement_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]     CHAR (10)     CONSTRAINT [DF_CSStatement_S4Future12] DEFAULT (' ') NOT NULL,
    [SlsperID]       CHAR (10)     CONSTRAINT [DF_CSStatement_SlsperID] DEFAULT (' ') NOT NULL,
    [Status]         CHAR (1)      CONSTRAINT [DF_CSStatement_Status] DEFAULT (' ') NOT NULL,
    [StmntDate]      SMALLDATETIME CONSTRAINT [DF_CSStatement_StmntDate] DEFAULT ('01/01/1900') NOT NULL,
    [StmntFormat]    CHAR (10)     CONSTRAINT [DF_CSStatement_StmntFormat] DEFAULT (' ') NOT NULL,
    [StmntID]        CHAR (10)     CONSTRAINT [DF_CSStatement_StmntID] DEFAULT (' ') NOT NULL,
    [StmntTotal]     FLOAT (53)    CONSTRAINT [DF_CSStatement_StmntTotal] DEFAULT ((0)) NOT NULL,
    [TranCntr]       SMALLINT      CONSTRAINT [DF_CSStatement_TranCntr] DEFAULT ((0)) NOT NULL,
    [User1]          CHAR (30)     CONSTRAINT [DF_CSStatement_User1] DEFAULT (' ') NOT NULL,
    [User10]         SMALLDATETIME CONSTRAINT [DF_CSStatement_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]          CHAR (30)     CONSTRAINT [DF_CSStatement_User2] DEFAULT (' ') NOT NULL,
    [User3]          CHAR (30)     CONSTRAINT [DF_CSStatement_User3] DEFAULT (' ') NOT NULL,
    [User4]          CHAR (30)     CONSTRAINT [DF_CSStatement_User4] DEFAULT (' ') NOT NULL,
    [User5]          FLOAT (53)    CONSTRAINT [DF_CSStatement_User5] DEFAULT ((0)) NOT NULL,
    [User6]          FLOAT (53)    CONSTRAINT [DF_CSStatement_User6] DEFAULT ((0)) NOT NULL,
    [User7]          CHAR (10)     CONSTRAINT [DF_CSStatement_User7] DEFAULT (' ') NOT NULL,
    [User8]          CHAR (10)     CONSTRAINT [DF_CSStatement_User8] DEFAULT (' ') NOT NULL,
    [User9]          SMALLDATETIME CONSTRAINT [DF_CSStatement_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [CSStatement0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [SlsperID] ASC, [CycleID] ASC, [CommPerNbr] ASC) WITH (FILLFACTOR = 90)
);

