CREATE TABLE [dbo].[cftPGDateSum] (
    [Capacity]       INT           NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Company]        CHAR (10)     NOT NULL,
    [CurrentInv]     INT           NOT NULL,
    [DataDate]       SMALLDATETIME NOT NULL,
    [DeadtoDate]     INT           NOT NULL,
    [FacilityType]   CHAR (30)     NOT NULL,
    [FeedLbs]        FLOAT (53)    NOT NULL,
    [GenderTypeID]   CHAR (6)      NOT NULL,
    [GroupDesc]      CHAR (30)     NOT NULL,
    [InvtoDate]      INT           NOT NULL,
    [LastFeed]       SMALLDATETIME NOT NULL,
    [LastSale]       SMALLDATETIME NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [MarketMgr]      CHAR (50)     NOT NULL,
    [NextMarketDate] SMALLDATETIME NOT NULL,
    [Ownership]      CHAR (30)     NOT NULL,
    [PigGroupID]     CHAR (10)     NOT NULL,
    [Phase]          CHAR (30)     NOT NULL,
    [SalestoDate]    INT           NOT NULL,
    [SalesWgt]       FLOAT (53)    NOT NULL,
    [SiteName]       CHAR (50)     NOT NULL,
    [StartDate]      SMALLDATETIME NOT NULL,
    [StartQty]       INT           NOT NULL,
    [StartWgt]       FLOAT (53)    NOT NULL,
    [State]          CHAR (3)      NOT NULL,
    [Status]         CHAR (30)     NOT NULL,
    [SvcMgr]         CHAR (50)     NOT NULL,
    [tstamp]         ROWVERSION    NULL
);

