CREATE TABLE [dbo].[EDPurchOrd] (
    [AcctNbr]         CHAR (35)     CONSTRAINT [DF_EDPurchOrd_AcctNbr] DEFAULT (' ') NOT NULL,
    [AgreeNbr]        CHAR (35)     CONSTRAINT [DF_EDPurchOrd_AgreeNbr] DEFAULT (' ') NOT NULL,
    [ArrivalDate]     SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ArrivalDate] DEFAULT ('01/01/1900') NOT NULL,
    [BackOrderFlag]   SMALLINT      CONSTRAINT [DF_EDPurchOrd_BackOrderFlag] DEFAULT ((0)) NOT NULL,
    [BatchNbr]        CHAR (35)     CONSTRAINT [DF_EDPurchOrd_BatchNbr] DEFAULT (' ') NOT NULL,
    [BidNbr]          CHAR (35)     CONSTRAINT [DF_EDPurchOrd_BidNbr] DEFAULT (' ') NOT NULL,
    [CancelDate]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_CancelDate] DEFAULT ('01/01/1900') NOT NULL,
    [ChangeNbr]       CHAR (35)     CONSTRAINT [DF_EDPurchOrd_ChangeNbr] DEFAULT (' ') NOT NULL,
    [ContractNbr]     CHAR (35)     CONSTRAINT [DF_EDPurchOrd_ContractNbr] DEFAULT (' ') NOT NULL,
    [ConvertedDate]   SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ConvertedDate] DEFAULT ('01/01/1900') NOT NULL,
    [CreationDate]    SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_CreationDate] DEFAULT ('01/01/1900') NOT NULL,
    [CrossDock]       CHAR (20)     CONSTRAINT [DF_EDPurchOrd_CrossDock] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      CONSTRAINT [DF_EDPurchOrd_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     CONSTRAINT [DF_EDPurchOrd_Crtd_User] DEFAULT (' ') NOT NULL,
    [DeliveryDate]    SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_DeliveryDate] DEFAULT ('01/01/1900') NOT NULL,
    [DeptNbr]         CHAR (35)     CONSTRAINT [DF_EDPurchOrd_DeptNbr] DEFAULT (' ') NOT NULL,
    [DistributorNbr]  CHAR (35)     CONSTRAINT [DF_EDPurchOrd_DistributorNbr] DEFAULT (' ') NOT NULL,
    [EffDate]         SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_EffDate] DEFAULT ('01/01/1900') NOT NULL,
    [EndCustPackNbr]  CHAR (30)     CONSTRAINT [DF_EDPurchOrd_EndCustPackNbr] DEFAULT (' ') NOT NULL,
    [EndCustPODate]   SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_EndCustPODate] DEFAULT ('01/01/1900') NOT NULL,
    [EndCustPONbr]    CHAR (30)     CONSTRAINT [DF_EDPurchOrd_EndCustPONbr] DEFAULT (' ') NOT NULL,
    [EndCustSONbr]    CHAR (30)     CONSTRAINT [DF_EDPurchOrd_EndCustSONbr] DEFAULT (' ') NOT NULL,
    [ExpirDate]       SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ExpirDate] DEFAULT ('01/01/1900') NOT NULL,
    [FOBLocQual]      CHAR (2)      CONSTRAINT [DF_EDPurchOrd_FOBLocQual] DEFAULT (' ') NOT NULL,
    [Height]          FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]       CHAR (6)      CONSTRAINT [DF_EDPurchOrd_HeightUOM] DEFAULT (' ') NOT NULL,
    [LastEDIDate]     SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_LastEDIDate] DEFAULT ('01/01/1900') NOT NULL,
    [Len]             FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]          CHAR (6)      CONSTRAINT [DF_EDPurchOrd_LenUOM] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]   SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]       CHAR (8)      CONSTRAINT [DF_EDPurchOrd_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]       CHAR (10)     CONSTRAINT [DF_EDPurchOrd_Lupd_User] DEFAULT (' ') NOT NULL,
    [NbrContainer]    SMALLINT      CONSTRAINT [DF_EDPurchOrd_NbrContainer] DEFAULT ((0)) NOT NULL,
    [OutboundProcNbr] CHAR (10)     CONSTRAINT [DF_EDPurchOrd_OutboundProcNbr] DEFAULT (' ') NOT NULL,
    [PONbr]           CHAR (10)     CONSTRAINT [DF_EDPurchOrd_PONbr] DEFAULT (' ') NOT NULL,
    [POSuff]          CHAR (35)     CONSTRAINT [DF_EDPurchOrd_POSuff] DEFAULT (' ') NOT NULL,
    [PromoEndDate]    SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_PromoEndDate] DEFAULT ('01/01/1900') NOT NULL,
    [PromoNbr]        CHAR (35)     CONSTRAINT [DF_EDPurchOrd_PromoNbr] DEFAULT (' ') NOT NULL,
    [PromoStartDate]  SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_PromoStartDate] DEFAULT ('01/01/1900') NOT NULL,
    [PurReqNbr]       CHAR (35)     CONSTRAINT [DF_EDPurchOrd_PurReqNbr] DEFAULT (' ') NOT NULL,
    [QuoteNbr]        CHAR (35)     CONSTRAINT [DF_EDPurchOrd_QuoteNbr] DEFAULT (' ') NOT NULL,
    [RequestDate]     SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_RequestDate] DEFAULT ('01/01/1900') NOT NULL,
    [Routing]         CHAR (50)     CONSTRAINT [DF_EDPurchOrd_Routing] DEFAULT (' ') NOT NULL,
    [RoutingIDCode]   CHAR (80)     CONSTRAINT [DF_EDPurchOrd_RoutingIDCode] DEFAULT (' ') NOT NULL,
    [RoutingIDQual]   CHAR (3)      CONSTRAINT [DF_EDPurchOrd_RoutingIDQual] DEFAULT (' ') NOT NULL,
    [RoutingSeqCode]  CHAR (3)      CONSTRAINT [DF_EDPurchOrd_RoutingSeqCode] DEFAULT (' ') NOT NULL,
    [S4Future01]      CHAR (30)     CONSTRAINT [DF_EDPurchOrd_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]      CHAR (30)     CONSTRAINT [DF_EDPurchOrd_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]      FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]      FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]      FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]      FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]      INT           CONSTRAINT [DF_EDPurchOrd_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]      INT           CONSTRAINT [DF_EDPurchOrd_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]      CHAR (10)     CONSTRAINT [DF_EDPurchOrd_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]      CHAR (10)     CONSTRAINT [DF_EDPurchOrd_S4Future12] DEFAULT (' ') NOT NULL,
    [SalesDivision]   CHAR (30)     CONSTRAINT [DF_EDPurchOrd_SalesDivision] DEFAULT (' ') NOT NULL,
    [Salesman]        CHAR (30)     CONSTRAINT [DF_EDPurchOrd_Salesman] DEFAULT (' ') NOT NULL,
    [SalesRegion]     CHAR (30)     CONSTRAINT [DF_EDPurchOrd_SalesRegion] DEFAULT (' ') NOT NULL,
    [SalesTerritory]  CHAR (30)     CONSTRAINT [DF_EDPurchOrd_SalesTerritory] DEFAULT (' ') NOT NULL,
    [ScheduleDate]    SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ScheduleDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipDate]        SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ShipDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipMthPay]      CHAR (2)      CONSTRAINT [DF_EDPurchOrd_ShipMthPay] DEFAULT (' ') NOT NULL,
    [ShipNBDate]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ShipNBDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipNLDate]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ShipNLDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipWeekOf]      SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_ShipWeekOf] DEFAULT ('01/01/1900') NOT NULL,
    [TranMethCode]    CHAR (3)      CONSTRAINT [DF_EDPurchOrd_TranMethCode] DEFAULT (' ') NOT NULL,
    [User1]           CHAR (30)     CONSTRAINT [DF_EDPurchOrd_User1] DEFAULT (' ') NOT NULL,
    [User10]          SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]           CHAR (30)     CONSTRAINT [DF_EDPurchOrd_User2] DEFAULT (' ') NOT NULL,
    [User3]           CHAR (30)     CONSTRAINT [DF_EDPurchOrd_User3] DEFAULT (' ') NOT NULL,
    [User4]           CHAR (30)     CONSTRAINT [DF_EDPurchOrd_User4] DEFAULT (' ') NOT NULL,
    [User5]           FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_User5] DEFAULT ((0)) NOT NULL,
    [User6]           FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_User6] DEFAULT ((0)) NOT NULL,
    [User7]           CHAR (10)     CONSTRAINT [DF_EDPurchOrd_User7] DEFAULT (' ') NOT NULL,
    [User8]           CHAR (10)     CONSTRAINT [DF_EDPurchOrd_User8] DEFAULT (' ') NOT NULL,
    [User9]           SMALLDATETIME CONSTRAINT [DF_EDPurchOrd_User9] DEFAULT ('01/01/1900') NOT NULL,
    [Volume]          FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_Volume] DEFAULT ((0)) NOT NULL,
    [VolumeUOM]       CHAR (6)      CONSTRAINT [DF_EDPurchOrd_VolumeUOM] DEFAULT (' ') NOT NULL,
    [Weight]          FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]       CHAR (6)      CONSTRAINT [DF_EDPurchOrd_WeightUOM] DEFAULT (' ') NOT NULL,
    [Width]           FLOAT (53)    CONSTRAINT [DF_EDPurchOrd_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]        CHAR (6)      CONSTRAINT [DF_EDPurchOrd_WidthUOM] DEFAULT (' ') NOT NULL,
    [WONbr]           CHAR (30)     CONSTRAINT [DF_EDPurchOrd_WONbr] DEFAULT (' ') NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [EDPurchOrd0] PRIMARY KEY CLUSTERED ([PONbr] ASC) WITH (FILLFACTOR = 90)
);

