CREATE TABLE [dbo].[APHist] (
    [BegBal]         FLOAT (53)    NOT NULL,
    [CpnyID]         CHAR (10)     NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [CuryID]         CHAR (4)      NOT NULL,
    [FiscYr]         CHAR (4)      NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [NoteID]         INT           NOT NULL,
    [PerNbr]         CHAR (6)      NOT NULL,
    [PtdBkupWthld00] FLOAT (53)    NOT NULL,
    [PtdBkupWthld01] FLOAT (53)    NOT NULL,
    [PtdBkupWthld02] FLOAT (53)    NOT NULL,
    [PtdBkupWthld03] FLOAT (53)    NOT NULL,
    [PtdBkupWthld04] FLOAT (53)    NOT NULL,
    [PtdBkupWthld05] FLOAT (53)    NOT NULL,
    [PtdBkupWthld06] FLOAT (53)    NOT NULL,
    [PtdBkupWthld07] FLOAT (53)    NOT NULL,
    [PtdBkupWthld08] FLOAT (53)    NOT NULL,
    [PtdBkupWthld09] FLOAT (53)    NOT NULL,
    [PtdBkupWthld10] FLOAT (53)    NOT NULL,
    [PtdBkupWthld11] FLOAT (53)    NOT NULL,
    [PtdBkupWthld12] FLOAT (53)    NOT NULL,
    [PtdCrAdjs00]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs01]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs02]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs03]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs04]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs05]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs06]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs07]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs08]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs09]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs10]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs11]    FLOAT (53)    NOT NULL,
    [PtdCrAdjs12]    FLOAT (53)    NOT NULL,
    [PtdDiscTkn00]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn01]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn02]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn03]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn04]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn05]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn06]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn07]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn08]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn09]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn10]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn11]   FLOAT (53)    NOT NULL,
    [PtdDiscTkn12]   FLOAT (53)    NOT NULL,
    [PtdDrAdjs00]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs01]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs02]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs03]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs04]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs05]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs06]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs07]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs08]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs09]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs10]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs11]    FLOAT (53)    NOT NULL,
    [PtdDrAdjs12]    FLOAT (53)    NOT NULL,
    [PtdPaymt00]     FLOAT (53)    NOT NULL,
    [PtdPaymt01]     FLOAT (53)    NOT NULL,
    [PtdPaymt02]     FLOAT (53)    NOT NULL,
    [PtdPaymt03]     FLOAT (53)    NOT NULL,
    [PtdPaymt04]     FLOAT (53)    NOT NULL,
    [PtdPaymt05]     FLOAT (53)    NOT NULL,
    [PtdPaymt06]     FLOAT (53)    NOT NULL,
    [PtdPaymt07]     FLOAT (53)    NOT NULL,
    [PtdPaymt08]     FLOAT (53)    NOT NULL,
    [PtdPaymt09]     FLOAT (53)    NOT NULL,
    [PtdPaymt10]     FLOAT (53)    NOT NULL,
    [PtdPaymt11]     FLOAT (53)    NOT NULL,
    [PtdPaymt12]     FLOAT (53)    NOT NULL,
    [PtdPurch00]     FLOAT (53)    NOT NULL,
    [PtdPurch01]     FLOAT (53)    NOT NULL,
    [PtdPurch02]     FLOAT (53)    NOT NULL,
    [PtdPurch03]     FLOAT (53)    NOT NULL,
    [PtdPurch04]     FLOAT (53)    NOT NULL,
    [PtdPurch05]     FLOAT (53)    NOT NULL,
    [PtdPurch06]     FLOAT (53)    NOT NULL,
    [PtdPurch07]     FLOAT (53)    NOT NULL,
    [PtdPurch08]     FLOAT (53)    NOT NULL,
    [PtdPurch09]     FLOAT (53)    NOT NULL,
    [PtdPurch10]     FLOAT (53)    NOT NULL,
    [PtdPurch11]     FLOAT (53)    NOT NULL,
    [PtdPurch12]     FLOAT (53)    NOT NULL,
    [S4Future01]     CHAR (30)     NOT NULL,
    [S4Future02]     CHAR (30)     NOT NULL,
    [S4Future03]     FLOAT (53)    NOT NULL,
    [S4Future04]     FLOAT (53)    NOT NULL,
    [S4Future05]     FLOAT (53)    NOT NULL,
    [S4Future06]     FLOAT (53)    NOT NULL,
    [S4Future07]     SMALLDATETIME NOT NULL,
    [S4Future08]     SMALLDATETIME NOT NULL,
    [S4Future09]     INT           NOT NULL,
    [S4Future10]     INT           NOT NULL,
    [S4Future11]     CHAR (10)     NOT NULL,
    [S4Future12]     CHAR (10)     NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [VendId]         CHAR (15)     NOT NULL,
    [YtdBkupWthld]   FLOAT (53)    NOT NULL,
    [YtdCrAdjs]      FLOAT (53)    NOT NULL,
    [YtdDiscTkn]     FLOAT (53)    NOT NULL,
    [YtdDrAdjs]      FLOAT (53)    NOT NULL,
    [YtdPaymt]       FLOAT (53)    NOT NULL,
    [YtdPurch]       FLOAT (53)    NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [APHist0] PRIMARY KEY CLUSTERED ([VendId] ASC, [CpnyID] ASC, [FiscYr] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE NONCLUSTERED INDEX [APHist1]
    ON [dbo].[APHist]([PerNbr] ASC);


GO
CREATE NONCLUSTERED INDEX [APHist2]
    ON [dbo].[APHist]([VendId] ASC, [PerNbr] ASC);

