CREATE TABLE [dbo].[RQVendEval] (
    [Addr1]         CHAR (60)     NOT NULL,
    [Addr2]         CHAR (60)     NOT NULL,
    [Attn]          CHAR (30)     NOT NULL,
    [City]          CHAR (30)     NOT NULL,
    [Comment]       CHAR (60)     NOT NULL,
    [Country]       CHAR (3)      NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [Email]         CHAR (80)     NOT NULL,
    [Fax]           CHAR (30)     NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [Name]          CHAR (60)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [Output]        CHAR (1)      NOT NULL,
    [Phone]         CHAR (30)     NOT NULL,
    [QuoteAmt]      FLOAT (53)    NOT NULL,
    [QuoteNbr]      CHAR (10)     NOT NULL,
    [ReqNbr]        CHAR (10)     NOT NULL,
    [S4Future1]     CHAR (30)     NOT NULL,
    [S4Future2]     CHAR (30)     NOT NULL,
    [S4Future3]     FLOAT (53)    NOT NULL,
    [S4Future4]     FLOAT (53)    NOT NULL,
    [S4Future5]     FLOAT (53)    NOT NULL,
    [S4Future6]     FLOAT (53)    NOT NULL,
    [S4Future7]     SMALLDATETIME NOT NULL,
    [S4Future8]     SMALLDATETIME NOT NULL,
    [S4Future9]     INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [State]         CHAR (3)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [VendID]        CHAR (15)     NOT NULL,
    [VOC]           CHAR (1)      NOT NULL,
    [Zip]           CHAR (10)     NOT NULL,
    [zzCommentText] TEXT          NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RQVendEval0]
    ON [dbo].[RQVendEval]([ReqNbr] ASC, [Name] ASC, [VendID] ASC);

