CREATE TABLE [dbo].[BRHeader] (
    [AcctID]          CHAR (10)     NOT NULL,
    [BankCleared]     FLOAT (53)    NOT NULL,
    [BankOS]          FLOAT (53)    NOT NULL,
    [BBBegBal]        FLOAT (53)    NOT NULL,
    [BBChkClrd]       FLOAT (53)    NOT NULL,
    [BBDepClrd]       FLOAT (53)    NOT NULL,
    [BBDiff]          FLOAT (53)    NOT NULL,
    [BBEndBalC]       FLOAT (53)    NOT NULL,
    [BBEndBalS]       FLOAT (53)    NOT NULL,
    [CBankBal]        FLOAT (53)    NOT NULL,
    [CGLBal]          FLOAT (53)    NOT NULL,
    [CpnyId]          CHAR (10)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [CuryBankCleared] FLOAT (53)    NOT NULL,
    [CuryBankOS]      FLOAT (53)    NOT NULL,
    [CuryBBBegBal]    FLOAT (53)    NOT NULL,
    [CuryBBChkClrd]   FLOAT (53)    NOT NULL,
    [CuryBBDepClrd]   FLOAT (53)    NOT NULL,
    [CuryBBDiff]      FLOAT (53)    NOT NULL,
    [CuryBBEndBalC]   FLOAT (53)    NOT NULL,
    [CuryBBEndBalS]   FLOAT (53)    NOT NULL,
    [CuryCBankBal]    FLOAT (53)    NOT NULL,
    [CuryCGLBal]      FLOAT (53)    NOT NULL,
    [CuryId]          CHAR (4)      NOT NULL,
    [CuryGLAcctBal]   FLOAT (53)    NOT NULL,
    [CuryGLChkClrd]   FLOAT (53)    NOT NULL,
    [CuryGLCleared]   FLOAT (53)    NOT NULL,
    [CuryGLDepClrd]   FLOAT (53)    NOT NULL,
    [CuryGLDiff]      FLOAT (53)    NOT NULL,
    [CuryGLEndBalC]   FLOAT (53)    NOT NULL,
    [CuryGLEndBalS]   FLOAT (53)    NOT NULL,
    [CuryGLOS]        FLOAT (53)    NOT NULL,
    [CuryMultDiv]     CHAR (1)      NOT NULL,
    [CuryRate]        FLOAT (53)    NOT NULL,
    [CuryRBankBal]    FLOAT (53)    NOT NULL,
    [CuryRGLBal]      FLOAT (53)    NOT NULL,
    [FutureC1]        CHAR (30)     NOT NULL,
    [FutureC2]        CHAR (10)     NOT NULL,
    [FutureD1]        SMALLDATETIME NOT NULL,
    [FutureF1]        FLOAT (53)    NOT NULL,
    [FutureI1]        INT           NOT NULL,
    [FutureL1]        SMALLINT      NOT NULL,
    [GLAcctBal]       FLOAT (53)    NOT NULL,
    [GLChkClrd]       FLOAT (53)    NOT NULL,
    [GLCleared]       FLOAT (53)    NOT NULL,
    [GLDepClrd]       FLOAT (53)    NOT NULL,
    [GLDiff]          FLOAT (53)    NOT NULL,
    [GLEndBalC]       FLOAT (53)    NOT NULL,
    [GLEndBalS]       FLOAT (53)    NOT NULL,
    [GLOS]            FLOAT (53)    NOT NULL,
    [NoteID]          INT           NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [RBankBal]        FLOAT (53)    NOT NULL,
    [ReconPerNbr]     CHAR (6)      NOT NULL,
    [RGLBal]          FLOAT (53)    NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [SetUpID]         CHAR (4)      NOT NULL,
    [UserC1]          CHAR (30)     NOT NULL,
    [UserC2]          CHAR (30)     NOT NULL,
    [UserC3]          CHAR (10)     NOT NULL,
    [UserC4]          CHAR (10)     NOT NULL,
    [UserD1]          SMALLDATETIME NOT NULL,
    [UserD2]          SMALLDATETIME NOT NULL,
    [UserF1]          FLOAT (53)    NOT NULL,
    [UserF2]          FLOAT (53)    NOT NULL,
    [UserI1]          INT           NOT NULL,
    [UserI2]          INT           NOT NULL,
    [UserL1]          SMALLINT      NOT NULL,
    [UserL2]          SMALLINT      NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [BRHeader0] PRIMARY KEY CLUSTERED ([CpnyId] ASC, [AcctID] ASC, [ReconPerNbr] ASC) WITH (FILLFACTOR = 90)
);

