CREATE TABLE [dbo].[BOMDoc] (
    [AssyQty]            FLOAT (53)    CONSTRAINT [DF_BOMDoc_AssyQty] DEFAULT ((0)) NOT NULL,
    [BatNbr]             CHAR (10)     CONSTRAINT [DF_BOMDoc_BatNbr] DEFAULT (' ') NOT NULL,
    [BOMSiteID]          CHAR (10)     CONSTRAINT [DF_BOMDoc_BOMSiteID] DEFAULT (' ') NOT NULL,
    [CnvFact]            FLOAT (53)    CONSTRAINT [DF_BOMDoc_CnvFact] DEFAULT ((0)) NOT NULL,
    [CpnyID]             CHAR (10)     CONSTRAINT [DF_BOMDoc_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME CONSTRAINT [DF_BOMDoc_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_BOMDoc_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_BOMDoc_Crtd_User] DEFAULT (' ') NOT NULL,
    [Descr]              CHAR (30)     CONSTRAINT [DF_BOMDoc_Descr] DEFAULT (' ') NOT NULL,
    [DirLbrAmt]          FLOAT (53)    CONSTRAINT [DF_BOMDoc_DirLbrAmt] DEFAULT ((0)) NOT NULL,
    [DirMatlAmt]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_DirMatlAmt] DEFAULT ((0)) NOT NULL,
    [DirOthAmt]          FLOAT (53)    CONSTRAINT [DF_BOMDoc_DirOthAmt] DEFAULT ((0)) NOT NULL,
    [DocType]            CHAR (1)      CONSTRAINT [DF_BOMDoc_DocType] DEFAULT (' ') NOT NULL,
    [EffLbrOvhVarAmt]    FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffLbrOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [EffLbrVarAmt]       FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffLbrVarAmt] DEFAULT ((0)) NOT NULL,
    [EffMachOvhVarAmt]   FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffMachOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [EffMatlOvhVarAmt]   FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffMatlOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [EffMatlVarAmt]      FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffMatlVarAmt] DEFAULT ((0)) NOT NULL,
    [EffOthVarAmt]       FLOAT (53)    CONSTRAINT [DF_BOMDoc_EffOthVarAmt] DEFAULT ((0)) NOT NULL,
    [InBal]              CHAR (1)      CONSTRAINT [DF_BOMDoc_InBal] DEFAULT (' ') NOT NULL,
    [KitCntr]            FLOAT (53)    CONSTRAINT [DF_BOMDoc_KitCntr] DEFAULT ((0)) NOT NULL,
    [KitID]              CHAR (30)     CONSTRAINT [DF_BOMDoc_KitID] DEFAULT (' ') NOT NULL,
    [LotSerNbr]          CHAR (25)     CONSTRAINT [DF_BOMDoc_LotSerNbr] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME CONSTRAINT [DF_BOMDoc_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      CONSTRAINT [DF_BOMDoc_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]          CHAR (10)     CONSTRAINT [DF_BOMDoc_LUpd_User] DEFAULT (' ') NOT NULL,
    [MCActivated]        SMALLINT      CONSTRAINT [DF_BOMDoc_MCActivated] DEFAULT ((0)) NOT NULL,
    [NoteID]             INT           CONSTRAINT [DF_BOMDoc_NoteID] DEFAULT ((0)) NOT NULL,
    [OrigRefNbr]         CHAR (10)     CONSTRAINT [DF_BOMDoc_OrigRefNbr] DEFAULT (' ') NOT NULL,
    [OvhLbrAmt]          FLOAT (53)    CONSTRAINT [DF_BOMDoc_OvhLbrAmt] DEFAULT ((0)) NOT NULL,
    [OvhMachAmt]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_OvhMachAmt] DEFAULT ((0)) NOT NULL,
    [OvhMatlAmt]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_OvhMatlAmt] DEFAULT ((0)) NOT NULL,
    [PerPost]            CHAR (6)      CONSTRAINT [DF_BOMDoc_PerPost] DEFAULT (' ') NOT NULL,
    [PlanID]             CHAR (6)      CONSTRAINT [DF_BOMDoc_PlanID] DEFAULT (' ') NOT NULL,
    [ProductionQuantity] FLOAT (53)    CONSTRAINT [DF_BOMDoc_ProductionQuantity] DEFAULT ((0)) NOT NULL,
    [ProductionUnit]     CHAR (6)      CONSTRAINT [DF_BOMDoc_ProductionUnit] DEFAULT (' ') NOT NULL,
    [RateLbrOvhVarAmt]   FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateLbrOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [RateLbrVarAmt]      FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateLbrVarAmt] DEFAULT ((0)) NOT NULL,
    [RateMachOvhVarAmt]  FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateMachOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [RateMatlOvhVarAmt]  FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateMatlOvhVarAmt] DEFAULT ((0)) NOT NULL,
    [RateMatlVarAmt]     FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateMatlVarAmt] DEFAULT ((0)) NOT NULL,
    [RateOthVarAmt]      FLOAT (53)    CONSTRAINT [DF_BOMDoc_RateOthVarAmt] DEFAULT ((0)) NOT NULL,
    [RefNbr]             CHAR (10)     CONSTRAINT [DF_BOMDoc_RefNbr] DEFAULT (' ') NOT NULL,
    [Rlsed]              SMALLINT      CONSTRAINT [DF_BOMDoc_Rlsed] DEFAULT ((0)) NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_BOMDoc_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_BOMDoc_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_BOMDoc_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_BOMDoc_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_BOMDoc_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_BOMDoc_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_BOMDoc_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_BOMDoc_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]             CHAR (10)     CONSTRAINT [DF_BOMDoc_SiteID] DEFAULT (' ') NOT NULL,
    [SpecificCostID]     CHAR (25)     CONSTRAINT [DF_BOMDoc_SpecificCostID] DEFAULT (' ') NOT NULL,
    [Status]             CHAR (1)      CONSTRAINT [DF_BOMDoc_Status] DEFAULT (' ') NOT NULL,
    [StockUsage]         CHAR (1)      CONSTRAINT [DF_BOMDoc_StockUsage] DEFAULT (' ') NOT NULL,
    [TotTranAmt]         FLOAT (53)    CONSTRAINT [DF_BOMDoc_TotTranAmt] DEFAULT ((0)) NOT NULL,
    [TotVarAmt]          FLOAT (53)    CONSTRAINT [DF_BOMDoc_TotVarAmt] DEFAULT ((0)) NOT NULL,
    [TranDate]           SMALLDATETIME CONSTRAINT [DF_BOMDoc_TranDate] DEFAULT ('01/01/1900') NOT NULL,
    [TranType]           CHAR (2)      CONSTRAINT [DF_BOMDoc_TranType] DEFAULT (' ') NOT NULL,
    [UnitMultDiv]        CHAR (1)      CONSTRAINT [DF_BOMDoc_UnitMultDiv] DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_BOMDoc_User1] DEFAULT (' ') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_BOMDoc_User2] DEFAULT (' ') NOT NULL,
    [User3]              FLOAT (53)    CONSTRAINT [DF_BOMDoc_User3] DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    CONSTRAINT [DF_BOMDoc_User4] DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     CONSTRAINT [DF_BOMDoc_User5] DEFAULT (' ') NOT NULL,
    [User6]              CHAR (10)     CONSTRAINT [DF_BOMDoc_User6] DEFAULT (' ') NOT NULL,
    [User7]              SMALLDATETIME CONSTRAINT [DF_BOMDoc_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME CONSTRAINT [DF_BOMDoc_User8] DEFAULT ('01/01/1900') NOT NULL,
    [WhseLoc]            CHAR (10)     CONSTRAINT [DF_BOMDoc_WhseLoc] DEFAULT (' ') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [BOMDoc0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [RefNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [BOMDoc1]
    ON [dbo].[BOMDoc]([BatNbr] ASC, [KitID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [BOMDoc2]
    ON [dbo].[BOMDoc]([BatNbr] ASC, [RefNbr] ASC) WITH (FILLFACTOR = 90);

