CREATE TABLE [dbo].[CustContact] (
    [Addr1]         CHAR (60)     CONSTRAINT [DF_CustContact_Addr1] DEFAULT (' ') NOT NULL,
    [Addr2]         CHAR (60)     CONSTRAINT [DF_CustContact_Addr2] DEFAULT (' ') NOT NULL,
    [City]          CHAR (30)     CONSTRAINT [DF_CustContact_City] DEFAULT (' ') NOT NULL,
    [ContactID]     CHAR (10)     CONSTRAINT [DF_CustContact_ContactID] DEFAULT (' ') NOT NULL,
    [Country]       CHAR (3)      CONSTRAINT [DF_CustContact_Country] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustContact_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_CustContact_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_CustContact_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]        CHAR (15)     CONSTRAINT [DF_CustContact_CustID] DEFAULT (' ') NOT NULL,
    [EmailAddr]     CHAR (80)     CONSTRAINT [DF_CustContact_EmailAddr] DEFAULT (' ') NOT NULL,
    [Fax]           CHAR (30)     CONSTRAINT [DF_CustContact_Fax] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustContact_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_CustContact_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_CustContact_LUpd_User] DEFAULT (' ') NOT NULL,
    [Name]          CHAR (60)     CONSTRAINT [DF_CustContact_Name] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_CustContact_NoteID] DEFAULT ((0)) NOT NULL,
    [OrderLimit]    FLOAT (53)    CONSTRAINT [DF_CustContact_OrderLimit] DEFAULT ((0)) NOT NULL,
    [Phone]         CHAR (30)     CONSTRAINT [DF_CustContact_Phone] DEFAULT (' ') NOT NULL,
    [POReqdAmt]     FLOAT (53)    CONSTRAINT [DF_CustContact_POReqdAmt] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_CustContact_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_CustContact_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_CustContact_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_CustContact_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_CustContact_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_CustContact_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_CustContact_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_CustContact_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_CustContact_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_CustContact_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_CustContact_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_CustContact_S4Future12] DEFAULT (' ') NOT NULL,
    [Salut]         CHAR (30)     CONSTRAINT [DF_CustContact_Salut] DEFAULT (' ') NOT NULL,
    [State]         CHAR (3)      CONSTRAINT [DF_CustContact_State] DEFAULT (' ') NOT NULL,
    [Type]          CHAR (2)      CONSTRAINT [DF_CustContact_Type] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_CustContact_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_CustContact_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_CustContact_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_CustContact_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_CustContact_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_CustContact_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_CustContact_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_CustContact_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_CustContact_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_CustContact_User9] DEFAULT ('01/01/1900') NOT NULL,
    [WebSite]       CHAR (40)     CONSTRAINT [DF_CustContact_WebSite] DEFAULT (' ') NOT NULL,
    [Zip]           CHAR (10)     CONSTRAINT [DF_CustContact_Zip] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CustContact0] PRIMARY KEY CLUSTERED ([CustID] ASC, [ContactID] ASC) WITH (FILLFACTOR = 90)
);

