CREATE TABLE [dbo].[smFlatRate] (
    [BasePrice]           FLOAT (53)    NOT NULL,
    [BranchId]            CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [DatePrinted]         SMALLDATETIME NOT NULL,
    [EffectiveDate]       SMALLDATETIME NOT NULL,
    [FlatRateCategory]    CHAR (10)     NOT NULL,
    [FlatRateDesc]        CHAR (50)     NOT NULL,
    [FlatRateId]          CHAR (10)     NOT NULL,
    [FlatRateSubCategory] CHAR (10)     NOT NULL,
    [FlatRateType]        CHAR (1)      NOT NULL,
    [LaborWarranty]       SMALLINT      NOT NULL,
    [LaborWarrantyType]   CHAR (1)      NOT NULL,
    [LastUpdate]          SMALLDATETIME NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MarkupPercent]       FLOAT (53)    NOT NULL,
    [NoteID]              INT           NOT NULL,
    [PartsWarranty]       SMALLINT      NOT NULL,
    [PartsWarrantyType]   CHAR (1)      NOT NULL,
    [StandardHours]       FLOAT (53)    NOT NULL,
    [TaxBasis]            CHAR (1)      NOT NULL,
    [TaxID]               CHAR (10)     NOT NULL,
    [TaxTotal]            FLOAT (53)    NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smFlatRate0] PRIMARY KEY CLUSTERED ([FlatRateId] ASC) WITH (FILLFACTOR = 90)
);

