CREATE TABLE [dbo].[smEmpAdj] (
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [EmpAdjAmount]     FLOAT (53)    NOT NULL,
    [EmpAdjDate]       SMALLDATETIME NOT NULL,
    [EmpAdjDocument]   CHAR (10)     NOT NULL,
    [EmpAdjId]         CHAR (10)     NOT NULL,
    [EmpAdjNotes]      CHAR (30)     NOT NULL,
    [EmpAdjSalesOrder] CHAR (10)     NOT NULL,
    [EmpAdjTypeID]     CHAR (10)     NOT NULL,
    [linenbr]          SMALLINT      NOT NULL,
    [Lupd_DateTime]    SMALLDATETIME NOT NULL,
    [Lupd_Prog]        CHAR (8)      NOT NULL,
    [Lupd_User]        CHAR (10)     NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [smEmpAdj0] PRIMARY KEY CLUSTERED ([EmpAdjId] ASC, [linenbr] ASC) WITH (FILLFACTOR = 90)
);

