CREATE TABLE [dbo].[PJEQUIP] (
    [cpnyId]            CHAR (10)     NOT NULL,
    [crtd_datetime]     SMALLDATETIME NOT NULL,
    [crtd_prog]         CHAR (8)      NOT NULL,
    [crtd_user]         CHAR (10)     NOT NULL,
    [eq_id01]           CHAR (30)     NOT NULL,
    [eq_id02]           CHAR (30)     NOT NULL,
    [eq_id03]           CHAR (16)     NOT NULL,
    [eq_id04]           CHAR (16)     NOT NULL,
    [eq_id05]           CHAR (4)      NOT NULL,
    [eq_id06]           FLOAT (53)    NOT NULL,
    [eq_id07]           FLOAT (53)    NOT NULL,
    [eq_id08]           SMALLDATETIME NOT NULL,
    [eq_id09]           SMALLDATETIME NOT NULL,
    [eq_id10]           INT           NOT NULL,
    [eq_id11]           CHAR (30)     NOT NULL,
    [eq_id12]           CHAR (30)     NOT NULL,
    [eq_id13]           CHAR (4)      NOT NULL,
    [eq_id14]           CHAR (4)      NOT NULL,
    [eq_id15]           CHAR (4)      NOT NULL,
    [eq_id16]           CHAR (4)      NOT NULL,
    [eq_id17]           CHAR (2)      NOT NULL,
    [eq_id18]           CHAR (2)      NOT NULL,
    [eq_id19]           CHAR (2)      NOT NULL,
    [eq_id20]           CHAR (2)      NOT NULL,
    [er_id01]           CHAR (30)     NOT NULL,
    [er_id02]           CHAR (30)     NOT NULL,
    [er_id03]           CHAR (16)     NOT NULL,
    [er_id04]           CHAR (16)     NOT NULL,
    [er_id05]           CHAR (4)      NOT NULL,
    [er_id06]           FLOAT (53)    NOT NULL,
    [er_id07]           FLOAT (53)    NOT NULL,
    [er_id08]           SMALLDATETIME NOT NULL,
    [er_id09]           SMALLDATETIME NOT NULL,
    [er_id10]           SMALLINT      NOT NULL,
    [equip_desc]        CHAR (60)     NOT NULL,
    [equip_id]          CHAR (10)     NOT NULL,
    [equip_type]        CHAR (10)     NOT NULL,
    [gl_subacct]        CHAR (24)     NOT NULL,
    [lupd_datetime]     SMALLDATETIME NOT NULL,
    [lupd_prog]         CHAR (8)      NOT NULL,
    [lupd_user]         CHAR (10)     NOT NULL,
    [NoteID]            INT           NOT NULL,
    [project_costbasis] CHAR (16)     NOT NULL,
    [status]            CHAR (1)      NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [pjequip0] PRIMARY KEY CLUSTERED ([equip_id] ASC) WITH (FILLFACTOR = 90)
);

