CREATE TABLE [dbo].[cftRptRuntime] (
    [AccessNbr]     CHAR (4)   NOT NULL,
    [Acct]          CHAR (10)  NOT NULL,
    [Banner]        CHAR (1)   NOT NULL,
    [BatNbr]        CHAR (10)  NOT NULL,
    [BegPerNbr]     CHAR (6)   NOT NULL,
    [BusinessDate]  CHAR (10)  NOT NULL,
    [CmpnyName]     CHAR (30)  NOT NULL,
    [ComputerName]  CHAR (21)  NOT NULL,
    [CpnyID]        CHAR (10)  NOT NULL,
    [DatabaseName]  CHAR (20)  NOT NULL,
    [DocNbr]        CHAR (10)  NOT NULL,
    [EndPerNbr]     CHAR (6)   NOT NULL,
    [LongAnswer00]  CHAR (80)  NOT NULL,
    [LongAnswer01]  CHAR (80)  NOT NULL,
    [LongAnswer02]  CHAR (80)  NOT NULL,
    [LongAnswer03]  CHAR (80)  NOT NULL,
    [LongAnswer04]  CHAR (80)  NOT NULL,
    [NotesOn]       SMALLINT   NOT NULL,
    [PerNbr]        CHAR (6)   NOT NULL,
    [ReportDate]    CHAR (10)  NOT NULL,
    [ReportFormat]  CHAR (30)  NOT NULL,
    [ReportName]    CHAR (30)  NOT NULL,
    [ReportNbr]     CHAR (5)   NOT NULL,
    [ReportTitle]   CHAR (30)  NOT NULL,
    [RI_BEGPAGE]    SMALLINT   NOT NULL,
    [RI_CHKTIME]    CHAR (1)   NOT NULL,
    [RI_COPIES]     SMALLINT   NOT NULL,
    [RI_DATADIR]    CHAR (21)  NOT NULL,
    [RI_DICTDIR]    CHAR (21)  NOT NULL,
    [RI_DISPERR]    CHAR (1)   NOT NULL,
    [RI_ENDPAGE]    SMALLINT   NOT NULL,
    [RI_ID]         SMALLINT   NOT NULL,
    [RI_INCLUDE]    CHAR (1)   NOT NULL,
    [RI_LIBRARY]    CHAR (80)  NOT NULL,
    [RI_NOESC]      CHAR (1)   NOT NULL,
    [RI_OUTAPPN]    CHAR (1)   NOT NULL,
    [RI_OUTFILE]    CHAR (255) NOT NULL,
    [RI_PRINTER]    CHAR (1)   NOT NULL,
    [RI_REPLACE]    CHAR (255) NOT NULL,
    [RI_REPORT]     CHAR (30)  NOT NULL,
    [RI_STATUS]     CHAR (1)   NOT NULL,
    [RI_TEST]       CHAR (1)   NOT NULL,
    [RI_WHERE]      CHAR (255) NOT NULL,
    [RI_WPORT]      CHAR (255) NOT NULL,
    [RI_WPTR]       CHAR (255) NOT NULL,
    [RI_WTITLE]     CHAR (30)  NOT NULL,
    [SegCustMask]   CHAR (16)  NOT NULL,
    [SegCustTitle]  CHAR (16)  NOT NULL,
    [SegInvenMask]  CHAR (26)  NOT NULL,
    [SegInvenTitle] CHAR (26)  NOT NULL,
    [SegSubMask]    CHAR (38)  NOT NULL,
    [SegSubTitle]   CHAR (38)  NOT NULL,
    [SegVendMask]   CHAR (16)  NOT NULL,
    [SegVendTitle]  CHAR (16)  NOT NULL,
    [ShortAnswer00] CHAR (10)  NOT NULL,
    [ShortAnswer01] CHAR (10)  NOT NULL,
    [ShortAnswer02] CHAR (10)  NOT NULL,
    [ShortAnswer03] CHAR (10)  NOT NULL,
    [ShortAnswer04] CHAR (10)  NOT NULL,
    [Sub]           CHAR (24)  NOT NULL,
    [SystemDate]    CHAR (10)  NOT NULL,
    [SystemTime]    CHAR (7)   NOT NULL,
    [UserId]        CHAR (47)  NOT NULL,
    [trig_ts]       DATETIME   NOT NULL
);

