CREATE TABLE [dbo].[smSOAddress] (
    [BlanketPONbr]        CHAR (15)     NOT NULL,
    [BranchID]            CHAR (10)     NOT NULL,
    [CreatedBy]           CHAR (47)     NOT NULL,
    [CreatedDate]         SMALLDATETIME NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [Ctrd_Prog]           CHAR (8)      NOT NULL,
    [CustID]              CHAR (15)     NOT NULL,
    [DefaultCallType]     CHAR (10)     NOT NULL,
    [DefaultPrcPlanID]    CHAR (10)     NOT NULL,
    [DefaultProjManager]  CHAR (10)     NOT NULL,
    [DefaultPytMethod]    CHAR (1)      NOT NULL,
    [DefaultSalesPerson]  CHAR (10)     NOT NULL,
    [DefaultStatusID]     CHAR (10)     NOT NULL,
    [DefaultTechnician]   CHAR (10)     NOT NULL,
    [DwellingType]        CHAR (10)     NOT NULL,
    [GeographicZone]      CHAR (10)     NOT NULL,
    [LabMarkupID]         CHAR (10)     NOT NULL,
    [Latitude]            CHAR (10)     NOT NULL,
    [Longitude]           CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MapCoordinates]      CHAR (10)     NOT NULL,
    [MapPage]             CHAR (10)     NOT NULL,
    [MatMarkupID]         CHAR (10)     NOT NULL,
    [MaxServAmount]       FLOAT (53)    NOT NULL,
    [OriginalMediaID]     CHAR (10)     NOT NULL,
    [POEndDate]           SMALLDATETIME NOT NULL,
    [POStartDate]         SMALLDATETIME NOT NULL,
    [POOption]            CHAR (1)      NOT NULL,
    [PrintFlag]           SMALLINT      NOT NULL,
    [Priority]            CHAR (1)      NOT NULL,
    [RouteID]             CHAR (10)     NOT NULL,
    [SecurityEntryCode]   CHAR (30)     NOT NULL,
    [ShiptoID]            CHAR (10)     NOT NULL,
    [Sub]                 CHAR (24)     NOT NULL,
    [TaxID]               CHAR (10)     NOT NULL,
    [TenantAuthorizeCall] CHAR (1)      NOT NULL,
    [TImeZone]            CHAR (6)      NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smSOAddress0] PRIMARY KEY CLUSTERED ([CustID] ASC, [ShiptoID] ASC) WITH (FILLFACTOR = 90)
);

