CREATE TABLE [dbo].[Field] (
    [Active]           CHAR (1)      NOT NULL,
    [Caption]          CHAR (40)     NOT NULL,
    [ControlType]      SMALLINT      NOT NULL,
    [DArray]           CHAR (1)      NOT NULL,
    [DArraySize]       SMALLINT      NOT NULL,
    [DefaultConst]     CHAR (20)     NOT NULL,
    [DefaultStructFld] CHAR (20)     NOT NULL,
    [DefaultStructRec] CHAR (20)     NOT NULL,
    [FieldName]        CHAR (20)     NOT NULL,
    [Heading]          CHAR (40)     NOT NULL,
    [MaskType]         CHAR (3)      NOT NULL,
    [OldFieldName]     CHAR (20)     NOT NULL,
    [pBlankErr]        CHAR (1)      NOT NULL,
    [pDecimalPlaces]   SMALLINT      NOT NULL,
    [pDefaultType]     CHAR (1)      NOT NULL,
    [pDisplayLen]      SMALLINT      NOT NULL,
    [pEnabled]         CHAR (1)      NOT NULL,
    [pFalseText]       CHAR (10)     NOT NULL,
    [pFieldClass]      SMALLINT      NOT NULL,
    [pFieldDclLen]     SMALLINT      NOT NULL,
    [pFieldDclType]    SMALLINT      NOT NULL,
    [pMaxVal]          FLOAT (53)    NOT NULL,
    [pMinVal]          FLOAT (53)    NOT NULL,
    [pTrueText]        CHAR (10)     NOT NULL,
    [pVisible]         CHAR (1)      NOT NULL,
    [PVParmConstant00] CHAR (20)     NOT NULL,
    [PVParmConstant01] CHAR (20)     NOT NULL,
    [PVParmConstant02] CHAR (20)     NOT NULL,
    [PVParmConstant03] CHAR (20)     NOT NULL,
    [PVParmField00]    CHAR (20)     NOT NULL,
    [PVParmField01]    CHAR (20)     NOT NULL,
    [PVParmField02]    CHAR (20)     NOT NULL,
    [PVParmField03]    CHAR (20)     NOT NULL,
    [PVParmRec00]      CHAR (20)     NOT NULL,
    [PVParmRec01]      CHAR (20)     NOT NULL,
    [PVParmRec02]      CHAR (20)     NOT NULL,
    [PVParmRec03]      CHAR (20)     NOT NULL,
    [PVParmType00]     CHAR (1)      NOT NULL,
    [PVParmType01]     CHAR (1)      NOT NULL,
    [PVParmType02]     CHAR (1)      NOT NULL,
    [PVParmType03]     CHAR (1)      NOT NULL,
    [RecField]         CHAR (40)     NOT NULL,
    [RecordName]       CHAR (20)     NOT NULL,
    [TotalPrecision]   SMALLINT      NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [Field0] PRIMARY KEY CLUSTERED ([RecordName] ASC, [FieldName] ASC) WITH (FILLFACTOR = 90)
);

