CREATE TABLE [dbo].[SOShipMark] (
    [Addr1]         CHAR (60)     CONSTRAINT [DF_SOShipMark_Addr1] DEFAULT (' ') NOT NULL,
    [Addr2]         CHAR (60)     CONSTRAINT [DF_SOShipMark_Addr2] DEFAULT (' ') NOT NULL,
    [AddrID]        CHAR (10)     CONSTRAINT [DF_SOShipMark_AddrID] DEFAULT (' ') NOT NULL,
    [AddrSpecial]   SMALLINT      CONSTRAINT [DF_SOShipMark_AddrSpecial] DEFAULT ((0)) NOT NULL,
    [Attn]          CHAR (30)     CONSTRAINT [DF_SOShipMark_Attn] DEFAULT (' ') NOT NULL,
    [City]          CHAR (30)     CONSTRAINT [DF_SOShipMark_City] DEFAULT (' ') NOT NULL,
    [Country]       CHAR (3)      CONSTRAINT [DF_SOShipMark_Country] DEFAULT (' ') NOT NULL,
    [CpnyID]        CHAR (10)     CONSTRAINT [DF_SOShipMark_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_SOShipMark_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_SOShipMark_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_SOShipMark_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]        CHAR (15)     CONSTRAINT [DF_SOShipMark_CustID] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_SOShipMark_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_SOShipMark_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_SOShipMark_LUpd_User] DEFAULT (' ') NOT NULL,
    [MarkForID]     CHAR (10)     CONSTRAINT [DF_SOShipMark_MarkForID] DEFAULT (' ') NOT NULL,
    [MarkForType]   CHAR (1)      CONSTRAINT [DF_SOShipMark_MarkForType] DEFAULT (' ') NOT NULL,
    [Name1]         CHAR (60)     CONSTRAINT [DF_SOShipMark_Name1] DEFAULT (' ') NOT NULL,
    [Name2]         CHAR (60)     CONSTRAINT [DF_SOShipMark_Name2] DEFAULT (' ') NOT NULL,
    [Name3]         CHAR (60)     CONSTRAINT [DF_SOShipMark_Name3] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_SOShipMark_NoteID] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_SOShipMark_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_SOShipMark_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_SOShipMark_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_SOShipMark_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_SOShipMark_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_SOShipMark_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_SOShipMark_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_SOShipMark_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_SOShipMark_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_SOShipMark_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_SOShipMark_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_SOShipMark_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipperID]     CHAR (15)     CONSTRAINT [DF_SOShipMark_ShipperID] DEFAULT (' ') NOT NULL,
    [ShipViaID]     CHAR (15)     CONSTRAINT [DF_SOShipMark_ShipViaID] DEFAULT (' ') NOT NULL,
    [SiteID]        CHAR (10)     CONSTRAINT [DF_SOShipMark_SiteID] DEFAULT (' ') NOT NULL,
    [State]         CHAR (3)      CONSTRAINT [DF_SOShipMark_State] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_SOShipMark_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_SOShipMark_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_SOShipMark_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_SOShipMark_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_SOShipMark_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_SOShipMark_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_SOShipMark_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_SOShipMark_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_SOShipMark_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_SOShipMark_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendAddrID]    CHAR (10)     CONSTRAINT [DF_SOShipMark_VendAddrID] DEFAULT (' ') NOT NULL,
    [VendID]        CHAR (15)     CONSTRAINT [DF_SOShipMark_VendID] DEFAULT (' ') NOT NULL,
    [Zip]           CHAR (10)     CONSTRAINT [DF_SOShipMark_Zip] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SOShipMark0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [ShipperID] ASC) WITH (FILLFACTOR = 90)
);

