CREATE TABLE [dbo].[smEmpLicense] (
    [ActiveFlag]          SMALLINT      NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [EffectiveDate]       SMALLDATETIME NOT NULL,
    [EmployeeId]          CHAR (10)     NOT NULL,
    [ExpiredDate]         SMALLDATETIME NOT NULL,
    [FlagCertificateSent] SMALLINT      NOT NULL,
    [LicenseID]           CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smEmpLicense0] PRIMARY KEY CLUSTERED ([EmployeeId] ASC, [LicenseID] ASC) WITH (FILLFACTOR = 90)
);

