CREATE TABLE [dbo].[PJREVTSK] (
    [contract_type]   CHAR (4)      NOT NULL,
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [end_date]        SMALLDATETIME NOT NULL,
    [fips_num]        CHAR (10)     NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [manager1]        CHAR (10)     NOT NULL,
    [NoteId]          INT           NOT NULL,
    [pe_id01]         CHAR (30)     NOT NULL,
    [pe_id02]         CHAR (30)     NOT NULL,
    [pe_id03]         CHAR (16)     NOT NULL,
    [pe_id04]         CHAR (16)     NOT NULL,
    [pe_id05]         CHAR (4)      NOT NULL,
    [pe_id06]         FLOAT (53)    NOT NULL,
    [pe_id07]         FLOAT (53)    NOT NULL,
    [pe_id08]         SMALLDATETIME NOT NULL,
    [pe_id09]         SMALLDATETIME NOT NULL,
    [pe_id10]         INT           NOT NULL,
    [pjt_entity]      CHAR (32)     NOT NULL,
    [pjt_entity_desc] CHAR (60)     NOT NULL,
    [project]         CHAR (16)     NOT NULL,
    [revid]           CHAR (4)      NOT NULL,
    [rt_id01]         CHAR (30)     NOT NULL,
    [rt_id02]         CHAR (30)     NOT NULL,
    [rt_id03]         CHAR (16)     NOT NULL,
    [rt_id04]         CHAR (16)     NOT NULL,
    [rt_id05]         CHAR (4)      NOT NULL,
    [rt_id06]         FLOAT (53)    NOT NULL,
    [rt_id07]         FLOAT (53)    NOT NULL,
    [rt_id08]         SMALLDATETIME NOT NULL,
    [rt_id09]         SMALLDATETIME NOT NULL,
    [rt_id10]         INT           NOT NULL,
    [start_date]      SMALLDATETIME NOT NULL,
    [user1]           CHAR (30)     NOT NULL,
    [user2]           CHAR (30)     NOT NULL,
    [user3]           FLOAT (53)    NOT NULL,
    [user4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjrevtsk0] PRIMARY KEY CLUSTERED ([project] ASC, [revid] ASC, [pjt_entity] ASC) WITH (FILLFACTOR = 90)
);

