CREATE TABLE [dbo].[RtgStep] (
    [ActStart]         SMALLDATETIME CONSTRAINT [DF_RtgStep_ActStart] DEFAULT ('01/01/1900') NOT NULL,
    [CCumDirLbrCst]    FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumDirLbrCst] DEFAULT ((0)) NOT NULL,
    [CCumDirOthCst]    FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumDirOthCst] DEFAULT ((0)) NOT NULL,
    [CCumEngrLbrHrs]   FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumEngrLbrHrs] DEFAULT ((0)) NOT NULL,
    [CCumEngrLeadTime] FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumEngrLeadTime] DEFAULT ((0)) NOT NULL,
    [CCumEngrMachHrs]  FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumEngrMachHrs] DEFAULT ((0)) NOT NULL,
    [CCumFOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CCumFOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [CCumStdCst]       FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumStdCst] DEFAULT ((0)) NOT NULL,
    [CCumStdLbrHrs]    FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumStdLbrHrs] DEFAULT ((0)) NOT NULL,
    [CCumStdLeadTime]  FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumStdLeadTime] DEFAULT ((0)) NOT NULL,
    [CCumStdMachHrs]   FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumStdMachHrs] DEFAULT ((0)) NOT NULL,
    [CCumStdYield]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumStdYield] DEFAULT ((0)) NOT NULL,
    [CCumVOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CCumVOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_RtgStep_CCumVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [CDirLbrCst]       FLOAT (53)    CONSTRAINT [DF_RtgStep_CDirLbrCst] DEFAULT ((0)) NOT NULL,
    [CDirOthCst]       FLOAT (53)    CONSTRAINT [DF_RtgStep_CDirOthCst] DEFAULT ((0)) NOT NULL,
    [CEngLbrHrs]       FLOAT (53)    CONSTRAINT [DF_RtgStep_CEngLbrHrs] DEFAULT ((0)) NOT NULL,
    [CEngLeadTime]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CEngLeadTime] DEFAULT ((0)) NOT NULL,
    [CEngMachHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CEngMachHrs] DEFAULT ((0)) NOT NULL,
    [CEngMoveHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CEngMoveHrs] DEFAULT ((0)) NOT NULL,
    [CEngQueueHrs]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CEngQueueHrs] DEFAULT ((0)) NOT NULL,
    [CFOvhLbrCst]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CFOvhMachCst]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [CpnyID]           CHAR (10)     CONSTRAINT [DF_RtgStep_CpnyID] DEFAULT (' ') NOT NULL,
    [CrewSize]         FLOAT (53)    CONSTRAINT [DF_RtgStep_CrewSize] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_RtgStep_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_RtgStep_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_RtgStep_Crtd_User] DEFAULT (' ') NOT NULL,
    [CStdCst]          FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdCst] DEFAULT ((0)) NOT NULL,
    [CStdLbrHrs]       FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdLbrHrs] DEFAULT ((0)) NOT NULL,
    [CStdLeadTime]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdLeadTime] DEFAULT ((0)) NOT NULL,
    [CStdMachHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdMachHrs] DEFAULT ((0)) NOT NULL,
    [CStdMoveHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdMoveHrs] DEFAULT ((0)) NOT NULL,
    [CStdQueueHrs]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdQueueHrs] DEFAULT ((0)) NOT NULL,
    [CStdYield]        FLOAT (53)    CONSTRAINT [DF_RtgStep_CStdYield] DEFAULT ((0)) NOT NULL,
    [CVOvhLbrCst]      FLOAT (53)    CONSTRAINT [DF_RtgStep_CVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CVOvhMachCst]     FLOAT (53)    CONSTRAINT [DF_RtgStep_CVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [EngrChgOrder]     CHAR (20)     CONSTRAINT [DF_RtgStep_EngrChgOrder] DEFAULT (' ') NOT NULL,
    [KitID]            CHAR (30)     CONSTRAINT [DF_RtgStep_KitID] DEFAULT (' ') NOT NULL,
    [LaborClassID]     CHAR (10)     CONSTRAINT [DF_RtgStep_LaborClassID] DEFAULT (' ') NOT NULL,
    [LineID]           INT           CONSTRAINT [DF_RtgStep_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]          SMALLINT      CONSTRAINT [DF_RtgStep_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]          CHAR (5)      CONSTRAINT [DF_RtgStep_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME CONSTRAINT [DF_RtgStep_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      CONSTRAINT [DF_RtgStep_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]        CHAR (10)     CONSTRAINT [DF_RtgStep_LUpd_User] DEFAULT (' ') NOT NULL,
    [MachinID]         CHAR (10)     CONSTRAINT [DF_RtgStep_MachinID] DEFAULT (' ') NOT NULL,
    [NbrMachines]      FLOAT (53)    CONSTRAINT [DF_RtgStep_NbrMachines] DEFAULT ((0)) NOT NULL,
    [NoteID]           INT           CONSTRAINT [DF_RtgStep_NoteID] DEFAULT ((0)) NOT NULL,
    [OperationID]      CHAR (10)     CONSTRAINT [DF_RtgStep_OperationID] DEFAULT (' ') NOT NULL,
    [PCumDirLbrCst]    FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumDirLbrCst] DEFAULT ((0)) NOT NULL,
    [PCumDirOthCst]    FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumDirOthCst] DEFAULT ((0)) NOT NULL,
    [PCumEngrLbrHrs]   FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumEngrLbrHrs] DEFAULT ((0)) NOT NULL,
    [PCumEngrLeadTime] FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumEngrLeadTime] DEFAULT ((0)) NOT NULL,
    [PCumEngrMachHrs]  FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumEngrMachHrs] DEFAULT ((0)) NOT NULL,
    [PCumFOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PCumFOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [PCumStdCost]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumStdCost] DEFAULT ((0)) NOT NULL,
    [PCumStdLbrHrs]    FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumStdLbrHrs] DEFAULT ((0)) NOT NULL,
    [PCumStdLeadTime]  FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumStdLeadTime] DEFAULT ((0)) NOT NULL,
    [PCumStdMachHrs]   FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumStdMachHrs] DEFAULT ((0)) NOT NULL,
    [PCumStdYield]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumStdYield] DEFAULT ((0)) NOT NULL,
    [PCumVOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PCumVOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_RtgStep_PCumVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [PDirLbrCst]       FLOAT (53)    CONSTRAINT [DF_RtgStep_PDirLbrCst] DEFAULT ((0)) NOT NULL,
    [PDirOthCst]       FLOAT (53)    CONSTRAINT [DF_RtgStep_PDirOthCst] DEFAULT ((0)) NOT NULL,
    [PEngLbrHrs]       FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngLbrHrs] DEFAULT ((0)) NOT NULL,
    [PEngLeadTime]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngLeadTime] DEFAULT ((0)) NOT NULL,
    [PEngMachHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngMachHrs] DEFAULT ((0)) NOT NULL,
    [PEngMoveHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngMoveHrs] DEFAULT ((0)) NOT NULL,
    [PEngQueueHrs]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngQueueHrs] DEFAULT ((0)) NOT NULL,
    [PEngYield]        FLOAT (53)    CONSTRAINT [DF_RtgStep_PEngYield] DEFAULT ((0)) NOT NULL,
    [PFOvhLbrCst]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PFOvhMachCst]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [PStdCst]          FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdCst] DEFAULT ((0)) NOT NULL,
    [PStdLbrHrs]       FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdLbrHrs] DEFAULT ((0)) NOT NULL,
    [PStdLeadTime]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdLeadTime] DEFAULT ((0)) NOT NULL,
    [PStdMachHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdMachHrs] DEFAULT ((0)) NOT NULL,
    [PStdMoveHrs]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdMoveHrs] DEFAULT ((0)) NOT NULL,
    [PStdQueueHrs]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdQueueHrs] DEFAULT ((0)) NOT NULL,
    [PStdYield]        FLOAT (53)    CONSTRAINT [DF_RtgStep_PStdYield] DEFAULT ((0)) NOT NULL,
    [PVOvhLbrCst]      FLOAT (53)    CONSTRAINT [DF_RtgStep_PVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PVOvhMachCst]     FLOAT (53)    CONSTRAINT [DF_RtgStep_PVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [RtgStatus]        CHAR (1)      CONSTRAINT [DF_RtgStep_RtgStatus] DEFAULT (' ') NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_RtgStep_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_RtgStep_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_RtgStep_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_RtgStep_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_RtgStep_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_RtgStep_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_RtgStep_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_RtgStep_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_RtgStep_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_RtgStep_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_RtgStep_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_RtgStep_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]           CHAR (10)     CONSTRAINT [DF_RtgStep_SiteID] DEFAULT (' ') NOT NULL,
    [Status]           CHAR (1)      CONSTRAINT [DF_RtgStep_Status] DEFAULT (' ') NOT NULL,
    [StepNbr]          CHAR (5)      CONSTRAINT [DF_RtgStep_StepNbr] DEFAULT (' ') NOT NULL,
    [ToolID1]          CHAR (10)     CONSTRAINT [DF_RtgStep_ToolID1] DEFAULT (' ') NOT NULL,
    [ToolID2]          CHAR (10)     CONSTRAINT [DF_RtgStep_ToolID2] DEFAULT (' ') NOT NULL,
    [ToolID3]          CHAR (10)     CONSTRAINT [DF_RtgStep_ToolID3] DEFAULT (' ') NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_RtgStep_User1] DEFAULT (' ') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_RtgStep_User2] DEFAULT (' ') NOT NULL,
    [User3]            FLOAT (53)    CONSTRAINT [DF_RtgStep_User3] DEFAULT ((0)) NOT NULL,
    [User4]            FLOAT (53)    CONSTRAINT [DF_RtgStep_User4] DEFAULT ((0)) NOT NULL,
    [User5]            CHAR (10)     CONSTRAINT [DF_RtgStep_User5] DEFAULT (' ') NOT NULL,
    [User6]            CHAR (10)     CONSTRAINT [DF_RtgStep_User6] DEFAULT (' ') NOT NULL,
    [User7]            SMALLDATETIME CONSTRAINT [DF_RtgStep_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]            SMALLDATETIME CONSTRAINT [DF_RtgStep_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]           CHAR (15)     CONSTRAINT [DF_RtgStep_VendID] DEFAULT (' ') NOT NULL,
    [WorkCenterID]     CHAR (10)     CONSTRAINT [DF_RtgStep_WorkCenterID] DEFAULT (' ') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [RtgStep0] PRIMARY KEY CLUSTERED ([KitID] ASC, [SiteID] ASC, [RtgStatus] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [RtgStep1]
    ON [dbo].[RtgStep]([WorkCenterID] ASC) WITH (FILLFACTOR = 90);

