CREATE TABLE [dbo].[SMDispSetup] (
    [AssignTTWhen]        CHAR (1)      NOT NULL,
    [AvgTravelTime]       CHAR (4)      NOT NULL,
    [BarLabelAlign]       SMALLINT      NOT NULL,
    [BarLabelTextAmt]     SMALLINT      NOT NULL,
    [BodyText]            CHAR (255)    NOT NULL,
    [ColorProbUnassigned] CHAR (15)     NOT NULL,
    [ColorProbAssigned]   CHAR (15)     NOT NULL,
    [ColorProbInRoute]    CHAR (15)     NOT NULL,
    [ColorProbWIP]        CHAR (15)     NOT NULL,
    [ColorProbCompleted]  CHAR (15)     NOT NULL,
    [ColorProbPUParts]    CHAR (15)     NOT NULL,
    [ColorProbPartsOut]   CHAR (15)     NOT NULL,
    [ColorProbPartsIn]    CHAR (15)     NOT NULL,
    [ColorProbHold]       CHAR (15)     NOT NULL,
    [ColorProbIncomplete] CHAR (15)     NOT NULL,
    [ColorTechVacation]   CHAR (15)     NOT NULL,
    [ColorTechSick]       CHAR (15)     NOT NULL,
    [ColorTechPersonal]   CHAR (15)     NOT NULL,
    [ColorTechTraining]   CHAR (15)     NOT NULL,
    [ColorTechShop]       CHAR (15)     NOT NULL,
    [ColorFuture1]        CHAR (15)     NOT NULL,
    [ColorFuture2]        CHAR (15)     NOT NULL,
    [ColorFuture3]        CHAR (15)     NOT NULL,
    [ColorFuture4]        CHAR (15)     NOT NULL,
    [ColorFuture5]        CHAR (15)     NOT NULL,
    [ConflictWarning]     SMALLINT      NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [DispSetupID]         CHAR (10)     NOT NULL,
    [DateRange]           SMALLINT      NOT NULL,
    [EmailOption]         CHAR (1)      NOT NULL,
    [EmpClassLabel]       SMALLINT      NOT NULL,
    [FirstCallTravel]     CHAR (4)      NOT NULL,
    [Future1Int]          SMALLINT      NOT NULL,
    [Future2Int]          SMALLINT      NOT NULL,
    [Future3Str]          CHAR (10)     NOT NULL,
    [Future4Str]          CHAR (10)     NOT NULL,
    [Future5Str]          CHAR (10)     NOT NULL,
    [Future6Str]          CHAR (10)     NOT NULL,
    [Future7Str]          CHAR (10)     NOT NULL,
    [Future8Int]          SMALLINT      NOT NULL,
    [Future9str]          CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MinTimeProb]         CHAR (4)      NOT NULL,
    [SD_ID01]             CHAR (30)     NOT NULL,
    [SD_ID02]             CHAR (30)     NOT NULL,
    [SD_ID03]             CHAR (20)     NOT NULL,
    [SD_ID04]             CHAR (20)     NOT NULL,
    [SD_ID05]             CHAR (10)     NOT NULL,
    [SD_ID06]             CHAR (10)     NOT NULL,
    [SD_ID07]             CHAR (4)      NOT NULL,
    [SD_ID08]             FLOAT (53)    NOT NULL,
    [SD_ID09]             SMALLDATETIME NOT NULL,
    [SD_ID10]             SMALLINT      NOT NULL,
    [SD_ID11]             CHAR (30)     NOT NULL,
    [SD_ID12]             CHAR (30)     NOT NULL,
    [SD_ID13]             CHAR (20)     NOT NULL,
    [SD_ID14]             CHAR (20)     NOT NULL,
    [SD_ID15]             CHAR (10)     NOT NULL,
    [SD_ID16]             CHAR (10)     NOT NULL,
    [SD_ID17]             CHAR (4)      NOT NULL,
    [SD_ID18]             FLOAT (53)    NOT NULL,
    [SD_ID19]             SMALLDATETIME NOT NULL,
    [SD_ID20]             SMALLINT      NOT NULL,
    [SubjectText]         CHAR (80)     NOT NULL,
    [TechEmailBody]       CHAR (255)    NOT NULL,
    [TechEmailSubject]    CHAR (80)     NOT NULL,
    [TechLabel]           SMALLINT      NOT NULL,
    [UpdateOption]        CHAR (1)      NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smDispSetup0] PRIMARY KEY CLUSTERED ([DispSetupID] ASC) WITH (FILLFACTOR = 90)
);

