CREATE TABLE [dbo].[AttribDef] (
    [ClassID]          CHAR (6)      CONSTRAINT [DF_AttribDef_ClassID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_AttribDef_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_AttribDef_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_AttribDef_Crtd_User] DEFAULT (' ') NOT NULL,
    [Descr00]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr00] DEFAULT (' ') NOT NULL,
    [Descr01]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr01] DEFAULT (' ') NOT NULL,
    [Descr02]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr02] DEFAULT (' ') NOT NULL,
    [Descr03]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr03] DEFAULT (' ') NOT NULL,
    [Descr04]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr04] DEFAULT (' ') NOT NULL,
    [Descr05]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr05] DEFAULT (' ') NOT NULL,
    [Descr06]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr06] DEFAULT (' ') NOT NULL,
    [Descr07]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr07] DEFAULT (' ') NOT NULL,
    [Descr08]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr08] DEFAULT (' ') NOT NULL,
    [Descr09]          CHAR (30)     CONSTRAINT [DF_AttribDef_Descr09] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME CONSTRAINT [DF_AttribDef_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      CONSTRAINT [DF_AttribDef_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]        CHAR (10)     CONSTRAINT [DF_AttribDef_LUpd_User] DEFAULT (' ') NOT NULL,
    [Mask00]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask00] DEFAULT (' ') NOT NULL,
    [Mask01]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask01] DEFAULT (' ') NOT NULL,
    [Mask02]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask02] DEFAULT (' ') NOT NULL,
    [Mask03]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask03] DEFAULT (' ') NOT NULL,
    [Mask04]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask04] DEFAULT (' ') NOT NULL,
    [Mask05]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask05] DEFAULT (' ') NOT NULL,
    [Mask06]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask06] DEFAULT (' ') NOT NULL,
    [Mask07]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask07] DEFAULT (' ') NOT NULL,
    [Mask08]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask08] DEFAULT (' ') NOT NULL,
    [Mask09]           CHAR (10)     CONSTRAINT [DF_AttribDef_Mask09] DEFAULT (' ') NOT NULL,
    [NoteID]           INT           CONSTRAINT [DF_AttribDef_NoteID] DEFAULT ((0)) NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_AttribDef_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_AttribDef_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_AttribDef_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_AttribDef_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_AttribDef_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_AttribDef_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_AttribDef_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_AttribDef_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_AttribDef_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_AttribDef_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_AttribDef_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_AttribDef_S4Future12] DEFAULT (' ') NOT NULL,
    [UnitDesc00]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc00] DEFAULT (' ') NOT NULL,
    [UnitDesc01]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc01] DEFAULT (' ') NOT NULL,
    [UnitDesc02]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc02] DEFAULT (' ') NOT NULL,
    [UnitDesc03]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc03] DEFAULT (' ') NOT NULL,
    [UnitDesc04]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc04] DEFAULT (' ') NOT NULL,
    [UnitDesc05]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc05] DEFAULT (' ') NOT NULL,
    [UnitDesc06]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc06] DEFAULT (' ') NOT NULL,
    [UnitDesc07]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc07] DEFAULT (' ') NOT NULL,
    [UnitDesc08]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc08] DEFAULT (' ') NOT NULL,
    [UnitDesc09]       CHAR (6)      CONSTRAINT [DF_AttribDef_UnitDesc09] DEFAULT (' ') NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_AttribDef_User1] DEFAULT (' ') NOT NULL,
    [User10]           SMALLDATETIME CONSTRAINT [DF_AttribDef_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_AttribDef_User2] DEFAULT (' ') NOT NULL,
    [User3]            CHAR (30)     CONSTRAINT [DF_AttribDef_User3] DEFAULT (' ') NOT NULL,
    [User4]            CHAR (30)     CONSTRAINT [DF_AttribDef_User4] DEFAULT (' ') NOT NULL,
    [User5]            FLOAT (53)    CONSTRAINT [DF_AttribDef_User5] DEFAULT ((0)) NOT NULL,
    [User6]            FLOAT (53)    CONSTRAINT [DF_AttribDef_User6] DEFAULT ((0)) NOT NULL,
    [User7]            CHAR (10)     CONSTRAINT [DF_AttribDef_User7] DEFAULT (' ') NOT NULL,
    [User8]            CHAR (10)     CONSTRAINT [DF_AttribDef_User8] DEFAULT (' ') NOT NULL,
    [User9]            SMALLDATETIME CONSTRAINT [DF_AttribDef_User9] DEFAULT ('01/01/1900') NOT NULL,
    [ValidationType00] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType00] DEFAULT (' ') NOT NULL,
    [ValidationType01] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType01] DEFAULT (' ') NOT NULL,
    [ValidationType02] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType02] DEFAULT (' ') NOT NULL,
    [ValidationType03] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType03] DEFAULT (' ') NOT NULL,
    [ValidationType04] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType04] DEFAULT (' ') NOT NULL,
    [ValidationType05] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType05] DEFAULT (' ') NOT NULL,
    [ValidationType06] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType06] DEFAULT (' ') NOT NULL,
    [ValidationType07] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType07] DEFAULT (' ') NOT NULL,
    [ValidationType08] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType08] DEFAULT (' ') NOT NULL,
    [ValidationType09] CHAR (1)      CONSTRAINT [DF_AttribDef_ValidationType09] DEFAULT (' ') NOT NULL,
    [ValidValues00]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues00] DEFAULT (' ') NOT NULL,
    [ValidValues01]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues01] DEFAULT (' ') NOT NULL,
    [ValidValues02]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues02] DEFAULT (' ') NOT NULL,
    [ValidValues03]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues03] DEFAULT (' ') NOT NULL,
    [ValidValues04]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues04] DEFAULT (' ') NOT NULL,
    [ValidValues05]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues05] DEFAULT (' ') NOT NULL,
    [ValidValues06]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues06] DEFAULT (' ') NOT NULL,
    [ValidValues07]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues07] DEFAULT (' ') NOT NULL,
    [ValidValues08]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues08] DEFAULT (' ') NOT NULL,
    [ValidValues09]    CHAR (60)     CONSTRAINT [DF_AttribDef_ValidValues09] DEFAULT (' ') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [AttribDef0] PRIMARY KEY CLUSTERED ([ClassID] ASC) WITH (FILLFACTOR = 90)
);

