CREATE TABLE [dbo].[smConHistory] (
    [AmtInvoiced]   FLOAT (53)    NOT NULL,
    [AmtRevenue]    FLOAT (53)    NOT NULL,
    [ContractID]    CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [HistMonth]     SMALLINT      NOT NULL,
    [HistYear]      SMALLINT      NOT NULL,
    [LaborBillHrs]  FLOAT (53)    NOT NULL,
    [LaborCost]     FLOAT (53)    NOT NULL,
    [LaborHours]    FLOAT (53)    NOT NULL,
    [LaborSales]    FLOAT (53)    NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [OtherCost]     FLOAT (53)    NOT NULL,
    [OtherSales]    FLOAT (53)    NOT NULL,
    [SalesTotal]    FLOAT (53)    NOT NULL,
    [TaxTotal]      FLOAT (53)    NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smConHistory0] PRIMARY KEY CLUSTERED ([ContractID] ASC, [HistYear] ASC, [HistMonth] ASC) WITH (FILLFACTOR = 90)
);

