CREATE TABLE [dbo].[ED850Lineitem] (
    [ArrivalDate]         SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ArrivalDate] DEFAULT ('01/01/1900') NOT NULL,
    [BuyCatalog]          CHAR (48)     CONSTRAINT [DF_ED850Lineitem_BuyCatalog] DEFAULT (' ') NOT NULL,
    [BuyPart]             CHAR (48)     CONSTRAINT [DF_ED850Lineitem_BuyPart] DEFAULT (' ') NOT NULL,
    [CancelDate]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_CancelDate] DEFAULT ('01/01/1900') NOT NULL,
    [CatalogPrice]        FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CatalogPrice] DEFAULT ((0)) NOT NULL,
    [ClassOfTrade]        CHAR (5)      CONSTRAINT [DF_ED850Lineitem_ClassOfTrade] DEFAULT (' ') NOT NULL,
    [ContainerPerLayer]   SMALLINT      CONSTRAINT [DF_ED850Lineitem_ContainerPerLayer] DEFAULT ((0)) NOT NULL,
    [Containers]          INT           CONSTRAINT [DF_ED850Lineitem_Containers] DEFAULT ((0)) NOT NULL,
    [CpnyID]              CHAR (10)     CONSTRAINT [DF_ED850Lineitem_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_ED850Lineitem_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_ED850Lineitem_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCatalogPrice]    FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CuryCatalogPrice] DEFAULT ((0)) NOT NULL,
    [CuryEffDate]         SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_CuryEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryID]              CHAR (4)      CONSTRAINT [DF_ED850Lineitem_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]         CHAR (1)      CONSTRAINT [DF_ED850Lineitem_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryPrice]           FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CuryPrice] DEFAULT ((0)) NOT NULL,
    [CuryPriceExt]        FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CuryPriceExt] DEFAULT ((0)) NOT NULL,
    [CuryRate]            FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CuryRate] DEFAULT ((0)) NOT NULL,
    [CuryRateType]        CHAR (6)      CONSTRAINT [DF_ED850Lineitem_CuryRateType] DEFAULT (' ') NOT NULL,
    [CuryRetailPrice]     FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_CuryRetailPrice] DEFAULT ((0)) NOT NULL,
    [CustPackListItemNbr] CHAR (30)     CONSTRAINT [DF_ED850Lineitem_CustPackListItemNbr] DEFAULT (' ') NOT NULL,
    [CustPartDesc]        CHAR (80)     CONSTRAINT [DF_ED850Lineitem_CustPartDesc] DEFAULT (' ') NOT NULL,
    [CustPODate]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_CustPODate] DEFAULT ('01/01/1900') NOT NULL,
    [CustPONbr]           CHAR (30)     CONSTRAINT [DF_ED850Lineitem_CustPONbr] DEFAULT (' ') NOT NULL,
    [CustPOSuff]          CHAR (30)     CONSTRAINT [DF_ED850Lineitem_CustPOSuff] DEFAULT (' ') NOT NULL,
    [DeliveryDate]        SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_DeliveryDate] DEFAULT ('01/01/1900') NOT NULL,
    [Density]             FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Density] DEFAULT ((0)) NOT NULL,
    [DensityUOM]          CHAR (6)      CONSTRAINT [DF_ED850Lineitem_DensityUOM] DEFAULT (' ') NOT NULL,
    [Depth]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Depth] DEFAULT ((0)) NOT NULL,
    [DepthUOM]            CHAR (6)      CONSTRAINT [DF_ED850Lineitem_DepthUOM] DEFAULT (' ') NOT NULL,
    [Diameter]            FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Diameter] DEFAULT ((0)) NOT NULL,
    [DiameterUOM]         CHAR (6)      CONSTRAINT [DF_ED850Lineitem_DiameterUOM] DEFAULT (' ') NOT NULL,
    [EAN]                 CHAR (48)     CONSTRAINT [DF_ED850Lineitem_EAN] DEFAULT (' ') NOT NULL,
    [ECCN]                CHAR (48)     CONSTRAINT [DF_ED850Lineitem_ECCN] DEFAULT (' ') NOT NULL,
    [EDIPOID]             CHAR (10)     CONSTRAINT [DF_ED850Lineitem_EDIPOID] DEFAULT (' ') NOT NULL,
    [EffDate]             SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_EffDate] DEFAULT ('01/01/1900') NOT NULL,
    [ExpDate]             SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ExpDate] DEFAULT ('01/01/1900') NOT NULL,
    [Gauge]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Gauge] DEFAULT ((0)) NOT NULL,
    [GaugeUOM]            CHAR (6)      CONSTRAINT [DF_ED850Lineitem_GaugeUOM] DEFAULT (' ') NOT NULL,
    [Height]              FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]           CHAR (6)      CONSTRAINT [DF_ED850Lineitem_HeightUOM] DEFAULT (' ') NOT NULL,
    [InvtID]              CHAR (48)     CONSTRAINT [DF_ED850Lineitem_InvtID] DEFAULT (' ') NOT NULL,
    [ISBN]                CHAR (48)     CONSTRAINT [DF_ED850Lineitem_ISBN] DEFAULT (' ') NOT NULL,
    [ItemColor]           CHAR (48)     CONSTRAINT [DF_ED850Lineitem_ItemColor] DEFAULT (' ') NOT NULL,
    [ItemSize]            CHAR (48)     CONSTRAINT [DF_ED850Lineitem_ItemSize] DEFAULT (' ') NOT NULL,
    [LayersPerPallet]     SMALLINT      CONSTRAINT [DF_ED850Lineitem_LayersPerPallet] DEFAULT ((0)) NOT NULL,
    [Len]                 FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]              CHAR (6)      CONSTRAINT [DF_ED850Lineitem_LenUOM] DEFAULT (' ') NOT NULL,
    [LineID]              INT           CONSTRAINT [DF_ED850Lineitem_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]             SMALLINT      CONSTRAINT [DF_ED850Lineitem_LineNbr] DEFAULT ((0)) NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]           CHAR (8)      CONSTRAINT [DF_ED850Lineitem_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]           CHAR (10)     CONSTRAINT [DF_ED850Lineitem_Lupd_User] DEFAULT (' ') NOT NULL,
    [MemaCode]            CHAR (48)     CONSTRAINT [DF_ED850Lineitem_MemaCode] DEFAULT (' ') NOT NULL,
    [MfgPart]             CHAR (48)     CONSTRAINT [DF_ED850Lineitem_MfgPart] DEFAULT (' ') NOT NULL,
    [MilSpec]             CHAR (48)     CONSTRAINT [DF_ED850Lineitem_MilSpec] DEFAULT (' ') NOT NULL,
    [NDC]                 CHAR (48)     CONSTRAINT [DF_ED850Lineitem_NDC] DEFAULT (' ') NOT NULL,
    [NoteID]              INT           CONSTRAINT [DF_ED850Lineitem_NoteID] DEFAULT ((0)) NOT NULL,
    [OtherRef]            CHAR (48)     CONSTRAINT [DF_ED850Lineitem_OtherRef] DEFAULT (' ') NOT NULL,
    [OtherRefQual]        CHAR (5)      CONSTRAINT [DF_ED850Lineitem_OtherRefQual] DEFAULT (' ') NOT NULL,
    [Pack]                SMALLINT      CONSTRAINT [DF_ED850Lineitem_Pack] DEFAULT ((0)) NOT NULL,
    [PackSize]            SMALLINT      CONSTRAINT [DF_ED850Lineitem_PackSize] DEFAULT ((0)) NOT NULL,
    [PackUom]             CHAR (6)      CONSTRAINT [DF_ED850Lineitem_PackUom] DEFAULT (' ') NOT NULL,
    [POLineNbr]           CHAR (20)     CONSTRAINT [DF_ED850Lineitem_POLineNbr] DEFAULT (' ') NOT NULL,
    [Price]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Price] DEFAULT ((0)) NOT NULL,
    [PriceExt]            FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_PriceExt] DEFAULT ((0)) NOT NULL,
    [PrintNbr]            CHAR (48)     CONSTRAINT [DF_ED850Lineitem_PrintNbr] DEFAULT (' ') NOT NULL,
    [ProdClass]           CHAR (35)     CONSTRAINT [DF_ED850Lineitem_ProdClass] DEFAULT (' ') NOT NULL,
    [PromoEndDate]        SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_PromoEndDate] DEFAULT ('01/01/1900') NOT NULL,
    [PromoStartDate]      SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_PromoStartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Qty]                 FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Qty] DEFAULT ((0)) NOT NULL,
    [ReqLotSer]           CHAR (35)     CONSTRAINT [DF_ED850Lineitem_ReqLotSer] DEFAULT (' ') NOT NULL,
    [ReqSite]             CHAR (35)     CONSTRAINT [DF_ED850Lineitem_ReqSite] DEFAULT (' ') NOT NULL,
    [RequestDate]         SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_RequestDate] DEFAULT ('01/01/1900') NOT NULL,
    [ReqWhseLoc]          CHAR (35)     CONSTRAINT [DF_ED850Lineitem_ReqWhseLoc] DEFAULT (' ') NOT NULL,
    [RetailPrice]         FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_RetailPrice] DEFAULT ((0)) NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_ED850Lineitem_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_ED850Lineitem_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_ED850Lineitem_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_ED850Lineitem_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_ED850Lineitem_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_ED850Lineitem_S4Future12] DEFAULT (' ') NOT NULL,
    [ScheduleDate]        SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ScheduleDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipDate]            SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ShipDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipNBDate]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ShipNBDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipNLDate]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ShipNLDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipWeekOf]          SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_ShipWeekOf] DEFAULT ('01/01/1900') NOT NULL,
    [SKU]                 CHAR (48)     CONSTRAINT [DF_ED850Lineitem_SKU] DEFAULT (' ') NOT NULL,
    [TariffNbr]           CHAR (35)     CONSTRAINT [DF_ED850Lineitem_TariffNbr] DEFAULT (' ') NOT NULL,
    [UCC]                 CHAR (48)     CONSTRAINT [DF_ED850Lineitem_UCC] DEFAULT (' ') NOT NULL,
    [UnitPriceBasis]      CHAR (5)      CONSTRAINT [DF_ED850Lineitem_UnitPriceBasis] DEFAULT (' ') NOT NULL,
    [UOM]                 CHAR (6)      CONSTRAINT [DF_ED850Lineitem_UOM] DEFAULT (' ') NOT NULL,
    [UPC]                 CHAR (48)     CONSTRAINT [DF_ED850Lineitem_UPC] DEFAULT (' ') NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_ED850Lineitem_User1] DEFAULT (' ') NOT NULL,
    [User10]              SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_ED850Lineitem_User2] DEFAULT (' ') NOT NULL,
    [User3]               CHAR (30)     CONSTRAINT [DF_ED850Lineitem_User3] DEFAULT (' ') NOT NULL,
    [User4]               CHAR (30)     CONSTRAINT [DF_ED850Lineitem_User4] DEFAULT (' ') NOT NULL,
    [User5]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_User5] DEFAULT ((0)) NOT NULL,
    [User6]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_User6] DEFAULT ((0)) NOT NULL,
    [User7]               CHAR (10)     CONSTRAINT [DF_ED850Lineitem_User7] DEFAULT (' ') NOT NULL,
    [User8]               CHAR (10)     CONSTRAINT [DF_ED850Lineitem_User8] DEFAULT (' ') NOT NULL,
    [User9]               SMALLDATETIME CONSTRAINT [DF_ED850Lineitem_User9] DEFAULT ('01/01/1900') NOT NULL,
    [Volume]              FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Volume] DEFAULT ((0)) NOT NULL,
    [VolumeUOM]           CHAR (6)      CONSTRAINT [DF_ED850Lineitem_VolumeUOM] DEFAULT (' ') NOT NULL,
    [Weight]              FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]           CHAR (6)      CONSTRAINT [DF_ED850Lineitem_WeightUOM] DEFAULT (' ') NOT NULL,
    [Width]               FLOAT (53)    CONSTRAINT [DF_ED850Lineitem_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]            CHAR (6)      CONSTRAINT [DF_ED850Lineitem_WidthUOM] DEFAULT (' ') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [ED850Lineitem0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [EDIPOID] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

