CREATE TABLE [dbo].[CuryAcct] (
    [Acct]          CHAR (10)     NOT NULL,
    [BalanceType]   CHAR (1)      NOT NULL,
    [BaseCuryID]    CHAR (4)      NOT NULL,
    [BegBal]        FLOAT (53)    NOT NULL,
    [CpnyID]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CuryBegBal]    FLOAT (53)    NOT NULL,
    [CuryId]        CHAR (4)      NOT NULL,
    [CuryPtdBal00]  FLOAT (53)    NOT NULL,
    [CuryPtdBal01]  FLOAT (53)    NOT NULL,
    [CuryPtdBal02]  FLOAT (53)    NOT NULL,
    [CuryPtdBal03]  FLOAT (53)    NOT NULL,
    [CuryPtdBal04]  FLOAT (53)    NOT NULL,
    [CuryPtdBal05]  FLOAT (53)    NOT NULL,
    [CuryPtdBal06]  FLOAT (53)    NOT NULL,
    [CuryPtdBal07]  FLOAT (53)    NOT NULL,
    [CuryPtdBal08]  FLOAT (53)    NOT NULL,
    [CuryPtdBal09]  FLOAT (53)    NOT NULL,
    [CuryPtdBal10]  FLOAT (53)    NOT NULL,
    [CuryPtdBal11]  FLOAT (53)    NOT NULL,
    [CuryPtdBal12]  FLOAT (53)    NOT NULL,
    [CuryYtdBal00]  FLOAT (53)    NOT NULL,
    [CuryYtdBal01]  FLOAT (53)    NOT NULL,
    [CuryYtdBal02]  FLOAT (53)    NOT NULL,
    [CuryYtdBal03]  FLOAT (53)    NOT NULL,
    [CuryYtdBal04]  FLOAT (53)    NOT NULL,
    [CuryYtdBal05]  FLOAT (53)    NOT NULL,
    [CuryYtdBal06]  FLOAT (53)    NOT NULL,
    [CuryYtdBal07]  FLOAT (53)    NOT NULL,
    [CuryYtdBal08]  FLOAT (53)    NOT NULL,
    [CuryYtdBal09]  FLOAT (53)    NOT NULL,
    [CuryYtdBal10]  FLOAT (53)    NOT NULL,
    [CuryYtdBal11]  FLOAT (53)    NOT NULL,
    [CuryYtdBal12]  FLOAT (53)    NOT NULL,
    [FiscYr]        CHAR (4)      NOT NULL,
    [LedgerID]      CHAR (10)     NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NoteId]        INT           NOT NULL,
    [PtdBal00]      FLOAT (53)    NOT NULL,
    [PtdBal01]      FLOAT (53)    NOT NULL,
    [PtdBal02]      FLOAT (53)    NOT NULL,
    [PtdBal03]      FLOAT (53)    NOT NULL,
    [PtdBal04]      FLOAT (53)    NOT NULL,
    [PtdBal05]      FLOAT (53)    NOT NULL,
    [PtdBal06]      FLOAT (53)    NOT NULL,
    [PtdBal07]      FLOAT (53)    NOT NULL,
    [PtdBal08]      FLOAT (53)    NOT NULL,
    [PtdBal09]      FLOAT (53)    NOT NULL,
    [PtdBal10]      FLOAT (53)    NOT NULL,
    [PtdBal11]      FLOAT (53)    NOT NULL,
    [PtdBal12]      FLOAT (53)    NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [Sub]           CHAR (24)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [YtdBal00]      FLOAT (53)    NOT NULL,
    [YtdBal01]      FLOAT (53)    NOT NULL,
    [YtdBal02]      FLOAT (53)    NOT NULL,
    [YtdBal03]      FLOAT (53)    NOT NULL,
    [YtdBal04]      FLOAT (53)    NOT NULL,
    [YtdBal05]      FLOAT (53)    NOT NULL,
    [YtdBal06]      FLOAT (53)    NOT NULL,
    [YtdBal07]      FLOAT (53)    NOT NULL,
    [YtdBal08]      FLOAT (53)    NOT NULL,
    [YtdBal09]      FLOAT (53)    NOT NULL,
    [YtdBal10]      FLOAT (53)    NOT NULL,
    [YtdBal11]      FLOAT (53)    NOT NULL,
    [YtdBal12]      FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CuryAcct0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [Acct] ASC, [Sub] ASC, [LedgerID] ASC, [FiscYr] ASC, [CuryId] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE NONCLUSTERED INDEX [CuryAcct1]
    ON [dbo].[CuryAcct]([FiscYr] ASC, [Acct] ASC, [Sub] ASC, [LedgerID] ASC) WITH (FILLFACTOR = 100);

