CREATE TABLE [dbo].[EDVendor] (
    [AllowDiffItem]       SMALLINT      CONSTRAINT [DF_EDVendor_AllowDiffItem] DEFAULT ((0)) NOT NULL,
    [AutoStoreVenPartNbr] SMALLINT      CONSTRAINT [DF_EDVendor_AutoStoreVenPartNbr] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_EDVendor_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_EDVendor_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_EDVendor_Crtd_User] DEFAULT (' ') NOT NULL,
    [DefaultCarrier]      CHAR (10)     CONSTRAINT [DF_EDVendor_DefaultCarrier] DEFAULT (' ') NOT NULL,
    [DefaultFOB]          CHAR (20)     CONSTRAINT [DF_EDVendor_DefaultFOB] DEFAULT (' ') NOT NULL,
    [DefaultVia]          CHAR (10)     CONSTRAINT [DF_EDVendor_DefaultVia] DEFAULT (' ') NOT NULL,
    [FOBLocQual]          CHAR (2)      CONSTRAINT [DF_EDVendor_FOBLocQual] DEFAULT (' ') NOT NULL,
    [InEDICost]           SMALLINT      CONSTRAINT [DF_EDVendor_InEDICost] DEFAULT ((0)) NOT NULL,
    [IntCustNbr]          CHAR (20)     CONSTRAINT [DF_EDVendor_IntCustNbr] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME CONSTRAINT [DF_EDVendor_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]           CHAR (8)      CONSTRAINT [DF_EDVendor_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]           CHAR (10)     CONSTRAINT [DF_EDVendor_Lupd_User] DEFAULT (' ') NOT NULL,
    [OutBoundTemplate]    CHAR (20)     CONSTRAINT [DF_EDVendor_OutBoundTemplate] DEFAULT (' ') NOT NULL,
    [ReqILineID]          SMALLINT      CONSTRAINT [DF_EDVendor_ReqILineID] DEFAULT ((0)) NOT NULL,
    [ReqOAcctNbr]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOAcctNbr] DEFAULT ((0)) NOT NULL,
    [ReqOAgreeNbr]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOAgreeNbr] DEFAULT ((0)) NOT NULL,
    [ReqOArrivalDate]     SMALLINT      CONSTRAINT [DF_EDVendor_ReqOArrivalDate] DEFAULT ((0)) NOT NULL,
    [ReqOBatchNbr]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOBatchNbr] DEFAULT ((0)) NOT NULL,
    [ReqOBidNbr]          SMALLINT      CONSTRAINT [DF_EDVendor_ReqOBidNbr] DEFAULT ((0)) NOT NULL,
    [ReqOBuyerName]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOBuyerName] DEFAULT ((0)) NOT NULL,
    [ReqOCancelDate]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOCancelDate] DEFAULT ((0)) NOT NULL,
    [ReqOChangeNbr]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOChangeNbr] DEFAULT ((0)) NOT NULL,
    [ReqOConfirmerName]   SMALLINT      CONSTRAINT [DF_EDVendor_ReqOConfirmerName] DEFAULT ((0)) NOT NULL,
    [ReqOContractNbr]     SMALLINT      CONSTRAINT [DF_EDVendor_ReqOContractNbr] DEFAULT ((0)) NOT NULL,
    [ReqOCreationDate]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqOCreationDate] DEFAULT ((0)) NOT NULL,
    [ReqODeliveryDate]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqODeliveryDate] DEFAULT ((0)) NOT NULL,
    [ReqODeptNbr]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqODeptNbr] DEFAULT ((0)) NOT NULL,
    [ReqODistributorNbr]  SMALLINT      CONSTRAINT [DF_EDVendor_ReqODistributorNbr] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser1]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser1] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser10]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser10] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser2]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser2] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser3]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser3] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser4]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser4] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser5]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser5] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser6]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser6] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser7]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser7] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser8]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser8] DEFAULT ((0)) NOT NULL,
    [ReqOEDPOUser9]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEDPOUser9] DEFAULT ((0)) NOT NULL,
    [ReqOEffDate]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEffDate] DEFAULT ((0)) NOT NULL,
    [ReqOEndCustPackNbr]  SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEndCustPackNbr] DEFAULT ((0)) NOT NULL,
    [ReqOEndCustPODate]   SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEndCustPODate] DEFAULT ((0)) NOT NULL,
    [ReqOEndCustPONbr]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEndCustPONbr] DEFAULT ((0)) NOT NULL,
    [ReqOEndCustSONbr]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqOEndCustSONbr] DEFAULT ((0)) NOT NULL,
    [ReqOExpirDate]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOExpirDate] DEFAULT ((0)) NOT NULL,
    [ReqOFOBLocQual]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOFOBLocQual] DEFAULT ((0)) NOT NULL,
    [ReqOFOBPoint]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOFOBPoint] DEFAULT ((0)) NOT NULL,
    [ReqOFOBShipMethPay]  SMALLINT      CONSTRAINT [DF_EDVendor_ReqOFOBShipMethPay] DEFAULT ((0)) NOT NULL,
    [ReqOFreight]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOFreight] DEFAULT ((0)) NOT NULL,
    [ReqOPOSuff]          SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOSuff] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser1]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser1] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser2]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser2] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser3]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser3] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser4]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser4] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser5]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser5] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser6]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser6] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser7]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser7] DEFAULT ((0)) NOT NULL,
    [ReqOPOUser8]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPOUser8] DEFAULT ((0)) NOT NULL,
    [ReqOPromoEndDate]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPromoEndDate] DEFAULT ((0)) NOT NULL,
    [ReqOPromoNbr]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPromoNbr] DEFAULT ((0)) NOT NULL,
    [ReqOPromoStartDate]  SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPromoStartDate] DEFAULT ((0)) NOT NULL,
    [ReqOPurReqNbr]       SMALLINT      CONSTRAINT [DF_EDVendor_ReqOPurReqNbr] DEFAULT ((0)) NOT NULL,
    [ReqORequestDate]     SMALLINT      CONSTRAINT [DF_EDVendor_ReqORequestDate] DEFAULT ((0)) NOT NULL,
    [ReqOSalesDivision]   SMALLINT      CONSTRAINT [DF_EDVendor_ReqOSalesDivision] DEFAULT ((0)) NOT NULL,
    [ReqOSalesman]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOSalesman] DEFAULT ((0)) NOT NULL,
    [ReqOSalesRegion]     SMALLINT      CONSTRAINT [DF_EDVendor_ReqOSalesRegion] DEFAULT ((0)) NOT NULL,
    [ReqOSalesTerritory]  SMALLINT      CONSTRAINT [DF_EDVendor_ReqOSalesTerritory] DEFAULT ((0)) NOT NULL,
    [ReqOScheduleDate]    SMALLINT      CONSTRAINT [DF_EDVendor_ReqOScheduleDate] DEFAULT ((0)) NOT NULL,
    [ReqOShipDate]        SMALLINT      CONSTRAINT [DF_EDVendor_ReqOShipDate] DEFAULT ((0)) NOT NULL,
    [ReqOShipNBDate]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOShipNBDate] DEFAULT ((0)) NOT NULL,
    [ReqOShipNLDate]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOShipNLDate] DEFAULT ((0)) NOT NULL,
    [ReqOShipVia]         SMALLINT      CONSTRAINT [DF_EDVendor_ReqOShipVia] DEFAULT ((0)) NOT NULL,
    [ReqOShipWeekOf]      SMALLINT      CONSTRAINT [DF_EDVendor_ReqOShipWeekOf] DEFAULT ((0)) NOT NULL,
    [ReqOTerms]           SMALLINT      CONSTRAINT [DF_EDVendor_ReqOTerms] DEFAULT ((0)) NOT NULL,
    [ReqOVolume]          SMALLINT      CONSTRAINT [DF_EDVendor_ReqOVolume] DEFAULT ((0)) NOT NULL,
    [ReqOWeight]          SMALLINT      CONSTRAINT [DF_EDVendor_ReqOWeight] DEFAULT ((0)) NOT NULL,
    [ReqOWONbr]           SMALLINT      CONSTRAINT [DF_EDVendor_ReqOWONbr] DEFAULT ((0)) NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_EDVendor_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_EDVendor_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_EDVendor_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_EDVendor_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_EDVendor_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_EDVendor_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_EDVendor_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_EDVendor_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_EDVendor_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_EDVendor_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_EDVendor_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_EDVendor_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipMethPay]         CHAR (2)      CONSTRAINT [DF_EDVendor_ShipMethPay] DEFAULT (' ') NOT NULL,
    [UseLineID]           SMALLINT      CONSTRAINT [DF_EDVendor_UseLineID] DEFAULT ((0)) NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_EDVendor_User1] DEFAULT (' ') NOT NULL,
    [User10]              SMALLDATETIME CONSTRAINT [DF_EDVendor_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_EDVendor_User2] DEFAULT (' ') NOT NULL,
    [User3]               CHAR (30)     CONSTRAINT [DF_EDVendor_User3] DEFAULT (' ') NOT NULL,
    [User4]               CHAR (30)     CONSTRAINT [DF_EDVendor_User4] DEFAULT (' ') NOT NULL,
    [User5]               FLOAT (53)    CONSTRAINT [DF_EDVendor_User5] DEFAULT ((0)) NOT NULL,
    [User6]               FLOAT (53)    CONSTRAINT [DF_EDVendor_User6] DEFAULT ((0)) NOT NULL,
    [User7]               CHAR (10)     CONSTRAINT [DF_EDVendor_User7] DEFAULT (' ') NOT NULL,
    [User8]               CHAR (10)     CONSTRAINT [DF_EDVendor_User8] DEFAULT (' ') NOT NULL,
    [User9]               SMALLDATETIME CONSTRAINT [DF_EDVendor_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]              CHAR (15)     CONSTRAINT [DF_EDVendor_VendID] DEFAULT (' ') NOT NULL,
    [VouchFreight]        SMALLINT      CONSTRAINT [DF_EDVendor_VouchFreight] DEFAULT ((0)) NOT NULL,
    [VouchRecpt]          SMALLINT      CONSTRAINT [DF_EDVendor_VouchRecpt] DEFAULT ((0)) NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [EDVendor0] PRIMARY KEY CLUSTERED ([VendID] ASC) WITH (FILLFACTOR = 90)
);

