CREATE TABLE [dbo].[SlsPerHist] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_SlsPerHist_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_SlsPerHist_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_SlsPerHist_Crtd_User] DEFAULT (' ') NOT NULL,
    [FiscYr]        CHAR (4)      CONSTRAINT [DF_SlsPerHist_FiscYr] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_SlsPerHist_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_SlsPerHist_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_SlsPerHist_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteId]        INT           CONSTRAINT [DF_SlsPerHist_NoteId] DEFAULT ((0)) NOT NULL,
    [PerNbr]        CHAR (6)      CONSTRAINT [DF_SlsPerHist_PerNbr] DEFAULT (' ') NOT NULL,
    [PtdCOGS00]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS00] DEFAULT ((0)) NOT NULL,
    [PtdCOGS01]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS01] DEFAULT ((0)) NOT NULL,
    [PtdCOGS02]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS02] DEFAULT ((0)) NOT NULL,
    [PtdCOGS03]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS03] DEFAULT ((0)) NOT NULL,
    [PtdCOGS04]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS04] DEFAULT ((0)) NOT NULL,
    [PtdCOGS05]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS05] DEFAULT ((0)) NOT NULL,
    [PtdCOGS06]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS06] DEFAULT ((0)) NOT NULL,
    [PtdCOGS07]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS07] DEFAULT ((0)) NOT NULL,
    [PtdCOGS08]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS08] DEFAULT ((0)) NOT NULL,
    [PtdCOGS09]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS09] DEFAULT ((0)) NOT NULL,
    [PtdCOGS10]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS10] DEFAULT ((0)) NOT NULL,
    [PtdCOGS11]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS11] DEFAULT ((0)) NOT NULL,
    [PtdCOGS12]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdCOGS12] DEFAULT ((0)) NOT NULL,
    [PtdRcpt00]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt00] DEFAULT ((0)) NOT NULL,
    [PtdRcpt01]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt01] DEFAULT ((0)) NOT NULL,
    [PtdRcpt02]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt02] DEFAULT ((0)) NOT NULL,
    [PtdRcpt03]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt03] DEFAULT ((0)) NOT NULL,
    [PtdRcpt04]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt04] DEFAULT ((0)) NOT NULL,
    [PtdRcpt05]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt05] DEFAULT ((0)) NOT NULL,
    [PtdRcpt06]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt06] DEFAULT ((0)) NOT NULL,
    [PtdRcpt07]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt07] DEFAULT ((0)) NOT NULL,
    [PtdRcpt08]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt08] DEFAULT ((0)) NOT NULL,
    [PtdRcpt09]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt09] DEFAULT ((0)) NOT NULL,
    [PtdRcpt10]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt10] DEFAULT ((0)) NOT NULL,
    [PtdRcpt11]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt11] DEFAULT ((0)) NOT NULL,
    [PtdRcpt12]     FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdRcpt12] DEFAULT ((0)) NOT NULL,
    [PtdSls00]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls00] DEFAULT ((0)) NOT NULL,
    [PtdSls01]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls01] DEFAULT ((0)) NOT NULL,
    [PtdSls02]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls02] DEFAULT ((0)) NOT NULL,
    [PtdSls03]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls03] DEFAULT ((0)) NOT NULL,
    [PtdSls04]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls04] DEFAULT ((0)) NOT NULL,
    [PtdSls05]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls05] DEFAULT ((0)) NOT NULL,
    [PtdSls06]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls06] DEFAULT ((0)) NOT NULL,
    [PtdSls07]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls07] DEFAULT ((0)) NOT NULL,
    [PtdSls08]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls08] DEFAULT ((0)) NOT NULL,
    [PtdSls09]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls09] DEFAULT ((0)) NOT NULL,
    [PtdSls10]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls10] DEFAULT ((0)) NOT NULL,
    [PtdSls11]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls11] DEFAULT ((0)) NOT NULL,
    [PtdSls12]      FLOAT (53)    CONSTRAINT [DF_SlsPerHist_PtdSls12] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_SlsPerHist_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_SlsPerHist_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_SlsPerHist_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_SlsPerHist_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_SlsPerHist_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_SlsPerHist_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_SlsPerHist_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_SlsPerHist_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_SlsPerHist_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_SlsPerHist_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_SlsPerHist_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_SlsPerHist_S4Future12] DEFAULT (' ') NOT NULL,
    [SlsperId]      CHAR (10)     CONSTRAINT [DF_SlsPerHist_SlsperId] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_SlsPerHist_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_SlsPerHist_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_SlsPerHist_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_SlsPerHist_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_SlsPerHist_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_SlsPerHist_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_SlsPerHist_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_SlsPerHist_User8] DEFAULT ('01/01/1900') NOT NULL,
    [YtdCOGS]       FLOAT (53)    CONSTRAINT [DF_SlsPerHist_YtdCOGS] DEFAULT ((0)) NOT NULL,
    [YtdRcpt]       FLOAT (53)    CONSTRAINT [DF_SlsPerHist_YtdRcpt] DEFAULT ((0)) NOT NULL,
    [YtdSls]        FLOAT (53)    CONSTRAINT [DF_SlsPerHist_YtdSls] DEFAULT ((0)) NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SlsperHist0] PRIMARY KEY CLUSTERED ([SlsperId] ASC, [FiscYr] ASC) WITH (FILLFACTOR = 90)
);

