CREATE TABLE [dbo].[ProductClass] (
    [Buyer]               CHAR (10)     CONSTRAINT [DF_ProductClass_Buyer] DEFAULT (' ') NOT NULL,
    [CFOvhMatlRate]       FLOAT (53)    CONSTRAINT [DF_ProductClass_CFOvhMatlRate] DEFAULT ((0)) NOT NULL,
    [ChkOrdQty]           CHAR (1)      CONSTRAINT [DF_ProductClass_ChkOrdQty] DEFAULT (' ') NOT NULL,
    [ClassID]             CHAR (6)      CONSTRAINT [DF_ProductClass_ClassID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_ProductClass_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_ProductClass_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_ProductClass_Crtd_User] DEFAULT (' ') NOT NULL,
    [CVOvhMatlRate]       FLOAT (53)    CONSTRAINT [DF_ProductClass_CVOvhMatlRate] DEFAULT ((0)) NOT NULL,
    [Descr]               CHAR (30)     CONSTRAINT [DF_ProductClass_Descr] DEFAULT (' ') NOT NULL,
    [DfltCOGSAcct]        CHAR (10)     CONSTRAINT [DF_ProductClass_DfltCOGSAcct] DEFAULT (' ') NOT NULL,
    [DfltCOGSSub]         CHAR (24)     CONSTRAINT [DF_ProductClass_DfltCOGSSub] DEFAULT (' ') NOT NULL,
    [DfltDiscPrc]         CHAR (1)      CONSTRAINT [DF_ProductClass_DfltDiscPrc] DEFAULT (' ') NOT NULL,
    [DfltInvtAcct]        CHAR (10)     CONSTRAINT [DF_ProductClass_DfltInvtAcct] DEFAULT (' ') NOT NULL,
    [DfltInvtSub]         CHAR (24)     CONSTRAINT [DF_ProductClass_DfltInvtSub] DEFAULT (' ') NOT NULL,
    [DfltInvtType]        CHAR (1)      CONSTRAINT [DF_ProductClass_DfltInvtType] DEFAULT (' ') NOT NULL,
    [DfltLCVarianceAcct]  CHAR (10)     CONSTRAINT [DF_ProductClass_DfltLCVarianceAcct] DEFAULT (' ') NOT NULL,
    [DfltLCVarianceSub]   CHAR (24)     CONSTRAINT [DF_ProductClass_DfltLCVarianceSub] DEFAULT (' ') NOT NULL,
    [DfltLotSerAssign]    CHAR (1)      CONSTRAINT [DF_ProductClass_DfltLotSerAssign] DEFAULT (' ') NOT NULL,
    [DfltLotSerFxdLen]    SMALLINT      CONSTRAINT [DF_ProductClass_DfltLotSerFxdLen] DEFAULT ((0)) NOT NULL,
    [DfltLotSerFxdTyp]    CHAR (1)      CONSTRAINT [DF_ProductClass_DfltLotSerFxdTyp] DEFAULT (' ') NOT NULL,
    [DfltLotSerFxdVal]    CHAR (12)     CONSTRAINT [DF_ProductClass_DfltLotSerFxdVal] DEFAULT (' ') NOT NULL,
    [DfltLotSerMthd]      CHAR (1)      CONSTRAINT [DF_ProductClass_DfltLotSerMthd] DEFAULT (' ') NOT NULL,
    [DfltLotSerNumLen]    SMALLINT      CONSTRAINT [DF_ProductClass_DfltLotSerNumLen] DEFAULT ((0)) NOT NULL,
    [DfltLotSerNumVal]    CHAR (25)     CONSTRAINT [DF_ProductClass_DfltLotSerNumVal] DEFAULT (' ') NOT NULL,
    [DfltLotSerShelfLife] SMALLINT      CONSTRAINT [DF_ProductClass_DfltLotSerShelfLife] DEFAULT ((0)) NOT NULL,
    [DfltLotSerTrack]     CHAR (1)      CONSTRAINT [DF_ProductClass_DfltLotSerTrack] DEFAULT (' ') NOT NULL,
    [DfltPOUnit]          CHAR (6)      CONSTRAINT [DF_ProductClass_DfltPOUnit] DEFAULT (' ') NOT NULL,
    [DfltPPVAcct]         CHAR (10)     CONSTRAINT [DF_ProductClass_DfltPPVAcct] DEFAULT (' ') NOT NULL,
    [DfltPPVSub]          CHAR (24)     CONSTRAINT [DF_ProductClass_DfltPPVSub] DEFAULT (' ') NOT NULL,
    [DfltSalesAcct]       CHAR (10)     CONSTRAINT [DF_ProductClass_DfltSalesAcct] DEFAULT (' ') NOT NULL,
    [DfltSalesSub]        CHAR (24)     CONSTRAINT [DF_ProductClass_DfltSalesSub] DEFAULT (' ') NOT NULL,
    [DfltShpNotInvAcct]   CHAR (10)     CONSTRAINT [DF_ProductClass_DfltShpNotInvAcct] DEFAULT (' ') NOT NULL,
    [DfltShpnotInvSub]    CHAR (24)     CONSTRAINT [DF_ProductClass_DfltShpnotInvSub] DEFAULT (' ') NOT NULL,
    [DfltSite]            CHAR (10)     CONSTRAINT [DF_ProductClass_DfltSite] DEFAULT (' ') NOT NULL,
    [DfltSlsTaxCat]       CHAR (10)     CONSTRAINT [DF_ProductClass_DfltSlsTaxCat] DEFAULT (' ') NOT NULL,
    [DfltSOUnit]          CHAR (6)      CONSTRAINT [DF_ProductClass_DfltSOUnit] DEFAULT (' ') NOT NULL,
    [DfltSource]          CHAR (1)      CONSTRAINT [DF_ProductClass_DfltSource] DEFAULT (' ') NOT NULL,
    [DfltStatus]          CHAR (1)      CONSTRAINT [DF_ProductClass_DfltStatus] DEFAULT (' ') NOT NULL,
    [DfltStkItem]         SMALLINT      CONSTRAINT [DF_ProductClass_DfltStkItem] DEFAULT ((0)) NOT NULL,
    [DfltStkWt]           FLOAT (53)    CONSTRAINT [DF_ProductClass_DfltStkWt] DEFAULT ((0)) NOT NULL,
    [DfltStkWtUnit]       CHAR (6)      CONSTRAINT [DF_ProductClass_DfltStkWtUnit] DEFAULT (' ') NOT NULL,
    [DfltValMthd]         CHAR (1)      CONSTRAINT [DF_ProductClass_DfltValMthd] DEFAULT (' ') NOT NULL,
    [DfltWarrantyDays]    SMALLINT      CONSTRAINT [DF_ProductClass_DfltWarrantyDays] DEFAULT ((0)) NOT NULL,
    [ExplInvoice]         SMALLINT      CONSTRAINT [DF_ProductClass_ExplInvoice] DEFAULT ((0)) NOT NULL,
    [ExplOrder]           SMALLINT      CONSTRAINT [DF_ProductClass_ExplOrder] DEFAULT ((0)) NOT NULL,
    [ExplPackSlip]        SMALLINT      CONSTRAINT [DF_ProductClass_ExplPackSlip] DEFAULT ((0)) NOT NULL,
    [ExplPickList]        SMALLINT      CONSTRAINT [DF_ProductClass_ExplPickList] DEFAULT ((0)) NOT NULL,
    [ExplShipping]        SMALLINT      CONSTRAINT [DF_ProductClass_ExplShipping] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME CONSTRAINT [DF_ProductClass_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      CONSTRAINT [DF_ProductClass_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]           CHAR (10)     CONSTRAINT [DF_ProductClass_LUpd_User] DEFAULT (' ') NOT NULL,
    [MaterialType]        CHAR (10)     CONSTRAINT [DF_ProductClass_MaterialType] DEFAULT (' ') NOT NULL,
    [MinGrossProfit]      FLOAT (53)    CONSTRAINT [DF_ProductClass_MinGrossProfit] DEFAULT ((0)) NOT NULL,
    [NoteID]              INT           CONSTRAINT [DF_ProductClass_NoteID] DEFAULT ((0)) NOT NULL,
    [PFOvhMatlRate]       FLOAT (53)    CONSTRAINT [DF_ProductClass_PFOvhMatlRate] DEFAULT ((0)) NOT NULL,
    [PVOvhMatlRate]       FLOAT (53)    CONSTRAINT [DF_ProductClass_PVOvhMatlRate] DEFAULT ((0)) NOT NULL,
    [RollupCost]          SMALLINT      CONSTRAINT [DF_ProductClass_RollupCost] DEFAULT ((0)) NOT NULL,
    [RollupPrice]         SMALLINT      CONSTRAINT [DF_ProductClass_RollupPrice] DEFAULT ((0)) NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_ProductClass_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_ProductClass_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_ProductClass_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_ProductClass_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_ProductClass_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_ProductClass_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_ProductClass_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_ProductClass_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_ProductClass_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_ProductClass_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_ProductClass_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_ProductClass_S4Future12] DEFAULT (' ') NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_ProductClass_User1] DEFAULT (' ') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_ProductClass_User2] DEFAULT (' ') NOT NULL,
    [User3]               FLOAT (53)    CONSTRAINT [DF_ProductClass_User3] DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    CONSTRAINT [DF_ProductClass_User4] DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     CONSTRAINT [DF_ProductClass_User5] DEFAULT (' ') NOT NULL,
    [User6]               CHAR (10)     CONSTRAINT [DF_ProductClass_User6] DEFAULT (' ') NOT NULL,
    [User7]               SMALLDATETIME CONSTRAINT [DF_ProductClass_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME CONSTRAINT [DF_ProductClass_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [ProductClass0] PRIMARY KEY CLUSTERED ([ClassID] ASC) WITH (FILLFACTOR = 90)
);

