CREATE TABLE [dbo].[XDDFile_Wrk] (
    [AdjCrtd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [AdjCrtd_Prog]         CHAR (8)      DEFAULT ('') NOT NULL,
    [AdjCrtd_User]         CHAR (10)     DEFAULT ('') NOT NULL,
    [AdjS4Future01]        CHAR (30)     DEFAULT ('') NOT NULL,
    [AdjS4Future02]        CHAR (30)     DEFAULT ('') NOT NULL,
    [AdjS4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AdjS4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AdjS4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AdjS4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AdjS4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [AdjS4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [AdjS4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [AdjS4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [AdjS4Future11]        CHAR (10)     DEFAULT ('') NOT NULL,
    [AdjS4Future12]        CHAR (10)     DEFAULT ('') NOT NULL,
    [BnkAcctType]          CHAR (1)      DEFAULT ('') NOT NULL,
    [BnkBankAcct]          CHAR (35)     DEFAULT ('') NOT NULL,
    [BnkBankTransit]       CHAR (30)     DEFAULT ('') NOT NULL,
    [BnkOrigDFI]           CHAR (9)      DEFAULT ('') NOT NULL,
    [BnkPNDate]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [BnkPNStatus]          CHAR (1)      DEFAULT ('') NOT NULL,
    [BnkUser1]             CHAR (30)     DEFAULT ('') NOT NULL,
    [BnkUser10]            CHAR (30)     DEFAULT ('') NOT NULL,
    [BnkUser2]             CHAR (30)     DEFAULT ('') NOT NULL,
    [BnkUser3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BnkUser4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BnkUser5]             CHAR (10)     DEFAULT ('') NOT NULL,
    [BnkUser6]             CHAR (10)     DEFAULT ('') NOT NULL,
    [BnkUser7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [BnkUser8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [BnkUser9]             CHAR (30)     DEFAULT ('') NOT NULL,
    [ChkAcct]              CHAR (10)     DEFAULT ('') NOT NULL,
    [ChkBatEFTGrp]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [ChkBatNbr]            CHAR (10)     DEFAULT ('') NOT NULL,
    [ChkBatSeq]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [ChkCpnyID]            CHAR (10)     DEFAULT ('') NOT NULL,
    [ChkCuryAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ChkCuryDiscAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ChkCuryID]            CHAR (4)      DEFAULT ('') NOT NULL,
    [ChkCuryRGOLAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ChkDocDate]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [ChkDocType]           CHAR (2)      DEFAULT ('') NOT NULL,
    [ChkEffDate]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [ChkLUpd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [ChkLUpd_Prog]         CHAR (8)      DEFAULT ('') NOT NULL,
    [ChkLUpd_User]         CHAR (10)     DEFAULT ('') NOT NULL,
    [ChkPerPost]           CHAR (6)      DEFAULT ('') NOT NULL,
    [ChkRefNbr]            CHAR (10)     DEFAULT ('') NOT NULL,
    [ChkSub]               CHAR (24)     DEFAULT ('') NOT NULL,
    [ChkTerms]             CHAR (2)      DEFAULT ('') NOT NULL,
    [ComputerName]         CHAR (21)     DEFAULT ('') NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]            CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]            CHAR (10)     DEFAULT ('') NOT NULL,
    [DepAcctType]          CHAR (1)      DEFAULT ('') NOT NULL,
    [DepBankAcct]          CHAR (35)     DEFAULT ('') NOT NULL,
    [DepBankAcctLen]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [DepBankTransit]       CHAR (30)     DEFAULT ('') NOT NULL,
    [DepBankTransitLen]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [DepEDIVersion]        CHAR (6)      DEFAULT ('') NOT NULL,
    [DepEntryClass]        CHAR (4)      DEFAULT ('') NOT NULL,
    [DepISOCntry]          CHAR (2)      DEFAULT ('') NOT NULL,
    [DepPNDate]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DepPNStatus]          CHAR (1)      DEFAULT ('') NOT NULL,
    [DepPNTaxPmt]          CHAR (15)     DEFAULT ('') NOT NULL,
    [DepRecord]            CHAR (1)      DEFAULT ('') NOT NULL,
    [DepUser1]             CHAR (30)     DEFAULT ('') NOT NULL,
    [DepUser10]            CHAR (30)     DEFAULT ('') NOT NULL,
    [DepUser2]             CHAR (30)     DEFAULT ('') NOT NULL,
    [DepUser3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DepUser4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DepUser5]             CHAR (10)     DEFAULT ('') NOT NULL,
    [DepUser6]             CHAR (10)     DEFAULT ('') NOT NULL,
    [DepUser7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DepUser8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DepUser9]             CHAR (30)     DEFAULT ('') NOT NULL,
    [EBFileNbr]            CHAR (6)      DEFAULT ('') NOT NULL,
    [EditScrnNbr]          CHAR (5)      DEFAULT ('') NOT NULL,
    [FilACHCompanyID]      CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHCompanyIDLen]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilACHCompanyName]    CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHCompanyNameLen] SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilACHImmDest]        CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHImmDestLen]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilACHImmDestN]       CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHImmDestNLen]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilACHImmOrig]        CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHImmOrigLen]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilACHImmOrigN]       CHAR (30)     DEFAULT ('') NOT NULL,
    [FilACHImmOrigNLen]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [FilCrLf]              CHAR (1)      DEFAULT ('') NOT NULL,
    [FileType]             CHAR (1)      DEFAULT ('') NOT NULL,
    [FormatID]             CHAR (15)     DEFAULT ('') NOT NULL,
    [KeepDelete]           CHAR (1)      DEFAULT ('') NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]            CHAR (10)     DEFAULT ('') NOT NULL,
    [PerAppl]              CHAR (6)      DEFAULT ('') NOT NULL,
    [RecordID]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RecordSumAmt]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RecordSummary]        CHAR (1)      DEFAULT ('') NOT NULL,
    [RecSection]           CHAR (3)      DEFAULT ('') NOT NULL,
    [RecType]              CHAR (3)      DEFAULT ('') NOT NULL,
    [SKFuture01]           CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]           CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]           INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]           INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]           CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]           CHAR (10)     DEFAULT ('') NOT NULL,
    [User1]                CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]                CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]                CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]                CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]                CHAR (30)     DEFAULT ('') NOT NULL,
    [ValueString]          CHAR (255)    DEFAULT ('') NOT NULL,
    [VchAmt]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchAmtInChkCury]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchCpnyID]            CHAR (10)     DEFAULT ('') NOT NULL,
    [VchCpnyIDEIN]         CHAR (12)     DEFAULT ('') NOT NULL,
    [VchCuryAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchCuryDiscAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchCuryID]            CHAR (4)      DEFAULT ('') NOT NULL,
    [VchCuryMultDiv]       CHAR (1)      DEFAULT ('') NOT NULL,
    [VchCuryOrigDocAmt]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchCuryRate]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchDiscAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchDocDesc]           CHAR (30)     DEFAULT ('') NOT NULL,
    [VchDocType]           CHAR (2)      DEFAULT ((0)) NOT NULL,
    [VchInvcDate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VchInvcNbr]           CHAR (15)     DEFAULT ('') NOT NULL,
    [VchPONbr]             CHAR (10)     DEFAULT ('') NOT NULL,
    [VchRefNbr]            CHAR (10)     DEFAULT ('') NOT NULL,
    [VchUser1]             CHAR (30)     DEFAULT ('') NOT NULL,
    [VchUser2]             CHAR (30)     DEFAULT ('') NOT NULL,
    [VchUser3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchUser4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [VchUser5]             CHAR (10)     DEFAULT ('') NOT NULL,
    [VchUser6]             CHAR (10)     DEFAULT ('') NOT NULL,
    [VchUser7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VchUser8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VendAcct]             CHAR (10)     DEFAULT ('') NOT NULL,
    [VendCust]             CHAR (1)      DEFAULT ('') NOT NULL,
    [VendID]               CHAR (15)     DEFAULT ('') NOT NULL,
    [VendName]             CHAR (60)     DEFAULT ('') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [XDDFile_Wrk0] PRIMARY KEY CLUSTERED ([FileType] ASC, [EBFileNbr] ASC, [RecordID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [XDDFile_Wrk1]
    ON [dbo].[XDDFile_Wrk]([FileType] ASC, [ComputerName] ASC, [RecordID] ASC);

