CREATE TABLE [dbo].[SOType] (
    [Active]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARAcct]               CHAR (10)     DEFAULT (' ') NOT NULL,
    [ARSub]                CHAR (31)     DEFAULT (' ') NOT NULL,
    [AssemblyOnSat]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AssemblyOnSun]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoReleaseReturns]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [Behavior]             CHAR (4)      DEFAULT (' ') NOT NULL,
    [CancelDays]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [COGSAcct]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [COGSSub]              CHAR (31)     DEFAULT (' ') NOT NULL,
    [CpnyID]               CHAR (10)     DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [Descr]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [DiscAcct]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [DiscSub]              CHAR (31)     DEFAULT (' ') NOT NULL,
    [Disp]                 CHAR (3)      DEFAULT (' ') NOT NULL,
    [EnterLotSer]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [FrtAcct]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [FrtSub]               CHAR (31)     DEFAULT (' ') NOT NULL,
    [InvAcct]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [InvcNbrAR]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [InvcNbrPrefix]        CHAR (15)     DEFAULT (' ') NOT NULL,
    [InvcNbrType]          CHAR (4)      DEFAULT (' ') NOT NULL,
    [InvSub]               CHAR (31)     DEFAULT (' ') NOT NULL,
    [LastInvcNbr]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [LastOrdNbr]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [LastShipperNbr]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [MiscAcct]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [MiscSub]              CHAR (31)     DEFAULT (' ') NOT NULL,
    [NoAutoCreateShippers] SMALLINT      DEFAULT ((0)) NOT NULL,
    [NoteID]               INT           DEFAULT ((0)) NOT NULL,
    [OrdNbrPrefix]         CHAR (15)     DEFAULT (' ') NOT NULL,
    [OrdNbrType]           CHAR (4)      DEFAULT (' ') NOT NULL,
    [ProjectStatus]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [RequireDetailAppr]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [RequireManRelease]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [RequireTechAppr]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [ReturnOrderTypeID]    CHAR (4)      DEFAULT (' ') NOT NULL,
    [S4Future01]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipperPrefix]        CHAR (15)     DEFAULT (' ') NOT NULL,
    [ShipperType]          CHAR (4)      DEFAULT (' ') NOT NULL,
    [ShiptoType]           CHAR (1)      DEFAULT (' ') NOT NULL,
    [SlsAcct]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [SlsSub]               CHAR (31)     DEFAULT (' ') NOT NULL,
    [SOTypeID]             CHAR (4)      DEFAULT (' ') NOT NULL,
    [StdOrdType]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [TemplateProject]      CHAR (16)     DEFAULT (' ') NOT NULL,
    [User1]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User10]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User2]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User4]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User5]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User6]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User7]                CHAR (10)     DEFAULT (' ') NOT NULL,
    [User8]                CHAR (10)     DEFAULT (' ') NOT NULL,
    [User9]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [WholeOrdDiscAcct]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [WholeOrdDiscSub]      CHAR (31)     DEFAULT (' ') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [SOType0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [SOTypeID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [SOType1]
    ON [dbo].[SOType]([CpnyID] ASC, [SOTypeID] ASC, [Behavior] ASC) WITH (FILLFACTOR = 90);

