CREATE TABLE [dbo].[APTranDt] (
    [AlternateID]      CHAR (30)     NOT NULL,
    [APLineRef]        CHAR (5)      NOT NULL,
    [BOMLineRef]       CHAR (5)      NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [CuryExtCost]      FLOAT (53)    NOT NULL,
    [CuryExtCostVar]   FLOAT (53)    NOT NULL,
    [CuryID]           CHAR (4)      NOT NULL,
    [CuryInvcExtCost]  FLOAT (53)    NOT NULL,
    [CuryInvcUnitCost] FLOAT (53)    NOT NULL,
    [CuryMultDiv]      CHAR (1)      NOT NULL,
    [CuryRate]         FLOAT (53)    NOT NULL,
    [CuryUnitCost]     FLOAT (53)    NOT NULL,
    [CuryUnitCostVar]  FLOAT (53)    NOT NULL,
    [Descr]            CHAR (60)     NOT NULL,
    [EmpID]            CHAR (10)     NOT NULL,
    [ExtCost]          FLOAT (53)    NOT NULL,
    [ExtCostVar]       FLOAT (53)    NOT NULL,
    [InvcExtCost]      FLOAT (53)    NOT NULL,
    [InvcQty]          FLOAT (53)    NOT NULL,
    [InvcUnitCost]     FLOAT (53)    NOT NULL,
    [InvtID]           CHAR (30)     NOT NULL,
    [Labor_Class_Cd]   CHAR (4)      NOT NULL,
    [LineID]           INT           NOT NULL,
    [LineNbr]          SMALLINT      NOT NULL,
    [LineRef]          CHAR (5)      NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME NOT NULL,
    [LUpd_Prog]        CHAR (8)      NOT NULL,
    [LUpd_User]        CHAR (10)     NOT NULL,
    [NoteID]           INT           NOT NULL,
    [ProjectID]        CHAR (16)     NOT NULL,
    [PurchAcct]        CHAR (10)     NOT NULL,
    [PurchSub]         CHAR (24)     NOT NULL,
    [Qty]              FLOAT (53)    NOT NULL,
    [QtyVar]           FLOAT (53)    NOT NULL,
    [RcptLineRef]      CHAR (5)      NOT NULL,
    [RcptNbr]          CHAR (10)     NOT NULL,
    [RefNbr]           CHAR (10)     NOT NULL,
    [S4Future01]       CHAR (30)     NOT NULL,
    [S4Future02]       CHAR (30)     NOT NULL,
    [S4Future03]       FLOAT (53)    NOT NULL,
    [S4Future04]       FLOAT (53)    NOT NULL,
    [S4Future05]       FLOAT (53)    NOT NULL,
    [S4Future06]       FLOAT (53)    NOT NULL,
    [S4Future07]       SMALLDATETIME NOT NULL,
    [S4Future08]       SMALLDATETIME NOT NULL,
    [S4Future09]       INT           NOT NULL,
    [S4Future10]       INT           NOT NULL,
    [S4Future11]       CHAR (10)     NOT NULL,
    [S4Future12]       CHAR (10)     NOT NULL,
    [SiteID]           CHAR (10)     NOT NULL,
    [SOLineRef]        CHAR (5)      NOT NULL,
    [SONbr]            CHAR (10)     NOT NULL,
    [SOType]           CHAR (2)      NOT NULL,
    [TaskID]           CHAR (32)     NOT NULL,
    [UnitCost]         FLOAT (53)    NOT NULL,
    [UnitCostVar]      FLOAT (53)    NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [WOCostType]       CHAR (2)      NOT NULL,
    [WONbr]            CHAR (10)     NOT NULL,
    [WOStepNbr]        CHAR (5)      NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [APTranDT0] PRIMARY KEY CLUSTERED ([RefNbr] ASC, [APLineRef] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

