CREATE TABLE [dbo].[ExmptCreditAudt] (
    [AnnMaxAmt]         FLOAT (53)    NOT NULL,
    [AnnMinAmt]         FLOAT (53)    NOT NULL,
    [Annualize]         SMALLINT      NOT NULL,
    [AudtDate]          CHAR (25)     NOT NULL,
    [AudtDateSort]      CHAR (25)     NOT NULL,
    [BaseDedId]         CHAR (10)     NOT NULL,
    [BaseType]          CHAR (1)      NOT NULL,
    [CalcMthd]          CHAR (2)      NOT NULL,
    [CalYr]             CHAR (4)      NOT NULL,
    [CpnyID]            CHAR (10)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [DedId]             CHAR (10)     NOT NULL,
    [Descr]             CHAR (30)     NOT NULL,
    [ExmptCr]           CHAR (1)      NOT NULL,
    [ExmptCrId]         CHAR (4)      NOT NULL,
    [ExmptID]           CHAR (10)     NOT NULL,
    [FxdPctRate]        FLOAT (53)    NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME NOT NULL,
    [LUpd_Prog]         CHAR (8)      NOT NULL,
    [LUpd_User]         CHAR (10)     NOT NULL,
    [MarStat]           CHAR (1)      NOT NULL,
    [MaxApplyFlg]       CHAR (1)      NOT NULL,
    [NoteId]            INT           NOT NULL,
    [PayTblId]          CHAR (4)      NOT NULL,
    [RedRptEarnSubjDed] SMALLINT      NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [ExmptCreditAudt0] PRIMARY KEY CLUSTERED ([DedId] ASC, [CalYr] ASC, [MarStat] ASC, [ExmptCr] ASC, [ExmptCrId] ASC, [AudtDateSort] ASC)
);

