CREATE TABLE [dbo].[KSYNCTABLESBASE] (
    [TABLENAME]    VARCHAR (32)  NOT NULL,
    [OWNER]        VARCHAR (32)  NOT NULL,
    [SUBJECT_AREA] VARCHAR (128) NULL,
    [LABEL]        VARCHAR (32)  NULL,
    [TYPE]         VARCHAR (16)  NOT NULL,
    [UPDATABLE]    CHAR (1)      NOT NULL,
    [HIDDEN]       CHAR (1)      NOT NULL,
    [DRS_OBJECT]   VARCHAR (32)  NULL,
    [BASE_TABLES]  VARCHAR (254) NULL,
    [REMARKS]      VARCHAR (254) NULL,
    [FIELD_INFO]   VARCHAR (254) NULL,
    PRIMARY KEY CLUSTERED ([TABLENAME] ASC) WITH (FILLFACTOR = 90)
);

