CREATE TABLE [dbo].[PJALERT] (
    [alert_group_cd] CHAR (4)      NOT NULL,
    [alert_id]       SMALLINT      NOT NULL,
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [data1]          CHAR (20)     NOT NULL,
    [data2]          CHAR (30)     NOT NULL,
    [data3]          FLOAT (53)    NOT NULL,
    [employee]       CHAR (10)     NOT NULL,
    [event_id]       CHAR (8)      NOT NULL,
    [last_eval_date] SMALLDATETIME NOT NULL,
    [last_eval_time] SMALLDATETIME NOT NULL,
    [levelnbr]       CHAR (1)      NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [mgr_type]       CHAR (2)      NOT NULL,
    [noteid]         INT           NOT NULL,
    [param1]         FLOAT (53)    NOT NULL,
    [param2]         FLOAT (53)    NOT NULL,
    [param3]         FLOAT (53)    NOT NULL,
    [select_item1]   CHAR (40)     NOT NULL,
    [select_item2]   CHAR (40)     NOT NULL,
    [select_item3]   CHAR (40)     NOT NULL,
    [select_sw]      CHAR (1)      NOT NULL,
    [select_value1]  CHAR (30)     NOT NULL,
    [select_value2]  CHAR (30)     NOT NULL,
    [select_value3]  CHAR (30)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjalert0] PRIMARY KEY CLUSTERED ([alert_group_cd] ASC, [alert_id] ASC) WITH (FILLFACTOR = 90)
);

