CREATE TABLE [dbo].[PJEQRATE] (
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [ec_id01]         CHAR (30)     NOT NULL,
    [ec_id02]         CHAR (30)     NOT NULL,
    [ec_id03]         CHAR (16)     NOT NULL,
    [ec_id04]         CHAR (16)     NOT NULL,
    [ec_id05]         CHAR (4)      NOT NULL,
    [ec_id06]         FLOAT (53)    NOT NULL,
    [ec_id07]         FLOAT (53)    NOT NULL,
    [ec_id08]         SMALLDATETIME NOT NULL,
    [ec_id09]         SMALLDATETIME NOT NULL,
    [ec_id10]         INT           NOT NULL,
    [ec_id11]         CHAR (30)     NOT NULL,
    [ec_id12]         CHAR (30)     NOT NULL,
    [ec_id13]         CHAR (16)     NOT NULL,
    [ec_id14]         CHAR (16)     NOT NULL,
    [ec_id15]         CHAR (4)      NOT NULL,
    [ec_id16]         FLOAT (53)    NOT NULL,
    [ec_id17]         FLOAT (53)    NOT NULL,
    [ec_id18]         SMALLDATETIME NOT NULL,
    [ec_id19]         SMALLDATETIME NOT NULL,
    [ec_id20]         INT           NOT NULL,
    [effect_date]     SMALLDATETIME NOT NULL,
    [equip_id]        CHAR (10)     NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [project]         CHAR (16)     NOT NULL,
    [rate1]           FLOAT (53)    NOT NULL,
    [rate2]           FLOAT (53)    NOT NULL,
    [rate3]           FLOAT (53)    NOT NULL,
    [unit_of_measure] CHAR (10)     NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjeqrate0] PRIMARY KEY CLUSTERED ([equip_id] ASC, [project] ASC, [effect_date] ASC) WITH (FILLFACTOR = 90)
);

