CREATE TABLE [dbo].[smRateCommission] (
    [CommTypeId]    CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtrd_User]    CHAR (10)     NOT NULL,
    [ExtPrice]      FLOAT (53)    NOT NULL,
    [FlatRateId]    CHAR (10)     NOT NULL,
    [InvtId]        CHAR (30)     NOT NULL,
    [LineNbr]       SMALLINT      NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [Quantity]      SMALLINT      NOT NULL,
    [UnitPrice]     FLOAT (53)    NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smRateCommission0] PRIMARY KEY CLUSTERED ([FlatRateId] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

