CREATE TABLE [dbo].[PJPAYDET] (
    [crtd_datetime]      SMALLDATETIME NOT NULL,
    [crtd_prog]          CHAR (8)      NOT NULL,
    [crtd_user]          CHAR (10)     NOT NULL,
    [curr_net_amt]       FLOAT (53)    NOT NULL,
    [curr_rate]          FLOAT (53)    NOT NULL,
    [curr_ret_amt]       FLOAT (53)    NOT NULL,
    [curr_total_amt]     FLOAT (53)    NOT NULL,
    [curr_units]         FLOAT (53)    NOT NULL,
    [Curycurr_net_amt]   FLOAT (53)    NOT NULL,
    [Curycurr_rate]      FLOAT (53)    NOT NULL,
    [Curycurr_ret_amt]   FLOAT (53)    NOT NULL,
    [Curycurr_total_amt] FLOAT (53)    NOT NULL,
    [CuryId]             CHAR (4)      NOT NULL,
    [CuryMultDiv]        CHAR (1)      NOT NULL,
    [CuryRate]           FLOAT (53)    NOT NULL,
    [lupd_datetime]      SMALLDATETIME NOT NULL,
    [lupd_prog]          CHAR (8)      NOT NULL,
    [lupd_user]          CHAR (10)     NOT NULL,
    [noteid]             INT           NOT NULL,
    [payreqnbr]          CHAR (4)      NOT NULL,
    [pd_id01]            CHAR (30)     NOT NULL,
    [pd_id02]            CHAR (30)     NOT NULL,
    [pd_id03]            CHAR (16)     NOT NULL,
    [pd_id04]            CHAR (16)     NOT NULL,
    [pd_id05]            CHAR (4)      NOT NULL,
    [pd_id06]            FLOAT (53)    NOT NULL,
    [pd_id07]            FLOAT (53)    NOT NULL,
    [pd_id08]            SMALLDATETIME NOT NULL,
    [pd_id09]            SMALLDATETIME NOT NULL,
    [pd_id10]            INT           NOT NULL,
    [pd_id11]            CHAR (30)     NOT NULL,
    [pd_id12]            CHAR (30)     NOT NULL,
    [pd_id13]            CHAR (16)     NOT NULL,
    [pd_id14]            CHAR (16)     NOT NULL,
    [pd_id15]            CHAR (4)      NOT NULL,
    [pd_id16]            FLOAT (53)    NOT NULL,
    [pd_id17]            FLOAT (53)    NOT NULL,
    [pd_id18]            SMALLDATETIME NOT NULL,
    [pd_id19]            SMALLDATETIME NOT NULL,
    [pd_id20]            INT           NOT NULL,
    [project]            CHAR (16)     NOT NULL,
    [request_percent]    FLOAT (53)    NOT NULL,
    [status1]            CHAR (1)      NOT NULL,
    [sub_line_item]      CHAR (4)      NOT NULL,
    [subcontract]        CHAR (16)     NOT NULL,
    [user1]              CHAR (30)     NOT NULL,
    [user2]              CHAR (30)     NOT NULL,
    [user3]              FLOAT (53)    NOT NULL,
    [user4]              FLOAT (53)    NOT NULL,
    [user5]              CHAR (30)     NOT NULL,
    [user6]              CHAR (30)     NOT NULL,
    [user7]              FLOAT (53)    NOT NULL,
    [user8]              FLOAT (53)    NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [pjpaydet0] PRIMARY KEY CLUSTERED ([project] ASC, [subcontract] ASC, [payreqnbr] ASC, [sub_line_item] ASC)
);

