CREATE TABLE [dbo].[PJRULIP] (
    [acct]              CHAR (16)     NOT NULL,
    [adj_cpnyid]        CHAR (10)     NOT NULL,
    [adj_gl_acct]       CHAR (10)     NOT NULL,
    [adj_gl_subacct]    CHAR (24)     NOT NULL,
    [bill_type_cd]      CHAR (4)      NOT NULL,
    [cpnyid]            CHAR (10)     NOT NULL,
    [credit_cpnyid]     CHAR (10)     NOT NULL,
    [credit_gl_acct]    CHAR (10)     NOT NULL,
    [credit_gl_subacct] CHAR (24)     NOT NULL,
    [crtd_datetime]     SMALLDATETIME NOT NULL,
    [crtd_prog]         CHAR (8)      NOT NULL,
    [crtd_user]         CHAR (10)     NOT NULL,
    [debit_cpnyid]      CHAR (10)     NOT NULL,
    [debit_gl_acct]     CHAR (10)     NOT NULL,
    [debit_gl_subacct]  CHAR (24)     NOT NULL,
    [gl_acct]           CHAR (10)     NOT NULL,
    [gl_subacct]        CHAR (24)     NOT NULL,
    [lupd_datetime]     SMALLDATETIME NOT NULL,
    [lupd_prog]         CHAR (8)      NOT NULL,
    [lupd_user]         CHAR (10)     NOT NULL,
    [noteid]            INT           NOT NULL,
    [rp_id01]           CHAR (30)     NOT NULL,
    [rp_id02]           CHAR (30)     NOT NULL,
    [rp_id03]           CHAR (16)     NOT NULL,
    [rp_id04]           CHAR (16)     NOT NULL,
    [rp_id05]           CHAR (4)      NOT NULL,
    [rp_id06]           CHAR (4)      NOT NULL,
    [rp_id07]           CHAR (4)      NOT NULL,
    [rp_id08]           CHAR (4)      NOT NULL,
    [rp_id09]           FLOAT (53)    NOT NULL,
    [rp_id10]           SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [pjrulip0] PRIMARY KEY CLUSTERED ([bill_type_cd] ASC, [acct] ASC) WITH (FILLFACTOR = 90)
);

