CREATE TABLE [dbo].[PJADDR] (
    [ad_id01]       CHAR (30)     NOT NULL,
    [ad_id02]       CHAR (30)     NOT NULL,
    [ad_id03]       CHAR (16)     NOT NULL,
    [ad_id04]       CHAR (16)     NOT NULL,
    [ad_id05]       CHAR (4)      NOT NULL,
    [ad_id06]       CHAR (4)      NOT NULL,
    [ad_id07]       FLOAT (53)    NOT NULL,
    [ad_id08]       SMALLDATETIME NOT NULL,
    [addr_key]      CHAR (48)     NOT NULL,
    [addr_key_cd]   CHAR (2)      NOT NULL,
    [addr_type_cd]  CHAR (2)      NOT NULL,
    [addr1]         CHAR (60)     NOT NULL,
    [addr2]         CHAR (60)     NOT NULL,
    [city]          CHAR (30)     NOT NULL,
    [comp_name]     CHAR (60)     NOT NULL,
    [country]       CHAR (3)      NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [email]         CHAR (80)     NOT NULL,
    [fax]           CHAR (15)     NOT NULL,
    [individual]    CHAR (30)     NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [phone]         CHAR (15)     NOT NULL,
    [state]         CHAR (3)      NOT NULL,
    [title]         CHAR (30)     NOT NULL,
    [zip]           CHAR (10)     NOT NULL,
    [user1]         CHAR (30)     NOT NULL,
    [user2]         CHAR (30)     NOT NULL,
    [user3]         FLOAT (53)    NOT NULL,
    [user4]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [pjaddr0] PRIMARY KEY CLUSTERED ([addr_key_cd] ASC, [addr_key] ASC, [addr_type_cd] ASC) WITH (FILLFACTOR = 90)
);

