CREATE TABLE [dbo].[EDSOShipHeader] (
    [BOL]             CHAR (20)     CONSTRAINT [DF_EDSOShipHeader_BOL] DEFAULT (' ') NOT NULL,
    [CpnyId]          CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_CpnyId] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      CONSTRAINT [DF_EDSOShipHeader_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_Crtd_User] DEFAULT (' ') NOT NULL,
    [Height]          FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]       CHAR (6)      CONSTRAINT [DF_EDSOShipHeader_HeightUOM] DEFAULT (' ') NOT NULL,
    [LastEDIDate]     SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_LastEDIDate] DEFAULT ('01/01/1900') NOT NULL,
    [Len]             FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]          CHAR (6)      CONSTRAINT [DF_EDSOShipHeader_LenUOM] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]   SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]       CHAR (8)      CONSTRAINT [DF_EDSOShipHeader_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]       CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_Lupd_User] DEFAULT (' ') NOT NULL,
    [OutboundProcNbr] CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_OutboundProcNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]      CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]      CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]      FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]      FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]      FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]      FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]      SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]      SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]      INT           CONSTRAINT [DF_EDSOShipHeader_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]      INT           CONSTRAINT [DF_EDSOShipHeader_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]      CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]      CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_S4Future12] DEFAULT (' ') NOT NULL,
    [SendViaEDI]      SMALLINT      CONSTRAINT [DF_EDSOShipHeader_SendViaEDI] DEFAULT ((0)) NOT NULL,
    [ShipperId]       CHAR (15)     CONSTRAINT [DF_EDSOShipHeader_ShipperId] DEFAULT (' ') NOT NULL,
    [User1]           CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_User1] DEFAULT (' ') NOT NULL,
    [User10]          SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]           CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_User2] DEFAULT (' ') NOT NULL,
    [User3]           CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_User3] DEFAULT (' ') NOT NULL,
    [User4]           CHAR (30)     CONSTRAINT [DF_EDSOShipHeader_User4] DEFAULT (' ') NOT NULL,
    [User5]           FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_User5] DEFAULT ((0)) NOT NULL,
    [User6]           FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_User6] DEFAULT ((0)) NOT NULL,
    [User7]           SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]           CHAR (10)     CONSTRAINT [DF_EDSOShipHeader_User8] DEFAULT (' ') NOT NULL,
    [User9]           SMALLDATETIME CONSTRAINT [DF_EDSOShipHeader_User9] DEFAULT ('01/01/1900') NOT NULL,
    [Volume]          FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_Volume] DEFAULT ((0)) NOT NULL,
    [VolumeUOM]       CHAR (6)      CONSTRAINT [DF_EDSOShipHeader_VolumeUOM] DEFAULT (' ') NOT NULL,
    [Weight]          FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]       CHAR (6)      CONSTRAINT [DF_EDSOShipHeader_WeightUOM] DEFAULT (' ') NOT NULL,
    [Width]           FLOAT (53)    CONSTRAINT [DF_EDSOShipHeader_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]        CHAR (6)      CONSTRAINT [DF_EDSOShipHeader_WidthUOM] DEFAULT (' ') NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [EDSOShipHeader0] PRIMARY KEY CLUSTERED ([CpnyId] ASC, [ShipperId] ASC, [BOL] ASC) WITH (FILLFACTOR = 90)
);

