CREATE TABLE [dbo].[CSHeader] (
    [CalcExpl]      CHAR (255)    CONSTRAINT [DF_CSHeader_CalcExpl] DEFAULT (' ') NOT NULL,
    [CommAmt]       FLOAT (53)    CONSTRAINT [DF_CSHeader_CommAmt] DEFAULT ((0)) NOT NULL,
    [CommRate]      FLOAT (53)    CONSTRAINT [DF_CSHeader_CommRate] DEFAULT ((0)) NOT NULL,
    [CommTotal]     FLOAT (53)    CONSTRAINT [DF_CSHeader_CommTotal] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_CSHeader_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_CSHeader_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_CSHeader_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCommAmt]   FLOAT (53)    CONSTRAINT [DF_CSHeader_CuryCommAmt] DEFAULT ((0)) NOT NULL,
    [CuryCommTotal] FLOAT (53)    CONSTRAINT [DF_CSHeader_CuryCommTotal] DEFAULT ((0)) NOT NULL,
    [CuryDocTotal]  FLOAT (53)    CONSTRAINT [DF_CSHeader_CuryDocTotal] DEFAULT ((0)) NOT NULL,
    [CuryPlusAmt]   FLOAT (53)    CONSTRAINT [DF_CSHeader_CuryPlusAmt] DEFAULT ((0)) NOT NULL,
    [CustID]        CHAR (15)     CONSTRAINT [DF_CSHeader_CustID] DEFAULT (' ') NOT NULL,
    [DocDate]       SMALLDATETIME CONSTRAINT [DF_CSHeader_DocDate] DEFAULT ('01/01/1900') NOT NULL,
    [DocDesc]       CHAR (30)     CONSTRAINT [DF_CSHeader_DocDesc] DEFAULT (' ') NOT NULL,
    [DocTotal]      FLOAT (53)    CONSTRAINT [DF_CSHeader_DocTotal] DEFAULT ((0)) NOT NULL,
    [DocType]       CHAR (1)      CONSTRAINT [DF_CSHeader_DocType] DEFAULT (' ') NOT NULL,
    [InvcNbr]       CHAR (10)     CONSTRAINT [DF_CSHeader_InvcNbr] DEFAULT (' ') NOT NULL,
    [LineCntr]      SMALLINT      CONSTRAINT [DF_CSHeader_LineCntr] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_CSHeader_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_CSHeader_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_CSHeader_LUpd_User] DEFAULT (' ') NOT NULL,
    [NetCommPct]    FLOAT (53)    CONSTRAINT [DF_CSHeader_NetCommPct] DEFAULT ((0)) NOT NULL,
    [NetGMPct]      FLOAT (53)    CONSTRAINT [DF_CSHeader_NetGMPct] DEFAULT ((0)) NOT NULL,
    [NetSplitPct]   FLOAT (53)    CONSTRAINT [DF_CSHeader_NetSplitPct] DEFAULT ((0)) NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_CSHeader_NoteID] DEFAULT ((0)) NOT NULL,
    [OrdNbr]        CHAR (10)     CONSTRAINT [DF_CSHeader_OrdNbr] DEFAULT (' ') NOT NULL,
    [PlusAmt]       FLOAT (53)    CONSTRAINT [DF_CSHeader_PlusAmt] DEFAULT ((0)) NOT NULL,
    [PlusMult]      FLOAT (53)    CONSTRAINT [DF_CSHeader_PlusMult] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_CSHeader_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_CSHeader_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_CSHeader_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_CSHeader_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_CSHeader_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_CSHeader_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_CSHeader_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_CSHeader_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_CSHeader_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_CSHeader_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_CSHeader_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_CSHeader_S4Future12] DEFAULT (' ') NOT NULL,
    [Status]        CHAR (1)      CONSTRAINT [DF_CSHeader_Status] DEFAULT (' ') NOT NULL,
    [StmntID]       CHAR (10)     CONSTRAINT [DF_CSHeader_StmntID] DEFAULT (' ') NOT NULL,
    [TotExtCost]    FLOAT (53)    CONSTRAINT [DF_CSHeader_TotExtCost] DEFAULT ((0)) NOT NULL,
    [TotExtPrice]   FLOAT (53)    CONSTRAINT [DF_CSHeader_TotExtPrice] DEFAULT ((0)) NOT NULL,
    [TranRef]       CHAR (5)      CONSTRAINT [DF_CSHeader_TranRef] DEFAULT (' ') NOT NULL,
    [TranType]      CHAR (2)      CONSTRAINT [DF_CSHeader_TranType] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_CSHeader_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_CSHeader_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_CSHeader_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_CSHeader_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_CSHeader_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_CSHeader_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_CSHeader_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_CSHeader_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_CSHeader_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_CSHeader_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CSHeader0] PRIMARY KEY CLUSTERED ([StmntID] ASC, [TranRef] ASC) WITH (FILLFACTOR = 90)
);

