CREATE TABLE [dbo].[WrkSUTAG] (
    [CpnyID]              CHAR (10)     NOT NULL,
    [FICAWageLimit]       FLOAT (53)    NOT NULL,
    [GLAddr1]             CHAR (30)     NOT NULL,
    [GLAddr2]             CHAR (30)     NOT NULL,
    [GLCity]              CHAR (30)     NOT NULL,
    [GLCpnyName]          CHAR (30)     NOT NULL,
    [GLState]             CHAR (3)      NOT NULL,
    [GLZip]               CHAR (10)     NOT NULL,
    [QtrBegDate]          SMALLDATETIME NOT NULL,
    [QtrEndDate]          SMALLDATETIME NOT NULL,
    [RptQtr]              SMALLINT      NOT NULL,
    [RptYr]               CHAR (4)      NOT NULL,
    [StateName]           CHAR (15)     NOT NULL,
    [StateTaxId]          CHAR (20)     NOT NULL,
    [StateWageLimit]      FLOAT (53)    NOT NULL,
    [SUTAId]              CHAR (10)     NOT NULL,
    [TaxRate]             FLOAT (53)    NOT NULL,
    [TotQTDFICAWages]     FLOAT (53)    NOT NULL,
    [TotQTDNonWageIncome] FLOAT (53)    NOT NULL,
    [TotQTDStateWages]    FLOAT (53)    NOT NULL,
    [TotQTDTaxableWages]  FLOAT (53)    NOT NULL,
    [TotSUTATax]          FLOAT (53)    NOT NULL,
    [TotYTDFICAWages]     FLOAT (53)    NOT NULL,
    [UserId]              CHAR (47)     NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [WrkSUTAG0] PRIMARY KEY CLUSTERED ([UserId] ASC) WITH (FILLFACTOR = 90)
);

