CREATE TABLE [dbo].[SMWrkDetailInv] (
    [Acct]         CHAR (10)     NOT NULL,
    [ARBatNbr]     CHAR (10)     NOT NULL,
    [CmmnAmt]      FLOAT (53)    NOT NULL,
    [CmmnPct]      FLOAT (53)    NOT NULL,
    [COGSAcct]     CHAR (10)     NOT NULL,
    [COGSSub]      CHAR (24)     NOT NULL,
    [ContractID]   CHAR (10)     NOT NULL,
    [Cost]         FLOAT (53)    NOT NULL,
    [CpnyId]       CHAR (10)     NOT NULL,
    [CustId]       CHAR (15)     NOT NULL,
    [Description]  CHAR (60)     NOT NULL,
    [DetailType]   CHAR (1)      NOT NULL,
    [DocType]      CHAR (1)      NOT NULL,
    [DocumentID]   CHAR (10)     NOT NULL,
    [EarnMult]     FLOAT (53)    NOT NULL,
    [EmpID]        CHAR (10)     NOT NULL,
    [EmpPRID]      CHAR (10)     NOT NULL,
    [EquipID]      CHAR (10)     NOT NULL,
    [ExtPrice]     FLOAT (53)    NOT NULL,
    [ExtRefNbr]    CHAR (15)     NOT NULL,
    [InvBatNbr]    CHAR (10)     NOT NULL,
    [InvoiceNbr]   CHAR (10)     NOT NULL,
    [Invtid]       CHAR (30)     NOT NULL,
    [LineID]       SMALLINT      NOT NULL,
    [LineNbr]      SMALLINT      NOT NULL,
    [LineTypes]    CHAR (1)      NOT NULL,
    [LotSerialPU]  CHAR (25)     NOT NULL,
    [LotSerialRep] CHAR (25)     NOT NULL,
    [NoteID]       INT           NOT NULL,
    [PerEnt]       CHAR (6)      NOT NULL,
    [PerPost]      CHAR (6)      NOT NULL,
    [Quantity]     FLOAT (53)    NOT NULL,
    [Refnbr]       CHAR (10)     NOT NULL,
    [RI_ID]        SMALLINT      NOT NULL,
    [SiteID]       CHAR (10)     NOT NULL,
    [SlsperID]     CHAR (10)     NOT NULL,
    [SpecCostID]   CHAR (25)     NOT NULL,
    [StdCost]      FLOAT (53)    NOT NULL,
    [Sub]          CHAR (24)     NOT NULL,
    [TaskID]       CHAR (32)     NOT NULL,
    [TaxAmt00]     FLOAT (53)    NOT NULL,
    [TaxAmt01]     FLOAT (53)    NOT NULL,
    [TaxAmt02]     FLOAT (53)    NOT NULL,
    [TaxAmt03]     FLOAT (53)    NOT NULL,
    [TaxExempt]    CHAR (1)      NOT NULL,
    [TaxID00]      CHAR (10)     NOT NULL,
    [TaxID01]      CHAR (10)     NOT NULL,
    [TaxID02]      CHAR (10)     NOT NULL,
    [TaxID03]      CHAR (10)     NOT NULL,
    [TranAmt]      FLOAT (53)    NOT NULL,
    [TranDate]     SMALLDATETIME NOT NULL,
    [TxblAmt00]    FLOAT (53)    NOT NULL,
    [TxblAmt01]    FLOAT (53)    NOT NULL,
    [TxblAmt02]    FLOAT (53)    NOT NULL,
    [TxblAmt03]    FLOAT (53)    NOT NULL,
    [UnitPrice]    FLOAT (53)    NOT NULL,
    [User1]        CHAR (30)     NOT NULL,
    [User2]        CHAR (30)     NOT NULL,
    [User3]        FLOAT (53)    NOT NULL,
    [User4]        FLOAT (53)    NOT NULL,
    [User5]        CHAR (10)     NOT NULL,
    [User6]        CHAR (10)     NOT NULL,
    [User7]        SMALLDATETIME NOT NULL,
    [User8]        SMALLDATETIME NOT NULL,
    [User9]        SMALLINT      NOT NULL,
    [WhseLoc]      CHAR (10)     NOT NULL,
    [WorkHr]       FLOAT (53)    NOT NULL,
    [tstamp]       ROWVERSION    NOT NULL,
    CONSTRAINT [smWrkDetailInv0] PRIMARY KEY CLUSTERED ([InvBatNbr] ASC, [DocType] ASC, [Refnbr] ASC, [DocumentID] ASC, [LineID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [smWrkDetailInv1]
    ON [dbo].[SMWrkDetailInv]([RI_ID] ASC, [Refnbr] ASC, [LineID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [smWrkDetailInv2]
    ON [dbo].[SMWrkDetailInv]([InvBatNbr] ASC, [Refnbr] ASC, [DocumentID] ASC, [ContractID] ASC, [LineID] ASC) WITH (FILLFACTOR = 90);

