CREATE TABLE [dbo].[ItemHist] (
    [BegBal]            FLOAT (53)    CONSTRAINT [DF_ItemHist_BegBal] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME CONSTRAINT [DF_ItemHist_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      CONSTRAINT [DF_ItemHist_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     CONSTRAINT [DF_ItemHist_Crtd_User] DEFAULT (' ') NOT NULL,
    [FiscYr]            CHAR (4)      CONSTRAINT [DF_ItemHist_FiscYr] DEFAULT (' ') NOT NULL,
    [InvtID]            CHAR (30)     CONSTRAINT [DF_ItemHist_InvtID] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME CONSTRAINT [DF_ItemHist_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      CONSTRAINT [DF_ItemHist_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     CONSTRAINT [DF_ItemHist_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]            INT           CONSTRAINT [DF_ItemHist_NoteID] DEFAULT ((0)) NOT NULL,
    [PerNbr]            CHAR (6)      CONSTRAINT [DF_ItemHist_PerNbr] DEFAULT (' ') NOT NULL,
    [PTDCOGS00]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS00] DEFAULT ((0)) NOT NULL,
    [PTDCOGS01]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS01] DEFAULT ((0)) NOT NULL,
    [PTDCOGS02]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS02] DEFAULT ((0)) NOT NULL,
    [PTDCOGS03]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS03] DEFAULT ((0)) NOT NULL,
    [PTDCOGS04]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS04] DEFAULT ((0)) NOT NULL,
    [PTDCOGS05]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS05] DEFAULT ((0)) NOT NULL,
    [PTDCOGS06]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS06] DEFAULT ((0)) NOT NULL,
    [PTDCOGS07]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS07] DEFAULT ((0)) NOT NULL,
    [PTDCOGS08]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS08] DEFAULT ((0)) NOT NULL,
    [PTDCOGS09]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS09] DEFAULT ((0)) NOT NULL,
    [PTDCOGS10]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS10] DEFAULT ((0)) NOT NULL,
    [PTDCOGS11]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS11] DEFAULT ((0)) NOT NULL,
    [PTDCOGS12]         FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCOGS12] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd00]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd00] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd01]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd01] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd02]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd02] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd03]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd03] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd04]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd04] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd05]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd05] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd06]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd06] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd07]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd07] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd08]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd08] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd09]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd09] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd10]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd10] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd11]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd11] DEFAULT ((0)) NOT NULL,
    [PTDCostAdjd12]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostAdjd12] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd00]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd00] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd01]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd01] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd02]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd02] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd03]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd03] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd04]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd04] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd05]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd05] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd06]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd06] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd07]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd07] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd08]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd08] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd09]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd09] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd10]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd10] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd11]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd11] DEFAULT ((0)) NOT NULL,
    [PTDCostIssd12]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostIssd12] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd00]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd00] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd01]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd01] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd02]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd02] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd03]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd03] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd04]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd04] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd05]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd05] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd06]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd06] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd07]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd07] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd08]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd08] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd09]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd09] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd10]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd10] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd11]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd11] DEFAULT ((0)) NOT NULL,
    [PTDCostRcvd12]     FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostRcvd12] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn00]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn00] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn01]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn01] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn02]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn02] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn03]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn03] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn04]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn04] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn05]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn05] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn06]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn06] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn07]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn07] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn08]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn08] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn09]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn09] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn10]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn10] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn11]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn11] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrIn12]  FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrIn12] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut00] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut00] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut01] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut01] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut02] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut02] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut03] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut03] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut04] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut04] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut05] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut05] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut06] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut06] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut07] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut07] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut08] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut08] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut09] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut09] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut10] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut10] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut11] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut11] DEFAULT ((0)) NOT NULL,
    [PTDCostTrsfrOut12] FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDCostTrsfrOut12] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls00]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls00] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls01]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls01] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls02]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls02] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls03]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls03] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls04]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls04] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls05]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls05] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls06]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls06] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls07]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls07] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls08]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls08] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls09]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls09] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls10]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls10] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls11]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls11] DEFAULT ((0)) NOT NULL,
    [PTDDShpSls12]      FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDDShpSls12] DEFAULT ((0)) NOT NULL,
    [PTDSls00]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls00] DEFAULT ((0)) NOT NULL,
    [PTDSls01]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls01] DEFAULT ((0)) NOT NULL,
    [PTDSls02]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls02] DEFAULT ((0)) NOT NULL,
    [PTDSls03]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls03] DEFAULT ((0)) NOT NULL,
    [PTDSls04]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls04] DEFAULT ((0)) NOT NULL,
    [PTDSls05]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls05] DEFAULT ((0)) NOT NULL,
    [PTDSls06]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls06] DEFAULT ((0)) NOT NULL,
    [PTDSls07]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls07] DEFAULT ((0)) NOT NULL,
    [PTDSls08]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls08] DEFAULT ((0)) NOT NULL,
    [PTDSls09]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls09] DEFAULT ((0)) NOT NULL,
    [PTDSls10]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls10] DEFAULT ((0)) NOT NULL,
    [PTDSls11]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls11] DEFAULT ((0)) NOT NULL,
    [PTDSls12]          FLOAT (53)    CONSTRAINT [DF_ItemHist_PTDSls12] DEFAULT ((0)) NOT NULL,
    [S4Future01]        CHAR (30)     CONSTRAINT [DF_ItemHist_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     CONSTRAINT [DF_ItemHist_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    CONSTRAINT [DF_ItemHist_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    CONSTRAINT [DF_ItemHist_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    CONSTRAINT [DF_ItemHist_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    CONSTRAINT [DF_ItemHist_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME CONSTRAINT [DF_ItemHist_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME CONSTRAINT [DF_ItemHist_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           CONSTRAINT [DF_ItemHist_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           CONSTRAINT [DF_ItemHist_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     CONSTRAINT [DF_ItemHist_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     CONSTRAINT [DF_ItemHist_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]            CHAR (10)     CONSTRAINT [DF_ItemHist_SiteID] DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     CONSTRAINT [DF_ItemHist_User1] DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     CONSTRAINT [DF_ItemHist_User2] DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    CONSTRAINT [DF_ItemHist_User3] DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    CONSTRAINT [DF_ItemHist_User4] DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     CONSTRAINT [DF_ItemHist_User5] DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     CONSTRAINT [DF_ItemHist_User6] DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME CONSTRAINT [DF_ItemHist_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME CONSTRAINT [DF_ItemHist_User8] DEFAULT ('01/01/1900') NOT NULL,
    [YTDCOGS]           FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCOGS] DEFAULT ((0)) NOT NULL,
    [YTDCostAdjd]       FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCostAdjd] DEFAULT ((0)) NOT NULL,
    [YTDCostIssd]       FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCostIssd] DEFAULT ((0)) NOT NULL,
    [YTDCostRcvd]       FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCostRcvd] DEFAULT ((0)) NOT NULL,
    [YTDCostTrsfrIn]    FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCostTrsfrIn] DEFAULT ((0)) NOT NULL,
    [YTDCostTrsfrOut]   FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDCostTrsfrOut] DEFAULT ((0)) NOT NULL,
    [YTDDShpSls]        FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDDShpSls] DEFAULT ((0)) NOT NULL,
    [YTDSls]            FLOAT (53)    CONSTRAINT [DF_ItemHist_YTDSls] DEFAULT ((0)) NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [ItemHist0] PRIMARY KEY CLUSTERED ([InvtID] ASC, [SiteID] ASC, [FiscYr] ASC) WITH (FILLFACTOR = 100)
);

