CREATE TABLE [dbo].[IRSetup] (
    [CentDistMthd]     SMALLINT      CONSTRAINT [DF_IRSetup_CentDistMthd] DEFAULT ((0)) NOT NULL,
    [Crtd_Datetime]    SMALLDATETIME CONSTRAINT [DF_IRSetup_Crtd_Datetime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_IRSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_IRSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [DemPeriodNbr]     INT           CONSTRAINT [DF_IRSetup_DemPeriodNbr] DEFAULT ((0)) NOT NULL,
    [DemTranDate]      SMALLDATETIME CONSTRAINT [DF_IRSetup_DemTranDate] DEFAULT ('01/01/1900') NOT NULL,
    [DemTranTime]      SMALLDATETIME CONSTRAINT [DF_IRSetup_DemTranTime] DEFAULT ('01/01/1900') NOT NULL,
    [DemTranUserID]    CHAR (10)     CONSTRAINT [DF_IRSetup_DemTranUserID] DEFAULT (' ') NOT NULL,
    [EOQCarryCostPct]  FLOAT (53)    CONSTRAINT [DF_IRSetup_EOQCarryCostPct] DEFAULT ((0)) NOT NULL,
    [EOQReordCost]     FLOAT (53)    CONSTRAINT [DF_IRSetup_EOQReordCost] DEFAULT ((0)) NOT NULL,
    [ExclNonRecurTran] SMALLINT      CONSTRAINT [DF_IRSetup_ExclNonRecurTran] DEFAULT ((0)) NOT NULL,
    [IncludeDropShip]  SMALLINT      CONSTRAINT [DF_IRSetup_IncludeDropShip] DEFAULT ((0)) NOT NULL,
    [LTPeriodNbr]      INT           CONSTRAINT [DF_IRSetup_LTPeriodNbr] DEFAULT ((0)) NOT NULL,
    [Lupd_Datetime]    SMALLDATETIME CONSTRAINT [DF_IRSetup_Lupd_Datetime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]        CHAR (8)      CONSTRAINT [DF_IRSetup_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]        CHAR (10)     CONSTRAINT [DF_IRSetup_Lupd_User] DEFAULT (' ') NOT NULL,
    [NbrPerRtnDem]     INT           CONSTRAINT [DF_IRSetup_NbrPerRtnDem] DEFAULT ((0)) NOT NULL,
    [NextPlanOrdNbr]   CHAR (15)     CONSTRAINT [DF_IRSetup_NextPlanOrdNbr] DEFAULT (' ') NOT NULL,
    [PeriodLength]     INT           CONSTRAINT [DF_IRSetup_PeriodLength] DEFAULT ((0)) NOT NULL,
    [PlanOrdDate]      SMALLDATETIME CONSTRAINT [DF_IRSetup_PlanOrdDate] DEFAULT ('01/01/1900') NOT NULL,
    [PlanOrdStartDate] SMALLDATETIME CONSTRAINT [DF_IRSetup_PlanOrdStartDate] DEFAULT ('01/01/1900') NOT NULL,
    [PlanOrdTime]      SMALLDATETIME CONSTRAINT [DF_IRSetup_PlanOrdTime] DEFAULT ('01/01/1900') NOT NULL,
    [PlanOrdUserID]    CHAR (10)     CONSTRAINT [DF_IRSetup_PlanOrdUserID] DEFAULT (' ') NOT NULL,
    [ReplenValDate]    SMALLDATETIME CONSTRAINT [DF_IRSetup_ReplenValDate] DEFAULT ('01/01/1900') NOT NULL,
    [ReplenValTime]    SMALLDATETIME CONSTRAINT [DF_IRSetup_ReplenValTime] DEFAULT ('01/01/1900') NOT NULL,
    [ReplenValUserID]  CHAR (10)     CONSTRAINT [DF_IRSetup_ReplenValUserID] DEFAULT (' ') NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_IRSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_IRSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_IRSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_IRSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_IRSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_IRSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_IRSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_IRSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_IRSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_IRSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_IRSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_IRSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [SetupID]          CHAR (2)      CONSTRAINT [DF_IRSetup_SetupID] DEFAULT (' ') NOT NULL,
    [ShipViaID]        CHAR (15)     CONSTRAINT [DF_IRSetup_ShipViaID] DEFAULT (' ') NOT NULL,
    [SrvLvlPeriodNbr]  INT           CONSTRAINT [DF_IRSetup_SrvLvlPeriodNbr] DEFAULT ((0)) NOT NULL,
    [TOPeriodNbr]      INT           CONSTRAINT [DF_IRSetup_TOPeriodNbr] DEFAULT ((0)) NOT NULL,
    [TransferDays]     INT           CONSTRAINT [DF_IRSetup_TransferDays] DEFAULT ((0)) NOT NULL,
    [UseBookings]      SMALLINT      CONSTRAINT [DF_IRSetup_UseBookings] DEFAULT ((0)) NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_IRSetup_User1] DEFAULT (' ') NOT NULL,
    [User10]           SMALLDATETIME CONSTRAINT [DF_IRSetup_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_IRSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]            CHAR (30)     CONSTRAINT [DF_IRSetup_User3] DEFAULT (' ') NOT NULL,
    [User4]            CHAR (30)     CONSTRAINT [DF_IRSetup_User4] DEFAULT (' ') NOT NULL,
    [User5]            FLOAT (53)    CONSTRAINT [DF_IRSetup_User5] DEFAULT ((0)) NOT NULL,
    [User6]            FLOAT (53)    CONSTRAINT [DF_IRSetup_User6] DEFAULT ((0)) NOT NULL,
    [User7]            CHAR (10)     CONSTRAINT [DF_IRSetup_User7] DEFAULT (' ') NOT NULL,
    [User8]            CHAR (10)     CONSTRAINT [DF_IRSetup_User8] DEFAULT (' ') NOT NULL,
    [User9]            SMALLDATETIME CONSTRAINT [DF_IRSetup_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [IRSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

