CREATE TABLE [dbo].[IN10990_ItemSite] (
    [AvgCost]       FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_AvgCost] DEFAULT ((0)) NOT NULL,
    [BMIAvgCost]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMIAvgCost] DEFAULT ((0)) NOT NULL,
    [BMIDirStdCst]  FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMIDirStdCst] DEFAULT ((0)) NOT NULL,
    [BMIFOvhStdCst] FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMIFOvhStdCst] DEFAULT ((0)) NOT NULL,
    [BMILastCost]   FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMILastCost] DEFAULT ((0)) NOT NULL,
    [BMIStdCost]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMIStdCost] DEFAULT ((0)) NOT NULL,
    [BMITotCost]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMITotCost] DEFAULT ((0)) NOT NULL,
    [BMIVOvhStdCst] FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_BMIVOvhStdCst] DEFAULT ((0)) NOT NULL,
    [Changed]       BIT           NOT NULL,
    [CpnyID]        CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_IN10990_ItemSite_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_Crtd_User] DEFAULT (' ') NOT NULL,
    [DirStdCst]     FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_DirStdCst] DEFAULT ((0)) NOT NULL,
    [FOvhStdCst]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_FOvhStdCst] DEFAULT ((0)) NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_IN10990_ItemSite_InvtID] DEFAULT (' ') NOT NULL,
    [LastCost]      FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_LastCost] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_IN10990_ItemSite_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_LUpd_User] DEFAULT (' ') NOT NULL,
    [MstStamp]      BINARY (8)    NOT NULL,
    [MaxOnHand]     FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_MaxOnHand] DEFAULT ((0)) NOT NULL,
    [QtyOnHand]     FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_QtyOnHand] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_IN10990_ItemSite_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_IN10990_ItemSite_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_IN10990_ItemSite_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_IN10990_ItemSite_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]        CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_SiteID] DEFAULT (' ') NOT NULL,
    [StdCost]       FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_StdCost] DEFAULT ((0)) NOT NULL,
    [StdCostDate]   SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_StdCostDate] DEFAULT ('01/01/1900') NOT NULL,
    [TotCost]       FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_TotCost] DEFAULT ((0)) NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_IN10990_ItemSite_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_IN10990_ItemSite_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_IN10990_ItemSite_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_IN10990_ItemSite_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VOvhStdCst]    FLOAT (53)    CONSTRAINT [DF_IN10990_ItemSite_VOvhStdCst] DEFAULT ((0)) NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [IN10990_ItemSite0] PRIMARY KEY CLUSTERED ([InvtID] ASC, [SiteID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IN10990_ItemSite1]
    ON [dbo].[IN10990_ItemSite]([SiteID] ASC, [InvtID] ASC) WITH (FILLFACTOR = 90);

