CREATE TABLE [dbo].[smMedCoop] (
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [LineNbr]         SMALLINT      NOT NULL,
    [Lupd_DateTime]   SMALLDATETIME NOT NULL,
    [Lupd_Prog]       CHAR (8)      NOT NULL,
    [Lupd_User]       CHAR (10)     NOT NULL,
    [MedCoopAddress1] CHAR (30)     NOT NULL,
    [MedCoopAddress2] CHAR (30)     NOT NULL,
    [MedCoopBuyId]    CHAR (10)     NOT NULL,
    [MedCoopCity]     CHAR (30)     NOT NULL,
    [MedCoopContact]  CHAR (30)     NOT NULL,
    [MedCoopFaxNo]    CHAR (15)     NOT NULL,
    [MedCoopName]     CHAR (30)     NOT NULL,
    [MedCoopPaid]     CHAR (1)      NOT NULL,
    [MedCoopPct]      FLOAT (53)    NOT NULL,
    [MedCoopPhoneNo]  CHAR (15)     NOT NULL,
    [MedCoopState]    CHAR (3)      NOT NULL,
    [MedCoopVendorId] CHAR (15)     NOT NULL,
    [MedCoopZip]      CHAR (10)     NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [smMedCoop0] PRIMARY KEY CLUSTERED ([MedCoopBuyId] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

