CREATE TABLE [dbo].[AP_PPApplicDet] (
    [AppliedDocAmt]      FLOAT (53)    NOT NULL,
    [AppliedDocBalance]  FLOAT (53)    NOT NULL,
    [AppliedDocDate]     SMALLDATETIME NOT NULL,
    [AppliedDocType]     CHAR (2)      NOT NULL,
    [ApplyingDocAmt]     FLOAT (53)    NOT NULL,
    [ApplyingDocBalance] FLOAT (53)    NOT NULL,
    [ApplyingDocDate]    SMALLDATETIME NOT NULL,
    [BatNbr]             CHAR (10)     NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME NOT NULL,
    [Crtd_Prog]          CHAR (8)      NOT NULL,
    [Crtd_User]          CHAR (10)     NOT NULL,
    [CuryApplyAmt]       FLOAT (53)    NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME NOT NULL,
    [LUpd_Prog]          CHAR (8)      NOT NULL,
    [LUpd_User]          CHAR (10)     NOT NULL,
    [OperType]           CHAR (1)      NOT NULL,
    [PPRefNbr]           CHAR (10)     NOT NULL,
    [Rlsed]              SMALLINT      NOT NULL,
    [S4Future01]         CHAR (30)     NOT NULL,
    [S4Future02]         CHAR (30)     NOT NULL,
    [S4Future03]         FLOAT (53)    NOT NULL,
    [S4Future04]         FLOAT (53)    NOT NULL,
    [S4Future05]         FLOAT (53)    NOT NULL,
    [S4Future06]         FLOAT (53)    NOT NULL,
    [S4Future07]         SMALLDATETIME NOT NULL,
    [S4Future08]         SMALLDATETIME NOT NULL,
    [S4Future09]         INT           NOT NULL,
    [S4Future10]         INT           NOT NULL,
    [S4Future11]         CHAR (10)     NOT NULL,
    [S4Future12]         CHAR (10)     NOT NULL,
    [User1]              CHAR (30)     NOT NULL,
    [User2]              CHAR (30)     NOT NULL,
    [User3]              FLOAT (53)    NOT NULL,
    [User4]              FLOAT (53)    NOT NULL,
    [User5]              CHAR (10)     NOT NULL,
    [User6]              CHAR (10)     NOT NULL,
    [User7]              SMALLDATETIME NOT NULL,
    [User8]              SMALLDATETIME NOT NULL,
    [VORefNbr]           CHAR (10)     NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [AP_PPApplicDet0] PRIMARY KEY NONCLUSTERED ([BatNbr] ASC, [VORefNbr] ASC, [PPRefNbr] ASC)
);

