CREATE TABLE [dbo].[IRPlanOrd] (
    [Buyer]          CHAR (10)     CONSTRAINT [DF_IRPlanOrd_Buyer] DEFAULT (' ') NOT NULL,
    [CnvFact]        FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_CnvFact] DEFAULT ((0)) NOT NULL,
    [CpnyID]         CHAR (10)     CONSTRAINT [DF_IRPlanOrd_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_Datetime]  SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_Crtd_Datetime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]      CHAR (8)      CONSTRAINT [DF_IRPlanOrd_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]      CHAR (10)     CONSTRAINT [DF_IRPlanOrd_Crtd_User] DEFAULT (' ') NOT NULL,
    [FinishDate]     SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_FinishDate] DEFAULT ('01/01/1900') NOT NULL,
    [FirmedDate]     SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_FirmedDate] DEFAULT ('01/01/1900') NOT NULL,
    [InvtID]         CHAR (30)     CONSTRAINT [DF_IRPlanOrd_InvtID] DEFAULT (' ') NOT NULL,
    [IRDocType]      CHAR (2)      CONSTRAINT [DF_IRPlanOrd_IRDocType] DEFAULT (' ') NOT NULL,
    [LeadTime]       INT           CONSTRAINT [DF_IRPlanOrd_LeadTime] DEFAULT ((0)) NOT NULL,
    [Lupd_Datetime]  SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_Lupd_Datetime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]      CHAR (8)      CONSTRAINT [DF_IRPlanOrd_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]      CHAR (10)     CONSTRAINT [DF_IRPlanOrd_Lupd_User] DEFAULT (' ') NOT NULL,
    [Planner]        CHAR (10)     CONSTRAINT [DF_IRPlanOrd_Planner] DEFAULT (' ') NOT NULL,
    [PlanOrdNbr]     CHAR (15)     CONSTRAINT [DF_IRPlanOrd_PlanOrdNbr] DEFAULT (' ') NOT NULL,
    [PlanQty]        FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_PlanQty] DEFAULT ((0)) NOT NULL,
    [S4Future01]     CHAR (30)     CONSTRAINT [DF_IRPlanOrd_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]     CHAR (30)     CONSTRAINT [DF_IRPlanOrd_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]     FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]     FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]     FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]     FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]     SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]     SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]     INT           CONSTRAINT [DF_IRPlanOrd_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]     INT           CONSTRAINT [DF_IRPlanOrd_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]     CHAR (10)     CONSTRAINT [DF_IRPlanOrd_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]     CHAR (10)     CONSTRAINT [DF_IRPlanOrd_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipViaID]      CHAR (15)     CONSTRAINT [DF_IRPlanOrd_ShipViaID] DEFAULT (' ') NOT NULL,
    [SiteID]         CHAR (10)     CONSTRAINT [DF_IRPlanOrd_SiteID] DEFAULT (' ') NOT NULL,
    [SolDocID]       CHAR (15)     CONSTRAINT [DF_IRPlanOrd_SolDocID] DEFAULT (' ') NOT NULL,
    [StartDate]      SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Status]         CHAR (2)      CONSTRAINT [DF_IRPlanOrd_Status] DEFAULT (' ') NOT NULL,
    [TransferSiteID] CHAR (10)     CONSTRAINT [DF_IRPlanOrd_TransferSiteID] DEFAULT (' ') NOT NULL,
    [UnitDesc]       CHAR (6)      CONSTRAINT [DF_IRPlanOrd_UnitDesc] DEFAULT (' ') NOT NULL,
    [UnitMultDiv]    CHAR (1)      CONSTRAINT [DF_IRPlanOrd_UnitMultDiv] DEFAULT (' ') NOT NULL,
    [User1]          CHAR (30)     CONSTRAINT [DF_IRPlanOrd_User1] DEFAULT (' ') NOT NULL,
    [User10]         SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]          CHAR (30)     CONSTRAINT [DF_IRPlanOrd_User2] DEFAULT (' ') NOT NULL,
    [User3]          CHAR (30)     CONSTRAINT [DF_IRPlanOrd_User3] DEFAULT (' ') NOT NULL,
    [User4]          CHAR (30)     CONSTRAINT [DF_IRPlanOrd_User4] DEFAULT (' ') NOT NULL,
    [User5]          FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_User5] DEFAULT ((0)) NOT NULL,
    [User6]          FLOAT (53)    CONSTRAINT [DF_IRPlanOrd_User6] DEFAULT ((0)) NOT NULL,
    [User7]          CHAR (10)     CONSTRAINT [DF_IRPlanOrd_User7] DEFAULT (' ') NOT NULL,
    [User8]          CHAR (10)     CONSTRAINT [DF_IRPlanOrd_User8] DEFAULT (' ') NOT NULL,
    [User9]          SMALLDATETIME CONSTRAINT [DF_IRPlanOrd_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]         CHAR (15)     CONSTRAINT [DF_IRPlanOrd_VendID] DEFAULT (' ') NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [IRPlanOrd0] PRIMARY KEY CLUSTERED ([PlanOrdNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IRPlanOrd1]
    ON [dbo].[IRPlanOrd]([InvtID] ASC, [SiteID] ASC, [Status] ASC) WITH (FILLFACTOR = 90);

