CREATE TABLE [dbo].[PJPFTUSER] (
    [Crtd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]            CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]            CHAR (10)     DEFAULT ('') NOT NULL,
    [DayRange]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [DecPlHrs]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Cust_Chars]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Cust_Code]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Oper_Chars]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Oper_Code]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Proj_Chars]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Proj_Code]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Task_Chars]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Desc_Task_Code]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_CmplStep]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_CmplTask]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_Order]        CHAR (1)      DEFAULT ('') NOT NULL,
    [Display_ProjActive]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_ProjInActive] SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_ProjPlan]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_TaskActive]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_TaskInActive] SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_TaskPlan]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Display_WeekEnd]      CHAR (1)      DEFAULT ('') NOT NULL,
    [Employee]             CHAR (10)     DEFAULT ('') NOT NULL,
    [FontSize]             CHAR (5)      DEFAULT ('') NOT NULL,
    [IntervalFut]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [IntervalPast]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]            CHAR (10)     DEFAULT ('') NOT NULL,
    [NoteID]               INT           DEFAULT ((0)) NOT NULL,
    [Prox_AmtYellowN]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Prox_AmtYellowP]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Prox_DateYellowN]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Prox_DateYellowP]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Prox_HrsYellowN]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Prox_HrsYellowP]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [S4Future01]           CHAR (30)     DEFAULT ('') NOT NULL,
    [S4Future02]           CHAR (30)     DEFAULT ('') NOT NULL,
    [S4Future03]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     DEFAULT ('') NOT NULL,
    [S4Future12]           CHAR (10)     DEFAULT ('') NOT NULL,
    [ShowCertifiedPR]      CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowCpnyID]           CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowGLAcct]           CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowGLSub]            CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowGroupCode]        CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowHrsToCmp]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowLbrClass]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowMgrReview]        CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowNonBill]          CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowOT]               CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowShift]            CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowStepCmpO]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowTaskCmpO]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowUnionCode]        CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowWklyDesc]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowWorkerComp]       CHAR (1)      DEFAULT ('') NOT NULL,
    [ShowWorkType]         CHAR (1)      DEFAULT ('') NOT NULL,
    [TimeInterval]         CHAR (1)      DEFAULT ('') NOT NULL,
    [ToolTipDisplay]       CHAR (1)      DEFAULT ('') NOT NULL,
    [User1]                CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]                CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]                CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]                CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [PJPFTUSER0] PRIMARY KEY CLUSTERED ([Employee] ASC) WITH (FILLFACTOR = 90)
);

