CREATE TABLE [dbo].[smRateDetail] (
    [ClassID]           CHAR (6)      NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [DetailType]        CHAR (1)      NOT NULL,
    [ExtPrice]          FLOAT (53)    NOT NULL,
    [FlatRateId]        CHAR (10)     NOT NULL,
    [InvtDescr]         CHAR (60)     NOT NULL,
    [InvtId]            CHAR (30)     NOT NULL,
    [InvtProfit]        FLOAT (53)    NOT NULL,
    [InvtProfitPercent] FLOAT (53)    NOT NULL,
    [InvtStdCost]       FLOAT (53)    NOT NULL,
    [LineNbr]           SMALLINT      NOT NULL,
    [Lupd_DateTime]     SMALLDATETIME NOT NULL,
    [Lupd_Prog]         CHAR (8)      NOT NULL,
    [Lupd_User]         CHAR (10)     NOT NULL,
    [MarkupId]          CHAR (10)     NOT NULL,
    [Quantity]          FLOAT (53)    NOT NULL,
    [TaxAmt00]          FLOAT (53)    NOT NULL,
    [TaxAmt01]          FLOAT (53)    NOT NULL,
    [TaxAmt02]          FLOAT (53)    NOT NULL,
    [TaxAmt03]          FLOAT (53)    NOT NULL,
    [TaxExempt]         CHAR (1)      NOT NULL,
    [TxblAmt00]         FLOAT (53)    NOT NULL,
    [TxblAmt01]         FLOAT (53)    NOT NULL,
    [TxblAmt02]         FLOAT (53)    NOT NULL,
    [TxblAmt03]         FLOAT (53)    NOT NULL,
    [UnitPrice]         FLOAT (53)    NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [smRateDetail0] PRIMARY KEY CLUSTERED ([FlatRateId] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

