CREATE TABLE [dbo].[FtrOptions] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_FtrOptions_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_FtrOptions_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_FtrOptions_Crtd_User] DEFAULT (' ') NOT NULL,
    [Dependencies]  SMALLINT      CONSTRAINT [DF_FtrOptions_Dependencies] DEFAULT ((0)) NOT NULL,
    [Descr]         CHAR (60)     CONSTRAINT [DF_FtrOptions_Descr] DEFAULT (' ') NOT NULL,
    [DfltOpt]       SMALLINT      CONSTRAINT [DF_FtrOptions_DfltOpt] DEFAULT ((0)) NOT NULL,
    [Exclusions]    SMALLINT      CONSTRAINT [DF_FtrOptions_Exclusions] DEFAULT ((0)) NOT NULL,
    [FeatureNbr]    CHAR (4)      CONSTRAINT [DF_FtrOptions_FeatureNbr] DEFAULT (' ') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_FtrOptions_InvtID] DEFAULT (' ') NOT NULL,
    [LineID]        INT           CONSTRAINT [DF_FtrOptions_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]       SMALLINT      CONSTRAINT [DF_FtrOptions_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]       CHAR (5)      CONSTRAINT [DF_FtrOptions_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_FtrOptions_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_FtrOptions_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_FtrOptions_LUpd_User] DEFAULT (' ') NOT NULL,
    [MaxQty]        FLOAT (53)    CONSTRAINT [DF_FtrOptions_MaxQty] DEFAULT ((0)) NOT NULL,
    [MinQty]        FLOAT (53)    CONSTRAINT [DF_FtrOptions_MinQty] DEFAULT ((0)) NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_FtrOptions_NoteID] DEFAULT ((0)) NOT NULL,
    [OptInvtID]     CHAR (30)     CONSTRAINT [DF_FtrOptions_OptInvtID] DEFAULT (' ') NOT NULL,
    [QtyPer]        FLOAT (53)    CONSTRAINT [DF_FtrOptions_QtyPer] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_FtrOptions_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_FtrOptions_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_FtrOptions_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_FtrOptions_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_FtrOptions_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_FtrOptions_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_FtrOptions_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_FtrOptions_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_FtrOptions_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_FtrOptions_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_FtrOptions_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_FtrOptions_S4Future12] DEFAULT (' ') NOT NULL,
    [StartDate]     SMALLDATETIME CONSTRAINT [DF_FtrOptions_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Status]        CHAR (1)      CONSTRAINT [DF_FtrOptions_Status] DEFAULT (' ') NOT NULL,
    [StopDate]      SMALLDATETIME CONSTRAINT [DF_FtrOptions_StopDate] DEFAULT ('01/01/1900') NOT NULL,
    [UnitDesc]      CHAR (6)      CONSTRAINT [DF_FtrOptions_UnitDesc] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_FtrOptions_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_FtrOptions_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_FtrOptions_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_FtrOptions_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_FtrOptions_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_FtrOptions_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_FtrOptions_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_FtrOptions_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [FtrOptions0] PRIMARY KEY CLUSTERED ([InvtID] ASC, [FeatureNbr] ASC, [OptInvtID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [FtrOptions1]
    ON [dbo].[FtrOptions]([InvtID] ASC, [FeatureNbr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);

