CREATE TABLE [dbo].[WorkCenter] (
    [CpnyID]              CHAR (10)     CONSTRAINT [DF_WorkCenter_CpnyID] DEFAULT (' ') NOT NULL,
    [CrewSize]            FLOAT (53)    CONSTRAINT [DF_WorkCenter_CrewSize] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_WorkCenter_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_WorkCenter_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_WorkCenter_Crtd_User] DEFAULT (' ') NOT NULL,
    [Descr]               CHAR (30)     CONSTRAINT [DF_WorkCenter_Descr] DEFAULT (' ') NOT NULL,
    [DirectLaborAC]       CHAR (16)     CONSTRAINT [DF_WorkCenter_DirectLaborAC] DEFAULT (' ') NOT NULL,
    [DirectMtlAC]         CHAR (16)     CONSTRAINT [DF_WorkCenter_DirectMtlAC] DEFAULT (' ') NOT NULL,
    [DirectOtherAC]       CHAR (16)     CONSTRAINT [DF_WorkCenter_DirectOtherAC] DEFAULT (' ') NOT NULL,
    [LbrDirOffAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrDirOffAcct] DEFAULT (' ') NOT NULL,
    [LbrDirOffSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrDirOffSub] DEFAULT (' ') NOT NULL,
    [LbrDirScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrDirScrapVarAcct] DEFAULT (' ') NOT NULL,
    [LbrDirScrapVarSub]   CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrDirScrapVarSub] DEFAULT (' ') NOT NULL,
    [LbrDirVarAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrDirVarAcct] DEFAULT (' ') NOT NULL,
    [LbrDirVarSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrDirVarSub] DEFAULT (' ') NOT NULL,
    [LbrOvhOffAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrOvhOffAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhOffSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrOvhOffSub] DEFAULT (' ') NOT NULL,
    [LbrOvhScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrOvhScrapVarAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhScrapVarSub]   CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrOvhScrapVarSub] DEFAULT (' ') NOT NULL,
    [LbrOvhVarAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_LbrOvhVarAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhVarSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_LbrOvhVarSub] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME CONSTRAINT [DF_WorkCenter_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      CONSTRAINT [DF_WorkCenter_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]           CHAR (10)     CONSTRAINT [DF_WorkCenter_LUpd_User] DEFAULT (' ') NOT NULL,
    [MachOvhOffAcct]      CHAR (10)     CONSTRAINT [DF_WorkCenter_MachOvhOffAcct] DEFAULT (' ') NOT NULL,
    [MachOvhOffSub]       CHAR (24)     CONSTRAINT [DF_WorkCenter_MachOvhOffSub] DEFAULT (' ') NOT NULL,
    [MachOvhScrapVarAcct] CHAR (10)     CONSTRAINT [DF_WorkCenter_MachOvhScrapVarAcct] DEFAULT (' ') NOT NULL,
    [MachOvhScrapVarSub]  CHAR (24)     CONSTRAINT [DF_WorkCenter_MachOvhScrapVarSub] DEFAULT (' ') NOT NULL,
    [MachOvhVarAcct]      CHAR (10)     CONSTRAINT [DF_WorkCenter_MachOvhVarAcct] DEFAULT (' ') NOT NULL,
    [MachOvhVarSub]       CHAR (24)     CONSTRAINT [DF_WorkCenter_MachOvhVarSub] DEFAULT (' ') NOT NULL,
    [NbrMachines]         FLOAT (53)    CONSTRAINT [DF_WorkCenter_NbrMachines] DEFAULT ((0)) NOT NULL,
    [NoteID]              INT           CONSTRAINT [DF_WorkCenter_NoteID] DEFAULT ((0)) NOT NULL,
    [OthDirOffAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_OthDirOffAcct] DEFAULT (' ') NOT NULL,
    [OthDirOffSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_OthDirOffSub] DEFAULT (' ') NOT NULL,
    [OthDirScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_WorkCenter_OthDirScrapVarAcct] DEFAULT (' ') NOT NULL,
    [OthDirScrapVarSub]   CHAR (24)     CONSTRAINT [DF_WorkCenter_OthDirScrapVarSub] DEFAULT (' ') NOT NULL,
    [OthDirVarAcct]       CHAR (10)     CONSTRAINT [DF_WorkCenter_OthDirVarAcct] DEFAULT (' ') NOT NULL,
    [OthDirVarSub]        CHAR (24)     CONSTRAINT [DF_WorkCenter_OthDirVarSub] DEFAULT (' ') NOT NULL,
    [OvhLaborFixedAC]     CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhLaborFixedAC] DEFAULT (' ') NOT NULL,
    [OvhLaborVarAC]       CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhLaborVarAC] DEFAULT (' ') NOT NULL,
    [OvhMachFixedAC]      CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhMachFixedAC] DEFAULT (' ') NOT NULL,
    [OvhMachVarAC]        CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhMachVarAC] DEFAULT (' ') NOT NULL,
    [OvhMtlFixedAC]       CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhMtlFixedAC] DEFAULT (' ') NOT NULL,
    [OvhMtlVarAC]         CHAR (16)     CONSTRAINT [DF_WorkCenter_OvhMtlVarAC] DEFAULT (' ') NOT NULL,
    [PFLbrOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_PFLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [PFMachOvhRate]       FLOAT (53)    CONSTRAINT [DF_WorkCenter_PFMachOvhRate] DEFAULT ((0)) NOT NULL,
    [PLbrOvhRate]         FLOAT (53)    CONSTRAINT [DF_WorkCenter_PLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [PMachOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_PMachOvhRate] DEFAULT ((0)) NOT NULL,
    [PVLbrOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_PVLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [PVMachOvhRate]       FLOAT (53)    CONSTRAINT [DF_WorkCenter_PVMachOvhRate] DEFAULT ((0)) NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_WorkCenter_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_WorkCenter_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_WorkCenter_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_WorkCenter_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_WorkCenter_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_WorkCenter_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_WorkCenter_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_WorkCenter_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_WorkCenter_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_WorkCenter_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_WorkCenter_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_WorkCenter_S4Future12] DEFAULT (' ') NOT NULL,
    [SFLbrOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_SFLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [SFMachOvhRate]       FLOAT (53)    CONSTRAINT [DF_WorkCenter_SFMachOvhRate] DEFAULT ((0)) NOT NULL,
    [SiteID]              CHAR (10)     CONSTRAINT [DF_WorkCenter_SiteID] DEFAULT (' ') NOT NULL,
    [SLbrOvhRate]         FLOAT (53)    CONSTRAINT [DF_WorkCenter_SLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [SMachOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_SMachOvhRate] DEFAULT ((0)) NOT NULL,
    [SVLbrOvhRate]        FLOAT (53)    CONSTRAINT [DF_WorkCenter_SVLbrOvhRate] DEFAULT ((0)) NOT NULL,
    [SVMachOvhRate]       FLOAT (53)    CONSTRAINT [DF_WorkCenter_SVMachOvhRate] DEFAULT ((0)) NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_WorkCenter_User1] DEFAULT (' ') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_WorkCenter_User2] DEFAULT (' ') NOT NULL,
    [User3]               FLOAT (53)    CONSTRAINT [DF_WorkCenter_User3] DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    CONSTRAINT [DF_WorkCenter_User4] DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     CONSTRAINT [DF_WorkCenter_User5] DEFAULT (' ') NOT NULL,
    [User6]               CHAR (10)     CONSTRAINT [DF_WorkCenter_User6] DEFAULT (' ') NOT NULL,
    [User7]               SMALLDATETIME CONSTRAINT [DF_WorkCenter_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME CONSTRAINT [DF_WorkCenter_User8] DEFAULT ('01/01/1900') NOT NULL,
    [WorkCenterID]        CHAR (10)     CONSTRAINT [DF_WorkCenter_WorkCenterID] DEFAULT (' ') NOT NULL,
    [WorkHrs]             FLOAT (53)    CONSTRAINT [DF_WorkCenter_WorkHrs] DEFAULT ((0)) NOT NULL,
    [WrkComp]             CHAR (6)      CONSTRAINT [DF_WorkCenter_WrkComp] DEFAULT (' ') NOT NULL,
    [WrkLoc]              CHAR (6)      CONSTRAINT [DF_WorkCenter_WrkLoc] DEFAULT (' ') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [WorkCenter0] PRIMARY KEY CLUSTERED ([WorkCenterID] ASC) WITH (FILLFACTOR = 90)
);

