CREATE TABLE [dbo].[SOLine] (
    [AlternateID]          CHAR (30)     CONSTRAINT [DF_SOLine_AlternateID] DEFAULT (' ') NOT NULL,
    [AltIDType]            CHAR (1)      CONSTRAINT [DF_SOLine_AltIDType] DEFAULT (' ') NOT NULL,
    [AutoPO]               SMALLINT      CONSTRAINT [DF_SOLine_AutoPO] DEFAULT ((0)) NOT NULL,
    [AutoPOVendID]         CHAR (15)     CONSTRAINT [DF_SOLine_AutoPOVendID] DEFAULT (' ') NOT NULL,
    [BlktOrdLineRef]       CHAR (5)      CONSTRAINT [DF_SOLine_BlktOrdLineRef] DEFAULT (' ') NOT NULL,
    [BlktOrdQty]           FLOAT (53)    CONSTRAINT [DF_SOLine_BlktOrdQty] DEFAULT ((0)) NOT NULL,
    [BMICost]              FLOAT (53)    CONSTRAINT [DF_SOLine_BMICost] DEFAULT ((0)) NOT NULL,
    [BMICuryID]            CHAR (4)      CONSTRAINT [DF_SOLine_BMICuryID] DEFAULT (' ') NOT NULL,
    [BMIEffDate]           SMALLDATETIME CONSTRAINT [DF_SOLine_BMIEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [BMIExtPriceInvc]      FLOAT (53)    CONSTRAINT [DF_SOLine_BMIExtPriceInvc] DEFAULT ((0)) NOT NULL,
    [BMIMultDiv]           CHAR (1)      CONSTRAINT [DF_SOLine_BMIMultDiv] DEFAULT (' ') NOT NULL,
    [BMIRate]              FLOAT (53)    CONSTRAINT [DF_SOLine_BMIRate] DEFAULT ((0)) NOT NULL,
    [BMIRtTp]              CHAR (6)      CONSTRAINT [DF_SOLine_BMIRtTp] DEFAULT (' ') NOT NULL,
    [BMISlsPrice]          FLOAT (53)    CONSTRAINT [DF_SOLine_BMISlsPrice] DEFAULT ((0)) NOT NULL,
    [BoundToWO]            SMALLINT      CONSTRAINT [DF_SOLine_BoundToWO] DEFAULT ((0)) NOT NULL,
    [CancelDate]           SMALLDATETIME CONSTRAINT [DF_SOLine_CancelDate] DEFAULT ('01/01/1900') NOT NULL,
    [ChainDisc]            CHAR (15)     CONSTRAINT [DF_SOLine_ChainDisc] DEFAULT (' ') NOT NULL,
    [CmmnPct]              FLOAT (53)    CONSTRAINT [DF_SOLine_CmmnPct] DEFAULT ((0)) NOT NULL,
    [CnvFact]              FLOAT (53)    CONSTRAINT [DF_SOLine_CnvFact] DEFAULT ((0)) NOT NULL,
    [COGSAcct]             CHAR (10)     CONSTRAINT [DF_SOLine_COGSAcct] DEFAULT (' ') NOT NULL,
    [COGSSub]              CHAR (24)     CONSTRAINT [DF_SOLine_COGSSub] DEFAULT (' ') NOT NULL,
    [CommCost]             FLOAT (53)    CONSTRAINT [DF_SOLine_CommCost] DEFAULT ((0)) NOT NULL,
    [Cost]                 FLOAT (53)    CONSTRAINT [DF_SOLine_Cost] DEFAULT ((0)) NOT NULL,
    [CpnyID]               CHAR (10)     CONSTRAINT [DF_SOLine_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME CONSTRAINT [DF_SOLine_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      CONSTRAINT [DF_SOLine_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]            CHAR (10)     CONSTRAINT [DF_SOLine_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCommCost]         FLOAT (53)    CONSTRAINT [DF_SOLine_CuryCommCost] DEFAULT ((0)) NOT NULL,
    [CuryCost]             FLOAT (53)    CONSTRAINT [DF_SOLine_CuryCost] DEFAULT ((0)) NOT NULL,
    [CuryListPrice]        FLOAT (53)    CONSTRAINT [DF_SOLine_CuryListPrice] DEFAULT ((0)) NOT NULL,
    [CurySlsPrice]         FLOAT (53)    CONSTRAINT [DF_SOLine_CurySlsPrice] DEFAULT ((0)) NOT NULL,
    [CurySlsPriceOrig]     FLOAT (53)    CONSTRAINT [DF_SOLine_CurySlsPriceOrig] DEFAULT ((0)) NOT NULL,
    [CuryTotCommCost]      FLOAT (53)    CONSTRAINT [DF_SOLine_CuryTotCommCost] DEFAULT ((0)) NOT NULL,
    [CuryTotCost]          FLOAT (53)    CONSTRAINT [DF_SOLine_CuryTotCost] DEFAULT ((0)) NOT NULL,
    [CuryTotOrd]           FLOAT (53)    CONSTRAINT [DF_SOLine_CuryTotOrd] DEFAULT ((0)) NOT NULL,
    [Descr]                CHAR (60)     CONSTRAINT [DF_SOLine_Descr] DEFAULT (' ') NOT NULL,
    [DescrLang]            CHAR (30)     CONSTRAINT [DF_SOLine_DescrLang] DEFAULT (' ') NOT NULL,
    [DiscAcct]             CHAR (10)     CONSTRAINT [DF_SOLine_DiscAcct] DEFAULT (' ') NOT NULL,
    [DiscPct]              FLOAT (53)    CONSTRAINT [DF_SOLine_DiscPct] DEFAULT ((0)) NOT NULL,
    [DiscPrcType]          CHAR (1)      CONSTRAINT [DF_SOLine_DiscPrcType] DEFAULT (' ') NOT NULL,
    [DiscSub]              CHAR (24)     CONSTRAINT [DF_SOLine_DiscSub] DEFAULT (' ') NOT NULL,
    [Disp]                 CHAR (3)      CONSTRAINT [DF_SOLine_Disp] DEFAULT (' ') NOT NULL,
    [DropShip]             SMALLINT      CONSTRAINT [DF_SOLine_DropShip] DEFAULT ((0)) NOT NULL,
    [InclForecastUsageClc] SMALLINT      CONSTRAINT [DF_SOLine_InclForecastUsageClc] DEFAULT ((0)) NOT NULL,
    [InspID]               CHAR (2)      CONSTRAINT [DF_SOLine_InspID] DEFAULT (' ') NOT NULL,
    [InspNoteID]           INT           CONSTRAINT [DF_SOLine_InspNoteID] DEFAULT ((0)) NOT NULL,
    [InvAcct]              CHAR (10)     CONSTRAINT [DF_SOLine_InvAcct] DEFAULT (' ') NOT NULL,
    [InvSub]               CHAR (24)     CONSTRAINT [DF_SOLine_InvSub] DEFAULT (' ') NOT NULL,
    [InvtID]               CHAR (30)     CONSTRAINT [DF_SOLine_InvtID] DEFAULT (' ') NOT NULL,
    [IRDemand]             SMALLINT      CONSTRAINT [DF_SOLine_IRDemand] DEFAULT ((0)) NOT NULL,
    [IRInvtID]             CHAR (30)     CONSTRAINT [DF_SOLine_IRInvtID] DEFAULT (' ') NOT NULL,
    [IRProcessed]          SMALLINT      CONSTRAINT [DF_SOLine_IRProcessed] DEFAULT ((0)) NOT NULL,
    [IRSiteID]             CHAR (10)     CONSTRAINT [DF_SOLine_IRSiteID] DEFAULT (' ') NOT NULL,
    [ItemGLClassID]        CHAR (4)      CONSTRAINT [DF_SOLine_ItemGLClassID] DEFAULT (' ') NOT NULL,
    [KitComponent]         SMALLINT      CONSTRAINT [DF_SOLine_KitComponent] DEFAULT ((0)) NOT NULL,
    [LineNbr]              SMALLINT      CONSTRAINT [DF_SOLine_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]              CHAR (5)      CONSTRAINT [DF_SOLine_LineRef] DEFAULT (' ') NOT NULL,
    [ListPrice]            FLOAT (53)    CONSTRAINT [DF_SOLine_ListPrice] DEFAULT ((0)) NOT NULL,
    [LotSerialReq]         SMALLINT      CONSTRAINT [DF_SOLine_LotSerialReq] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME CONSTRAINT [DF_SOLine_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      CONSTRAINT [DF_SOLine_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]            CHAR (10)     CONSTRAINT [DF_SOLine_LUpd_User] DEFAULT (' ') NOT NULL,
    [ManualCost]           SMALLINT      CONSTRAINT [DF_SOLine_ManualCost] DEFAULT ((0)) NOT NULL,
    [ManualPrice]          SMALLINT      CONSTRAINT [DF_SOLine_ManualPrice] DEFAULT ((0)) NOT NULL,
    [NoteId]               INT           CONSTRAINT [DF_SOLine_NoteId] DEFAULT ((0)) NOT NULL,
    [OrdNbr]               CHAR (15)     CONSTRAINT [DF_SOLine_OrdNbr] DEFAULT (' ') NOT NULL,
    [OrigINBatNbr]         CHAR (10)     CONSTRAINT [DF_SOLine_OrigINBatNbr] DEFAULT (' ') NOT NULL,
    [OrigInvcNbr]          CHAR (15)     CONSTRAINT [DF_SOLine_OrigInvcNbr] DEFAULT (' ') NOT NULL,
    [OrigInvtID]           CHAR (30)     CONSTRAINT [DF_SOLine_OrigInvtID] DEFAULT (' ') NOT NULL,
    [OrigShipperCnvFact]   FLOAT (53)    CONSTRAINT [DF_SOLine_OrigShipperCnvFact] DEFAULT ((0)) NOT NULL,
    [OrigShipperID]        CHAR (15)     CONSTRAINT [DF_SOLine_OrigShipperID] DEFAULT (' ') NOT NULL,
    [OrigShipperLineQty]   FLOAT (53)    CONSTRAINT [DF_SOLine_OrigShipperLineQty] DEFAULT ((0)) NOT NULL,
    [OrigShipperLineRef]   CHAR (5)      CONSTRAINT [DF_SOLine_OrigShipperLineRef] DEFAULT (' ') NOT NULL,
    [OrigShipperUnitDesc]  CHAR (6)      CONSTRAINT [DF_SOLine_OrigShipperUnitDesc] DEFAULT (' ') NOT NULL,
    [OrigShipperMultDiv]   CHAR (1)      CONSTRAINT [DF_SOLine_OrigShipperMultDiv] DEFAULT (' ') NOT NULL,
    [PC_Status]            CHAR (1)      CONSTRAINT [DF_SOLine_PC_Status] DEFAULT (' ') NOT NULL,
    [ProjectID]            CHAR (16)     CONSTRAINT [DF_SOLine_ProjectID] DEFAULT (' ') NOT NULL,
    [PromDate]             SMALLDATETIME CONSTRAINT [DF_SOLine_PromDate] DEFAULT ('01/01/1900') NOT NULL,
    [QtyBO]                FLOAT (53)    CONSTRAINT [DF_SOLine_QtyBO] DEFAULT ((0)) NOT NULL,
    [QtyCloseShip]         FLOAT (53)    CONSTRAINT [DF_SOLine_QtyCloseShip] DEFAULT ((0)) NOT NULL,
    [QtyFuture]            FLOAT (53)    CONSTRAINT [DF_SOLine_QtyFuture] DEFAULT ((0)) NOT NULL,
    [QtyOpenShip]          FLOAT (53)    CONSTRAINT [DF_SOLine_QtyOpenShip] DEFAULT ((0)) NOT NULL,
    [QtyOrd]               FLOAT (53)    CONSTRAINT [DF_SOLine_QtyOrd] DEFAULT ((0)) NOT NULL,
    [QtyShip]              FLOAT (53)    CONSTRAINT [DF_SOLine_QtyShip] DEFAULT ((0)) NOT NULL,
    [QtyToInvc]            FLOAT (53)    CONSTRAINT [DF_SOLine_QtyToInvc] DEFAULT ((0)) NOT NULL,
    [ReasonCd]             CHAR (6)      CONSTRAINT [DF_SOLine_ReasonCd] DEFAULT (' ') NOT NULL,
    [RebateID]             CHAR (10)     CONSTRAINT [DF_SOLine_RebateID] DEFAULT (' ') NOT NULL,
    [ReqDate]              SMALLDATETIME CONSTRAINT [DF_SOLine_ReqDate] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future01]           CHAR (30)     CONSTRAINT [DF_SOLine_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     CONSTRAINT [DF_SOLine_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    CONSTRAINT [DF_SOLine_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    CONSTRAINT [DF_SOLine_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    CONSTRAINT [DF_SOLine_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    CONSTRAINT [DF_SOLine_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME CONSTRAINT [DF_SOLine_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME CONSTRAINT [DF_SOLine_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           CONSTRAINT [DF_SOLine_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           CONSTRAINT [DF_SOLine_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     CONSTRAINT [DF_SOLine_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     CONSTRAINT [DF_SOLine_S4Future12] DEFAULT (' ') NOT NULL,
    [SalesPriceID]         CHAR (15)     CONSTRAINT [DF_SOLine_SalesPriceID] DEFAULT (' ') NOT NULL,
    [Sample]               SMALLINT      CONSTRAINT [DF_SOLine_Sample] DEFAULT ((0)) NOT NULL,
    [SchedCntr]            SMALLINT      CONSTRAINT [DF_SOLine_SchedCntr] DEFAULT ((0)) NOT NULL,
    [Service]              SMALLINT      CONSTRAINT [DF_SOLine_Service] DEFAULT ((0)) NOT NULL,
    [ShipWght]             FLOAT (53)    CONSTRAINT [DF_SOLine_ShipWght] DEFAULT ((0)) NOT NULL,
    [SiteID]               CHAR (10)     CONSTRAINT [DF_SOLine_SiteID] DEFAULT (' ') NOT NULL,
    [SlsAcct]              CHAR (10)     CONSTRAINT [DF_SOLine_SlsAcct] DEFAULT (' ') NOT NULL,
    [SlsperID]             CHAR (10)     CONSTRAINT [DF_SOLine_SlsperID] DEFAULT (' ') NOT NULL,
    [SlsPrice]             FLOAT (53)    CONSTRAINT [DF_SOLine_SlsPrice] DEFAULT ((0)) NOT NULL,
    [SlsPriceID]           CHAR (15)     CONSTRAINT [DF_SOLine_SlsPriceID] DEFAULT (' ') NOT NULL,
    [SlsPriceOrig]         FLOAT (53)    CONSTRAINT [DF_SOLine_SlsPriceOrig] DEFAULT ((0)) NOT NULL,
    [SlsSub]               CHAR (24)     CONSTRAINT [DF_SOLine_SlsSub] DEFAULT (' ') NOT NULL,
    [SplitLots]            SMALLINT      CONSTRAINT [DF_SOLine_SplitLots] DEFAULT ((0)) NOT NULL,
    [Status]               CHAR (1)      CONSTRAINT [DF_SOLine_Status] DEFAULT (' ') NOT NULL,
    [TaskID]               CHAR (32)     CONSTRAINT [DF_SOLine_TaskID] DEFAULT (' ') NOT NULL,
    [Taxable]              SMALLINT      CONSTRAINT [DF_SOLine_Taxable] DEFAULT ((0)) NOT NULL,
    [TaxCat]               CHAR (10)     CONSTRAINT [DF_SOLine_TaxCat] DEFAULT (' ') NOT NULL,
    [TotCommCost]          FLOAT (53)    CONSTRAINT [DF_SOLine_TotCommCost] DEFAULT ((0)) NOT NULL,
    [TotCost]              FLOAT (53)    CONSTRAINT [DF_SOLine_TotCost] DEFAULT ((0)) NOT NULL,
    [TotOrd]               FLOAT (53)    CONSTRAINT [DF_SOLine_TotOrd] DEFAULT ((0)) NOT NULL,
    [TotShipWght]          FLOAT (53)    CONSTRAINT [DF_SOLine_TotShipWght] DEFAULT ((0)) NOT NULL,
    [UnitDesc]             CHAR (6)      CONSTRAINT [DF_SOLine_UnitDesc] DEFAULT (' ') NOT NULL,
    [UnitMultDiv]          CHAR (1)      CONSTRAINT [DF_SOLine_UnitMultDiv] DEFAULT (' ') NOT NULL,
    [User1]                CHAR (30)     CONSTRAINT [DF_SOLine_User1] DEFAULT (' ') NOT NULL,
    [User10]               SMALLDATETIME CONSTRAINT [DF_SOLine_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]                CHAR (30)     CONSTRAINT [DF_SOLine_User2] DEFAULT (' ') NOT NULL,
    [User3]                CHAR (30)     CONSTRAINT [DF_SOLine_User3] DEFAULT (' ') NOT NULL,
    [User4]                CHAR (30)     CONSTRAINT [DF_SOLine_User4] DEFAULT (' ') NOT NULL,
    [User5]                FLOAT (53)    CONSTRAINT [DF_SOLine_User5] DEFAULT ((0)) NOT NULL,
    [User6]                FLOAT (53)    CONSTRAINT [DF_SOLine_User6] DEFAULT ((0)) NOT NULL,
    [User7]                CHAR (10)     CONSTRAINT [DF_SOLine_User7] DEFAULT (' ') NOT NULL,
    [User8]                CHAR (10)     CONSTRAINT [DF_SOLine_User8] DEFAULT (' ') NOT NULL,
    [User9]                SMALLDATETIME CONSTRAINT [DF_SOLine_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [SOLine0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [OrdNbr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [SOLine2]
    ON [dbo].[SOLine]([OrdNbr] ASC, [LineRef] ASC, [CpnyID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOLine1]
    ON [dbo].[SOLine]([InvtID] ASC, [Status] ASC, [CnvFact] ASC, [UnitMultDiv] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOLine3]
    ON [dbo].[SOLine]([InvtID] ASC, [SiteID] ASC, [Status] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOLine4]
    ON [dbo].[SOLine]([CpnyID] ASC, [OrdNbr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SOLine5]
    ON [dbo].[SOLine]([CpnyID] ASC, [OrdNbr] ASC, [LineRef] ASC, [Status] ASC) WITH (FILLFACTOR = 90);

