CREATE TABLE [dbo].[XDDLBView] (
    [AutoDisplay]      SMALLINT      DEFAULT (0) NOT NULL,
    [BalanceAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [BalanceFrom]      FLOAT (53)    DEFAULT (0) NOT NULL,
    [BalanceOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [BalanceTo]        FLOAT (53)    DEFAULT (0) NOT NULL,
    [ClosedDoc]        SMALLINT      DEFAULT (0) NOT NULL,
    [CpnyID]           CHAR (10)     DEFAULT ('') NOT NULL,
    [CpnyIDAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [CpnyIDOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]        CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_Time]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_User]        CHAR (10)     DEFAULT ('') NOT NULL,
    [CuryID]           CHAR (4)      DEFAULT ('') NOT NULL,
    [CuryIDAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [CuryIDOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [CustID]           CHAR (15)     DEFAULT ('') NOT NULL,
    [CustIDAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [CustIDOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [CustName]         CHAR (30)     DEFAULT ('') NOT NULL,
    [CustNameAD]       CHAR (1)      DEFAULT ('') NOT NULL,
    [CustNameOrd]      SMALLINT      DEFAULT (0) NOT NULL,
    [CustOrdNbr]       CHAR (15)     DEFAULT ('') NOT NULL,
    [CustOrdNbrAD]     CHAR (1)      DEFAULT ('') NOT NULL,
    [CustOrdNbrOrd]    SMALLINT      DEFAULT (0) NOT NULL,
    [DateDiscAD]       CHAR (1)      DEFAULT ('') NOT NULL,
    [DateDiscFrom]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDiscOrd]      SMALLINT      DEFAULT (0) NOT NULL,
    [DateDiscTo]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDiscType]     CHAR (2)      DEFAULT ('') NOT NULL,
    [DateDocAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [DateDocFrom]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDocOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [DateDocTo]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDocType]      CHAR (2)      DEFAULT ('') NOT NULL,
    [DateDueAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [DateDueFrom]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDueOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [DateDueTo]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DateDueType]      CHAR (2)      DEFAULT ('') NOT NULL,
    [Descr]            CHAR (60)     DEFAULT ('') NOT NULL,
    [DocTypeAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [DocType_CM]       SMALLINT      DEFAULT (0) NOT NULL,
    [DocType_DM]       SMALLINT      DEFAULT (0) NOT NULL,
    [DocType_FI]       SMALLINT      DEFAULT (0) NOT NULL,
    [DocType_IN]       SMALLINT      DEFAULT (0) NOT NULL,
    [DocType_PA]       SMALLINT      DEFAULT (0) NOT NULL,
    [DocTypeOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [EmpID]            CHAR (10)     DEFAULT ('') NOT NULL,
    [ExpLevel1]        CHAR (2)      DEFAULT ('') NOT NULL,
    [ExpLevel2]        CHAR (2)      DEFAULT ('') NOT NULL,
    [ExpLevel3]        CHAR (2)      DEFAULT ('') NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_Time]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]        CHAR (10)     DEFAULT ('') NOT NULL,
    [NoteID]           INT           DEFAULT (0) NOT NULL,
    [OpenDoc]          SMALLINT      DEFAULT (0) NOT NULL,
    [OpenDocAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [OpenDocOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [OpenViewExpanded] SMALLINT      DEFAULT (0) NOT NULL,
    [OrdNbr]           CHAR (15)     DEFAULT ('') NOT NULL,
    [OrdNbrAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [OrdNbrOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [PerPostAD]        CHAR (1)      DEFAULT ('') NOT NULL,
    [PerPostFrom]      CHAR (6)      DEFAULT ('') NOT NULL,
    [PerPostOrd]       SMALLINT      DEFAULT (0) NOT NULL,
    [PerPostTo]        CHAR (6)      DEFAULT ('') NOT NULL,
    [ProjectID]        CHAR (16)     DEFAULT ('') NOT NULL,
    [ProjectIDAD]      CHAR (1)      DEFAULT ('') NOT NULL,
    [ProjectIDOrd]     SMALLINT      DEFAULT (0) NOT NULL,
    [RecordLimit]      INT           DEFAULT (0) NOT NULL,
    [RefNbrAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [RefNbrFrom]       CHAR (10)     DEFAULT ('') NOT NULL,
    [RefNbrOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [RefNbrTo]         CHAR (10)     DEFAULT ('') NOT NULL,
    [Rlsed]            SMALLINT      DEFAULT (0) NOT NULL,
    [RlsedAD]          CHAR (1)      DEFAULT ('') NOT NULL,
    [RlsedOrd]         SMALLINT      DEFAULT (0) NOT NULL,
    [SKFuture01]       CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]       CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]       FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture04]       FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture05]       FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture06]       FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture07]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]       INT           DEFAULT (0) NOT NULL,
    [SKFuture10]       INT           DEFAULT (0) NOT NULL,
    [SKFuture11]       CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]       CHAR (10)     DEFAULT ('') NOT NULL,
    [TaskID]           CHAR (32)     DEFAULT ('') NOT NULL,
    [TaskIDAD]         CHAR (1)      DEFAULT ('') NOT NULL,
    [TaskIDOrd]        SMALLINT      DEFAULT (0) NOT NULL,
    [Terms]            CHAR (2)      DEFAULT ('') NOT NULL,
    [TermsAD]          CHAR (1)      DEFAULT ('') NOT NULL,
    [TermsOrd]         SMALLINT      DEFAULT (0) NOT NULL,
    [UnRlsed]          SMALLINT      DEFAULT (0) NOT NULL,
    [User1]            CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]           CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]            CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]            FLOAT (53)    DEFAULT (0) NOT NULL,
    [User4]            FLOAT (53)    DEFAULT (0) NOT NULL,
    [User5]            CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]            CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]            CHAR (30)     DEFAULT ('') NOT NULL,
    [ViewID]           CHAR (10)     DEFAULT ('') NOT NULL,
    [WhereClause]      CHAR (200)    DEFAULT ('') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [XDDLBView0] PRIMARY KEY CLUSTERED ([ViewID] ASC)
);

