CREATE TABLE [dbo].[cft_scribe_CRM_Staging_WorkOrder] (
    [f1_workorderId]                 NVARCHAR (38)    NOT NULL,
    [CreatedOn]                      DATETIME         NULL,
    [CreatedBy]                      NVARCHAR (38)    NULL,
    [ModifiedOn]                     DATETIME         NULL,
    [ModifiedBy]                     NVARCHAR (38)    NULL,
    [CreatedOnBehalfBy]              NVARCHAR (38)    NULL,
    [ModifiedOnBehalfBy]             NVARCHAR (38)    NULL,
    [OwnerId]                        NVARCHAR (38)    NOT NULL,
    [OwnerIdType]                    INT              NOT NULL,
    [OwningBusinessUnit]             NVARCHAR (38)    NULL,
    [statecode]                      INT              NOT NULL,
    [statuscode]                     INT              NULL,
    [TransactionCurrencyId]          NVARCHAR (38)    NULL,
    [ExchangeRate]                   DECIMAL (23, 10) NULL,
    [f1_TimeClosed]                  DATETIME         NULL,
    [f1_ServiceRequest]              NVARCHAR (38)    NULL,
    [f1_Latitude]                    DECIMAL (23, 10) NULL,
    [f1_EstimateSubtotalAmount]      MONEY            NULL,
    [f1_ImportID]                    NVARCHAR (20)    NULL,
    [f1_ServiceOverhead]             FLOAT (53)       NULL,
    [f1_PrimaryIncident]             NVARCHAR (38)    NULL,
    [f1_totalamount_Base]            MONEY            NULL,
    [f1_SubtotalAmount]              MONEY            NULL,
    [f1_SalesPerson]                 NVARCHAR (38)    NULL,
    [f1_estimatesubtotalamount_Base] MONEY            NULL,
    [f1_City]                        NVARCHAR (80)    NULL,
    [f1_name]                        NVARCHAR (100)   NULL,
    [f1_PrimaryIncidentDescription]  NVARCHAR (MAX)   NULL,
    [f1_Address1]                    NVARCHAR (250)   NULL,
    [f1_PrimaryIncidentType]         NVARCHAR (38)    NULL,
    [f1_TotalSalesTax]               MONEY            NULL,
    [f1_TimeWindowStart]             DATETIME         NULL,
    [f1_FollowUpNote]                NVARCHAR (MAX)   NULL,
    [f1_Agreement]                   NVARCHAR (38)    NULL,
    [f1_subtotalamount_Base]         MONEY            NULL,
    [f1_SchedulingMethod]            INT              NULL,
    [f1_PriceList]                   NVARCHAR (38)    NULL,
    [f1_EstimatedTime]               INT              NULL,
    [f1_Address2]                    NVARCHAR (250)   NULL,
    [f1_TimeFromPromised]            DATETIME         NULL,
    [f1_ServiceAccount]              NVARCHAR (38)    NULL,
    [f1_IsFollowUp]                  BIT              NULL,
    [f1_ClosedBy]                    NVARCHAR (38)    NULL,
    [f1_CampaignSource]              NVARCHAR (38)    NULL,
    [f1_WorkOrderType]               NVARCHAR (38)    NULL,
    [f1_WorkOrderSummary]            NVARCHAR (MAX)   NULL,
    [f1_ProductOverhead]             FLOAT (53)       NULL,
    [f1_systemstatusold]             INT              NULL,
    [f1_OpportunityId]               NVARCHAR (38)    NULL,
    [f1_TotalAmount]                 MONEY            NULL,
    [f1_TaxCode]                     NVARCHAR (38)    NULL,
    [f1_ParentWorkOrder]             NVARCHAR (38)    NULL,
    [f1_SystemStatus]                INT              NULL,
    [f1_Index]                       INT              NULL,
    [f1_Country]                     NVARCHAR (80)    NULL,
    [f1_CustomerPO]                  NVARCHAR (25)    NULL,
    [f1_Taxable]                     BIT              NULL,
    [f1_Longitude]                   DECIMAL (23, 10) NULL,
    [f1_TimeWindowEnd]               DATETIME         NULL,
    [f1_IsGeneratedByMethod]         BIT              NULL,
    [f1_PreferredResource]           NVARCHAR (38)    NULL,
    [f1_Instructions]                NVARCHAR (MAX)   NULL,
    [f1_TimeToPromised]              DATETIME         NULL,
    [f1_ServiceTerritory]            NVARCHAR (38)    NULL,
    [f1_Status]                      NVARCHAR (38)    NULL,
    [f1_Zip]                         NVARCHAR (20)    NULL,
    [f1_ScheduleSummary]             NVARCHAR (MAX)   NULL,
    [f1_CustomerEquipment]           NVARCHAR (38)    NULL,
    [f1_AddressName]                 NVARCHAR (250)   NULL,
    [f1_DateWindowEnd]               DATETIME         NULL,
    [f1_PrimaryResourceSchedule]     NVARCHAR (38)    NULL,
    [f1_WorkLocation]                INT              NULL,
    [f1_FollowUpRequired]            BIT              NULL,
    [f1_Address3]                    NVARCHAR (250)   NULL,
    [f1_DateWindowStart]             DATETIME         NULL,
    [f1_DispatchedTime]              DATETIME         NULL,
    [f1_totalsalestax_Base]          MONEY            NULL,
    [f1_ChildIndex]                  INT              NULL,
    [f1_DispatchedBy]                NVARCHAR (38)    NULL,
    [f1_IsMobile]                    BIT              NULL,
    [f1_ReportedByContact]           NVARCHAR (38)    NULL,
    [f1_Priority]                    NVARCHAR (38)    NULL,
    [f1_BillingAccount]              NVARCHAR (38)    NULL,
    [f1_State]                       NVARCHAR (50)    NULL,
    [processid]                      NVARCHAR (38)    NULL,
    [stageid]                        NVARCHAR (38)    NULL,
    [f1_RoutingOptimization]         NVARCHAR (38)    NULL,
    [cf_ApplyCredit]                 BIT              NULL,
    [cf_ApproversPhone]              NVARCHAR (100)   NULL,
    [cf_Billable]                    BIT              NULL,
    [cf_BioSecurity]                 NVARCHAR (100)   NULL,
    [cf_BSCall]                      BIT              NULL,
    [cf_InvoiceComments]             NVARCHAR (MAX)   NULL,
    [cf_NeedsApproval]               BIT              NULL,
    [cf_PigSizePigDaysPigHealth]     NVARCHAR (MAX)   NULL,
    [cf_ProjectID]                   NVARCHAR (100)   NULL,
    [cf_RequestorName]               NVARCHAR (100)   NULL,
    [cf_RequestorPhone]              NVARCHAR (100)   NULL,
    [cf_SLAEndTime]                  DATETIME         NULL,
    [cf_SLAStartTime]                DATETIME         NULL,
    [cf_SLAStatus]                   INT              NULL,
    [cf_TechnicianComments]          NVARCHAR (MAX)   NULL,
    [cf_Account_WorkOrder_ProjectId] NVARCHAR (38)    NULL,
    [cf_Barn]                        NVARCHAR (38)    NULL,
    [cf_Bin]                         NVARCHAR (38)    NULL,
    [cf_PigGroup]                    NVARCHAR (38)    NULL,
    [cf_Project]                     NVARCHAR (38)    NULL,
    [cf_Room]                        NVARCHAR (38)    NULL,
    [cf_Approver]                    NVARCHAR (38)    NULL,
    [cf_AssociatedInvoice]           NVARCHAR (38)    NULL,
    [SyncStatus]                     BIT              NULL,
    [SyncDate]                       DATETIME         NULL,
    [CustID]                         CHAR (15)        NULL,
    [ProjectNumber]                  CHAR (15)        NULL,
    [ServiceTerritory]               CHAR (15)        NULL,
    CONSTRAINT [PK_cft_scribe_CRM_Staging_WorkOrder] PRIMARY KEY CLUSTERED ([f1_workorderId] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE NONCLUSTERED INDEX [cft_scribe_CRM_Staging_WorkOrder_syncdata]
    ON [dbo].[cft_scribe_CRM_Staging_WorkOrder]([f1_workorderId] ASC, [CustID] ASC, [SyncStatus] ASC)
    INCLUDE([SyncDate]) WITH (FILLFACTOR = 100);

