CREATE TABLE [dbo].[AR_Balances] (
    [AccruedRevAgeBal00] FLOAT (53)    NOT NULL,
    [AccruedRevAgeBal01] FLOAT (53)    NOT NULL,
    [AccruedRevAgeBal02] FLOAT (53)    NOT NULL,
    [AccruedRevAgeBal03] FLOAT (53)    NOT NULL,
    [AccruedRevAgeBal04] FLOAT (53)    NOT NULL,
    [AccruedRevBal]      FLOAT (53)    NOT NULL,
    [AgeBal00]           FLOAT (53)    NOT NULL,
    [AgeBal01]           FLOAT (53)    NOT NULL,
    [AgeBal02]           FLOAT (53)    NOT NULL,
    [AgeBal03]           FLOAT (53)    NOT NULL,
    [AgeBal04]           FLOAT (53)    NOT NULL,
    [AvgDayToPay]        FLOAT (53)    NOT NULL,
    [CpnyID]             CHAR (10)     NOT NULL,
    [CrLmt]              FLOAT (53)    NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME NOT NULL,
    [Crtd_Prog]          CHAR (8)      NOT NULL,
    [Crtd_User]          CHAR (10)     NOT NULL,
    [CurrBal]            FLOAT (53)    NOT NULL,
    [CuryID]             CHAR (4)      NOT NULL,
    [CuryPromoBal]       FLOAT (53)    NOT NULL,
    [CustID]             CHAR (15)     NOT NULL,
    [FutureBal]          FLOAT (53)    NOT NULL,
    [LastActDate]        SMALLDATETIME NOT NULL,
    [LastAgeDate]        SMALLDATETIME NOT NULL,
    [LastFinChrgDate]    SMALLDATETIME NOT NULL,
    [LastInvcDate]       SMALLDATETIME NOT NULL,
    [LastStmtBal00]      FLOAT (53)    NOT NULL,
    [LastStmtBal01]      FLOAT (53)    NOT NULL,
    [LastStmtBal02]      FLOAT (53)    NOT NULL,
    [LastStmtBal03]      FLOAT (53)    NOT NULL,
    [LastStmtBal04]      FLOAT (53)    NOT NULL,
    [LastStmtBegBal]     FLOAT (53)    NOT NULL,
    [LastStmtDate]       SMALLDATETIME NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME NOT NULL,
    [LUpd_Prog]          CHAR (8)      NOT NULL,
    [LUpd_User]          CHAR (10)     NOT NULL,
    [NbrInvcPaid]        FLOAT (53)    NOT NULL,
    [NoteID]             INT           NOT NULL,
    [PaidInvcDays]       FLOAT (53)    NOT NULL,
    [PerNbr]             CHAR (6)      NOT NULL,
    [PromoBal]           FLOAT (53)    NOT NULL,
    [S4Future01]         CHAR (30)     NOT NULL,
    [S4Future02]         CHAR (30)     NOT NULL,
    [S4Future03]         FLOAT (53)    NOT NULL,
    [S4Future04]         FLOAT (53)    NOT NULL,
    [S4Future05]         FLOAT (53)    NOT NULL,
    [S4Future06]         FLOAT (53)    NOT NULL,
    [S4Future07]         SMALLDATETIME NOT NULL,
    [S4Future08]         SMALLDATETIME NOT NULL,
    [S4Future09]         INT           NOT NULL,
    [S4Future10]         INT           NOT NULL,
    [S4Future11]         CHAR (10)     NOT NULL,
    [S4Future12]         CHAR (10)     NOT NULL,
    [TotOpenOrd]         FLOAT (53)    NOT NULL,
    [TotPrePay]          FLOAT (53)    NOT NULL,
    [TotShipped]         FLOAT (53)    NOT NULL,
    [User1]              CHAR (30)     NOT NULL,
    [User2]              CHAR (30)     NOT NULL,
    [User3]              FLOAT (53)    NOT NULL,
    [User4]              FLOAT (53)    NOT NULL,
    [User5]              CHAR (10)     NOT NULL,
    [User6]              CHAR (10)     NOT NULL,
    [User7]              SMALLDATETIME NOT NULL,
    [User8]              SMALLDATETIME NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [AR_Balances0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [CustID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [AR_Balances1]
    ON [dbo].[AR_Balances]([CustID] ASC, [CpnyID] ASC) WITH (FILLFACTOR = 90);

