CREATE TABLE [dbo].[AP03680_Wrk] (
    [RI_ID]                SMALLINT      NOT NULL,
    [CpnyID]               CHAR (10)     NULL,
    [DiscDate]             SMALLDATETIME NULL,
    [DocDate]              SMALLDATETIME NULL,
    [DocType]              CHAR (2)      NULL,
    [DueDate]              SMALLDATETIME NULL,
    [InvcDate]             SMALLDATETIME NULL,
    [InvcNbr]              CHAR (15)     NULL,
    [OrigDocAmt]           FLOAT (53)    NULL,
    [PayDate]              SMALLDATETIME NULL,
    [RefNbr]               CHAR (10)     NULL,
    [Rlsed]                SMALLINT      NULL,
    [Status]               CHAR (1)      NULL,
    [VendID]               CHAR (15)     NULL,
    [DocBal]               FLOAT (53)    NULL,
    [CuryDocBal]           FLOAT (53)    NULL,
    [CuryID]               CHAR (4)      NULL,
    [APAdjust_AdjAmt]      FLOAT (53)    NULL,
    [APAdjust_AdjDiscAmt]  FLOAT (53)    NULL,
    [APAdjust_AdjgAcct]    CHAR (10)     NULL,
    [APAdjust_AdjgDocType] CHAR (2)      NULL,
    [APAdjust_AdjgRefNbr]  CHAR (10)     NULL,
    [APAdjust_AdjgSub]     CHAR (24)     NULL,
    [Vendor_Name]          CHAR (60)     NOT NULL,
    [Vendor_Status]        CHAR (1)      NULL,
    [Vendor_CuryID]        CHAR (4)      NULL,
    [APDocCk_DocDate]      SMALLDATETIME NULL,
    [tstamp]               ROWVERSION    NOT NULL
);

