CREATE TABLE [dbo].[ShipVia] (
    [CarrierID]          CHAR (10)     NOT NULL,
    [CommonCarrier]      SMALLINT      NOT NULL,
    [CompareVia]         SMALLINT      NOT NULL,
    [CpnyID]             CHAR (10)     NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME NOT NULL,
    [Crtd_Prog]          CHAR (8)      NOT NULL,
    [Crtd_User]          CHAR (10)     NOT NULL,
    [DeliveryCalendarID] SMALLINT      NOT NULL,
    [Descr]              CHAR (30)     NOT NULL,
    [DfltFrtAmt]         FLOAT (53)    NOT NULL,
    [DfltFrtMthd]        CHAR (1)      NOT NULL,
    [EDIViaCode]         CHAR (20)     NOT NULL,
    [FrtAcct]            CHAR (10)     NOT NULL,
    [FrtSub]             CHAR (31)     NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME NOT NULL,
    [LUpd_Prog]          CHAR (8)      NOT NULL,
    [LUpd_User]          CHAR (10)     NOT NULL,
    [Mode]               CHAR (2)      NOT NULL,
    [MoveOnDeliveryDays] SMALLINT      NOT NULL,
    [S4Future01]         CHAR (30)     NOT NULL,
    [S4Future02]         CHAR (30)     NOT NULL,
    [S4Future03]         FLOAT (53)    NOT NULL,
    [S4Future04]         FLOAT (53)    NOT NULL,
    [S4Future05]         FLOAT (53)    NOT NULL,
    [S4Future06]         FLOAT (53)    NOT NULL,
    [S4Future07]         SMALLDATETIME NOT NULL,
    [S4Future08]         SMALLDATETIME NOT NULL,
    [S4Future09]         INT           NOT NULL,
    [S4Future10]         INT           NOT NULL,
    [S4Future11]         CHAR (10)     NOT NULL,
    [S4Future12]         CHAR (10)     NOT NULL,
    [SCAC]               CHAR (5)      NOT NULL,
    [ShipViaID]          CHAR (15)     NOT NULL,
    [TaxCat]             CHAR (10)     NOT NULL,
    [TransitTime]        SMALLINT      NOT NULL,
    [User1]              CHAR (30)     NOT NULL,
    [User2]              CHAR (30)     NOT NULL,
    [User3]              FLOAT (53)    NOT NULL,
    [User4]              FLOAT (53)    NOT NULL,
    [User5]              CHAR (10)     NOT NULL,
    [User6]              CHAR (10)     NOT NULL,
    [User7]              SMALLDATETIME NOT NULL,
    [User8]              SMALLDATETIME NOT NULL,
    [WeekendDelivery]    SMALLINT      NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [ShipVia0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [ShipViaID] ASC) WITH (FILLFACTOR = 90)
);

