CREATE TABLE [dbo].[PJEXPDET] (
    [amt_employ]      FLOAT (53)    NOT NULL,
    [amt_company]     FLOAT (53)    NOT NULL,
    [amt_tax]         FLOAT (53)    NOT NULL,
    [CpnyId_chrg]     CHAR (10)     NOT NULL,
    [CpnyId_home]     CHAR (10)     NOT NULL,
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [CuryId]          CHAR (4)      NOT NULL,
    [CuryMultDiv]     CHAR (1)      NOT NULL,
    [CuryRate]        FLOAT (53)    NOT NULL,
    [curyratetype]    CHAR (6)      NOT NULL,
    [CuryTranamt]     FLOAT (53)    NOT NULL,
    [desc_detail]     CHAR (40)     NOT NULL,
    [docnbr]          CHAR (10)     NOT NULL,
    [exp_date]        SMALLDATETIME NOT NULL,
    [exp_type]        CHAR (4)      NOT NULL,
    [gl_acct]         CHAR (10)     NOT NULL,
    [gl_subacct]      CHAR (24)     NOT NULL,
    [linenbr]         SMALLINT      NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [NoteId]          INT           NOT NULL,
    [payment_cd]      CHAR (4)      NOT NULL,
    [pjt_entity]      CHAR (32)     NOT NULL,
    [project]         CHAR (16)     NOT NULL,
    [rate]            FLOAT (53)    NOT NULL,
    [status]          CHAR (1)      NOT NULL,
    [tax_amount]      FLOAT (53)    NOT NULL,
    [tax_flag]        CHAR (1)      NOT NULL,
    [taxcatid]        CHAR (10)     NOT NULL,
    [taxid]           CHAR (10)     NOT NULL,
    [taxitembasis]    FLOAT (53)    NOT NULL,
    [td_id01]         CHAR (30)     NOT NULL,
    [td_id02]         CHAR (30)     NOT NULL,
    [td_id03]         CHAR (16)     NOT NULL,
    [td_id04]         CHAR (16)     NOT NULL,
    [td_id05]         CHAR (4)      NOT NULL,
    [td_id06]         FLOAT (53)    NOT NULL,
    [td_id07]         FLOAT (53)    NOT NULL,
    [td_id08]         SMALLDATETIME NOT NULL,
    [td_id09]         SMALLDATETIME NOT NULL,
    [td_id10]         INT           NOT NULL,
    [td_id11]         CHAR (30)     NOT NULL,
    [td_id12]         CHAR (20)     NOT NULL,
    [td_id13]         CHAR (10)     NOT NULL,
    [td_id14]         CHAR (4)      NOT NULL,
    [td_id15]         FLOAT (53)    NOT NULL,
    [unit_of_measure] CHAR (10)     NOT NULL,
    [units]           FLOAT (53)    NOT NULL,
    [user1]           CHAR (30)     NOT NULL,
    [user2]           CHAR (30)     NOT NULL,
    [user3]           FLOAT (53)    NOT NULL,
    [user4]           FLOAT (53)    NOT NULL,
    [vendor_num]      CHAR (15)     NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjexpdet0] PRIMARY KEY CLUSTERED ([docnbr] ASC, [linenbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [pjexpdet1]
    ON [dbo].[PJEXPDET]([exp_date] ASC) WITH (FILLFACTOR = 90);

