CREATE TABLE [dbo].[InventoryADG] (
    [AllowGenCont]    SMALLINT      CONSTRAINT [DF_InventoryADG_AllowGenCont] DEFAULT ((0)) NOT NULL,
    [BatchSize]       FLOAT (53)    CONSTRAINT [DF_InventoryADG_BatchSize] DEFAULT ((0)) NOT NULL,
    [BOLClass]        CHAR (20)     CONSTRAINT [DF_InventoryADG_BOLClass] DEFAULT (' ') NOT NULL,
    [CategoryCode]    CHAR (10)     CONSTRAINT [DF_InventoryADG_CategoryCode] DEFAULT (' ') NOT NULL,
    [CountryOrig]     CHAR (20)     CONSTRAINT [DF_InventoryADG_CountryOrig] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME CONSTRAINT [DF_InventoryADG_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      CONSTRAINT [DF_InventoryADG_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     CONSTRAINT [DF_InventoryADG_Crtd_User] DEFAULT (' ') NOT NULL,
    [Density]         FLOAT (53)    CONSTRAINT [DF_InventoryADG_Density] DEFAULT ((0)) NOT NULL,
    [DensityUOM]      CHAR (5)      CONSTRAINT [DF_InventoryADG_DensityUOM] DEFAULT (' ') NOT NULL,
    [Depth]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_Depth] DEFAULT ((0)) NOT NULL,
    [DepthUOM]        CHAR (5)      CONSTRAINT [DF_InventoryADG_DepthUOM] DEFAULT (' ') NOT NULL,
    [Diameter]        FLOAT (53)    CONSTRAINT [DF_InventoryADG_Diameter] DEFAULT ((0)) NOT NULL,
    [DiameterUOM]     CHAR (5)      CONSTRAINT [DF_InventoryADG_DiameterUOM] DEFAULT (' ') NOT NULL,
    [Gauge]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_Gauge] DEFAULT ((0)) NOT NULL,
    [GaugeUOM]        CHAR (5)      CONSTRAINT [DF_InventoryADG_GaugeUOM] DEFAULT (' ') NOT NULL,
    [Height]          FLOAT (53)    CONSTRAINT [DF_InventoryADG_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]       CHAR (5)      CONSTRAINT [DF_InventoryADG_HeightUOM] DEFAULT (' ') NOT NULL,
    [InvtID]          CHAR (30)     CONSTRAINT [DF_InventoryADG_InvtID] DEFAULT (' ') NOT NULL,
    [Len]             FLOAT (53)    CONSTRAINT [DF_InventoryADG_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]          CHAR (5)      CONSTRAINT [DF_InventoryADG_LenUOM] DEFAULT (' ') NOT NULL,
    [ListPrice]       FLOAT (53)    CONSTRAINT [DF_InventoryADG_ListPrice] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME CONSTRAINT [DF_InventoryADG_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]       CHAR (8)      CONSTRAINT [DF_InventoryADG_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]       CHAR (10)     CONSTRAINT [DF_InventoryADG_LUpd_User] DEFAULT (' ') NOT NULL,
    [MinPrice]        FLOAT (53)    CONSTRAINT [DF_InventoryADG_MinPrice] DEFAULT ((0)) NOT NULL,
    [NoteID]          INT           CONSTRAINT [DF_InventoryADG_NoteID] DEFAULT ((0)) NOT NULL,
    [OMCOGSAcct]      CHAR (10)     CONSTRAINT [DF_InventoryADG_OMCOGSAcct] DEFAULT (' ') NOT NULL,
    [OMCOGSSub]       CHAR (31)     CONSTRAINT [DF_InventoryADG_OMCOGSSub] DEFAULT (' ') NOT NULL,
    [OMSalesAcct]     CHAR (10)     CONSTRAINT [DF_InventoryADG_OMSalesAcct] DEFAULT (' ') NOT NULL,
    [OMSalesSub]      CHAR (31)     CONSTRAINT [DF_InventoryADG_OMSalesSub] DEFAULT (' ') NOT NULL,
    [Pack]            SMALLINT      CONSTRAINT [DF_InventoryADG_Pack] DEFAULT ((0)) NOT NULL,
    [PackCnvFact]     FLOAT (53)    CONSTRAINT [DF_InventoryADG_PackCnvFact] DEFAULT ((0)) NOT NULL,
    [PackMethod]      CHAR (2)      CONSTRAINT [DF_InventoryADG_PackMethod] DEFAULT (' ') NOT NULL,
    [PackSize]        SMALLINT      CONSTRAINT [DF_InventoryADG_PackSize] DEFAULT ((0)) NOT NULL,
    [PackUnitMultDiv] CHAR (1)      CONSTRAINT [DF_InventoryADG_PackUnitMultDiv] DEFAULT (' ') NOT NULL,
    [PackUOM]         CHAR (6)      CONSTRAINT [DF_InventoryADG_PackUOM] DEFAULT (' ') NOT NULL,
    [ProdLineID]      CHAR (4)      CONSTRAINT [DF_InventoryADG_ProdLineID] DEFAULT (' ') NOT NULL,
    [RetailPrice]     FLOAT (53)    CONSTRAINT [DF_InventoryADG_RetailPrice] DEFAULT ((0)) NOT NULL,
    [RoyaltyCode]     CHAR (10)     CONSTRAINT [DF_InventoryADG_RoyaltyCode] DEFAULT (' ') NOT NULL,
    [S4Future01]      CHAR (30)     CONSTRAINT [DF_InventoryADG_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]      CHAR (30)     CONSTRAINT [DF_InventoryADG_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]      FLOAT (53)    CONSTRAINT [DF_InventoryADG_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]      FLOAT (53)    CONSTRAINT [DF_InventoryADG_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]      FLOAT (53)    CONSTRAINT [DF_InventoryADG_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]      FLOAT (53)    CONSTRAINT [DF_InventoryADG_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]      SMALLDATETIME CONSTRAINT [DF_InventoryADG_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]      SMALLDATETIME CONSTRAINT [DF_InventoryADG_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]      INT           CONSTRAINT [DF_InventoryADG_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]      INT           CONSTRAINT [DF_InventoryADG_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]      CHAR (10)     CONSTRAINT [DF_InventoryADG_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]      CHAR (10)     CONSTRAINT [DF_InventoryADG_S4Future12] DEFAULT (' ') NOT NULL,
    [SCHeight]        FLOAT (53)    CONSTRAINT [DF_InventoryADG_SCHeight] DEFAULT ((0)) NOT NULL,
    [SCHeightUOM]     CHAR (6)      CONSTRAINT [DF_InventoryADG_SCHeightUOM] DEFAULT (' ') NOT NULL,
    [SCLen]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_SCLen] DEFAULT ((0)) NOT NULL,
    [SCLenUOM]        CHAR (6)      CONSTRAINT [DF_InventoryADG_SCLenUOM] DEFAULT (' ') NOT NULL,
    [SCVolume]        FLOAT (53)    CONSTRAINT [DF_InventoryADG_SCVolume] DEFAULT ((0)) NOT NULL,
    [SCVolumeUOM]     CHAR (6)      CONSTRAINT [DF_InventoryADG_SCVolumeUOM] DEFAULT (' ') NOT NULL,
    [SCWeight]        FLOAT (53)    CONSTRAINT [DF_InventoryADG_SCWeight] DEFAULT ((0)) NOT NULL,
    [SCWeightUOM]     CHAR (6)      CONSTRAINT [DF_InventoryADG_SCWeightUOM] DEFAULT (' ') NOT NULL,
    [SCWidth]         FLOAT (53)    CONSTRAINT [DF_InventoryADG_SCWidth] DEFAULT ((0)) NOT NULL,
    [SCWidthUOM]      CHAR (6)      CONSTRAINT [DF_InventoryADG_SCWidthUOM] DEFAULT (' ') NOT NULL,
    [StdCartonBreak]  SMALLINT      CONSTRAINT [DF_InventoryADG_StdCartonBreak] DEFAULT ((0)) NOT NULL,
    [StdGrossWt]      FLOAT (53)    CONSTRAINT [DF_InventoryADG_StdGrossWt] DEFAULT ((0)) NOT NULL,
    [StdTareWt]       FLOAT (53)    CONSTRAINT [DF_InventoryADG_StdTareWt] DEFAULT ((0)) NOT NULL,
    [Style]           CHAR (20)     CONSTRAINT [DF_InventoryADG_Style] DEFAULT (' ') NOT NULL,
    [User1]           CHAR (30)     CONSTRAINT [DF_InventoryADG_User1] DEFAULT (' ') NOT NULL,
    [User10]          SMALLDATETIME CONSTRAINT [DF_InventoryADG_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]           CHAR (30)     CONSTRAINT [DF_InventoryADG_User2] DEFAULT (' ') NOT NULL,
    [User3]           CHAR (30)     CONSTRAINT [DF_InventoryADG_User3] DEFAULT (' ') NOT NULL,
    [User4]           CHAR (30)     CONSTRAINT [DF_InventoryADG_User4] DEFAULT (' ') NOT NULL,
    [User5]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_User5] DEFAULT ((0)) NOT NULL,
    [User6]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_User6] DEFAULT ((0)) NOT NULL,
    [User7]           CHAR (10)     CONSTRAINT [DF_InventoryADG_User7] DEFAULT (' ') NOT NULL,
    [User8]           CHAR (10)     CONSTRAINT [DF_InventoryADG_User8] DEFAULT (' ') NOT NULL,
    [User9]           SMALLDATETIME CONSTRAINT [DF_InventoryADG_User9] DEFAULT ('01/01/1900') NOT NULL,
    [Volume]          FLOAT (53)    CONSTRAINT [DF_InventoryADG_Volume] DEFAULT ((0)) NOT NULL,
    [VolUOM]          CHAR (6)      CONSTRAINT [DF_InventoryADG_VolUOM] DEFAULT (' ') NOT NULL,
    [Weight]          FLOAT (53)    CONSTRAINT [DF_InventoryADG_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]       CHAR (6)      CONSTRAINT [DF_InventoryADG_WeightUOM] DEFAULT (' ') NOT NULL,
    [Width]           FLOAT (53)    CONSTRAINT [DF_InventoryADG_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]        CHAR (5)      CONSTRAINT [DF_InventoryADG_WidthUOM] DEFAULT (' ') NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [InventoryADG0] PRIMARY KEY CLUSTERED ([InvtID] ASC) WITH (FILLFACTOR = 90)
);

