CREATE TABLE [dbo].[PJSUBVEN] (
    [carrier1]        CHAR (20)     NOT NULL,
    [carrier2]        CHAR (20)     NOT NULL,
    [carrier3]        CHAR (20)     NOT NULL,
    [carrier4]        CHAR (20)     NOT NULL,
    [carrier5]        CHAR (20)     NOT NULL,
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [date_ins_eff1]   SMALLDATETIME NOT NULL,
    [date_ins_eff2]   SMALLDATETIME NOT NULL,
    [date_ins_eff3]   SMALLDATETIME NOT NULL,
    [date_ins_eff4]   SMALLDATETIME NOT NULL,
    [date_ins_eff5]   SMALLDATETIME NOT NULL,
    [date_ins_exp1]   SMALLDATETIME NOT NULL,
    [date_ins_exp2]   SMALLDATETIME NOT NULL,
    [date_ins_exp3]   SMALLDATETIME NOT NULL,
    [date_ins_exp4]   SMALLDATETIME NOT NULL,
    [date_ins_exp5]   SMALLDATETIME NOT NULL,
    [eeo_class_cd]    CHAR (4)      NOT NULL,
    [flag_disabled]   CHAR (1)      NOT NULL,
    [flag_female]     CHAR (1)      NOT NULL,
    [flag_minority]   CHAR (1)      NOT NULL,
    [flag_preferred]  CHAR (1)      NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [noteid]          INT           NOT NULL,
    [pay_control]     CHAR (2)      NOT NULL,
    [policy_amt1]     FLOAT (53)    NOT NULL,
    [policy_amt2]     FLOAT (53)    NOT NULL,
    [policy_amt3]     FLOAT (53)    NOT NULL,
    [policy_amt4]     FLOAT (53)    NOT NULL,
    [policy_amt5]     FLOAT (53)    NOT NULL,
    [policy_nbr1]     CHAR (20)     NOT NULL,
    [policy_nbr2]     CHAR (20)     NOT NULL,
    [policy_nbr3]     CHAR (20)     NOT NULL,
    [policy_nbr4]     CHAR (20)     NOT NULL,
    [policy_nbr5]     CHAR (20)     NOT NULL,
    [policy_type_cd1] CHAR (2)      NOT NULL,
    [policy_type_cd2] CHAR (2)      NOT NULL,
    [policy_type_cd3] CHAR (2)      NOT NULL,
    [policy_type_cd4] CHAR (2)      NOT NULL,
    [policy_type_cd5] CHAR (2)      NOT NULL,
    [specialty_cd]    CHAR (4)      NOT NULL,
    [status]          CHAR (1)      NOT NULL,
    [sv_id01]         CHAR (30)     NOT NULL,
    [sv_id02]         CHAR (30)     NOT NULL,
    [sv_id03]         CHAR (16)     NOT NULL,
    [sv_id04]         CHAR (16)     NOT NULL,
    [sv_id05]         CHAR (4)      NOT NULL,
    [sv_id06]         FLOAT (53)    NOT NULL,
    [sv_id07]         FLOAT (53)    NOT NULL,
    [sv_id08]         SMALLDATETIME NOT NULL,
    [sv_id09]         SMALLDATETIME NOT NULL,
    [sv_id10]         INT           NOT NULL,
    [sv_id11]         CHAR (30)     NOT NULL,
    [sv_id12]         CHAR (30)     NOT NULL,
    [sv_id13]         CHAR (16)     NOT NULL,
    [sv_id14]         CHAR (16)     NOT NULL,
    [sv_id15]         CHAR (4)      NOT NULL,
    [sv_id16]         FLOAT (53)    NOT NULL,
    [sv_id17]         FLOAT (53)    NOT NULL,
    [sv_id18]         SMALLDATETIME NOT NULL,
    [sv_id19]         SMALLDATETIME NOT NULL,
    [sv_id20]         INT           NOT NULL,
    [user1]           CHAR (30)     NOT NULL,
    [user2]           CHAR (30)     NOT NULL,
    [user3]           FLOAT (53)    NOT NULL,
    [user4]           FLOAT (53)    NOT NULL,
    [user5]           CHAR (30)     NOT NULL,
    [user6]           CHAR (30)     NOT NULL,
    [user7]           FLOAT (53)    NOT NULL,
    [user8]           FLOAT (53)    NOT NULL,
    [vend_name]       CHAR (60)     NOT NULL,
    [vendid]          CHAR (15)     NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjsubven0] PRIMARY KEY CLUSTERED ([vendid] ASC) WITH (FILLFACTOR = 90)
);

