CREATE TABLE [dbo].[EDWrkContPrint] (
    [AccessNbr]   SMALLINT      CONSTRAINT [DF_EDWrkContPrint_AccessNbr] DEFAULT ((0)) NOT NULL,
    [CpnyID]      CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_CpnyID] DEFAULT (' ') NOT NULL,
    [CustID]      CHAR (15)     CONSTRAINT [DF_EDWrkContPrint_CustID] DEFAULT (' ') NOT NULL,
    [CustOrdNbr]  CHAR (25)     CONSTRAINT [DF_EDWrkContPrint_CustOrdNbr] DEFAULT (' ') NOT NULL,
    [OrdNbr]      CHAR (15)     CONSTRAINT [DF_EDWrkContPrint_OrdNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]  CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]  CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]  FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]  FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]  FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]  FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]  SMALLDATETIME CONSTRAINT [DF_EDWrkContPrint_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]  SMALLDATETIME CONSTRAINT [DF_EDWrkContPrint_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]  INT           CONSTRAINT [DF_EDWrkContPrint_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]  INT           CONSTRAINT [DF_EDWrkContPrint_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]  CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]  CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_S4Future12] DEFAULT (' ') NOT NULL,
    [Selected]    SMALLINT      CONSTRAINT [DF_EDWrkContPrint_Selected] DEFAULT ((0)) NOT NULL,
    [ShipDateAct] SMALLDATETIME CONSTRAINT [DF_EDWrkContPrint_ShipDateAct] DEFAULT ('01/01/1900') NOT NULL,
    [ShipperID]   CHAR (15)     CONSTRAINT [DF_EDWrkContPrint_ShipperID] DEFAULT (' ') NOT NULL,
    [ShiptoID]    CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_ShiptoID] DEFAULT (' ') NOT NULL,
    [ShipViaID]   CHAR (15)     CONSTRAINT [DF_EDWrkContPrint_ShipViaID] DEFAULT (' ') NOT NULL,
    [SiteID]      CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_SiteID] DEFAULT (' ') NOT NULL,
    [User1]       CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_User1] DEFAULT (' ') NOT NULL,
    [User10]      SMALLDATETIME CONSTRAINT [DF_EDWrkContPrint_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]       CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_User2] DEFAULT (' ') NOT NULL,
    [User3]       CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_User3] DEFAULT (' ') NOT NULL,
    [User4]       CHAR (30)     CONSTRAINT [DF_EDWrkContPrint_User4] DEFAULT (' ') NOT NULL,
    [User5]       FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_User5] DEFAULT ((0)) NOT NULL,
    [User6]       FLOAT (53)    CONSTRAINT [DF_EDWrkContPrint_User6] DEFAULT ((0)) NOT NULL,
    [User7]       CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_User7] DEFAULT (' ') NOT NULL,
    [User8]       CHAR (10)     CONSTRAINT [DF_EDWrkContPrint_User8] DEFAULT (' ') NOT NULL,
    [User9]       SMALLDATETIME CONSTRAINT [DF_EDWrkContPrint_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]      ROWVERSION    NOT NULL,
    CONSTRAINT [EDWrkContPrint0] PRIMARY KEY CLUSTERED ([AccessNbr] ASC, [ShipperID] ASC) WITH (FILLFACTOR = 90)
);

