CREATE TABLE [dbo].[WORouting] (
    [ActualCost]          FLOAT (53)    CONSTRAINT [DF_WORouting_ActualCost] DEFAULT ((0)) NOT NULL,
    [ActualHrs]           FLOAT (53)    CONSTRAINT [DF_WORouting_ActualHrs] DEFAULT ((0)) NOT NULL,
    [ActualLaborOvhFixed] FLOAT (53)    CONSTRAINT [DF_WORouting_ActualLaborOvhFixed] DEFAULT ((0)) NOT NULL,
    [ActualLaborOvhVar]   FLOAT (53)    CONSTRAINT [DF_WORouting_ActualLaborOvhVar] DEFAULT ((0)) NOT NULL,
    [ActualMachOvhFixed]  FLOAT (53)    CONSTRAINT [DF_WORouting_ActualMachOvhFixed] DEFAULT ((0)) NOT NULL,
    [ActualMachOvhVar]    FLOAT (53)    CONSTRAINT [DF_WORouting_ActualMachOvhVar] DEFAULT ((0)) NOT NULL,
    [ActualScrap]         FLOAT (53)    CONSTRAINT [DF_WORouting_ActualScrap] DEFAULT ((0)) NOT NULL,
    [ActualUnits]         FLOAT (53)    CONSTRAINT [DF_WORouting_ActualUnits] DEFAULT ((0)) NOT NULL,
    [BudgetCst]           FLOAT (53)    CONSTRAINT [DF_WORouting_BudgetCst] DEFAULT ((0)) NOT NULL,
    [BudgetHrs]           FLOAT (53)    CONSTRAINT [DF_WORouting_BudgetHrs] DEFAULT ((0)) NOT NULL,
    [CEngLbrHrs]          FLOAT (53)    CONSTRAINT [DF_WORouting_CEngLbrHrs] DEFAULT ((0)) NOT NULL,
    [CEngMachHrs]         FLOAT (53)    CONSTRAINT [DF_WORouting_CEngMachHrs] DEFAULT ((0)) NOT NULL,
    [CpnyID]              CHAR (10)     CONSTRAINT [DF_WORouting_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME CONSTRAINT [DF_WORouting_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]           CHAR (8)      CONSTRAINT [DF_WORouting_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_Time]           SMALLDATETIME CONSTRAINT [DF_WORouting_Crtd_Time] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_User]           CHAR (10)     CONSTRAINT [DF_WORouting_Crtd_User] DEFAULT (' ') NOT NULL,
    [InvtID]              CHAR (30)     CONSTRAINT [DF_WORouting_InvtID] DEFAULT (' ') NOT NULL,
    [LaborClassID]        CHAR (10)     CONSTRAINT [DF_WORouting_LaborClassID] DEFAULT (' ') NOT NULL,
    [LineNbr]             SMALLINT      CONSTRAINT [DF_WORouting_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]             CHAR (5)      CONSTRAINT [DF_WORouting_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME CONSTRAINT [DF_WORouting_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      CONSTRAINT [DF_WORouting_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUPd_Time]           SMALLDATETIME CONSTRAINT [DF_WORouting_LUPd_Time] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]           CHAR (10)     CONSTRAINT [DF_WORouting_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]              INT           CONSTRAINT [DF_WORouting_NoteID] DEFAULT ((0)) NOT NULL,
    [OperationID]         CHAR (10)     CONSTRAINT [DF_WORouting_OperationID] DEFAULT (' ') NOT NULL,
    [OperType]            CHAR (1)      CONSTRAINT [DF_WORouting_OperType] DEFAULT (' ') NOT NULL,
    [PlanStart]           SMALLDATETIME CONSTRAINT [DF_WORouting_PlanStart] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future01]          CHAR (30)     CONSTRAINT [DF_WORouting_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]          CHAR (30)     CONSTRAINT [DF_WORouting_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]          FLOAT (53)    CONSTRAINT [DF_WORouting_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]          FLOAT (53)    CONSTRAINT [DF_WORouting_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]          FLOAT (53)    CONSTRAINT [DF_WORouting_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]          FLOAT (53)    CONSTRAINT [DF_WORouting_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]          SMALLDATETIME CONSTRAINT [DF_WORouting_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]          SMALLDATETIME CONSTRAINT [DF_WORouting_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]          INT           CONSTRAINT [DF_WORouting_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]          INT           CONSTRAINT [DF_WORouting_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]          CHAR (10)     CONSTRAINT [DF_WORouting_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]          CHAR (10)     CONSTRAINT [DF_WORouting_S4Future12] DEFAULT (' ') NOT NULL,
    [StdRate]             FLOAT (53)    CONSTRAINT [DF_WORouting_StdRate] DEFAULT ((0)) NOT NULL,
    [StepAdded]           CHAR (1)      CONSTRAINT [DF_WORouting_StepAdded] DEFAULT (' ') NOT NULL,
    [StepComplete]        CHAR (1)      CONSTRAINT [DF_WORouting_StepComplete] DEFAULT (' ') NOT NULL,
    [StepHrs]             FLOAT (53)    CONSTRAINT [DF_WORouting_StepHrs] DEFAULT ((0)) NOT NULL,
    [StepNbr]             SMALLINT      CONSTRAINT [DF_WORouting_StepNbr] DEFAULT ((0)) NOT NULL,
    [Task]                CHAR (32)     CONSTRAINT [DF_WORouting_Task] DEFAULT (' ') NOT NULL,
    [User1]               CHAR (30)     CONSTRAINT [DF_WORouting_User1] DEFAULT (' ') NOT NULL,
    [User10]              CHAR (30)     CONSTRAINT [DF_WORouting_User10] DEFAULT (' ') NOT NULL,
    [User2]               CHAR (30)     CONSTRAINT [DF_WORouting_User2] DEFAULT (' ') NOT NULL,
    [User3]               FLOAT (53)    CONSTRAINT [DF_WORouting_User3] DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    CONSTRAINT [DF_WORouting_User4] DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     CONSTRAINT [DF_WORouting_User5] DEFAULT (' ') NOT NULL,
    [User6]               CHAR (10)     CONSTRAINT [DF_WORouting_User6] DEFAULT (' ') NOT NULL,
    [User7]               SMALLDATETIME CONSTRAINT [DF_WORouting_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME CONSTRAINT [DF_WORouting_User8] DEFAULT ('01/01/1900') NOT NULL,
    [User9]               CHAR (30)     CONSTRAINT [DF_WORouting_User9] DEFAULT (' ') NOT NULL,
    [WONbr]               CHAR (16)     CONSTRAINT [DF_WORouting_WONbr] DEFAULT (' ') NOT NULL,
    [WorkCenterID]        CHAR (10)     CONSTRAINT [DF_WORouting_WorkCenterID] DEFAULT (' ') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [WORouting0] PRIMARY KEY CLUSTERED ([WONbr] ASC, [Task] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

