CREATE TABLE [dbo].[CustEDDReceiver] (
    [BodyText]          CHAR (255)    NOT NULL,
    [CpnyID]            CHAR (10)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_user]         CHAR (10)     NOT NULL,
    [CustID]            CHAR (15)     NOT NULL,
    [DeliveryMethod]    CHAR (1)      NOT NULL,
    [DocType]           CHAR (2)      NOT NULL,
    [EDDEmail]          CHAR (80)     NOT NULL,
    [EDDFax]            CHAR (10)     NOT NULL,
    [EDDFaxPrefix]      CHAR (15)     NOT NULL,
    [EDDFaxUseAreaCode] SMALLINT      NOT NULL,
    [EmailFileType]     CHAR (1)      NOT NULL,
    [FaxComment]        CHAR (1)      NOT NULL,
    [FaxCover]          CHAR (1)      NOT NULL,
    [FaxReceiverName]   CHAR (60)     NOT NULL,
    [FaxRecycle]        CHAR (1)      NOT NULL,
    [FaxReply]          CHAR (1)      NOT NULL,
    [FaxReview]         CHAR (1)      NOT NULL,
    [FaxSenderName]     CHAR (60)     NOT NULL,
    [FaxSenderNbr]      CHAR (10)     NOT NULL,
    [FaxUrgent]         CHAR (1)      NOT NULL,
    [LineNbr]           SMALLINT      NOT NULL,
    [Lupd_DateTime]     SMALLDATETIME NOT NULL,
    [Lupd_Prog]         CHAR (8)      NOT NULL,
    [Lupd_User]         CHAR (10)     NOT NULL,
    [NoteID]            INT           NOT NULL,
    [Priority]          CHAR (1)      NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [SendersEmail]      CHAR (80)     NOT NULL,
    [ShipToID]          CHAR (10)     NOT NULL,
    [SubjectText]       CHAR (80)     NOT NULL,
    [UsePrimaryPref]    SMALLINT      NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [CustEDDReceiver0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [CustID] ASC, [DocType] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

