CREATE TABLE [dbo].[PJIMPEXP] (
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [data1]         CHAR (2)      NOT NULL,
    [data2]         CHAR (4)      NOT NULL,
    [data3]         CHAR (10)     NOT NULL,
    [data4]         CHAR (30)     NOT NULL,
    [data5]         CHAR (30)     NOT NULL,
    [fld01_col]     SMALLINT      NOT NULL,
    [fld02_col]     SMALLINT      NOT NULL,
    [fld03_col]     SMALLINT      NOT NULL,
    [fld04_col]     SMALLINT      NOT NULL,
    [fld05_col]     SMALLINT      NOT NULL,
    [fld06_col]     SMALLINT      NOT NULL,
    [fld07_col]     SMALLINT      NOT NULL,
    [fld08_col]     SMALLINT      NOT NULL,
    [fld09_col]     SMALLINT      NOT NULL,
    [fld10_col]     SMALLINT      NOT NULL,
    [fld11_col]     SMALLINT      NOT NULL,
    [fld12_col]     SMALLINT      NOT NULL,
    [fld13_col]     SMALLINT      NOT NULL,
    [fld14_col]     SMALLINT      NOT NULL,
    [fld15_col]     SMALLINT      NOT NULL,
    [fld16_col]     SMALLINT      NOT NULL,
    [fld17_col]     SMALLINT      NOT NULL,
    [fld18_col]     SMALLINT      NOT NULL,
    [fld19_col]     SMALLINT      NOT NULL,
    [fld20_col]     SMALLINT      NOT NULL,
    [fld21_col]     SMALLINT      NOT NULL,
    [fld22_col]     SMALLINT      NOT NULL,
    [fld23_col]     SMALLINT      NOT NULL,
    [fld24_col]     SMALLINT      NOT NULL,
    [fld25_col]     SMALLINT      NOT NULL,
    [fld26_col]     SMALLINT      NOT NULL,
    [fld27_col]     SMALLINT      NOT NULL,
    [fld28_col]     SMALLINT      NOT NULL,
    [fld29_col]     SMALLINT      NOT NULL,
    [fld30_col]     SMALLINT      NOT NULL,
    [fld31_col]     SMALLINT      NOT NULL,
    [fld32_col]     SMALLINT      NOT NULL,
    [fld33_col]     SMALLINT      NOT NULL,
    [fld34_col]     SMALLINT      NOT NULL,
    [fld35_col]     SMALLINT      NOT NULL,
    [fld36_col]     SMALLINT      NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [map_desc]      CHAR (30)     NOT NULL,
    [map_id]        CHAR (8)      NOT NULL,
    [map_type]      CHAR (2)      NOT NULL,
    [noteid]        INT           NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [pjimpexp0] PRIMARY KEY CLUSTERED ([map_type] ASC, [map_id] ASC) WITH (FILLFACTOR = 90)
);

