CREATE TABLE [dbo].[WOSetup] (
    [BackFlush]            CHAR (1)      CONSTRAINT [DF_WOSetup_BackFlush] DEFAULT (' ') NOT NULL,
    [BuildToTypeDefault]   CHAR (3)      CONSTRAINT [DF_WOSetup_BuildToTypeDefault] DEFAULT (' ') NOT NULL,
    [CloseLateChrgAcct]    CHAR (16)     CONSTRAINT [DF_WOSetup_CloseLateChrgAcct] DEFAULT (' ') NOT NULL,
    [CloseShort]           CHAR (1)      CONSTRAINT [DF_WOSetup_CloseShort] DEFAULT (' ') NOT NULL,
    [CloseUnapplied]       CHAR (1)      CONSTRAINT [DF_WOSetup_CloseUnapplied] DEFAULT (' ') NOT NULL,
    [CloseUnissued]        CHAR (1)      CONSTRAINT [DF_WOSetup_CloseUnissued] DEFAULT (' ') NOT NULL,
    [COGSNonInv_GLAcct]    CHAR (10)     CONSTRAINT [DF_WOSetup_COGSNonInv_GLAcct] DEFAULT (' ') NOT NULL,
    [COGSNonInv_GLSUb]     CHAR (24)     CONSTRAINT [DF_WOSetup_COGSNonInv_GLSUb] DEFAULT (' ') NOT NULL,
    [COGSNonInvOverRide]   CHAR (1)      CONSTRAINT [DF_WOSetup_COGSNonInvOverRide] DEFAULT (' ') NOT NULL,
    [CompAllocMethod]      CHAR (4)      CONSTRAINT [DF_WOSetup_CompAllocMethod] DEFAULT (' ') NOT NULL,
    [CompChkReleased]      CHAR (1)      CONSTRAINT [DF_WOSetup_CompChkReleased] DEFAULT (' ') NOT NULL,
    [CompCMDefault]        CHAR (1)      CONSTRAINT [DF_WOSetup_CompCMDefault] DEFAULT (' ') NOT NULL,
    [CompCMDisable]        CHAR (1)      CONSTRAINT [DF_WOSetup_CompCMDisable] DEFAULT (' ') NOT NULL,
    [CompGridAllowChgs]    CHAR (1)      CONSTRAINT [DF_WOSetup_CompGridAllowChgs] DEFAULT (' ') NOT NULL,
    [CompMapping]          CHAR (1)      CONSTRAINT [DF_WOSetup_CompMapping] DEFAULT (' ') NOT NULL,
    [CompScrapXferOut]     CHAR (1)      CONSTRAINT [DF_WOSetup_CompScrapXferOut] DEFAULT (' ') NOT NULL,
    [CompSubAssyVarAcct]   CHAR (16)     CONSTRAINT [DF_WOSetup_CompSubAssyVarAcct] DEFAULT (' ') NOT NULL,
    [CompVarTiming]        CHAR (1)      CONSTRAINT [DF_WOSetup_CompVarTiming] DEFAULT (' ') NOT NULL,
    [CompXferAllocFlag]    CHAR (1)      CONSTRAINT [DF_WOSetup_CompXferAllocFlag] DEFAULT (' ') NOT NULL,
    [CompZeroCost]         CHAR (1)      CONSTRAINT [DF_WOSetup_CompZeroCost] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME CONSTRAINT [DF_WOSetup_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      CONSTRAINT [DF_WOSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_Time]            SMALLDATETIME CONSTRAINT [DF_WOSetup_Crtd_Time] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_User]            CHAR (10)     CONSTRAINT [DF_WOSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [DeleteMonths]         SMALLINT      CONSTRAINT [DF_WOSetup_DeleteMonths] DEFAULT ((0)) NOT NULL,
    [DfltScheduleMaterial] CHAR (1)      CONSTRAINT [DF_WOSetup_DfltScheduleMaterial] DEFAULT (' ') NOT NULL,
    [DfltScheduling]       CHAR (1)      CONSTRAINT [DF_WOSetup_DfltScheduling] DEFAULT (' ') NOT NULL,
    [DirectLaborAC]        CHAR (16)     CONSTRAINT [DF_WOSetup_DirectLaborAC] DEFAULT (' ') NOT NULL,
    [DirectMtlAC]          CHAR (16)     CONSTRAINT [DF_WOSetup_DirectMtlAC] DEFAULT (' ') NOT NULL,
    [DirectOtherAC]        CHAR (16)     CONSTRAINT [DF_WOSetup_DirectOtherAC] DEFAULT (' ') NOT NULL,
    [GLEntriesTrnsfr]      CHAR (1)      CONSTRAINT [DF_WOSetup_GLEntriesTrnsfr] DEFAULT (' ') NOT NULL,
    [Init]                 CHAR (1)      CONSTRAINT [DF_WOSetup_Init] DEFAULT (' ') NOT NULL,
    [Labor_Acct]           CHAR (16)     CONSTRAINT [DF_WOSetup_Labor_Acct] DEFAULT (' ') NOT NULL,
    [LaborBdgUpdate]       CHAR (1)      CONSTRAINT [DF_WOSetup_LaborBdgUpdate] DEFAULT (' ') NOT NULL,
    [LaborBdgUpdPrj]       CHAR (1)      CONSTRAINT [DF_WOSetup_LaborBdgUpdPrj] DEFAULT (' ') NOT NULL,
    [LateChrg_GLAcct]      CHAR (10)     CONSTRAINT [DF_WOSetup_LateChrg_GLAcct] DEFAULT (' ') NOT NULL,
    [LateChrg_GLSub]       CHAR (24)     CONSTRAINT [DF_WOSetup_LateChrg_GLSub] DEFAULT (' ') NOT NULL,
    [LateChrgOverRide]     CHAR (1)      CONSTRAINT [DF_WOSetup_LateChrgOverRide] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME CONSTRAINT [DF_WOSetup_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      CONSTRAINT [DF_WOSetup_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUPd_Time]            SMALLDATETIME CONSTRAINT [DF_WOSetup_LUPd_Time] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]            CHAR (10)     CONSTRAINT [DF_WOSetup_LUpd_User] DEFAULT (' ') NOT NULL,
    [Material_Acct]        CHAR (16)     CONSTRAINT [DF_WOSetup_Material_Acct] DEFAULT (' ') NOT NULL,
    [MaterialBdgUpdate]    CHAR (1)      CONSTRAINT [DF_WOSetup_MaterialBdgUpdate] DEFAULT (' ') NOT NULL,
    [MaterialBdgUpdPrj]    CHAR (1)      CONSTRAINT [DF_WOSetup_MaterialBdgUpdPrj] DEFAULT (' ') NOT NULL,
    [Mfg_Task]             CHAR (32)     CONSTRAINT [DF_WOSetup_Mfg_Task] DEFAULT (' ') NOT NULL,
    [MfgGLSub]             CHAR (24)     CONSTRAINT [DF_WOSetup_MfgGLSub] DEFAULT (' ') NOT NULL,
    [NoteID]               INT           CONSTRAINT [DF_WOSetup_NoteID] DEFAULT ((0)) NOT NULL,
    [OvhLaborFixedAC]      CHAR (16)     CONSTRAINT [DF_WOSetup_OvhLaborFixedAC] DEFAULT (' ') NOT NULL,
    [OvhLaborVarAC]        CHAR (16)     CONSTRAINT [DF_WOSetup_OvhLaborVarAC] DEFAULT (' ') NOT NULL,
    [OvhMachFixedAC]       CHAR (16)     CONSTRAINT [DF_WOSetup_OvhMachFixedAC] DEFAULT (' ') NOT NULL,
    [OvhMachVarAC]         CHAR (16)     CONSTRAINT [DF_WOSetup_OvhMachVarAC] DEFAULT (' ') NOT NULL,
    [OvhMtlFixedAC]        CHAR (16)     CONSTRAINT [DF_WOSetup_OvhMtlFixedAC] DEFAULT (' ') NOT NULL,
    [OvhMtlVarAC]          CHAR (16)     CONSTRAINT [DF_WOSetup_OvhMtlVarAC] DEFAULT (' ') NOT NULL,
    [PerNbr]               CHAR (6)      CONSTRAINT [DF_WOSetup_PerNbr] DEFAULT (' ') NOT NULL,
    [PerNbrINDefault]      CHAR (1)      CONSTRAINT [DF_WOSetup_PerNbrINDefault] DEFAULT (' ') NOT NULL,
    [PrjWoGLIMDflt]        CHAR (1)      CONSTRAINT [DF_WOSetup_PrjWoGLIMDflt] DEFAULT (' ') NOT NULL,
    [PrjWoUpdTaskStatus]   CHAR (1)      CONSTRAINT [DF_WOSetup_PrjWoUpdTaskStatus] DEFAULT (' ') NOT NULL,
    [ProdFri]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdFri] DEFAULT (' ') NOT NULL,
    [ProdMon]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdMon] DEFAULT (' ') NOT NULL,
    [ProdSat]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdSat] DEFAULT (' ') NOT NULL,
    [ProdSun]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdSun] DEFAULT (' ') NOT NULL,
    [ProdThu]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdThu] DEFAULT (' ') NOT NULL,
    [ProdTue]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdTue] DEFAULT (' ') NOT NULL,
    [ProdWed]              CHAR (1)      CONSTRAINT [DF_WOSetup_ProdWed] DEFAULT (' ') NOT NULL,
    [RateTableID]          CHAR (4)      CONSTRAINT [DF_WOSetup_RateTableID] DEFAULT (' ') NOT NULL,
    [ReceiptReasonCode]    CHAR (6)      CONSTRAINT [DF_WOSetup_ReceiptReasonCode] DEFAULT (' ') NOT NULL,
    [RegAuthorizedUsers]   SMALLINT      CONSTRAINT [DF_WOSetup_RegAuthorizedUsers] DEFAULT ((0)) NOT NULL,
    [RegCustomerID]        CHAR (10)     CONSTRAINT [DF_WOSetup_RegCustomerID] DEFAULT (' ') NOT NULL,
    [RegOptions]           CHAR (15)     CONSTRAINT [DF_WOSetup_RegOptions] DEFAULT (' ') NOT NULL,
    [RegPlatform]          CHAR (1)      CONSTRAINT [DF_WOSetup_RegPlatform] DEFAULT (' ') NOT NULL,
    [RegUnlockKey]         CHAR (8)      CONSTRAINT [DF_WOSetup_RegUnlockKey] DEFAULT (' ') NOT NULL,
    [S4Future01]           CHAR (30)     CONSTRAINT [DF_WOSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     CONSTRAINT [DF_WOSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    CONSTRAINT [DF_WOSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    CONSTRAINT [DF_WOSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    CONSTRAINT [DF_WOSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    CONSTRAINT [DF_WOSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME CONSTRAINT [DF_WOSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME CONSTRAINT [DF_WOSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           CONSTRAINT [DF_WOSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           CONSTRAINT [DF_WOSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     CONSTRAINT [DF_WOSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     CONSTRAINT [DF_WOSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [ScrapCompInvtID]      CHAR (30)     CONSTRAINT [DF_WOSetup_ScrapCompInvtID] DEFAULT (' ') NOT NULL,
    [ScrapProdInvtID]      CHAR (30)     CONSTRAINT [DF_WOSetup_ScrapProdInvtID] DEFAULT (' ') NOT NULL,
    [SetupID]              CHAR (2)      CONSTRAINT [DF_WOSetup_SetupID] DEFAULT (' ') NOT NULL,
    [StdCostVar_GLAcct]    CHAR (10)     CONSTRAINT [DF_WOSetup_StdCostVar_GLAcct] DEFAULT (' ') NOT NULL,
    [StdCostVar_GLSub]     CHAR (24)     CONSTRAINT [DF_WOSetup_StdCostVar_GLSub] DEFAULT (' ') NOT NULL,
    [TransferAlloc]        CHAR (1)      CONSTRAINT [DF_WOSetup_TransferAlloc] DEFAULT (' ') NOT NULL,
    [User1]                CHAR (30)     CONSTRAINT [DF_WOSetup_User1] DEFAULT (' ') NOT NULL,
    [User10]               CHAR (30)     CONSTRAINT [DF_WOSetup_User10] DEFAULT (' ') NOT NULL,
    [User2]                CHAR (30)     CONSTRAINT [DF_WOSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]                FLOAT (53)    CONSTRAINT [DF_WOSetup_User3] DEFAULT ((0)) NOT NULL,
    [User4]                FLOAT (53)    CONSTRAINT [DF_WOSetup_User4] DEFAULT ((0)) NOT NULL,
    [User5]                CHAR (10)     CONSTRAINT [DF_WOSetup_User5] DEFAULT (' ') NOT NULL,
    [User6]                CHAR (10)     CONSTRAINT [DF_WOSetup_User6] DEFAULT (' ') NOT NULL,
    [User7]                SMALLDATETIME CONSTRAINT [DF_WOSetup_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]                SMALLDATETIME CONSTRAINT [DF_WOSetup_User8] DEFAULT ('01/01/1900') NOT NULL,
    [User9]                CHAR (30)     CONSTRAINT [DF_WOSetup_User9] DEFAULT (' ') NOT NULL,
    [VarianceTiming]       CHAR (1)      CONSTRAINT [DF_WOSetup_VarianceTiming] DEFAULT (' ') NOT NULL,
    [WOPendingProject]     CHAR (16)     CONSTRAINT [DF_WOSetup_WOPendingProject] DEFAULT (' ') NOT NULL,
    [WORequestRefresh]     SMALLINT      CONSTRAINT [DF_WOSetup_WORequestRefresh] DEFAULT ((0)) NOT NULL,
    [WOTypeDefault]        CHAR (1)      CONSTRAINT [DF_WOSetup_WOTypeDefault] DEFAULT (' ') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [WOSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

