CREATE TABLE [dbo].[XDDWrkCheckSel] (
    [AccessNbr]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [Acct]              CHAR (10)     DEFAULT ('') NOT NULL,
    [AdjFlag]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [ApplyRefNbr]       CHAR (10)     DEFAULT ('') NOT NULL,
    [BWAmt]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CheckCuryId]       CHAR (4)      DEFAULT ('') NOT NULL,
    [CheckCuryRate]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CheckCuryMultDiv]  CHAR (1)      DEFAULT ('') NOT NULL,
    [CpnyID]            CHAR (10)     DEFAULT ('') NOT NULL,
    [CheckRefNbr]       CHAR (10)     DEFAULT ('') NULL,
    [CuryBWAmt]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryDecPl]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [CuryDiscBal]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryDiscTkn]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryDocBal]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryEffDate]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [CuryId]            CHAR (4)      DEFAULT ('') NOT NULL,
    [CuryMultDiv]       CHAR (1)      DEFAULT ('') NOT NULL,
    [CuryPmtAmt]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRate]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRateType]      CHAR (6)      DEFAULT ('') NOT NULL,
    [DiscBal]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DiscDate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DiscTkn]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DocBal]            FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DocDesc]           CHAR (30)     DEFAULT ('') NOT NULL,
    [DocType]           CHAR (2)      DEFAULT ('') NOT NULL,
    [DueDate]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [EBActive]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [EBBatNbr]          CHAR (10)     DEFAULT ('') NOT NULL,
    [EBCheckDate]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [EBChkWF]           CHAR (1)      DEFAULT ('') NOT NULL,
    [EBChkWF_CreateMCB] CHAR (1)      DEFAULT ('') NOT NULL,
    [EBDescr]           CHAR (60)     DEFAULT ('') NOT NULL,
    [EBEmailNotif]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [EBEntryClass]      CHAR (4)      DEFAULT ('') NOT NULL,
    [EBEStatus]         CHAR (1)      DEFAULT ('') NOT NULL,
    [EBFormatID]        CHAR (15)     DEFAULT ('') NOT NULL,
    [EBGroup]           CHAR (1)      DEFAULT ('') NOT NULL,
    [EBInvcDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [EBInvcNbr]         CHAR (15)     DEFAULT ('') NOT NULL,
    [EBNACHATxn]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [EBPreNoteApp]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [EBSeparateTxnType] CHAR (10)     DEFAULT ('') NOT NULL,
    [EBTerminated]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [EBTxnType]         CHAR (10)     DEFAULT ('') NOT NULL,
    [EBVchCuryID]       CHAR (4)      DEFAULT ('') NOT NULL,
    [EBVendAcct]        CHAR (10)     DEFAULT ('') NOT NULL,
    [LineNbr]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [MultiChk]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [PayDate]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [PmtAmt]            FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RefNbr]            CHAR (10)     DEFAULT ('') NOT NULL,
    [ReqBkupWthld]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [S4Future01]        CHAR (30)     DEFAULT ('') NOT NULL,
    [S4Future02]        CHAR (30)     DEFAULT ('') NOT NULL,
    [S4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     DEFAULT ('') NOT NULL,
    [S4Future12]        CHAR (10)     DEFAULT ('') NOT NULL,
    [Sub]               CHAR (24)     DEFAULT ('') NOT NULL,
    [User1]             CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]             CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]             CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VendId]            CHAR (15)     DEFAULT ('') NOT NULL,
    [VendName]          CHAR (60)     DEFAULT ('') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [XDDWrkCheckSel0] PRIMARY KEY CLUSTERED ([AccessNbr] ASC, [VendId] ASC, [AdjFlag] ASC, [DocType] ASC, [RefNbr] ASC) WITH (FILLFACTOR = 90)
);

