CREATE TABLE [dbo].[SiteGroup] (
    [CpnyID]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [Descr]         CHAR (60)     DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [NoteID]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     DEFAULT (' ') NOT NULL,
    [SiteGroupID]   CHAR (10)     DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SiteGroup0] PRIMARY KEY CLUSTERED ([SiteGroupID] ASC) WITH (FILLFACTOR = 90)
);

