CREATE TABLE [dbo].[cftFeedOrderX] (
    [AvgWgt]        FLOAT (53)    NOT NULL,
    [BarnNbr]       CHAR (6)      NOT NULL,
    [BatNbrAP]      CHAR (10)     NOT NULL,
    [BatNbrGL]      CHAR (10)     NOT NULL,
    [BatNbrIN]      CHAR (10)     NOT NULL,
    [BinNbr]        CHAR (6)      NOT NULL,
    [CnvFactDel]    FLOAT (53)    NOT NULL,
    [CnvFactOrd]    FLOAT (53)    NOT NULL,
    [Comment]       CHAR (30)     NOT NULL,
    [CommentId]     CHAR (5)      NOT NULL,
    [ContactId]     CHAR (6)      NOT NULL,
    [ContactName]   CHAR (50)     NOT NULL,
    [ContAddrId]    CHAR (6)      NOT NULL,
    [CpnyId]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DateDel]       SMALLDATETIME NOT NULL,
    [DateOrd]       SMALLDATETIME NOT NULL,
    [DateReq]       SMALLDATETIME NOT NULL,
    [DateSched]     SMALLDATETIME NOT NULL,
    [DaysIn]        SMALLINT      NOT NULL,
    [FeedPlanId]    CHAR (4)      NOT NULL,
    [InvtIdDel]     CHAR (30)     NOT NULL,
    [InvtIdDflt]    CHAR (30)     NOT NULL,
    [InvtIdOrd]     CHAR (30)     NOT NULL,
    [IssueType]     CHAR (15)     NOT NULL,
    [LoadNbr]       CHAR (6)      NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [MillAddrId]    CHAR (6)      NOT NULL,
    [MillId]        CHAR (6)      NOT NULL,
    [NoteId]        INT           NOT NULL,
    [OrdNbr]        CHAR (10)     NOT NULL,
    [OrdType]       CHAR (2)      NOT NULL,
    [PGQty]         INT           NOT NULL,
    [PigGroupId]    CHAR (10)     NOT NULL,
    [Priority]      CHAR (10)     NOT NULL,
    [Project]       CHAR (16)     NOT NULL,
    [PrtFlg]        SMALLINT      NOT NULL,
    [QtyDel]        FLOAT (53)    NOT NULL,
    [QtyOrd]        FLOAT (53)    NOT NULL,
    [Reversal]      SMALLINT      NOT NULL,
    [RoomNbr]       CHAR (10)     NOT NULL,
    [StageDflt]     SMALLINT      NOT NULL,
    [StageOrd]      SMALLINT      NOT NULL,
    [Status]        CHAR (1)      NOT NULL,
    [TaskId]        CHAR (32)     NOT NULL,
    [UOMDel]        CHAR (6)      NOT NULL,
    [UOMOrd]        CHAR (6)      NOT NULL,
    [tstamp]        ROWVERSION    NULL
);

