CREATE TABLE [dbo].[BCShipping] (
    [CpnyID]         CHAR (10)     CONSTRAINT [DF_BCShipping_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME CONSTRAINT [DF_BCShipping_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]      CHAR (8)      CONSTRAINT [DF_BCShipping_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]      CHAR (10)     CONSTRAINT [DF_BCShipping_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]         CHAR (10)     CONSTRAINT [DF_BCShipping_CustID] DEFAULT (' ') NOT NULL,
    [Freight]        FLOAT (53)    CONSTRAINT [DF_BCShipping_Freight] DEFAULT ((0)) NOT NULL,
    [InvtID]         CHAR (30)     CONSTRAINT [DF_BCShipping_InvtID] DEFAULT (' ') NOT NULL,
    [LotSerNbr]      CHAR (15)     CONSTRAINT [DF_BCShipping_LotSerNbr] DEFAULT (' ') NOT NULL,
    [LotSerTrack]    CHAR (1)      CONSTRAINT [DF_BCShipping_LotSerTrack] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME CONSTRAINT [DF_BCShipping_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]      CHAR (8)      CONSTRAINT [DF_BCShipping_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]      CHAR (10)     CONSTRAINT [DF_BCShipping_LUpd_User] DEFAULT (' ') NOT NULL,
    [MiscCharge]     FLOAT (53)    CONSTRAINT [DF_BCShipping_MiscCharge] DEFAULT ((0)) NOT NULL,
    [QtyShip]        FLOAT (53)    CONSTRAINT [DF_BCShipping_QtyShip] DEFAULT ((0)) NOT NULL,
    [RefNbr]         CHAR (6)      CONSTRAINT [DF_BCShipping_RefNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]     CHAR (30)     CONSTRAINT [DF_BCShipping_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]     CHAR (30)     CONSTRAINT [DF_BCShipping_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]     FLOAT (53)    CONSTRAINT [DF_BCShipping_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]     FLOAT (53)    CONSTRAINT [DF_BCShipping_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]     FLOAT (53)    CONSTRAINT [DF_BCShipping_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]     FLOAT (53)    CONSTRAINT [DF_BCShipping_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]     SMALLDATETIME CONSTRAINT [DF_BCShipping_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]     SMALLDATETIME CONSTRAINT [DF_BCShipping_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]     INT           CONSTRAINT [DF_BCShipping_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]     INT           CONSTRAINT [DF_BCShipping_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]     CHAR (10)     CONSTRAINT [DF_BCShipping_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]     CHAR (10)     CONSTRAINT [DF_BCShipping_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipperID]      CHAR (15)     CONSTRAINT [DF_BCShipping_ShipperID] DEFAULT (' ') NOT NULL,
    [ShipperLineRef] CHAR (5)      CONSTRAINT [DF_BCShipping_ShipperLineRef] DEFAULT (' ') NOT NULL,
    [SiteID]         CHAR (10)     CONSTRAINT [DF_BCShipping_SiteID] DEFAULT (' ') NOT NULL,
    [Status]         CHAR (2)      CONSTRAINT [DF_BCShipping_Status] DEFAULT (' ') NOT NULL,
    [SubstItem]      CHAR (20)     CONSTRAINT [DF_BCShipping_SubstItem] DEFAULT (' ') NOT NULL,
    [sUser]          CHAR (10)     CONSTRAINT [DF_BCShipping_sUser] DEFAULT (' ') NOT NULL,
    [TransType]      CHAR (2)      CONSTRAINT [DF_BCShipping_TransType] DEFAULT (' ') NOT NULL,
    [UnitDesc]       CHAR (6)      CONSTRAINT [DF_BCShipping_UnitDesc] DEFAULT (' ') NOT NULL,
    [User1]          CHAR (30)     CONSTRAINT [DF_BCShipping_User1] DEFAULT (' ') NOT NULL,
    [User2]          CHAR (30)     CONSTRAINT [DF_BCShipping_User2] DEFAULT (' ') NOT NULL,
    [User3]          FLOAT (53)    CONSTRAINT [DF_BCShipping_User3] DEFAULT ((0)) NOT NULL,
    [User4]          FLOAT (53)    CONSTRAINT [DF_BCShipping_User4] DEFAULT ((0)) NOT NULL,
    [User5]          CHAR (10)     CONSTRAINT [DF_BCShipping_User5] DEFAULT (' ') NOT NULL,
    [User6]          CHAR (10)     CONSTRAINT [DF_BCShipping_User6] DEFAULT (' ') NOT NULL,
    [User7]          SMALLDATETIME CONSTRAINT [DF_BCShipping_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]          SMALLDATETIME CONSTRAINT [DF_BCShipping_User8] DEFAULT ('01/01/1900') NOT NULL,
    [WhseLoc]        CHAR (10)     CONSTRAINT [DF_BCShipping_WhseLoc] DEFAULT (' ') NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL
);

