CREATE TABLE [dbo].[CSDetail] (
    [CalcExpl]          CHAR (255)    CONSTRAINT [DF_CSDetail_CalcExpl] DEFAULT (' ') NOT NULL,
    [CommPct]           FLOAT (53)    CONSTRAINT [DF_CSDetail_CommPct] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME CONSTRAINT [DF_CSDetail_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      CONSTRAINT [DF_CSDetail_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     CONSTRAINT [DF_CSDetail_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryLineCommAmt]   FLOAT (53)    CONSTRAINT [DF_CSDetail_CuryLineCommAmt] DEFAULT ((0)) NOT NULL,
    [CuryLineCommTotal] FLOAT (53)    CONSTRAINT [DF_CSDetail_CuryLineCommTotal] DEFAULT ((0)) NOT NULL,
    [CuryLinePlusAmt]   FLOAT (53)    CONSTRAINT [DF_CSDetail_CuryLinePlusAmt] DEFAULT ((0)) NOT NULL,
    [Descr]             CHAR (30)     CONSTRAINT [DF_CSDetail_Descr] DEFAULT (' ') NOT NULL,
    [ExtCost]           FLOAT (53)    CONSTRAINT [DF_CSDetail_ExtCost] DEFAULT ((0)) NOT NULL,
    [ExtPrice]          FLOAT (53)    CONSTRAINT [DF_CSDetail_ExtPrice] DEFAULT ((0)) NOT NULL,
    [GMPct]             FLOAT (53)    CONSTRAINT [DF_CSDetail_GMPct] DEFAULT ((0)) NOT NULL,
    [InvcLineNbr]       SMALLINT      CONSTRAINT [DF_CSDetail_InvcLineNbr] DEFAULT ((0)) NOT NULL,
    [InvcRecordID]      INT           CONSTRAINT [DF_CSDetail_InvcRecordID] DEFAULT ((0)) NOT NULL,
    [InvtID]            CHAR (30)     CONSTRAINT [DF_CSDetail_InvtID] DEFAULT (' ') NOT NULL,
    [LineCommAmt]       FLOAT (53)    CONSTRAINT [DF_CSDetail_LineCommAmt] DEFAULT ((0)) NOT NULL,
    [LineCommRate]      FLOAT (53)    CONSTRAINT [DF_CSDetail_LineCommRate] DEFAULT ((0)) NOT NULL,
    [LineCommTotal]     FLOAT (53)    CONSTRAINT [DF_CSDetail_LineCommTotal] DEFAULT ((0)) NOT NULL,
    [LinePlusAmt]       FLOAT (53)    CONSTRAINT [DF_CSDetail_LinePlusAmt] DEFAULT ((0)) NOT NULL,
    [LinePlusMult]      FLOAT (53)    CONSTRAINT [DF_CSDetail_LinePlusMult] DEFAULT ((0)) NOT NULL,
    [LineRef]           CHAR (5)      CONSTRAINT [DF_CSDetail_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME CONSTRAINT [DF_CSDetail_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      CONSTRAINT [DF_CSDetail_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     CONSTRAINT [DF_CSDetail_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]            INT           CONSTRAINT [DF_CSDetail_NoteID] DEFAULT ((0)) NOT NULL,
    [OrderLineNbr]      SMALLINT      CONSTRAINT [DF_CSDetail_OrderLineNbr] DEFAULT ((0)) NOT NULL,
    [Price]             FLOAT (53)    CONSTRAINT [DF_CSDetail_Price] DEFAULT ((0)) NOT NULL,
    [Qty]               FLOAT (53)    CONSTRAINT [DF_CSDetail_Qty] DEFAULT ((0)) NOT NULL,
    [S4Future01]        CHAR (30)     CONSTRAINT [DF_CSDetail_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     CONSTRAINT [DF_CSDetail_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    CONSTRAINT [DF_CSDetail_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    CONSTRAINT [DF_CSDetail_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    CONSTRAINT [DF_CSDetail_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    CONSTRAINT [DF_CSDetail_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME CONSTRAINT [DF_CSDetail_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME CONSTRAINT [DF_CSDetail_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           CONSTRAINT [DF_CSDetail_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           CONSTRAINT [DF_CSDetail_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     CONSTRAINT [DF_CSDetail_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     CONSTRAINT [DF_CSDetail_S4Future12] DEFAULT (' ') NOT NULL,
    [SplitPct]          FLOAT (53)    CONSTRAINT [DF_CSDetail_SplitPct] DEFAULT ((0)) NOT NULL,
    [StmntID]           CHAR (10)     CONSTRAINT [DF_CSDetail_StmntID] DEFAULT (' ') NOT NULL,
    [TranRef]           CHAR (5)      CONSTRAINT [DF_CSDetail_TranRef] DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     CONSTRAINT [DF_CSDetail_User1] DEFAULT (' ') NOT NULL,
    [User10]            SMALLDATETIME CONSTRAINT [DF_CSDetail_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]             CHAR (30)     CONSTRAINT [DF_CSDetail_User2] DEFAULT (' ') NOT NULL,
    [User3]             CHAR (30)     CONSTRAINT [DF_CSDetail_User3] DEFAULT (' ') NOT NULL,
    [User4]             CHAR (30)     CONSTRAINT [DF_CSDetail_User4] DEFAULT (' ') NOT NULL,
    [User5]             FLOAT (53)    CONSTRAINT [DF_CSDetail_User5] DEFAULT ((0)) NOT NULL,
    [User6]             FLOAT (53)    CONSTRAINT [DF_CSDetail_User6] DEFAULT ((0)) NOT NULL,
    [User7]             CHAR (10)     CONSTRAINT [DF_CSDetail_User7] DEFAULT (' ') NOT NULL,
    [User8]             CHAR (10)     CONSTRAINT [DF_CSDetail_User8] DEFAULT (' ') NOT NULL,
    [User9]             SMALLDATETIME CONSTRAINT [DF_CSDetail_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [CSDetail0] PRIMARY KEY CLUSTERED ([StmntID] ASC, [TranRef] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);

