CREATE TABLE [dbo].[XDDBatchARLB] (
    [Acct]            CHAR (10)     DEFAULT ('') NOT NULL,
    [Amount]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AmountApplied]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ApplicMethod]    CHAR (2)      DEFAULT ('') NOT NULL,
    [BankAcct]        CHAR (30)     DEFAULT ('') NOT NULL,
    [BankTransit]     CHAR (30)     DEFAULT ('') NOT NULL,
    [CpnyID]          CHAR (10)     DEFAULT ('') NOT NULL,
    [CpnyIDInv]       CHAR (10)     DEFAULT ('') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]       CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]       CHAR (10)     DEFAULT ('') NOT NULL,
    [CuryID]          CHAR (4)      DEFAULT ('') NOT NULL,
    [CustID]          CHAR (15)     DEFAULT ('') NOT NULL,
    [CustIDErr]       CHAR (1)      DEFAULT ('') NOT NULL,
    [CustIDSugg]      CHAR (15)     DEFAULT ('') NOT NULL,
    [CustName]        CHAR (30)     DEFAULT ('') NOT NULL,
    [Descr]           CHAR (30)     DEFAULT ('') NOT NULL,
    [DocDate]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DocType]         CHAR (2)      DEFAULT ('') NOT NULL,
    [FileDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [FilePathName]    CHAR (255)    DEFAULT ('') NOT NULL,
    [FileRecord]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [FormatID]        CHAR (15)     DEFAULT ('') NOT NULL,
    [InvApplyAmt]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [InvcLeftUnappl]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [InvcNbr]         CHAR (10)     DEFAULT ('') NOT NULL,
    [InvcNbrErr]      CHAR (1)      DEFAULT ('') NOT NULL,
    [LBBatNbr]        CHAR (10)     DEFAULT ('') NOT NULL,
    [LBCustID]        CHAR (15)     DEFAULT ('') NOT NULL,
    [LineNbr]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]       CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]       CHAR (10)     DEFAULT ('') NOT NULL,
    [NoteID]          INT           DEFAULT ((0)) NOT NULL,
    [PmtApplicBatNbr] CHAR (10)     DEFAULT ('') NOT NULL,
    [PmtApplicRefNbr] CHAR (10)     DEFAULT ('') NOT NULL,
    [RecordID]        INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RefNbr]          CHAR (10)     DEFAULT ('') NOT NULL,
    [RefNbrDupe]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [SKFuture01]      CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]      CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]      INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]      INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]      CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]      CHAR (10)     DEFAULT ('') NOT NULL,
    [Sub]             CHAR (24)     DEFAULT ('') NOT NULL,
    [TotalRemBal]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User1]           CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]          CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]           CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]           CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]           CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]           CHAR (30)     DEFAULT ('') NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [XDDBatchARLB0] PRIMARY KEY CLUSTERED ([LBBatNbr] ASC, [CustID] ASC, [LineNbr] ASC, [RecordID] ASC)
);

