CREATE TABLE [dbo].[WSPInstance] (
    [Crtd_DateTime]      SMALLDATETIME NOT NULL,
    [Crtd_Prog]          CHAR (8)      NOT NULL,
    [Crtd_User]          CHAR (10)     NOT NULL,
    [defaultCreationOpt] CHAR (1)      NOT NULL,
    [docLibName]         CHAR (100)    NOT NULL,
    [docLibOrSite]       CHAR (1)      NOT NULL,
    [docLibTemplate]     CHAR (128)    NOT NULL,
    [EntityKey]          CHAR (64)     NOT NULL,
    [inheritPermissions] CHAR (1)      NOT NULL,
    [Lupd_DateTime]      SMALLDATETIME NOT NULL,
    [Lupd_Prog]          CHAR (8)      NOT NULL,
    [Lupd_User]          CHAR (10)     NOT NULL,
    [rootSiteUrl]        CHAR (150)    NOT NULL,
    [S4Future01]         CHAR (30)     NOT NULL,
    [S4Future02]         CHAR (30)     NOT NULL,
    [S4Future03]         FLOAT (53)    NOT NULL,
    [S4Future04]         FLOAT (53)    NOT NULL,
    [S4Future05]         FLOAT (53)    NOT NULL,
    [S4Future06]         FLOAT (53)    NOT NULL,
    [S4Future07]         SMALLDATETIME NOT NULL,
    [S4Future08]         SMALLDATETIME NOT NULL,
    [S4Future09]         INT           NOT NULL,
    [S4Future10]         INT           NOT NULL,
    [S4Future11]         CHAR (10)     NOT NULL,
    [S4Future12]         CHAR (10)     NOT NULL,
    [SPtemplate]         CHAR (128)    NOT NULL,
    [SLTypeID]           SMALLINT      NOT NULL,
    [SLTypeDesc]         CHAR (60)     NOT NULL,
    [spdocLibTemplate]   CHAR (128)    NOT NULL,
    [Status]             CHAR (1)      NOT NULL,
    [subSiteNamePrefix]  CHAR (100)    NOT NULL,
    [templateFile]       CHAR (128)    NOT NULL,
    [User1]              CHAR (30)     NOT NULL,
    [User10]             SMALLDATETIME NOT NULL,
    [User2]              CHAR (30)     NOT NULL,
    [User3]              CHAR (30)     NOT NULL,
    [User4]              CHAR (30)     NOT NULL,
    [User5]              FLOAT (53)    NOT NULL,
    [User6]              FLOAT (53)    NOT NULL,
    [User7]              CHAR (10)     NOT NULL,
    [User8]              CHAR (10)     NOT NULL,
    [User9]              SMALLDATETIME NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [WSPInstance0] PRIMARY KEY CLUSTERED ([SLTypeID] ASC, [SLTypeDesc] ASC) WITH (FILLFACTOR = 90)
);

