CREATE TABLE [dbo].[TempCloseInfo] (
    [CalQtr00]       SMALLINT      NOT NULL,
    [CalQtr01]       SMALLINT      NOT NULL,
    [CalQtr02]       SMALLINT      NOT NULL,
    [CalQtr03]       SMALLINT      NOT NULL,
    [CalQtr04]       SMALLINT      NOT NULL,
    [CalQtr05]       SMALLINT      NOT NULL,
    [CalQtr06]       SMALLINT      NOT NULL,
    [CalQtr07]       SMALLINT      NOT NULL,
    [CalQtr08]       SMALLINT      NOT NULL,
    [CalYr00]        CHAR (4)      NOT NULL,
    [CalYr01]        CHAR (4)      NOT NULL,
    [CalYr02]        CHAR (4)      NOT NULL,
    [CalYr03]        CHAR (4)      NOT NULL,
    [CalYr04]        CHAR (4)      NOT NULL,
    [CalYr05]        CHAR (4)      NOT NULL,
    [CalYr06]        CHAR (4)      NOT NULL,
    [CalYr07]        CHAR (4)      NOT NULL,
    [CalYr08]        CHAR (4)      NOT NULL,
    [CloseType00]    CHAR (1)      NOT NULL,
    [CloseType01]    CHAR (1)      NOT NULL,
    [CloseType02]    CHAR (1)      NOT NULL,
    [CloseType03]    CHAR (1)      NOT NULL,
    [CloseType04]    CHAR (1)      NOT NULL,
    [CloseType05]    CHAR (1)      NOT NULL,
    [CloseType06]    CHAR (1)      NOT NULL,
    [CloseType07]    CHAR (1)      NOT NULL,
    [CloseType08]    CHAR (1)      NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [CurrFiscPer00]  CHAR (2)      NOT NULL,
    [CurrFiscPer01]  CHAR (2)      NOT NULL,
    [CurrFiscPer02]  CHAR (2)      NOT NULL,
    [CurrFiscPer03]  CHAR (2)      NOT NULL,
    [CurrFiscPer04]  CHAR (2)      NOT NULL,
    [CurrFiscPer05]  CHAR (2)      NOT NULL,
    [CurrFiscPer06]  CHAR (2)      NOT NULL,
    [CurrFiscPer07]  CHAR (2)      NOT NULL,
    [CurrFiscPer08]  CHAR (2)      NOT NULL,
    [DeleteDetail00] SMALLINT      NOT NULL,
    [DeleteDetail01] SMALLINT      NOT NULL,
    [DeleteDetail02] SMALLINT      NOT NULL,
    [DeleteDetail03] SMALLINT      NOT NULL,
    [DeleteDetail04] SMALLINT      NOT NULL,
    [DeleteDetail05] SMALLINT      NOT NULL,
    [DeleteDetail06] SMALLINT      NOT NULL,
    [DeleteDetail07] SMALLINT      NOT NULL,
    [DeleteDetail08] SMALLINT      NOT NULL,
    [Init00]         SMALLINT      NOT NULL,
    [Init01]         SMALLINT      NOT NULL,
    [Init02]         SMALLINT      NOT NULL,
    [Init03]         SMALLINT      NOT NULL,
    [Init04]         SMALLINT      NOT NULL,
    [Init05]         SMALLINT      NOT NULL,
    [Init06]         SMALLINT      NOT NULL,
    [Init07]         SMALLINT      NOT NULL,
    [Init08]         SMALLINT      NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [Module00]       CHAR (2)      NOT NULL,
    [Module01]       CHAR (2)      NOT NULL,
    [Module02]       CHAR (2)      NOT NULL,
    [Module03]       CHAR (2)      NOT NULL,
    [Module04]       CHAR (2)      NOT NULL,
    [Module05]       CHAR (2)      NOT NULL,
    [Module06]       CHAR (2)      NOT NULL,
    [Module07]       CHAR (2)      NOT NULL,
    [Module08]       CHAR (2)      NOT NULL,
    [PerNbr00]       CHAR (6)      NOT NULL,
    [PerNbr01]       CHAR (6)      NOT NULL,
    [PerNbr02]       CHAR (6)      NOT NULL,
    [PerNbr03]       CHAR (6)      NOT NULL,
    [PerNbr04]       CHAR (6)      NOT NULL,
    [PerNbr05]       CHAR (6)      NOT NULL,
    [PerNbr06]       CHAR (6)      NOT NULL,
    [PerNbr07]       CHAR (6)      NOT NULL,
    [PerNbr08]       CHAR (6)      NOT NULL,
    [S4Future01]     CHAR (30)     NOT NULL,
    [S4Future02]     CHAR (30)     NOT NULL,
    [S4Future03]     FLOAT (53)    NOT NULL,
    [S4Future04]     FLOAT (53)    NOT NULL,
    [S4Future05]     FLOAT (53)    NOT NULL,
    [S4Future06]     FLOAT (53)    NOT NULL,
    [S4Future07]     SMALLDATETIME NOT NULL,
    [S4Future08]     SMALLDATETIME NOT NULL,
    [S4Future09]     INT           NOT NULL,
    [S4Future10]     INT           NOT NULL,
    [S4Future11]     CHAR (10)     NOT NULL,
    [S4Future12]     CHAR (10)     NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [TempCloseInfo0] PRIMARY KEY CLUSTERED ([Module00] ASC, [PerNbr00] ASC) WITH (FILLFACTOR = 90)
);

