CREATE TABLE [dbo].[PJCONT] (
    [change_days]     SMALLINT      NOT NULL,
    [change_flag]     CHAR (1)      NOT NULL,
    [contract]        CHAR (16)     NOT NULL,
    [contract_desc]   CHAR (60)     NOT NULL,
    [cn_id01]         CHAR (30)     NOT NULL,
    [cn_id02]         CHAR (30)     NOT NULL,
    [cn_id03]         CHAR (16)     NOT NULL,
    [cn_id04]         CHAR (16)     NOT NULL,
    [cn_id05]         CHAR (4)      NOT NULL,
    [cn_id06]         FLOAT (53)    NOT NULL,
    [cn_id07]         FLOAT (53)    NOT NULL,
    [cn_id08]         SMALLDATETIME NOT NULL,
    [cn_id09]         SMALLDATETIME NOT NULL,
    [cn_id10]         INT           NOT NULL,
    [cn_id11]         CHAR (30)     NOT NULL,
    [cn_id12]         CHAR (30)     NOT NULL,
    [cn_id13]         CHAR (16)     NOT NULL,
    [cn_id14]         CHAR (16)     NOT NULL,
    [cn_id15]         CHAR (4)      NOT NULL,
    [cn_id16]         FLOAT (53)    NOT NULL,
    [cn_id17]         FLOAT (53)    NOT NULL,
    [cn_id18]         SMALLDATETIME NOT NULL,
    [cn_id19]         SMALLDATETIME NOT NULL,
    [cn_id20]         INT           NOT NULL,
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [cust_ref]        CHAR (30)     NOT NULL,
    [customer]        CHAR (15)     NOT NULL,
    [date_comp_act]   SMALLDATETIME NOT NULL,
    [date_comp_ant]   SMALLDATETIME NOT NULL,
    [date_cont_exe]   SMALLDATETIME NOT NULL,
    [date_start_act]  SMALLDATETIME NOT NULL,
    [date_start_ant]  SMALLDATETIME NOT NULL,
    [date_start_auth] SMALLDATETIME NOT NULL,
    [date_start_org]  SMALLDATETIME NOT NULL,
    [date_end_org]    SMALLDATETIME NOT NULL,
    [date_end_rev]    SMALLDATETIME NOT NULL,
    [extension_days]  SMALLINT      NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [manager_acct]    CHAR (10)     NOT NULL,
    [manager_cont]    CHAR (10)     NOT NULL,
    [noteid]          INT           NOT NULL,
    [prime_type_cd]   CHAR (4)      NOT NULL,
    [status1]         CHAR (1)      NOT NULL,
    [termsid]         CHAR (2)      NOT NULL,
    [text_contract1]  CHAR (254)    NOT NULL,
    [text_contract2]  CHAR (254)    NOT NULL,
    [user1]           CHAR (30)     NOT NULL,
    [user2]           CHAR (30)     NOT NULL,
    [user3]           FLOAT (53)    NOT NULL,
    [user4]           FLOAT (53)    NOT NULL,
    [user5]           CHAR (30)     NOT NULL,
    [user6]           CHAR (30)     NOT NULL,
    [user7]           FLOAT (53)    NOT NULL,
    [user8]           FLOAT (53)    NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjcont0] PRIMARY KEY CLUSTERED ([contract] ASC) WITH (FILLFACTOR = 90)
);

