CREATE TABLE [dbo].[BCTransfers] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_BCTransfers_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_BCTransfers_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_BCTransfers_Crtd_User] DEFAULT (' ') NOT NULL,
    [FromSite]      CHAR (6)      CONSTRAINT [DF_BCTransfers_FromSite] DEFAULT (' ') NOT NULL,
    [FromWhseLoc]   CHAR (10)     CONSTRAINT [DF_BCTransfers_FromWhseLoc] DEFAULT (' ') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_BCTransfers_InvtID] DEFAULT (' ') NOT NULL,
    [LotSerNbr]     CHAR (15)     CONSTRAINT [DF_BCTransfers_LotSerNbr] DEFAULT (' ') NOT NULL,
    [LotSerTrack]   CHAR (1)      CONSTRAINT [DF_BCTransfers_LotSerTrack] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_BCTransfers_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_BCTransfers_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_BCTransfers_LUpd_User] DEFAULT (' ') NOT NULL,
    [Qty]           FLOAT (53)    CONSTRAINT [DF_BCTransfers_Qty] DEFAULT ((0)) NOT NULL,
    [RefNbr]        CHAR (6)      CONSTRAINT [DF_BCTransfers_RefNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_BCTransfers_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_BCTransfers_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_BCTransfers_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_BCTransfers_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_BCTransfers_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_BCTransfers_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_BCTransfers_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_BCTransfers_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_BCTransfers_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_BCTransfers_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_BCTransfers_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_BCTransfers_S4Future12] DEFAULT (' ') NOT NULL,
    [Status]        CHAR (2)      CONSTRAINT [DF_BCTransfers_Status] DEFAULT (' ') NOT NULL,
    [sUser]         CHAR (10)     CONSTRAINT [DF_BCTransfers_sUser] DEFAULT (' ') NOT NULL,
    [ToSite]        CHAR (6)      CONSTRAINT [DF_BCTransfers_ToSite] DEFAULT (' ') NOT NULL,
    [ToWhseLoc]     CHAR (10)     CONSTRAINT [DF_BCTransfers_ToWhseLoc] DEFAULT (' ') NOT NULL,
    [TranDate]      SMALLDATETIME CONSTRAINT [DF_BCTransfers_TranDate] DEFAULT ('01/01/1900') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_BCTransfers_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_BCTransfers_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_BCTransfers_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_BCTransfers_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_BCTransfers_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_BCTransfers_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_BCTransfers_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_BCTransfers_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL
);

