CREATE TABLE [dbo].[ED810Header] (
    [BackOrderFlag]        SMALLINT      CONSTRAINT [DF_ED810Header_BackOrderFlag] DEFAULT ((0)) NOT NULL,
    [BlktPONbr]            CHAR (20)     CONSTRAINT [DF_ED810Header_BlktPONbr] DEFAULT (' ') NOT NULL,
    [BOLNbr]               CHAR (20)     CONSTRAINT [DF_ED810Header_BOLNbr] DEFAULT (' ') NOT NULL,
    [BuyerID]              CHAR (10)     CONSTRAINT [DF_ED810Header_BuyerID] DEFAULT (' ') NOT NULL,
    [BuyerName]            CHAR (30)     CONSTRAINT [DF_ED810Header_BuyerName] DEFAULT (' ') NOT NULL,
    [ChangeOrdNbr]         CHAR (10)     CONSTRAINT [DF_ED810Header_ChangeOrdNbr] DEFAULT (' ') NOT NULL,
    [CpnyID]               CHAR (10)     CONSTRAINT [DF_ED810Header_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME CONSTRAINT [DF_ED810Header_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      CONSTRAINT [DF_ED810Header_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]            CHAR (10)     CONSTRAINT [DF_ED810Header_Crtd_User] DEFAULT (' ') NOT NULL,
    [CurCode]              CHAR (3)      CONSTRAINT [DF_ED810Header_CurCode] DEFAULT (' ') NOT NULL,
    [CuryDiscTot]          FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryDiscTot] DEFAULT ((0)) NOT NULL,
    [CuryEffDate]          SMALLDATETIME CONSTRAINT [DF_ED810Header_CuryEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryFreightTot]       FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryFreightTot] DEFAULT ((0)) NOT NULL,
    [CuryID]               CHAR (4)      CONSTRAINT [DF_ED810Header_CuryID] DEFAULT (' ') NOT NULL,
    [CuryInvcTot]          FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryInvcTot] DEFAULT ((0)) NOT NULL,
    [CuryMiscChargeTot]    FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryMiscChargeTot] DEFAULT ((0)) NOT NULL,
    [CuryMultDiv]          CHAR (1)      CONSTRAINT [DF_ED810Header_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryMultiDiv]         CHAR (1)      CONSTRAINT [DF_ED810Header_CuryMultiDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]             FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryRate] DEFAULT ((0)) NOT NULL,
    [CuryRateType]         CHAR (6)      CONSTRAINT [DF_ED810Header_CuryRateType] DEFAULT (' ') NOT NULL,
    [CuryTaxTot]           FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryTaxTot] DEFAULT ((0)) NOT NULL,
    [CuryTermsAmtSubjDisc] FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryTermsAmtSubjDisc] DEFAULT ((0)) NOT NULL,
    [CuryTermsDefAmtDue]   FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryTermsDefAmtDue] DEFAULT ((0)) NOT NULL,
    [CuryTermsDiscAmt]     FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryTermsDiscAmt] DEFAULT ((0)) NOT NULL,
    [CuryTermsTotDisc]     FLOAT (53)    CONSTRAINT [DF_ED810Header_CuryTermsTotDisc] DEFAULT ((0)) NOT NULL,
    [DiscTot]              FLOAT (53)    CONSTRAINT [DF_ED810Header_DiscTot] DEFAULT ((0)) NOT NULL,
    [EDIInvID]             CHAR (10)     CONSTRAINT [DF_ED810Header_EDIInvID] DEFAULT (' ') NOT NULL,
    [FOBDesc]              CHAR (80)     CONSTRAINT [DF_ED810Header_FOBDesc] DEFAULT (' ') NOT NULL,
    [FOBLocQual]           CHAR (2)      CONSTRAINT [DF_ED810Header_FOBLocQual] DEFAULT (' ') NOT NULL,
    [FreightTot]           FLOAT (53)    CONSTRAINT [DF_ED810Header_FreightTot] DEFAULT ((0)) NOT NULL,
    [GSNbr]                INT           CONSTRAINT [DF_ED810Header_GSNbr] DEFAULT ((0)) NOT NULL,
    [GSRcvID]              CHAR (15)     CONSTRAINT [DF_ED810Header_GSRcvID] DEFAULT (' ') NOT NULL,
    [GSSenderID]           CHAR (15)     CONSTRAINT [DF_ED810Header_GSSenderID] DEFAULT (' ') NOT NULL,
    [HashTotal]            FLOAT (53)    CONSTRAINT [DF_ED810Header_HashTotal] DEFAULT ((0)) NOT NULL,
    [IntChgStandard]       CHAR (1)      CONSTRAINT [DF_ED810Header_IntChgStandard] DEFAULT (' ') NOT NULL,
    [IntChgTestFlag]       CHAR (1)      CONSTRAINT [DF_ED810Header_IntChgTestFlag] DEFAULT (' ') NOT NULL,
    [IntChgVersion]        CHAR (5)      CONSTRAINT [DF_ED810Header_IntChgVersion] DEFAULT (' ') NOT NULL,
    [IntVendNbr]           CHAR (30)     CONSTRAINT [DF_ED810Header_IntVendNbr] DEFAULT (' ') NOT NULL,
    [InvcDate]             SMALLDATETIME CONSTRAINT [DF_ED810Header_InvcDate] DEFAULT ('01/01/1900') NOT NULL,
    [InvcNbr]              CHAR (15)     CONSTRAINT [DF_ED810Header_InvcNbr] DEFAULT (' ') NOT NULL,
    [InvcTot]              FLOAT (53)    CONSTRAINT [DF_ED810Header_InvcTot] DEFAULT ((0)) NOT NULL,
    [IsaNbr]               INT           CONSTRAINT [DF_ED810Header_IsaNbr] DEFAULT ((0)) NOT NULL,
    [IsaRcvID]             CHAR (15)     CONSTRAINT [DF_ED810Header_IsaRcvID] DEFAULT (' ') NOT NULL,
    [IsaRcvQual]           CHAR (2)      CONSTRAINT [DF_ED810Header_IsaRcvQual] DEFAULT (' ') NOT NULL,
    [ISndID]               CHAR (15)     CONSTRAINT [DF_ED810Header_ISndID] DEFAULT (' ') NOT NULL,
    [ISndQual]             CHAR (2)      CONSTRAINT [DF_ED810Header_ISndQual] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]        SMALLDATETIME CONSTRAINT [DF_ED810Header_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]            CHAR (8)      CONSTRAINT [DF_ED810Header_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]            CHAR (10)     CONSTRAINT [DF_ED810Header_Lupd_User] DEFAULT (' ') NOT NULL,
    [MiscChargeTot]        FLOAT (53)    CONSTRAINT [DF_ED810Header_MiscChargeTot] DEFAULT ((0)) NOT NULL,
    [NbrContainer]         SMALLINT      CONSTRAINT [DF_ED810Header_NbrContainer] DEFAULT ((0)) NOT NULL,
    [NbrLines]             SMALLINT      CONSTRAINT [DF_ED810Header_NbrLines] DEFAULT ((0)) NOT NULL,
    [NoteID]               INT           CONSTRAINT [DF_ED810Header_NoteID] DEFAULT ((0)) NOT NULL,
    [OrderVolume]          INT           CONSTRAINT [DF_ED810Header_OrderVolume] DEFAULT ((0)) NOT NULL,
    [OrderVolumeUOM]       CHAR (6)      CONSTRAINT [DF_ED810Header_OrderVolumeUOM] DEFAULT (' ') NOT NULL,
    [OrderWeight]          INT           CONSTRAINT [DF_ED810Header_OrderWeight] DEFAULT ((0)) NOT NULL,
    [OrderWeightUOM]       CHAR (6)      CONSTRAINT [DF_ED810Header_OrderWeightUOM] DEFAULT (' ') NOT NULL,
    [PODate]               SMALLDATETIME CONSTRAINT [DF_ED810Header_PODate] DEFAULT ('01/01/1900') NOT NULL,
    [PONbr]                CHAR (10)     CONSTRAINT [DF_ED810Header_PONbr] DEFAULT (' ') NOT NULL,
    [PRO]                  CHAR (20)     CONSTRAINT [DF_ED810Header_PRO] DEFAULT (' ') NOT NULL,
    [ProjectDescr]         CHAR (80)     CONSTRAINT [DF_ED810Header_ProjectDescr] DEFAULT (' ') NOT NULL,
    [ProjectID]            CHAR (16)     CONSTRAINT [DF_ED810Header_ProjectID] DEFAULT (' ') NOT NULL,
    [ReleaseNbr]           CHAR (30)     CONSTRAINT [DF_ED810Header_ReleaseNbr] DEFAULT (' ') NOT NULL,
    [Routing]              CHAR (50)     CONSTRAINT [DF_ED810Header_Routing] DEFAULT (' ') NOT NULL,
    [S4Future01]           CHAR (30)     CONSTRAINT [DF_ED810Header_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     CONSTRAINT [DF_ED810Header_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    CONSTRAINT [DF_ED810Header_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    CONSTRAINT [DF_ED810Header_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    CONSTRAINT [DF_ED810Header_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    CONSTRAINT [DF_ED810Header_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME CONSTRAINT [DF_ED810Header_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME CONSTRAINT [DF_ED810Header_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           CONSTRAINT [DF_ED810Header_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           CONSTRAINT [DF_ED810Header_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     CONSTRAINT [DF_ED810Header_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     CONSTRAINT [DF_ED810Header_S4Future12] DEFAULT (' ') NOT NULL,
    [SCAC]                 CHAR (5)      CONSTRAINT [DF_ED810Header_SCAC] DEFAULT (' ') NOT NULL,
    [ShipMethPay]          CHAR (2)      CONSTRAINT [DF_ED810Header_ShipMethPay] DEFAULT (' ') NOT NULL,
    [Standard]             CHAR (2)      CONSTRAINT [DF_ED810Header_Standard] DEFAULT (' ') NOT NULL,
    [STNbr]                INT           CONSTRAINT [DF_ED810Header_STNbr] DEFAULT ((0)) NOT NULL,
    [TaxTot]               FLOAT (53)    CONSTRAINT [DF_ED810Header_TaxTot] DEFAULT ((0)) NOT NULL,
    [TermsAmtSubjDisc]     FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsAmtSubjDisc] DEFAULT ((0)) NOT NULL,
    [TermsBasisCode]       CHAR (2)      CONSTRAINT [DF_ED810Header_TermsBasisCode] DEFAULT (' ') NOT NULL,
    [TermsDayMonth]        SMALLINT      CONSTRAINT [DF_ED810Header_TermsDayMonth] DEFAULT ((0)) NOT NULL,
    [TermsDefAmtDue]       FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsDefAmtDue] DEFAULT ((0)) NOT NULL,
    [TermsDefDueDate]      SMALLDATETIME CONSTRAINT [DF_ED810Header_TermsDefDueDate] DEFAULT ('01/01/1900') NOT NULL,
    [TermsDesc]            CHAR (80)     CONSTRAINT [DF_ED810Header_TermsDesc] DEFAULT (' ') NOT NULL,
    [TermsDiscAmt]         FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsDiscAmt] DEFAULT ((0)) NOT NULL,
    [TermsDiscDaysDue]     SMALLINT      CONSTRAINT [DF_ED810Header_TermsDiscDaysDue] DEFAULT ((0)) NOT NULL,
    [TermsDiscDueDate]     SMALLDATETIME CONSTRAINT [DF_ED810Header_TermsDiscDueDate] DEFAULT ('01/01/1900') NOT NULL,
    [TermsDiscNetDueDate]  SMALLDATETIME CONSTRAINT [DF_ED810Header_TermsDiscNetDueDate] DEFAULT ('01/01/1900') NOT NULL,
    [TermsDiscPerc]        FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsDiscPerc] DEFAULT ((0)) NOT NULL,
    [TermsID]              CHAR (2)      CONSTRAINT [DF_ED810Header_TermsID] DEFAULT (' ') NOT NULL,
    [TermsNetDays]         SMALLINT      CONSTRAINT [DF_ED810Header_TermsNetDays] DEFAULT ((0)) NOT NULL,
    [TermsPayMethCode]     CHAR (2)      CONSTRAINT [DF_ED810Header_TermsPayMethCode] DEFAULT (' ') NOT NULL,
    [TermsPercPay]         FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsPercPay] DEFAULT ((0)) NOT NULL,
    [TermsTotDisc]         FLOAT (53)    CONSTRAINT [DF_ED810Header_TermsTotDisc] DEFAULT ((0)) NOT NULL,
    [TermsTypeCode]        CHAR (3)      CONSTRAINT [DF_ED810Header_TermsTypeCode] DEFAULT (' ') NOT NULL,
    [TranMethCode]         CHAR (3)      CONSTRAINT [DF_ED810Header_TranMethCode] DEFAULT (' ') NOT NULL,
    [TransmitDate]         SMALLDATETIME CONSTRAINT [DF_ED810Header_TransmitDate] DEFAULT ('01/01/1900') NOT NULL,
    [TransmitTime]         CHAR (8)      CONSTRAINT [DF_ED810Header_TransmitTime] DEFAULT (' ') NOT NULL,
    [UpdateStatus]         CHAR (2)      CONSTRAINT [DF_ED810Header_UpdateStatus] DEFAULT (' ') NOT NULL,
    [User1]                CHAR (30)     CONSTRAINT [DF_ED810Header_User1] DEFAULT (' ') NOT NULL,
    [User10]               SMALLDATETIME CONSTRAINT [DF_ED810Header_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]                CHAR (30)     CONSTRAINT [DF_ED810Header_User2] DEFAULT (' ') NOT NULL,
    [User3]                CHAR (30)     CONSTRAINT [DF_ED810Header_User3] DEFAULT (' ') NOT NULL,
    [User4]                CHAR (30)     CONSTRAINT [DF_ED810Header_User4] DEFAULT (' ') NOT NULL,
    [User5]                FLOAT (53)    CONSTRAINT [DF_ED810Header_User5] DEFAULT ((0)) NOT NULL,
    [User6]                FLOAT (53)    CONSTRAINT [DF_ED810Header_User6] DEFAULT ((0)) NOT NULL,
    [User7]                CHAR (10)     CONSTRAINT [DF_ED810Header_User7] DEFAULT (' ') NOT NULL,
    [User8]                CHAR (10)     CONSTRAINT [DF_ED810Header_User8] DEFAULT (' ') NOT NULL,
    [User9]                SMALLDATETIME CONSTRAINT [DF_ED810Header_User9] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]               CHAR (15)     CONSTRAINT [DF_ED810Header_VendID] DEFAULT (' ') NOT NULL,
    [Version]              CHAR (12)     CONSTRAINT [DF_ED810Header_Version] DEFAULT (' ') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [ED810Header0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [EDIInvID] ASC) WITH (FILLFACTOR = 90)
);

