CREATE TABLE [dbo].[cftSiteDir] (
    [CF01]             CHAR (30)     NOT NULL,
    [CF02]             CHAR (30)     NOT NULL,
    [CF03]             CHAR (10)     NOT NULL,
    [CF04]             CHAR (10)     NOT NULL,
    [CF05]             SMALLDATETIME NOT NULL,
    [CF06]             SMALLDATETIME NOT NULL,
    [CF07]             SMALLINT      NOT NULL,
    [CF08]             SMALLINT      NOT NULL,
    [CF09]             INT           NOT NULL,
    [CF10]             INT           NOT NULL,
    [CF11]             FLOAT (53)    NOT NULL,
    [CF12]             FLOAT (53)    NOT NULL,
    [ContactID]        CHAR (6)      NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [Dir1]             CHAR (100)    NOT NULL,
    [Dir2]             CHAR (100)    NULL,
    [Dir3]             CHAR (100)    NULL,
    [Dir4]             CHAR (100)    NULL,
    [Lupd_DateTime]    SMALLDATETIME NOT NULL,
    [Lupd_Prog]        CHAR (8)      NOT NULL,
    [Lupd_User]        CHAR (10)     NOT NULL,
    [RoadRestrictions] CHAR (1)      NOT NULL,
    [ShowInWEM]        CHAR (1)      CONSTRAINT [DF_cftSiteDir_ShowInWEM] DEFAULT (0) NOT NULL,
    [tstamp]           ROWVERSION    NULL,
    CONSTRAINT [cftSiteDir0] PRIMARY KEY CLUSTERED ([ContactID] ASC, [RoadRestrictions] ASC) WITH (FILLFACTOR = 90)
);

