CREATE TABLE [dbo].[POBudHist] (
    [Acct]            CHAR (10)     CONSTRAINT [DF_POBudHist_Acct] DEFAULT (' ') NOT NULL,
    [AnnBdgt]         FLOAT (53)    CONSTRAINT [DF_POBudHist_AnnBdgt] DEFAULT ((0)) NOT NULL,
    [AnnMemo1]        FLOAT (53)    CONSTRAINT [DF_POBudHist_AnnMemo1] DEFAULT ((0)) NOT NULL,
    [BalanceType]     CHAR (1)      CONSTRAINT [DF_POBudHist_BalanceType] DEFAULT (' ') NOT NULL,
    [BdgtRvsnDate]    SMALLDATETIME CONSTRAINT [DF_POBudHist_BdgtRvsnDate] DEFAULT ('01/01/1900') NOT NULL,
    [BegBal]          FLOAT (53)    CONSTRAINT [DF_POBudHist_BegBal] DEFAULT ((0)) NOT NULL,
    [CpnyID]          CHAR (10)     CONSTRAINT [DF_POBudHist_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME CONSTRAINT [DF_POBudHist_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      CONSTRAINT [DF_POBudHist_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     CONSTRAINT [DF_POBudHist_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryId]          CHAR (4)      CONSTRAINT [DF_POBudHist_CuryId] DEFAULT (' ') NOT NULL,
    [DistType]        CHAR (8)      CONSTRAINT [DF_POBudHist_DistType] DEFAULT (' ') NOT NULL,
    [FiscYr]          CHAR (4)      CONSTRAINT [DF_POBudHist_FiscYr] DEFAULT (' ') NOT NULL,
    [LastClosePerNbr] CHAR (6)      CONSTRAINT [DF_POBudHist_LastClosePerNbr] DEFAULT (' ') NOT NULL,
    [LedgerID]        CHAR (10)     CONSTRAINT [DF_POBudHist_LedgerID] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME CONSTRAINT [DF_POBudHist_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]       CHAR (8)      CONSTRAINT [DF_POBudHist_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]       CHAR (10)     CONSTRAINT [DF_POBudHist_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]          INT           CONSTRAINT [DF_POBudHist_NoteID] DEFAULT ((0)) NOT NULL,
    [PtdAlloc00]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc00] DEFAULT ((0)) NOT NULL,
    [PtdAlloc01]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc01] DEFAULT ((0)) NOT NULL,
    [PtdAlloc02]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc02] DEFAULT ((0)) NOT NULL,
    [PtdAlloc03]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc03] DEFAULT ((0)) NOT NULL,
    [PtdAlloc04]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc04] DEFAULT ((0)) NOT NULL,
    [PtdAlloc05]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc05] DEFAULT ((0)) NOT NULL,
    [PtdAlloc06]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc06] DEFAULT ((0)) NOT NULL,
    [PtdAlloc07]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc07] DEFAULT ((0)) NOT NULL,
    [PtdAlloc08]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc08] DEFAULT ((0)) NOT NULL,
    [PtdAlloc09]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc09] DEFAULT ((0)) NOT NULL,
    [PtdAlloc10]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc10] DEFAULT ((0)) NOT NULL,
    [PtdAlloc11]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc11] DEFAULT ((0)) NOT NULL,
    [PtdAlloc12]      FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdAlloc12] DEFAULT ((0)) NOT NULL,
    [PtdBal00]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal00] DEFAULT ((0)) NOT NULL,
    [PtdBal01]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal01] DEFAULT ((0)) NOT NULL,
    [PtdBal02]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal02] DEFAULT ((0)) NOT NULL,
    [PtdBal03]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal03] DEFAULT ((0)) NOT NULL,
    [PtdBal04]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal04] DEFAULT ((0)) NOT NULL,
    [PtdBal05]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal05] DEFAULT ((0)) NOT NULL,
    [PtdBal06]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal06] DEFAULT ((0)) NOT NULL,
    [PtdBal07]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal07] DEFAULT ((0)) NOT NULL,
    [PtdBal08]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal08] DEFAULT ((0)) NOT NULL,
    [PtdBal09]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal09] DEFAULT ((0)) NOT NULL,
    [PtdBal10]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal10] DEFAULT ((0)) NOT NULL,
    [PtdBal11]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal11] DEFAULT ((0)) NOT NULL,
    [PtdBal12]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdBal12] DEFAULT ((0)) NOT NULL,
    [PtdCon00]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon00] DEFAULT ((0)) NOT NULL,
    [PtdCon01]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon01] DEFAULT ((0)) NOT NULL,
    [PtdCon02]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon02] DEFAULT ((0)) NOT NULL,
    [PtdCon03]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon03] DEFAULT ((0)) NOT NULL,
    [PtdCon04]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon04] DEFAULT ((0)) NOT NULL,
    [PtdCon05]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon05] DEFAULT ((0)) NOT NULL,
    [PtdCon06]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon06] DEFAULT ((0)) NOT NULL,
    [PtdCon07]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon07] DEFAULT ((0)) NOT NULL,
    [PtdCon08]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon08] DEFAULT ((0)) NOT NULL,
    [PtdCon09]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon09] DEFAULT ((0)) NOT NULL,
    [PtdCon10]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon10] DEFAULT ((0)) NOT NULL,
    [PtdCon11]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon11] DEFAULT ((0)) NOT NULL,
    [PtdCon12]        FLOAT (53)    CONSTRAINT [DF_POBudHist_PtdCon12] DEFAULT ((0)) NOT NULL,
    [S4Future01]      CHAR (30)     CONSTRAINT [DF_POBudHist_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]      CHAR (30)     CONSTRAINT [DF_POBudHist_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]      FLOAT (53)    CONSTRAINT [DF_POBudHist_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]      FLOAT (53)    CONSTRAINT [DF_POBudHist_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]      FLOAT (53)    CONSTRAINT [DF_POBudHist_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]      FLOAT (53)    CONSTRAINT [DF_POBudHist_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]      SMALLDATETIME CONSTRAINT [DF_POBudHist_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]      SMALLDATETIME CONSTRAINT [DF_POBudHist_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]      INT           CONSTRAINT [DF_POBudHist_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]      INT           CONSTRAINT [DF_POBudHist_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]      CHAR (10)     CONSTRAINT [DF_POBudHist_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]      CHAR (10)     CONSTRAINT [DF_POBudHist_S4Future12] DEFAULT (' ') NOT NULL,
    [SpreadSheetType] CHAR (1)      CONSTRAINT [DF_POBudHist_SpreadSheetType] DEFAULT (' ') NOT NULL,
    [Sub]             CHAR (24)     CONSTRAINT [DF_POBudHist_Sub] DEFAULT (' ') NOT NULL,
    [User1]           CHAR (30)     CONSTRAINT [DF_POBudHist_User1] DEFAULT (' ') NOT NULL,
    [User2]           CHAR (30)     CONSTRAINT [DF_POBudHist_User2] DEFAULT (' ') NOT NULL,
    [User3]           FLOAT (53)    CONSTRAINT [DF_POBudHist_User3] DEFAULT ((0)) NOT NULL,
    [User4]           FLOAT (53)    CONSTRAINT [DF_POBudHist_User4] DEFAULT ((0)) NOT NULL,
    [User5]           CHAR (10)     CONSTRAINT [DF_POBudHist_User5] DEFAULT (' ') NOT NULL,
    [User6]           CHAR (10)     CONSTRAINT [DF_POBudHist_User6] DEFAULT (' ') NOT NULL,
    [User7]           SMALLDATETIME CONSTRAINT [DF_POBudHist_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]           SMALLDATETIME CONSTRAINT [DF_POBudHist_User8] DEFAULT ('01/01/1900') NOT NULL,
    [YtdBal00]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal00] DEFAULT ((0)) NOT NULL,
    [YtdBal01]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal01] DEFAULT ((0)) NOT NULL,
    [YtdBal02]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal02] DEFAULT ((0)) NOT NULL,
    [YtdBal03]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal03] DEFAULT ((0)) NOT NULL,
    [YtdBal04]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal04] DEFAULT ((0)) NOT NULL,
    [YtdBal05]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal05] DEFAULT ((0)) NOT NULL,
    [YtdBal06]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal06] DEFAULT ((0)) NOT NULL,
    [YtdBal07]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal07] DEFAULT ((0)) NOT NULL,
    [YtdBal08]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal08] DEFAULT ((0)) NOT NULL,
    [YtdBal09]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal09] DEFAULT ((0)) NOT NULL,
    [YtdBal10]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal10] DEFAULT ((0)) NOT NULL,
    [YtdBal11]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal11] DEFAULT ((0)) NOT NULL,
    [YtdBal12]        FLOAT (53)    CONSTRAINT [DF_POBudHist_YtdBal12] DEFAULT ((0)) NOT NULL,
    [YTDEstimated]    FLOAT (53)    CONSTRAINT [DF_POBudHist_YTDEstimated] DEFAULT ((0)) NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [POBudHist0] PRIMARY KEY CLUSTERED ([Acct] ASC, [Sub] ASC, [CuryId] ASC, [FiscYr] ASC) WITH (FILLFACTOR = 90)
);

