CREATE TABLE [dbo].[EDWrkPOToSO] (
    [AccessNbr] SMALLINT   CONSTRAINT [DF_EDWrkPOToSO_AccessNbr] DEFAULT ((0)) NOT NULL,
    [CpnyID]    CHAR (10)  CONSTRAINT [DF_EDWrkPOToSO_CpnyID] DEFAULT (' ') NOT NULL,
    [EDIPOID]   CHAR (10)  CONSTRAINT [DF_EDWrkPOToSO_EDIPOID] DEFAULT (' ') NOT NULL,
    [InvtID]    CHAR (30)  CONSTRAINT [DF_EDWrkPOToSO_InvtID] DEFAULT (' ') NOT NULL,
    [POQty]     FLOAT (53) CONSTRAINT [DF_EDWrkPOToSO_POQty] DEFAULT ((0)) NOT NULL,
    [POUOM]     CHAR (6)   CONSTRAINT [DF_EDWrkPOToSO_POUOM] DEFAULT (' ') NOT NULL,
    [SOQty]     FLOAT (53) CONSTRAINT [DF_EDWrkPOToSO_SOQty] DEFAULT ((0)) NOT NULL,
    [tstamp]    ROWVERSION NOT NULL,
    CONSTRAINT [EDWrkPOToSO0] PRIMARY KEY CLUSTERED ([AccessNbr] ASC, [CpnyID] ASC, [EDIPOID] ASC, [InvtID] ASC, [POUOM] ASC) WITH (FILLFACTOR = 90)
);

