CREATE TABLE [dbo].[WOTask] (
    [CntMaterial]   SMALLINT      CONSTRAINT [DF_WOTask_CntMaterial] DEFAULT ((0)) NOT NULL,
    [CntRouting]    SMALLINT      CONSTRAINT [DF_WOTask_CntRouting] DEFAULT ((0)) NOT NULL,
    [CpnyID]        CHAR (10)     CONSTRAINT [DF_WOTask_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_WOTask_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_WOTask_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_Time]     SMALLDATETIME CONSTRAINT [DF_WOTask_Crtd_Time] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_WOTask_Crtd_User] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_WOTask_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_WOTask_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUPd_Time]     SMALLDATETIME CONSTRAINT [DF_WOTask_LUPd_Time] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_WOTask_LUpd_User] DEFAULT (' ') NOT NULL,
    [MRLineCntr]    INT           CONSTRAINT [DF_WOTask_MRLineCntr] DEFAULT ((0)) NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_WOTask_NoteID] DEFAULT ((0)) NOT NULL,
    [ProcStage]     CHAR (1)      CONSTRAINT [DF_WOTask_ProcStage] DEFAULT (' ') NOT NULL,
    [RLineCntr]     INT           CONSTRAINT [DF_WOTask_RLineCntr] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_WOTask_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_WOTask_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_WOTask_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_WOTask_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_WOTask_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_WOTask_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_WOTask_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_WOTask_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_WOTask_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_WOTask_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_WOTask_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_WOTask_S4Future12] DEFAULT (' ') NOT NULL,
    [Task]          CHAR (32)     CONSTRAINT [DF_WOTask_Task] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_WOTask_User1] DEFAULT (' ') NOT NULL,
    [User10]        CHAR (30)     CONSTRAINT [DF_WOTask_User10] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_WOTask_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_WOTask_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_WOTask_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_WOTask_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_WOTask_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_WOTask_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_WOTask_User8] DEFAULT ('01/01/1900') NOT NULL,
    [User9]         CHAR (30)     CONSTRAINT [DF_WOTask_User9] DEFAULT (' ') NOT NULL,
    [WONbr]         CHAR (16)     CONSTRAINT [DF_WOTask_WONbr] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [WOTask0] PRIMARY KEY CLUSTERED ([WONbr] ASC, [Task] ASC) WITH (FILLFACTOR = 90)
);

