CREATE TABLE [dbo].[PJBHSROL] (
    [acct]                 CHAR (16)     NOT NULL,
    [crtd_datetime]        SMALLDATETIME NOT NULL,
    [crtd_prog]            CHAR (8)      NOT NULL,
    [crtd_user]            CHAR (10)     NOT NULL,
    [data1]                CHAR (16)     NOT NULL,
    [data2]                FLOAT (53)    NOT NULL,
    [data3]                FLOAT (53)    NOT NULL,
    [data4]                FLOAT (53)    NOT NULL,
    [data5]                FLOAT (53)    NOT NULL,
    [eac_amount]           FLOAT (53)    NOT NULL,
    [eac_units]            FLOAT (53)    NOT NULL,
    [fac_amount]           FLOAT (53)    NOT NULL,
    [fac_units]            FLOAT (53)    NOT NULL,
    [fiscalno]             CHAR (6)      NOT NULL,
    [lupd_datetime]        SMALLDATETIME NOT NULL,
    [lupd_prog]            CHAR (8)      NOT NULL,
    [lupd_user]            CHAR (10)     NOT NULL,
    [ProjCury_eac_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_fac_amount]  FLOAT (53)    NOT NULL,
    [ProjCury_tot_bud_amt] FLOAT (53)    NOT NULL,
    [ProjCuryEffDate]      SMALLDATETIME NOT NULL,
    [ProjCuryId]           CHAR (4)      NOT NULL,
    [ProjCuryMultiDiv]     CHAR (1)      NOT NULL,
    [ProjCuryRate]         FLOAT (53)    NOT NULL,
    [ProjCuryRateType]     CHAR (6)      NOT NULL,
    [project]              CHAR (16)     NOT NULL,
    [total_budget_amount]  FLOAT (53)    NOT NULL,
    [total_budget_units]   FLOAT (53)    NOT NULL,
    [user1]                CHAR (30)     NOT NULL,
    [user2]                CHAR (30)     NOT NULL,
    [user3]                FLOAT (53)    NOT NULL,
    [user4]                FLOAT (53)    NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [PJBHSROL0] PRIMARY KEY CLUSTERED ([project] ASC, [acct] ASC, [fiscalno] ASC)
);

