CREATE TABLE [dbo].[PJWAGEPR] (
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [group_code]     CHAR (2)      NOT NULL,
    [labor_class_cd] CHAR (4)      NOT NULL,
    [labor_rate]     FLOAT (53)    NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [prev_wage_cd]   CHAR (4)      NOT NULL,
    [pw_id01]        CHAR (30)     NOT NULL,
    [pw_id02]        CHAR (30)     NOT NULL,
    [pw_id03]        CHAR (16)     NOT NULL,
    [pw_id04]        CHAR (16)     NOT NULL,
    [pw_id05]        CHAR (4)      NOT NULL,
    [pw_id06]        FLOAT (53)    NOT NULL,
    [pw_id07]        FLOAT (53)    NOT NULL,
    [pw_id08]        SMALLDATETIME NOT NULL,
    [pw_id09]        SMALLDATETIME NOT NULL,
    [pw_id10]        INT           NOT NULL,
    [pw_id11]        CHAR (30)     NOT NULL,
    [pw_id12]        CHAR (30)     NOT NULL,
    [pw_id13]        CHAR (16)     NOT NULL,
    [pw_id14]        CHAR (16)     NOT NULL,
    [pw_id15]        CHAR (4)      NOT NULL,
    [pw_id16]        FLOAT (53)    NOT NULL,
    [pw_id17]        FLOAT (53)    NOT NULL,
    [pw_id18]        SMALLDATETIME NOT NULL,
    [pw_id19]        SMALLDATETIME NOT NULL,
    [pw_id20]        INT           NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjwagepr0] PRIMARY KEY CLUSTERED ([prev_wage_cd] ASC, [labor_class_cd] ASC, [group_code] ASC) WITH (FILLFACTOR = 90)
);

