CREATE TABLE [dbo].[PJBILLSB] (
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [customer]      CHAR (15)     NOT NULL,
    [cust_percent]  FLOAT (53)    NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [project]       CHAR (16)     NOT NULL,
    [sb_comment]    CHAR (30)     NOT NULL,
    [sb_id01]       CHAR (30)     NOT NULL,
    [sb_id02]       CHAR (30)     NOT NULL,
    [sb_id03]       CHAR (20)     NOT NULL,
    [sb_id04]       CHAR (20)     NOT NULL,
    [sb_id05]       CHAR (10)     NOT NULL,
    [sb_id06]       CHAR (10)     NOT NULL,
    [sb_id07]       CHAR (4)      NOT NULL,
    [sb_id08]       FLOAT (53)    NOT NULL,
    [sb_id09]       SMALLDATETIME NOT NULL,
    [sb_id10]       INT           NOT NULL,
    [user1]         CHAR (30)     NOT NULL,
    [user2]         CHAR (30)     NOT NULL,
    [user3]         FLOAT (53)    NOT NULL,
    [user4]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [pjbillsb0] PRIMARY KEY CLUSTERED ([project] ASC, [customer] ASC) WITH (FILLFACTOR = 90)
);

