CREATE TABLE [dbo].[Currncy] (
    [BitmapId]      CHAR (3)      NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CuryCapt]      CHAR (15)     NOT NULL,
    [CuryId]        CHAR (4)      NOT NULL,
    [CurySym]       CHAR (4)      NOT NULL,
    [DecPl]         SMALLINT      NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NoteId]        INT           NOT NULL,
    [RealGainAcct]  CHAR (10)     NOT NULL,
    [RealGainSub]   CHAR (24)     NOT NULL,
    [RealLossAcct]  CHAR (10)     NOT NULL,
    [RealLossSub]   CHAR (24)     NOT NULL,
    [RvalGainAcct]  CHAR (10)     NOT NULL,
    [RvalGainSub]   CHAR (24)     NOT NULL,
    [RvalLossAcct]  CHAR (10)     NOT NULL,
    [RvalLossSub]   CHAR (24)     NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [Status]        CHAR (1)      NOT NULL,
    [TrslGainAcct]  CHAR (10)     NOT NULL,
    [TrslGainSub]   CHAR (24)     NOT NULL,
    [TrslLossAcct]  CHAR (10)     NOT NULL,
    [TrslLossSub]   CHAR (24)     NOT NULL,
    [UnrlGainAcct]  CHAR (10)     NOT NULL,
    [UnrlGainSub]   CHAR (24)     NOT NULL,
    [UnrlLossAcct]  CHAR (10)     NOT NULL,
    [UnrlLossSub]   CHAR (24)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [Currncy0] PRIMARY KEY CLUSTERED ([CuryId] ASC) WITH (FILLFACTOR = 90)
);

