CREATE TABLE [dbo].[smWrkSvDetail] (
    [Acct]                CHAR (10)     NOT NULL,
    [ARBatNbr]            CHAR (10)     NOT NULL,
    [ARRefNbr]            CHAR (10)     NOT NULL,
    [Billable]            FLOAT (53)    NOT NULL,
    [BillFlag]            SMALLINT      NOT NULL,
    [BillingType]         CHAR (1)      NOT NULL,
    [BillWarranty]        SMALLINT      NOT NULL,
    [Certified]           CHAR (1)      NOT NULL,
    [ClassID]             CHAR (6)      NOT NULL,
    [COGSAcct]            CHAR (10)     NOT NULL,
    [COGSSub]             CHAR (24)     NOT NULL,
    [Cost]                FLOAT (53)    NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [CreateReceipt]       SMALLINT      NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [Description]         CHAR (60)     NOT NULL,
    [DetailType]          CHAR (1)      NOT NULL,
    [EarningType]         CHAR (10)     NOT NULL,
    [EarnMult]            FLOAT (53)    NOT NULL,
    [EmpID]               CHAR (10)     NOT NULL,
    [EmpPRID]             CHAR (10)     NOT NULL,
    [EquipID]             CHAR (10)     NOT NULL,
    [ExtPrice]            FLOAT (53)    NOT NULL,
    [FlatRateID]          CHAR (10)     NOT NULL,
    [FlatRateLineNbr]     SMALLINT      NOT NULL,
    [INBatNbr]            CHAR (10)     NOT NULL,
    [INLineID]            SMALLINT      NOT NULL,
    [INTranFlag]          SMALLINT      NOT NULL,
    [InvoiceInProgress]   SMALLINT      NOT NULL,
    [InvoiceLineID]       SMALLINT      NOT NULL,
    [InvtId]              CHAR (30)     NOT NULL,
    [InvtStdCost]         FLOAT (53)    NOT NULL,
    [LaborClass]          CHAR (4)      NOT NULL,
    [LaborBurden]         FLOAT (53)    NOT NULL,
    [LineNbr]             SMALLINT      NOT NULL,
    [LineTypes]           CHAR (1)      NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MarkupId]            CHAR (10)     NOT NULL,
    [NoteID]              INT           NOT NULL,
    [OrdLineID]           SMALLINT      NOT NULL,
    [OrdNbr]              CHAR (10)     NOT NULL,
    [PJBatNbr]            CHAR (10)     NOT NULL,
    [PJDocNbr]            CHAR (10)     NOT NULL,
    [POCost]              FLOAT (53)    NOT NULL,
    [PODate]              SMALLDATETIME NOT NULL,
    [POFlag]              SMALLINT      NOT NULL,
    [PONumber]            CHAR (20)     NOT NULL,
    [POOrderQty]          FLOAT (53)    NOT NULL,
    [PORcptQty]           FLOAT (53)    NOT NULL,
    [PRBatchNbr]          CHAR (10)     NOT NULL,
    [PRCreated]           SMALLINT      NOT NULL,
    [PRDocNBr]            CHAR (10)     NOT NULL,
    [PrevailingWageCode]  CHAR (4)      NOT NULL,
    [PrevailingWageGroup] CHAR (2)      NOT NULL,
    [PRLineID]            SMALLINT      NOT NULL,
    [Profit]              FLOAT (53)    NOT NULL,
    [ProfitPercent]       FLOAT (53)    NOT NULL,
    [Quantity]            FLOAT (53)    NOT NULL,
    [RecptFlag]           SMALLINT      NOT NULL,
    [RecptNbr]            CHAR (10)     NOT NULL,
    [RI_ID]               SMALLINT      NOT NULL,
    [ServiceCallID]       CHAR (10)     NOT NULL,
    [ServiceContract]     CHAR (10)     NOT NULL,
    [ShiftCode]           CHAR (7)      NOT NULL,
    [SiteID]              CHAR (10)     NOT NULL,
    [StdCost]             FLOAT (53)    NOT NULL,
    [Sub]                 CHAR (24)     NOT NULL,
    [Task]                CHAR (32)     NOT NULL,
    [TaxAmt00]            FLOAT (53)    NOT NULL,
    [TaxAmt01]            FLOAT (53)    NOT NULL,
    [TaxAmt02]            FLOAT (53)    NOT NULL,
    [TaxAmt03]            FLOAT (53)    NOT NULL,
    [TaxCalced]           CHAR (1)      NOT NULL,
    [TaxCat]              CHAR (10)     NOT NULL,
    [TaxExempt]           CHAR (1)      NOT NULL,
    [TaxID00]             CHAR (10)     NOT NULL,
    [TaxID01]             CHAR (10)     NOT NULL,
    [TaxID02]             CHAR (10)     NOT NULL,
    [TaxID03]             CHAR (10)     NOT NULL,
    [TaxIDDflt]           CHAR (10)     NOT NULL,
    [TimeShtNbr]          CHAR (10)     NOT NULL,
    [TM_ID01]             CHAR (30)     NOT NULL,
    [TM_ID02]             CHAR (30)     NOT NULL,
    [TM_ID03]             CHAR (20)     NOT NULL,
    [TM_ID04]             CHAR (20)     NOT NULL,
    [TM_ID05]             CHAR (10)     NOT NULL,
    [TM_ID06]             CHAR (10)     NOT NULL,
    [TM_ID07]             CHAR (4)      NOT NULL,
    [TM_ID08]             FLOAT (53)    NOT NULL,
    [TM_ID09]             SMALLDATETIME NOT NULL,
    [TM_ID10]             SMALLINT      NOT NULL,
    [TM_ID11]             CHAR (30)     NOT NULL,
    [TM_ID12]             CHAR (30)     NOT NULL,
    [TM_ID13]             CHAR (20)     NOT NULL,
    [TM_ID14]             CHAR (20)     NOT NULL,
    [TM_ID15]             CHAR (10)     NOT NULL,
    [TM_ID16]             CHAR (10)     NOT NULL,
    [TM_ID17]             CHAR (4)      NOT NULL,
    [TM_ID18]             FLOAT (53)    NOT NULL,
    [TM_ID19]             SMALLDATETIME NOT NULL,
    [TM_ID20]             SMALLINT      NOT NULL,
    [TranAmt]             FLOAT (53)    NOT NULL,
    [TranDate]            SMALLDATETIME NOT NULL,
    [TxblAmt00]           FLOAT (53)    NOT NULL,
    [TxblAmt01]           FLOAT (53)    NOT NULL,
    [TxblAmt02]           FLOAT (53)    NOT NULL,
    [TxblAmt03]           FLOAT (53)    NOT NULL,
    [UnionCode]           CHAR (10)     NOT NULL,
    [UnitPrice]           FLOAT (53)    NOT NULL,
    [user1]               CHAR (30)     NOT NULL,
    [user2]               CHAR (30)     NOT NULL,
    [user3]               FLOAT (53)    NOT NULL,
    [user4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [UserID]              CHAR (47)     NOT NULL,
    [VendID]              CHAR (15)     NOT NULL,
    [WarrantyApproval]    CHAR (20)     NOT NULL,
    [WarrantyCustId]      CHAR (15)     NOT NULL,
    [WhseLoc]             CHAR (10)     NOT NULL,
    [WorkersComp]         CHAR (6)      NOT NULL,
    [WorkHr]              FLOAT (53)    NOT NULL,
    [WorkLoc]             CHAR (6)      NOT NULL,
    [WorkType]            CHAR (2)      NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smWrkSvDetail0] PRIMARY KEY CLUSTERED ([ServiceCallID] ASC, [BillingType] ASC, [FlatRateLineNbr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [smWrkSvDetail1]
    ON [dbo].[smWrkSvDetail]([UserID] ASC, [ServiceCallID] ASC, [VendID] ASC, [PODate] ASC) WITH (FILLFACTOR = 90);

