CREATE TABLE [dbo].[RQBudHist] (
    [Acct]          CHAR (10)     NOT NULL,
    [BegBal]        FLOAT (53)    NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [FiscYr]        CHAR (4)      NOT NULL,
    [LedgerId]      CHAR (10)     NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [PtdBal00]      FLOAT (53)    NOT NULL,
    [PtdBal01]      FLOAT (53)    NOT NULL,
    [PtdBal02]      FLOAT (53)    NOT NULL,
    [PtdBal03]      FLOAT (53)    NOT NULL,
    [PtdBal04]      FLOAT (53)    NOT NULL,
    [PtdBal05]      FLOAT (53)    NOT NULL,
    [PtdBal06]      FLOAT (53)    NOT NULL,
    [PtdBal07]      FLOAT (53)    NOT NULL,
    [PtdBal08]      FLOAT (53)    NOT NULL,
    [PtdBal09]      FLOAT (53)    NOT NULL,
    [PtdBal10]      FLOAT (53)    NOT NULL,
    [PtdBal11]      FLOAT (53)    NOT NULL,
    [PtdBal12]      FLOAT (53)    NOT NULL,
    [S4Future1]     CHAR (30)     NOT NULL,
    [S4Future2]     CHAR (30)     NOT NULL,
    [S4Future3]     FLOAT (53)    NOT NULL,
    [S4Future4]     FLOAT (53)    NOT NULL,
    [S4Future5]     FLOAT (53)    NOT NULL,
    [S4Future6]     FLOAT (53)    NOT NULL,
    [S4Future7]     SMALLDATETIME NOT NULL,
    [S4Future8]     SMALLDATETIME NOT NULL,
    [S4Future9]     INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [Sub]           CHAR (24)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [YtdBal00]      FLOAT (53)    NOT NULL,
    [YtdBal01]      FLOAT (53)    NOT NULL,
    [YtdBal02]      FLOAT (53)    NOT NULL,
    [YtdBal03]      FLOAT (53)    NOT NULL,
    [YtdBal04]      FLOAT (53)    NOT NULL,
    [YtdBal05]      FLOAT (53)    NOT NULL,
    [YtdBal06]      FLOAT (53)    NOT NULL,
    [YtdBal07]      FLOAT (53)    NOT NULL,
    [YtdBal08]      FLOAT (53)    NOT NULL,
    [YtdBal09]      FLOAT (53)    NOT NULL,
    [YtdBal10]      FLOAT (53)    NOT NULL,
    [YtdBal11]      FLOAT (53)    NOT NULL,
    [YtdBal12]      FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RQBudHist0]
    ON [dbo].[RQBudHist]([Acct] ASC, [Sub] ASC, [LedgerId] ASC, [FiscYr] ASC, [User5] ASC);

