CREATE TABLE [dbo].[CashAvgD] (
    [BankAcct]      CHAR (10)     NOT NULL,
    [BankSub]       CHAR (24)     NOT NULL,
    [CloseBal]      FLOAT (53)    NOT NULL,
    [CpnyID]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [CuryCloseBal]  FLOAT (53)    NOT NULL,
    [curytotchkamt] FLOAT (53)    NOT NULL,
    [curytotdepamt] FLOAT (53)    NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NbrChecks]     FLOAT (53)    NOT NULL,
    [NbrChkDays]    FLOAT (53)    NOT NULL,
    [NbrDepDays]    FLOAT (53)    NOT NULL,
    [NbrDeposits]   FLOAT (53)    NOT NULL,
    [NoteID]        INT           NOT NULL,
    [PerNbr]        CHAR (6)      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [TotChkAmt]     FLOAT (53)    NOT NULL,
    [TotDepAmt]     FLOAT (53)    NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [cashavgd0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [BankAcct] ASC, [BankSub] ASC, [PerNbr] ASC) WITH (FILLFACTOR = 90)
);

