CREATE TABLE [dbo].[Kit] (
    [BomType]       CHAR (1)      CONSTRAINT [DF_Kit_BomType] DEFAULT (' ') NOT NULL,
    [CDirLbrCst]    FLOAT (53)    CONSTRAINT [DF_Kit_CDirLbrCst] DEFAULT ((0)) NOT NULL,
    [CDirMatlCst]   FLOAT (53)    CONSTRAINT [DF_Kit_CDirMatlCst] DEFAULT ((0)) NOT NULL,
    [CDirOthCst]    FLOAT (53)    CONSTRAINT [DF_Kit_CDirOthCst] DEFAULT ((0)) NOT NULL,
    [CFOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_Kit_CFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CFOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_Kit_CFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [CFOvhMatlCst]  FLOAT (53)    CONSTRAINT [DF_Kit_CFOvhMatlCst] DEFAULT ((0)) NOT NULL,
    [CpnyID]        CHAR (10)     CONSTRAINT [DF_Kit_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_Kit_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_Kit_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_Kit_Crtd_User] DEFAULT (' ') NOT NULL,
    [CStdCst]       FLOAT (53)    CONSTRAINT [DF_Kit_CStdCst] DEFAULT ((0)) NOT NULL,
    [CVOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_Kit_CVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [CVOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_Kit_CVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [CVOvhMatlCst]  FLOAT (53)    CONSTRAINT [DF_Kit_CVOvhMatlCst] DEFAULT ((0)) NOT NULL,
    [Descr]         CHAR (60)     CONSTRAINT [DF_Kit_Descr] DEFAULT (' ') NOT NULL,
    [Drawing]       CHAR (15)     CONSTRAINT [DF_Kit_Drawing] DEFAULT (' ') NOT NULL,
    [EngrChgOrder]  CHAR (20)     CONSTRAINT [DF_Kit_EngrChgOrder] DEFAULT (' ') NOT NULL,
    [ExpKitDet]     SMALLINT      CONSTRAINT [DF_Kit_ExpKitDet] DEFAULT ((0)) NOT NULL,
    [ExplodeFlg]    CHAR (1)      CONSTRAINT [DF_Kit_ExplodeFlg] DEFAULT (' ') NOT NULL,
    [KitID]         CHAR (30)     CONSTRAINT [DF_Kit_KitID] DEFAULT (' ') NOT NULL,
    [KitType]       CHAR (1)      CONSTRAINT [DF_Kit_KitType] DEFAULT (' ') NOT NULL,
    [LevelNbr]      SMALLINT      CONSTRAINT [DF_Kit_LevelNbr] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_Kit_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_Kit_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_Kit_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_Kit_NoteID] DEFAULT ((0)) NOT NULL,
    [PC_Status]     CHAR (1)      CONSTRAINT [DF_Kit_PC_Status] DEFAULT (' ') NOT NULL,
    [PDirLbrCst]    FLOAT (53)    CONSTRAINT [DF_Kit_PDirLbrCst] DEFAULT ((0)) NOT NULL,
    [PDirMatlCst]   FLOAT (53)    CONSTRAINT [DF_Kit_PDirMatlCst] DEFAULT ((0)) NOT NULL,
    [PDirOthCst]    FLOAT (53)    CONSTRAINT [DF_Kit_PDirOthCst] DEFAULT ((0)) NOT NULL,
    [PFOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_Kit_PFOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PFOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_Kit_PFOvhMachCst] DEFAULT ((0)) NOT NULL,
    [PFOvhMatlCst]  FLOAT (53)    CONSTRAINT [DF_Kit_PFOvhMatlCst] DEFAULT ((0)) NOT NULL,
    [ProjectID]     CHAR (16)     CONSTRAINT [DF_Kit_ProjectID] DEFAULT (' ') NOT NULL,
    [PStdCst]       FLOAT (53)    CONSTRAINT [DF_Kit_PStdCst] DEFAULT ((0)) NOT NULL,
    [PVOvhLbrCst]   FLOAT (53)    CONSTRAINT [DF_Kit_PVOvhLbrCst] DEFAULT ((0)) NOT NULL,
    [PVOvhMachCst]  FLOAT (53)    CONSTRAINT [DF_Kit_PVOvhMachCst] DEFAULT ((0)) NOT NULL,
    [PVOvhMatlCst]  FLOAT (53)    CONSTRAINT [DF_Kit_PVOvhMatlCst] DEFAULT ((0)) NOT NULL,
    [Revision]      CHAR (10)     CONSTRAINT [DF_Kit_Revision] DEFAULT (' ') NOT NULL,
    [RtgExist]      CHAR (1)      CONSTRAINT [DF_Kit_RtgExist] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_Kit_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_Kit_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_Kit_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_Kit_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_Kit_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_Kit_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_Kit_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_Kit_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_Kit_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_Kit_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_Kit_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_Kit_S4Future12] DEFAULT (' ') NOT NULL,
    [SiteID]        CHAR (10)     CONSTRAINT [DF_Kit_SiteID] DEFAULT (' ') NOT NULL,
    [StartDate]     SMALLDATETIME CONSTRAINT [DF_Kit_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Status]        CHAR (1)      CONSTRAINT [DF_Kit_Status] DEFAULT (' ') NOT NULL,
    [StockUsage]    CHAR (1)      CONSTRAINT [DF_Kit_StockUsage] DEFAULT (' ') NOT NULL,
    [StopDate]      SMALLDATETIME CONSTRAINT [DF_Kit_StopDate] DEFAULT ('01/01/1900') NOT NULL,
    [SupersededBy]  CHAR (30)     CONSTRAINT [DF_Kit_SupersededBy] DEFAULT (' ') NOT NULL,
    [Supersedes]    CHAR (30)     CONSTRAINT [DF_Kit_Supersedes] DEFAULT (' ') NOT NULL,
    [TaskID]        CHAR (32)     CONSTRAINT [DF_Kit_TaskID] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_Kit_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_Kit_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_Kit_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_Kit_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_Kit_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_Kit_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_Kit_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_Kit_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VarAcct]       CHAR (10)     CONSTRAINT [DF_Kit_VarAcct] DEFAULT (' ') NOT NULL,
    [VarSub]        CHAR (24)     CONSTRAINT [DF_Kit_VarSub] DEFAULT (' ') NOT NULL,
    [WONbr]         CHAR (10)     CONSTRAINT [DF_Kit_WONbr] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [Kit0] PRIMARY KEY CLUSTERED ([KitID] ASC, [SiteID] ASC, [Status] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Kit1]
    ON [dbo].[Kit]([LevelNbr] ASC, [KitID] ASC, [SiteID] ASC, [Status] ASC) WITH (FILLFACTOR = 90);

