CREATE TABLE [dbo].[XDDPPFileFormat] (
    [BankTransitNoCD]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [BlockFill]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [CrLf]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [Descr]              CHAR (60)     DEFAULT ('') NOT NULL,
    [FormatID]           CHAR (15)     DEFAULT ('') NOT NULL,
    [HeadTrailNotes]     CHAR (255)    DEFAULT ('') NOT NULL,
    [KeepDelete]         CHAR (1)      DEFAULT ('') NOT NULL,
    [LastEffDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LeadingSpace]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [MultiAcctAllowed]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [MultiAcctImplInRpt] SMALLINT      DEFAULT ((0)) NOT NULL,
    [MultiAcctReqdInRpt] SMALLINT      DEFAULT ((0)) NOT NULL,
    [NoteID]             INT           DEFAULT ((0)) NOT NULL,
    [RecordLen]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [Selected]           CHAR (1)      DEFAULT ('') NOT NULL,
    [SKFuture01]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]         CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]         CHAR (10)     DEFAULT ('') NOT NULL,
    [TrailerRecord]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [TrimRecord]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [User1]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]             CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]              CHAR (30)     DEFAULT ('') NOT NULL,
    [VoidChkSeparate]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [XDDBankPP01Descr]   CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP01Mask]    CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP02Descr]   CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP02Mask]    CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP03Descr]   CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP03Mask]    CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP04Descr]   CHAR (30)     DEFAULT ('') NOT NULL,
    [XDDBankPP04Mask]    CHAR (30)     DEFAULT ('') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [XDDPPFileFormat0] PRIMARY KEY CLUSTERED ([FormatID] ASC)
);

