CREATE TABLE [dbo].[SalesTax] (
    [AccruTaxAcct]     CHAR (10)     NOT NULL,
    [AccruTaxSubAcct]  CHAR (24)     NOT NULL,
    [AdjByTermsDisc]   CHAR (1)      NOT NULL,
    [ApplTermDisc]     CHAR (1)      NOT NULL,
    [ApplTermsDiscTax] SMALLINT      NOT NULL,
    [APTaxPtDate]      CHAR (1)      NOT NULL,
    [ARTaxPtDate]      CHAR (1)      NOT NULL,
    [CatExcept00]      CHAR (10)     NOT NULL,
    [CatExcept01]      CHAR (10)     NOT NULL,
    [CatExcept02]      CHAR (10)     NOT NULL,
    [CatExcept03]      CHAR (10)     NOT NULL,
    [CatExcept04]      CHAR (10)     NOT NULL,
    [CatExcept05]      CHAR (10)     NOT NULL,
    [CatFlg]           CHAR (1)      NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [Descr]            CHAR (30)     NOT NULL,
    [Exemption]        CHAR (1)      NOT NULL,
    [ExemTaxId]        CHAR (10)     NOT NULL,
    [Exp_to_Proj_Sw]   SMALLINT      NOT NULL,
    [ExpTaxAcct]       CHAR (10)     NOT NULL,
    [ExpTaxSub]        CHAR (24)     NOT NULL,
    [FilingLoc]        CHAR (10)     NOT NULL,
    [GroupDetCnt]      SMALLINT      NOT NULL,
    [GroupID]          CHAR (10)     NOT NULL,
    [GroupRule]        CHAR (1)      NOT NULL,
    [InclFrt]          CHAR (1)      NOT NULL,
    [InclInDocTot]     CHAR (1)      NOT NULL,
    [Inclmisc]         CHAR (1)      NOT NULL,
    [LiabTaxAcct]      CHAR (10)     NOT NULL,
    [LiabTaxSub]       CHAR (24)     NOT NULL,
    [LocalCode]        CHAR (15)     NOT NULL,
    [LongId]           CHAR (15)     NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME NOT NULL,
    [LUpd_Prog]        CHAR (8)      NOT NULL,
    [LUpd_User]        CHAR (10)     NOT NULL,
    [Lvl2Exmpt]        SMALLINT      NOT NULL,
    [NewRateDate]      SMALLDATETIME NOT NULL,
    [NewTaxRate]       FLOAT (53)    NOT NULL,
    [NoteId]           INT           NOT NULL,
    [OldTaxRate]       FLOAT (53)    NOT NULL,
    [OPTaxPtDate]      CHAR (1)      NOT NULL,
    [POTaxPtDate]      CHAR (1)      NOT NULL,
    [PrcTaxIncl]       CHAR (1)      NOT NULL,
    [PurTaxAcct]       CHAR (10)     NOT NULL,
    [PurTaxDiscAcct]   CHAR (10)     NOT NULL,
    [PurTaxDiscSub]    CHAR (24)     NOT NULL,
    [PurTaxSub]        CHAR (24)     NOT NULL,
    [RateAboveMax]     FLOAT (53)    NOT NULL,
    [S4Future01]       CHAR (30)     NOT NULL,
    [S4Future02]       CHAR (30)     NOT NULL,
    [S4Future03]       FLOAT (53)    NOT NULL,
    [S4Future04]       FLOAT (53)    NOT NULL,
    [S4Future05]       FLOAT (53)    NOT NULL,
    [S4Future06]       FLOAT (53)    NOT NULL,
    [S4Future07]       SMALLDATETIME NOT NULL,
    [S4Future08]       SMALLDATETIME NOT NULL,
    [S4Future09]       INT           NOT NULL,
    [S4Future10]       INT           NOT NULL,
    [S4Future11]       CHAR (10)     NOT NULL,
    [S4Future12]       CHAR (10)     NOT NULL,
    [SlsTaxAcct]       CHAR (10)     NOT NULL,
    [SlsTaxDiscAcct]   CHAR (10)     NOT NULL,
    [SlsTaxDiscSub]    CHAR (24)     NOT NULL,
    [SlsTaxSub]        CHAR (24)     NOT NULL,
    [TaxAuthLvl]       CHAR (1)      NOT NULL,
    [TaxBasis]         CHAR (1)      NOT NULL,
    [TaxCalcLvl]       CHAR (1)      NOT NULL,
    [TaxCalcMeth]      CHAR (1)      NOT NULL,
    [TaxCalcType]      CHAR (1)      NOT NULL,
    [TaxId]            CHAR (10)     NOT NULL,
    [TaxRate]          FLOAT (53)    NOT NULL,
    [TaxRvsdDate]      SMALLDATETIME NOT NULL,
    [TaxType]          CHAR (1)      NOT NULL,
    [TxblAdjPct]       FLOAT (53)    NOT NULL,
    [TxblMax]          FLOAT (53)    NOT NULL,
    [TxblMin]          FLOAT (53)    NOT NULL,
    [TxblMinMaxCuryID] CHAR (4)      NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [VendID]           CHAR (15)     NOT NULL,
    [VoucherTax]       SMALLINT      NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [SalesTax0] PRIMARY KEY CLUSTERED ([TaxType] ASC, [TaxId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [SalesTax1]
    ON [dbo].[SalesTax]([TaxId] ASC, [TaxType] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [SalesTax2]
    ON [dbo].[SalesTax]([Descr] ASC) WITH (FILLFACTOR = 90);

