CREATE TABLE [dbo].[smConSetup] (
    [AdjustAcct]          CHAR (10)     NOT NULL,
    [AdjustSub]           CHAR (24)     NOT NULL,
    [AutoBatNbr]          SMALLINT      NOT NULL,
    [AutoPrint]           SMALLINT      NOT NULL,
    [CreditAdjAcct]       CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [DebitAdjAcct]        CHAR (10)     NOT NULL,
    [DepositAcct]         CHAR (10)     NOT NULL,
    [DepositSub]          CHAR (24)     NOT NULL,
    [LastAccrual]         SMALLDATETIME NOT NULL,
    [LastBatNbr]          CHAR (10)     NOT NULL,
    [LastBilling]         SMALLDATETIME NOT NULL,
    [LastDepositBillling] SMALLDATETIME NOT NULL,
    [LastDiscBilling]     SMALLDATETIME NOT NULL,
    [LastMiscBilling]     SMALLDATETIME NOT NULL,
    [LastRevenue]         SMALLDATETIME NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MiscAcct]            CHAR (10)     NOT NULL,
    [MiscSub]             CHAR (24)     NOT NULL,
    [PartialAdjust]       SMALLINT      NOT NULL,
    [PartialDeposits]     SMALLINT      NOT NULL,
    [SetUpID]             CHAR (10)     NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               SMALLINT      NOT NULL,
    [User4]               SMALLINT      NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smConSetup0] PRIMARY KEY CLUSTERED ([SetUpID] ASC) WITH (FILLFACTOR = 90)
);

