CREATE TABLE [dbo].[EDShipment] (
    [AddWeight]          FLOAT (53)    CONSTRAINT [DF_EDShipment_AddWeight] DEFAULT ((0)) NOT NULL,
    [AHCharge]           FLOAT (53)    CONSTRAINT [DF_EDShipment_AHCharge] DEFAULT ((0)) NOT NULL,
    [AirbillNbr]         CHAR (30)     CONSTRAINT [DF_EDShipment_AirbillNbr] DEFAULT (' ') NOT NULL,
    [BOLNbr]             CHAR (20)     CONSTRAINT [DF_EDShipment_BOLNbr] DEFAULT (' ') NOT NULL,
    [BOLState]           CHAR (1)      CONSTRAINT [DF_EDShipment_BOLState] DEFAULT (' ') NOT NULL,
    [CODCharge]          FLOAT (53)    CONSTRAINT [DF_EDShipment_CODCharge] DEFAULT ((0)) NOT NULL,
    [CommCodeQual]       CHAR (2)      CONSTRAINT [DF_EDShipment_CommCodeQual] DEFAULT (' ') NOT NULL,
    [ConsignAddr1]       CHAR (35)     CONSTRAINT [DF_EDShipment_ConsignAddr1] DEFAULT (' ') NOT NULL,
    [ConsignAddr2]       CHAR (35)     CONSTRAINT [DF_EDShipment_ConsignAddr2] DEFAULT (' ') NOT NULL,
    [ConsignAddr3]       CHAR (35)     CONSTRAINT [DF_EDShipment_ConsignAddr3] DEFAULT (' ') NOT NULL,
    [ConsignCity]        CHAR (19)     CONSTRAINT [DF_EDShipment_ConsignCity] DEFAULT (' ') NOT NULL,
    [ConsignCountry]     CHAR (3)      CONSTRAINT [DF_EDShipment_ConsignCountry] DEFAULT (' ') NOT NULL,
    [ConsignName]        CHAR (35)     CONSTRAINT [DF_EDShipment_ConsignName] DEFAULT (' ') NOT NULL,
    [ConsignState]       CHAR (3)      CONSTRAINT [DF_EDShipment_ConsignState] DEFAULT (' ') NOT NULL,
    [ConsignZip]         CHAR (10)     CONSTRAINT [DF_EDShipment_ConsignZip] DEFAULT (' ') NOT NULL,
    [CrossDock]          CHAR (20)     CONSTRAINT [DF_EDShipment_CrossDock] DEFAULT (' ') NOT NULL,
    [Crtd_Datetime]      SMALLDATETIME CONSTRAINT [DF_EDShipment_Crtd_Datetime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]          CHAR (8)      CONSTRAINT [DF_EDShipment_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]          CHAR (10)     CONSTRAINT [DF_EDShipment_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryAHCharge]       FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryAHCharge] DEFAULT ((0)) NOT NULL,
    [CuryCODCharge]      FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryCODCharge] DEFAULT ((0)) NOT NULL,
    [CuryHazCharge]      FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryHazCharge] DEFAULT ((0)) NOT NULL,
    [CuryInsurCharge]    FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryInsurCharge] DEFAULT ((0)) NOT NULL,
    [CuryMiscCharge]     FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryMiscCharge] DEFAULT ((0)) NOT NULL,
    [CuryOverSizeCharge] FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryOverSizeCharge] DEFAULT ((0)) NOT NULL,
    [CuryPickupCharge]   FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryPickupCharge] DEFAULT ((0)) NOT NULL,
    [CuryShipCharge]     FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryShipCharge] DEFAULT ((0)) NOT NULL,
    [CurySurCharge]      FLOAT (53)    CONSTRAINT [DF_EDShipment_CurySurCharge] DEFAULT ((0)) NOT NULL,
    [CuryTotBillCharge]  FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryTotBillCharge] DEFAULT ((0)) NOT NULL,
    [CuryTotShipCharge]  FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryTotShipCharge] DEFAULT ((0)) NOT NULL,
    [CuryTrackCharge]    FLOAT (53)    CONSTRAINT [DF_EDShipment_CuryTrackCharge] DEFAULT ((0)) NOT NULL,
    [EquipNbr]           CHAR (20)     CONSTRAINT [DF_EDShipment_EquipNbr] DEFAULT (' ') NOT NULL,
    [HazCharge]          FLOAT (53)    CONSTRAINT [DF_EDShipment_HazCharge] DEFAULT ((0)) NOT NULL,
    [Height]             FLOAT (53)    CONSTRAINT [DF_EDShipment_Height] DEFAULT ((0)) NOT NULL,
    [HeightUOM]          CHAR (6)      CONSTRAINT [DF_EDShipment_HeightUOM] DEFAULT (' ') NOT NULL,
    [InsurCharge]        FLOAT (53)    CONSTRAINT [DF_EDShipment_InsurCharge] DEFAULT ((0)) NOT NULL,
    [Len]                FLOAT (53)    CONSTRAINT [DF_EDShipment_Len] DEFAULT ((0)) NOT NULL,
    [LenUOM]             CHAR (6)      CONSTRAINT [DF_EDShipment_LenUOM] DEFAULT (' ') NOT NULL,
    [Lupd_Datetime]      SMALLDATETIME CONSTRAINT [DF_EDShipment_Lupd_Datetime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]          CHAR (8)      CONSTRAINT [DF_EDShipment_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]          CHAR (10)     CONSTRAINT [DF_EDShipment_Lupd_User] DEFAULT (' ') NOT NULL,
    [MiscCharge]         FLOAT (53)    CONSTRAINT [DF_EDShipment_MiscCharge] DEFAULT ((0)) NOT NULL,
    [NbrContainer]       SMALLINT      CONSTRAINT [DF_EDShipment_NbrContainer] DEFAULT ((0)) NOT NULL,
    [NoteId]             INT           CONSTRAINT [DF_EDShipment_NoteId] DEFAULT ((0)) NOT NULL,
    [OverSizeCharge]     FLOAT (53)    CONSTRAINT [DF_EDShipment_OverSizeCharge] DEFAULT ((0)) NOT NULL,
    [PackMethod]         CHAR (2)      CONSTRAINT [DF_EDShipment_PackMethod] DEFAULT (' ') NOT NULL,
    [PickupCharge]       FLOAT (53)    CONSTRAINT [DF_EDShipment_PickupCharge] DEFAULT ((0)) NOT NULL,
    [Pro]                CHAR (30)     CONSTRAINT [DF_EDShipment_Pro] DEFAULT (' ') NOT NULL,
    [S4Future01]         CHAR (30)     CONSTRAINT [DF_EDShipment_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]         CHAR (30)     CONSTRAINT [DF_EDShipment_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]         FLOAT (53)    CONSTRAINT [DF_EDShipment_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]         FLOAT (53)    CONSTRAINT [DF_EDShipment_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]         FLOAT (53)    CONSTRAINT [DF_EDShipment_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]         FLOAT (53)    CONSTRAINT [DF_EDShipment_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]         SMALLDATETIME CONSTRAINT [DF_EDShipment_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]         SMALLDATETIME CONSTRAINT [DF_EDShipment_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]         INT           CONSTRAINT [DF_EDShipment_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]         INT           CONSTRAINT [DF_EDShipment_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]         CHAR (10)     CONSTRAINT [DF_EDShipment_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]         CHAR (10)     CONSTRAINT [DF_EDShipment_S4Future12] DEFAULT (' ') NOT NULL,
    [SCAC]               CHAR (5)      CONSTRAINT [DF_EDShipment_SCAC] DEFAULT (' ') NOT NULL,
    [SendASN]            SMALLINT      CONSTRAINT [DF_EDShipment_SendASN] DEFAULT ((0)) NOT NULL,
    [ShipperAddr1]       CHAR (35)     CONSTRAINT [DF_EDShipment_ShipperAddr1] DEFAULT (' ') NOT NULL,
    [ShipperAddr2]       CHAR (35)     CONSTRAINT [DF_EDShipment_ShipperAddr2] DEFAULT (' ') NOT NULL,
    [ShipperAddr3]       CHAR (35)     CONSTRAINT [DF_EDShipment_ShipperAddr3] DEFAULT (' ') NOT NULL,
    [ShipperCity]        CHAR (19)     CONSTRAINT [DF_EDShipment_ShipperCity] DEFAULT (' ') NOT NULL,
    [ShipperCountry]     CHAR (3)      CONSTRAINT [DF_EDShipment_ShipperCountry] DEFAULT (' ') NOT NULL,
    [ShipperName]        CHAR (35)     CONSTRAINT [DF_EDShipment_ShipperName] DEFAULT (' ') NOT NULL,
    [ShipperState]       CHAR (3)      CONSTRAINT [DF_EDShipment_ShipperState] DEFAULT (' ') NOT NULL,
    [ShipperZip]         CHAR (10)     CONSTRAINT [DF_EDShipment_ShipperZip] DEFAULT (' ') NOT NULL,
    [ShipStatus]         CHAR (1)      CONSTRAINT [DF_EDShipment_ShipStatus] DEFAULT (' ') NOT NULL,
    [ShpCharge]          FLOAT (53)    CONSTRAINT [DF_EDShipment_ShpCharge] DEFAULT ((0)) NOT NULL,
    [ShpDate]            SMALLDATETIME CONSTRAINT [DF_EDShipment_ShpDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShpTime]            CHAR (10)     CONSTRAINT [DF_EDShipment_ShpTime] DEFAULT (' ') NOT NULL,
    [ShpWeight]          FLOAT (53)    CONSTRAINT [DF_EDShipment_ShpWeight] DEFAULT ((0)) NOT NULL,
    [ShpWeightUom]       CHAR (6)      CONSTRAINT [DF_EDShipment_ShpWeightUom] DEFAULT (' ') NOT NULL,
    [Surcharge]          FLOAT (53)    CONSTRAINT [DF_EDShipment_Surcharge] DEFAULT ((0)) NOT NULL,
    [TotBillCharge]      FLOAT (53)    CONSTRAINT [DF_EDShipment_TotBillCharge] DEFAULT ((0)) NOT NULL,
    [TotShipCharge]      FLOAT (53)    CONSTRAINT [DF_EDShipment_TotShipCharge] DEFAULT ((0)) NOT NULL,
    [TrackCharge]        FLOAT (53)    CONSTRAINT [DF_EDShipment_TrackCharge] DEFAULT ((0)) NOT NULL,
    [TrackingNbr]        CHAR (30)     CONSTRAINT [DF_EDShipment_TrackingNbr] DEFAULT (' ') NOT NULL,
    [User1]              CHAR (30)     CONSTRAINT [DF_EDShipment_User1] DEFAULT (' ') NOT NULL,
    [User10]             SMALLDATETIME CONSTRAINT [DF_EDShipment_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]              CHAR (30)     CONSTRAINT [DF_EDShipment_User2] DEFAULT (' ') NOT NULL,
    [User3]              CHAR (30)     CONSTRAINT [DF_EDShipment_User3] DEFAULT (' ') NOT NULL,
    [User4]              CHAR (30)     CONSTRAINT [DF_EDShipment_User4] DEFAULT (' ') NOT NULL,
    [User5]              FLOAT (53)    CONSTRAINT [DF_EDShipment_User5] DEFAULT ((0)) NOT NULL,
    [User6]              FLOAT (53)    CONSTRAINT [DF_EDShipment_User6] DEFAULT ((0)) NOT NULL,
    [User7]              CHAR (10)     CONSTRAINT [DF_EDShipment_User7] DEFAULT (' ') NOT NULL,
    [User8]              CHAR (10)     CONSTRAINT [DF_EDShipment_User8] DEFAULT (' ') NOT NULL,
    [User9]              SMALLDATETIME CONSTRAINT [DF_EDShipment_User9] DEFAULT ('01/01/1900') NOT NULL,
    [ViaCode]            CHAR (15)     CONSTRAINT [DF_EDShipment_ViaCode] DEFAULT (' ') NOT NULL,
    [Volume]             FLOAT (53)    CONSTRAINT [DF_EDShipment_Volume] DEFAULT ((0)) NOT NULL,
    [VolumeUOM]          CHAR (6)      CONSTRAINT [DF_EDShipment_VolumeUOM] DEFAULT (' ') NOT NULL,
    [Weight]             FLOAT (53)    CONSTRAINT [DF_EDShipment_Weight] DEFAULT ((0)) NOT NULL,
    [WeightUOM]          CHAR (6)      CONSTRAINT [DF_EDShipment_WeightUOM] DEFAULT (' ') NOT NULL,
    [Width]              FLOAT (53)    CONSTRAINT [DF_EDShipment_Width] DEFAULT ((0)) NOT NULL,
    [WidthUOM]           CHAR (6)      CONSTRAINT [DF_EDShipment_WidthUOM] DEFAULT (' ') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [EDShipment0] PRIMARY KEY CLUSTERED ([BOLNbr] ASC) WITH (FILLFACTOR = 90)
);

