CREATE TABLE [dbo].[RtgTran] (
    [ActLbrHrs]         FLOAT (53)    CONSTRAINT [DF_RtgTran_ActLbrHrs] DEFAULT ((0)) NOT NULL,
    [ActMachHrs]        FLOAT (53)    CONSTRAINT [DF_RtgTran_ActMachHrs] DEFAULT ((0)) NOT NULL,
    [BatNbr]            CHAR (10)     CONSTRAINT [DF_RtgTran_BatNbr] DEFAULT (' ') NOT NULL,
    [CDirOthCst]        FLOAT (53)    CONSTRAINT [DF_RtgTran_CDirOthCst] DEFAULT ((0)) NOT NULL,
    [CpnyID]            CHAR (10)     CONSTRAINT [DF_RtgTran_CpnyID] DEFAULT (' ') NOT NULL,
    [CrewSize]          FLOAT (53)    CONSTRAINT [DF_RtgTran_CrewSize] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME CONSTRAINT [DF_RtgTran_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      CONSTRAINT [DF_RtgTran_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     CONSTRAINT [DF_RtgTran_Crtd_User] DEFAULT (' ') NOT NULL,
    [CStdLbrHrs]        FLOAT (53)    CONSTRAINT [DF_RtgTran_CStdLbrHrs] DEFAULT ((0)) NOT NULL,
    [CStdMachHrs]       FLOAT (53)    CONSTRAINT [DF_RtgTran_CStdMachHrs] DEFAULT ((0)) NOT NULL,
    [DeleteFlg]         SMALLINT      CONSTRAINT [DF_RtgTran_DeleteFlg] DEFAULT ((0)) NOT NULL,
    [DirLbrAmt]         FLOAT (53)    CONSTRAINT [DF_RtgTran_DirLbrAmt] DEFAULT ((0)) NOT NULL,
    [DirLbrEffVarAmt]   FLOAT (53)    CONSTRAINT [DF_RtgTran_DirLbrEffVarAmt] DEFAULT ((0)) NOT NULL,
    [DirLbrRateVarAmt]  FLOAT (53)    CONSTRAINT [DF_RtgTran_DirLbrRateVarAmt] DEFAULT ((0)) NOT NULL,
    [DirOthAmt]         FLOAT (53)    CONSTRAINT [DF_RtgTran_DirOthAmt] DEFAULT ((0)) NOT NULL,
    [DirOthEffVarAmt]   FLOAT (53)    CONSTRAINT [DF_RtgTran_DirOthEffVarAmt] DEFAULT ((0)) NOT NULL,
    [DirOthRateVarAmt]  FLOAT (53)    CONSTRAINT [DF_RtgTran_DirOthRateVarAmt] DEFAULT ((0)) NOT NULL,
    [KitID]             CHAR (30)     CONSTRAINT [DF_RtgTran_KitID] DEFAULT (' ') NOT NULL,
    [LaborClassID]      CHAR (10)     CONSTRAINT [DF_RtgTran_LaborClassID] DEFAULT (' ') NOT NULL,
    [LbrDirOffAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_LbrDirOffAcct] DEFAULT (' ') NOT NULL,
    [LbrDirOffSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_LbrDirOffSub] DEFAULT (' ') NOT NULL,
    [LbrDirVarAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_LbrDirVarAcct] DEFAULT (' ') NOT NULL,
    [LbrDirVarSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_LbrDirVarSub] DEFAULT (' ') NOT NULL,
    [LbrOvhOffAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_LbrOvhOffAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhOffSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_LbrOvhOffSub] DEFAULT (' ') NOT NULL,
    [LbrOvhVarAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_LbrOvhVarAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhVarSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_LbrOvhVarSub] DEFAULT (' ') NOT NULL,
    [LineID]            INT           CONSTRAINT [DF_RtgTran_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]           SMALLINT      CONSTRAINT [DF_RtgTran_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]           CHAR (5)      CONSTRAINT [DF_RtgTran_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME CONSTRAINT [DF_RtgTran_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      CONSTRAINT [DF_RtgTran_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     CONSTRAINT [DF_RtgTran_LUpd_User] DEFAULT (' ') NOT NULL,
    [MachinID]          CHAR (10)     CONSTRAINT [DF_RtgTran_MachinID] DEFAULT (' ') NOT NULL,
    [MachOvhOffAcct]    CHAR (10)     CONSTRAINT [DF_RtgTran_MachOvhOffAcct] DEFAULT (' ') NOT NULL,
    [MachOvhOffSub]     CHAR (24)     CONSTRAINT [DF_RtgTran_MachOvhOffSub] DEFAULT (' ') NOT NULL,
    [MachOvhVarAcct]    CHAR (10)     CONSTRAINT [DF_RtgTran_MachOvhVarAcct] DEFAULT (' ') NOT NULL,
    [MachOvhVarSub]     CHAR (24)     CONSTRAINT [DF_RtgTran_MachOvhVarSub] DEFAULT (' ') NOT NULL,
    [NoteID]            INT           CONSTRAINT [DF_RtgTran_NoteID] DEFAULT ((0)) NOT NULL,
    [OperationID]       CHAR (10)     CONSTRAINT [DF_RtgTran_OperationID] DEFAULT (' ') NOT NULL,
    [OthDirOffAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_OthDirOffAcct] DEFAULT (' ') NOT NULL,
    [OthDirOffSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_OthDirOffSub] DEFAULT (' ') NOT NULL,
    [OthDirVarAcct]     CHAR (10)     CONSTRAINT [DF_RtgTran_OthDirVarAcct] DEFAULT (' ') NOT NULL,
    [OthDirVarSub]      CHAR (24)     CONSTRAINT [DF_RtgTran_OthDirVarSub] DEFAULT (' ') NOT NULL,
    [OvhLbrAmt]         FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhLbrAmt] DEFAULT ((0)) NOT NULL,
    [OvhLbrEffVarAmt]   FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhLbrEffVarAmt] DEFAULT ((0)) NOT NULL,
    [OvhLbrRateVarAmt]  FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhLbrRateVarAmt] DEFAULT ((0)) NOT NULL,
    [OvhMachAmt]        FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhMachAmt] DEFAULT ((0)) NOT NULL,
    [OvhMachEffVarAmt]  FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhMachEffVarAmt] DEFAULT ((0)) NOT NULL,
    [OvhMachRateVarAmt] FLOAT (53)    CONSTRAINT [DF_RtgTran_OvhMachRateVarAmt] DEFAULT ((0)) NOT NULL,
    [RefNbr]            CHAR (10)     CONSTRAINT [DF_RtgTran_RefNbr] DEFAULT (' ') NOT NULL,
    [RtgLineNbr]        SMALLINT      CONSTRAINT [DF_RtgTran_RtgLineNbr] DEFAULT ((0)) NOT NULL,
    [RtgSiteID]         CHAR (10)     CONSTRAINT [DF_RtgTran_RtgSiteID] DEFAULT (' ') NOT NULL,
    [RtgStatus]         SMALLINT      CONSTRAINT [DF_RtgTran_RtgStatus] DEFAULT ((0)) NOT NULL,
    [S4Future01]        CHAR (30)     CONSTRAINT [DF_RtgTran_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     CONSTRAINT [DF_RtgTran_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    CONSTRAINT [DF_RtgTran_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    CONSTRAINT [DF_RtgTran_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    CONSTRAINT [DF_RtgTran_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    CONSTRAINT [DF_RtgTran_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME CONSTRAINT [DF_RtgTran_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME CONSTRAINT [DF_RtgTran_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           CONSTRAINT [DF_RtgTran_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           CONSTRAINT [DF_RtgTran_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     CONSTRAINT [DF_RtgTran_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     CONSTRAINT [DF_RtgTran_S4Future12] DEFAULT (' ') NOT NULL,
    [StepNbr]           CHAR (5)      CONSTRAINT [DF_RtgTran_StepNbr] DEFAULT (' ') NOT NULL,
    [ToolID1]           CHAR (10)     CONSTRAINT [DF_RtgTran_ToolID1] DEFAULT (' ') NOT NULL,
    [ToolID2]           CHAR (10)     CONSTRAINT [DF_RtgTran_ToolID2] DEFAULT (' ') NOT NULL,
    [ToolID3]           CHAR (10)     CONSTRAINT [DF_RtgTran_ToolID3] DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     CONSTRAINT [DF_RtgTran_User1] DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     CONSTRAINT [DF_RtgTran_User2] DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    CONSTRAINT [DF_RtgTran_User3] DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    CONSTRAINT [DF_RtgTran_User4] DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     CONSTRAINT [DF_RtgTran_User5] DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     CONSTRAINT [DF_RtgTran_User6] DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME CONSTRAINT [DF_RtgTran_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME CONSTRAINT [DF_RtgTran_User8] DEFAULT ('01/01/1900') NOT NULL,
    [WorkCenterID]      CHAR (10)     CONSTRAINT [DF_RtgTran_WorkCenterID] DEFAULT (' ') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [RtgTran0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [RefNbr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

