CREATE TABLE [dbo].[smPMModel] (
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Descr]         CHAR (60)     NOT NULL,
    [DetailType]    CHAR (1)      NOT NULL,
    [Invtid]        CHAR (30)     NOT NULL,
    [LineNbr]       SMALLINT      NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [ManufId]       CHAR (10)     NOT NULL,
    [ModelId]       CHAR (40)     NOT NULL,
    [PMType]        CHAR (10)     NOT NULL,
    [Quantity]      FLOAT (53)    NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [smPMModel0] PRIMARY KEY CLUSTERED ([PMType] ASC, [ManufId] ASC, [ModelId] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

