CREATE TABLE [dbo].[smSplCommDetail] (
    [CommissionPercent] FLOAT (53)    NOT NULL,
    [Crtd_DateTIme]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [EmpID]             CHAR (10)     NOT NULL,
    [EndingMileage]     FLOAT (53)    NOT NULL,
    [Lupd_DateTime]     SMALLDATETIME NOT NULL,
    [Lupd_Prog]         CHAR (8)      NOT NULL,
    [Lupd_User]         CHAR (10)     NOT NULL,
    [RevenueCredit]     FLOAT (53)    NOT NULL,
    [ServiceCallID]     CHAR (10)     NOT NULL,
    [user1]             CHAR (30)     NOT NULL,
    [user2]             CHAR (30)     NOT NULL,
    [user3]             FLOAT (53)    NOT NULL,
    [user4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [VehicleID]         CHAR (10)     NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [smSplCommDetail0] PRIMARY KEY CLUSTERED ([ServiceCallID] ASC, [EmpID] ASC) WITH (FILLFACTOR = 90)
);

