CREATE TABLE [dbo].[cftFOSetUp] (
    [ClassBag]      CHAR (6)      NOT NULL,
    [ClassIngr]     CHAR (6)      NOT NULL,
    [ClassRation]   CHAR (6)      NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DfltOrderType] CHAR (2)      NOT NULL,
    [DfltPath]      CHAR (120)    NOT NULL,
    [DfltPriority]  CHAR (10)     NOT NULL,
    [FeedPlanPct]   FLOAT (53)    NOT NULL,
    [GLDelOffAcct]  CHAR (10)     NOT NULL,
    [GLDelOffDesc]  CHAR (30)     NOT NULL,
    [GLDelOffSub]   CHAR (24)     NOT NULL,
    [GLDelvAcct]    CHAR (10)     NOT NULL,
    [GLDelvDesc]    CHAR (30)     NOT NULL,
    [GLDelvSub]     CHAR (24)     NOT NULL,
    [GLGMOffAcct]   CHAR (10)     NOT NULL,
    [GLGMOffDesc]   CHAR (30)     NOT NULL,
    [GLGMOffSub]    CHAR (24)     NOT NULL,
    [GLGrindAcct]   CHAR (10)     NOT NULL,
    [GLGrindDesc]   CHAR (30)     NOT NULL,
    [GLGrindSub]    CHAR (24)     NOT NULL,
    [LastOrdNbr]    CHAR (10)     NOT NULL,
    [LastRefNbr]    CHAR (10)     NOT NULL,
    [LoadTime]      FLOAT (53)    NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [MaxLoad]       FLOAT (53)    NOT NULL,
    [OrdWgtLmt]     FLOAT (53)    NOT NULL,
    [ProjPref]      CHAR (2)      NOT NULL,
    [RoadRestr]     SMALLINT      NOT NULL,
    [SetUpId]       CHAR (2)      NOT NULL,
    [SiteTaskId]    CHAR (32)     NOT NULL,
    [StatusChg]     CHAR (1)      NOT NULL,
    [StatusCplt]    CHAR (1)      NOT NULL,
    [StatusCxl]     CHAR (1)      NOT NULL,
    [StatusDflt]    CHAR (1)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         INT           NOT NULL,
    [tstamp]        ROWVERSION    NULL,
    CONSTRAINT [PK_cftFOSetUp] PRIMARY KEY NONCLUSTERED ([SetUpId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE UNIQUE CLUSTERED INDEX [cftFOSetup0]
    ON [dbo].[cftFOSetUp]([SetUpId] ASC) WITH (FILLFACTOR = 90);

