CREATE TABLE [dbo].[CustItem] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustItem_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_CustItem_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_CustItem_Crtd_User] DEFAULT (' ') NOT NULL,
    [CustID]        CHAR (15)     CONSTRAINT [DF_CustItem_CustID] DEFAULT (' ') NOT NULL,
    [CustItemID]    CHAR (30)     CONSTRAINT [DF_CustItem_CustItemID] DEFAULT (' ') NOT NULL,
    [FiscYr]        CHAR (4)      CONSTRAINT [DF_CustItem_FiscYr] DEFAULT (' ') NOT NULL,
    [InvtID]        CHAR (30)     CONSTRAINT [DF_CustItem_InvtID] DEFAULT (' ') NOT NULL,
    [LastSaleCost]  FLOAT (53)    CONSTRAINT [DF_CustItem_LastSaleCost] DEFAULT ((0)) NOT NULL,
    [LastSaleDate]  SMALLDATETIME CONSTRAINT [DF_CustItem_LastSaleDate] DEFAULT ('01/01/1900') NOT NULL,
    [LastSalePrice] FLOAT (53)    CONSTRAINT [DF_CustItem_LastSalePrice] DEFAULT ((0)) NOT NULL,
    [LastSaleQty]   FLOAT (53)    CONSTRAINT [DF_CustItem_LastSaleQty] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_CustItem_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_CustItem_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_CustItem_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_CustItem_NoteID] DEFAULT ((0)) NOT NULL,
    [PYAvgCost]     FLOAT (53)    CONSTRAINT [DF_CustItem_PYAvgCost] DEFAULT ((0)) NOT NULL,
    [PYAvgPrice]    FLOAT (53)    CONSTRAINT [DF_CustItem_PYAvgPrice] DEFAULT ((0)) NOT NULL,
    [PYCOGS]        FLOAT (53)    CONSTRAINT [DF_CustItem_PYCOGS] DEFAULT ((0)) NOT NULL,
    [PYCostRet]     FLOAT (53)    CONSTRAINT [DF_CustItem_PYCostRet] DEFAULT ((0)) NOT NULL,
    [PYOrders]      FLOAT (53)    CONSTRAINT [DF_CustItem_PYOrders] DEFAULT ((0)) NOT NULL,
    [PYQtyRet]      FLOAT (53)    CONSTRAINT [DF_CustItem_PYQtyRet] DEFAULT ((0)) NOT NULL,
    [PYQtySold]     FLOAT (53)    CONSTRAINT [DF_CustItem_PYQtySold] DEFAULT ((0)) NOT NULL,
    [PYSales]       FLOAT (53)    CONSTRAINT [DF_CustItem_PYSales] DEFAULT ((0)) NOT NULL,
    [PYSalesRet]    FLOAT (53)    CONSTRAINT [DF_CustItem_PYSalesRet] DEFAULT ((0)) NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_CustItem_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_CustItem_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_CustItem_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_CustItem_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_CustItem_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_CustItem_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_CustItem_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_CustItem_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_CustItem_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_CustItem_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_CustItem_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_CustItem_S4Future12] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_CustItem_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_CustItem_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_CustItem_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_CustItem_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_CustItem_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_CustItem_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_CustItem_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_CustItem_User8] DEFAULT ('01/01/1900') NOT NULL,
    [YTDAvgCost]    FLOAT (53)    CONSTRAINT [DF_CustItem_YTDAvgCost] DEFAULT ((0)) NOT NULL,
    [YTDAvgPrice]   FLOAT (53)    CONSTRAINT [DF_CustItem_YTDAvgPrice] DEFAULT ((0)) NOT NULL,
    [YTDCOGS]       FLOAT (53)    CONSTRAINT [DF_CustItem_YTDCOGS] DEFAULT ((0)) NOT NULL,
    [YTDCostRet]    FLOAT (53)    CONSTRAINT [DF_CustItem_YTDCostRet] DEFAULT ((0)) NOT NULL,
    [YTDOrders]     FLOAT (53)    CONSTRAINT [DF_CustItem_YTDOrders] DEFAULT ((0)) NOT NULL,
    [YTDQtyRet]     FLOAT (53)    CONSTRAINT [DF_CustItem_YTDQtyRet] DEFAULT ((0)) NOT NULL,
    [YTDQtySold]    FLOAT (53)    CONSTRAINT [DF_CustItem_YTDQtySold] DEFAULT ((0)) NOT NULL,
    [YTDSales]      FLOAT (53)    CONSTRAINT [DF_CustItem_YTDSales] DEFAULT ((0)) NOT NULL,
    [YTDSalesRet]   FLOAT (53)    CONSTRAINT [DF_CustItem_YTDSalesRet] DEFAULT ((0)) NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CustItem0] PRIMARY KEY CLUSTERED ([CustID] ASC, [InvtID] ASC, [FiscYr] ASC) WITH (FILLFACTOR = 90)
);

