CREATE TABLE [dbo].[XDDBank] (
    [Acct]                CHAR (10)     NOT NULL,
    [AcctType]            CHAR (1)      NOT NULL,
    [ACHCompanyID]        CHAR (30)     NOT NULL,
    [ACHCompanyName]      CHAR (30)     NOT NULL,
    [ACHCrLf]             CHAR (1)      NOT NULL,
    [ACHDelete]           CHAR (1)      NOT NULL,
    [ACHFileIDModifier]   CHAR (1)      NOT NULL,
    [ACHFileName]         CHAR (80)     NOT NULL,
    [ACHFillBlock]        CHAR (1)      NOT NULL,
    [ACHImmDest]          CHAR (30)     NOT NULL,
    [ACHImmDestN]         CHAR (30)     NOT NULL,
    [ACHImmOrig]          CHAR (30)     NOT NULL,
    [ACHImmOrigN]         CHAR (30)     NOT NULL,
    [ACHInclDR]           CHAR (1)      NOT NULL,
    [ACHMixedCrDr]        CHAR (1)      NOT NULL,
    [ACHOrigDFI]          CHAR (9)      NOT NULL,
    [ACHOrigDFIName]      CHAR (35)     NOT NULL,
    [ACHPreNote]          CHAR (1)      NOT NULL,
    [ACHRecord]           CHAR (1)      NOT NULL,
    [ACHTPZeroDollar]     CHAR (1)      NOT NULL,
    [APArchive]           SMALLINT      NOT NULL,
    [APAutoClear]         SMALLINT      NOT NULL,
    [APFileFromSetup]     SMALLINT      NOT NULL,
    [APGatewayOperID]     CHAR (9)      NOT NULL,
    [ARACHDelete]         CHAR (1)      NOT NULL,
    [ARACHFileName]       CHAR (80)     NOT NULL,
    [ARACHInclCR]         CHAR (1)      NOT NULL,
    [ARACHMixedCrDr]      CHAR (1)      NOT NULL,
    [ARACHPreNote]        CHAR (1)      NOT NULL,
    [ARACHTPZeroDollar]   CHAR (1)      NOT NULL,
    [ARArchive]           SMALLINT      NOT NULL,
    [AREMARTran]          CHAR (1)      NOT NULL,
    [AREMAttachment]      CHAR (128)    NOT NULL,
    [AREMAutoWrap]        INT           NOT NULL,
    [AREMCpnyName]        CHAR (128)    NOT NULL,
    [AREMFromAddr]        CHAR (128)    NOT NULL,
    [AREMFromName]        CHAR (128)    NOT NULL,
    [AREMFromSetup]       SMALLINT      NOT NULL,
    [AREMMessageBottom]   SMALLINT      NOT NULL,
    [AREMMessageTop]      SMALLINT      NOT NULL,
    [AREMNotification]    CHAR (1)      NOT NULL,
    [AREMPriority]        INT           NOT NULL,
    [AREMReplyToAddr]     CHAR (128)    NOT NULL,
    [AREMReplyToName]     CHAR (128)    NOT NULL,
    [AREMStubLayout]      CHAR (1)      NOT NULL,
    [AREMSubject]         CHAR (128)    NOT NULL,
    [AREMTUser1]          CHAR (30)     NOT NULL,
    [AREMTUser2]          CHAR (30)     NOT NULL,
    [AREMTUser3]          CHAR (30)     NOT NULL,
    [AREMTUser4]          CHAR (30)     NOT NULL,
    [AREMTUser5]          CHAR (30)     NOT NULL,
    [AREMTUser6]          CHAR (30)     NOT NULL,
    [AREMTUser7]          CHAR (30)     NOT NULL,
    [AREMTUser8]          CHAR (30)     NOT NULL,
    [AREMUser1]           CHAR (30)     NOT NULL,
    [AREMUser2]           CHAR (30)     NOT NULL,
    [AREMUser3]           CHAR (30)     NOT NULL,
    [AREMUser4]           CHAR (30)     NOT NULL,
    [AREMUser5]           CHAR (30)     NOT NULL,
    [AREMUser6]           CHAR (30)     NOT NULL,
    [AREMUser7]           CHAR (30)     NOT NULL,
    [AREMUser8]           CHAR (30)     NOT NULL,
    [ARFileFromSetup]     SMALLINT      NOT NULL,
    [ARHeadTrailID]       CHAR (1)      NOT NULL,
    [ARPathACHScript]     CHAR (128)    NOT NULL,
    [ARTest]              CHAR (1)      DEFAULT ('') NOT NULL,
    [BankAcct]            CHAR (30)     NOT NULL,
    [BankTransit]         CHAR (30)     NOT NULL,
    [CommDevice]          CHAR (128)    NOT NULL,
    [CommEchoOn]          SMALLINT      NOT NULL,
    [CommLocation]        CHAR (128)    NOT NULL,
    [CommPhone]           CHAR (20)     NOT NULL,
    [CommPXferProto]      SMALLINT      NOT NULL,
    [CommSecProg]         CHAR (128)    NOT NULL,
    [CommTermEmulation]   CHAR (1)      NOT NULL,
    [CommType]            CHAR (1)      NOT NULL,
    [CommUserProg]        CHAR (128)    NOT NULL,
    [CompanyIDCCD]        CHAR (10)     NOT NULL,
    [CompanyIDCCDP]       CHAR (10)     NOT NULL,
    [CompanyIDCCDT]       CHAR (10)     NOT NULL,
    [CompanyIDCTX]        CHAR (10)     NOT NULL,
    [CompanyIDIAT]        CHAR (10)     NOT NULL,
    [CompanyIDPPD]        CHAR (10)     NOT NULL,
    [CompanyIDUnique]     SMALLINT      NOT NULL,
    [CompEntryDescCCD]    CHAR (16)     NOT NULL,
    [CompEntryDescCCDP]   CHAR (16)     NOT NULL,
    [CompEntryDescCCDT]   CHAR (16)     NOT NULL,
    [CompEntryDescCTX]    CHAR (16)     NOT NULL,
    [CompEntryDescIAT]    CHAR (16)     NOT NULL,
    [CompEntryDescPPD]    CHAR (16)     NOT NULL,
    [CpnyFromSetup]       SMALLINT      NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [EMAPTran]            CHAR (1)      NOT NULL,
    [EMAttachment]        CHAR (128)    NOT NULL,
    [EMAutoWrap]          INT           NOT NULL,
    [EMCpnyName]          CHAR (128)    NOT NULL,
    [EMFromAddr]          CHAR (128)    NOT NULL,
    [EMFromName]          CHAR (128)    NOT NULL,
    [EMFromSetup]         SMALLINT      NOT NULL,
    [EMMessageBottom]     SMALLINT      NOT NULL,
    [EMMessageTop]        SMALLINT      NOT NULL,
    [EMNotification]      CHAR (1)      NOT NULL,
    [EMPriority]          INT           NOT NULL,
    [EMReplyToAddr]       CHAR (128)    NOT NULL,
    [EMReplyToName]       CHAR (128)    NOT NULL,
    [EMStubLayout]        CHAR (1)      NOT NULL,
    [EMSubject]           CHAR (128)    NOT NULL,
    [EMTUser1]            CHAR (30)     NOT NULL,
    [EMTUser2]            CHAR (30)     NOT NULL,
    [EMTUser3]            CHAR (30)     NOT NULL,
    [EMTUser4]            CHAR (30)     NOT NULL,
    [EMTUser5]            CHAR (30)     NOT NULL,
    [EMTUser6]            CHAR (30)     NOT NULL,
    [EMTUser7]            CHAR (30)     NOT NULL,
    [EMTUser8]            CHAR (30)     NOT NULL,
    [EMUser1]             CHAR (30)     NOT NULL,
    [EMUser2]             CHAR (30)     NOT NULL,
    [EMUser3]             CHAR (30)     NOT NULL,
    [EMUser4]             CHAR (30)     NOT NULL,
    [EMUser5]             CHAR (30)     NOT NULL,
    [EMUser6]             CHAR (30)     NOT NULL,
    [EMUser7]             CHAR (30)     NOT NULL,
    [EMUser8]             CHAR (30)     NOT NULL,
    [FileFromSetup]       SMALLINT      NOT NULL,
    [FormatID]            CHAR (15)     NOT NULL,
    [HeadTrailID]         CHAR (1)      NOT NULL,
    [LBArchive]           SMALLINT      NOT NULL,
    [LBCommDevice]        CHAR (128)    NOT NULL,
    [LBCommEchoOn]        SMALLINT      NOT NULL,
    [LBCommLocation]      CHAR (128)    NOT NULL,
    [LBCommPhone]         CHAR (20)     NOT NULL,
    [LBCommPXferProto]    SMALLINT      NOT NULL,
    [LBCommTermEmulation] CHAR (1)      NOT NULL,
    [LBCommType]          CHAR (1)      NOT NULL,
    [LBCommUserProg]      CHAR (128)    NOT NULL,
    [LBDelete]            CHAR (1)      NOT NULL,
    [LBFileName]          CHAR (80)     NOT NULL,
    [LBFormatID]          CHAR (15)     NOT NULL,
    [LBFromSetup]         SMALLINT      NOT NULL,
    [LBPath]              CHAR (128)    NOT NULL,
    [LBSuggCustGood]      SMALLINT      NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME NOT NULL,
    [LUpd_Prog]           CHAR (8)      NOT NULL,
    [LUpd_User]           CHAR (10)     NOT NULL,
    [MCB_EBNbrLen]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [MCB_EBNbrPrefix]     CHAR (2)      DEFAULT ('') NOT NULL,
    [MCB_NextEBNbr]       CHAR (10)     DEFAULT ('') NOT NULL,
    [MCB_UseEBNbr]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [Name]                CHAR (30)     NOT NULL,
    [NoteID]              INT           NOT NULL,
    [PathACHScript]       CHAR (128)    NOT NULL,
    [PNDate]              SMALLDATETIME NOT NULL,
    [PNStatus]            CHAR (1)      NOT NULL,
    [PP01]                CHAR (30)     NOT NULL,
    [PP02]                CHAR (30)     NOT NULL,
    [PP03]                CHAR (30)     NOT NULL,
    [PP04]                CHAR (30)     NOT NULL,
    [PPArchive]           SMALLINT      NOT NULL,
    [PPBankAcct]          CHAR (30)     NOT NULL,
    [PPCommDevice]        CHAR (128)    NOT NULL,
    [PPCommEchoOn]        SMALLINT      NOT NULL,
    [PPCommLocation]      CHAR (128)    NOT NULL,
    [PPCommPhone]         CHAR (20)     NOT NULL,
    [PPCommPXferProto]    SMALLINT      NOT NULL,
    [PPCommTermEmulation] CHAR (1)      NOT NULL,
    [PPCommType]          CHAR (1)      NOT NULL,
    [PPCommUserProg]      CHAR (128)    NOT NULL,
    [PPCrLf]              CHAR (1)      NOT NULL,
    [PPDelete]            CHAR (1)      NOT NULL,
    [PPFileName]          CHAR (80)     NOT NULL,
    [PPFillBlock]         CHAR (1)      NOT NULL,
    [PPFormatID]          CHAR (15)     NOT NULL,
    [PPFromSetup]         SMALLINT      NOT NULL,
    [PPHeadTrailID]       CHAR (1)      NOT NULL,
    [PPPath]              CHAR (128)    NOT NULL,
    [SKFuture01]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]          CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]          CHAR (10)     DEFAULT ('') NOT NULL,
    [Sub]                 CHAR (24)     NOT NULL,
    [Test]                CHAR (1)      DEFAULT ('') NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User10]              CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [User9]               CHAR (30)     NOT NULL,
    [W01]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W02]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W03]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W04]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W05]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W06]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W07]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [W08]                 CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyAddr]       CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyAddr2]      CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyCity]       CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyCountry]    CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyID]         CHAR (15)     DEFAULT ('') NOT NULL,
    [WOrdPartyISOCntry]   CHAR (3)      DEFAULT ('') NOT NULL,
    [WOrdPartyName]       CHAR (35)     DEFAULT ('') NOT NULL,
    [WOrdPartyState]      CHAR (3)      DEFAULT ('') NOT NULL,
    [WOrdPartySwift]      CHAR (11)     DEFAULT ('') NOT NULL,
    [WOrdPartyZipPostal]  CHAR (11)     DEFAULT ('') NOT NULL,
    [WTArchive]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTCommType]          CHAR (1)      DEFAULT ('') NOT NULL,
    [WTCommUserProg]      CHAR (128)    DEFAULT ('') NOT NULL,
    [WTCrLf]              CHAR (1)      DEFAULT ('') NOT NULL,
    [WTDelete]            CHAR (1)      DEFAULT ('') NOT NULL,
    [WTFileName]          CHAR (80)     DEFAULT ('') NOT NULL,
    [WTFillBlock]         CHAR (1)      DEFAULT ('') NOT NULL,
    [WTFilterMCBatInBC]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTFilterMultiCury]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTFromSetup]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTHeadTrailID]       CHAR (1)      DEFAULT ('') NOT NULL,
    [WTPath]              CHAR (128)    DEFAULT ('') NOT NULL,
    [WTTest]              CHAR (1)      DEFAULT ('') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [XDDBank0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [Acct] ASC, [Sub] ASC)
);

