CREATE TABLE [dbo].[PJRESSUM] (
    [acct]            CHAR (16)     NOT NULL,
    [act_amount]      FLOAT (53)    NOT NULL,
    [act_end_date]    SMALLDATETIME NOT NULL,
    [act_start_date]  SMALLDATETIME NOT NULL,
    [act_units]       FLOAT (53)    NOT NULL,
    [crtd_datetime]   SMALLDATETIME NOT NULL,
    [crtd_prog]       CHAR (8)      NOT NULL,
    [crtd_user]       CHAR (10)     NOT NULL,
    [eac_amount]      FLOAT (53)    NOT NULL,
    [eac_end_date]    SMALLDATETIME NOT NULL,
    [eac_rate]        FLOAT (53)    NOT NULL,
    [eac_start_date]  SMALLDATETIME NOT NULL,
    [eac_units]       FLOAT (53)    NOT NULL,
    [employee]        CHAR (10)     NOT NULL,
    [lineID]          SMALLINT      NOT NULL,
    [linenbr]         SMALLINT      NOT NULL,
    [lupd_datetime]   SMALLDATETIME NOT NULL,
    [lupd_prog]       CHAR (8)      NOT NULL,
    [lupd_user]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [orig_amount]     FLOAT (53)    NOT NULL,
    [orig_end_date]   SMALLDATETIME NOT NULL,
    [orig_rate]       FLOAT (53)    NOT NULL,
    [orig_start_date] SMALLDATETIME NOT NULL,
    [orig_units]      FLOAT (53)    NOT NULL,
    [pjt_entity]      CHAR (32)     NOT NULL,
    [project]         CHAR (16)     NOT NULL,
    [resource_id]     CHAR (10)     NOT NULL,
    [resource_type]   CHAR (16)     NOT NULL,
    [ss_id01]         CHAR (30)     NOT NULL,
    [ss_id02]         CHAR (30)     NOT NULL,
    [ss_id03]         CHAR (16)     NOT NULL,
    [ss_id04]         CHAR (16)     NOT NULL,
    [ss_id05]         CHAR (4)      NOT NULL,
    [ss_id06]         FLOAT (53)    NOT NULL,
    [ss_id07]         FLOAT (53)    NOT NULL,
    [ss_id08]         SMALLDATETIME NOT NULL,
    [ss_id09]         SMALLDATETIME NOT NULL,
    [ss_id10]         SMALLINT      NOT NULL,
    [subcontractor]   CHAR (10)     NOT NULL,
    [user1]           CHAR (30)     NOT NULL,
    [user2]           CHAR (30)     NOT NULL,
    [user3]           FLOAT (53)    NOT NULL,
    [user4]           FLOAT (53)    NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [pjressum0] PRIMARY KEY NONCLUSTERED ([project] ASC, [pjt_entity] ASC, [acct] ASC, [resource_type] ASC, [employee] ASC, [subcontractor] ASC, [resource_id] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE UNIQUE CLUSTERED INDEX [PJRESSUM1]
    ON [dbo].[PJRESSUM]([project] ASC, [pjt_entity] ASC, [acct] ASC, [lineID] ASC) WITH (FILLFACTOR = 90);

