CREATE TABLE [dbo].[PJPENTEM] (
    [Actual_amt]           FLOAT (53)    NOT NULL,
    [Actual_units]         FLOAT (53)    NOT NULL,
    [Budget_amt]           FLOAT (53)    NOT NULL,
    [Budget_units]         FLOAT (53)    NOT NULL,
    [Comment]              CHAR (50)     NOT NULL,
    [crtd_datetime]        SMALLDATETIME NOT NULL,
    [crtd_prog]            CHAR (8)      NOT NULL,
    [crtd_user]            CHAR (10)     NOT NULL,
    [Date_start]           SMALLDATETIME NOT NULL,
    [Date_end]             SMALLDATETIME NOT NULL,
    [Employee]             CHAR (10)     NOT NULL,
    [lupd_datetime]        SMALLDATETIME NOT NULL,
    [lupd_prog]            CHAR (8)      NOT NULL,
    [lupd_user]            CHAR (10)     NOT NULL,
    [MSPSync]              CHAR (1)      NOT NULL,
    [noteid]               INT           NOT NULL,
    [Pjt_entity]           CHAR (32)     NOT NULL,
    [ProjCury_Actual_amt]  FLOAT (53)    NOT NULL,
    [ProjCury_Budget_amt]  FLOAT (53)    NOT NULL,
    [ProjCury_Revadj_amt]  FLOAT (53)    NOT NULL,
    [ProjCury_Revenue_amt] FLOAT (53)    NOT NULL,
    [ProjCuryEffDate]      SMALLDATETIME NOT NULL,
    [ProjCuryId]           CHAR (4)      NOT NULL,
    [ProjCuryMultiDiv]     CHAR (1)      NOT NULL,
    [ProjCuryRate]         FLOAT (53)    NOT NULL,
    [ProjCuryRateType]     CHAR (6)      NOT NULL,
    [Project]              CHAR (16)     NOT NULL,
    [Revadj_amt]           FLOAT (53)    NOT NULL,
    [Revenue_amt]          FLOAT (53)    NOT NULL,
    [SubTask_Name]         CHAR (50)     NOT NULL,
    [SubTask_UID]          INT           NOT NULL,
    [Tk_id01]              CHAR (30)     NOT NULL,
    [Tk_id02]              CHAR (30)     NOT NULL,
    [Tk_id03]              CHAR (16)     NOT NULL,
    [Tk_id04]              CHAR (16)     NOT NULL,
    [Tk_id05]              CHAR (4)      NOT NULL,
    [Tk_id06]              FLOAT (53)    NOT NULL,
    [Tk_id07]              FLOAT (53)    NOT NULL,
    [Tk_id08]              SMALLDATETIME NOT NULL,
    [Tk_id09]              SMALLDATETIME NOT NULL,
    [Tk_id10]              INT           NOT NULL,
    [User1]                CHAR (30)     NOT NULL,
    [User2]                CHAR (30)     NOT NULL,
    [User3]                FLOAT (53)    NOT NULL,
    [User4]                FLOAT (53)    NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [pjpentem0] PRIMARY KEY CLUSTERED ([Project] ASC, [Pjt_entity] ASC, [Employee] ASC, [SubTask_Name] ASC)
);


GO
CREATE NONCLUSTERED INDEX [pjpentem1]
    ON [dbo].[PJPENTEM]([Employee] ASC);

