CREATE TABLE [dbo].[SlsperQuota] (
    [Bookings]      FLOAT (53)    CONSTRAINT [DF_SlsperQuota_Bookings] DEFAULT ((0)) NOT NULL,
    [BookQuota]     FLOAT (53)    CONSTRAINT [DF_SlsperQuota_BookQuota] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_SlsperQuota_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_SlsperQuota_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_SlsperQuota_Crtd_User] DEFAULT (' ') NOT NULL,
    [EndDate]       SMALLDATETIME CONSTRAINT [DF_SlsperQuota_EndDate] DEFAULT ('01/01/1900') NOT NULL,
    [GrossProfit]   FLOAT (53)    CONSTRAINT [DF_SlsperQuota_GrossProfit] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_SlsperQuota_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_SlsperQuota_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_SlsperQuota_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]        INT           CONSTRAINT [DF_SlsperQuota_NoteID] DEFAULT ((0)) NOT NULL,
    [PerNbr]        CHAR (6)      CONSTRAINT [DF_SlsperQuota_PerNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_SlsperQuota_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_SlsperQuota_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_SlsperQuota_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_SlsperQuota_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_SlsperQuota_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_SlsperQuota_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_SlsperQuota_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_SlsperQuota_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_SlsperQuota_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_SlsperQuota_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_SlsperQuota_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_SlsperQuota_S4Future12] DEFAULT (' ') NOT NULL,
    [Sales]         FLOAT (53)    CONSTRAINT [DF_SlsperQuota_Sales] DEFAULT ((0)) NOT NULL,
    [SalesQuota]    FLOAT (53)    CONSTRAINT [DF_SlsperQuota_SalesQuota] DEFAULT ((0)) NOT NULL,
    [SlsperID]      CHAR (10)     CONSTRAINT [DF_SlsperQuota_SlsperID] DEFAULT (' ') NOT NULL,
    [StartDate]     SMALLDATETIME CONSTRAINT [DF_SlsperQuota_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_SlsperQuota_User1] DEFAULT (' ') NOT NULL,
    [User10]        SMALLDATETIME CONSTRAINT [DF_SlsperQuota_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_SlsperQuota_User2] DEFAULT (' ') NOT NULL,
    [User3]         CHAR (30)     CONSTRAINT [DF_SlsperQuota_User3] DEFAULT (' ') NOT NULL,
    [User4]         CHAR (30)     CONSTRAINT [DF_SlsperQuota_User4] DEFAULT (' ') NOT NULL,
    [User5]         FLOAT (53)    CONSTRAINT [DF_SlsperQuota_User5] DEFAULT ((0)) NOT NULL,
    [User6]         FLOAT (53)    CONSTRAINT [DF_SlsperQuota_User6] DEFAULT ((0)) NOT NULL,
    [User7]         CHAR (10)     CONSTRAINT [DF_SlsperQuota_User7] DEFAULT (' ') NOT NULL,
    [User8]         CHAR (10)     CONSTRAINT [DF_SlsperQuota_User8] DEFAULT (' ') NOT NULL,
    [User9]         SMALLDATETIME CONSTRAINT [DF_SlsperQuota_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [SlsperQuota0] PRIMARY KEY CLUSTERED ([SlsperID] ASC, [PerNbr] ASC) WITH (FILLFACTOR = 90)
);

