CREATE TABLE [dbo].[XDDBatch] (
    [Acct]               CHAR (10)     DEFAULT ('') NOT NULL,
    [AREFTInvoices]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltDiscDate]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltDiscDateD] SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [AREFTFiltDueDate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltDueDateD]  SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [AREFTFiltCM]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltDM]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltFI]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTFiltIN]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTTotal]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BatEFTGrp]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [BatNbr]             CHAR (10)     DEFAULT ('') NOT NULL,
    [BatSeq]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [ComputerName]       CHAR (21)     DEFAULT ('') NOT NULL,
    [CpnyID]             CHAR (10)     DEFAULT ('') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [CuryEffDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [CuryID]             CHAR (4)      DEFAULT ('') NOT NULL,
    [CuryMultDiv]        CHAR (1)      DEFAULT ('') NOT NULL,
    [CuryRate]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRateReciprocal] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRateType]       CHAR (6)      DEFAULT ('') NOT NULL,
    [DepDate]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [EBFileNbr]          CHAR (6)      DEFAULT ('') NOT NULL,
    [EffDate]            SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [FileType]           CHAR (1)      DEFAULT ('') NOT NULL,
    [FormatID]           CHAR (15)     DEFAULT ('') NOT NULL,
    [KeepDelete]         CHAR (1)      DEFAULT ('') NOT NULL,
    [LBPerPost]          CHAR (6)      DEFAULT ('') NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [MCB_SettleDate]     CHAR (20)     DEFAULT ('') NOT NULL,
    [MCB_SameDateOnly]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [Module]             CHAR (2)      DEFAULT ('') NOT NULL,
    [PmtTotal]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture01]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]         CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]         CHAR (10)     DEFAULT ('') NOT NULL,
    [Sub]                CHAR (24)     DEFAULT ('') NOT NULL,
    [User1]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]             CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]              CHAR (30)     DEFAULT ('') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [XDDBatch0] PRIMARY KEY CLUSTERED ([Module] ASC, [BatNbr] ASC, [FileType] ASC, [BatSeq] ASC, [BatEFTGrp] ASC)
);


GO
CREATE NONCLUSTERED INDEX [XDDBatch1]
    ON [dbo].[XDDBatch]([FileType] ASC, [EBFileNbr] ASC);

