CREATE TABLE [dbo].[cftFarmDSetUp] (
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [CuttOff]        FLOAT (53)    NULL,
    [DayVal1]        SMALLINT      NOT NULL,
    [DayVal2]        SMALLINT      NOT NULL,
    [DayVal3]        SMALLINT      NOT NULL,
    [DayVal4]        SMALLINT      NOT NULL,
    [DayVal5]        SMALLINT      NOT NULL,
    [DayVal6]        SMALLINT      NOT NULL,
    [DayVal7]        SMALLINT      NOT NULL,
    [DfltOrderType]  CHAR (2)      NOT NULL,
    [DfltOrderTypeT] CHAR (2)      NOT NULL,
    [DfltPath]       CHAR (120)    NOT NULL,
    [DfltPriority]   CHAR (10)     NOT NULL,
    [LastOrdNbr]     CHAR (10)     NOT NULL,
    [LastBnRef]      CHAR (10)     NOT NULL,
    [LoadTime]       FLOAT (53)    NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [ProjPref]       CHAR (2)      NOT NULL,
    [SetUpId]        CHAR (2)      NOT NULL,
    [StatusDflt]     CHAR (1)      NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          INT           NOT NULL,
    [tstamp]         ROWVERSION    NULL,
    CONSTRAINT [cftFarmDSetup0] PRIMARY KEY CLUSTERED ([SetUpId] ASC) WITH (FILLFACTOR = 90)
);

