CREATE TABLE [dbo].[cft_VFDMed] (
    [Approved_Indications] VARCHAR (MAX) NULL,
    [Address]              VARCHAR (30)  NOT NULL,
    [Caution1]             VARCHAR (MAX) NULL,
    [Caution2]             VARCHAR (MAX) NULL,
    [Caution3]             VARCHAR (MAX) NULL,
    [Caution4]             VARCHAR (MAX) NULL,
    [Caution5]             VARCHAR (MAX) NULL,
    [Caution6]             VARCHAR (MAX) NULL,
    [Caution7]             VARCHAR (MAX) NULL,
    [Caution8]             VARCHAR (MAX) NULL,
    [Caution9]             VARCHAR (MAX) NULL,
    [Caution10]            VARCHAR (MAX) NULL,
    [City]                 VARCHAR (30)  NOT NULL,
    [CombinationFeeding]   VARCHAR (MAX) NULL,
    [Company]              VARCHAR (50)  NOT NULL,
    [Crtd_DateTime]        DATETIME      NOT NULL,
    [Crtd_Prog]            CHAR (8)      NOT NULL,
    [Crtd_User]            CHAR (10)     NOT NULL,
    [Dosage]               VARCHAR (MAX) NOT NULL,
    [Fax]                  VARCHAR (10)  NOT NULL,
    [IDVFDMed]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [InvtID]               VARCHAR (30)  CONSTRAINT [DF_cft_VFDMed_InvtID] DEFAULT ('0') NOT NULL,
    [Lupd_DateTime]        SMALLDATETIME NULL,
    [Lupd_Prog]            CHAR (8)      NULL,
    [Lupd_User]            CHAR (20)     NULL,
    [Name]                 VARCHAR (60)  NOT NULL,
    [NameSelect]           VARCHAR (60)  NOT NULL,
    [Phone]                VARCHAR (10)  NOT NULL,
    [Species]              VARCHAR (15)  NOT NULL,
    [State]                VARCHAR (3)   NOT NULL,
    [WithDrawal]           VARCHAR (MAX) NULL,
    [Zip]                  VARCHAR (10)  NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [cft_VFDMed0] PRIMARY KEY CLUSTERED ([IDVFDMed] ASC) WITH (FILLFACTOR = 100)
);

