CREATE TABLE [dbo].[POProjApprDefer] (
    [Crtd_DateTime] SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]     CHAR (8)      CONSTRAINT [DF_POProjApprDefer_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]     CHAR (10)     CONSTRAINT [DF_POProjApprDefer_Crtd_User] DEFAULT (' ') NOT NULL,
    [DeferUserID]   CHAR (47)     CONSTRAINT [DF_POProjApprDefer_DeferUserID] DEFAULT (' ') NOT NULL,
    [EndDate]       SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_EndDate] DEFAULT ('01/01/1900') NOT NULL,
    [Entered]       CHAR (1)      CONSTRAINT [DF_POProjApprDefer_Entered] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime] SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]     CHAR (8)      CONSTRAINT [DF_POProjApprDefer_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]     CHAR (10)     CONSTRAINT [DF_POProjApprDefer_LUpd_User] DEFAULT (' ') NOT NULL,
    [ProcessedBy]   CHAR (47)     CONSTRAINT [DF_POProjApprDefer_ProcessedBy] DEFAULT (' ') NOT NULL,
    [ProcessedOn]   SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_ProcessedOn] DEFAULT ('01/01/1900') NOT NULL,
    [Project]       CHAR (16)     CONSTRAINT [DF_POProjApprDefer_Project] DEFAULT (' ') NOT NULL,
    [S4Future01]    CHAR (30)     CONSTRAINT [DF_POProjApprDefer_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]    CHAR (30)     CONSTRAINT [DF_POProjApprDefer_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]    FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]    FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]    FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]    FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]    SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]    SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]    INT           CONSTRAINT [DF_POProjApprDefer_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]    INT           CONSTRAINT [DF_POProjApprDefer_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]    CHAR (10)     CONSTRAINT [DF_POProjApprDefer_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]    CHAR (10)     CONSTRAINT [DF_POProjApprDefer_S4Future12] DEFAULT (' ') NOT NULL,
    [StartDate]     SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_StartDate] DEFAULT ('01/01/1900') NOT NULL,
    [Terminated]    CHAR (1)      CONSTRAINT [DF_POProjApprDefer_Terminated] DEFAULT (' ') NOT NULL,
    [User1]         CHAR (30)     CONSTRAINT [DF_POProjApprDefer_User1] DEFAULT (' ') NOT NULL,
    [User2]         CHAR (30)     CONSTRAINT [DF_POProjApprDefer_User2] DEFAULT (' ') NOT NULL,
    [User3]         FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_User3] DEFAULT ((0)) NOT NULL,
    [User4]         FLOAT (53)    CONSTRAINT [DF_POProjApprDefer_User4] DEFAULT ((0)) NOT NULL,
    [User5]         CHAR (10)     CONSTRAINT [DF_POProjApprDefer_User5] DEFAULT (' ') NOT NULL,
    [User6]         CHAR (10)     CONSTRAINT [DF_POProjApprDefer_User6] DEFAULT (' ') NOT NULL,
    [User7]         SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]         SMALLDATETIME CONSTRAINT [DF_POProjApprDefer_User8] DEFAULT ('01/01/1900') NOT NULL,
    [UserID]        CHAR (47)     CONSTRAINT [DF_POProjApprDefer_UserID] DEFAULT (' ') NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [POProjApprDefer0] PRIMARY KEY CLUSTERED ([Project] ASC, [UserID] ASC, [DeferUserID] ASC, [StartDate] ASC) WITH (FILLFACTOR = 90)
);

