CREATE TABLE [dbo].[XDDBatchAREFT] (
    [BatEFTGrp]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [BatNbr]             CHAR (10)     DEFAULT ('') NOT NULL,
    [BatSeq]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [CashAcct]           CHAR (10)     DEFAULT ('') NOT NULL,
    [CashSub]            CHAR (24)     DEFAULT ('') NOT NULL,
    [Crtd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [CustID]             CHAR (15)     DEFAULT ('') NOT NULL,
    [DocType]            CHAR (2)      DEFAULT ('') NOT NULL,
    [EFTAmount]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [EFTDiscAmount]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [EFTEligible]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [EFTEligibleReasons] CHAR (4)      DEFAULT ('') NOT NULL,
    [EFTError]           CHAR (1)      DEFAULT ('') NOT NULL,
    [EFTTerms]           CHAR (2)      DEFAULT ('') NOT NULL,
    [LUpd_DateTime]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]          CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]          CHAR (10)     DEFAULT ('') NOT NULL,
    [PaymentCpnyID]      CHAR (10)     DEFAULT ('') NOT NULL,
    [PmtApplicBatNbr]    CHAR (10)     DEFAULT ('') NOT NULL,
    [PmtApplicRefNbr]    CHAR (10)     DEFAULT ('') NOT NULL,
    [RefNbr]             CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture01]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]         CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]         SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]         INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]         CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]         CHAR (10)     DEFAULT ('') NOT NULL,
    [User1]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]             CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]              FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]              CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]              SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]              CHAR (30)     DEFAULT ('') NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [XDDBatchAREFT0] PRIMARY KEY CLUSTERED ([CustID] ASC, [DocType] ASC, [RefNbr] ASC, [BatNbr] ASC, [BatSeq] ASC, [BatEFTGrp] ASC)
);

