CREATE TABLE [dbo].[BenEmp] (
    [BenId]               CHAR (10)     NOT NULL,
    [BTotWorked]          FLOAT (53)    NOT NULL,
    [BYBegBal]            FLOAT (53)    NOT NULL,
    [BYTDAccr]            FLOAT (53)    NOT NULL,
    [BYTDAvail]           FLOAT (53)    NOT NULL,
    [BYTDUsed]            FLOAT (53)    NOT NULL,
    [BYTDWorked]          FLOAT (53)    NOT NULL,
    [CpnyID]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [CurrAvail]           FLOAT (53)    NOT NULL,
    [CurrBYBegBal]        FLOAT (53)    NOT NULL,
    [CurrBYTDAccr]        FLOAT (53)    NOT NULL,
    [CurrBYTDAvail]       FLOAT (53)    NOT NULL,
    [CurrBYTDUsed]        FLOAT (53)    NOT NULL,
    [CurrBYTDWorked]      FLOAT (53)    NOT NULL,
    [CurrLastAvailDate]   SMALLDATETIME NOT NULL,
    [CurrLastCloseDate]   SMALLDATETIME NOT NULL,
    [CurrLastPayPEndDate] SMALLDATETIME NOT NULL,
    [CurrUsed]            FLOAT (53)    NOT NULL,
    [CurrWorked]          FLOAT (53)    NOT NULL,
    [EmpId]               CHAR (10)     NOT NULL,
    [LastAccrRate]        FLOAT (53)    NOT NULL,
    [LastAvailDate]       SMALLDATETIME NOT NULL,
    [LastCloseDate]       SMALLDATETIME NOT NULL,
    [LastPayPerEndDate]   SMALLDATETIME NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME NOT NULL,
    [LUpd_Prog]           CHAR (8)      NOT NULL,
    [LUpd_User]           CHAR (10)     NOT NULL,
    [MaxCarryOver]        FLOAT (53)    NOT NULL,
    [NoteId]              INT           NOT NULL,
    [S4Future01]          CHAR (30)     NOT NULL,
    [S4Future02]          CHAR (30)     NOT NULL,
    [S4Future03]          FLOAT (53)    NOT NULL,
    [S4Future04]          FLOAT (53)    NOT NULL,
    [S4Future05]          FLOAT (53)    NOT NULL,
    [S4Future06]          FLOAT (53)    NOT NULL,
    [S4Future07]          SMALLDATETIME NOT NULL,
    [S4Future08]          SMALLDATETIME NOT NULL,
    [S4Future09]          INT           NOT NULL,
    [S4Future10]          INT           NOT NULL,
    [S4Future11]          CHAR (10)     NOT NULL,
    [S4Future12]          CHAR (10)     NOT NULL,
    [Status]              CHAR (2)      NOT NULL,
    [TrnsBenId]           CHAR (10)     NOT NULL,
    [TrnsCarryFwdHist]    SMALLINT      NOT NULL,
    [TrnsDate]            SMALLDATETIME NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [BenEmp0] PRIMARY KEY CLUSTERED ([EmpId] ASC, [BenId] ASC) WITH (FILLFACTOR = 90)
);

