CREATE TABLE [dbo].[BRSetup] (
    [Addr1]         CHAR (30)     NOT NULL,
    [Addr2]         CHAR (30)     NOT NULL,
    [AggSubAcct]    CHAR (10)     NOT NULL,
    [City]          CHAR (20)     NOT NULL,
    [Country]       CHAR (3)      NOT NULL,
    [CpnyId]        CHAR (10)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [PerNbr]        CHAR (6)      NOT NULL,
    [Periods]       INT           NOT NULL,
    [FutureC1]      CHAR (30)     NOT NULL,
    [FutureC2]      CHAR (10)     NOT NULL,
    [FutureD1]      SMALLDATETIME NOT NULL,
    [FutureF1]      FLOAT (53)    NOT NULL,
    [FutureI1]      INT           NOT NULL,
    [FutureL1]      SMALLINT      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [Name]          CHAR (30)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [PullAP]        SMALLINT      NOT NULL,
    [PullAR]        SMALLINT      NOT NULL,
    [PullCA]        SMALLINT      NOT NULL,
    [PullGL]        SMALLINT      NOT NULL,
    [PullIN]        SMALLINT      NOT NULL,
    [PullPC]        SMALLINT      NOT NULL,
    [PullPR]        SMALLINT      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [SetupID]       CHAR (4)      NOT NULL,
    [State]         CHAR (3)      NOT NULL,
    [UseAggSub]     SMALLINT      NOT NULL,
    [UserC1]        CHAR (30)     NOT NULL,
    [UserC2]        CHAR (10)     NOT NULL,
    [UserD1]        SMALLDATETIME NOT NULL,
    [UserF1]        FLOAT (53)    NOT NULL,
    [UserI1]        INT           NOT NULL,
    [UserL1]        SMALLINT      NOT NULL,
    [Zip]           CHAR (9)      NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [BRSetup0] PRIMARY KEY CLUSTERED ([CpnyId] ASC) WITH (FILLFACTOR = 90)
);

