CREATE TABLE [dbo].[EarnType] (
    [Acct]            CHAR (10)     NOT NULL,
    [BenClassId]      CHAR (10)     NOT NULL,
    [BoxLet]          CHAR (2)      NOT NULL,
    [BoxNbr]          CHAR (3)      NOT NULL,
    [CpnyID]          CHAR (10)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [DefrdComp]       SMALLINT      NOT NULL,
    [Descr]           CHAR (30)     NOT NULL,
    [ETType]          CHAR (1)      NOT NULL,
    [ExcFromDispEarn] SMALLINT      NOT NULL,
    [Id]              CHAR (10)     NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [NetPay]          SMALLINT      NOT NULL,
    [NoteId]          INT           NOT NULL,
    [PayRateMult]     FLOAT (53)    NOT NULL,
    [Pension]         SMALLINT      NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [Section457]      SMALLINT      NOT NULL,
    [Sub]             CHAR (24)     NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [EarnType0] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [EarnType1]
    ON [dbo].[EarnType]([BenClassId] ASC) WITH (FILLFACTOR = 90);

