CREATE TABLE [dbo].[RQReqDet] (
    [Acct]                 CHAR (10)     NOT NULL,
    [AddlCostPct]          FLOAT (53)    NOT NULL,
    [AllocCntr]            SMALLINT      NOT NULL,
    [AlternateID]          CHAR (30)     NOT NULL,
    [AltIDType]            CHAR (1)      NOT NULL,
    [AppvLevObt]           CHAR (2)      NOT NULL,
    [AppvLevReq]           CHAR (2)      NOT NULL,
    [BlktLineID]           SMALLINT      NOT NULL,
    [BlktLineRef]          CHAR (5)      NOT NULL,
    [Budgeted]             CHAR (1)      NOT NULL,
    [Buyer]                CHAR (10)     NOT NULL,
    [CatalogInfo]          CHAR (60)     NOT NULL,
    [CnvFact]              FLOAT (53)    NOT NULL,
    [ComitAmt]             FLOAT (53)    NOT NULL,
    [CommitAmtLeft]        FLOAT (53)    NOT NULL,
    [CostReceived]         FLOAT (53)    NOT NULL,
    [CostReturned]         FLOAT (53)    NOT NULL,
    [CostVouched]          FLOAT (53)    NOT NULL,
    [CpnyID]               CHAR (10)     NOT NULL,
    [crtd_datetime]        SMALLDATETIME NOT NULL,
    [crtd_prog]            CHAR (8)      NOT NULL,
    [crtd_user]            CHAR (10)     NOT NULL,
    [CuryComitAmt]         FLOAT (53)    NOT NULL,
    [CuryCostReceived]     FLOAT (53)    NOT NULL,
    [CuryCostReturned]     FLOAT (53)    NOT NULL,
    [CuryCostVouched]      FLOAT (53)    NOT NULL,
    [CuryExtCost]          FLOAT (53)    NOT NULL,
    [CuryID]               CHAR (4)      NOT NULL,
    [CuryMultDiv]          CHAR (1)      NOT NULL,
    [CuryRate]             FLOAT (53)    NOT NULL,
    [CuryTaxAmt00]         FLOAT (53)    NOT NULL,
    [CuryTaxAmt01]         FLOAT (53)    NOT NULL,
    [CuryTaxAmt02]         FLOAT (53)    NOT NULL,
    [CuryTaxAmt03]         FLOAT (53)    NOT NULL,
    [CuryTxblAmt00]        FLOAT (53)    NOT NULL,
    [CuryTxblAmt01]        FLOAT (53)    NOT NULL,
    [CuryTxblAmt02]        FLOAT (53)    NOT NULL,
    [CuryTxblAmt03]        FLOAT (53)    NOT NULL,
    [CuryUnitCost]         FLOAT (53)    NOT NULL,
    [Dept]                 CHAR (10)     NOT NULL,
    [Descr]                CHAR (60)     NOT NULL,
    [ExtCost]              FLOAT (53)    NOT NULL,
    [ExtWeight]            FLOAT (53)    NOT NULL,
    [FlatRateLineNbr]      SMALLINT      NOT NULL,
    [InclForecastUsageClc] SMALLINT      NOT NULL,
    [InvtID]               CHAR (30)     NOT NULL,
    [IRInclLeadTime]       SMALLINT      NOT NULL,
    [ItemLineID]           SMALLINT      NOT NULL,
    [ItemLineRef]          CHAR (4)      NOT NULL,
    [ItemReqNbr]           CHAR (10)     NOT NULL,
    [KitUnExpld]           FLOAT (53)    NOT NULL,
    [Labor_Class_CD]       CHAR (4)      NOT NULL,
    [LineKey]              CHAR (17)     NOT NULL,
    [LineNbr]              SMALLINT      NOT NULL,
    [lupd_datetime]        SMALLDATETIME NOT NULL,
    [lupd_prog]            CHAR (8)      NOT NULL,
    [lupd_user]            CHAR (10)     NOT NULL,
    [MaterialType]         CHAR (10)     NOT NULL,
    [NoteID]               INT           NOT NULL,
    [OpenLine]             SMALLINT      NOT NULL,
    [OrigPOLine]           SMALLINT      NOT NULL,
    [OrigPOSeq]            CHAR (1)      NOT NULL,
    [PC_Flag]              CHAR (1)      NOT NULL,
    [PC_ID]                CHAR (20)     NOT NULL,
    [PC_Status]            CHAR (1)      NOT NULL,
    [PolicyLevObt]         CHAR (2)      NOT NULL,
    [PolicyLevReq]         CHAR (2)      NOT NULL,
    [PrefVendID]           CHAR (15)     NOT NULL,
    [Project]              CHAR (16)     NOT NULL,
    [PromiseDate]          SMALLDATETIME NOT NULL,
    [PurchaseFor]          CHAR (2)      NOT NULL,
    [Qty]                  FLOAT (53)    NOT NULL,
    [QtyRcvd]              FLOAT (53)    NOT NULL,
    [QtyReturned]          FLOAT (53)    NOT NULL,
    [QtyVouched]           FLOAT (53)    NOT NULL,
    [RcptPctAct]           CHAR (1)      NOT NULL,
    [RcptPctMax]           FLOAT (53)    NOT NULL,
    [RcptPctMin]           FLOAT (53)    NOT NULL,
    [RcptStage]            CHAR (1)      NOT NULL,
    [ReasonCD]             CHAR (6)      NOT NULL,
    [ReqCntr]              CHAR (2)      NOT NULL,
    [ReqNbr]               CHAR (10)     NOT NULL,
    [RequiredDate]         SMALLDATETIME NOT NULL,
    [S4Future1]            CHAR (30)     NOT NULL,
    [S4Future2]            CHAR (30)     NOT NULL,
    [S4Future3]            FLOAT (53)    NOT NULL,
    [S4Future4]            FLOAT (53)    NOT NULL,
    [S4Future5]            FLOAT (53)    NOT NULL,
    [S4Future6]            FLOAT (53)    NOT NULL,
    [S4Future7]            SMALLDATETIME NOT NULL,
    [S4Future8]            SMALLDATETIME NOT NULL,
    [S4Future9]            INT           NOT NULL,
    [S4Future10]           INT           NOT NULL,
    [S4Future11]           CHAR (10)     NOT NULL,
    [S4Future12]           CHAR (10)     NOT NULL,
    [SeqNbr]               CHAR (4)      NOT NULL,
    [ShelfLife]            SMALLINT      NOT NULL,
    [ShipAddr1]            CHAR (60)     NOT NULL,
    [ShipAddr2]            CHAR (60)     NOT NULL,
    [ShipAddrID]           CHAR (10)     NOT NULL,
    [ShipCity]             CHAR (30)     NOT NULL,
    [ShipCountry]          CHAR (3)      NOT NULL,
    [ShipFrom]             CHAR (20)     NOT NULL,
    [ShipName]             CHAR (60)     NOT NULL,
    [ShipState]            CHAR (3)      NOT NULL,
    [ShipViaID]            CHAR (20)     NOT NULL,
    [ShipZip]              CHAR (10)     NOT NULL,
    [SiteID]               CHAR (10)     NOT NULL,
    [SOLineRef]            CHAR (5)      NOT NULL,
    [SOOrdNbr]             CHAR (15)     NOT NULL,
    [SOSchedRef]           CHAR (5)      NOT NULL,
    [Status]               CHAR (2)      NOT NULL,
    [StepNbr]              SMALLINT      NOT NULL,
    [Sub]                  CHAR (24)     NOT NULL,
    [SupplrItem1]          CHAR (20)     NOT NULL,
    [SvcContractID]        CHAR (10)     NOT NULL,
    [SvcLineNbr]           SMALLINT      NOT NULL,
    [Task]                 CHAR (32)     NOT NULL,
    [TaxAmt00]             FLOAT (53)    NOT NULL,
    [TaxAmt01]             FLOAT (53)    NOT NULL,
    [TaxAmt02]             FLOAT (53)    NOT NULL,
    [TaxAmt03]             FLOAT (53)    NOT NULL,
    [TaxCalced]            CHAR (1)      NOT NULL,
    [TaxCat]               CHAR (10)     NOT NULL,
    [TaxID00]              CHAR (10)     NOT NULL,
    [TaxID01]              CHAR (10)     NOT NULL,
    [TaxID02]              CHAR (10)     NOT NULL,
    [TaxID03]              CHAR (10)     NOT NULL,
    [TaxIDDflt]            CHAR (10)     NOT NULL,
    [Transfer]             CHAR (1)      NOT NULL,
    [TxblAmt00]            FLOAT (53)    NOT NULL,
    [TxblAmt01]            FLOAT (53)    NOT NULL,
    [TxblAmt02]            FLOAT (53)    NOT NULL,
    [TxblAmt03]            FLOAT (53)    NOT NULL,
    [Unit]                 CHAR (6)      NOT NULL,
    [UnitCost]             FLOAT (53)    NOT NULL,
    [UnitMultDiv]          CHAR (1)      NOT NULL,
    [UnitWeight]           FLOAT (53)    NOT NULL,
    [User1]                CHAR (30)     NOT NULL,
    [User2]                CHAR (30)     NOT NULL,
    [User3]                FLOAT (53)    NOT NULL,
    [User4]                FLOAT (53)    NOT NULL,
    [User5]                CHAR (10)     NOT NULL,
    [User6]                CHAR (10)     NOT NULL,
    [User7]                SMALLDATETIME NOT NULL,
    [User8]                SMALLDATETIME NOT NULL,
    [VendItemID]           CHAR (30)     NOT NULL,
    [VouchStage]           CHAR (1)      NOT NULL,
    [WOBOMSeq]             SMALLINT      NOT NULL,
    [WOCostType]           CHAR (2)      NOT NULL,
    [WONbr]                CHAR (10)     NOT NULL,
    [WOStepNbr]            SMALLINT      NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [RQReqDet1]
    ON [dbo].[RQReqDet]([ReqNbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RQReqDet2]
    ON [dbo].[RQReqDet]([Status] ASC, [ReqNbr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RQReqDet3]
    ON [dbo].[RQReqDet]([ReqNbr] ASC, [InvtID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RQReqDet4]
    ON [dbo].[RQReqDet]([ReqNbr] ASC, [SeqNbr] ASC, [ReqCntr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [RQReqDet5]
    ON [dbo].[RQReqDet]([Project] ASC, [Task] ASC, [ReqNbr] ASC, [LineNbr] ASC, [SeqNbr] ASC, [ReqCntr] ASC) WITH (FILLFACTOR = 90);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RQReqDet0]
    ON [dbo].[RQReqDet]([ReqNbr] ASC, [ReqCntr] ASC, [LineNbr] ASC);

