CREATE TABLE [dbo].[EmpEDD] (
    [BodyText]          CHAR (255) NOT NULL,
    [EmpID]             CHAR (10)  NOT NULL,
    [DeliveryMethod]    CHAR (1)   NOT NULL,
    [DocsDeliveredNbr]  CHAR (1)   NOT NULL,
    [DocType]           CHAR (2)   NOT NULL,
    [EDD]               CHAR (1)   NOT NULL,
    [EDDEmail]          CHAR (80)  NOT NULL,
    [EDDFax]            CHAR (10)  NOT NULL,
    [EDDFaxPrefix]      CHAR (15)  NOT NULL,
    [EDDFaxUseAreaCode] SMALLINT   NOT NULL,
    [EmailFileType]     CHAR (1)   NOT NULL,
    [FaxComment]        CHAR (1)   NOT NULL,
    [FaxCover]          CHAR (1)   NOT NULL,
    [FaxReceiverName]   CHAR (60)  NOT NULL,
    [FaxRecycle]        CHAR (1)   NOT NULL,
    [FaxReply]          CHAR (1)   NOT NULL,
    [FaxReview]         CHAR (1)   NOT NULL,
    [FaxSenderName]     CHAR (60)  NOT NULL,
    [FaxSenderNbr]      CHAR (10)  NOT NULL,
    [FaxUrgent]         CHAR (1)   NOT NULL,
    [NoteId]            INT        NOT NULL,
    [NotifyOptions]     CHAR (1)   NOT NULL,
    [PrintOption]       CHAR (1)   NOT NULL,
    [Priority]          CHAR (1)   NOT NULL,
    [RequestorsEmail]   CHAR (80)  NOT NULL,
    [SendersEmail]      CHAR (80)  NOT NULL,
    [SubjectText]       CHAR (80)  NOT NULL,
    [tstamp]            ROWVERSION NOT NULL,
    CONSTRAINT [EmpEDD0] PRIMARY KEY CLUSTERED ([EmpID] ASC, [DocType] ASC)
);

