CREATE TABLE [dbo].[DocTerms] (
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DocType]       CHAR (2)      NOT NULL,
    [InstallAmt]    FLOAT (53)    NOT NULL,
    [InstallDate]   SMALLDATETIME NOT NULL,
    [InstallNbr]    SMALLINT      NOT NULL,
    [LineId]        INT           NOT NULL,
    [LineNbr]       SMALLINT      NOT NULL,
    [LineRef]       CHAR (5)      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NbrDays]       SMALLINT      NOT NULL,
    [NoteID]        INT           NOT NULL,
    [RefNbr]        CHAR (10)     NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [DocTerms0] PRIMARY KEY CLUSTERED ([DocType] ASC, [RefNbr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90)
);

