CREATE TABLE [dbo].[ED810HeaderExt] (
    [AcctNbr]         CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_AcctNbr] DEFAULT (' ') NOT NULL,
    [AgreeNbr]        CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_AgreeNbr] DEFAULT (' ') NOT NULL,
    [AirBillNbr]      CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_AirBillNbr] DEFAULT (' ') NOT NULL,
    [ArrivalDate]     SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_ArrivalDate] DEFAULT ('01/01/1900') NOT NULL,
    [BidNbr]          CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_BidNbr] DEFAULT (' ') NOT NULL,
    [BillToAdd1]      CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_BillToAdd1] DEFAULT (' ') NOT NULL,
    [BillToAdd2]      CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_BillToAdd2] DEFAULT (' ') NOT NULL,
    [BillToCity]      CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_BillToCity] DEFAULT (' ') NOT NULL,
    [BillToCountry]   CHAR (3)      CONSTRAINT [DF_ED810HeaderExt_BillToCountry] DEFAULT (' ') NOT NULL,
    [BillToName]      CHAR (60)     CONSTRAINT [DF_ED810HeaderExt_BillToName] DEFAULT (' ') NOT NULL,
    [BillToName2]     CHAR (60)     CONSTRAINT [DF_ED810HeaderExt_BillToName2] DEFAULT (' ') NOT NULL,
    [BillToNbr]       CHAR (80)     CONSTRAINT [DF_ED810HeaderExt_BillToNbr] DEFAULT (' ') NOT NULL,
    [BillToState]     CHAR (2)      CONSTRAINT [DF_ED810HeaderExt_BillToState] DEFAULT (' ') NOT NULL,
    [BillToZip]       CHAR (15)     CONSTRAINT [DF_ED810HeaderExt_BillToZip] DEFAULT (' ') NOT NULL,
    [CancelDate]      SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_CancelDate] DEFAULT ('01/01/1900') NOT NULL,
    [CpnyID]          CHAR (10)     CONSTRAINT [DF_ED810HeaderExt_CpnyID] DEFAULT (' ') NOT NULL,
    [CrossDock]       CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_CrossDock] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      CONSTRAINT [DF_ED810HeaderExt_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     CONSTRAINT [DF_ED810HeaderExt_Crtd_User] DEFAULT (' ') NOT NULL,
    [DeliveryDate]    SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_DeliveryDate] DEFAULT ('01/01/1900') NOT NULL,
    [DeptNbr]         CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_DeptNbr] DEFAULT (' ') NOT NULL,
    [DistributorNbr]  CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_DistributorNbr] DEFAULT (' ') NOT NULL,
    [EDIInvID]        CHAR (10)     CONSTRAINT [DF_ED810HeaderExt_EDIInvID] DEFAULT (' ') NOT NULL,
    [EffDate]         SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_EffDate] DEFAULT ('01/01/1900') NOT NULL,
    [EndCustPODate]   SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_EndCustPODate] DEFAULT ('01/01/1900') NOT NULL,
    [EndCustPONbr]    CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_EndCustPONbr] DEFAULT (' ') NOT NULL,
    [EndCustSONbr]    CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_EndCustSONbr] DEFAULT (' ') NOT NULL,
    [EquipmentNbr]    CHAR (20)     CONSTRAINT [DF_ED810HeaderExt_EquipmentNbr] DEFAULT (' ') NOT NULL,
    [ExpirDate]       SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_ExpirDate] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_DateTime]   SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]       CHAR (8)      CONSTRAINT [DF_ED810HeaderExt_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]       CHAR (10)     CONSTRAINT [DF_ED810HeaderExt_Lupd_User] DEFAULT (' ') NOT NULL,
    [PromoEndDate]    SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_PromoEndDate] DEFAULT ('01/01/1900') NOT NULL,
    [PromoNbr]        CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_PromoNbr] DEFAULT (' ') NOT NULL,
    [PromoStartDate]  SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_PromoStartDate] DEFAULT ('01/01/1900') NOT NULL,
    [QuoteNbr]        CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_QuoteNbr] DEFAULT (' ') NOT NULL,
    [ShipDate]        SMALLDATETIME CONSTRAINT [DF_ED810HeaderExt_ShipDate] DEFAULT ('01/01/1900') NOT NULL,
    [ShipFromAdd1]    CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_ShipFromAdd1] DEFAULT (' ') NOT NULL,
    [ShipFromAdd2]    CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_ShipFromAdd2] DEFAULT (' ') NOT NULL,
    [ShipFromCity]    CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_ShipFromCity] DEFAULT (' ') NOT NULL,
    [ShipFromCountry] CHAR (3)      CONSTRAINT [DF_ED810HeaderExt_ShipFromCountry] DEFAULT (' ') NOT NULL,
    [ShipFromName]    CHAR (60)     CONSTRAINT [DF_ED810HeaderExt_ShipFromName] DEFAULT (' ') NOT NULL,
    [ShipFromNbr]     CHAR (80)     CONSTRAINT [DF_ED810HeaderExt_ShipFromNbr] DEFAULT (' ') NOT NULL,
    [ShipFromState]   CHAR (2)      CONSTRAINT [DF_ED810HeaderExt_ShipFromState] DEFAULT (' ') NOT NULL,
    [ShipFromZip]     CHAR (15)     CONSTRAINT [DF_ED810HeaderExt_ShipFromZip] DEFAULT (' ') NOT NULL,
    [ShipToAdd1]      CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_ShipToAdd1] DEFAULT (' ') NOT NULL,
    [ShipToAdd2]      CHAR (55)     CONSTRAINT [DF_ED810HeaderExt_ShipToAdd2] DEFAULT (' ') NOT NULL,
    [ShipToCity]      CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_ShipToCity] DEFAULT (' ') NOT NULL,
    [ShipToCountry]   CHAR (3)      CONSTRAINT [DF_ED810HeaderExt_ShipToCountry] DEFAULT (' ') NOT NULL,
    [ShipToName]      CHAR (60)     CONSTRAINT [DF_ED810HeaderExt_ShipToName] DEFAULT (' ') NOT NULL,
    [ShipToName2]     CHAR (60)     CONSTRAINT [DF_ED810HeaderExt_ShipToName2] DEFAULT (' ') NOT NULL,
    [ShipToNbr]       CHAR (80)     CONSTRAINT [DF_ED810HeaderExt_ShipToNbr] DEFAULT (' ') NOT NULL,
    [ShipToState]     CHAR (2)      CONSTRAINT [DF_ED810HeaderExt_ShipToState] DEFAULT (' ') NOT NULL,
    [ShipToZip]       CHAR (15)     CONSTRAINT [DF_ED810HeaderExt_ShipToZip] DEFAULT (' ') NOT NULL,
    [TrackingNbr]     CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_TrackingNbr] DEFAULT (' ') NOT NULL,
    [WONbr]           CHAR (30)     CONSTRAINT [DF_ED810HeaderExt_WONbr] DEFAULT (' ') NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [ED810HeaderExt0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [EDIInvID] ASC) WITH (FILLFACTOR = 90)
);

