CREATE TABLE [dbo].[PJRESTIM] (
    [acct]          CHAR (16)     NOT NULL,
    [act_amount]    FLOAT (53)    NOT NULL,
    [act_units]     FLOAT (53)    NOT NULL,
    [crtd_datetime] SMALLDATETIME NOT NULL,
    [crtd_prog]     CHAR (8)      NOT NULL,
    [crtd_user]     CHAR (10)     NOT NULL,
    [eac_amount]    FLOAT (53)    NOT NULL,
    [eac_rate]      FLOAT (53)    NOT NULL,
    [eac_units]     FLOAT (53)    NOT NULL,
    [fiscalno]      CHAR (6)      NOT NULL,
    [fsyear_num]    CHAR (4)      NOT NULL,
    [lineID]        SMALLINT      NOT NULL,
    [lupd_datetime] SMALLDATETIME NOT NULL,
    [lupd_prog]     CHAR (8)      NOT NULL,
    [lupd_user]     CHAR (10)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [orig_amount]   FLOAT (53)    NOT NULL,
    [orig_rate]     FLOAT (53)    NOT NULL,
    [orig_units]    FLOAT (53)    NOT NULL,
    [pjt_entity]    CHAR (32)     NOT NULL,
    [project]       CHAR (16)     NOT NULL,
    [st_id01]       CHAR (30)     NOT NULL,
    [st_id02]       CHAR (30)     NOT NULL,
    [st_id03]       CHAR (16)     NOT NULL,
    [st_id04]       CHAR (16)     NOT NULL,
    [st_id05]       CHAR (4)      NOT NULL,
    [st_id06]       FLOAT (53)    NOT NULL,
    [st_id07]       FLOAT (53)    NOT NULL,
    [st_id08]       SMALLDATETIME NOT NULL,
    [st_id09]       SMALLDATETIME NOT NULL,
    [st_id10]       SMALLINT      NOT NULL,
    [user1]         CHAR (30)     NOT NULL,
    [user2]         CHAR (30)     NOT NULL,
    [user3]         FLOAT (53)    NOT NULL,
    [user4]         FLOAT (53)    NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [pjrestim0] PRIMARY KEY CLUSTERED ([project] ASC, [pjt_entity] ASC, [acct] ASC, [lineID] ASC, [fiscalno] ASC) WITH (FILLFACTOR = 90)
);

