CREATE TABLE [dbo].[BMSetup] (
    [AutoRef]              SMALLINT      CONSTRAINT [DF_BMSetup_AutoRef] DEFAULT ((0)) NOT NULL,
    [BOMSeqAssign]         SMALLINT      CONSTRAINT [DF_BMSetup_BOMSeqAssign] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME CONSTRAINT [DF_BMSetup_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      CONSTRAINT [DF_BMSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]            CHAR (10)     CONSTRAINT [DF_BMSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [CstRollOffVarAcct]    CHAR (10)     CONSTRAINT [DF_BMSetup_CstRollOffVarAcct] DEFAULT (' ') NOT NULL,
    [CstRollOffVarSub]     CHAR (24)     CONSTRAINT [DF_BMSetup_CstRollOffVarSub] DEFAULT (' ') NOT NULL,
    [DecPlHrs]             SMALLINT      CONSTRAINT [DF_BMSetup_DecPlHrs] DEFAULT ((0)) NOT NULL,
    [DfltDirectLbrAC]      CHAR (16)     CONSTRAINT [DF_BMSetup_DfltDirectLbrAC] DEFAULT (' ') NOT NULL,
    [DfltDirectMtlAC]      CHAR (16)     CONSTRAINT [DF_BMSetup_DfltDirectMtlAC] DEFAULT (' ') NOT NULL,
    [DfltDirectOtherAC]    CHAR (16)     CONSTRAINT [DF_BMSetup_DfltDirectOtherAC] DEFAULT (' ') NOT NULL,
    [DfltOvhLbrFixedAC]    CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhLbrFixedAC] DEFAULT (' ') NOT NULL,
    [DfltOvhLbrFixedRate]  FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhLbrFixedRate] DEFAULT ((0)) NOT NULL,
    [DfltOvhLbrVarAC]      CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhLbrVarAC] DEFAULT (' ') NOT NULL,
    [DfltOvhLbrVarRate]    FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhLbrVarRate] DEFAULT ((0)) NOT NULL,
    [DfltOvhMachFixedAC]   CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhMachFixedAC] DEFAULT (' ') NOT NULL,
    [DfltOvhMachFixedRate] FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhMachFixedRate] DEFAULT ((0)) NOT NULL,
    [DfltOvhMachVarAC]     CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhMachVarAC] DEFAULT (' ') NOT NULL,
    [DfltOvhMachVarRate]   FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhMachVarRate] DEFAULT ((0)) NOT NULL,
    [DfltOvhMtlFixedAC]    CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhMtlFixedAC] DEFAULT (' ') NOT NULL,
    [DfltOvhMtlFixedRate]  FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhMtlFixedRate] DEFAULT ((0)) NOT NULL,
    [DfltOvhMtlVarAC]      CHAR (16)     CONSTRAINT [DF_BMSetup_DfltOvhMtlVarAC] DEFAULT (' ') NOT NULL,
    [DfltOvhMtlVarRate]    FLOAT (53)    CONSTRAINT [DF_BMSetup_DfltOvhMtlVarRate] DEFAULT ((0)) NOT NULL,
    [GlbSiteID]            CHAR (10)     CONSTRAINT [DF_BMSetup_GlbSiteID] DEFAULT (' ') NOT NULL,
    [LastRefNbr]           CHAR (10)     CONSTRAINT [DF_BMSetup_LastRefNbr] DEFAULT (' ') NOT NULL,
    [LbrACOvhSource]       CHAR (1)      CONSTRAINT [DF_BMSetup_LbrACOvhSource] DEFAULT (' ') NOT NULL,
    [LbrDirOffAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_LbrDirOffAcct] DEFAULT (' ') NOT NULL,
    [LbrDirOffSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_LbrDirOffSub] DEFAULT (' ') NOT NULL,
    [LbrDirScrapVarAcct]   CHAR (10)     CONSTRAINT [DF_BMSetup_LbrDirScrapVarAcct] DEFAULT (' ') NOT NULL,
    [LbrDirScrapVarSub]    CHAR (24)     CONSTRAINT [DF_BMSetup_LbrDirScrapVarSub] DEFAULT (' ') NOT NULL,
    [LbrDirVarAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_LbrDirVarAcct] DEFAULT (' ') NOT NULL,
    [LbrDirVarSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_LbrDirVarSub] DEFAULT (' ') NOT NULL,
    [LbrOvhOffAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_LbrOvhOffAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhOffSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_LbrOvhOffSub] DEFAULT (' ') NOT NULL,
    [LbrOvhRatePct]        CHAR (1)      CONSTRAINT [DF_BMSetup_LbrOvhRatePct] DEFAULT (' ') NOT NULL,
    [LbrOvhScrapVarAcct]   CHAR (10)     CONSTRAINT [DF_BMSetup_LbrOvhScrapVarAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhScrapVarSub]    CHAR (24)     CONSTRAINT [DF_BMSetup_LbrOvhScrapVarSub] DEFAULT (' ') NOT NULL,
    [LbrOvhVarAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_LbrOvhVarAcct] DEFAULT (' ') NOT NULL,
    [LbrOvhVarSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_LbrOvhVarSub] DEFAULT (' ') NOT NULL,
    [LowLevelFlag]         SMALLINT      CONSTRAINT [DF_BMSetup_LowLevelFlag] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME CONSTRAINT [DF_BMSetup_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      CONSTRAINT [DF_BMSetup_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]            CHAR (10)     CONSTRAINT [DF_BMSetup_LUpd_User] DEFAULT (' ') NOT NULL,
    [MachOvhOffAcct]       CHAR (10)     CONSTRAINT [DF_BMSetup_MachOvhOffAcct] DEFAULT (' ') NOT NULL,
    [MachOvhOffSub]        CHAR (24)     CONSTRAINT [DF_BMSetup_MachOvhOffSub] DEFAULT (' ') NOT NULL,
    [MachOvhScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_BMSetup_MachOvhScrapVarAcct] DEFAULT (' ') NOT NULL,
    [MachOvhScrapVarSub]   CHAR (24)     CONSTRAINT [DF_BMSetup_MachOvhScrapVarSub] DEFAULT (' ') NOT NULL,
    [MachOvhVarAcct]       CHAR (10)     CONSTRAINT [DF_BMSetup_MachOvhVarAcct] DEFAULT (' ') NOT NULL,
    [MachOvhVarSub]        CHAR (24)     CONSTRAINT [DF_BMSetup_MachOvhVarSub] DEFAULT (' ') NOT NULL,
    [MatlDirScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_BMSetup_MatlDirScrapVarAcct] DEFAULT (' ') NOT NULL,
    [MatlDirScrapVarSub]   CHAR (24)     CONSTRAINT [DF_BMSetup_MatlDirScrapVarSub] DEFAULT (' ') NOT NULL,
    [MatlDirVarAcct]       CHAR (10)     CONSTRAINT [DF_BMSetup_MatlDirVarAcct] DEFAULT (' ') NOT NULL,
    [MatlDirVarSub]        CHAR (24)     CONSTRAINT [DF_BMSetup_MatlDirVarSub] DEFAULT (' ') NOT NULL,
    [MatlOvhCalc]          CHAR (1)      CONSTRAINT [DF_BMSetup_MatlOvhCalc] DEFAULT (' ') NOT NULL,
    [MatlOvhOffAcct]       CHAR (10)     CONSTRAINT [DF_BMSetup_MatlOvhOffAcct] DEFAULT (' ') NOT NULL,
    [MatlOvhOffSub]        CHAR (24)     CONSTRAINT [DF_BMSetup_MatlOvhOffSub] DEFAULT (' ') NOT NULL,
    [MatlOvhRatePct]       CHAR (1)      CONSTRAINT [DF_BMSetup_MatlOvhRatePct] DEFAULT (' ') NOT NULL,
    [MatlOvhScrapVarAcct]  CHAR (10)     CONSTRAINT [DF_BMSetup_MatlOvhScrapVarAcct] DEFAULT (' ') NOT NULL,
    [MatlOvhScrapVarSub]   CHAR (24)     CONSTRAINT [DF_BMSetup_MatlOvhScrapVarSub] DEFAULT (' ') NOT NULL,
    [MatlOvhVarAcct]       CHAR (10)     CONSTRAINT [DF_BMSetup_MatlOvhVarAcct] DEFAULT (' ') NOT NULL,
    [MatlOvhVarSub]        CHAR (24)     CONSTRAINT [DF_BMSetup_MatlOvhVarSub] DEFAULT (' ') NOT NULL,
    [MCTypeBusFlg]         CHAR (1)      CONSTRAINT [DF_BMSetup_MCTypeBusFlg] DEFAULT (' ') NOT NULL,
    [NoteID]               INT           CONSTRAINT [DF_BMSetup_NoteID] DEFAULT ((0)) NOT NULL,
    [OthDirOffAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_OthDirOffAcct] DEFAULT (' ') NOT NULL,
    [OthDirOffSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_OthDirOffSub] DEFAULT (' ') NOT NULL,
    [OthDirScrapVarAcct]   CHAR (10)     CONSTRAINT [DF_BMSetup_OthDirScrapVarAcct] DEFAULT (' ') NOT NULL,
    [OthDirScrapVarSub]    CHAR (24)     CONSTRAINT [DF_BMSetup_OthDirScrapVarSub] DEFAULT (' ') NOT NULL,
    [OthDirVarAcct]        CHAR (10)     CONSTRAINT [DF_BMSetup_OthDirVarAcct] DEFAULT (' ') NOT NULL,
    [OthDirVarSub]         CHAR (24)     CONSTRAINT [DF_BMSetup_OthDirVarSub] DEFAULT (' ') NOT NULL,
    [PerNbr]               CHAR (6)      CONSTRAINT [DF_BMSetup_PerNbr] DEFAULT (' ') NOT NULL,
    [PerRetDoc]            SMALLINT      CONSTRAINT [DF_BMSetup_PerRetDoc] DEFAULT ((0)) NOT NULL,
    [RetObsComp]           SMALLINT      CONSTRAINT [DF_BMSetup_RetObsComp] DEFAULT ((0)) NOT NULL,
    [RtgRptOpt]            SMALLINT      CONSTRAINT [DF_BMSetup_RtgRptOpt] DEFAULT ((0)) NOT NULL,
    [RtgSeqAssign]         SMALLINT      CONSTRAINT [DF_BMSetup_RtgSeqAssign] DEFAULT ((0)) NOT NULL,
    [S4Future01]           CHAR (30)     CONSTRAINT [DF_BMSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     CONSTRAINT [DF_BMSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    CONSTRAINT [DF_BMSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    CONSTRAINT [DF_BMSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    CONSTRAINT [DF_BMSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    CONSTRAINT [DF_BMSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME CONSTRAINT [DF_BMSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME CONSTRAINT [DF_BMSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           CONSTRAINT [DF_BMSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           CONSTRAINT [DF_BMSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     CONSTRAINT [DF_BMSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     CONSTRAINT [DF_BMSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [SetupID]              CHAR (2)      CONSTRAINT [DF_BMSetup_SetupID] DEFAULT (' ') NOT NULL,
    [SiteBOM]              SMALLINT      CONSTRAINT [DF_BMSetup_SiteBOM] DEFAULT ((0)) NOT NULL,
    [StdCstRevalAcct]      CHAR (10)     CONSTRAINT [DF_BMSetup_StdCstRevalAcct] DEFAULT (' ') NOT NULL,
    [StdCstRevalSub]       CHAR (24)     CONSTRAINT [DF_BMSetup_StdCstRevalSub] DEFAULT (' ') NOT NULL,
    [SubTranCrt]           SMALLINT      CONSTRAINT [DF_BMSetup_SubTranCrt] DEFAULT ((0)) NOT NULL,
    [User1]                CHAR (30)     CONSTRAINT [DF_BMSetup_User1] DEFAULT (' ') NOT NULL,
    [User2]                CHAR (30)     CONSTRAINT [DF_BMSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]                FLOAT (53)    CONSTRAINT [DF_BMSetup_User3] DEFAULT ((0)) NOT NULL,
    [User4]                FLOAT (53)    CONSTRAINT [DF_BMSetup_User4] DEFAULT ((0)) NOT NULL,
    [User5]                CHAR (10)     CONSTRAINT [DF_BMSetup_User5] DEFAULT (' ') NOT NULL,
    [User6]                CHAR (10)     CONSTRAINT [DF_BMSetup_User6] DEFAULT (' ') NOT NULL,
    [User7]                SMALLDATETIME CONSTRAINT [DF_BMSetup_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]                SMALLDATETIME CONSTRAINT [DF_BMSetup_User8] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [BMSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

