CREATE TABLE [dbo].[smWrkInvoice] (
    [Acct]           CHAR (10)     NOT NULL,
    [Amount]         FLOAT (53)    NOT NULL,
    [ARBatNbr]       CHAR (10)     NOT NULL,
    [BillingType]    CHAR (1)      NOT NULL,
    [BranchId]       CHAR (10)     NOT NULL,
    [CallDetailType] CHAR (1)      NOT NULL,
    [CmmnAmt]        FLOAT (53)    NOT NULL,
    [CmmnPct]        FLOAT (53)    NOT NULL,
    [ContractID]     CHAR (10)     NOT NULL,
    [CpnyID]         CHAR (10)     NOT NULL,
    [CustID]         CHAR (15)     NOT NULL,
    [CustPO]         CHAR (30)     NOT NULL,
    [DocDate]        SMALLDATETIME NOT NULL,
    [DocDesc]        CHAR (30)     NOT NULL,
    [DocType]        CHAR (1)      NOT NULL,
    [DocumentID]     CHAR (10)     NOT NULL,
    [Handling]       SMALLINT      NOT NULL,
    [InvBatNbr]      CHAR (10)     NOT NULL,
    [InvoiceType]    CHAR (1)      NOT NULL,
    [NoteId]         INT           NOT NULL,
    [OrigCallID]     CHAR (10)     NOT NULL,
    [PerEnt]         CHAR (6)      NOT NULL,
    [PerPost]        CHAR (6)      NOT NULL,
    [ProjectID]      CHAR (16)     NOT NULL,
    [Refnbr]         CHAR (10)     NOT NULL,
    [RI_ID]          SMALLINT      NOT NULL,
    [ShipTOID]       CHAR (10)     NOT NULL,
    [SlsperID]       CHAR (10)     NOT NULL,
    [Sub]            CHAR (24)     NOT NULL,
    [TaxAmt00]       FLOAT (53)    NOT NULL,
    [TaxAmt01]       FLOAT (53)    NOT NULL,
    [TaxAmt02]       FLOAT (53)    NOT NULL,
    [TaxAmt03]       FLOAT (53)    NOT NULL,
    [TaxID00]        CHAR (10)     NOT NULL,
    [TaxID01]        CHAR (10)     NOT NULL,
    [TaxID02]        CHAR (10)     NOT NULL,
    [TaxID03]        CHAR (10)     NOT NULL,
    [TermID]         CHAR (2)      NOT NULL,
    [TxblAmt00]      FLOAT (53)    NOT NULL,
    [TxblAmt01]      FLOAT (53)    NOT NULL,
    [TxblAmt02]      FLOAT (53)    NOT NULL,
    [TxblAmt03]      FLOAT (53)    NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [User9]          SMALLINT      NOT NULL,
    [UserID]         CHAR (47)     NOT NULL,
    [WrkOrdNbr]      CHAR (10)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [smWrkInvoice0] PRIMARY KEY CLUSTERED ([InvBatNbr] ASC, [DocType] ASC, [Refnbr] ASC, [DocumentID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [smWrkInvoice1]
    ON [dbo].[smWrkInvoice]([RI_ID] ASC, [Refnbr] ASC) WITH (FILLFACTOR = 90);

