CREATE TABLE [dbo].[smSCQConfig] (
    [BranchID]            CHAR (10)     NOT NULL,
    [BranchIDAll]         SMALLINT      NOT NULL,
    [ConfigCode]          CHAR (10)     NOT NULL,
    [ConfigColorMinutes]  SMALLINT      NOT NULL,
    [ConfigColorOn]       CHAR (1)      NOT NULL,
    [ConfigDescription]   CHAR (30)     NOT NULL,
    [ConfigPriorityBlink] CHAR (1)      NOT NULL,
    [ConfigPTimeBlink]    CHAR (1)      NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [PriorityHigh]        SMALLINT      NOT NULL,
    [Prioritylow]         SMALLINT      NOT NULL,
    [PriorityMedium]      SMALLINT      NOT NULL,
    [PriorityPremium]     SMALLINT      NOT NULL,
    [Technician]          CHAR (10)     NOT NULL,
    [TechnicianAll]       SMALLINT      NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [smSCQConfig0] PRIMARY KEY CLUSTERED ([ConfigCode] ASC) WITH (FILLFACTOR = 90)
);

