CREATE TABLE [dbo].[BRAcct] (
    [Acct]             CHAR (10)     NOT NULL,
    [AcctDescr]        CHAR (30)     NOT NULL,
    [AcctID]           CHAR (10)     NOT NULL,
    [Active]           SMALLINT      NOT NULL,
    [BankAcctNbr]      CHAR (30)     NOT NULL,
    [BankName]         CHAR (30)     NOT NULL,
    [CpnyId]           CHAR (10)     NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [CurrPerNbr]       CHAR (6)      NOT NULL,
    [CuryId]           CHAR (4)      NOT NULL,
    [CuryLastReconBal] FLOAT (53)    NOT NULL,
    [FutureC1]         CHAR (30)     NOT NULL,
    [FutureC2]         CHAR (10)     NOT NULL,
    [FutureD1]         SMALLDATETIME NOT NULL,
    [FutureF1]         FLOAT (53)    NOT NULL,
    [FutureI1]         INT           NOT NULL,
    [FutureL1]         SMALLINT      NOT NULL,
    [LastReconBal]     FLOAT (53)    NOT NULL,
    [LastReconDate]    SMALLDATETIME NOT NULL,
    [LedgerID]         CHAR (10)     NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME NOT NULL,
    [LUpd_Prog]        CHAR (8)      NOT NULL,
    [LUpd_User]        CHAR (10)     NOT NULL,
    [NoteID]           INT           NOT NULL,
    [S4Future01]       CHAR (30)     NOT NULL,
    [S4Future02]       CHAR (30)     NOT NULL,
    [S4Future03]       FLOAT (53)    NOT NULL,
    [S4Future04]       FLOAT (53)    NOT NULL,
    [S4Future05]       FLOAT (53)    NOT NULL,
    [S4Future06]       FLOAT (53)    NOT NULL,
    [S4Future07]       SMALLDATETIME NOT NULL,
    [S4Future08]       SMALLDATETIME NOT NULL,
    [S4Future09]       INT           NOT NULL,
    [S4Future10]       INT           NOT NULL,
    [S4Future11]       CHAR (10)     NOT NULL,
    [S4Future12]       CHAR (10)     NOT NULL,
    [SetUpID]          CHAR (4)      NOT NULL,
    [Sub]              CHAR (24)     NOT NULL,
    [UserC1]           CHAR (30)     NOT NULL,
    [UserC2]           CHAR (30)     NOT NULL,
    [UserC3]           CHAR (10)     NOT NULL,
    [UserC4]           CHAR (10)     NOT NULL,
    [UserD1]           SMALLDATETIME NOT NULL,
    [UserD2]           SMALLDATETIME NOT NULL,
    [UserF1]           FLOAT (53)    NOT NULL,
    [UserF2]           FLOAT (53)    NOT NULL,
    [UserI1]           INT           NOT NULL,
    [UserI2]           INT           NOT NULL,
    [UserL1]           SMALLINT      NOT NULL,
    [UserL2]           SMALLINT      NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [BRAcct0] PRIMARY KEY CLUSTERED ([CpnyId] ASC, [AcctID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BRAcct1]
    ON [dbo].[BRAcct]([CpnyId] ASC, [Acct] ASC, [Sub] ASC) WITH (FILLFACTOR = 90);

