CREATE TABLE [dbo].[cftAPImportStaging] (
    [Acct]           CHAR (10)     NOT NULL,
    [ACHFlag]        CHAR (30)     NOT NULL,
    [BoxNbr]         CHAR (2)      NOT NULL,
    [Comment]        CHAR (30)     NOT NULL,
    [CpnyID]         CHAR (10)     NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [ExtPrice]       FLOAT (53)    NOT NULL,
    [GroupReference] CHAR (5)      NOT NULL,
    [InvoiceDate]    SMALLDATETIME NOT NULL,
    [InvoiceDescr]   CHAR (30)     NOT NULL,
    [InvoiceNbr]     CHAR (15)     NOT NULL,
    [LineErrorText]  CHAR (255)    NOT NULL,
    [PayDate]        SMALLDATETIME NOT NULL,
    [ProjectID]      CHAR (16)     NOT NULL,
    [Qty]            FLOAT (53)    NOT NULL,
    [RecordID]       INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [RowErrorFlag]   SMALLINT      NOT NULL,
    [SubAcct]        CHAR (24)     NOT NULL,
    [TaskID]         CHAR (32)     NOT NULL,
    [TranDescr]      CHAR (30)     NOT NULL,
    [UnitPrice]      FLOAT (53)    NOT NULL,
    [UOM]            CHAR (6)      NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [VendID]         CHAR (15)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [cftAPImportStaging0] PRIMARY KEY CLUSTERED ([RecordID] ASC) WITH (FILLFACTOR = 90)
);

