CREATE TABLE [dbo].[SOSetup] (
    [AccrRevAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [AccrRevSub]           CHAR (24)     DEFAULT (' ') NOT NULL,
    [AddAlternateID]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AddDaysEarly]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [AddDaysLate]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [Addr1]                CHAR (60)     DEFAULT (' ') NOT NULL,
    [Addr2]                CHAR (60)     DEFAULT (' ') NOT NULL,
    [AllowDiscPrice]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoCreateShippers]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoInsertContacts]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoRef]              SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoReleaseBatches]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoSalesJournal]     CHAR (1)      DEFAULT (' ') NOT NULL,
    [AutoSave]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [BillThruProject]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [BookingLimit]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [CashSaleCustID]       CHAR (15)     DEFAULT (' ') NOT NULL,
    [ChainDiscEnabled]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [City]                 CHAR (30)     DEFAULT (' ') NOT NULL,
    [ConsolInv]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [CopyNotes]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [CopyToInvc00]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc01]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc02]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc03]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc04]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc05]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc06]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToInvc07]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper00]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper01]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper02]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper03]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper04]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper05]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper06]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper07]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper08]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [CopyToShipper09]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [Country]              CHAR (3)      DEFAULT (' ') NOT NULL,
    [CpnyName]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [CreditCheck]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [CreditGraceDays]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [CreditGracePct]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CreditNoOrdEntry]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]        SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]            CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [CutoffTime]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [DecPlNonStdQty]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [DecPlPrice]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [DelayManifestUpdate]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [DelayShipperCreation] SMALLINT      DEFAULT ((0)) NOT NULL,
    [DelayShipperUpdate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [DelayUpdOrd]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [DfltAccrueRev]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [DfltAltIDType]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [DfltBillThruProject]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [DfltConsolInv]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [DfltDiscountID]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [DfltOrderType]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltShipperType]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltSiteIDMethod]     CHAR (1)      DEFAULT (' ') NOT NULL,
    [DfltSlsperMethod]     CHAR (1)      DEFAULT (' ') NOT NULL,
    [DiscBySite]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [DiscPrcDate]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq00]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq01]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq02]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq03]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq04]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq05]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq06]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq07]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DiscPrcSeq08]         CHAR (2)      DEFAULT (' ') NOT NULL,
    [DispAvailSO]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [EarlyWarningCutoff]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [ErrorAcct]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [ErrorSub]             CHAR (24)     DEFAULT (' ') NOT NULL,
    [Fax]                  CHAR (30)     DEFAULT (' ') NOT NULL,
    [ForceValidSerialNo]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [INAvail]              SMALLINT      DEFAULT ((0)) NOT NULL,
    [Init]                 SMALLINT      DEFAULT ((0)) NOT NULL,
    [InvTaxCat]            SMALLINT      DEFAULT ((0)) NOT NULL,
    [InvtScrapAcct]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [InvtScrapSub]         CHAR (24)     DEFAULT (' ') NOT NULL,
    [KAAvailAtETA]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [LastRebateID]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [LastShipRegisterID]   CHAR (10)     DEFAULT (' ') NOT NULL,
    [LookupSpecChar]       CHAR (30)     DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]            CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [MinGPHandling]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [NegQtyMsg]            CHAR (1)      DEFAULT (' ') NOT NULL,
    [NoQueueOnUnreserve]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [NoteID]               INT           DEFAULT ((0)) NOT NULL,
    [PerRetBook]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [PerRetTran]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [Phone]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [PickTime]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [PlanScheds]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [POAvailAtETA]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [PostBookings]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [PrenumberedForms]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [ProcManSleepSecs]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [PrtCpny]              SMALLINT      DEFAULT ((0)) NOT NULL,
    [PrtSite]              SMALLINT      DEFAULT ((0)) NOT NULL,
    [PrtTax]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [RMARequired]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [S4Future01]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]           INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [SendProjInfotoPO]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [SetupID]              CHAR (2)      DEFAULT (' ') NOT NULL,
    [ShipConfirmNegQty]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [State]                CHAR (3)      DEFAULT (' ') NOT NULL,
    [TaxDet]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [TermsOverride]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [TotalOrdDisc]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [TransferAvailAtETA]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [User1]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User10]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User2]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User4]                CHAR (30)     DEFAULT (' ') NOT NULL,
    [User5]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User6]                FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User7]                CHAR (10)     DEFAULT (' ') NOT NULL,
    [User8]                CHAR (10)     DEFAULT (' ') NOT NULL,
    [User9]                SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [WCShipViaID]          CHAR (15)     DEFAULT (' ') NOT NULL,
    [WOAvailAtETA]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [Zip]                  CHAR (10)     DEFAULT (' ') NOT NULL,
    [tstamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [SOSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

