CREATE TABLE [dbo].[XDDAchHeadTrail] (
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Descr]          CHAR (30)     NOT NULL,
    [EndPos]         CHAR (2)      NOT NULL,
    [EntryType]      CHAR (10)     NOT NULL,
    [FileType]       CHAR (1)      NOT NULL,
    [FormatID]       CHAR (15)     NOT NULL,
    [Header_Trailer] CHAR (1)      NOT NULL,
    [HeadTrailID]    CHAR (1)      NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [SKFuture01]     CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]     CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]     FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture04]     FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture05]     FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture06]     FLOAT (53)    DEFAULT (0) NOT NULL,
    [SKFuture07]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]     INT           DEFAULT (0) NOT NULL,
    [SKFuture10]     INT           DEFAULT (0) NOT NULL,
    [SKFuture11]     CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]     CHAR (10)     DEFAULT ('') NOT NULL,
    [StartPos]       CHAR (2)      NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User10]         CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [User9]          CHAR (30)     NOT NULL,
    [Value]          CHAR (94)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [XDDAchHeadTrail0] PRIMARY KEY CLUSTERED ([FileType] ASC, [FormatID] ASC, [HeadTrailID] ASC, [Header_Trailer] ASC, [StartPos] ASC)
);

