CREATE TABLE [dbo].[POReqAddlCost] (
    [AddlCostAccrAcct] CHAR (10)     CONSTRAINT [DF_POReqAddlCost_AddlCostAccrAcct] DEFAULT (' ') NOT NULL,
    [AddlCostAccrSub]  CHAR (24)     CONSTRAINT [DF_POReqAddlCost_AddlCostAccrSub] DEFAULT (' ') NOT NULL,
    [AddlCostExpAcct]  CHAR (10)     CONSTRAINT [DF_POReqAddlCost_AddlCostExpAcct] DEFAULT (' ') NOT NULL,
    [AddlCostExpSub]   CHAR (24)     CONSTRAINT [DF_POReqAddlCost_AddlCostExpSub] DEFAULT (' ') NOT NULL,
    [AddlCostTypeID]   CHAR (10)     CONSTRAINT [DF_POReqAddlCost_AddlCostTypeID] DEFAULT (' ') NOT NULL,
    [CostOverride]     SMALLINT      CONSTRAINT [DF_POReqAddlCost_CostOverride] DEFAULT ((0)) NOT NULL,
    [CostReceived]     FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CostReceived] DEFAULT ((0)) NOT NULL,
    [CostVouchered]    FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CostVouchered] DEFAULT ((0)) NOT NULL,
    [CpnyID]           CHAR (10)     CONSTRAINT [DF_POReqAddlCost_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_POReqAddlCost_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_POReqAddlCost_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCostReceived] FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CuryCostReceived] DEFAULT ((0)) NOT NULL,
    [CuryCostVouched]  FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CuryCostVouched] DEFAULT ((0)) NOT NULL,
    [CuryExpectedCost] FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CuryExpectedCost] DEFAULT ((0)) NOT NULL,
    [CuryID]           CHAR (4)      CONSTRAINT [DF_POReqAddlCost_CuryID] DEFAULT (' ') NOT NULL,
    [CuryIntmCuryID]   CHAR (4)      CONSTRAINT [DF_POReqAddlCost_CuryIntmCuryID] DEFAULT (' ') NOT NULL,
    [CuryIntmEffDate]  SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_CuryIntmEffDate] DEFAULT ('01/01/1900') NOT NULL,
    [CuryIntmMultDiv]  CHAR (1)      CONSTRAINT [DF_POReqAddlCost_CuryIntmMultDiv] DEFAULT (' ') NOT NULL,
    [CuryIntmRate]     FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CuryIntmRate] DEFAULT ((0)) NOT NULL,
    [CuryMultDiv]      CHAR (1)      CONSTRAINT [DF_POReqAddlCost_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]         FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_CuryRate] DEFAULT ((0)) NOT NULL,
    [Descr]            CHAR (30)     CONSTRAINT [DF_POReqAddlCost_Descr] DEFAULT (' ') NOT NULL,
    [DfltPct]          FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_DfltPct] DEFAULT ((0)) NOT NULL,
    [ExpectedCost]     FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_ExpectedCost] DEFAULT ((0)) NOT NULL,
    [Labor_Class_CD]   CHAR (4)      CONSTRAINT [DF_POReqAddlCost_Labor_Class_CD] DEFAULT (' ') NOT NULL,
    [LineID]           INT           CONSTRAINT [DF_POReqAddlCost_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]          SMALLINT      CONSTRAINT [DF_POReqAddlCost_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]          CHAR (5)      CONSTRAINT [DF_POReqAddlCost_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      CONSTRAINT [DF_POReqAddlCost_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]        CHAR (10)     CONSTRAINT [DF_POReqAddlCost_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]           INT           CONSTRAINT [DF_POReqAddlCost_NoteID] DEFAULT ((0)) NOT NULL,
    [PC_Flag]          CHAR (1)      CONSTRAINT [DF_POReqAddlCost_PC_Flag] DEFAULT (' ') NOT NULL,
    [PC_Status]        CHAR (1)      CONSTRAINT [DF_POReqAddlCost_PC_Status] DEFAULT (' ') NOT NULL,
    [PONbr]            CHAR (10)     CONSTRAINT [DF_POReqAddlCost_PONbr] DEFAULT (' ') NOT NULL,
    [ProjectID]        CHAR (16)     CONSTRAINT [DF_POReqAddlCost_ProjectID] DEFAULT (' ') NOT NULL,
    [ProrateMthd]      CHAR (1)      CONSTRAINT [DF_POReqAddlCost_ProrateMthd] DEFAULT (' ') NOT NULL,
    [RcptStatus]       CHAR (1)      CONSTRAINT [DF_POReqAddlCost_RcptStatus] DEFAULT (' ') NOT NULL,
    [ReqCntr]          CHAR (2)      CONSTRAINT [DF_POReqAddlCost_ReqCntr] DEFAULT (' ') NOT NULL,
    [ReqNbr]           CHAR (10)     CONSTRAINT [DF_POReqAddlCost_ReqNbr] DEFAULT (' ') NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_POReqAddlCost_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_POReqAddlCost_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_POReqAddlCost_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_POReqAddlCost_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_POReqAddlCost_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_POReqAddlCost_S4Future12] DEFAULT (' ') NOT NULL,
    [SeparateVoucher]  SMALLINT      CONSTRAINT [DF_POReqAddlCost_SeparateVoucher] DEFAULT ((0)) NOT NULL,
    [TaskID]           CHAR (32)     CONSTRAINT [DF_POReqAddlCost_TaskID] DEFAULT (' ') NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_POReqAddlCost_User1] DEFAULT (' ') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_POReqAddlCost_User2] DEFAULT (' ') NOT NULL,
    [User3]            FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_User3] DEFAULT ((0)) NOT NULL,
    [User4]            FLOAT (53)    CONSTRAINT [DF_POReqAddlCost_User4] DEFAULT ((0)) NOT NULL,
    [User5]            CHAR (10)     CONSTRAINT [DF_POReqAddlCost_User5] DEFAULT (' ') NOT NULL,
    [User6]            CHAR (10)     CONSTRAINT [DF_POReqAddlCost_User6] DEFAULT (' ') NOT NULL,
    [User7]            SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]            SMALLDATETIME CONSTRAINT [DF_POReqAddlCost_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]           CHAR (15)     CONSTRAINT [DF_POReqAddlCost_VendID] DEFAULT (' ') NOT NULL,
    [VouchStatus]      CHAR (1)      CONSTRAINT [DF_POReqAddlCost_VouchStatus] DEFAULT (' ') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [POReqAddlCost0] PRIMARY KEY CLUSTERED ([ReqNbr] ASC, [ReqCntr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [POReqAddlCost1]
    ON [dbo].[POReqAddlCost]([ReqNbr] ASC, [ReqCntr] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);

