CREATE TABLE [dbo].[CustGLClass] (
    [ARAcct]        CHAR (10)     NOT NULL,
    [ARSub]         CHAR (24)     NOT NULL,
    [COGSAcct]      CHAR (10)     NOT NULL,
    [COGSSub]       CHAR (31)     NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [DiscAcct]      CHAR (10)     NOT NULL,
    [DiscSub]       CHAR (31)     NOT NULL,
    [FrtAcct]       CHAR (10)     NOT NULL,
    [FrtSub]        CHAR (31)     NOT NULL,
    [GLClassID]     CHAR (4)      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [MiscAcct]      CHAR (10)     NOT NULL,
    [MiscSub]       CHAR (31)     NOT NULL,
    [NoteID]        INT           NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [SlsAcct]       CHAR (10)     NOT NULL,
    [SlsSub]        CHAR (31)     NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User10]        SMALLDATETIME NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         CHAR (30)     NOT NULL,
    [User4]         CHAR (30)     NOT NULL,
    [User5]         FLOAT (53)    NOT NULL,
    [User6]         FLOAT (53)    NOT NULL,
    [User7]         CHAR (10)     NOT NULL,
    [User8]         CHAR (10)     NOT NULL,
    [User9]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [CustGLClass0] PRIMARY KEY CLUSTERED ([S4Future11] ASC) WITH (FILLFACTOR = 90)
);

