CREATE TABLE [dbo].[POAddlCost] (
    [AddlCostAccrAcct] CHAR (10)     CONSTRAINT [DF_POAddlCost_AddlCostAccrAcct] DEFAULT (' ') NOT NULL,
    [AddlCostAccrSub]  CHAR (24)     CONSTRAINT [DF_POAddlCost_AddlCostAccrSub] DEFAULT (' ') NOT NULL,
    [AddlCostExpAcct]  CHAR (10)     CONSTRAINT [DF_POAddlCost_AddlCostExpAcct] DEFAULT (' ') NOT NULL,
    [AddlCostExpSub]   CHAR (24)     CONSTRAINT [DF_POAddlCost_AddlCostExpSub] DEFAULT (' ') NOT NULL,
    [AddlCostTypeID]   CHAR (10)     CONSTRAINT [DF_POAddlCost_AddlCostTypeID] DEFAULT (' ') NOT NULL,
    [CostOverride]     SMALLINT      CONSTRAINT [DF_POAddlCost_CostOverride] DEFAULT ((0)) NOT NULL,
    [CostReceived]     FLOAT (53)    CONSTRAINT [DF_POAddlCost_CostReceived] DEFAULT ((0)) NOT NULL,
    [CostVouchered]    FLOAT (53)    CONSTRAINT [DF_POAddlCost_CostVouchered] DEFAULT ((0)) NOT NULL,
    [CpnyID]           CHAR (10)     CONSTRAINT [DF_POAddlCost_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_POAddlCost_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_POAddlCost_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_POAddlCost_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryCostReceived] FLOAT (53)    CONSTRAINT [DF_POAddlCost_CuryCostReceived] DEFAULT ((0)) NOT NULL,
    [CuryCostVouched]  FLOAT (53)    CONSTRAINT [DF_POAddlCost_CuryCostVouched] DEFAULT ((0)) NOT NULL,
    [CuryExpectedCost] FLOAT (53)    CONSTRAINT [DF_POAddlCost_CuryExpectedCost] DEFAULT ((0)) NOT NULL,
    [CuryID]           CHAR (4)      CONSTRAINT [DF_POAddlCost_CuryID] DEFAULT (' ') NOT NULL,
    [CuryMultDiv]      CHAR (1)      CONSTRAINT [DF_POAddlCost_CuryMultDiv] DEFAULT (' ') NOT NULL,
    [CuryRate]         FLOAT (53)    CONSTRAINT [DF_POAddlCost_CuryRate] DEFAULT ((0)) NOT NULL,
    [Descr]            CHAR (30)     CONSTRAINT [DF_POAddlCost_Descr] DEFAULT (' ') NOT NULL,
    [DfltPct]          FLOAT (53)    CONSTRAINT [DF_POAddlCost_DfltPct] DEFAULT ((0)) NOT NULL,
    [ExpectedCost]     FLOAT (53)    CONSTRAINT [DF_POAddlCost_ExpectedCost] DEFAULT ((0)) NOT NULL,
    [Labor_Class_CD]   CHAR (4)      CONSTRAINT [DF_POAddlCost_Labor_Class_CD] DEFAULT (' ') NOT NULL,
    [LineID]           INT           CONSTRAINT [DF_POAddlCost_LineID] DEFAULT ((0)) NOT NULL,
    [LineNbr]          SMALLINT      CONSTRAINT [DF_POAddlCost_LineNbr] DEFAULT ((0)) NOT NULL,
    [LineRef]          CHAR (5)      CONSTRAINT [DF_POAddlCost_LineRef] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME CONSTRAINT [DF_POAddlCost_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      CONSTRAINT [DF_POAddlCost_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]        CHAR (10)     CONSTRAINT [DF_POAddlCost_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]           INT           CONSTRAINT [DF_POAddlCost_NoteID] DEFAULT ((0)) NOT NULL,
    [OpenLine]         SMALLINT      CONSTRAINT [DF_POAddlCost_OpenLine] DEFAULT ((0)) NOT NULL,
    [PC_Flag]          CHAR (1)      CONSTRAINT [DF_POAddlCost_PC_Flag] DEFAULT (' ') NOT NULL,
    [PC_Status]        CHAR (1)      CONSTRAINT [DF_POAddlCost_PC_Status] DEFAULT (' ') NOT NULL,
    [PONbr]            CHAR (10)     CONSTRAINT [DF_POAddlCost_PONbr] DEFAULT (' ') NOT NULL,
    [ProjectID]        CHAR (16)     CONSTRAINT [DF_POAddlCost_ProjectID] DEFAULT (' ') NOT NULL,
    [ProrateMthd]      CHAR (1)      CONSTRAINT [DF_POAddlCost_ProrateMthd] DEFAULT (' ') NOT NULL,
    [RcptStatus]       CHAR (1)      CONSTRAINT [DF_POAddlCost_RcptStatus] DEFAULT (' ') NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_POAddlCost_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_POAddlCost_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_POAddlCost_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_POAddlCost_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_POAddlCost_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_POAddlCost_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_POAddlCost_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_POAddlCost_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_POAddlCost_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_POAddlCost_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_POAddlCost_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_POAddlCost_S4Future12] DEFAULT (' ') NOT NULL,
    [SeparateVoucher]  SMALLINT      CONSTRAINT [DF_POAddlCost_SeparateVoucher] DEFAULT ((0)) NOT NULL,
    [TaskID]           CHAR (32)     CONSTRAINT [DF_POAddlCost_TaskID] DEFAULT (' ') NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_POAddlCost_User1] DEFAULT (' ') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_POAddlCost_User2] DEFAULT (' ') NOT NULL,
    [User3]            FLOAT (53)    CONSTRAINT [DF_POAddlCost_User3] DEFAULT ((0)) NOT NULL,
    [User4]            FLOAT (53)    CONSTRAINT [DF_POAddlCost_User4] DEFAULT ((0)) NOT NULL,
    [User5]            CHAR (10)     CONSTRAINT [DF_POAddlCost_User5] DEFAULT (' ') NOT NULL,
    [User6]            CHAR (10)     CONSTRAINT [DF_POAddlCost_User6] DEFAULT (' ') NOT NULL,
    [User7]            SMALLDATETIME CONSTRAINT [DF_POAddlCost_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]            SMALLDATETIME CONSTRAINT [DF_POAddlCost_User8] DEFAULT ('01/01/1900') NOT NULL,
    [VendID]           CHAR (15)     CONSTRAINT [DF_POAddlCost_VendID] DEFAULT (' ') NOT NULL,
    [VouchStatus]      CHAR (1)      CONSTRAINT [DF_POAddlCost_VouchStatus] DEFAULT (' ') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [POAddlCost0] PRIMARY KEY CLUSTERED ([PONbr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);

