CREATE TABLE [dbo].[cftPSSetup] (
    [BPDiffLimit]    FLOAT (53)    NULL,
    [Crtd_DateTime]  SMALLDATETIME NULL,
    [Crtd_Prog]      CHAR (8)      NULL,
    [Crtd_User]      CHAR (10)     NULL,
    [DeferAcct]      CHAR (10)     NULL,
    [DfltSalesBasis] CHAR (2)      NULL,
    [DfltSub]        CHAR (10)     NULL,
    [GradePremAcct]  CHAR (10)     NULL,
    [InsectAcct]     CHAR (10)     NULL,
    [InsurAcct]      CHAR (10)     NULL,
    [LastContrNbr]   CHAR (10)     NULL,
    [LastOrdNbr]     CHAR (10)     NULL,
    [Lupd_DateTime]  SMALLDATETIME NULL,
    [Lupd_Prog]      CHAR (8)      NULL,
    [Lupd_User]      CHAR (10)     NULL,
    [NonPGAcct]      CHAR (10)     NULL,
    [NonPGTrkAcct]   CHAR (10)     NULL,
    [NPPCAcct]       CHAR (10)     NULL,
    [OtherAcct]      CHAR (10)     NULL,
    [ScaleAcct]      CHAR (10)     NULL,
    [SetupID]        CHAR (2)      NOT NULL,
    [SortLossAcct]   CHAR (10)     NULL,
    [TruckAcct]      CHAR (10)     NULL,
    [TruckAllowAcct] CHAR (10)     NULL,
    [tstamp]         ROWVERSION    NULL,
    CONSTRAINT [cftPSSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

