CREATE TABLE [dbo].[CMSetup] (
    [APCuryOverride]  SMALLINT      NOT NULL,
    [APRateDate]      CHAR (1)      NOT NULL,
    [APRtTpDflt]      CHAR (6)      NOT NULL,
    [APRtTpOverride]  SMALLINT      NOT NULL,
    [ARCuryOverride]  SMALLINT      NOT NULL,
    [ARPrcLvlRtTp]    CHAR (6)      NOT NULL,
    [ARRateDate]      CHAR (1)      NOT NULL,
    [ARRtTpDflt]      CHAR (6)      NOT NULL,
    [ARRtTpOverride]  SMALLINT      NOT NULL,
    [CARtTpDflt]      CHAR (6)      NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [CuryWarning]     SMALLINT      NOT NULL,
    [GLRevalRtTpDflt] CHAR (6)      NOT NULL,
    [GLRtTpDflt]      CHAR (6)      NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [MCActivated]     SMALLINT      NOT NULL,
    [NoteId]          INT           NOT NULL,
    [OERateDate]      CHAR (1)      NOT NULL,
    [OERateWarning]   SMALLINT      NOT NULL,
    [RateVariance]    FLOAT (53)    NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [SetupId]         CHAR (2)      NOT NULL,
    [TriangCuryID]    CHAR (4)      NOT NULL,
    [TriangEffDate]   SMALLDATETIME NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [CMSetup0] PRIMARY KEY CLUSTERED ([SetupId] ASC) WITH (FILLFACTOR = 90)
);

