CREATE TABLE [dbo].[AP03615_Wrk] (
    [RI_ID]                SMALLINT      NOT NULL,
    [BatNbr]               CHAR (10)     NULL,
    [CpnyID]               CHAR (10)     NULL,
    [CuryDiscBal]          FLOAT (53)    NULL,
    [CuryDiscTkn]          FLOAT (53)    NULL,
    [CuryDocBal]           FLOAT (53)    NULL,
    [DiscDate]             SMALLDATETIME NULL,
    [DocType]              CHAR (2)      NULL,
    [DueDate]              SMALLDATETIME NULL,
    [InvcDate]             SMALLDATETIME NULL,
    [InvcNbr]              CHAR (15)     NULL,
    [PayDate]              SMALLDATETIME NULL,
    [RefNbr]               CHAR (10)     NULL,
    [Status]               CHAR (1)      NULL,
    [Vendor_Name]          CHAR (60)     NOT NULL,
    [Vendor_Status]        CHAR (1)      NULL,
    [Vendor_VendId]        CHAR (15)     NULL,
    [APTran_CpnyID]        CHAR (10)     NULL,
    [APTran_CuryTranAmt]   FLOAT (53)    NULL,
    [APTran_CuryUnitPrice] FLOAT (53)    NULL,
    [APTran_DrCr]          CHAR (1)      NULL,
    [APTran_ExtRefNbr]     CHAR (15)     NULL,
    [APTran_RefNbr]        CHAR (10)     NULL,
    [APTran_TranType]      CHAR (2)      NULL,
    [APTran_VendId]        CHAR (15)     NULL,
    [tstamp]               ROWVERSION    NOT NULL
);

