CREATE TABLE [dbo].[PJREVHDR] (
    [approved_by1]     CHAR (10)     NOT NULL,
    [approved_by2]     CHAR (10)     NOT NULL,
    [approved_by3]     CHAR (10)     NOT NULL,
    [approver]         CHAR (10)     NOT NULL,
    [Change_Order_Num] CHAR (16)     NOT NULL,
    [Create_Date]      SMALLDATETIME NOT NULL,
    [crtd_datetime]    SMALLDATETIME NOT NULL,
    [crtd_prog]        CHAR (8)      NOT NULL,
    [crtd_user]        CHAR (10)     NOT NULL,
    [end_date]         SMALLDATETIME NOT NULL,
    [Est_Approve_Date] SMALLDATETIME NOT NULL,
    [lupd_datetime]    SMALLDATETIME NOT NULL,
    [lupd_prog]        CHAR (8)      NOT NULL,
    [lupd_user]        CHAR (10)     NOT NULL,
    [NoteId]           INT           NOT NULL,
    [Post_Date]        SMALLDATETIME NOT NULL,
    [Post_Period]      CHAR (6)      NOT NULL,
    [Preparer]         CHAR (10)     NOT NULL,
    [Project]          CHAR (16)     NOT NULL,
    [RevId]            CHAR (4)      NOT NULL,
    [RevisionType]     CHAR (2)      NOT NULL,
    [Revision_Desc]    CHAR (60)     NOT NULL,
    [rh_id01]          CHAR (30)     NOT NULL,
    [rh_id02]          CHAR (30)     NOT NULL,
    [rh_id03]          CHAR (16)     NOT NULL,
    [rh_id04]          CHAR (16)     NOT NULL,
    [rh_id05]          CHAR (4)      NOT NULL,
    [rh_id06]          FLOAT (53)    NOT NULL,
    [rh_id07]          FLOAT (53)    NOT NULL,
    [rh_id08]          SMALLDATETIME NOT NULL,
    [rh_id09]          SMALLDATETIME NOT NULL,
    [rh_id10]          SMALLINT      NOT NULL,
    [start_date]       SMALLDATETIME NOT NULL,
    [status]           CHAR (2)      NOT NULL,
    [update_type]      CHAR (1)      NOT NULL,
    [User1]            CHAR (30)     NOT NULL,
    [User2]            CHAR (30)     NOT NULL,
    [User3]            FLOAT (53)    NOT NULL,
    [User4]            FLOAT (53)    NOT NULL,
    [User5]            CHAR (10)     NOT NULL,
    [User6]            CHAR (10)     NOT NULL,
    [User7]            SMALLDATETIME NOT NULL,
    [User8]            SMALLDATETIME NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [pjrevhdr0] PRIMARY KEY CLUSTERED ([Project] ASC, [RevId] ASC) WITH (FILLFACTOR = 90)
);

