CREATE TABLE [dbo].[XBANKINFO] (
    [ABA]                CHAR (20)     NOT NULL,
    [Acct]               CHAR (10)     NOT NULL,
    [Addr1]              CHAR (30)     NOT NULL,
    [Addr2]              CHAR (30)     NOT NULL,
    [BankAcctNum]        CHAR (30)     NOT NULL,
    [BankLimit]          FLOAT (53)    NOT NULL,
    [BankName]           CHAR (30)     NOT NULL,
    [BankReqSig2]        SMALLINT      NOT NULL,
    [City]               CHAR (20)     NOT NULL,
    [CnyAddr1]           CHAR (30)     NOT NULL,
    [CnyAddr2]           CHAR (30)     NOT NULL,
    [CnyCity]            CHAR (20)     NOT NULL,
    [CnyId]              CHAR (10)     NOT NULL,
    [CnyLogo]            CHAR (255)    NOT NULL,
    [CnyName]            CHAR (60)     NOT NULL,
    [CnyState]           CHAR (2)      NOT NULL,
    [CnyZip]             CHAR (10)     NOT NULL,
    [OnUsField]          CHAR (30)     NOT NULL,
    [prtLine1]           SMALLINT      NOT NULL,
    [RTNum]              CHAR (11)     NOT NULL,
    [Signature1]         CHAR (255)    NOT NULL,
    [Signature1always]   SMALLINT      NOT NULL,
    [Signature1Limit]    FLOAT (53)    NOT NULL,
    [Signature1Pwd]      CHAR (255)    NOT NULL,
    [Signature2]         CHAR (255)    NOT NULL,
    [Signature2Limit]    FLOAT (53)    NOT NULL,
    [Signature2Pwd]      CHAR (255)    NOT NULL,
    [Signature2Valid]    SMALLINT      NOT NULL,
    [Signature2ValidMsg] CHAR (75)     NOT NULL,
    [State]              CHAR (2)      NOT NULL,
    [SubAcct]            CHAR (24)     NOT NULL,
    [User1]              CHAR (40)     NOT NULL,
    [User2]              CHAR (40)     NOT NULL,
    [User3]              CHAR (15)     NOT NULL,
    [User4]              CHAR (10)     NOT NULL,
    [User5]              FLOAT (53)    NOT NULL,
    [User6]              FLOAT (53)    NOT NULL,
    [User7]              SMALLDATETIME NOT NULL,
    [User8]              SMALLDATETIME NOT NULL,
    [Void]               SMALLINT      NOT NULL,
    [VoidMsg]            CHAR (50)     NOT NULL,
    [Zip]                CHAR (10)     NOT NULL,
    [tstamp]             ROWVERSION    NOT NULL,
    CONSTRAINT [XBankInfo0] PRIMARY KEY CLUSTERED ([CnyId] ASC, [Acct] ASC, [SubAcct] ASC) WITH (FILLFACTOR = 90)
);

