CREATE TABLE [dbo].[PJBSDET] (
    [acct]           CHAR (16)     NOT NULL,
    [amount]         FLOAT (53)    NOT NULL,
    [bd_id01]        CHAR (30)     NOT NULL,
    [bd_id02]        CHAR (30)     NOT NULL,
    [bd_id03]        CHAR (16)     NOT NULL,
    [bd_id04]        CHAR (16)     NOT NULL,
    [bd_id05]        CHAR (4)      NOT NULL,
    [bd_id06]        FLOAT (53)    NOT NULL,
    [bd_id07]        FLOAT (53)    NOT NULL,
    [bd_id08]        SMALLDATETIME NOT NULL,
    [bd_id09]        SMALLDATETIME NOT NULL,
    [bd_id10]        SMALLINT      NOT NULL,
    [bd_id11]        CHAR (30)     NOT NULL,
    [bd_id12]        CHAR (30)     NOT NULL,
    [bd_id13]        CHAR (30)     NOT NULL,
    [bd_id14]        CHAR (20)     NOT NULL,
    [bd_id15]        CHAR (10)     NOT NULL,
    [bd_id16]        CHAR (10)     NOT NULL,
    [bd_id17]        CHAR (10)     NOT NULL,
    [bd_id18]        CHAR (4)      NOT NULL,
    [bd_id19]        FLOAT (53)    NOT NULL,
    [bd_id20]        SMALLDATETIME NOT NULL,
    [comment]        CHAR (250)    NOT NULL,
    [CpnyId]         CHAR (10)     NOT NULL,
    [crtd_datetime]  SMALLDATETIME NOT NULL,
    [crtd_prog]      CHAR (8)      NOT NULL,
    [crtd_user]      CHAR (10)     NOT NULL,
    [draft_num]      CHAR (10)     NOT NULL,
    [employee]       CHAR (10)     NOT NULL,
    [fee_rate]       FLOAT (53)    NOT NULL,
    [labor_class_cd] CHAR (4)      NOT NULL,
    [linenbr]        SMALLINT      NOT NULL,
    [li_type]        CHAR (1)      NOT NULL,
    [lupd_datetime]  SMALLDATETIME NOT NULL,
    [lupd_prog]      CHAR (8)      NOT NULL,
    [lupd_user]      CHAR (10)     NOT NULL,
    [noteid]         INT           NOT NULL,
    [percent_detail] FLOAT (53)    NOT NULL,
    [pjt_entity]     CHAR (32)     NOT NULL,
    [post_date]      SMALLDATETIME NOT NULL,
    [post_date_est]  SMALLDATETIME NOT NULL,
    [post_period]    CHAR (6)      NOT NULL,
    [project]        CHAR (16)     NOT NULL,
    [project_line]   CHAR (16)     NOT NULL,
    [rate_type_cd]   CHAR (2)      NOT NULL,
    [rel_status]     CHAR (1)      NOT NULL,
    [schednbr]       CHAR (6)      NOT NULL,
    [taxid]          CHAR (10)     NOT NULL,
    [units]          FLOAT (53)    NOT NULL,
    [user1]          CHAR (30)     NOT NULL,
    [user2]          CHAR (30)     NOT NULL,
    [user3]          FLOAT (53)    NOT NULL,
    [user4]          FLOAT (53)    NOT NULL,
    [vendor_num]     CHAR (15)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [pjbsdet0] PRIMARY KEY CLUSTERED ([project] ASC, [schednbr] ASC, [linenbr] ASC)
);

