CREATE TABLE [dbo].[PJBILL] (
    [approval_sw]       CHAR (1)      NOT NULL,
    [approver]          CHAR (10)     NOT NULL,
    [BillCuryId]        CHAR (4)      NOT NULL,
    [biller]            CHAR (10)     NOT NULL,
    [billings_cycle_cd] CHAR (2)      NOT NULL,
    [billings_level]    CHAR (2)      NOT NULL,
    [bill_type_cd]      CHAR (4)      NOT NULL,
    [copy_num]          SMALLINT      NOT NULL,
    [crtd_datetime]     SMALLDATETIME NOT NULL,
    [crtd_prog]         CHAR (8)      NOT NULL,
    [crtd_user]         CHAR (10)     NOT NULL,
    [curyratetype]      CHAR (6)      NOT NULL,
    [date_print_cd]     CHAR (2)      NOT NULL,
    [fips_num]          CHAR (10)     NOT NULL,
    [inv_attach_cd]     CHAR (4)      NOT NULL,
    [inv_format_cd]     CHAR (4)      NOT NULL,
    [last_bill_date]    SMALLDATETIME NOT NULL,
    [lupd_datetime]     SMALLDATETIME NOT NULL,
    [lupd_prog]         CHAR (8)      NOT NULL,
    [lupd_user]         CHAR (10)     NOT NULL,
    [noteid]            INT           NOT NULL,
    [pb_id01]           CHAR (30)     NOT NULL,
    [pb_id02]           CHAR (30)     NOT NULL,
    [pb_id03]           CHAR (16)     NOT NULL,
    [pb_id04]           CHAR (16)     NOT NULL,
    [pb_id05]           CHAR (4)      NOT NULL,
    [pb_id06]           FLOAT (53)    NOT NULL,
    [pb_id07]           FLOAT (53)    NOT NULL,
    [pb_id08]           SMALLDATETIME NOT NULL,
    [pb_id09]           SMALLDATETIME NOT NULL,
    [pb_id10]           INT           NOT NULL,
    [pb_id11]           CHAR (30)     NOT NULL,
    [pb_id12]           CHAR (30)     NOT NULL,
    [pb_id13]           CHAR (4)      NOT NULL,
    [pb_id14]           CHAR (4)      NOT NULL,
    [pb_id15]           CHAR (4)      NOT NULL,
    [pb_id16]           CHAR (4)      NOT NULL,
    [pb_id17]           CHAR (2)      NOT NULL,
    [pb_id18]           CHAR (2)      NOT NULL,
    [pb_id19]           CHAR (2)      NOT NULL,
    [pb_id20]           CHAR (2)      NOT NULL,
    [project]           CHAR (16)     NOT NULL,
    [project_billwith]  CHAR (16)     NOT NULL,
    [retention_method]  CHAR (2)      NOT NULL,
    [retention_percent] FLOAT (53)    NOT NULL,
    [user1]             CHAR (30)     NOT NULL,
    [user2]             CHAR (30)     NOT NULL,
    [user3]             FLOAT (53)    NOT NULL,
    [user4]             FLOAT (53)    NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [pjbill0] PRIMARY KEY CLUSTERED ([project] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [pjbill1]
    ON [dbo].[PJBILL]([project_billwith] ASC) WITH (FILLFACTOR = 90);

