CREATE TABLE [dbo].[XDDSetUp] (
    [ACHCompanyID]        CHAR (30)     NOT NULL,
    [ACHCompanyName]      CHAR (30)     NOT NULL,
    [ACHCrLf]             CHAR (1)      NOT NULL,
    [ACHDelete]           CHAR (1)      NOT NULL,
    [ACHEntryClass]       CHAR (4)      NOT NULL,
    [ACHFileIDModifier]   CHAR (1)      NOT NULL,
    [ACHFileName]         CHAR (80)     NOT NULL,
    [ACHFillBlock]        CHAR (1)      NOT NULL,
    [ACHImmDest]          CHAR (30)     NOT NULL,
    [ACHImmDestN]         CHAR (30)     NOT NULL,
    [ACHImmOrig]          CHAR (30)     NOT NULL,
    [ACHImmOrigN]         CHAR (30)     NOT NULL,
    [ACHInclDR]           CHAR (1)      NOT NULL,
    [ACHInclDROverRide]   SMALLINT      NOT NULL,
    [ACHPreNote]          CHAR (1)      NOT NULL,
    [ACHRecord]           CHAR (1)      NOT NULL,
    [ACHTPZeroDollar]     CHAR (1)      NOT NULL,
    [APArchive]           SMALLINT      NOT NULL,
    [APArchiveNbr]        SMALLINT      NOT NULL,
    [APSetPmtMethod]      SMALLINT      NOT NULL,
    [ARACHDelete]         CHAR (1)      NOT NULL,
    [ARACHEntryClass]     CHAR (4)      NOT NULL,
    [ARACHFileName]       CHAR (80)     NOT NULL,
    [ARACHInclCR]         CHAR (1)      NOT NULL,
    [ARACHInclCROverRide] SMALLINT      NOT NULL,
    [ARACHPreNote]        CHAR (1)      NOT NULL,
    [ARACHRecord]         CHAR (1)      NOT NULL,
    [ARACHTPZeroDollar]   CHAR (1)      NOT NULL,
    [ARArchive]           SMALLINT      NOT NULL,
    [ARArchiveNbr]        SMALLINT      NOT NULL,
    [AREMARTran]          CHAR (1)      NOT NULL,
    [AREMAttachment]      CHAR (128)    NOT NULL,
    [AREMAutoWrap]        INT           NOT NULL,
    [AREMCpnyName]        CHAR (128)    NOT NULL,
    [AREMFromAddr]        CHAR (128)    NOT NULL,
    [AREMFromName]        CHAR (128)    NOT NULL,
    [AREMMessageBottom]   SMALLINT      NOT NULL,
    [AREMMessageTop]      SMALLINT      NOT NULL,
    [AREMPriority]        INT           NOT NULL,
    [AREMReplyToAddr]     CHAR (128)    NOT NULL,
    [AREMReplyToName]     CHAR (128)    NOT NULL,
    [AREMStubLayout]      CHAR (1)      NOT NULL,
    [AREMSubject]         CHAR (128)    NOT NULL,
    [AREMTUser1]          CHAR (30)     NOT NULL,
    [AREMTUser2]          CHAR (30)     NOT NULL,
    [AREMTUser3]          CHAR (30)     NOT NULL,
    [AREMTUser4]          CHAR (30)     NOT NULL,
    [AREMTUser5]          CHAR (30)     NOT NULL,
    [AREMTUser6]          CHAR (30)     NOT NULL,
    [AREMTUser7]          CHAR (30)     NOT NULL,
    [AREMTUser8]          CHAR (30)     NOT NULL,
    [AREMUser1]           CHAR (30)     NOT NULL,
    [AREMUser2]           CHAR (30)     NOT NULL,
    [AREMUser3]           CHAR (30)     NOT NULL,
    [AREMUser4]           CHAR (30)     NOT NULL,
    [AREMUser5]           CHAR (30)     NOT NULL,
    [AREMUser6]           CHAR (30)     NOT NULL,
    [AREMUser7]           CHAR (30)     NOT NULL,
    [AREMUser8]           CHAR (30)     NOT NULL,
    [ARHeadTrailID]       CHAR (1)      NOT NULL,
    [ARInvoicePrint]      CHAR (1)      NOT NULL,
    [ARPathACHScript]     CHAR (128)    NOT NULL,
    [ARPathArchive]       CHAR (128)    NOT NULL,
    [ARPmtBatchPrint]     SMALLINT      NOT NULL,
    [ARPmtBatchStatus]    CHAR (1)      NOT NULL,
    [ARPmtNbr]            CHAR (6)      NOT NULL,
    [ARPmtNbrPrefix]      CHAR (4)      NOT NULL,
    [ARSelInvOptDocTerms] SMALLINT      NOT NULL,
    [ARSelInvOptEFTElig]  SMALLINT      NOT NULL,
    [ARSetPmtMethod]      SMALLINT      NOT NULL,
    [ARShowEFTBatches]    SMALLINT      NOT NULL,
    [ARTermsID]           CHAR (2)      NOT NULL,
    [CommDevice]          CHAR (128)    NOT NULL,
    [CommEchoOn]          SMALLINT      NOT NULL,
    [CommLocation]        CHAR (128)    NOT NULL,
    [CommPhone]           CHAR (20)     NOT NULL,
    [CommPXferProto]      SMALLINT      NOT NULL,
    [CommSecProg]         CHAR (128)    NOT NULL,
    [CommService]         CHAR (40)     NOT NULL,
    [CommTermEmulation]   CHAR (1)      NOT NULL,
    [CommType]            CHAR (1)      NOT NULL,
    [CommUserProg]        CHAR (128)    NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [EMAPTran]            CHAR (1)      NOT NULL,
    [EMAttachment]        CHAR (128)    NOT NULL,
    [EMAutoWrap]          INT           NOT NULL,
    [EMCpnyName]          CHAR (128)    NOT NULL,
    [EMFromAddr]          CHAR (128)    NOT NULL,
    [EMFromName]          CHAR (128)    NOT NULL,
    [EMHeaderContent]     SMALLINT      NOT NULL,
    [EMHeaderDate]        SMALLINT      NOT NULL,
    [EMHeaderFrom]        SMALLINT      NOT NULL,
    [EMHeaderMessage]     SMALLINT      NOT NULL,
    [EMMailLog]           SMALLINT      NOT NULL,
    [EMMailPort]          INT           NOT NULL,
    [EMMailServer]        CHAR (128)    NOT NULL,
    [EMMailTimeOut]       INT           NOT NULL,
    [EMMessageBottom]     SMALLINT      NOT NULL,
    [EMMessageTop]        SMALLINT      NOT NULL,
    [EMPriority]          INT           NOT NULL,
    [EMReplyToAddr]       CHAR (128)    NOT NULL,
    [EMReplyToName]       CHAR (128)    NOT NULL,
    [EMSSLMode]           INT           NOT NULL,
    [EMStubLayout]        CHAR (1)      NOT NULL,
    [EMSubject]           CHAR (128)    NOT NULL,
    [EMTUser1]            CHAR (30)     NOT NULL,
    [EMTUser2]            CHAR (30)     NOT NULL,
    [EMTUser3]            CHAR (30)     NOT NULL,
    [EMTUser4]            CHAR (30)     NOT NULL,
    [EMTUser5]            CHAR (30)     NOT NULL,
    [EMTUser6]            CHAR (30)     NOT NULL,
    [EMTUser7]            CHAR (30)     NOT NULL,
    [EMTUser8]            CHAR (30)     NOT NULL,
    [EMUser1]             CHAR (30)     NOT NULL,
    [EMUser2]             CHAR (30)     NOT NULL,
    [EMUser3]             CHAR (30)     NOT NULL,
    [EMUser4]             CHAR (30)     NOT NULL,
    [EMUser5]             CHAR (30)     NOT NULL,
    [EMUser6]             CHAR (30)     NOT NULL,
    [EMUser7]             CHAR (30)     NOT NULL,
    [EMUser8]             CHAR (30)     NOT NULL,
    [ESMTPAccount]        CHAR (60)     NOT NULL,
    [ESMTPAuthMode]       INT           NOT NULL,
    [ESMTPDoNotAppend]    SMALLINT      NOT NULL,
    [ESMTPPassword]       CHAR (30)     NOT NULL,
    [ESMTPPipelining]     INT           NOT NULL,
    [HeadTrailID]         CHAR (1)      NOT NULL,
    [IExplorePath]        CHAR (128)    NOT NULL,
    [Init]                CHAR (1)      NOT NULL,
    [LBApplicMethod]      CHAR (2)      NOT NULL,
    [LBArchive]           SMALLINT      NOT NULL,
    [LBArchiveNbr]        SMALLINT      NOT NULL,
    [LBCommDevice]        CHAR (128)    NOT NULL,
    [LBCommEchoOn]        SMALLINT      NOT NULL,
    [LBCommLocation]      CHAR (128)    NOT NULL,
    [LBCommPhone]         CHAR (20)     NOT NULL,
    [LBCommPXferProto]    SMALLINT      NOT NULL,
    [LBCommTermEmulation] CHAR (1)      NOT NULL,
    [LBCommType]          CHAR (1)      NOT NULL,
    [LBCommUserProg]      CHAR (128)    NOT NULL,
    [LBDelete]            CHAR (1)      NOT NULL,
    [LBFileName]          CHAR (80)     NOT NULL,
    [LBMergeDataFile]     SMALLINT      NOT NULL,
    [LBNextBatNbr]        CHAR (6)      NOT NULL,
    [LBOnlyFullApplyGood] SMALLINT      NOT NULL,
    [LBPath]              CHAR (128)    NOT NULL,
    [LBPathArchive]       CHAR (128)    NOT NULL,
    [LBPmtBatchPrint]     SMALLINT      NOT NULL,
    [LBPmtBatchStatus]    CHAR (1)      NOT NULL,
    [LBPmtNbr]            CHAR (6)      NOT NULL,
    [LBPmtNbrPrefix]      CHAR (4)      NOT NULL,
    [LBSetPmtMethod]      SMALLINT      NOT NULL,
    [LBSuggCustGood]      SMALLINT      NOT NULL,
    [LBUseCheckDate]      SMALLINT      NOT NULL,
    [LBViewIDError]       CHAR (10)     NOT NULL,
    [LBViewIDApplic]      CHAR (10)     NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME NOT NULL,
    [LUpd_Prog]           CHAR (8)      NOT NULL,
    [LUpd_User]           CHAR (10)     NOT NULL,
    [NoteID]              INT           NOT NULL,
    [ModAPEFT]            CHAR (1)      NOT NULL,
    [ModAPEmail]          CHAR (1)      NOT NULL,
    [ModAREFT]            CHAR (1)      NOT NULL,
    [ModAREmail]          CHAR (1)      NOT NULL,
    [ModeBankSecurity]    SMALLINT      NOT NULL,
    [ModFormatID]         CHAR (15)     NOT NULL,
    [ModLockbox]          CHAR (1)      NOT NULL,
    [ModLockboxFormatID]  CHAR (15)     NOT NULL,
    [ModMultiCompany]     CHAR (1)      NOT NULL,
    [ModMultiFormatID]    CHAR (1)      NOT NULL,
    [ModPosPay]           CHAR (1)      NOT NULL,
    [ModPosPayFormatID]   CHAR (15)     NOT NULL,
    [ModTestAP]           CHAR (1)      NOT NULL,
    [ModTestAR]           CHAR (1)      NOT NULL,
    [ModTestWire]         CHAR (1)      NOT NULL,
    [ModWire]             CHAR (1)      NOT NULL,
    [ModWireEmail]        CHAR (1)      NOT NULL,
    [PathACHScript]       CHAR (128)    NOT NULL,
    [PathArchiveAP]       CHAR (128)    NOT NULL,
    [PPAP]                SMALLINT      NOT NULL,
    [PPAPCanChange]       SMALLINT      NOT NULL,
    [PPAPVoid]            SMALLINT      NOT NULL,
    [PPArchive]           SMALLINT      NOT NULL,
    [PPArchiveNbr]        SMALLINT      NOT NULL,
    [PPAuditRpt]          SMALLINT      NOT NULL,
    [PPCommDevice]        CHAR (128)    NOT NULL,
    [PPCommEchoOn]        SMALLINT      NOT NULL,
    [PPCommLocation]      CHAR (128)    NOT NULL,
    [PPCommPhone]         CHAR (20)     NOT NULL,
    [PPCommPXferProto]    SMALLINT      NOT NULL,
    [PPCommTermEmulation] CHAR (1)      NOT NULL,
    [PPCommType]          CHAR (1)      NOT NULL,
    [PPCommUserProg]      CHAR (128)    NOT NULL,
    [PPCrLf]              CHAR (1)      NOT NULL,
    [PPDelete]            CHAR (1)      NOT NULL,
    [PPFileName]          CHAR (80)     NOT NULL,
    [PPFillBlock]         CHAR (1)      NOT NULL,
    [PPHeadTrailID]       CHAR (1)      NOT NULL,
    [PPPath]              CHAR (128)    NOT NULL,
    [PPPathArchive]       CHAR (128)    NOT NULL,
    [PPPR]                SMALLINT      NOT NULL,
    [PPPRCanChange]       SMALLINT      NOT NULL,
    [PPPRVoid]            SMALLINT      NOT NULL,
    [PurgePeriodsAP]      SMALLINT      NOT NULL,
    [PurgePeriodsAR]      SMALLINT      NOT NULL,
    [RegAuthorizedUsers]  SMALLINT      NOT NULL,
    [RegCustomerID]       CHAR (10)     NOT NULL,
    [RegOptions]          CHAR (10)     NOT NULL,
    [RegPlatform]         CHAR (1)      NOT NULL,
    [RegUnlockKey]        CHAR (8)      NOT NULL,
    [RegVersion]          CHAR (10)     NOT NULL,
    [SecDisbursement]     SMALLINT      NOT NULL,
    [SecDSigner1Amt]      FLOAT (53)    NOT NULL,
    [SecDSigner1PW]       CHAR (30)     NOT NULL,
    [SecDSigner2Amt]      FLOAT (53)    NOT NULL,
    [SecDSigner2PW]       CHAR (30)     NOT NULL,
    [SecSeparation]       SMALLINT      NOT NULL,
    [SetUpID]             CHAR (2)      NOT NULL,
    [SKFuture01]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]          CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]          CHAR (10)     DEFAULT ('') NOT NULL,
    [User1]               CHAR (30)     NOT NULL,
    [User10]              CHAR (30)     NOT NULL,
    [User2]               CHAR (30)     NOT NULL,
    [User3]               FLOAT (53)    NOT NULL,
    [User4]               FLOAT (53)    NOT NULL,
    [User5]               CHAR (10)     NOT NULL,
    [User6]               CHAR (10)     NOT NULL,
    [User7]               SMALLDATETIME NOT NULL,
    [User8]               SMALLDATETIME NOT NULL,
    [User9]               CHAR (30)     NOT NULL,
    [WTArchive]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTArchiveNbr]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTCommType]          CHAR (1)      DEFAULT ('') NOT NULL,
    [WTCommUserProg]      CHAR (128)    DEFAULT ('') NOT NULL,
    [WTCrLf]              CHAR (1)      DEFAULT ('') NOT NULL,
    [WTDelete]            CHAR (1)      DEFAULT ('') NOT NULL,
    [WTFileName]          CHAR (80)     DEFAULT ('') NOT NULL,
    [WTFillBlock]         CHAR (1)      DEFAULT ('') NOT NULL,
    [WTHeadTrailID]       CHAR (1)      DEFAULT ('') NOT NULL,
    [WTPath]              CHAR (128)    DEFAULT ('') NOT NULL,
    [WTPathArchive]       CHAR (128)    DEFAULT ('') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [XDDSetup0] PRIMARY KEY CLUSTERED ([SetUpID] ASC)
);

