CREATE TABLE [dbo].[PJDOCNUM] (
    [AutoNum_labhdr]   SMALLINT      NOT NULL,
    [LastUsed_labhdr]  CHAR (10)     NOT NULL,
    [AutoNum_chargh]   SMALLINT      NOT NULL,
    [LastUsed_chargh]  CHAR (10)     NOT NULL,
    [AutoNum_alloc]    SMALLINT      NOT NULL,
    [LastUsed_alloc]   CHAR (10)     NOT NULL,
    [AutoNum_tran]     SMALLINT      NOT NULL,
    [LastUsed_tran]    CHAR (10)     NOT NULL,
    [AutoNum_foreign]  SMALLINT      NOT NULL,
    [LastUsed_foreign] CHAR (10)     NOT NULL,
    [AutoNum_revenue]  SMALLINT      NOT NULL,
    [LastUsed_revenue] CHAR (10)     NOT NULL,
    [AutoNum_1]        SMALLINT      NOT NULL,
    [LastUsed_1]       CHAR (10)     NOT NULL,
    [AutoNum_2]        SMALLINT      NOT NULL,
    [LastUsed_2]       CHAR (10)     NOT NULL,
    [AutoNum_3]        SMALLINT      NOT NULL,
    [LastUsed_3]       CHAR (10)     NOT NULL,
    [AutoNum_4]        SMALLINT      NOT NULL,
    [LastUsed_4]       CHAR (10)     NOT NULL,
    [AutoNum_5]        SMALLINT      NOT NULL,
    [LastUsed_5]       CHAR (10)     NOT NULL,
    [AutoNum_6]        SMALLINT      NOT NULL,
    [LastUsed_6]       CHAR (10)     NOT NULL,
    [AutoNum_7]        SMALLINT      NOT NULL,
    [LastUsed_7]       CHAR (10)     NOT NULL,
    [AutoNum_8]        SMALLINT      NOT NULL,
    [LastUsed_8]       CHAR (10)     NOT NULL,
    [AutoNum_9]        SMALLINT      NOT NULL,
    [LastUsed_9]       CHAR (10)     NOT NULL,
    [AutoNum_10]       SMALLINT      NOT NULL,
    [LastUsed_10]      CHAR (10)     NOT NULL,
    [AutoNum_11]       SMALLINT      NOT NULL,
    [LastUsed_11]      CHAR (10)     NOT NULL,
    [AutoNum_12]       SMALLINT      NOT NULL,
    [LastUsed_12]      CHAR (10)     NOT NULL,
    [Id]               CHAR (10)     NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME NOT NULL,
    [Crtd_Prog]        CHAR (8)      NOT NULL,
    [Crtd_User]        CHAR (10)     NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME NOT NULL,
    [LUpd_Prog]        CHAR (8)      NOT NULL,
    [LUpd_User]        CHAR (10)     NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [pjdocnum0] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 90)
);

