CREATE TABLE [dbo].[PJTIMWRK] (
    [Corrections]      CHAR (1)      NOT NULL,
    [employee]         CHAR (10)     NOT NULL,
    [emp_name]         CHAR (60)     NOT NULL,
    [Hired]            SMALLDATETIME NOT NULL,
    [Linenbr]          SMALLINT      NOT NULL,
    [Manager]          CHAR (10)     NOT NULL,
    [MgrName]          CHAR (60)     NOT NULL,
    [Org]              CHAR (24)     NOT NULL,
    [Report_accessnbr] CHAR (10)     NOT NULL,
    [Select_By]        CHAR (1)      NOT NULL,
    [Status_select]    CHAR (10)     NOT NULL,
    [Status_01]        CHAR (1)      NOT NULL,
    [Status_02]        CHAR (1)      NOT NULL,
    [Status_03]        CHAR (1)      NOT NULL,
    [Status_04]        CHAR (1)      NOT NULL,
    [Status_05]        CHAR (1)      NOT NULL,
    [Status_06]        CHAR (1)      NOT NULL,
    [Status_07]        CHAR (1)      NOT NULL,
    [Status_08]        CHAR (1)      NOT NULL,
    [Status_09]        CHAR (1)      NOT NULL,
    [Status_10]        CHAR (1)      NOT NULL,
    [Status_11]        CHAR (1)      NOT NULL,
    [Status_12]        CHAR (1)      NOT NULL,
    [Status_13]        CHAR (1)      NOT NULL,
    [Status_14]        CHAR (1)      NOT NULL,
    [Status_15]        CHAR (1)      NOT NULL,
    [Status_16]        CHAR (1)      NOT NULL,
    [Status_17]        CHAR (1)      NOT NULL,
    [Status_18]        CHAR (1)      NOT NULL,
    [Status_19]        CHAR (1)      NOT NULL,
    [Status_20]        CHAR (1)      NOT NULL,
    [Status_21]        CHAR (1)      NOT NULL,
    [Status_22]        CHAR (1)      NOT NULL,
    [Status_23]        CHAR (1)      NOT NULL,
    [Status_24]        CHAR (1)      NOT NULL,
    [Status_25]        CHAR (1)      NOT NULL,
    [Status_26]        CHAR (1)      NOT NULL,
    [Status_27]        CHAR (1)      NOT NULL,
    [Status_28]        CHAR (1)      NOT NULL,
    [Status_29]        CHAR (1)      NOT NULL,
    [Status_30]        CHAR (1)      NOT NULL,
    [Status_31]        CHAR (1)      NOT NULL,
    [Status_32]        CHAR (1)      NOT NULL,
    [Status_33]        CHAR (1)      NOT NULL,
    [Status_34]        CHAR (1)      NOT NULL,
    [Status_35]        CHAR (1)      NOT NULL,
    [Supervisor]       CHAR (10)     NOT NULL,
    [SupName]          CHAR (60)     NOT NULL,
    [Term]             SMALLDATETIME NOT NULL,
    [WeekEnding]       SMALLDATETIME NOT NULL,
    [WeekEndingCol_01] SMALLDATETIME NOT NULL,
    [WeekEndingCol_02] SMALLDATETIME NOT NULL,
    [WeekEndingCol_03] SMALLDATETIME NOT NULL,
    [WeekEndingCol_04] SMALLDATETIME NOT NULL,
    [WeekEndingCol_05] SMALLDATETIME NOT NULL,
    [WeekEndingCol_06] SMALLDATETIME NOT NULL,
    [WeekEndingCol_07] SMALLDATETIME NOT NULL,
    [WeekEndingCol_08] SMALLDATETIME NOT NULL,
    [WeekEndingCol_09] SMALLDATETIME NOT NULL,
    [WeekEndingCol_10] SMALLDATETIME NOT NULL,
    [WeekEndingCol_11] SMALLDATETIME NOT NULL,
    [WeekEndingCol_12] SMALLDATETIME NOT NULL,
    [WeekEndingCol_13] SMALLDATETIME NOT NULL,
    [WeekEndingCol_14] SMALLDATETIME NOT NULL,
    [WeekEndingCol_15] SMALLDATETIME NOT NULL,
    [WeekEndingCol_16] SMALLDATETIME NOT NULL,
    [WeekEndingCol_17] SMALLDATETIME NOT NULL,
    [WeekEndingCol_18] SMALLDATETIME NOT NULL,
    [WeekEndingCol_19] SMALLDATETIME NOT NULL,
    [WeekEndingCol_20] SMALLDATETIME NOT NULL,
    [WeekEndingCol_21] SMALLDATETIME NOT NULL,
    [WeekEndingCol_22] SMALLDATETIME NOT NULL,
    [WeekEndingCol_23] SMALLDATETIME NOT NULL,
    [WeekEndingCol_24] SMALLDATETIME NOT NULL,
    [WeekEndingCol_25] SMALLDATETIME NOT NULL,
    [WeekEndingCol_26] SMALLDATETIME NOT NULL,
    [WeekEndingCol_27] SMALLDATETIME NOT NULL,
    [WeekEndingCol_28] SMALLDATETIME NOT NULL,
    [WeekEndingCol_29] SMALLDATETIME NOT NULL,
    [WeekEndingCol_30] SMALLDATETIME NOT NULL,
    [WeekEndingCol_31] SMALLDATETIME NOT NULL,
    [WeekEndingCol_32] SMALLDATETIME NOT NULL,
    [WeekEndingCol_33] SMALLDATETIME NOT NULL,
    [WeekEndingCol_34] SMALLDATETIME NOT NULL,
    [WeekEndingCol_35] SMALLDATETIME NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [pjtimwrk0] PRIMARY KEY CLUSTERED ([Report_accessnbr] ASC, [Linenbr] ASC)
);

