CREATE TABLE [dbo].[SOShipPack] (
    [BaseCost]         FLOAT (53)    CONSTRAINT [DF_SOShipPack_BaseCost] DEFAULT ((0)) NOT NULL,
    [BaseInvc]         FLOAT (53)    CONSTRAINT [DF_SOShipPack_BaseInvc] DEFAULT ((0)) NOT NULL,
    [BoxRef]           CHAR (5)      CONSTRAINT [DF_SOShipPack_BoxRef] DEFAULT (' ') NOT NULL,
    [CartonID]         CHAR (20)     CONSTRAINT [DF_SOShipPack_CartonID] DEFAULT (' ') NOT NULL,
    [CODAmt]           FLOAT (53)    CONSTRAINT [DF_SOShipPack_CODAmt] DEFAULT ((0)) NOT NULL,
    [CODCost]          FLOAT (53)    CONSTRAINT [DF_SOShipPack_CODCost] DEFAULT ((0)) NOT NULL,
    [CODInvc]          FLOAT (53)    CONSTRAINT [DF_SOShipPack_CODInvc] DEFAULT ((0)) NOT NULL,
    [ContainerID]      CHAR (10)     CONSTRAINT [DF_SOShipPack_ContainerID] DEFAULT (' ') NOT NULL,
    [CpnyID]           CHAR (10)     CONSTRAINT [DF_SOShipPack_CpnyID] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_SOShipPack_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_SOShipPack_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_SOShipPack_Crtd_User] DEFAULT (' ') NOT NULL,
    [CuryBaseCost]     FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryBaseCost] DEFAULT ((0)) NOT NULL,
    [CuryBaseInvc]     FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryBaseInvc] DEFAULT ((0)) NOT NULL,
    [CuryCODAmt]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryCODAmt] DEFAULT ((0)) NOT NULL,
    [CuryCODCost]      FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryCODCost] DEFAULT ((0)) NOT NULL,
    [CuryCODInvc]      FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryCODInvc] DEFAULT ((0)) NOT NULL,
    [CuryFrtCost]      FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryFrtCost] DEFAULT ((0)) NOT NULL,
    [CuryFrtInvc]      FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryFrtInvc] DEFAULT ((0)) NOT NULL,
    [CuryHandlingChg]  FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryHandlingChg] DEFAULT ((0)) NOT NULL,
    [CuryInsureCost]   FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryInsureCost] DEFAULT ((0)) NOT NULL,
    [CuryInsureInvc]   FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryInsureInvc] DEFAULT ((0)) NOT NULL,
    [CuryOtherCost]    FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryOtherCost] DEFAULT ((0)) NOT NULL,
    [CuryOtherInvc]    FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryOtherInvc] DEFAULT ((0)) NOT NULL,
    [CuryOversizeCost] FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryOversizeCost] DEFAULT ((0)) NOT NULL,
    [CuryOversizeInvc] FLOAT (53)    CONSTRAINT [DF_SOShipPack_CuryOversizeInvc] DEFAULT ((0)) NOT NULL,
    [FrtCost]          FLOAT (53)    CONSTRAINT [DF_SOShipPack_FrtCost] DEFAULT ((0)) NOT NULL,
    [FrtInvc]          FLOAT (53)    CONSTRAINT [DF_SOShipPack_FrtInvc] DEFAULT ((0)) NOT NULL,
    [HandlingChg]      FLOAT (53)    CONSTRAINT [DF_SOShipPack_HandlingChg] DEFAULT ((0)) NOT NULL,
    [InsureCost]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_InsureCost] DEFAULT ((0)) NOT NULL,
    [InsureInvc]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_InsureInvc] DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]    SMALLDATETIME CONSTRAINT [DF_SOShipPack_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]        CHAR (8)      CONSTRAINT [DF_SOShipPack_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUpd_User]        CHAR (10)     CONSTRAINT [DF_SOShipPack_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]           INT           CONSTRAINT [DF_SOShipPack_NoteID] DEFAULT ((0)) NOT NULL,
    [OtherCost]        FLOAT (53)    CONSTRAINT [DF_SOShipPack_OtherCost] DEFAULT ((0)) NOT NULL,
    [OtherInvc]        FLOAT (53)    CONSTRAINT [DF_SOShipPack_OtherInvc] DEFAULT ((0)) NOT NULL,
    [OversizeCost]     FLOAT (53)    CONSTRAINT [DF_SOShipPack_OversizeCost] DEFAULT ((0)) NOT NULL,
    [OversizeInvc]     FLOAT (53)    CONSTRAINT [DF_SOShipPack_OversizeInvc] DEFAULT ((0)) NOT NULL,
    [PackageID]        CHAR (15)     CONSTRAINT [DF_SOShipPack_PackageID] DEFAULT (' ') NOT NULL,
    [PalletID]         CHAR (20)     CONSTRAINT [DF_SOShipPack_PalletID] DEFAULT (' ') NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_SOShipPack_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_SOShipPack_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_SOShipPack_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_SOShipPack_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_SOShipPack_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_SOShipPack_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_SOShipPack_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_SOShipPack_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_SOShipPack_S4Future12] DEFAULT (' ') NOT NULL,
    [ShipperID]        CHAR (15)     CONSTRAINT [DF_SOShipPack_ShipperID] DEFAULT (' ') NOT NULL,
    [TrackingNbr]      CHAR (20)     CONSTRAINT [DF_SOShipPack_TrackingNbr] DEFAULT (' ') NOT NULL,
    [TruckID]          CHAR (18)     CONSTRAINT [DF_SOShipPack_TruckID] DEFAULT (' ') NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_SOShipPack_User1] DEFAULT (' ') NOT NULL,
    [User10]           SMALLDATETIME CONSTRAINT [DF_SOShipPack_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_SOShipPack_User2] DEFAULT (' ') NOT NULL,
    [User3]            CHAR (30)     CONSTRAINT [DF_SOShipPack_User3] DEFAULT (' ') NOT NULL,
    [User4]            CHAR (30)     CONSTRAINT [DF_SOShipPack_User4] DEFAULT (' ') NOT NULL,
    [User5]            FLOAT (53)    CONSTRAINT [DF_SOShipPack_User5] DEFAULT ((0)) NOT NULL,
    [User6]            FLOAT (53)    CONSTRAINT [DF_SOShipPack_User6] DEFAULT ((0)) NOT NULL,
    [User7]            CHAR (10)     CONSTRAINT [DF_SOShipPack_User7] DEFAULT (' ') NOT NULL,
    [User8]            CHAR (10)     CONSTRAINT [DF_SOShipPack_User8] DEFAULT (' ') NOT NULL,
    [User9]            SMALLDATETIME CONSTRAINT [DF_SOShipPack_User9] DEFAULT ('01/01/1900') NOT NULL,
    [Volume]           FLOAT (53)    CONSTRAINT [DF_SOShipPack_Volume] DEFAULT ((0)) NOT NULL,
    [Wght]             FLOAT (53)    CONSTRAINT [DF_SOShipPack_Wght] DEFAULT ((0)) NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [SOShipPack0] PRIMARY KEY CLUSTERED ([CpnyID] ASC, [ShipperID] ASC, [BoxRef] ASC) WITH (FILLFACTOR = 90)
);

