CREATE TABLE [dbo].[ANSetup] (
    [Active]           SMALLINT      CONSTRAINT [DF_ANSetup_Active] DEFAULT ((0)) NOT NULL,
    [AutoBOL]          SMALLINT      CONSTRAINT [DF_ANSetup_AutoBOL] DEFAULT ((0)) NOT NULL,
    [AutoContainer]    SMALLINT      CONSTRAINT [DF_ANSetup_AutoContainer] DEFAULT ((0)) NOT NULL,
    [AutoLabel]        SMALLINT      CONSTRAINT [DF_ANSetup_AutoLabel] DEFAULT ((0)) NOT NULL,
    [CalcDim]          SMALLINT      CONSTRAINT [DF_ANSetup_CalcDim] DEFAULT ((0)) NOT NULL,
    [CalcWeight]       SMALLINT      CONSTRAINT [DF_ANSetup_CalcWeight] DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_ANSetup_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]        CHAR (8)      CONSTRAINT [DF_ANSetup_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_User]        CHAR (10)     CONSTRAINT [DF_ANSetup_Crtd_User] DEFAULT (' ') NOT NULL,
    [Inbound945Path]   CHAR (255)    CONSTRAINT [DF_ANSetup_Inbound945Path] DEFAULT (' ') NOT NULL,
    [LabelAtRelease]   SMALLINT      CONSTRAINT [DF_ANSetup_LabelAtRelease] DEFAULT ((0)) NOT NULL,
    [LabelDbPath]      CHAR (255)    CONSTRAINT [DF_ANSetup_LabelDbPath] DEFAULT (' ') NOT NULL,
    [LabelSoftPath]    CHAR (255)    CONSTRAINT [DF_ANSetup_LabelSoftPath] DEFAULT (' ') NOT NULL,
    [LastBOL]          CHAR (20)     CONSTRAINT [DF_ANSetup_LastBOL] DEFAULT (' ') NOT NULL,
    [LastLabelNbr]     CHAR (10)     CONSTRAINT [DF_ANSetup_LastLabelNbr] DEFAULT (' ') NOT NULL,
    [LastSerContainer] CHAR (10)     CONSTRAINT [DF_ANSetup_LastSerContainer] DEFAULT (' ') NOT NULL,
    [Lupd_DateTime]    SMALLDATETIME CONSTRAINT [DF_ANSetup_Lupd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [Lupd_Prog]        CHAR (8)      CONSTRAINT [DF_ANSetup_Lupd_Prog] DEFAULT (' ') NOT NULL,
    [Lupd_User]        CHAR (10)     CONSTRAINT [DF_ANSetup_Lupd_User] DEFAULT (' ') NOT NULL,
    [MatchShipQty]     SMALLINT      CONSTRAINT [DF_ANSetup_MatchShipQty] DEFAULT ((0)) NOT NULL,
    [MfgID]            CHAR (20)     CONSTRAINT [DF_ANSetup_MfgID] DEFAULT (' ') NOT NULL,
    [PerNbr]           CHAR (6)      CONSTRAINT [DF_ANSetup_PerNbr] DEFAULT (' ') NOT NULL,
    [PrintOnSave]      SMALLINT      CONSTRAINT [DF_ANSetup_PrintOnSave] DEFAULT ((0)) NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_ANSetup_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_ANSetup_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_ANSetup_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_ANSetup_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_ANSetup_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_ANSetup_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_ANSetup_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_ANSetup_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_ANSetup_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_ANSetup_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_ANSetup_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_ANSetup_S4Future12] DEFAULT (' ') NOT NULL,
    [SetupID]          CHAR (2)      CONSTRAINT [DF_ANSetup_SetupID] DEFAULT (' ') NOT NULL,
    [SingleContainer]  SMALLINT      CONSTRAINT [DF_ANSetup_SingleContainer] DEFAULT ((0)) NOT NULL,
    [StdCartonBreak]   SMALLINT      CONSTRAINT [DF_ANSetup_StdCartonBreak] DEFAULT ((0)) NOT NULL,
    [TreeView]         SMALLINT      CONSTRAINT [DF_ANSetup_TreeView] DEFAULT ((0)) NOT NULL,
    [User1]            CHAR (30)     CONSTRAINT [DF_ANSetup_User1] DEFAULT (' ') NOT NULL,
    [User10]           SMALLDATETIME CONSTRAINT [DF_ANSetup_User10] DEFAULT ('01/01/1900') NOT NULL,
    [User2]            CHAR (30)     CONSTRAINT [DF_ANSetup_User2] DEFAULT (' ') NOT NULL,
    [User3]            CHAR (30)     CONSTRAINT [DF_ANSetup_User3] DEFAULT (' ') NOT NULL,
    [User4]            CHAR (30)     CONSTRAINT [DF_ANSetup_User4] DEFAULT (' ') NOT NULL,
    [User5]            FLOAT (53)    CONSTRAINT [DF_ANSetup_User5] DEFAULT ((0)) NOT NULL,
    [User6]            FLOAT (53)    CONSTRAINT [DF_ANSetup_User6] DEFAULT ((0)) NOT NULL,
    [User7]            CHAR (10)     CONSTRAINT [DF_ANSetup_User7] DEFAULT (' ') NOT NULL,
    [User8]            CHAR (10)     CONSTRAINT [DF_ANSetup_User8] DEFAULT (' ') NOT NULL,
    [User9]            SMALLDATETIME CONSTRAINT [DF_ANSetup_User9] DEFAULT ('01/01/1900') NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [ANSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

