CREATE TABLE [dbo].[IN10400_Return] (
    [BatchType]        CHAR (1)      CONSTRAINT [DF_IN10400_Return_BatchType] DEFAULT (' ') NOT NULL,
    [BatNbr]           CHAR (10)     CONSTRAINT [DF_IN10400_Return_BatNbr] DEFAULT (' ') NOT NULL,
    [COGSBatchCreated] SMALLINT      CONSTRAINT [DF_IN10400_Return_COGSBatchCreated] DEFAULT ((0)) NOT NULL,
    [ComputerName]     CHAR (21)     CONSTRAINT [DF_IN10400_Return_ComputerName] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]    SMALLDATETIME CONSTRAINT [DF_IN10400_Return_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [MsgID]            INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MsgNbr]           SMALLINT      CONSTRAINT [DF_IN10400_Return_MsgNbr] DEFAULT ((0)) NOT NULL,
    [MsgType]          CHAR (1)      CONSTRAINT [DF_IN10400_Return_MsgType] DEFAULT (' ') NOT NULL,
    [Parm00]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm00] DEFAULT (' ') NOT NULL,
    [Parm01]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm01] DEFAULT (' ') NOT NULL,
    [Parm02]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm02] DEFAULT (' ') NOT NULL,
    [Parm03]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm03] DEFAULT (' ') NOT NULL,
    [Parm04]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm04] DEFAULT (' ') NOT NULL,
    [Parm05]           CHAR (30)     CONSTRAINT [DF_IN10400_Return_Parm05] DEFAULT (' ') NOT NULL,
    [ParmCnt]          SMALLINT      CONSTRAINT [DF_IN10400_Return_ParmCnt] DEFAULT ((0)) NOT NULL,
    [S4Future01]       CHAR (30)     CONSTRAINT [DF_IN10400_Return_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]       CHAR (30)     CONSTRAINT [DF_IN10400_Return_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]       FLOAT (53)    CONSTRAINT [DF_IN10400_Return_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]       FLOAT (53)    CONSTRAINT [DF_IN10400_Return_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]       FLOAT (53)    CONSTRAINT [DF_IN10400_Return_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]       FLOAT (53)    CONSTRAINT [DF_IN10400_Return_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]       SMALLDATETIME CONSTRAINT [DF_IN10400_Return_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]       SMALLDATETIME CONSTRAINT [DF_IN10400_Return_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]       INT           CONSTRAINT [DF_IN10400_Return_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]       INT           CONSTRAINT [DF_IN10400_Return_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]       CHAR (10)     CONSTRAINT [DF_IN10400_Return_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]       CHAR (10)     CONSTRAINT [DF_IN10400_Return_S4Future12] DEFAULT (' ') NOT NULL,
    [SQLErrorNbr]      SMALLINT      CONSTRAINT [DF_IN10400_Return_SQLErrorNbr] DEFAULT ((0)) NOT NULL,
    [tstamp]           ROWVERSION    NOT NULL,
    CONSTRAINT [IN10400_Return0] PRIMARY KEY CLUSTERED ([ComputerName] ASC, [MsgID] ASC) WITH (FILLFACTOR = 90)
);

