CREATE TABLE [dbo].[PJALLSRT] (
    [acct]                CHAR (16)     NOT NULL,
    [alloc_batch]         CHAR (10)     NOT NULL,
    [allsrt_key]          INT           NOT NULL,
    [amount]              FLOAT (53)    NOT NULL,
    [bill_batch_id]       CHAR (10)     NOT NULL,
    [bill_detail_sw]      CHAR (1)      NOT NULL,
    [billable_sw]         CHAR (1)      NOT NULL,
    [cpnyId]              CHAR (10)     NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [CuryEffDate]         SMALLDATETIME NOT NULL,
    [CuryId]              CHAR (4)      NOT NULL,
    [CuryMultDiv]         CHAR (1)      NOT NULL,
    [CuryRate]            FLOAT (53)    NOT NULL,
    [CuryRateType]        CHAR (6)      NOT NULL,
    [CuryTranAmt]         FLOAT (53)    NOT NULL,
    [data1]               CHAR (10)     NOT NULL,
    [data2]               CHAR (30)     NOT NULL,
    [data3]               CHAR (30)     NOT NULL,
    [data4]               CHAR (30)     NOT NULL,
    [data5]               CHAR (10)     NOT NULL,
    [employee]            CHAR (10)     NOT NULL,
    [gl_acct]             CHAR (10)     NOT NULL,
    [gl_offset_acct]      CHAR (10)     NOT NULL,
    [gl_offset_cpnyId]    CHAR (10)     NOT NULL,
    [gl_offset_subacct]   CHAR (24)     NOT NULL,
    [gl_subacct]          CHAR (24)     NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME NOT NULL,
    [LUpd_Prog]           CHAR (8)      NOT NULL,
    [LUpd_User]           CHAR (10)     NOT NULL,
    [pjt_entity]          CHAR (32)     NOT NULL,
    [ProjCury_amount]     FLOAT (53)    NOT NULL,
    [ProjCuryId]          CHAR (4)      NOT NULL,
    [ProjCuryMultiDiv]    CHAR (1)      NOT NULL,
    [ProjCuryRate]        FLOAT (53)    NOT NULL,
    [ProjCuryRateType]    CHAR (6)      NOT NULL,
    [project]             CHAR (16)     NOT NULL,
    [src_acct_cat]        CHAR (16)     NOT NULL,
    [src_alloc_meth_cd]   CHAR (4)      NOT NULL,
    [src_alloc_meth_step] SMALLINT      NOT NULL,
    [src_amount]          FLOAT (53)    NOT NULL,
    [src_batch_id]        CHAR (10)     NOT NULL,
    [src_comment]         CHAR (100)    NOT NULL,
    [src_detail_num]      INT           NOT NULL,
    [src_fiscalno]        CHAR (6)      NOT NULL,
    [src_labor_class]     CHAR (4)      NOT NULL,
    [src_pjt_entity]      CHAR (32)     NOT NULL,
    [src_ProjCury_amount] FLOAT (53)    NOT NULL,
    [src_project]         CHAR (16)     NOT NULL,
    [src_system_cd]       CHAR (2)      NOT NULL,
    [src_trans_date]      SMALLDATETIME NOT NULL,
    [src_units]           FLOAT (53)    NOT NULL,
    [src_vendor]          CHAR (15)     NOT NULL,
    [src_voucher_line]    INT           NOT NULL,
    [src_voucher_num]     CHAR (10)     NOT NULL,
    [SubTask_Name]        CHAR (50)     NOT NULL,
    [tr_id01]             CHAR (30)     NOT NULL,
    [tr_id02]             CHAR (30)     NOT NULL,
    [tr_id03]             CHAR (16)     NOT NULL,
    [tr_id04]             CHAR (16)     NOT NULL,
    [tr_id05]             CHAR (4)      NOT NULL,
    [tr_id06]             FLOAT (53)    NOT NULL,
    [tr_id07]             FLOAT (53)    NOT NULL,
    [tr_id08]             SMALLDATETIME NOT NULL,
    [tr_id09]             SMALLDATETIME NOT NULL,
    [tr_id10]             INT           NOT NULL,
    [tr_id23]             CHAR (30)     NOT NULL,
    [tr_id24]             CHAR (20)     NOT NULL,
    [tr_id25]             CHAR (20)     NOT NULL,
    [tr_id26]             CHAR (10)     NOT NULL,
    [tr_id27]             CHAR (4)      NOT NULL,
    [tr_id28]             FLOAT (53)    NOT NULL,
    [tr_id29]             SMALLDATETIME NOT NULL,
    [tr_id30]             INT           NOT NULL,
    [tr_id31]             FLOAT (53)    NOT NULL,
    [tr_id32]             FLOAT (53)    NOT NULL,
    [unit_of_measure]     CHAR (10)     NOT NULL,
    [units]               FLOAT (53)    NOT NULL,
    [user1]               CHAR (30)     NOT NULL,
    [user2]               CHAR (30)     NOT NULL,
    [user3]               FLOAT (53)    NOT NULL,
    [user4]               FLOAT (53)    NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [pjallsrt0] PRIMARY KEY NONCLUSTERED ([alloc_batch] ASC, [allsrt_key] ASC)
);


GO
CREATE CLUSTERED INDEX [pjallsrt1]
    ON [dbo].[PJALLSRT]([alloc_batch] ASC, [src_project] ASC, [project] ASC, [pjt_entity] ASC, [acct] ASC, [cpnyId] ASC, [employee] ASC, [gl_subacct] ASC);

