CREATE TABLE [dbo].[XDDSetUpEx] (
    [AcctApp]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [ACHOrigDFI]          CHAR (9)      DEFAULT ('') NOT NULL,
    [ACHOrigDFIName]      CHAR (35)     DEFAULT ('') NOT NULL,
    [APAmtAppLvl1Amt]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [APAmtAppLvl1NbrA]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [APAmtAppLvl2Amt]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [APAmtAppLvl2NbrA]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [APAmtAppUserSetsApp] CHAR (47)     DEFAULT ('') NOT NULL,
    [APAPO]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [APAPOComm]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [APAPOFileNbrg]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APAPONextFileNbr]    CHAR (6)      DEFAULT ('') NOT NULL,
    [APAPOPreNotesOne]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEFTNoOrphanChk]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEFTPrintAudit]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEFTPrintAuditChg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachByA]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachByV]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachFExt]      CHAR (10)     DEFAULT ('') NOT NULL,
    [APEMAttachFF]        CHAR (1)      DEFAULT ('') NOT NULL,
    [APEMAttachFN]        CHAR (50)     DEFAULT ('') NOT NULL,
    [APEMAttachFND]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachFNI]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachFNote]     CHAR (100)    DEFAULT ('') NOT NULL,
    [APEMAttachFRL]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachInclBMsg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachInclTMsg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachNbrDocs]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [APEMAttachSP]        CHAR (50)     DEFAULT ('') NOT NULL,
    [APEMAttachUse]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [APFileHideCompBatch] SMALLINT      DEFAULT ((0)) NOT NULL,
    [APFileNameAddDate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [APFileNameAddEBNbr]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [APFileNameCanChange] SMALLINT      DEFAULT ((0)) NOT NULL,
    [APFileNameConnector] CHAR (1)      DEFAULT ('') NOT NULL,
    [APFilePeriodsRet]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [APGatewayOperID]     CHAR (9)      DEFAULT ('') NOT NULL,
    [APShowPosted]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTNoOrphanChk]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTPrintAudit]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREFTPrintAuditChg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachByA]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachByC]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachFExt]      CHAR (10)     DEFAULT ('') NOT NULL,
    [AREMAttachFF]        CHAR (1)      DEFAULT ('') NOT NULL,
    [AREMAttachFN]        CHAR (50)     DEFAULT ('') NOT NULL,
    [AREMAttachFND]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachFNI]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachFNote]     CHAR (100)    DEFAULT ('') NOT NULL,
    [AREMAttachFRL]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachInclBMsg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachInclTMsg]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachNbrDocs]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [AREMAttachSP]        CHAR (50)     DEFAULT ('') NOT NULL,
    [AREMAttachUse]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARFileHideCompBatch] SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARFileNameAddDate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARFileNameAddEBNbr]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARFileNameCanChange] SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARFileNameConnector] CHAR (1)      DEFAULT ('') NOT NULL,
    [ARFilePeriodsRet]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [ARNextFileNbr]       CHAR (6)      DEFAULT ('') NOT NULL,
    [ARShowPosted]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [Crtd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [Crtd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [EMASBurstDelay]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [EMASEmailsInBurst]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [LBAddMissingCM]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [LBAlwaysApplyDisc]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [LBErrorShowChgdPmt]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [LBFilePeriodsRet]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]           CHAR (8)      DEFAULT ('') NOT NULL,
    [LUpd_User]           CHAR (10)     DEFAULT ('') NOT NULL,
    [MultiVendAcct]       CHAR (10)     DEFAULT ('') NOT NULL,
    [MultiVendAcctUse]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [NoteID]              INT           DEFAULT ((0)) NOT NULL,
    [PPFileHideCompBatch] SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPFileNameAddDate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPFileNameAddEBNbr]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPFileNameCanChange] SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPFileNameConnector] CHAR (1)      DEFAULT ('') NOT NULL,
    [PPFilePeriodsRet]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [PPNextFileNbr]       CHAR (6)      DEFAULT ('') NOT NULL,
    [PPShowPosted]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [SecurityMsgOff]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [SetUpID]             CHAR (2)      DEFAULT ('') NOT NULL,
    [SKFuture01]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture02]          CHAR (30)     DEFAULT ('') NOT NULL,
    [SKFuture03]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture04]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture05]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture06]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SKFuture07]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture08]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [SKFuture09]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture10]          INT           DEFAULT ((0)) NOT NULL,
    [SKFuture11]          CHAR (10)     DEFAULT ('') NOT NULL,
    [SKFuture12]          CHAR (10)     DEFAULT ('') NOT NULL,
    [User1]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User10]              CHAR (30)     DEFAULT ('') NOT NULL,
    [User2]               CHAR (30)     DEFAULT ('') NOT NULL,
    [User3]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User6]               CHAR (10)     DEFAULT ('') NOT NULL,
    [User7]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]               SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User9]               CHAR (30)     DEFAULT ('') NOT NULL,
    [WTDefaultOrdParty]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTFileNameAddDate]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTFileNameAddEBNbr]  SMALLINT      DEFAULT ((0)) NOT NULL,
    [WTFileNameConnector] CHAR (1)      DEFAULT ('') NOT NULL,
    [tstamp]              ROWVERSION    NOT NULL,
    CONSTRAINT [XDDSetupEx0] PRIMARY KEY CLUSTERED ([SetUpID] ASC)
);

