CREATE TABLE [dbo].[WOAcctCategXRef] (
    [Acct]           CHAR (16)     CONSTRAINT [DF_WOAcctCategXRef_Acct] DEFAULT (' ') NOT NULL,
    [Acct_Comp]      CHAR (16)     CONSTRAINT [DF_WOAcctCategXRef_Acct_Comp] DEFAULT (' ') NOT NULL,
    [BOMCostClass]   CHAR (1)      CONSTRAINT [DF_WOAcctCategXRef_BOMCostClass] DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_Crtd_DateTime] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_Prog]      CHAR (8)      CONSTRAINT [DF_WOAcctCategXRef_Crtd_Prog] DEFAULT (' ') NOT NULL,
    [Crtd_Time]      SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_Crtd_Time] DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),0),0))) NOT NULL,
    [Crtd_User]      CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_Crtd_User] DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_LUpd_DateTime] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]      CHAR (8)      CONSTRAINT [DF_WOAcctCategXRef_LUpd_Prog] DEFAULT (' ') NOT NULL,
    [LUPd_Time]      SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_LUPd_Time] DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_User]      CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_LUpd_User] DEFAULT (' ') NOT NULL,
    [NoteID]         INT           CONSTRAINT [DF_WOAcctCategXRef_NoteID] DEFAULT ((0)) NOT NULL,
    [OffsetAcct]     CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_OffsetAcct] DEFAULT (' ') NOT NULL,
    [OffsetSub]      CHAR (24)     CONSTRAINT [DF_WOAcctCategXRef_OffsetSub] DEFAULT (' ') NOT NULL,
    [PrjExpense]     CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_PrjExpense] DEFAULT (' ') NOT NULL,
    [S4Future01]     CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_S4Future01] DEFAULT (' ') NOT NULL,
    [S4Future02]     CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_S4Future02] DEFAULT (' ') NOT NULL,
    [S4Future03]     FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_S4Future03] DEFAULT ((0)) NOT NULL,
    [S4Future04]     FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_S4Future04] DEFAULT ((0)) NOT NULL,
    [S4Future05]     FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_S4Future05] DEFAULT ((0)) NOT NULL,
    [S4Future06]     FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_S4Future06] DEFAULT ((0)) NOT NULL,
    [S4Future07]     SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_S4Future07] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]     SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_S4Future08] DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]     INT           CONSTRAINT [DF_WOAcctCategXRef_S4Future09] DEFAULT ((0)) NOT NULL,
    [S4Future10]     INT           CONSTRAINT [DF_WOAcctCategXRef_S4Future10] DEFAULT ((0)) NOT NULL,
    [S4Future11]     CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_S4Future11] DEFAULT (' ') NOT NULL,
    [S4Future12]     CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_S4Future12] DEFAULT (' ') NOT NULL,
    [ScrapVarAcct]   CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_ScrapVarAcct] DEFAULT (' ') NOT NULL,
    [ScrapVarSub]    CHAR (24)     CONSTRAINT [DF_WOAcctCategXRef_ScrapVarSub] DEFAULT (' ') NOT NULL,
    [User1]          CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_User1] DEFAULT (' ') NOT NULL,
    [User10]         CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_User10] DEFAULT (' ') NOT NULL,
    [User2]          CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_User2] DEFAULT (' ') NOT NULL,
    [User3]          FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_User3] DEFAULT ((0)) NOT NULL,
    [User4]          FLOAT (53)    CONSTRAINT [DF_WOAcctCategXRef_User4] DEFAULT ((0)) NOT NULL,
    [User5]          CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_User5] DEFAULT (' ') NOT NULL,
    [User6]          CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_User6] DEFAULT (' ') NOT NULL,
    [User7]          SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_User7] DEFAULT ('01/01/1900') NOT NULL,
    [User8]          SMALLDATETIME CONSTRAINT [DF_WOAcctCategXRef_User8] DEFAULT ('01/01/1900') NOT NULL,
    [User9]          CHAR (30)     CONSTRAINT [DF_WOAcctCategXRef_User9] DEFAULT (' ') NOT NULL,
    [VarAcct]        CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_VarAcct] DEFAULT (' ') NOT NULL,
    [VarSub]         CHAR (24)     CONSTRAINT [DF_WOAcctCategXRef_VarSub] DEFAULT (' ') NOT NULL,
    [WIPAcct_Mfg]    CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_WIPAcct_Mfg] DEFAULT (' ') NOT NULL,
    [WIPAcct_NonMfg] CHAR (10)     CONSTRAINT [DF_WOAcctCategXRef_WIPAcct_NonMfg] DEFAULT (' ') NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL,
    CONSTRAINT [WOAcctCategXRef0] PRIMARY KEY CLUSTERED ([Acct] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [WOAcctCategXRef1]
    ON [dbo].[WOAcctCategXRef]([Acct_Comp] ASC) WITH (FILLFACTOR = 90);

