
CREATE  PROC [dbo].[pClearSowTablesSpecificFarm_remove]
	@FarmID varchar(8)
	As
	SET NOCOUNT ON

	BEGIN TRANSACTION
	DELETE FROM dbo.Sow WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowParity WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowGroupEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowLocationEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowMatingEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFalloutEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFarrowEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowPigletDeathEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowNonServiceEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowNurseEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFosterEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowPregExamEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowWeanEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowRemoveEvent WHERE FarmID = @FarmID
	COMMIT TRANSACTION

	SET NOCOUNT OFF


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[pClearSowTablesSpecificFarm_remove] TO [se\analysts]
    AS [dbo];


GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[pClearSowTablesSpecificFarm_remove] TO [se\analysts]
    AS [dbo];

