CREATE TABLE [careglobal].[SAVED_REPORT_PARAMETERS] (
    [saved_id]    INT           NULL,
    [param_name]  VARCHAR (80)  NOT NULL,
    [param_value] VARCHAR (600) NULL,
    CONSTRAINT [FK_SAVED_REPORT_PARAMETERS_SAVED_REPORTS_0] FOREIGN KEY ([saved_id]) REFERENCES [careglobal].[SAVED_REPORTS] ([saved_id]) ON DELETE CASCADE
);


GO
CREATE CLUSTERED INDEX [IDX_SAVED_REPORT_PARAMETERS_0]
    ON [careglobal].[SAVED_REPORT_PARAMETERS]([saved_id] ASC) WITH (FILLFACTOR = 80);

