CREATE TABLE [careglobal].[REPORT_GROUP_MAP] (
    [group_id]  INT NOT NULL,
    [report_id] INT NOT NULL,
    CONSTRAINT [PK_REPORT_GROUP_MAP] PRIMARY KEY CLUSTERED ([group_id] ASC, [report_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_REPORT_GROUP_MAP_REPORT_GROUPS_0] FOREIGN KEY ([group_id]) REFERENCES [careglobal].[REPORT_GROUPS] ([group_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_REPORT_GROUP_MAP_REPORTS_1] FOREIGN KEY ([report_id]) REFERENCES [careglobal].[REPORTS] ([report_id]) ON DELETE CASCADE
);

