CREATE TABLE [careglobal].[FARM_GROUP_MEMBERS] (
    [group_id] INT NOT NULL,
    [farm_id]  INT NOT NULL,
    CONSTRAINT [PK_FARM_GROUP_MEMBERS] PRIMARY KEY CLUSTERED ([group_id] ASC, [farm_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_FARM_GROUP_MEMBERS_FARM_GROUPS_0] FOREIGN KEY ([group_id]) REFERENCES [careglobal].[FARM_GROUPS] ([site_id]),
    CONSTRAINT [FK_FARM_GROUP_MEMBERS_FARMS_1] FOREIGN KEY ([farm_id]) REFERENCES [careglobal].[FARMS] ([site_id]) ON DELETE CASCADE
);

