
CREATE VIEW 
    [stage].[vw_EventNumbers]
AS
SELECT
	EVENTTYPE	=	EVENTTYPE
  , EVENTID		=	ID
  , EVENTNBR	=	ROW_NUMBER() OVER ( PARTITION BY PARITYEVENTID ORDER BY SourceID ) + 1 
FROM( 
	SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_nurse
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_fallout
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_observedHeat
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_pregnancyExam
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_removal
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_wean
    UNION ALL
    SELECT 
		N'Animal', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_sales
    UNION ALL
    SELECT 
		N'Mating', ID, PARITYNUMBER, PIGCHAMP_ID FROM stage.vw_CFT_ANIMALEVENT_mating ) 
	AS Orders( EVENTTYPE, ID, PARITYEVENTID, SourceID ) ; 


