CREATE VIEW 
    [stage].[vw_CFT_ANIMALEVENT_all]
AS

SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_arrival 

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_fallout

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_nurse 

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_observedHeat

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_pregnancyExam 

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_removal 

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_sales

UNION 
SELECT 
    ID, DELETED_BY, ANIMALID, PARITYNUMBER, EVENTTYPEID, EVENTDATE, QTY, EVENTTHDATE, SOURCEFARMID, REMOVALREASONID, SYNCSTATUS, MFSYNC, ANIMALSTATUS, PIGCHAMP_ID
FROM
	stage.vw_CFT_ANIMALEVENT_wean
;
