
CREATE VIEW [QQ_itemhist]
AS
SELECT     IH.InvtID AS [Inventory ID], I.Descr AS [Inventory Description], IH.SiteID AS [Site ID], S.Name AS [Site Name], 
                      IH.FiscYr AS [Fiscal Year], IH.PerNbr AS [Current Period Number], IH.BegBal AS [Beginning Balance], 
                      I2.BegQty AS [Beginning Quantity], I.StkUnit AS [Stock UOM], I.StkItem AS [Stock/Nonstock], 
                      IH.YTDCOGS AS [Year To Date COGS], 
                      IH.YTDCostAdjd AS [Year To Date Cost Adjusted], I2.YTDQtyAdjd AS [Year To Date Quantity Adjusted],
                      IH.YTDCostIssd AS [Year To Date Cost Issued], I2.YTDQtyIssd AS [Year To Date Quantity Issued],
                      IH.YTDCostRcvd AS [Year To Date Cost Received], I2.YTDQtyRcvd AS [Year To Date Quantity Received],
                      IH.YTDCostTrsfrIn AS [Year To Date Cost Transferred In], I2.YTDQtyTrsfrIn AS [Year To Date Quantity Transferred In],
                      IH.YTDCostTrsfrOut AS [Year To Date Cost Transferred Out], I2.YTDQtyTrsfrOut AS [Year To Date Quantity Transferred Out],
                      IH.YTDDShpSls AS [Year To Date Drop Ship Sales], I2.YTDQtyDShpSls AS [Year To Date Quantity Drop Ship Sales],
                      IH.YTDSls AS [Year To Date Sales], I2.YTDQtySls AS [Year To Date Quantity Sold],
                      convert(date,IH.Crtd_DateTime) AS [Create Date], IH.Crtd_Prog AS [Create Program], IH.Crtd_User AS [Create User], 
                      convert(date,IH.LUpd_DateTime) AS [Last Update Date], IH.LUpd_Prog AS [Last Update Program], IH.LUpd_User AS [Last Update User], 
                      IH.NoteID AS [ItemHist NoteID], IH.PTDCOGS00 AS [Period To Date COGS 01], 
                      IH.PTDCOGS01 AS [Period To Date COGS 02], IH.PTDCOGS02 AS [Period To Date COGS 03], 
                      IH.PTDCOGS03 AS [Period To Date COGS 04], IH.PTDCOGS04 AS [Period To Date COGS 05], 
                      IH.PTDCOGS05 AS [Period To Date COGS 06], IH.PTDCOGS06 AS [Period To Date COGS 07], 
                      IH.PTDCOGS07 AS [Period To Date COGS 08], IH.PTDCOGS08 AS [Period To Date COGS 09], 
                      IH.PTDCOGS09 AS [Period To Date COGS 10], IH.PTDCOGS10 AS [Period To Date COGS 11], 
                      IH.PTDCOGS11 AS [Period To Date COGS 12], IH.PTDCOGS12 AS [Period To Date COGS 13], 
                      IH.PTDCostAdjd00 AS [Period To Date Cost Adjusted 01], IH.PTDCostAdjd01 AS [Period To Date Cost Adjusted 02], 
                      IH.PTDCostAdjd02 AS [Period To Date Cost Adjusted 03], IH.PTDCostAdjd03 AS [Period To Date Cost Adjusted 04], 
                      IH.PTDCostAdjd04 AS [Period To Date Cost Adjusted 05], IH.PTDCostAdjd05 AS [Period To Date Cost Adjusted 06], 
                      IH.PTDCostAdjd06 AS [Period To Date Cost Adjusted 07], IH.PTDCostAdjd07 AS [Period To Date Cost Adjusted 08], 
                      IH.PTDCostAdjd08 AS [Period To Date Cost Adjusted 09], IH.PTDCostAdjd09 AS [Period To Date Cost Adjusted 10], 
                      IH.PTDCostAdjd10 AS [Period To Date Cost Adjusted 11], IH.PTDCostAdjd11 AS [Period To Date Cost Adjusted 12], 
                      IH.PTDCostAdjd12 AS [Period To Date Cost Adjusted 13], IH.PTDCostIssd00 AS [Period To Date Cost Issued 01], 
                      IH.PTDCostIssd01 AS [Period To Date Cost Issued 02], IH.PTDCostIssd02 AS [Period To Date Cost Issued 03], 
                      IH.PTDCostIssd03 AS [Period To Date Cost Issued 04], IH.PTDCostIssd04 AS [Period To Date Cost Issued 05], 
                      IH.PTDCostIssd05 AS [Period To Date Cost Issued 06], IH.PTDCostIssd06 AS [Period To Date Cost Issued 07], 
                      IH.PTDCostIssd07 AS [Period To Date Cost Issued 08], IH.PTDCostIssd08 AS [Period To Date Cost Issued 09], 
                      IH.PTDCostIssd09 AS [Period To Date Cost Issued 10], IH.PTDCostIssd10 AS [Period To Date Cost Issued 11], 
                      IH.PTDCostIssd11 AS [Period To Date Cost Issued 12], IH.PTDCostIssd12 AS [Period To Date Cost Issued 13], 
                      IH.PTDCostRcvd00 AS [Period To Date Cost Received 01], IH.PTDCostRcvd01 AS [Period To Date Cost Received 02], 
                      IH.PTDCostRcvd02 AS [Period To Date Cost Received 03], IH.PTDCostRcvd03 AS [Period To Date Cost Received 04], 
                      IH.PTDCostRcvd04 AS [Period To Date Cost Received 05], IH.PTDCostRcvd05 AS [Period To Date Cost Received 06], 
                      IH.PTDCostRcvd06 AS [Period To Date Cost Received 07], IH.PTDCostRcvd07 AS [Period To Date Cost Received 08], 
                      IH.PTDCostRcvd08 AS [Period To Date Cost Received 09], IH.PTDCostRcvd09 AS [Period To Date Cost Received 10], 
                      IH.PTDCostRcvd10 AS [Period To Date Cost Received 11], IH.PTDCostRcvd11 AS [Period To Date Cost Received 12], 
                      IH.PTDCostRcvd12 AS [Period To Date Cost Received 13], IH.PTDCostTrsfrIn00 AS [Period To Date Cost Transfer In 01], 
                      IH.PTDCostTrsfrIn01 AS [Period To Date Cost Transfer In 02], IH.PTDCostTrsfrIn02 AS [Period To Date Cost Transfer In 03], 
                      IH.PTDCostTrsfrIn03 AS [Period To Date Cost Transfer In 04], IH.PTDCostTrsfrIn04 AS [Period To Date Cost Transfer In 05], 
                      IH.PTDCostTrsfrIn05 AS [Period To Date Cost Transfer In 06], IH.PTDCostTrsfrIn06 AS [Period To Date Cost Transfer In 07], 
                      IH.PTDCostTrsfrIn07 AS [Period To Date Cost Transfer In 08], IH.PTDCostTrsfrIn08 AS [Period To Date Cost Transfer In 09], 
                      IH.PTDCostTrsfrIn09 AS [Period To Date Cost Transfer In 10], IH.PTDCostTrsfrIn10 AS [Period To Date Cost Transfer In 11], 
                      IH.PTDCostTrsfrIn11 AS [Period To Date Cost Transfer In 12], IH.PTDCostTrsfrIn12 AS [Period To Date Cost Transfer In 13], 
                      IH.PTDCostTrsfrOut00 AS [Period To Date Cost Transfer Out 01], IH.PTDCostTrsfrOut01 AS [Period To Date Cost Transfer Out 02], 
                      IH.PTDCostTrsfrOut02 AS [Period To Date Cost Transfer Out 03], IH.PTDCostTrsfrOut03 AS [Period To Date Cost Transfer Out 04], 
                      IH.PTDCostTrsfrOut04 AS [Period To Date Cost Transfer Out 05], IH.PTDCostTrsfrOut05 AS [Period To Date Cost Transfer Out 06], 
                      IH.PTDCostTrsfrOut06 AS [Period To Date Cost Transfer Out 07], IH.PTDCostTrsfrOut07 AS [Period To Date Cost Transfer Out 08], 
                      IH.PTDCostTrsfrOut08 AS [Period To Date Cost Transfer Out 09], IH.PTDCostTrsfrOut09 AS [Period To Date Cost Transfer Out 10], 
                      IH.PTDCostTrsfrOut10 AS [Period To Date Cost Transfer Out 11], IH.PTDCostTrsfrOut11 AS [Period To Date Cost Transfer Out 12], 
                      IH.PTDCostTrsfrOut12 AS [Period To Date Cost Transfer Out 13], IH.PTDDShpSls00 AS [Period To Date Drop Ship Sales 01], 
                      IH.PTDDShpSls01 AS [Period To Date Drop Ship Sales 02], IH.PTDDShpSls02 AS [Period To Date Drop Ship Sales 03], 
                      IH.PTDDShpSls03 AS [Period To Date Drop Ship Sales 04], IH.PTDDShpSls04 AS [Period To Date Drop Ship Sales 05], 
                      IH.PTDDShpSls05 AS [Period To Date Drop Ship Sales 06], IH.PTDDShpSls06 AS [Period To Date Drop Ship Sales 07], 
                      IH.PTDDShpSls07 AS [Period To Date Drop Ship Sales 08], IH.PTDDShpSls08 AS [Period To Date Drop Ship Sales 09], 
                      IH.PTDDShpSls09 AS [Period To Date Drop Ship Sales 10], IH.PTDDShpSls10 AS [Period To Date Drop Ship Sales 11], 
                      IH.PTDDShpSls11 AS [Period To Date Drop Ship Sales 12], IH.PTDDShpSls12 AS [Period To Date Drop Ship Sales 13], 
                      IH.PTDSls00 AS [Period To Date Sales 01], IH.PTDSls01 AS [Period To Date Sales 02], IH.PTDSls02 AS [Period To Date Sales 03], 
                      IH.PTDSls03 AS [Period To Date Sales 04], IH.PTDSls04 AS [Period To Date Sales 05], IH.PTDSls05 AS [Period To Date Sales 06], 
                      IH.PTDSls06 AS [Period To Date Sales 07], IH.PTDSls07 AS [Period To Date Sales 08], IH.PTDSls08 AS [Period To Date Sales 09], 
                      IH.PTDSls09 AS [Period To Date Sales 10], IH.PTDSls10 AS [Period To Date Sales 11], IH.PTDSls11 AS [Period To Date Sales 12], 
                      IH.PTDSls12 AS [Period To Date Sales 13], IH.User1 AS [ItemHist User1], IH.User2 AS [ItemHist User2], 
                      IH.User3 AS [ItemHist User3], IH.User4 AS [ItemHist User4], IH.User5 AS [ItemHist User5], IH.User6 AS [ItemHist User6], 
                      convert(date,IH.User7) AS [ItemHist User7], convert(date,IH.User8) AS [ItemHist User8], I2.PTDQtyAdjd00 AS [Period To Date Quantity Adjusted 01], 
                      I2.PTDQtyAdjd01 AS [Period To Date Quantity Adjusted 02], I2.PTDQtyAdjd02 AS [Period To Date Quantity Adjusted 03], 
                      I2.PTDQtyAdjd03 AS [Period To Date Quantity Adjusted 04], I2.PTDQtyAdjd04 AS [Period To Date Quantity Adjusted 05], 
                      I2.PTDQtyAdjd05 AS [Period To Date Quantity Adjusted 06], I2.PTDQtyAdjd06 AS [Period To Date Quantity Adjusted 07], 
                      I2.PTDQtyAdjd07 AS [Period To Date Quantity Adjusted 08], I2.PTDQtyAdjd08 AS [Period To Date Quantity Adjusted 09], 
                      I2.PTDQtyAdjd09 AS [Period To Date Quantity Adjusted 10], I2.PTDQtyAdjd10 AS [Period To Date Quantity Adjusted 11], 
                      I2.PTDQtyAdjd11 AS [Period To Date Quantity Adjusted 12], I2.PTDQtyAdjd12 AS [Period To Date Quantity Adjusted 13], 
                      I2.PTDQtyDShpSls00 AS [Period To Date Quantity Drop Ship Sales 01], I2.PTDQtyDShpSls01 AS [Period To Date Quantity Drop Ship Sales 02], 
                      I2.PTDQtyDShpSls02 AS [Period To Date Quantity Drop Ship Sales 03], I2.PTDQtyDShpSls03 AS [Period To Date Quantity Drop Ship Sales 04], 
                      I2.PTDQtyDShpSls04 AS [Period To Date Quantity Drop Ship Sales 05], I2.PTDQtyDShpSls05 AS [Period To Date Quantity Drop Ship Sales 06], 
                      I2.PTDQtyDShpSls06 AS [Period To Date Quantity Drop Ship Sales 07], I2.PTDQtyDShpSls07 AS [Period To Date Quantity Drop Ship Sales 08], 
                      I2.PTDQtyDShpSls08 AS [Period To Date Quantity Drop Ship Sales 09], I2.PTDQtyDShpSls09 AS [Period To Date Quantity Drop Ship Sales 10], 
                      I2.PTDQtyDShpSls10 AS [Period To Date Quantity Drop Ship Sales 11], I2.PTDQtyDShpSls11 AS [Period To Date Quantity Drop Ship Sales 12], 
                      I2.PTDQtyDShpSls12 AS [Period To Date Quantity Drop Ship Sales 13], I2.PTDQtyIssd00 AS [Period To Date Quantity Issued 01], 
                      I2.PTDQtyIssd01 AS [Period To Date Quantity Issued 02], I2.PTDQtyIssd02 AS [Period To Date Quantity Issued 03], 
                      I2.PTDQtyIssd03 AS [Period To Date Quantity Issued 04], I2.PTDQtyIssd04 AS [Period To Date Quantity Issued 05], 
                      I2.PTDQtyIssd05 AS [Period To Date Quantity Issued 06], I2.PTDQtyIssd06 AS [Period To Date Quantity Issued 07], 
                      I2.PTDQtyIssd07 AS [Period To Date Quantity Issued 08], I2.PTDQtyIssd08 AS [Period To Date Quantity Issued 09], 
                      I2.PTDQtyIssd09 AS [Period To Date Quantity Issued 10], I2.PTDQtyIssd10 AS [Period To Date Quantity Issued 11], 
                      I2.PTDQtyIssd11 AS [Period To Date Quantity Issued 12], I2.PTDQtyIssd12 AS [Period To Date Quantity Issued 13], 
                      I2.PTDQtyRcvd00 AS [Period To Date Quantity Received 01], I2.PTDQtyRcvd01 AS [Period To Date Quantity Received 02], 
                      I2.PTDQtyRcvd02 AS [Period To Date Quantity Received 03], I2.PTDQtyRcvd03 AS [Period To Date Quantity Received 04], 
                      I2.PTDQtyRcvd04 AS [Period To Date Quantity Received 05], I2.PTDQtyRcvd05 AS [Period To Date Quantity Received 06], 
                      I2.PTDQtyRcvd06 AS [Period To Date Quantity Received 07], I2.PTDQtyRcvd07 AS [Period To Date Quantity Received 08], 
                      I2.PTDQtyRcvd08 AS [Period To Date Quantity Received 09], I2.PTDQtyRcvd09 AS [Period To Date Quantity Received 10], 
                      I2.PTDQtyRcvd10 AS [Period To Date Quantity Received 11], I2.PTDQtyRcvd11 AS [Period To Date Quantity Received 12], 
                      I2.PTDQtyRcvd12 AS [Period To Date Quantity Received 13], I2.PTDQtySls00 AS [Period To Date Quantity Sales 01], 
                      I2.PTDQtySls01 AS [Period To Date Quantity Sales 02], I2.PTDQtySls02 AS [Period To Date Quantity Sales 03], 
                      I2.PTDQtySls03 AS [Period To Date Quantity Sales 04], I2.PTDQtySls04 AS [Period To Date Quantity Sales 05], 
                      I2.PTDQtySls05 AS [Period To Date Quantity Sales 06], I2.PTDQtySls06 AS [Period To Date Quantity Sales 07], 
                      I2.PTDQtySls07 AS [Period To Date Quantity Sales 08], I2.PTDQtySls08 AS [Period To Date Quantity Sales 09], 
                      I2.PTDQtySls09 AS [Period To Date Quantity Sales 10], I2.PTDQtySls10 AS [Period To Date Quantity Sales 11], 
                      I2.PTDQtySls11 AS [Period To Date Quantity Sales 12], I2.PTDQtySls12 AS [Period To Date Quantity Sales 13], 
                      I2.PTDQtyTrsfrIn00 AS [Period To Date Quantity Transfer In 01], I2.PTDQtyTrsfrIn01 AS [Period To Date Quantity Transfer In 02], 
                      I2.PTDQtyTrsfrIn02 AS [Period To Date Quantity Transfer In 03], I2.PTDQtyTrsfrIn03 AS [Period To Date Quantity Transfer In 04], 
                      I2.PTDQtyTrsfrIn04 AS [Period To Date Quantity Transfer In 05], I2.PTDQtyTrsfrIn05 AS [Period To Date Quantity Transfer In 06], 
                      I2.PTDQtyTrsfrIn06 AS [Period To Date Quantity Transfer In 07], I2.PTDQtyTrsfrIn07 AS [Period To Date Quantity Transfer In 08], 
                      I2.PTDQtyTrsfrIn08 AS [Period To Date Quantity Transfer In 09], I2.PTDQtyTrsfrIn09 AS [Period To Date Quantity Transfer In 10], 
                      I2.PTDQtyTrsfrIn10 AS [Period To Date Quantity Transfer In 11], I2.PTDQtyTrsfrIn11 AS [Period To Date Quantity Transfer In 12], 
                      I2.PTDQtyTrsfrIn12 AS [Period To Date Quantity Transfer In 13], I2.PTDQtyTrsfrOut00 AS [Period To Date Quantity Transfer Out 01], 
                      I2.PTDQtyTrsfrOut01 AS [Period To Date Quantity Transfer Out 02], I2.PTDQtyTrsfrOut02 AS [Period To Date Quantity Transfer Out 03], 
                      I2.PTDQtyTrsfrOut03 AS [Period To Date Quantity Transfer Out 04], I2.PTDQtyTrsfrOut04 AS [Period To Date Quantity Transfer Out 05], 
                      I2.PTDQtyTrsfrOut05 AS [Period To Date Quantity Transfer Out 06], I2.PTDQtyTrsfrOut06 AS [Period To Date Quantity Transfer Out 07], 
                      I2.PTDQtyTrsfrOut07 AS [Period To Date Quantity Transfer Out 08], I2.PTDQtyTrsfrOut08 AS [Period To Date Quantity Transfer Out 09], 
                      I2.PTDQtyTrsfrOut09 AS [Period To Date Quantity Transfer Out 10], I2.PTDQtyTrsfrOut10 AS [Period To Date Quantity Transfer Out 11], 
                      I2.PTDQtyTrsfrOut11 AS [Period To Date Quantity Transfer Out 12], I2.PTDQtyTrsfrOut12 AS [Period To Date Quantity Transfer Out 13], 
                      I2.User1 AS [Item2Hist User1], I2.User2 AS [Item2Hist User2], I2.User3 AS [Item2Hist User3], 
                      I2.User4 AS [Item2Hist User4], I2.User5 AS [Item2Hist User5], I2.User6 AS [Item2Hist User6], 
                      convert(date,I2.User7) AS [Item2Hist User7], convert(date,I2.User8) AS [Item2Hist User8]
FROM         ItemHist IH with (nolock) 
				INNER JOIN Inventory I with (nolock) ON IH.InvtID = I.InvtID 
				INNER JOIN Item2Hist I2 with (nolock) ON IH.InvtID = I2.InvtID AND IH.FiscYr = I2.FiscYr AND IH.SiteID = I2.SiteID 
				INNER JOIN Site S with (nolock) ON IH.SiteID = S.SiteId
     
