
/****** Object:  View [dbo].[vw_GLTran]    Script Date: 09/14/2012 08:37:49 ******/
Create View [dbo].vw_GLTran
As
	Select	
		gltran.Acct+Sub as acct_code,
		BalanceType,
                BatNbr,
		Cpnyid,
		CrAmt * Multiplier CrAmt,
		CuryCrAmt * Multiplier CuryCrAmt,
		CuryDrAmt * Multiplier CuryDrAmt,
		gltran.CuryId as curr_code,
		CuryEffDate,
                CuryMultDiv,
                CuryRate,
                CuryRateType,
		DrAmt * Multiplier DrAmt,
                EmployeeID,
		CAST( FiscYr as smallint) as fiscal_year,
		JrnlType,
                Labor_Class_Cd,
		LedgerID,
                LineRef,
                Module,
                OrigAcct,
                OrigBatNbr,
                OrigCpnyID,
                OrigSub,
                PC_Flag,
                PC_ID,
                PC_Status,
                PerEnt,
		CAST( substring(PerPost, 5, 2) as smallint) as per_num,
		PerPost,
                ProjectID,
		Posted,
                RefNbr,
		Rlsed,
		Qty,
                TaskID,
		TranDate as date_applied,
		TranDesc as trx_desc,
		TranType,
		Units,
        	0 as adj_trx,
                gltran.User1,
                gltran.User2,
                gltran.User3,
                gltran.User4,
                gltran.User5,
                gltran.User6,
                gltran.User7,
                gltran.User8
	From GLTran

	LEFT OUTER JOIN (SELECT CASE WHEN CHARINDEX(SUBSTRING(AcctType, 2, 1),'AE') > 0 THEN 1 ELSE -1 END AS Multiplier, * FROM Account) Account on Account.Acct = GLTran.Acct
