 

CREATE VIEW PJvTran
AS 
SELECT PROJECT, PJT_ENTITY, ACCT, FISCALNO, 
 	'AMOUNT' = ROUND(SUM(ROUND(PJTRAN.AMOUNT,2)),2), 
 	'UNITS' = ROUND(SUM(ROUND(PJTRAN.UNITS,2)),2)
FROM PJTRAN 
WHERE TR_STATUS <> 'S' 
GROUP BY 
PROJECT, PJT_ENTITY, ACCT, FISCALNO

 
