
CREATE VIEW IC_PJvYTDSummary
AS
  SELECT PJvYTDSummary.Acct,
         PJvYTDSummary.Project,
         PJvYTDSummary.Period,
         PJvYTDSummary.Year,
         Sum(PJvYTDSummary.amount_01) 'ActualAmt01',
         Sum(PJvYTDSummary.amount_02) 'ActualAmt02',
         Sum(PJvYTDSummary.amount_03) 'ActualAmt03',
         Sum(PJvYTDSummary.amount_04) 'ActualAmt04',
         Sum(PJvYTDSummary.amount_05) 'ActualAmt05',
         Sum(PJvYTDSummary.amount_06) 'ActualAmt06',
         Sum(PJvYTDSummary.amount_07) 'ActualAmt07',
         Sum(PJvYTDSummary.amount_08) 'ActualAmt08',
         Sum(PJvYTDSummary.amount_09) 'ActualAmt09',
         Sum(PJvYTDSummary.amount_10) 'ActualAmt10',
         Sum(PJvYTDSummary.amount_11) 'ActualAmt11',
         Sum(PJvYTDSummary.amount_12) 'ActualAmt12',
         Sum(PJvYTDSummary.amount_13) 'ActualAmt13',
         Sum(PJvYTDSummary.amount_14) 'ActualAmt14',
         Sum(PJvYTDSummary.amount_15) 'ActualAmt15',
		 Sum(PJvYTDSummary.ProjCury_amount_01) 'ProjCury_ActualAmt01',
         Sum(PJvYTDSummary.ProjCury_amount_02) 'ProjCury_ActualAmt02',
         Sum(PJvYTDSummary.ProjCury_amount_03) 'ProjCury_ActualAmt03',
         Sum(PJvYTDSummary.ProjCury_amount_04) 'ProjCury_ActualAmt04',
         Sum(PJvYTDSummary.ProjCury_amount_05) 'ProjCury_ActualAmt05',
         Sum(PJvYTDSummary.ProjCury_amount_06) 'ProjCury_ActualAmt06',
         Sum(PJvYTDSummary.ProjCury_amount_07) 'ProjCury_ActualAmt07',
         Sum(PJvYTDSummary.ProjCury_amount_08) 'ProjCury_ActualAmt08',
         Sum(PJvYTDSummary.ProjCury_amount_09) 'ProjCury_ActualAmt09',
         Sum(PJvYTDSummary.ProjCury_amount_10) 'ProjCury_ActualAmt10',
         Sum(PJvYTDSummary.ProjCury_amount_11) 'ProjCury_ActualAmt11',
         Sum(PJvYTDSummary.ProjCury_amount_12) 'ProjCury_ActualAmt12',
         Sum(PJvYTDSummary.ProjCury_amount_13) 'ProjCury_ActualAmt13',
         Sum(PJvYTDSummary.ProjCury_amount_14) 'ProjCury_ActualAmt14',
         Sum(PJvYTDSummary.ProjCury_amount_15) 'ProjCury_ActualAmt15',
         Avg(PJvYTDSummary.rate)      'ActualRate'
  FROM   PJvYTDSummary
  GROUP  BY PJvYTDSummary.Project,
            PJvYTDSummary.Acct,
            PJvYTDSummary.Period,
            PJvYTDSummary.Year
