
CREATE VIEW PJvPTDSummary
AS
  SELECT PJPTDAIC.Acct,
         PJPTDAIC.project,
         PJPTDAIC.pjt_entity,
         PJPTDAIC.fsyear_num,
         PJPTDAIC.rate_01,
         PJPTDAIC.rate_02,
         PJPTDAIC.rate_03,
         PJPTDAIC.rate_04,
         PJPTDAIC.rate_05,
         PJPTDAIC.rate_06,
         PJPTDAIC.rate_07,
         PJPTDAIC.rate_08,
         PJPTDAIC.rate_09,
         PJPTDAIC.rate_10,
         PJPTDAIC.rate_11,
         PJPTDAIC.rate_12,
         PJPTDAIC.rate_13,
         PJPTDAIC.rate_14,
         PJPTDAIC.rate_15,
         PJPTDAIC.Amount_bf             'Beg_Amt',
         PJPTDAIC.amount_01,
         PJPTDAIC.amount_02,
         PJPTDAIC.amount_03,
         PJPTDAIC.amount_04,
         PJPTDAIC.amount_05,
         PJPTDAIC.amount_06,
         PJPTDAIC.amount_07,
         PJPTDAIC.amount_08,
         PJPTDAIC.amount_09,
         PJPTDAIC.amount_10,
         PJPTDAIC.amount_11,
         PJPTDAIC.amount_12,
         PJPTDAIC.amount_13,
         PJPTDAIC.amount_14,
         PJPTDAIC.amount_15,
         Isnull(PJPTDSUM.eac_amount, 0) 'EAC_Amt',
		 PJPTDAIC.ProjCury_Amount_bf             'ProjCury_Beg_Amt',
         PJPTDAIC.ProjCury_Amount_01,
         PJPTDAIC.ProjCury_Amount_02,
         PJPTDAIC.ProjCury_Amount_03,
         PJPTDAIC.ProjCury_Amount_04,
         PJPTDAIC.ProjCury_Amount_05,
         PJPTDAIC.ProjCury_Amount_06,
         PJPTDAIC.ProjCury_Amount_07,
         PJPTDAIC.ProjCury_Amount_08,
         PJPTDAIC.ProjCury_Amount_09,
         PJPTDAIC.ProjCury_Amount_10,
         PJPTDAIC.ProjCury_Amount_11,
         PJPTDAIC.ProjCury_Amount_12,
         PJPTDAIC.ProjCury_Amount_13,
         PJPTDAIC.ProjCury_Amount_14,
         PJPTDAIC.ProjCury_Amount_15,
         Isnull(PJPTDSUM.ProjCury_eac_amount, 0) 'ProjCury_EAC_Amt'
  FROM   PJPTDAIC
         LEFT OUTER JOIN PJPTDSUM
           ON PJPTDAIC.project = PJPTDSUM.project
              AND PJPTDAIC.pjt_entity = PJPTDSUM.pjt_entity
              AND PJPTDAIC.acct = PJPTDSUM.acct

