
CREATE VIEW IC_PJvPTDSummary
AS
  SELECT PJvPTDSummary.Acct,
         PJvPTDSummary.Project,
         PJvPTDSummary.fsyear_num     'Year',
         Sum(PJvPTDSummary.amount_01) 'ActualAmt01',
         Sum(PJvPTDSummary.amount_02) 'ActualAmt02',
         Sum(PJvPTDSummary.amount_03) 'ActualAmt03',
         Sum(PJvPTDSummary.amount_04) 'ActualAmt04',
         Sum(PJvPTDSummary.amount_05) 'ActualAmt05',
         Sum(PJvPTDSummary.amount_06) 'ActualAmt06',
         Sum(PJvPTDSummary.amount_07) 'ActualAmt07',
         Sum(PJvPTDSummary.amount_08) 'ActualAmt08',
         Sum(PJvPTDSummary.amount_09) 'ActualAmt09',
         Sum(PJvPTDSummary.amount_10) 'ActualAmt10',
         Sum(PJvPTDSummary.amount_11) 'ActualAmt11',
         Sum(PJvPTDSummary.amount_12) 'ActualAmt12',
         Sum(PJvPTDSummary.amount_13) 'ActualAmt13',
         Sum(PJvPTDSummary.amount_14) 'ActualAmt14',
         Sum(PJvPTDSummary.amount_15) 'ActualAmt15',
         Avg(PJvPTDSummary.rate_01)   'ActualRate01',
         Avg(PJvPTDSummary.rate_02)   'ActualRate02',
         Avg(PJvPTDSummary.rate_03)   'ActualRate03',
         Avg(PJvPTDSummary.rate_04)   'ActualRate04',
         Avg(PJvPTDSummary.rate_05)   'ActualRate05',
         Avg(PJvPTDSummary.rate_06)   'ActualRate06',
         Avg(PJvPTDSummary.rate_07)   'ActualRate07',
         Avg(PJvPTDSummary.rate_08)   'ActualRate08',
         Avg(PJvPTDSummary.rate_09)   'ActualRate09',
         Avg(PJvPTDSummary.rate_10)   'ActualRate10',
         Avg(PJvPTDSummary.rate_11)   'ActualRate11',
         Avg(PJvPTDSummary.rate_12)   'ActualRate12',
         Avg(PJvPTDSummary.rate_13)   'ActualRate13',
         Avg(PJvPTDSummary.rate_14)   'ActualRate14',
         Avg(PJvPTDSummary.rate_15)   'ActualRate15',
		 Sum(PJvPTDSummary.ProjCury_Amount_01) 'ProjCury_ActualAmt01',
         Sum(PJvPTDSummary.ProjCury_Amount_02) 'ProjCury_ActualAmt02',
         Sum(PJvPTDSummary.ProjCury_Amount_03) 'ProjCury_ActualAmt03',
         Sum(PJvPTDSummary.ProjCury_Amount_04) 'ProjCury_ActualAmt04',
         Sum(PJvPTDSummary.ProjCury_Amount_05) 'ProjCury_ActualAmt05',
         Sum(PJvPTDSummary.ProjCury_Amount_06) 'ProjCury_ActualAmt06',
         Sum(PJvPTDSummary.ProjCury_Amount_07) 'ProjCury_ActualAmt07',
         Sum(PJvPTDSummary.ProjCury_Amount_08) 'ProjCury_ActualAmt08',
         Sum(PJvPTDSummary.ProjCury_Amount_09) 'ProjCury_ActualAmt09',
         Sum(PJvPTDSummary.ProjCury_Amount_10) 'ProjCury_ActualAmt10',
         Sum(PJvPTDSummary.ProjCury_Amount_11) 'ProjCury_ActualAmt11',
         Sum(PJvPTDSummary.ProjCury_Amount_12) 'ProjCury_ActualAmt12',
         Sum(PJvPTDSummary.ProjCury_Amount_13) 'ProjCury_ActualAmt13',
         Sum(PJvPTDSummary.ProjCury_Amount_14) 'ProjCury_ActualAmt14',
         Sum(PJvPTDSummary.ProjCury_Amount_15) 'ProjCury_ActualAmt15'
  FROM   PJvPTDSummary
  GROUP  BY PJvPTDSummary.Project,
            PJvPTDSummary.Acct,
            PJvPTDSummary.fsyear_num
