create view bmd_test_view
([Crtd_DateTime]
      ,[Crtd_Prog]
      ,[Crtd_User]
      ,[Description]
      ,[LoadTimeMinutes]
      ,[Lupd_DateTime]
      ,[Lupd_Prog]
      ,[Lupd_User]
      ,[MarketSaleTypeID]
      ,[NoteID]
      ,[MarketTotalType]
      ,[TrailerWashFlg]
      ,[tstamp])
      AS
SELECT [Crtd_DateTime]
      ,[Crtd_Prog]
      ,[Crtd_User]
      ,[Description]
      ,[LoadTimeMinutes]
      ,[Lupd_DateTime]
      ,[Lupd_Prog]
      ,[Lupd_User]
      ,[MarketSaleTypeID]
      ,[NoteID]
      ,[MarketTotalType]
      ,[TrailerWashFlg]
      ,[tstamp]
  FROM cftMarketSaleType
  Union ALL
  SELECT [Crtd_DateTime]
      ,[Crtd_Prog]
      ,[Crtd_User]
      ,[Description]
      ,[LoadTimeMinutes]
      ,[Lupd_DateTime]
      ,[Lupd_Prog]
      ,[Lupd_User]
      ,[MarketSaleTypeID]
      ,[NoteID]
      ,[MarketTotalType]
      ,[TrailerWashFlg]
      ,[tstamp]
  FROM cftMarketSaleType
	Where 0=1
