CREATE TABLE [dbo].[CFT_BREEDER] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      CONSTRAINT [DF__CFT_BREED__CREAT__351DDF8C] DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      CONSTRAINT [DF__CFT_BREED__LAST___361203C5] DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        CONSTRAINT [DF__CFT_BREED__CREAT__370627FE] DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        CONSTRAINT [DF__CFT_BREED__LAST___37FA4C37] DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        CONSTRAINT [DF__CFT_BREED__DELET__38EE7070] DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (50) NULL,
    [FARMID]          NVARCHAR (36) NULL,
    [STATUS]          INT           NULL,
    [BREEDERID]       NVARCHAR (5)  NULL,
    CONSTRAINT [CFT_BREEDER_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [MFI_13]
    ON [dbo].[CFT_BREEDER]([NAME] ASC, [FARMID] ASC, [STATUS] ASC) WITH (FILLFACTOR = 90);

