CREATE TABLE [dbo].[MF_EVENT_QUEUE] (
    [ID]              BIGINT        IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (80) NULL,
    [SERVERID]        BIGINT        NULL,
    [PROJECTID]       BIGINT        NULL,
    [SESSIONID]       NVARCHAR (36) COLLATE Latin1_General_CS_AS NOT NULL,
    CONSTRAINT [MF_EVENT_QUEUE_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

