CREATE TABLE [dbo].[MF_SYNC_INFO] (
    [ID]              BIGINT        IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (80) NULL,
    [INSTANCEID]      BIGINT        NULL,
    [INSTANCEIDGUID]  NVARCHAR (36) COLLATE Latin1_General_CS_AS NULL,
    [TABLEID]         BIGINT        NOT NULL,
    [SYNCDATE]        DATETIME      NULL,
    [DBID]            NVARCHAR (40) NOT NULL,
    CONSTRAINT [MF_SYNC_INFO_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [SYNC_INFO_UNIQUE_CONSTRAINT] UNIQUE NONCLUSTERED ([INSTANCEIDGUID] ASC, [INSTANCEID] ASC, [TABLEID] ASC, [DBID] ASC) WITH (FILLFACTOR = 90)
);

