CREATE TABLE [dbo].[MF_META_ATTRIBUTE] (
    [ID]              BIGINT         IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT         DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT         DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT         DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (80)  NULL,
    [DATATYPE]        INT            NULL,
    [DATASIZE]        INT            NULL,
    [OBJECTID]        BIGINT         NULL,
    [LIST]            IMAGE          NULL,
    [LABEL]           NVARCHAR (80)  NULL,
    [DESCRIPTION]     NVARCHAR (255) NULL,
    [DEFAULTVALUE]    NVARCHAR (255) NULL,
    [INPUTMECHANISM]  INT            NULL,
    [SYSTEMFIELD]     INT            NULL,
    [SYNCHRONIZE]     INT            NULL,
    [ORDINAL]         INT            NULL,
    [VISIBLE]         INT            NULL,
    [READONLY]        INT            NULL,
    CONSTRAINT [MF_META_ATTRIBUTE_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [MA_MO_FK] FOREIGN KEY ([OBJECTID]) REFERENCES [dbo].[MF_META_OBJECT] ([ID])
);

