CREATE TABLE [dbo].[MF_ENTERPRISE_RELATIONSHIPS] (
    [ID]              BIGINT        IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [TYPE]            NVARCHAR (36) NULL,
    [PARENTTABLE]     BIGINT        NULL,
    [PARENTID]        BIGINT        NULL,
    [CHILDTABLE]      BIGINT        NULL,
    [CHILDID]         BIGINT        NULL,
    [PARENTIDGUID]    NVARCHAR (36) COLLATE Latin1_General_CS_AS NULL,
    [CHILDIDGUID]     NVARCHAR (36) COLLATE Latin1_General_CS_AS NULL,
    CONSTRAINT [MF_ENTERPRISE_RELATIONSHIPS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

