CREATE TABLE [dbo].[CFT_ANIMALEVENTS] (
    [ID]                   NVARCHAR (36) NOT NULL,
    [CREATE_DATE]          DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]          DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]           BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]           BIGINT        DEFAULT ((-1)) NOT NULL,
    [ANIMALID]             NVARCHAR (36) NULL,
    [PARITYNBR]            INT           NULL,
    [EVENTDATE]            DATETIME      NULL,
    [EVENTTHDATE]          NVARCHAR (10) NULL,
    [EVENTTYPEID]          NVARCHAR (36) NULL,
    [GROUPNAME]            NVARCHAR (4)  NULL,
    [QTY]                  INT           NULL,
    [BORNALIVE]            INT           NULL,
    [STILLBORN]            INT           NULL,
    [MUMMY]                INT           NULL,
    [SETNBR]               INT           NULL,
    [LOCATIONID]           NVARCHAR (36) NULL,
    [GESTATIONLENGTH]      INT           NULL,
    [MATINGHOUR]           INT           NULL,
    [BREEDERID]            NVARCHAR (36) NULL,
    [SEMENID]              NVARCHAR (36) NULL,
    [HEATCYCLE]            INT           NULL,
    [MATINGNBR]            INT           NULL,
    [BREEDINGNBR]          INT           NULL,
    [PARITYSERVICENBR]     INT           NULL,
    [SOURCEFARMID]         NVARCHAR (36) NULL,
    [DESTINATIONFARMID]    NVARCHAR (36) NULL,
    [REMOVALREASONID]      INT           NULL,
    [EVENTNBR]             INT           NULL,
    [COMMENT]              TEXT          NULL,
    [ANIMALSTATUS]         INT           NULL,
    [PREVSTATUS]           INT           NULL,
    [SYNCSTATUS]           NVARCHAR (20) NULL,
    [DEVICEID]             NVARCHAR (36) NULL,
    [DEVICEVERSION]        NVARCHAR (10) NULL,
    [ENTEREDDATE]          DATETIME      NULL,
    [LASTUPDATEDEVICEID]   NVARCHAR (36) NULL,
    [LASTUPDATEAPPVERSION] NVARCHAR (10) NULL,
    [LASTUPDATEDATE]       DATETIME      NULL,
    [PIGCHAMP_ID]          BIGINT        NULL,
    [DEVICEFARMID]         NVARCHAR (36) NULL,
    CONSTRAINT [CFT_ANIMALEVENTS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [MFI_2]
    ON [dbo].[CFT_ANIMALEVENTS]([DELETED_BY] ASC, [ANIMALID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_3]
    ON [dbo].[CFT_ANIMALEVENTS]([DELETED_BY] ASC, [SYNCSTATUS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_4]
    ON [dbo].[CFT_ANIMALEVENTS]([ANIMALID] ASC, [EVENTNBR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_5]
    ON [dbo].[CFT_ANIMALEVENTS]([DELETED_BY] ASC, [ANIMALID] ASC, [ANIMALSTATUS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_6]
    ON [dbo].[CFT_ANIMALEVENTS]([DELETED_BY] ASC, [EVENTTHDATE] ASC, [MATINGNBR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_8]
    ON [dbo].[CFT_ANIMALEVENTS]([DELETED_BY] ASC, [EVENTTHDATE] ASC, [EVENTTYPEID] ASC, [SYNCSTATUS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_19]
    ON [dbo].[CFT_ANIMALEVENTS]([ANIMALID] ASC, [EVENTDATE] ASC, [EVENTTYPEID] ASC, [MATINGNBR] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_20]
    ON [dbo].[CFT_ANIMALEVENTS]([PARITYNBR] ASC, [ANIMALID] ASC, [EVENTTYPEID] ASC) WITH (FILLFACTOR = 90);

