CREATE TABLE [dbo].[CFT_GENETICS] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (30) NULL,
    [SEX]             NVARCHAR (10) NULL,
    [PIGCHAMP_ID]     BIGINT        NULL,
    [STATUS]          NVARCHAR (1)  NULL,
    [FARMID]          NVARCHAR (36) NULL,
    CONSTRAINT [CFT_GENETICS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

