CREATE TABLE [dbo].[MF_SCHEDULED_PROJECT_ASSIGN] (
    [ID]              BIGINT   IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT   DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT   DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT   DEFAULT ((-1)) NOT NULL,
    [PROJECTID]       BIGINT   NULL,
    [ASSIGNEDUSER]    BIGINT   NULL,
    [DYNDATAID]       BIGINT   DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [MF_SCHED_PROJECT_ASSIGN_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [SPA_MFU_FK] FOREIGN KEY ([ASSIGNEDUSER]) REFERENCES [dbo].[MF_USER] ([ID]),
    CONSTRAINT [SPA_SP_FK] FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[MF_SCHEDULED_PROJECT] ([ID])
);

