CREATE TABLE [dbo].[MF_SCHEDULED_TASK] (
    [ID]                 BIGINT         IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]        DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]        DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]         BIGINT         DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY]    BIGINT         DEFAULT ((0)) NOT NULL,
    [DELETED_BY]         BIGINT         DEFAULT ((-1)) NOT NULL,
    [NAME]               NVARCHAR (80)  NULL,
    [PROJECTID]          BIGINT         NULL,
    [DESCRIPTION]        NVARCHAR (255) NULL,
    [SCREENLAYOUT]       IMAGE          NULL,
    [AUTORUN]            INT            NULL,
    [ATTRIBUTES]         IMAGE          NULL,
    [LIBRARYTASKID]      BIGINT         NULL,
    [LIBRARYTASKVERSION] BIGINT         NULL,
    CONSTRAINT [MF_SCHED_TASK_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [ST_SP_FK] FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[MF_SCHEDULED_PROJECT] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [ST_SP_FK_I]
    ON [dbo].[MF_SCHEDULED_TASK]([PROJECTID] ASC) WITH (FILLFACTOR = 90);

