CREATE TABLE [dbo].[MF_DEVICE_FARM] (
    [ID]                      BIGINT         IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]             DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]             DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]              BIGINT         DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY]         BIGINT         DEFAULT ((0)) NOT NULL,
    [DELETED_BY]              BIGINT         DEFAULT ((-1)) NOT NULL,
    [NAME]                    NVARCHAR (150) NULL,
    [DEVICEID]                NVARCHAR (255) NULL,
    [NOTES]                   NVARCHAR (150) NULL,
    [BATTERYPOWER]            INT            NULL,
    [FREEMEMORY]              INT            NULL,
    [TOTALMEMORY]             INT            NULL,
    [LASTSTARTDATE]           DATETIME       NULL,
    [TOTALDISKSPACE]          BIGINT         NULL,
    [FREEDISKSPACE]           BIGINT         NULL,
    [CLIENTDBSIZE]            BIGINT         NULL,
    [PLATFORM]                INT            NULL,
    [SUBPLATFORM]             INT            NULL,
    [OSVERSION]               NVARCHAR (80)  NULL,
    [MFVERSION]               NVARCHAR (80)  NULL,
    [OSDISPLAYVERSION]        NVARCHAR (255) NULL,
    [DEVICEOEMINFO]           NVARCHAR (255) NULL,
    [GPS_LATITUDE]            FLOAT (53)     NULL,
    [GPS_LONGITUDE]           FLOAT (53)     NULL,
    [GPS_SPEED]               FLOAT (53)     NULL,
    [GPS_HEADING]             FLOAT (53)     NULL,
    [GPS_LASTUPDATE]          DATETIME       NULL,
    [GPS_SATELLITECOUNT]      INT            NULL,
    [GPS_ALTITUDE]            FLOAT (53)     NULL,
    [GPS_DILUTIONOFPRECISION] FLOAT (53)     NULL,
    [LASTUSERID]              BIGINT         DEFAULT ((-1)) NOT NULL,
    [SERVERID]                BIGINT         DEFAULT ((-1)) NOT NULL,
    [LASTSTATUS]              INT            NULL,
    CONSTRAINT [MF_DEVICE_FARM_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

