CREATE TABLE [dbo].[MF_SCHEDULED_PROJECT_DYNDATA] (
    [ID]              BIGINT        IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [NAME]            NVARCHAR (80) NULL,
    [PROJECTID]       BIGINT        NULL,
    [OBJECTID]        BIGINT        NULL,
    [DESCRIPTION]     NVARCHAR (80) NULL,
    [DATA]            IMAGE         NULL,
    CONSTRAINT [MF_SCHED_PROJECT_DYNDATA_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [SPDED_SP_FK] FOREIGN KEY ([PROJECTID]) REFERENCES [dbo].[MF_SCHEDULED_PROJECT] ([ID])
);

