CREATE TABLE [dbo].[MF_WEB_SESSION] (
    [ID]              BIGINT   IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT   DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT   DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT   DEFAULT ((-1)) NOT NULL,
    [USERID]          BIGINT   NOT NULL,
    [SESSIONDATA]     IMAGE    NULL,
    CONSTRAINT [MF_WEB_SESSION_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [MF_WEB_SESSION_UNIQUE] UNIQUE NONCLUSTERED ([USERID] ASC) WITH (FILLFACTOR = 90)
);

