CREATE TABLE [dbo].[CFT_DRUGSSYMPTOMS] (
    [ID]              BIGINT   IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT   DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT   DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT   DEFAULT ((-1)) NOT NULL,
    [DRUGID]          INT      NULL,
    [SYMPTOMID]       INT      NULL,
    [ACTIVEDATE]      DATETIME NULL,
    [DEACTIVEDATE]    DATETIME NULL,
    CONSTRAINT [CFT_DRUGSSYMPTOMS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

