CREATE TABLE [dbo].[MF_USER] (
    [ID]                   BIGINT         IDENTITY (0, 1) NOT NULL,
    [CREATE_DATE]          DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]          DATETIME       DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]           BIGINT         DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY]      BIGINT         DEFAULT ((0)) NOT NULL,
    [DELETED_BY]           BIGINT         DEFAULT ((-1)) NOT NULL,
    [NAME]                 NVARCHAR (80)  NULL,
    [LOGINNAME]            NVARCHAR (25)  NULL,
    [PASSWORD]             NVARCHAR (255) NULL,
    [MFROLE]               INT            NOT NULL,
    [EMAILADDRESS]         NVARCHAR (255) NULL,
    [FIRSTNAME]            NVARCHAR (25)  NULL,
    [MIDDLENAME]           NVARCHAR (25)  NULL,
    [LASTNAME]             NVARCHAR (25)  NULL,
    [TITLE]                NVARCHAR (5)   NULL,
    [JOBTITLE]             NVARCHAR (30)  NULL,
    [NOTES]                NVARCHAR (255) NULL,
    [LICENSED]             INT            DEFAULT ((0)) NOT NULL,
    [PHONENUMBER]          NVARCHAR (80)  NULL,
    [PREFERENCES]          IMAGE          NULL,
    [AUTHENTICATIONTYPE]   INT            NULL,
    [AUTHENTICATIONDOMAIN] NVARCHAR (255) NULL,
    [REMOTEDBID]           NVARCHAR (80)  NULL,
    [LASTDEVICEID]         NVARCHAR (80)  NULL,
    [LASTSYNCSTARTED]      DATETIME       NULL,
    [AUTOSYNC]             INT            DEFAULT ((0)) NOT NULL,
    [DEPARTMENT]           NVARCHAR (10)  NULL,
    [FARMID]               NVARCHAR (36)  NULL,
    [SERVERCOUNT]          BIGINT         NULL,
    [SERVERCOUNTDATE]      DATETIME       NULL,
    [CLIENTCOUNT]          BIGINT         NULL,
    [CLIENTCOUNTDATE]      DATETIME       NULL,
    CONSTRAINT [MF_USER_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

