CREATE TABLE [dbo].[CFT_ANIMAL] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [BIRTHDATE]       DATETIME      NULL,
    [GENETICSID]      NVARCHAR (36) NULL,
    [ORIGIN]          NVARCHAR (50) NULL,
    [SEX]             NVARCHAR (10) NULL,
    [ORIGINID]        NVARCHAR (36) NULL,
    [PIGCHAMP_ID]     BIGINT        NULL,
    [PRINTFLAG]       NVARCHAR (1)  NULL,
    [DEVICEFARMID]    NVARCHAR (36) NULL,
    [ACTIVE]          NVARCHAR (1)  NULL,
    CONSTRAINT [CFT_ANIMAL_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [MFI_1]
    ON [dbo].[CFT_ANIMAL]([DELETED_BY] ASC, [SEX] ASC) WITH (FILLFACTOR = 90);

