CREATE TABLE [dbo].[CFT_ANIMALTAG] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [LAST_UPDATE]     DATETIME      DEFAULT (getutcdate()) NOT NULL,
    [CREATED_BY]      BIGINT        DEFAULT ((0)) NOT NULL,
    [LAST_UPDATED_BY] BIGINT        DEFAULT ((0)) NOT NULL,
    [DELETED_BY]      BIGINT        DEFAULT ((-1)) NOT NULL,
    [ANIMALID]        NVARCHAR (36) NULL,
    [TAGNBR]          NVARCHAR (20) NULL,
    [TAGDATE]         DATETIME      NULL,
    [PRIMARYTAG]      INT           NULL,
    [ISCURRENT]       INT           NULL,
    [QRCODE]          IMAGE         NULL,
    [QRCODETYPE]      NVARCHAR (20) NULL,
    [DEVICEFARMID]    NVARCHAR (36) NULL,
    CONSTRAINT [CFT_ANIMALTAG_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [MFI_11]
    ON [dbo].[CFT_ANIMALTAG]([DELETED_BY] ASC, [ANIMALID] ASC, [TAGNBR] ASC, [PRIMARYTAG] ASC, [ISCURRENT] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_12]
    ON [dbo].[CFT_ANIMALTAG]([DELETED_BY] ASC, [PRIMARYTAG] ASC, [ISCURRENT] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [MFI_17]
    ON [dbo].[CFT_ANIMALTAG]([DELETED_BY] ASC, [TAGNBR] ASC) WITH (FILLFACTOR = 90);

