






CREATE VIEW 
    [dbo].[CFV_PC_Farrows]
AS
SELECT   Distinct
			CAST(ATP.[TAGNBR] as varchar(12)) as 'Primary'
			,CAST(ATA.[TAGNBR] as varchar(20)) as 'ALTERNATE'
			,CAST(FRM.NAME as varchar(8))as Farm
			,MFU.NAME as 'Created_By'
			,Isnull(FE.ENTEREDDATE, FE.CREATE_DATE) as CREATE_DATE
			,FE.[EVENTDATE] as FARROWDATE
			,FE.EVENTTHDATE as FARROWTHDATE
			,FE.BORNALIVE
			,FE.STILLBORN
			,FE.MUMMY
			,LOC.ROOM
			,LOC.CRATE
			,FE.GESTATIONLENGTH
			,FE.[ID] as MFID
			,FE.SYNCSTATUS
			
FROM   [dbo].CFT_ANIMAL AS AN WITH (NOLOCK) 
		JOIN [dbo].[CFT_FARMANIMAL] FA (NOLOCK) on AN.ID  = FA.ANIMALID 
		JOIN [dbo].[CFT_FARM] FRM (NOLOCK) on FA.FARMID  = FRM.ID 
		JOIN [dbo].[CFT_ANIMALEVENTS] FE (NOLOCK) ON AN.ID  = FE.ANIMALID 
		JOIN [dbo].[CFT_EVENTTYPE] ET (NOLOCK) ON FE.EVENTTYPEID  = ET.ID
		JOIN [dbo].CFT_LOCATION AS LOC WITH (NOLOCK) ON FE.LOCATIONID  = LOC.ID 
		LEFT JOIN [dbo].[MF_USER] MFU (NOLOCK) ON MFU.ID = FE.DEVICEID
		CROSS APPLY (Select Top 1 [TAGNBR] From [dbo].[CFT_ANIMALTAG] AS ATP WITH (NOLOCK) Where
		AN.ID  = ATP.[ANIMALID] AND ATP.[PRIMARYTAG] = 1 AND ATP.[ISCURRENT] = 1) ATP
		OUTER APPLY (Select Top 1 [TAGNBR] From [dbo].[CFT_ANIMALTAG] AS ATA WITH (NOLOCK) Where
		AN.ID  = ATA.[ANIMALID] AND ATA.[PRIMARYTAG] = 0) ATA
		Where ET.[EVENTTYPE] Like 'Farrowing' --AND FE.SYNCSTATUS = 'NEW'
AND FE.[DELETED_BY] = -1 
AND FA.[DELETED_BY] = -1
