







CREATE VIEW 
    [dbo].[CFV_PC_Removals]
AS
SELECT Distinct
		    CAST(ATP.[TAGNBR] as varchar(12)) as 'Primary'
			,CAST(ATA.[TAGNBR] as varchar(20)) as 'ALTERNATE'
			,CAST(FRM.NAME as varchar(8))as Farm
			,MFU.NAME as 'Created_By'
			,Isnull(AE.ENTEREDDATE, AE.CREATE_DATE) as CREATE_DATE
			,AE.[EVENTDATE]
			,AE.[EVENTTHDATE]			
			,AE.[REMOVALREASONID]
			,Case when AE.REMOVALREASONID IS null or AE.REMOVALREASONID < 0 Then ''  ELSE RS.EVENTNAME END as 'Removal Desc'
			,AN.SEX as Sex
			,CAST( AN.ORIGIN as varchar(24)) as Origin
			,CASE ET.[EVENTNAME]
				WHEN 'EUTH' Then 'DESTROY'
				ELSE CAST(ET.[EVENTNAME] as varchar(8))
			End as 'EventType'
			,AE.[ID] as MFID
			,AE.SYNCSTATUS
FROM [dbo].CFT_ANIMAL AS AN WITH (NOLOCK)
	LEFT JOIN [MobileFrame].[dbo].[CFT_GENETICS] GEN (NOLOCK) on AN.GENETICSID = GEN.ID
	JOIN [dbo].[CFT_FARMANIMAL] FA (NOLOCK) on AN.ID  = FA.ANIMALID 
	JOIN [dbo].[CFT_FARM] FRM (NOLOCK) on FA.FARMID  = FRM.ID 
	JOIN [dbo].[CFT_ANIMALEVENTS] AE (NOLOCK) ON AN.ID  = AE.ANIMALID  
	JOIN [dbo].[CFT_EVENTTYPE] ET (NOLOCK) ON AE.EVENTTYPEID  = ET.ID 
	LEFT JOIN [dbo].[MF_USER] MFU (NOLOCK) ON MFU.ID = AE.DEVICEID
	CROSS APPLY (Select Top 1 [TAGNBR] From [dbo].[CFT_ANIMALTAG] AS ATP WITH (NOLOCK) Where
	 	AN.ID  = ATP.[ANIMALID] AND ATP.[PRIMARYTAG] = 1 AND ATP.[ISCURRENT] = 1) ATP	
	OUTER APPLY (Select Top 1 [TAGNBR] From [dbo].[CFT_ANIMALTAG] AS ATA WITH (NOLOCK) Where
		AN.ID  = ATA.[ANIMALID] AND ATA.[PRIMARYTAG] = 0) ATA 
	Outer Apply (select top 1 RS.EVENTNAME from [dbo].[CFT_EVENTTYPE] RS where DATALENGTH(RS.REASONID) > 0 and AE.REMOVALREASONID = RS.REASONID) RS
Where ET.[EVENTTYPE] like 'Removal' AND ET.[EVENTNAME] NOT like 'Transfer Off' 
AND AE.[DELETED_BY] = -1 
AND FA.[DELETED_BY] = -1
