

CREATE VIEW 
    [dbo].[vw_EventNumbers]
AS
SELECT
	EVENTNAME	=	EVENTNAME
  , ANIMALID	=	ANIMALID
  , EVENTID		=	ID
  , EVENTNBR	=	ROW_NUMBER() OVER ( PARTITION BY ANIMALID 
		ORDER BY EVENTDATE, 
		CASE 

			WHEN EVENTTYPE = 'Breed' Then 2
			WHEN EVENTTYPE = 'Mating' Then 3
			WHEN EVENTTYPE = 'Farrowing' Then 4
			WHEN EVENTTYPE = 'Piglet' AND EVENTNAME = 'Prewean Death' Then 5
			WHEN EVENTTYPE = 'Piglet' AND EVENTNAME = 'Part Wean' Then 6
			WHEN EVENTTYPE = 'Piglet' AND EVENTNAME = 'Foster' Then 7
			WHEN EVENTTYPE = 'Piglet' AND EVENTNAME = 'Wean' Then 8
			WHEN EVENTTYPE = 'Piglet' AND EVENTNAME = 'Nurse On' Then 9
			WHEN EVENTTYPE = 'Removal' AND EVENTNAME = 'Transfer Off' Then 10
			WHEN EVENTTYPE = 'Arrival' Then 11
			WHEN EVENTTYPE = 'Removal' Then 12
			else 13
		End, MATINGNBR,MATINGHOUR
		
   ) 
FROM( 
	SELECT 
		EVENTTYPE, EVENTNAME, AE.ID, ANIMALID, EVENTDATE,MATINGNBR, MATINGHOUR FROM [MobileFrame].[dbo].[CFT_ANIMALEVENTS] AE 
		JOIN [MobileFrame].[dbo].[CFT_EVENTTYPE] ET (NOLOCK) ON AE.EVENTTYPEID  = ET.ID 
		Where AE.[DELETED_BY] = -1 
		  ) 
	AS Orders( EVENTTYPE,EVENTNAME, ID, ANIMALID, EVENTDATE,MATINGNBR,MATINGHOUR) ;







