CREATE TABLE [dbo].[BarnChar] (
    [BarnID]               INT          NOT NULL,
    [StdPenWidth]          FLOAT (53)   NULL,
    [StdPenLength]         FLOAT (53)   NULL,
    [NbrStdPens]           FLOAT (53)   NULL,
    [NbrStdPenSpace]       FLOAT (53)   NULL,
    [FloorType]            SMALLINT     NULL,
    [FeederType]           SMALLINT     NULL,
    [FeederWidth]          FLOAT (53)   NULL,
    [FeedersPerPen]        FLOAT (53)   NULL,
    [WatererType]          SMALLINT     NULL,
    [WaterersPerPen]       FLOAT (53)   NULL,
    [SupplHeat]            VARCHAR (30) NULL,
    [SupplHeatSource]      VARCHAR (30) NULL,
    [SupplHeatAvailable]   VARCHAR (30) NULL,
    [CenterToLoadoutDist]  FLOAT (53)   NULL,
    [NbrOfLoadouts]        FLOAT (53)   NULL,
    [NurAvailable]         BIT          NULL,
    [BigPen]               BIT          NULL,
    [WFCapable]            BIT          NULL,
    [WFCapableOverride]    BIT          NULL,
    [ContractType]         SMALLINT     NULL,
    [NonPigSpace]          FLOAT (53)   NULL,
    [PaymentSpaces]        FLOAT (53)   NULL,
    [UpdatedBy]            VARCHAR (50) NULL,
    [UpdatedDateTime]      DATETIME     NULL,
    [FacilityUsedAsTypeID] SMALLINT     NULL,
    CONSTRAINT [PK_BarnChar] PRIMARY KEY CLUSTERED ([BarnID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_BarnCharContractTypeNull] CHECK ([ContractType] IS NULL)
);

