CREATE LOGIN [SSIS_CornPurch]
    WITH PASSWORD = N'z{|xtcutktsmvcEorK{mq<tcmsFT7_&#$!~<uyi&sl4bzfuP', SID = 0xEC8733E05A17F14DBED2E17D02A8B244, DEFAULT_DATABASE = [CFApp_CornPurch], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

