
CREATE view [dbo].[vSiteWithContactName]

as
SELECT s.ContactID, 
s.SiteID, 
s.AccountingEntityID, 
s.DefaultPigCompanyID, 
s.FacilityTypeID,
s.OwnershipID,
s.OwnershipLevelID,
s.DepartmentCode,
s.PigRelatedGLCode,
s.OtherGLCode,
s.PremiseID,
s.RoadRestrictionTons,
s.RoundTripHours,
s.RoundTripMiles,
s.RestrictRoundTripHours,
s.RestrictRoundTripMiles,
s.OneWayMiles,
s.OneWayRestrictionMiles,
s.FeedTransferLocation,
s.FeedTransferTons,
s.AugerType,
s.AugerRatePerHour,
s.DeliverFeedFlag,
s.FeedOrderComments,
s.FeedMillContactID,
s.PFEUClassification,
s.OverheadPowerLinesFlag,
s.OfficeLocaction,
s.OfficeSize,
s.SiteAcres,
s.CollateralHolderProperty,
s.CollateralHolderPigs,
s.MAS90JobNumber,
s.FeedGrouping,
s.SiteMgrContactID,
s.GeneratorTypeID,
s.FeedOrderDay,
s.WallMapPinNbr,
s.WallMapPinLocation,
s.CompanyName,
s.SolomonProjectID,
s.PigSystemID,
s.ContractCpnyID,
s.OwningCpnyID,
s.PortChuteFlg,
s.GeoState,
s.ManureAppComm,
s.SwapAssessorContID,
s.FeedlotRegNbr,
c.ContactName,
c.StatusTypeID

FROM dbo.Site s
JOIN dbo.Contact c on s.ContactID=c.ContactID
