CREATE TABLE [dbo].[PCEventUpload] (
    [EventUploadID]           INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Form_Id]                 NUMERIC (18)  NULL,
    [FormSerialID]            VARCHAR (30)  NULL,
    [CSID]                    VARCHAR (30)  NULL,
    [Verify_Wks]              VARCHAR (30)  NULL,
    [RowNbr]                  VARCHAR (30)  NULL,
    [FarmID]                  VARCHAR (8)   NULL,
    [SowID]                   VARCHAR (12)  NULL,
    [AlternateID]             VARCHAR (20)  NULL,
    [Genetics]                VARCHAR (20)  NULL,
    [Origin]                  VARCHAR (24)  NULL,
    [BirthDate]               VARCHAR (3)   NULL,
    [EventType]               VARCHAR (20)  NULL,
    [EventDay]                VARCHAR (3)   NULL,
    [EventWeek]               VARCHAR (2)   NULL,
    [Qty]                     INT           NULL,
    [QtyBornAlive]            INT           NULL,
    [QtyStillBorn]            INT           NULL,
    [QtyMummy]                INT           NULL,
    [GroupID]                 VARCHAR (8)   NULL,
    [RoomNbr]                 SMALLINT      NULL,
    [CrateNbr]                SMALLINT      NULL,
    [FosterOn]                SMALLINT      NULL,
    [FosterOff]               SMALLINT      NULL,
    [NurseOnQty]              SMALLINT      NULL,
    [MatingType]              VARCHAR (10)  NULL,
    [SemenID]                 VARCHAR (10)  NULL,
    [ObserverID]              VARCHAR (3)   NULL,
    [HourAMPM]                VARCHAR (2)   NULL,
    [Reason]                  VARCHAR (20)  NULL,
    [ExamResult]              VARCHAR (20)  NULL,
    [BoarID]                  VARCHAR (12)  NULL,
    [BoarStatus]              VARCHAR (20)  NULL,
    [RemovalTypeID]           VARCHAR (8)   NULL,
    [ReasonID1]               SMALLINT      NULL,
    [ReasonID2]               SMALLINT      NULL,
    [Service1Date]            VARCHAR (3)   NULL,
    [Service1SemenID]         INT           NULL,
    [Service1BreederID]       VARCHAR (3)   NULL,
    [Service1AMPMFlag]        VARCHAR (2)   NULL,
    [DateInserted]            SMALLDATETIME NULL,
    [TransferStatus]          SMALLINT      NULL,
    [FinalMateTransferStatus] SMALLINT      NULL,
    [DateTransferred]         SMALLDATETIME NULL
);

