CREATE TABLE [dbo].[FAX_INFORMATION] (
    [FAX_ID]                 VARCHAR (50)  NOT NULL,
    [FARM_ID]                VARCHAR (8)   NULL,
    [FAX_ORIGINATING_NUMBER] VARCHAR (10)  NULL,
    [FAX_PROCESSED]          CHAR (1)      NULL,
    [FAX_PROCESSED_DATE]     SMALLDATETIME NULL,
    CONSTRAINT [PK_FAX_INFORMATION] PRIMARY KEY CLUSTERED ([FAX_ID] ASC) WITH (FILLFACTOR = 90)
);

