CREATE TABLE [dbo].[cft_MARKET_OPTIMIZER_WEIGHT_PREDICTOR] (
    [WK]  INT  NOT NULL,
    [WT]  INT  NOT NULL,
    [ADG] REAL NOT NULL,
    CONSTRAINT [PK_cft_MARKET_OPTIMIZER_WEIGHT_PREDICTOR] PRIMARY KEY CLUSTERED ([WK] ASC, [WT] ASC) WITH (FILLFACTOR = 90)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[cft_MARKET_OPTIMIZER_WEIGHT_PREDICTOR] TO [master]
    AS [dbo];

