CREATE TABLE [dbo].[cft_DRIVER_STATUS_TYPE] (
    [StatusID]          INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [StatusDescription] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_cft_DRIVER_STATUS_TYPE] PRIMARY KEY CLUSTERED ([StatusID] ASC) WITH (FILLFACTOR = 90)
);

