CREATE TABLE [dbo].[cft_PACKER_MARKET_OPTIMIZER_CONSTRAINT] (
    [PackerID]    INT NOT NULL,
    [QtyDayMinMo] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin1] DEFAULT (0) NOT NULL,
    [QtyDayMaxMo] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax1] DEFAULT (0) NOT NULL,
    [QtyDayMinTu] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin2] DEFAULT (0) NOT NULL,
    [QtyDayMaxTu] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax2] DEFAULT (0) NOT NULL,
    [QtyDayMinWe] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin3] DEFAULT (0) NOT NULL,
    [QtyDayMaxWe] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax3] DEFAULT (0) NOT NULL,
    [QtyDayMinTh] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin4] DEFAULT (0) NOT NULL,
    [QtyDayMaxTh] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax4] DEFAULT (0) NOT NULL,
    [QtyDayMinFr] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin5] DEFAULT (0) NOT NULL,
    [QtyDayMaxFr] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax5] DEFAULT (0) NOT NULL,
    [QtyDayMinSa] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin6] DEFAULT (0) NOT NULL,
    [QtyDayMaxSa] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax6] DEFAULT (0) NOT NULL,
    [QtyWeekMin]  INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyWeekMin] DEFAULT (0) NOT NULL,
    [QtyWeekMax]  INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyWeekMax] DEFAULT (0) NOT NULL,
    [QtyLoadMin]  INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyLoadMin] DEFAULT (0) NOT NULL,
    [QtyLoadMax]  INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyLoadMax] DEFAULT (0) NOT NULL,
    [WtWeekAvg]   INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_wtWeekAvg] DEFAULT (0) NOT NULL,
    [QtyDayMinSn] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMin7] DEFAULT (0) NULL,
    [QtyDayMaxSn] INT CONSTRAINT [DF_cft_MARKET_OPTIMIZER_CONSTRAINTS_qtyDayMax7] DEFAULT (0) NULL,
    CONSTRAINT [PK_cft_PACKER_MARKET_OPTIMIZER_CONSTRAINT] PRIMARY KEY CLUSTERED ([PackerID] ASC) WITH (FILLFACTOR = 90)
);

