CREATE TABLE [dbo].[cft_PIG_VMR] (
    [VmrId]                                  INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [EffectiveDate]                          DATETIME        NOT NULL,
    [AverageValue]                           DECIMAL (10, 4) NOT NULL,
    [OverageValue]                           DECIMAL (10, 4) NOT NULL,
    [BackFatPointSeven_LoinDepthFourLow]     DECIMAL (10, 4) NOT NULL,
    [BackFatPointEight_LoinDepthFourLow]     DECIMAL (10, 4) NOT NULL,
    [BackFatPointNine_LoinDepthFourLow]      DECIMAL (10, 4) NOT NULL,
    [BackFatOne_LoinDepthFourLow]            DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthFourLow]    DECIMAL (10, 4) NOT NULL,
    [BackFatPointNine_LoinDepthFiveLow]      DECIMAL (10, 4) NOT NULL,
    [BackFatOne_LoinDepthFiveLow]            DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthFiveLow]    DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointTwo_LoinDepthFiveLow]    DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthSixLow]     DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointTwo_LoinDepthSixLow]     DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointFour_LoinDepthSixLow]    DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointFour_LoinDepthSevenLow]  DECIMAL (10, 4) NOT NULL,
    [BackFatPointSeven_LoinDepthFourHigh]    DECIMAL (10, 4) NOT NULL,
    [BackFatPointEight_LoinDepthFourHigh]    DECIMAL (10, 4) NOT NULL,
    [BackFatPointNine_LoinDepthFourHigh]     DECIMAL (10, 4) NOT NULL,
    [BackFatOne_LoinDepthFourHigh]           DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthFourHigh]   DECIMAL (10, 4) NOT NULL,
    [BackFatPointNine_LoinDepthFiveHigh]     DECIMAL (10, 4) NOT NULL,
    [BackFatOne_LoinDepthFiveHigh]           DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthFiveHigh]   DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointTwo_LoinDepthFiveHigh]   DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointOne_LoinDepthSixHigh]    DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointTwo_LoinDepthSixHigh]    DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointFour_LoinDepthSixHigh]   DECIMAL (10, 4) NOT NULL,
    [BackFatOnePointFour_LoinDepthSevenHigh] DECIMAL (10, 4) NOT NULL,
    [CreatedDateTime]                        DATETIME        CONSTRAINT [DF_cft_PIG_VMR_CreatedDateTime] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                              VARCHAR (50)    NOT NULL,
    [UpdatedDateTime]                        DATETIME        NULL,
    [UpdatedBy]                              VARCHAR (50)    NULL,
    CONSTRAINT [PK_PIG_VMR] PRIMARY KEY CLUSTERED ([VmrId] ASC) WITH (FILLFACTOR = 90)
);

