CREATE TABLE [dbo].[cft_SLF_FOURPHASE_COMPOSITION] (
    [CombPigGroupID] CHAR (50)  NOT NULL,
    [G1_PigGroupID]  CHAR (10)  NOT NULL,
    [G1G2_Qty]       INT        NOT NULL,
    [G1G2_TotalWgt]  FLOAT (53) NOT NULL,
    [G1G2_WgtGained] FLOAT (53) NOT NULL,
    [G1G2_PigDays]   FLOAT (53) NOT NULL,
    [G1G2_HC_Pct]    FLOAT (53) NOT NULL,
    [G1G2_WT_Pct]    FLOAT (53) NOT NULL,
    [G1G2_WG_Pct]    FLOAT (53) NOT NULL,
    [G1G2_PD_Pct]    FLOAT (53) NOT NULL,
    [G2_Qty]         INT        NOT NULL,
    [G2_TotalWgt]    FLOAT (53) NOT NULL,
    [G2_WgtGained]   FLOAT (53) NOT NULL,
    [G2_PigDays]     FLOAT (53) NOT NULL,
    [G2_PigGroupID]  CHAR (10)  NOT NULL,
    [G2G3_Qty]       INT        NOT NULL,
    [G2G3_TotalWgt]  FLOAT (53) NOT NULL,
    [G2G3_WgtGained] FLOAT (53) NOT NULL,
    [G2G3_PigDays]   FLOAT (53) NOT NULL,
    [G2G3_HC_Pct]    FLOAT (53) NOT NULL,
    [G2G3_WT_Pct]    FLOAT (53) NOT NULL,
    [G2G3_WG_Pct]    FLOAT (53) NOT NULL,
    [G2G3_PD_Pct]    FLOAT (53) NOT NULL,
    [G3_Qty]         INT        NOT NULL,
    [G3_TotalWgt]    FLOAT (53) NOT NULL,
    [G3_WgtGained]   FLOAT (53) NOT NULL,
    [G3_PigDays]     FLOAT (53) NOT NULL,
    [G3_PigGroupID]  CHAR (10)  NOT NULL,
    [G3G4_Qty]       INT        NOT NULL,
    [G3G4_TotalWgt]  FLOAT (53) NOT NULL,
    [G3G4_WgtGained] FLOAT (53) NOT NULL,
    [G3G4_PigDays]   FLOAT (53) NOT NULL,
    [G3G4_HC_Pct]    FLOAT (53) NOT NULL,
    [G3G4_WT_Pct]    FLOAT (53) NOT NULL,
    [G3G4_WG_Pct]    FLOAT (53) NOT NULL,
    [G3G4_PD_Pct]    FLOAT (53) NOT NULL,
    [G4_Qty]         INT        NOT NULL,
    [G4_TotalWgt]    FLOAT (53) NOT NULL,
    [G4_WgtGained]   FLOAT (53) NOT NULL,
    [G4_PigDays]     FLOAT (53) NOT NULL,
    [G4_PigGroupID]  CHAR (10)  NOT NULL
);

