CREATE TABLE [dbo].[cft_SBF_PigGroup_REF] (
    [ActStartDate]        DATETIME      NULL,
    [Crtd_dateTime]       DATETIME      NULL,
    [ActCloseDate]        DATETIME      NULL,
    [Lupd_DateTime]       DATETIME      NULL,
    [BarnNbr]             VARCHAR (6)   NULL,
    [FlowID]              INT           NULL,
    [PigFlowDescription]  VARCHAR (50)  NULL,
    [SiteContactID]       VARCHAR (8)   NULL,
    [SiteName]            VARCHAR (50)  NULL,
    [PG_Description]      VARCHAR (100) NULL,
    [EstCloseDate]        DATETIME      NULL,
    [EstStartWeight]      INT           NULL,
    [FeedMillContactID]   VARCHAR (8)   NULL,
    [FeedMillName]        VARCHAR (50)  NULL,
    [InitialPigValue]     FLOAT (53)    NULL,
    [PGStatusID]          VARCHAR (1)   NULL,
    [PigGroupId]          VARCHAR (6)   NOT NULL,
    [PigProdPhaseID]      VARCHAR (3)   NULL,
    [PriorFeedQty]        FLOAT (53)    NULL,
    [ProjectID]           VARCHAR (8)   NULL,
    [TaskID]              VARCHAR (8)   NULL,
    [PigGenderTypeID]     VARCHAR (1)   NULL,
    [PigChampGeneticName] VARCHAR (30)  NULL,
    [EstDaysOfAge]        FLOAT (53)    NULL,
    [EstPlacementAge]     FLOAT (53)    NULL,
    [AvgStartWeight]      FLOAT (53)    NULL,
    [FirstPlacementDt]    DATETIME      NULL,
    [EstInventory]        INT           NULL,
    [SiteOwnerShip]       VARCHAR (8)   NULL,
    [StdCapacity]         INT           NULL,
    [StockingMultiplier]  VARCHAR (1)   NULL,
    [OriginSiteContactID] VARCHAR (8)   NULL,
    [AirSpaceOnMove]      VARCHAR (1)   NULL,
    [SBFNurSrceContactID] VARCHAR (3)   NULL,
    [SBF_SiteID]          VARCHAR (3)   NULL,
    [SBFSrceSowFarm]      VARCHAR (3)   NULL,
    [MailAction]          VARCHAR (20)  NULL,
    [MailedDate]          DATETIME      NULL,
    [RoomNbr]             VARCHAR (20)  NULL,
    CONSTRAINT [pk_cft_SBF_PigGroup_REF] PRIMARY KEY CLUSTERED ([PigGroupId] ASC) WITH (FILLFACTOR = 90)
);

