CREATE TABLE [dbo].[cft_ESSBASE_CLOSEOUT_GROUPDATA] (
    [GroupNumber]        CHAR (32)    NOT NULL,
    [Phase]              CHAR (30)    NOT NULL,
    [ServiceManager]     CHAR (50)    NOT NULL,
    [Pod]                CHAR (30)    NOT NULL,
    [System]             CHAR (30)    NOT NULL,
    [FiscalYear]         CHAR (12)    NOT NULL,
    [PICQuarter]         CHAR (12)    NOT NULL,
    [FYPeriod]           CHAR (12)    NOT NULL,
    [Time]               CHAR (12)    NOT NULL,
    [Scenario]           CHAR (30)    NOT NULL,
    [TI_Qty]             INT          NULL,
    [MI_Qty]             INT          NULL,
    [MO_Qty]             INT          NULL,
    [Death_Qty]          INT          NULL,
    [TO_Qty]             INT          NULL,
    [TE_Qty]             INT          NULL,
    [Closeout_Qty]       INT          NULL,
    [Top_Qty]            INT          NULL,
    [Cull_Qty]           INT          NULL,
    [DP_Qty]             INT          NULL,
    [DT_Qty]             INT          NULL,
    [DY_Qty]             INT          NULL,
    [CD_Qty]             INT          NULL,
    [CP_Qty]             INT          NULL,
    [euthanized_Qty]     INT          NULL,
    [deadb4grd_Qty]      INT          NULL,
    [dot_td_Qty]         INT          NULL,
    [IA_Qty]             INT          NULL,
    [TI_Wt]              NUMERIC (18) NULL,
    [MI_Wt]              NUMERIC (18) NULL,
    [MO_Wt]              NUMERIC (18) NULL,
    [TO_Wt]              NUMERIC (18) NULL,
    [TE_Wt]              NUMERIC (18) NULL,
    [Closeout_Wt]        NUMERIC (18) NULL,
    [Top_Wt]             NUMERIC (18) NULL,
    [Cull_Wt]            NUMERIC (18) NULL,
    [DP_Wt]              NUMERIC (18) NULL,
    [DT_Wt]              NUMERIC (18) NULL,
    [DY_Wt]              NUMERIC (18) NULL,
    [CD_Wt]              NUMERIC (18) NULL,
    [CP_Wt]              NUMERIC (18) NULL,
    [euthanized_Wt]      NUMERIC (18) NULL,
    [deadb4grd_Wt]       NUMERIC (18) NULL,
    [dot_td_Wt]          NUMERIC (18) NULL,
    [LivePigDays]        BIGINT       NULL,
    [DeadPigDays]        BIGINT       NULL,
    [FeedQty]            NUMERIC (18) NULL,
    [FeedQuantity_75]    NUMERIC (18) NULL,
    [FirstPayleanDate]   INT          NULL,
    [DaysOnPaylean]      BIGINT       NULL,
    [LivePayleanPigDays] BIGINT       NULL,
    [FiscalStartDate]    INT          NULL,
    [PigStartDate]       INT          NULL,
    [PigEndDate]         INT          NULL,
    [HdCapacity]         INT          NULL,
    [FeedQuantity_55]    NUMERIC (18) NULL,
    [First55Date]        INT          NULL,
    [DaysOn55]           BIGINT       NULL,
    [FeedQuantity_54]    NUMERIC (18) NULL,
    [First54Date]        INT          NULL,
    [DaysOn54]           BIGINT       NULL
);

