CREATE TABLE [dbo].[cft_MARKET_LOAD2] (
    [MarketLoadID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [PMLoadID]                  CHAR (10)     NULL,
    [OriginSiteContactID]       CHAR (10)     NULL,
    [OriginSiteName]            CHAR (50)     NULL,
    [DestContactID]             CHAR (10)     NULL,
    [PigGroupID]                CHAR (10)     NULL,
    [PigQuantity]               BIGINT        NULL,
    [LoadWeight]                BIGINT        NULL,
    [Standards]                 SMALLINT      NULL,
    [DoA]                       SMALLINT      NULL,
    [DiY]                       SMALLINT      NULL,
    [Subs]                      SMALLINT      NULL,
    [Paylean]                   VARCHAR (7)   NULL,
    [MovementDate]              SMALLDATETIME NULL,
    [PackerContactID]           CHAR (10)     NULL,
    [PackerName]                CHAR (50)     NULL,
    [LoadCrewName]              VARCHAR (50)  NULL,
    [TruckerContactID]          CHAR (10)     NULL,
    [TruckerName]               CHAR (50)     NULL,
    [Distance]                  FLOAT (53)    NULL,
    [PigFlowID]                 INT           NULL,
    [SplitLoad]                 BIT           NULL,
    [ServiceManagerContactID]   CHAR (10)     NULL,
    [ServiceManagerName]        CHAR (50)     NULL,
    [SrServiceManagerContactID] CHAR (10)     NULL,
    [SrServiceManagerName]      CHAR (50)     NULL,
    [ImportDate]                DATETIME      NULL
);

