CREATE TABLE [dbo].[cft_SLF_GENERATIONAL_DATA_RAW] (
    [SLF_Status]     CHAR (1)      NULL,
    [G1_PigGroupID]  CHAR (10)     NOT NULL,
    [G1_MasterGroup] CHAR (10)     NOT NULL,
    [MGActCloseDate] SMALLDATETIME NOT NULL,
    [G1_Phase]       CHAR (3)      NOT NULL,
    [G2_PigGroupID]  CHAR (10)     NULL,
    [G2_Project]     CHAR (16)     NULL,
    [G2_Phase]       CHAR (3)      NULL,
    [G2_Cost]        SMALLINT      NULL,
    [G2_Status]      CHAR (2)      NULL,
    [G2_System]      CHAR (10)     NULL,
    [G3_PigGroupID]  CHAR (10)     NULL,
    [G3_Project]     CHAR (16)     NULL,
    [G3_Phase]       CHAR (3)      NULL,
    [G3_Cost]        SMALLINT      NULL,
    [G3_Status]      CHAR (2)      NULL,
    [G3_System]      CHAR (10)     NULL,
    [G4_PigGroupID]  CHAR (10)     NULL,
    [G4_Project]     CHAR (16)     NULL,
    [G4_Phase]       CHAR (3)      NULL,
    [G4_Cost]        SMALLINT      NULL,
    [G4_Status]      CHAR (2)      NULL,
    [G4_System]      CHAR (10)     NULL,
    [G5_PigGroupID]  CHAR (10)     NULL,
    [G5_Project]     CHAR (16)     NULL,
    [G5_Phase]       CHAR (3)      NULL,
    [G5_Cost]        SMALLINT      NULL,
    [G5_Status]      CHAR (2)      NULL,
    [G5_System]      CHAR (10)     NULL,
    [G6_PigGroupID]  CHAR (10)     NULL,
    [G6_Project]     CHAR (16)     NULL,
    [G6_Phase]       CHAR (3)      NULL,
    [G6_Cost]        SMALLINT      NULL,
    [G6_Status]      CHAR (2)      NULL,
    [G6_System]      CHAR (10)     NULL,
    [G7_PigGroupID]  CHAR (10)     NULL,
    [G7_Project]     CHAR (16)     NULL,
    [G7_Phase]       CHAR (3)      NULL,
    [G7_Cost]        SMALLINT      NULL,
    [G7_Status]      CHAR (2)      NULL,
    [G7_System]      CHAR (10)     NULL,
    [G8_PigGroupID]  CHAR (10)     NULL,
    [G8_Project]     CHAR (16)     NULL,
    [G8_Phase]       CHAR (3)      NULL,
    [G8_Cost]        SMALLINT      NULL,
    [G8_Status]      CHAR (2)      NULL,
    [G8_System]      CHAR (10)     NULL,
    [G9_PigGroupID]  CHAR (10)     NULL,
    [G9_Project]     CHAR (16)     NULL,
    [G9_Phase]       CHAR (3)      NULL,
    [G9_Cost]        SMALLINT      NULL,
    [G9_Status]      CHAR (2)      NULL,
    [G9_System]      CHAR (10)     NULL
);

