CREATE TABLE [dbo].[cft_SLF_FLow_Ranking_Rpt4] (
    [PicYearWeek]                 VARCHAR (6)   NOT NULL,
    [ReportingGroupID]            INT           NOT NULL,
    [Reporting_Group_Description] VARCHAR (100) NULL,
    [Avg Wean Age]                FLOAT (53)    NULL,
    [Avg Wean Wgt]                FLOAT (53)    NULL,
    [ADG FH]                      FLOAT (53)    NULL,
    [ADG Nursery]                 FLOAT (53)    NULL,
    [ADG Finish]                  FLOAT (53)    NULL,
    [ADG WTF]                     FLOAT (53)    NULL,
    [ADG rollup]                  FLOAT (53)    NULL,
    [ADG_Rank]                    FLOAT (53)    NULL,
    [WP_CostPerPig]               FLOAT (53)    NULL,
    [FP_CostPerPig]               FLOAT (53)    NULL,
    [Feed_Cost_of_Gain]           FLOAT (53)    NULL,
    [TotCost_of_gain_per_cwt]     FLOAT (53)    NULL,
    [revenue_per_cwt]             FLOAT (53)    NULL,
    [margin_per_cwt]              FLOAT (53)    NULL,
    [Med_per_HS]                  FLOAT (53)    NULL,
    [Vacc_per_HS]                 FLOAT (53)    NULL,
    [TotCost_per_cwt]             FLOAT (53)    NULL,
    [COST_Rank]                   FLOAT (53)    NULL,
    [Lac_lbs_day]                 FLOAT (53)    NULL,
    [Lac_days]                    FLOAT (53)    NULL,
    [Lac_lbs_sow_year]            FLOAT (53)    NULL,
    [Gest_lbs_day]                FLOAT (53)    NULL,
    [Gest_days]                   FLOAT (53)    NULL,
    [Gest_lbs_sow_year]           FLOAT (53)    NULL,
    [Tot_tonsowyear]              FLOAT (53)    NULL,
    [NurFE]                       FLOAT (53)    NULL,
    [FinFE]                       FLOAT (53)    NULL,
    [WTFFE]                       FLOAT (53)    NULL,
    [WholeHerdFE]                 FLOAT (53)    NULL,
    [FE_Rank]                     FLOAT (53)    NULL,
    [PctPrim]                     FLOAT (53)    NULL,
    [PctReSale]                   FLOAT (53)    NULL,
    [PctCull]                     FLOAT (53)    NULL,
    [Avg_Mkt_Wgt]                 FLOAT (53)    NULL,
    [PigMkt_sowperyear]           FLOAT (53)    NULL,
    [LBS_invsowperyear]           FLOAT (53)    NULL,
    [lbs_sowperyear_Rank]         FLOAT (53)    NULL,
    [Avg_born]                    FLOAT (53)    NULL,
    [Avg_BornAlive]               FLOAT (53)    NULL,
    [Wean/Litter]                 FLOAT (53)    NULL,
    [PctMummy]                    FLOAT (53)    NULL,
    [PctStillBorn]                FLOAT (53)    NULL,
    [PctFarHouse]                 FLOAT (53)    NULL,
    [NurDOTpct]                   FLOAT (53)    NULL,
    [NurMortpct]                  FLOAT (53)    NULL,
    [FinDOTpct]                   FLOAT (53)    NULL,
    [FinMortpct]                  FLOAT (53)    NULL,
    [WTFDOTpct]                   FLOAT (53)    NULL,
    [WTFMortpct]                  FLOAT (53)    NULL,
    [DOTpct]                      FLOAT (53)    NULL,
    [DIYpct]                      FLOAT (53)    NULL,
    [Compct]                      FLOAT (53)    NULL,
    [TotPctMort]                  FLOAT (53)    NULL,
    [Mort_Rank]                   FLOAT (53)    NULL,
    [Total_Rank]                  FLOAT (53)    NULL,
    PRIMARY KEY CLUSTERED ([PicYearWeek] ASC, [ReportingGroupID] ASC) WITH (FILLFACTOR = 90)
);

