CREATE TABLE [dbo].[cft_SLF_ESSBASE_DATA_COSTS] (
    [Site]                        CHAR (30)     NOT NULL,
    [MasterGroup]                 CHAR (10)     NOT NULL,
    [MasterGroupDescription]      CHAR (40)     NOT NULL,
    [FlowGroup]                   CHAR (10)     NOT NULL,
    [FlowGroupDescription]        CHAR (50)     NOT NULL,
    [CombWTFGroup]                CHAR (50)     NOT NULL,
    [Phase]                       CHAR (3)      NOT NULL,
    [PhaseTypeDesc]               CHAR (50)     NOT NULL,
    [PigFlowID]                   INT           NULL,
    [PigFlowDescription]          CHAR (50)     NULL,
    [PG_Week]                     CHAR (6)      NOT NULL,
    [MG_Week]                     CHAR (6)      NOT NULL,
    [Scenario]                    CHAR (30)     NOT NULL,
    [FEED_ISSUE]                  FLOAT (53)    NOT NULL,
    [FREIGHT]                     FLOAT (53)    NOT NULL,
    [MISC_JOB_CHARGES]            FLOAT (53)    NOT NULL,
    [OTHER_REVENUE]               FLOAT (53)    NOT NULL,
    [PIG_BASE_DOLLARS]            FLOAT (53)    NOT NULL,
    [PIG_DEATH]                   FLOAT (53)    NOT NULL,
    [PIG_FEED_DELIV]              FLOAT (53)    NOT NULL,
    [PIG_FEED_GRD_MIX]            FLOAT (53)    NOT NULL,
    [PIG_FEED_ISSUE]              FLOAT (53)    NOT NULL,
    [PIG_GRADE_PREM]              FLOAT (53)    NOT NULL,
    [PIG_INT_WC_CHG]              FLOAT (53)    NOT NULL,
    [PIG_MEDS_CHG]                FLOAT (53)    NOT NULL,
    [PIG_MEDS_ISSUE]              FLOAT (53)    NOT NULL,
    [PIG_MISC_EXP]                FLOAT (53)    NOT NULL,
    [PIG_MKT_TRUCKING]            FLOAT (53)    NOT NULL,
    [PIG_MOVE_IN]                 FLOAT (53)    NOT NULL,
    [PIG_MOVE_OUT]                FLOAT (53)    NOT NULL,
    [PIG_OVR_HD_CHG]              FLOAT (53)    NOT NULL,
    [PIG_OVR_HD_COST]             FLOAT (53)    NOT NULL,
    [PIG_PURCHASE]                FLOAT (53)    NOT NULL,
    [PIG_SALE]                    FLOAT (53)    NOT NULL,
    [PIG_SALE_DED_OTR]            FLOAT (53)    NOT NULL,
    [PIG_SITE_CHG]                FLOAT (53)    NOT NULL,
    [PIG_SORT_LOSS]               FLOAT (53)    NOT NULL,
    [PIG_TRANSFER_IN]             FLOAT (53)    NOT NULL,
    [PIG_TRANSFER_OUT]            FLOAT (53)    NOT NULL,
    [PIG_TRUCKING_CHG]            FLOAT (53)    NOT NULL,
    [PIG_TRUCKING_IN]             FLOAT (53)    NOT NULL,
    [PIG_VACC_CHG]                FLOAT (53)    NOT NULL,
    [PIG_VACC_ISSUE]              FLOAT (53)    NOT NULL,
    [PIG_VET_CHG]                 FLOAT (53)    NOT NULL,
    [REPAIR_MAINT]                FLOAT (53)    NOT NULL,
    [REPAIR_PARTS]                FLOAT (53)    NOT NULL,
    [SITE_COST_ACCUM]             FLOAT (53)    NOT NULL,
    [SUPPLIES]                    FLOAT (53)    NOT NULL,
    [TRANSPORT_DEATH]             FLOAT (53)    NOT NULL,
    [ReportingGroupID]            INT           NULL,
    [Reporting_Group_Description] VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([CombWTFGroup] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [idx_cft_SLF_ESSBASE_DATA_COSTS_rg_week]
    ON [dbo].[cft_SLF_ESSBASE_DATA_COSTS]([ReportingGroupID] ASC, [MG_Week] ASC)
    INCLUDE([OTHER_REVENUE], [PIG_BASE_DOLLARS], [PIG_DEATH], [PIG_FEED_DELIV], [PIG_FEED_GRD_MIX], [PIG_FEED_ISSUE], [PIG_GRADE_PREM], [PIG_INT_WC_CHG], [PIG_MEDS_CHG], [PIG_MEDS_ISSUE], [PIG_MISC_EXP], [PIG_MKT_TRUCKING], [PIG_MOVE_IN], [PIG_MOVE_OUT], [PIG_OVR_HD_CHG], [PIG_OVR_HD_COST], [PIG_PURCHASE], [PIG_SALE], [PIG_SALE_DED_OTR], [PIG_SITE_CHG], [PIG_SORT_LOSS], [PIG_TRANSFER_IN], [PIG_TRANSFER_OUT], [PIG_TRUCKING_CHG], [PIG_TRUCKING_IN], [PIG_VACC_CHG], [PIG_VACC_ISSUE], [PIG_VET_CHG], [REPAIR_MAINT], [SUPPLIES], [TRANSPORT_DEATH], [Reporting_Group_Description]) WITH (FILLFACTOR = 90);

