CREATE TABLE [dbo].[cft_Closeout_Summary_Report] (
    [TaskID]                     CHAR (32)       NOT NULL,
    [Description]                CHAR (30)       NULL,
    [SowSource]                  VARCHAR (8000)  NULL,
    [PigFlowDescription]         VARCHAR (100)   NOT NULL,
    [PigStartDate]               DATETIME        NULL,
    [PigEndDate]                 DATETIME        NULL,
    [picyear_week]               CHAR (6)        NULL,
    [period]                     CHAR (7)        NULL,
    [PGStatusID]                 CHAR (2)        NULL,
    [PigGenderTypeID]            CHAR (6)        NULL,
    [Phase]                      VARCHAR (30)    NULL,
    [PhaseDesc]                  VARCHAR (30)    NULL,
    [SvcManager]                 VARCHAR (100)   NULL,
    [SrSvcManager]               VARCHAR (100)   NULL,
    [ContactName]                CHAR (50)       NOT NULL,
    [LivePigDays]                BIGINT          NULL,
    [DeadPigDays]                BIGINT          NULL,
    [TotalPigDays]               BIGINT          NULL,
    [Feed_Qty]                   NUMERIC (14, 2) NULL,
    [TransferIn_Qty]             INT             NULL,
    [MoveIn_Qty]                 INT             NULL,
    [MoveOut_Qty]                INT             NULL,
    [PigDeath_Qty]               INT             NULL,
    [TransferOut_Qty]            INT             NULL,
    [TransferToTailender_Qty]    INT             NULL,
    [HeadSold]                   INT             NULL,
    [TotalHeadProduced]          INT             NULL,
    [Prim_Qty]                   INT             NULL,
    [Cull_Qty]                   INT             NULL,
    [DeadPigsToPacker_Qty]       INT             NULL,
    [TransportDeath_Qty]         INT             NULL,
    [InventoryAdjustment_Qty]    INT             NULL,
    [Top_Qty]                    INT             NULL,
    [TransferIn_Wt]              NUMERIC (14, 2) NULL,
    [MoveIn_Wt]                  NUMERIC (14, 2) NULL,
    [MoveOut_Wt]                 NUMERIC (14, 2) NULL,
    [TransferOut_Wt]             NUMERIC (14, 2) NULL,
    [TransferToTailender_Wt]     NUMERIC (14, 2) NULL,
    [Prim_Wt]                    NUMERIC (14, 2) NULL,
    [Cull_Wt]                    NUMERIC (14, 2) NULL,
    [DeadPigsToPacker_Wt]        NUMERIC (14, 2) NULL,
    [TransportDeath_Wt]          NUMERIC (14, 2) NULL,
    [Top_Wt]                     NUMERIC (14, 2) NULL,
    [AverageMarket_Wt]           NUMERIC (14, 2) NULL,
    [WeightGained]               NUMERIC (14, 2) NULL,
    [HeadStarted]                INT             NULL,
    [AverageDailyGain]           NUMERIC (14, 3) NULL,
    [FeedToGain]                 NUMERIC (14, 3) NULL,
    [AdjFeedToGain]              NUMERIC (14, 3) NULL,
    [Mortality]                  NUMERIC (14, 2) NULL,
    [AveragePurchase_Wt]         NUMERIC (14, 1) NULL,
    [AverageOut_Wt]              NUMERIC (14, 1) NULL,
    [AverageDailyFeedIntake]     NUMERIC (14, 2) NULL,
    [Tailender_Pct]              NUMERIC (5, 2)  NULL,
    [DeadPigsToPacker_Pct]       NUMERIC (5, 2)  NULL,
    [Cull_Pct]                   NUMERIC (5, 2)  NULL,
    [NoValue_Pct]                NUMERIC (5, 2)  NULL,
    [MedicationCost]             NUMERIC (14, 2) NULL,
    [MedicationCostPerHead]      NUMERIC (14, 2) NULL,
    [MedicationCostPerHeadSold]  NUMERIC (8, 2)  NULL,
    [VaccinationCost]            NUMERIC (14, 2) NULL,
    [VaccinationCostPerHeadSold] NUMERIC (8, 2)  NULL,
    [FeedCost]                   NUMERIC (14, 2) NULL,
    [HeadCapacity]               INT             NULL,
    [DaysInGroup]                INT             NULL,
    [PigCapacityDays]            INT             NULL,
    [EmptyDays]                  INT             NULL,
    [EmptyCapacityDays]          INT             NULL,
    [CapacityDays]               INT             NULL,
    [TotalCapacityDays]          INT             NULL,
    [AverageDaysInGroup]         INT             NULL,
    [AverageEmptyDays]           INT             NULL,
    [Utilization]                DECIMAL (6, 2)  NULL,
    [FeedCostPerHundredGain]     NUMERIC (8, 2)  NULL,
    [HeadForAdjFG]               INT             NULL,
    [ForAdjFGCalc]               NUMERIC (14, 2) NULL
);

