

CREATE  PROC [dbo].[SSIS_ClearSowTablesSpecificFarmSow]
	@FarmID varchar(8),
	@SowID varchar(12)
	As
	SET NOCOUNT ON

	BEGIN TRANSACTION
	DELETE FROM dbo.Sow WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowParity WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowGroupEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowLocationEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowMatingEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFalloutEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFarrowEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowPigletDeathEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowNonServiceEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowNurseEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowFosterEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowPregExamEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowWeanEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	BEGIN TRANSACTION
	DELETE FROM dbo.SowRemoveEvent WHERE FarmID = @FarmID And SowID = @SowID
	COMMIT TRANSACTION

	SET NOCOUNT OFF



GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SSIS_ClearSowTablesSpecificFarmSow] TO [db_sp_exec]
    AS [dbo];

