CREATE TABLE [dbo].[cftPigPreMkt] (
    [AdjCurrentInv]   INT           NOT NULL,
    [AdjCurWgtProd]   FLOAT (53)    NOT NULL,
    [AdjDaysOnFeed]   INT           NOT NULL,
    [AdjFeedEff]      FLOAT (53)    NOT NULL,
    [AdjFeedLbs]      FLOAT (53)    NOT NULL,
    [AdjProjCloseOut] SMALLDATETIME NOT NULL,
    [AdjSaleQty]      INT           NOT NULL,
    [AdjSaleWgt]      FLOAT (53)    NOT NULL,
    [AdjWgttoClose]   FLOAT (53)    NOT NULL,
    [CalcCurWgt]      FLOAT (53)    NOT NULL,
    [CalcDeadWgt]     FLOAT (53)    NOT NULL,
    [CalcOutWgt]      FLOAT (53)    NOT NULL,
    [Company]         CHAR (10)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [CurrentInv]      INT           NOT NULL,
    [CurrentWgtProd]  FLOAT (53)    NOT NULL,
    [DaysOnFeed]      INT           NOT NULL,
    [DeadQty]         INT           NOT NULL,
    [FacilityType]    CHAR (30)     NOT NULL,
    [FeedEfficiency]  FLOAT (53)    NOT NULL,
    [FeedInventory]   FLOAT (53)    NOT NULL,
    [FeedInvDate]     SMALLDATETIME NOT NULL,
    [FeedLbs]         FLOAT (53)    NOT NULL,
    [Gender]          CHAR (6)      NOT NULL,
    [LastFeed]        SMALLDATETIME NOT NULL,
    [LastSale]        SMALLDATETIME NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [MktMgrID]        CHAR (6)      NOT NULL,
    [NextMarketDate]  SMALLDATETIME NOT NULL,
    [NoteID]          INT           NOT NULL,
    [PhaseDesc]       CHAR (30)     NOT NULL,
    [PigGroupDesc]    CHAR (30)     NOT NULL,
    [PigGroupID]      CHAR (10)     NOT NULL,
    [PodID]           CHAR (3)      NOT NULL,
    [ProjCloseOut]    SMALLDATETIME NOT NULL,
    [SaleQty]         INT           NOT NULL,
    [SaleWgt]         FLOAT (53)    NOT NULL,
    [SiteContactID]   CHAR (6)      NOT NULL,
    [StartDate]       SMALLDATETIME NOT NULL,
    [StartQty]        INT           NOT NULL,
    [StartWgt]        FLOAT (53)    NOT NULL,
    [SvcMgrID]        CHAR (6)      NOT NULL,
    [TargetWgt]       FLOAT (53)    NOT NULL,
    [TrCloseDate]     DATETIME      NOT NULL,
    [WgttoClose]      FLOAT (53)    NOT NULL,
    [tstamp]          ROWVERSION    NULL,
    CONSTRAINT [cftPigPreMkt0] PRIMARY KEY CLUSTERED ([PigGroupID] ASC) WITH (FILLFACTOR = 90)
);

