CREATE TABLE [dbo].[GLSetup] (
    [Addr1]             CHAR (30)     NOT NULL,
    [Addr2]             CHAR (30)     NOT NULL,
    [AllowPostOpt]      CHAR (1)      DEFAULT ('A') NOT NULL,
    [AutoBatRpt]        SMALLINT      NOT NULL,
    [AutoPost]          CHAR (1)      NOT NULL,
    [AutoRef]           CHAR (1)      NOT NULL,
    [AutoRevOpt]        CHAR (1)      NOT NULL,
    [BaseCuryId]        CHAR (4)      NOT NULL,
    [BatCntrlByMod]     CHAR (150)    NOT NULL,
    [BegFiscalYr]       SMALLINT      NOT NULL,
    [BudgetLedgerID]    CHAR (10)     NOT NULL,
    [BudgetSpreadDir]   CHAR (50)     NOT NULL,
    [BudgetSpreadType]  CHAR (1)      NOT NULL,
    [BudgetSubSeg00]    CHAR (1)      NOT NULL,
    [BudgetSubSeg01]    CHAR (1)      NOT NULL,
    [BudgetSubSeg02]    CHAR (1)      NOT NULL,
    [BudgetSubSeg03]    CHAR (1)      NOT NULL,
    [BudgetSubSeg04]    CHAR (1)      NOT NULL,
    [BudgetSubSeg05]    CHAR (1)      NOT NULL,
    [BudgetSubSeg06]    CHAR (1)      NOT NULL,
    [BudgetSubSeg07]    CHAR (1)      NOT NULL,
    [BudgetYear]        CHAR (4)      NOT NULL,
    [Central_Cash_Cntl] SMALLINT      NOT NULL,
    [ChngNbrPer]        SMALLINT      NOT NULL,
    [City]              CHAR (30)     NOT NULL,
    [COAOrder]          CHAR (1)      NOT NULL,
    [Country]           CHAR (3)      NOT NULL,
    [CpnyId]            CHAR (10)     NOT NULL,
    [CpnyName]          CHAR (30)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [EditInit]          SMALLINT      NOT NULL,
    [EmplId]            CHAR (12)     NOT NULL,
    [Fax]               CHAR (30)     NOT NULL,
    [FiscalPerEnd00]    CHAR (4)      NOT NULL,
    [FiscalPerEnd01]    CHAR (4)      NOT NULL,
    [FiscalPerEnd02]    CHAR (4)      NOT NULL,
    [FiscalPerEnd03]    CHAR (4)      NOT NULL,
    [FiscalPerEnd04]    CHAR (4)      NOT NULL,
    [FiscalPerEnd05]    CHAR (4)      NOT NULL,
    [FiscalPerEnd06]    CHAR (4)      NOT NULL,
    [FiscalPerEnd07]    CHAR (4)      NOT NULL,
    [FiscalPerEnd08]    CHAR (4)      NOT NULL,
    [FiscalPerEnd09]    CHAR (4)      NOT NULL,
    [FiscalPerEnd10]    CHAR (4)      NOT NULL,
    [FiscalPerEnd11]    CHAR (4)      NOT NULL,
    [FiscalPerEnd12]    CHAR (4)      NOT NULL,
    [Init]              SMALLINT      NOT NULL,
    [LastBatNbr]        CHAR (10)     NOT NULL,
    [LastClosePerNbr]   CHAR (6)      NOT NULL,
    [LedgerID]          CHAR (10)     NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME NOT NULL,
    [LUpd_Prog]         CHAR (8)      NOT NULL,
    [LUpd_User]         CHAR (10)     NOT NULL,
    [Master_Fed_ID]     INT           NOT NULL,
    [MCActive]          SMALLINT      NOT NULL,
    [MCuryBatRpt]       SMALLINT      NOT NULL,
    [ModPriorPost]      CHAR (180)    NOT NULL,
    [Mult_Cpny_Db]      SMALLINT      NOT NULL,
    [NbrPer]            SMALLINT      NOT NULL,
    [NoteID]            INT           NOT NULL,
    [PerNbr]            CHAR (6)      NOT NULL,
    [PerRetHist]        SMALLINT      NOT NULL,
    [PerRetModTran]     SMALLINT      NOT NULL,
    [PerRetTran]        SMALLINT      NOT NULL,
    [Phone]             CHAR (30)     NOT NULL,
    [PriorYearPost]     SMALLINT      DEFAULT ((0)) NOT NULL,
    [PSC]               CHAR (4)      NOT NULL,
    [RetEarnAcct]       CHAR (10)     NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [SetupId]           CHAR (2)      NOT NULL,
    [State]             CHAR (3)      NOT NULL,
    [SubAcctSeg]        CHAR (2)      NOT NULL,
    [SummPostYCntr]     INT           NOT NULL,
    [UpdateCA]          SMALLINT      NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [ValidateAcctSub]   SMALLINT      NOT NULL,
    [ValidateAtPosting] SMALLINT      NOT NULL,
    [YtdNetIncAcct]     CHAR (10)     NOT NULL,
    [ZCount]            SMALLINT      NOT NULL,
    [Zip]               CHAR (10)     NOT NULL,
    [Zp]                CHAR (256)    NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [GLSetup0] PRIMARY KEY CLUSTERED ([SetupId] ASC),
    CONSTRAINT [CK_GLSetup_AllowPostOpt] CHECK ([AllowPostOpt]='A' OR [AllowPostOpt]='P'),
    CONSTRAINT [CK_GLSetup_PriorYearPost] CHECK ([PriorYearPost]=(0) OR [PriorYearPost]=(1))
);

