CREATE TABLE [dbo].[Inventory] (
    [ABCCode]           CHAR (2)      DEFAULT (' ') NOT NULL,
    [ApprovedVendor]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoPODropShip]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [AutoPOPolicy]      CHAR (2)      DEFAULT (' ') NOT NULL,
    [BMIDirStdCost]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIFOvhStdCost]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMILastCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIPDirStdCost]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIPFOvhStdCost]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIPStdCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIPVOvhStdCost]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIStdCost]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIVOvhStdCost]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BOLCode]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [Buyer]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [ChkOrdQty]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [ClassID]           CHAR (6)      DEFAULT (' ') NOT NULL,
    [COGSAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [COGSSub]           CHAR (24)     DEFAULT (' ') NOT NULL,
    [Color]             CHAR (20)     DEFAULT (' ') NOT NULL,
    [CountStatus]       CHAR (1)      DEFAULT ('A') NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [CuryListPrice]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryMinPrice]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CustomFtr]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [CycleID]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [Descr]             CHAR (60)     DEFAULT (' ') NOT NULL,
    [DfltPickLoc]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltPOUnit]        CHAR (6)      DEFAULT (' ') NOT NULL,
    [DfltSalesAcct]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltSalesSub]      CHAR (24)     DEFAULT (' ') NOT NULL,
    [DfltShpnotInvAcct] CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltShpnotInvSub]  CHAR (24)     DEFAULT (' ') NOT NULL,
    [DfltSite]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltSOUnit]        CHAR (6)      DEFAULT (' ') NOT NULL,
    [DfltWhseLoc]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [DirStdCost]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DiscAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [DiscPrc]           CHAR (1)      DEFAULT (' ') NOT NULL,
    [DiscSub]           CHAR (31)     DEFAULT (' ') NOT NULL,
    [EOQ]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ExplInvoice]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [ExplOrder]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [ExplPackSlip]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [ExplPickList]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [ExplShipping]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [FOvhStdCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [FrtAcct]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [FrtSub]            CHAR (24)     DEFAULT (' ') NOT NULL,
    [GLClassID]         CHAR (4)      DEFAULT (' ') NOT NULL,
    [InvtAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [InvtID]            CHAR (30)     DEFAULT (' ') NOT NULL,
    [InvtSub]           CHAR (24)     DEFAULT (' ') NOT NULL,
    [InvtType]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRCalcPolicy]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRDaysSupply]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRDemandID]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [IRFutureDate]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [IRFuturePolicy]    CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRLeadTimeID]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [IRLinePtQty]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRMinOnHand]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRModelInvtID]     CHAR (30)     DEFAULT (' ') NOT NULL,
    [IRRCycDays]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonEndDay]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonEndMon]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonStrtDay]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonStrtMon]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRServiceLevel]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkDays]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkPct]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkPolicy]   CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRSourceCode]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRTargetOrdMethod] CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRTargetOrdReq]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRTransferSiteID]  CHAR (10)     DEFAULT (' ') NOT NULL,
    [ItemCommClassID]   CHAR (10)     DEFAULT (' ') NOT NULL,
    [Kit]               SMALLINT      DEFAULT ((0)) NOT NULL,
    [LastBookQty]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastCost]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastCountDate]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LastSiteID]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [LastStdCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastVarAmt]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastVarPct]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastVarQty]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LCVarianceAcct]    CHAR (10)     DEFAULT (' ') NOT NULL,
    [LCVarianceSub]     CHAR (24)     DEFAULT (' ') NOT NULL,
    [LeadTime]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LinkSpecId]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [LotSerFxdLen]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [LotSerFxdTyp]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [LotSerFxdVal]      CHAR (12)     DEFAULT (' ') NOT NULL,
    [LotSerIssMthd]     CHAR (1)      DEFAULT (' ') NOT NULL,
    [LotSerNumLen]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [LotSerNumVal]      CHAR (25)     DEFAULT (' ') NOT NULL,
    [LotSerTrack]       CHAR (2)      DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [MaterialType]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [MaxOnHand]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [MfgClassID]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [MfgLeadTime]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [MinGrossProfit]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [MoveClass]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [MSDS]              CHAR (24)     DEFAULT (' ') NOT NULL,
    [NoteID]            INT           DEFAULT ((0)) NOT NULL,
    [Pack]              CHAR (6)      DEFAULT (' ') NOT NULL,
    [PDirStdCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PerNbr]            CHAR (6)      DEFAULT (' ') NOT NULL,
    [PFOvhStdCost]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PPVAcct]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [PPVSub]            CHAR (24)     DEFAULT (' ') NOT NULL,
    [PriceClassID]      CHAR (6)      DEFAULT (' ') NOT NULL,
    [ProdMgrID]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [ProductionUnit]    CHAR (6)      DEFAULT (' ') NOT NULL,
    [PStdCost]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PStdCostDate]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [PVOvhStdCost]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReordPt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReOrdPtCalc]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReordQty]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReOrdQtyCalc]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReplMthd]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [RollupCost]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [RollupPrice]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [RvsdPrc]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [S4Future01]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future13]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [SafetyStk]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SafetyStkCalc]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [Selected]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [SerAssign]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [Service]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [ShelfLife]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [Size]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [Source]            CHAR (1)      DEFAULT (' ') NOT NULL,
    [Status]            CHAR (1)      DEFAULT (' ') NOT NULL,
    [StdCost]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StdCostDate]       SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [StkBasePrc]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StkItem]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [StkRvsdPrc]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StkTaxBasisPrc]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StkUnit]           CHAR (6)      DEFAULT (' ') NOT NULL,
    [StkVol]            FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StkWt]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [StkWtUnit]         CHAR (6)      DEFAULT (' ') NOT NULL,
    [Style]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [Supplr1]           CHAR (15)     DEFAULT (' ') NOT NULL,
    [Supplr2]           CHAR (15)     DEFAULT (' ') NOT NULL,
    [SupplrItem1]       CHAR (20)     DEFAULT (' ') NOT NULL,
    [SupplrItem2]       CHAR (20)     DEFAULT (' ') NOT NULL,
    [TaskID]            CHAR (32)     DEFAULT (' ') NOT NULL,
    [TaxCat]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [TranStatusCode]    CHAR (2)      DEFAULT (' ') NOT NULL,
    [Turns]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [UPCCode]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [UsageRate]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User1]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [ValMthd]           CHAR (1)      DEFAULT (' ') NOT NULL,
    [VOvhStdCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [WarrantyDays]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [YTDUsage]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [Inventory0] PRIMARY KEY CLUSTERED ([InvtID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Inventory1]
    ON [dbo].[Inventory]([ClassID] ASC, [InvtID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Inventory2]
    ON [dbo].[Inventory]([Descr] ASC, [InvtID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Inventory3]
    ON [dbo].[Inventory]([TranStatusCode] ASC, [InvtID] ASC) WITH (FILLFACTOR = 90);

