CREATE TABLE [dbo].[cftPigGenderType] (
    [CF01]            CHAR (30)     NOT NULL,
    [CF02]            CHAR (30)     NOT NULL,
    [CF03]            CHAR (10)     NOT NULL,
    [CF04]            CHAR (10)     NOT NULL,
    [CF05]            SMALLDATETIME NOT NULL,
    [CF06]            SMALLDATETIME NOT NULL,
    [CF07]            INT           NOT NULL,
    [CF08]            INT           NOT NULL,
    [CF09]            SMALLINT      NOT NULL,
    [CF10]            SMALLINT      NOT NULL,
    [CF11]            FLOAT (53)    NOT NULL,
    [CF12]            FLOAT (53)    NOT NULL,
    [Crtd_Date]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [Description]     CHAR (30)     NOT NULL,
    [FeedCalcConstA]  FLOAT (53)    NOT NULL,
    [FeedCalcConstB]  FLOAT (53)    NOT NULL,
    [FeedCalcConstC]  FLOAT (53)    NOT NULL,
    [Lupd_Date]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]       CHAR (8)      NOT NULL,
    [Lupd_User]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [PigGenderTypeID] CHAR (6)      NOT NULL,
    [UseInPGFlag]     SMALLINT      NOT NULL,
    [tstamp]          ROWVERSION    NULL,
    CONSTRAINT [cftPigGenderType0] PRIMARY KEY CLUSTERED ([PigGenderTypeID] ASC) WITH (FILLFACTOR = 90)
);

