CREATE TABLE [dbo].[Terms] (
    [ApplyTo]       CHAR (1)      NOT NULL,
    [COD]           SMALLINT      NOT NULL,
    [CreditChk]     SMALLINT      NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [Cycle]         SMALLINT      NOT NULL,
    [Descr]         CHAR (30)     NOT NULL,
    [DiscIntrv]     SMALLINT      NOT NULL,
    [DiscPct]       FLOAT (53)    NOT NULL,
    [DiscType]      CHAR (1)      NOT NULL,
    [DueIntrv]      SMALLINT      NOT NULL,
    [DueType]       CHAR (1)      NOT NULL,
    [Frequency]     CHAR (1)      NOT NULL,
    [LUpd_DateTime] SMALLDATETIME NOT NULL,
    [LUpd_Prog]     CHAR (8)      NOT NULL,
    [LUpd_User]     CHAR (10)     NOT NULL,
    [NbrInstall]    SMALLINT      NOT NULL,
    [NoteId]        INT           NOT NULL,
    [Options]       CHAR (1)      NOT NULL,
    [S4Future01]    CHAR (30)     NOT NULL,
    [S4Future02]    CHAR (30)     NOT NULL,
    [S4Future03]    FLOAT (53)    NOT NULL,
    [S4Future04]    FLOAT (53)    NOT NULL,
    [S4Future05]    FLOAT (53)    NOT NULL,
    [S4Future06]    FLOAT (53)    NOT NULL,
    [S4Future07]    SMALLDATETIME NOT NULL,
    [S4Future08]    SMALLDATETIME NOT NULL,
    [S4Future09]    INT           NOT NULL,
    [S4Future10]    INT           NOT NULL,
    [S4Future11]    CHAR (10)     NOT NULL,
    [S4Future12]    CHAR (10)     NOT NULL,
    [TermsId]       CHAR (2)      NOT NULL,
    [TermsType]     CHAR (1)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         SMALLDATETIME NOT NULL,
    [tstamp]        ROWVERSION    NOT NULL,
    CONSTRAINT [Terms0] PRIMARY KEY CLUSTERED ([TermsId] ASC) WITH (FILLFACTOR = 90)
);

