CREATE TABLE [dbo].[cftPigProdPhase] (
    [CalcEstWgtFlag] SMALLINT      NOT NULL,
    [CF01]           CHAR (30)     NOT NULL,
    [CF02]           CHAR (30)     NOT NULL,
    [CF03]           CHAR (10)     NOT NULL,
    [CF04]           CHAR (10)     NOT NULL,
    [CF05]           SMALLDATETIME NOT NULL,
    [CF06]           SMALLDATETIME NOT NULL,
    [CF07]           INT           NOT NULL,
    [CF08]           INT           NOT NULL,
    [CF09]           SMALLINT      NOT NULL,
    [CF10]           SMALLINT      NOT NULL,
    [CF11]           FLOAT (53)    NOT NULL,
    [CF12]           FLOAT (53)    NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [DailyRate]      FLOAT (53)    NOT NULL,
    [EstDays]        SMALLINT      NOT NULL,
    [EstStartWt]     SMALLINT      NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [NoteID]         INT           NOT NULL,
    [PhaseDesc]      CHAR (30)     NOT NULL,
    [PigProdPhaseID] CHAR (3)      NOT NULL,
    [ProdType]       CHAR (3)      NOT NULL,
    [RatePeriod]     CHAR (6)      NOT NULL,
    [Status]         CHAR (1)      NOT NULL,
    [tstamp]         ROWVERSION    NULL,
    CONSTRAINT [cftPigProdPhase0] PRIMARY KEY CLUSTERED ([PigProdPhaseID] ASC) WITH (FILLFACTOR = 90)
);

