CREATE TABLE [dbo].[cftPGSetup] (
    [CF01]                CHAR (30)     NOT NULL,
    [CF02]                CHAR (30)     NOT NULL,
    [CF03]                CHAR (10)     NOT NULL,
    [CF04]                CHAR (10)     NOT NULL,
    [CF05]                SMALLDATETIME NOT NULL,
    [CF06]                SMALLDATETIME NOT NULL,
    [CF07]                INT           NOT NULL,
    [CF08]                INT           NOT NULL,
    [CF09]                SMALLINT      NOT NULL,
    [CF10]                SMALLINT      NOT NULL,
    [CF11]                FLOAT (53)    NOT NULL,
    [CF12]                FLOAT (53)    NOT NULL,
    [CommDivision]        CHAR (2)      NOT NULL,
    [ContractLocation]    CHAR (4)      NOT NULL,
    [Crtd_DateTime]       SMALLDATETIME NOT NULL,
    [Crtd_Prog]           CHAR (8)      NOT NULL,
    [Crtd_User]           CHAR (10)     NOT NULL,
    [FinishDept]          CHAR (2)      NOT NULL,
    [InvDestSub]          CHAR (2)      NOT NULL,
    [InvDestTType]        CHAR (2)      NOT NULL,
    [InvSrcSub]           CHAR (2)      NOT NULL,
    [InvSrcTType]         CHAR (2)      NOT NULL,
    [LastBatNbr]          CHAR (10)     NOT NULL,
    [LastRefNbr]          CHAR (10)     NOT NULL,
    [LastTaskNbr]         CHAR (10)     NOT NULL,
    [Lupd_DateTime]       SMALLDATETIME NOT NULL,
    [Lupd_Prog]           CHAR (8)      NOT NULL,
    [Lupd_User]           CHAR (10)     NOT NULL,
    [MixedPodPctLimit]    FLOAT (53)    NOT NULL,
    [MultDivision]        CHAR (2)      NOT NULL,
    [NoteID]              INT           NOT NULL,
    [NurseryDept]         CHAR (2)      NOT NULL,
    [PGInvLimit]          SMALLINT      NOT NULL,
    [PigPurchPrefix]      CHAR (2)      NOT NULL,
    [ProjectPrefix]       CHAR (2)      NOT NULL,
    [SetupID]             SMALLINT      NOT NULL,
    [SiteCostAcct]        CHAR (16)     NOT NULL,
    [SiteCostTask]        CHAR (32)     NOT NULL,
    [TaskPrefix]          CHAR (2)      NOT NULL,
    [TransferQtyPctLimit] FLOAT (53)    NOT NULL,
    [WeanFinishDept]      CHAR (2)      NOT NULL,
    [WgtPctVarLimit]      FLOAT (53)    NOT NULL,
    [tstamp]              ROWVERSION    NULL,
    CONSTRAINT [cftPGSetup0] PRIMARY KEY CLUSTERED ([SetupID] ASC) WITH (FILLFACTOR = 90)
);

