CREATE TABLE [dbo].[cftPigProdPod] (
    [BarrowPodID]    CHAR (3)      NOT NULL,
    [CF01]           CHAR (30)     NOT NULL,
    [CF02]           CHAR (30)     NOT NULL,
    [CF03]           CHAR (10)     NOT NULL,
    [CF04]           CHAR (10)     NOT NULL,
    [CF05]           SMALLDATETIME NOT NULL,
    [CF06]           SMALLDATETIME NOT NULL,
    [CF07]           INT           NOT NULL,
    [CF08]           INT           NOT NULL,
    [CF09]           SMALLINT      NOT NULL,
    [CF10]           SMALLINT      NOT NULL,
    [CF11]           FLOAT (53)    NOT NULL,
    [CF12]           FLOAT (53)    NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [Description]    CHAR (30)     NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [MixedPodID]     CHAR (3)      NOT NULL,
    [NoteID]         INT           NOT NULL,
    [NurWgtFactorA]  FLOAT (53)    NOT NULL,
    [NurWgtFactorB]  FLOAT (53)    NOT NULL,
    [PodID]          CHAR (3)      NOT NULL,
    [WeanEffDate]    CHAR (6)      NOT NULL,
    [WeanStartValue] FLOAT (53)    NOT NULL,
    [tstamp]         ROWVERSION    NULL,
    CONSTRAINT [cftPigProdPod0] PRIMARY KEY CLUSTERED ([PodID] ASC) WITH (FILLFACTOR = 90)
);

