CREATE TABLE [dbo].[WrkMarketTotals] (
    [PackerContactID] VARCHAR (6)   NULL,
    [Day0Date]        SMALLDATETIME NULL,
    [DayTotalQty]     INT           NULL,
    [DayEstLbs]       INT           NULL,
    [DayActLbs]       INT           NULL,
    [DayEstLbsCount]  INT           NULL,
    [DayActLbsCount]  INT           NULL,
    [Day0TotalQty]    INT           NULL,
    [Day0EstLbs]      INT           NULL,
    [Day0ActLbs]      INT           NULL,
    [Day0EstLbsCount] INT           NULL,
    [Day0ActLbsCount] INT           NULL,
    [Day1Date]        SMALLDATETIME NULL,
    [Day1TotalQty]    INT           NULL,
    [Day1EstLbs]      INT           NULL,
    [Day1ActLbs]      INT           NULL,
    [Day1EstLbsCount] INT           NULL,
    [Day1ActLbsCount] INT           NULL,
    [Day2Date]        SMALLDATETIME NULL,
    [Day2TotalQty]    INT           NULL,
    [Day2EstLbs]      INT           NULL,
    [Day2ActLbs]      INT           NULL,
    [Day2EstLbsCount] INT           NULL,
    [Day2ActLbsCount] INT           NULL,
    [Day3Date]        SMALLDATETIME NULL,
    [Day3TotalQty]    INT           NULL,
    [Day3EstLbs]      INT           NULL,
    [Day3ActLbs]      INT           NULL,
    [Day3EstLbsCount] INT           NULL,
    [Day3ActLbsCount] INT           NULL,
    [Day4Date]        SMALLDATETIME NULL,
    [Day4TotalQty]    INT           NULL,
    [Day4EstLbs]      INT           NULL,
    [Day4ActLbs]      INT           NULL,
    [Day4EstLbsCount] INT           NULL,
    [Day4ActLbsCount] INT           NULL,
    [Day5Date]        SMALLDATETIME NULL,
    [Day5TotalQty]    INT           NULL,
    [Day5EstLbs]      INT           NULL,
    [Day5ActLbs]      INT           NULL,
    [Day5EstLbsCount] INT           NULL,
    [Day5ActLbsCount] INT           NULL,
    [Day6Date]        SMALLDATETIME NULL,
    [Day6TotalQty]    INT           NULL,
    [Day6EstLbs]      INT           NULL,
    [Day6ActLbs]      INT           NULL,
    [Day6EstLbsCount] INT           NULL,
    [Day6ActLbsCount] INT           NULL,
    [RI_ID]           SMALLINT      NOT NULL
);

