CREATE TABLE [dbo].[PurchOrd] (
    [AckDateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [ASID]            INT           DEFAULT ((0)) NOT NULL,
    [BatNbr]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [BillShipAddr]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [BlktExprDate]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [BlktPONbr]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [Buyer]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [BuyerEmail]      CHAR (80)     DEFAULT (' ') NOT NULL,
    [CertCompl]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [ConfirmTo]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [CpnyID]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]       CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [CurrentNbr]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [CuryEffDate]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [CuryFreight]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryID]          CHAR (4)      DEFAULT (' ') NOT NULL,
    [CuryMultDiv]     CHAR (1)      DEFAULT (' ') NOT NULL,
    [CuryPOAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryPOItemTotal] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRate]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryRateType]    CHAR (6)      DEFAULT (' ') NOT NULL,
    [CuryRcptTotAmt]  FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTaxTot00]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTaxTot01]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTaxTot02]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTaxTot03]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTxblTot00]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTxblTot01]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTxblTot02]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTxblTot03]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [EDI]             SMALLINT      DEFAULT ((0)) NOT NULL,
    [FOB]             CHAR (15)     DEFAULT (' ') NOT NULL,
    [Freight]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [LastRcptDate]    SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LineCntr]        INT           DEFAULT ((0)) NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]       CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [NoteID]          INT           DEFAULT ((0)) NOT NULL,
    [OpenPO]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [PC_Status]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [PerClosed]       CHAR (6)      DEFAULT (' ') NOT NULL,
    [PerEnt]          CHAR (6)      DEFAULT (' ') NOT NULL,
    [POAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PODate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [POItemTotal]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [PONbr]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [POType]          CHAR (2)      DEFAULT (' ') NOT NULL,
    [ProjectID]       CHAR (16)     DEFAULT (' ') NOT NULL,
    [PrtBatNbr]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [PrtFlg]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [RcptStage]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [RcptTotAmt]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ReqNbr]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future01]      CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]      CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]      INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]      INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [ServiceCallID]   CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipAddr1]       CHAR (60)     DEFAULT (' ') NOT NULL,
    [ShipAddr2]       CHAR (60)     DEFAULT (' ') NOT NULL,
    [ShipAddrID]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipAttn]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [ShipCity]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [ShipCountry]     CHAR (3)      DEFAULT (' ') NOT NULL,
    [ShipCustID]      CHAR (15)     DEFAULT (' ') NOT NULL,
    [ShipEmail]       CHAR (80)     DEFAULT (' ') NOT NULL,
    [ShipFax]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [ShipName]        CHAR (60)     DEFAULT (' ') NOT NULL,
    [ShipPhone]       CHAR (30)     DEFAULT (' ') NOT NULL,
    [ShipSiteID]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipState]       CHAR (3)      DEFAULT (' ') NOT NULL,
    [ShiptoID]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShiptoType]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [ShipVendAddrID]  CHAR (10)     DEFAULT (' ') NOT NULL,
    [ShipVendID]      CHAR (15)     DEFAULT (' ') NOT NULL,
    [ShipVia]         CHAR (15)     DEFAULT (' ') NOT NULL,
    [ShipZip]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [Status]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [TaxCntr00]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [TaxCntr01]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [TaxCntr02]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [TaxCntr03]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [TaxID00]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [TaxID01]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [TaxID02]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [TaxID03]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [TaxTot00]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TaxTot01]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TaxTot02]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TaxTot03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [Terms]           CHAR (2)      DEFAULT (' ') NOT NULL,
    [TxblTot00]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TxblTot01]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TxblTot02]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TxblTot03]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User1]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]           CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]           SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VendAddr1]       CHAR (60)     DEFAULT (' ') NOT NULL,
    [VendAddr2]       CHAR (60)     DEFAULT (' ') NOT NULL,
    [VendAddrID]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [VendAttn]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [VendCity]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [VendCountry]     CHAR (3)      DEFAULT (' ') NOT NULL,
    [VendEmail]       CHAR (80)     DEFAULT (' ') NOT NULL,
    [VendFax]         CHAR (30)     DEFAULT (' ') NOT NULL,
    [VendID]          CHAR (15)     DEFAULT (' ') NOT NULL,
    [VendName]        CHAR (60)     DEFAULT (' ') NOT NULL,
    [VendPhone]       CHAR (30)     DEFAULT (' ') NOT NULL,
    [VendState]       CHAR (3)      DEFAULT (' ') NOT NULL,
    [VendZip]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [VouchStage]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [WSID]            INT           DEFAULT ((0)) NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL,
    CONSTRAINT [PurchOrd0] PRIMARY KEY CLUSTERED ([PONbr] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [PurchOrd1]
    ON [dbo].[PurchOrd]([BatNbr] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [PurchOrd2]
    ON [dbo].[PurchOrd]([VendID] ASC, [PONbr] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [PurchOrd3]
    ON [dbo].[PurchOrd]([PrtBatNbr] ASC, [VendID] ASC, [PONbr] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [PurchOrd4]
    ON [dbo].[PurchOrd]([POType] ASC, [Status] ASC) WITH (FILLFACTOR = 90);

