CREATE TABLE [dbo].[POTran] (
    [Acct]              CHAR (10)     DEFAULT (' ') NOT NULL,
    [AcctDist]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [AddlCost]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AddlCostPct]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AddlCostVouch]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [AlternateID]       CHAR (30)     DEFAULT (' ') NOT NULL,
    [AltIDType]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [APLineID]          SMALLINT      DEFAULT ((0)) NOT NULL,
    [APLineRef]         CHAR (5)      DEFAULT (' ') NOT NULL,
    [BatNbr]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [BMICuryID]         CHAR (4)      DEFAULT (' ') NOT NULL,
    [BMIEffDate]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [BMIExtCost]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIMultDiv]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [BMIRate]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIRtTp]           CHAR (6)      DEFAULT (' ') NOT NULL,
    [BMITranAmt]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIUnitCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BMIUnitPrice]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [BOMLineRef]        CHAR (5)      DEFAULT (' ') NOT NULL,
    [BOMSequence]       SMALLINT      DEFAULT ((0)) NOT NULL,
    [CnvFact]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CostVouched]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CpnyID]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [CuryAddlCost]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryAddlCostVouch] FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryCostVouched]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryExtCost]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryID]            CHAR (4)      DEFAULT (' ') NOT NULL,
    [CuryMultDiv]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [CuryRate]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryTranAmt]       FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [CuryUnitCost]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [DrCr]              CHAR (1)      DEFAULT (' ') NOT NULL,
    [ExtCost]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [ExtWeight]         FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [FlatRateLineNbr]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [InvtID]            CHAR (30)     DEFAULT (' ') NOT NULL,
    [JrnlType]          CHAR (3)      DEFAULT (' ') NOT NULL,
    [Labor_Class_Cd]    CHAR (4)      DEFAULT (' ') NOT NULL,
    [LineID]            INT           DEFAULT ((0)) NOT NULL,
    [LineNbr]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [LineRef]           CHAR (5)      DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [NoteID]            INT           DEFAULT ((0)) NOT NULL,
    [OrigRcptDate]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [OrigRcptNbr]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [OrigRetRcptNbr]    CHAR (10)     DEFAULT (' ') NOT NULL,
    [PC_Flag]           CHAR (1)      DEFAULT (' ') NOT NULL,
    [PC_ID]             CHAR (20)     DEFAULT (' ') NOT NULL,
    [PC_Status]         CHAR (1)      DEFAULT (' ') NOT NULL,
    [PerEnt]            CHAR (6)      DEFAULT (' ') NOT NULL,
    [PerPost]           CHAR (6)      DEFAULT (' ') NOT NULL,
    [POLineID]          INT           DEFAULT ((0)) NOT NULL,
    [POLineNbr]         SMALLINT      DEFAULT ((0)) NOT NULL,
    [POLIneRef]         CHAR (5)      DEFAULT (' ') NOT NULL,
    [PONbr]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [POOriginal]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [ProjectID]         CHAR (16)     DEFAULT (' ') NOT NULL,
    [PurchaseType]      CHAR (2)      DEFAULT (' ') NOT NULL,
    [Qty]               FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [QtyVouched]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptConvFact]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptDate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [RcptLineRefOrig]   CHAR (5)      DEFAULT (' ') NOT NULL,
    [RcptMultDiv]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [RcptNbr]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [RcptNbrOrig]       CHAR (10)     DEFAULT (' ') NOT NULL,
    [RcptQty]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [RcptUnitDescr]     CHAR (6)      DEFAULT (' ') NOT NULL,
    [ReasonCd]          CHAR (6)      DEFAULT (' ') NOT NULL,
    [Refnbr]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future01]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [ServiceCallID]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [SiteID]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [SOLineID]          INT           DEFAULT ((0)) NOT NULL,
    [SOLineRef]         CHAR (5)      DEFAULT (' ') NOT NULL,
    [SOOrdNbr]          CHAR (15)     DEFAULT (' ') NOT NULL,
    [SOTypeID]          CHAR (4)      DEFAULT (' ') NOT NULL,
    [SpecificCostID]    CHAR (25)     DEFAULT (' ') NOT NULL,
    [StepNbr]           SMALLINT      DEFAULT ((0)) NOT NULL,
    [Sub]               CHAR (24)     DEFAULT (' ') NOT NULL,
    [SvcContractID]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [SvcLineNbr]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [TaskID]            CHAR (32)     DEFAULT (' ') NOT NULL,
    [TaxCat]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [TaxIDDflt]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [TranAmt]           FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [TranDate]          SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [TranDesc]          CHAR (60)     DEFAULT (' ') NOT NULL,
    [TranType]          CHAR (2)      DEFAULT (' ') NOT NULL,
    [UnitCost]          FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [UnitDescr]         CHAR (6)      DEFAULT (' ') NOT NULL,
    [UnitMultDiv]       CHAR (1)      DEFAULT (' ') NOT NULL,
    [UnitWeight]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User1]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VendId]            CHAR (15)     DEFAULT (' ') NOT NULL,
    [VouchStage]        CHAR (1)      DEFAULT (' ') NOT NULL,
    [WhseLoc]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [WIP_COGS_Acct]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [WIP_COGS_Sub]      CHAR (24)     DEFAULT (' ') NOT NULL,
    [WOBomRef]          CHAR (5)      DEFAULT (' ') NOT NULL,
    [WOCostType]        CHAR (2)      DEFAULT (' ') NOT NULL,
    [WONbr]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [WOStepNbr]         CHAR (5)      DEFAULT (' ') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [POTran0] PRIMARY KEY CLUSTERED ([RcptNbr] ASC, [LineRef] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [POTran4]
    ON [dbo].[POTran]([InvtID] ASC, [SiteID] ASC, [PurchaseType] ASC, [TranType] ASC, [WhseLoc] ASC, [LineRef] ASC, [RcptNbr] ASC, [CnvFact] ASC, [UnitMultDiv] ASC, [Qty] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [potran_stran]
    ON [dbo].[POTran]([PerPost] ASC, [PC_Status] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [POTran1]
    ON [dbo].[POTran]([PONbr] ASC, [POLineNbr] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [POTran2]
    ON [dbo].[POTran]([ReasonCd] ASC, [InvtID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [POTran3]
    ON [dbo].[POTran]([RcptNbr] ASC, [LineRef] ASC, [LineNbr] ASC) WITH (FILLFACTOR = 90);

