CREATE TABLE [dbo].[Site] (
    [Addr1]             CHAR (60)     DEFAULT (' ') NOT NULL,
    [Addr2]             CHAR (60)     DEFAULT (' ') NOT NULL,
    [AlwaysShip]        SMALLINT      DEFAULT ((0)) NOT NULL,
    [Attn]              CHAR (30)     DEFAULT (' ') NOT NULL,
    [City]              CHAR (30)     DEFAULT (' ') NOT NULL,
    [COGSAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [COGSSub]           CHAR (31)     DEFAULT (' ') NOT NULL,
    [Country]           CHAR (3)      DEFAULT (' ') NOT NULL,
    [CpnyID]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME DEFAULT (rtrim(CONVERT([varchar](30),CONVERT([smalldatetime],getdate(),(0)),(0)))) NOT NULL,
    [Crtd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [Crtd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltInvtAcct]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltInvtSub]       CHAR (31)     DEFAULT (' ') NOT NULL,
    [DfltRepairBin]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [DfltVendorBin]     CHAR (10)     DEFAULT (' ') NOT NULL,
    [DicsAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [DiscSub]           CHAR (31)     DEFAULT (' ') NOT NULL,
    [Fax]               CHAR (30)     DEFAULT (' ') NOT NULL,
    [FrtAcct]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [FrtSub]            CHAR (31)     DEFAULT (' ') NOT NULL,
    [GeoCode]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [IRCalcPolicy]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRDaysSupply]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRDemandID]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [IRFutureDate]      SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [IRFuturePolicy]    CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRLeadTimeID]      CHAR (10)     DEFAULT (' ') NOT NULL,
    [IRPrimaryVendID]   CHAR (15)     DEFAULT (' ') NOT NULL,
    [IRSeasonEndDay]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonEndMon]    SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonStrtDay]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRSeasonStrtMon]   SMALLINT      DEFAULT ((0)) NOT NULL,
    [IRServiceLevel]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkDays]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkPct]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRSftyStkPolicy]   CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRSourceCode]      CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRTargetOrdMethod] CHAR (1)      DEFAULT (' ') NOT NULL,
    [IRTargetOrdReq]    FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [IRTransferSiteID]  CHAR (10)     DEFAULT (' ') NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [LUpd_Prog]         CHAR (8)      DEFAULT (' ') NOT NULL,
    [LUpd_User]         CHAR (10)     DEFAULT (' ') NOT NULL,
    [MiscAcct]          CHAR (10)     DEFAULT (' ') NOT NULL,
    [MiscSub]           CHAR (31)     DEFAULT (' ') NOT NULL,
    [Name]              CHAR (30)     DEFAULT (' ') NOT NULL,
    [NoteID]            INT           DEFAULT ((0)) NOT NULL,
    [Phone]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [ReplMthd]          CHAR (1)      DEFAULT (' ') NOT NULL,
    [REPWhseLoc]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [RTVWhseLoc]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future01]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future02]        CHAR (30)     DEFAULT (' ') NOT NULL,
    [S4Future03]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future04]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future05]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future06]        FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [S4Future07]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future08]        SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [S4Future09]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future10]        INT           DEFAULT ((0)) NOT NULL,
    [S4Future11]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [S4Future12]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [Salut]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [SiteId]            CHAR (10)     DEFAULT (' ') NOT NULL,
    [SlsAcct]           CHAR (10)     DEFAULT (' ') NOT NULL,
    [SlsSub]            CHAR (31)     DEFAULT (' ') NOT NULL,
    [State]             CHAR (3)      DEFAULT (' ') NOT NULL,
    [Status]            CHAR (1)      DEFAULT (' ') NOT NULL,
    [User1]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User2]             CHAR (30)     DEFAULT (' ') NOT NULL,
    [User3]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User4]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [User5]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User6]             CHAR (10)     DEFAULT (' ') NOT NULL,
    [User7]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [User8]             SMALLDATETIME DEFAULT ('01/01/1900') NOT NULL,
    [VisibleForWC]      SMALLINT      DEFAULT ((0)) NOT NULL,
    [Zip]               CHAR (10)     DEFAULT (' ') NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL,
    CONSTRAINT [Site0] PRIMARY KEY CLUSTERED ([SiteId] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [Site1]
    ON [dbo].[Site]([CpnyID] ASC, [SiteId] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [Site2]
    ON [dbo].[Site]([NoteID] ASC) WITH (FILLFACTOR = 90);

