CREATE TABLE [dbo].[cftPigPurchase] (
    [BegDelvDate]    SMALLDATETIME NOT NULL,
    [BasePrice]      FLOAT (53)    NOT NULL,
    [BaseWeight]     FLOAT (53)    NOT NULL,
    [ContactID]      CHAR (6)      NOT NULL,
    [CpnyId]         CHAR (10)     NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [DaysDue]        SMALLINT      NOT NULL,
    [DiffPoundsDown] FLOAT (53)    NOT NULL,
    [DiffPriceDown]  FLOAT (53)    NOT NULL,
    [DiffPoundsUp]   FLOAT (53)    NOT NULL,
    [DiffPriceUp]    FLOAT (53)    NOT NULL,
    [DOAPrice]       FLOAT (53)    NOT NULL,
    [EndDelvDate]    SMALLDATETIME NOT NULL,
    [JunkPrice]      FLOAT (53)    NOT NULL,
    [Lupd_DateTime]  SMALLDATETIME NOT NULL,
    [Lupd_Prog]      CHAR (8)      NOT NULL,
    [Lupd_User]      CHAR (10)     NOT NULL,
    [NoteID]         INT           NOT NULL,
    [PodID]          CHAR (3)      NOT NULL,
    [PPID]           CHAR (10)     NOT NULL,
    [ProfitShare]    SMALLINT      NOT NULL,
    [PurchaseDate]   SMALLDATETIME NOT NULL,
    [PurchaseTypeID] CHAR (1)      NOT NULL,
    [SubPrice]       FLOAT (53)    NOT NULL,
    [TranTypeID]     CHAR (2)      NOT NULL,
    [tstamp]         ROWVERSION    NULL,
    CONSTRAINT [cftPigPurchase0] PRIMARY KEY CLUSTERED ([PPID] ASC) WITH (FILLFACTOR = 90)
);

