CREATE TABLE [dbo].[Batch2] (
    [Acct]           CHAR (10)     NOT NULL,
    [AutoRev]        SMALLINT      NOT NULL,
    [AutoRevCopy]    SMALLINT      NOT NULL,
    [BalanceType]    CHAR (1)      NOT NULL,
    [BankAcct]       CHAR (10)     NOT NULL,
    [BankSub]        CHAR (24)     NOT NULL,
    [BaseCuryID]     CHAR (4)      NOT NULL,
    [BatNbr]         CHAR (10)     NOT NULL,
    [BatType]        CHAR (1)      NOT NULL,
    [clearamt]       FLOAT (53)    NOT NULL,
    [Cleared]        SMALLINT      NOT NULL,
    [CpnyID]         CHAR (10)     NOT NULL,
    [Crtd_DateTime]  SMALLDATETIME NOT NULL,
    [Crtd_Prog]      CHAR (8)      NOT NULL,
    [Crtd_User]      CHAR (10)     NOT NULL,
    [CrTot]          FLOAT (53)    NOT NULL,
    [CtrlTot]        FLOAT (53)    NOT NULL,
    [CuryCrTot]      FLOAT (53)    NOT NULL,
    [CuryCtrlTot]    FLOAT (53)    NOT NULL,
    [CuryDepositAmt] FLOAT (53)    NOT NULL,
    [CuryDrTot]      FLOAT (53)    NOT NULL,
    [CuryEffDate]    SMALLDATETIME NOT NULL,
    [CuryId]         CHAR (4)      NOT NULL,
    [CuryMultDiv]    CHAR (1)      NOT NULL,
    [CuryRate]       FLOAT (53)    NOT NULL,
    [CuryRateType]   CHAR (6)      NOT NULL,
    [Cycle]          SMALLINT      NOT NULL,
    [DateClr]        SMALLDATETIME NOT NULL,
    [DateEnt]        SMALLDATETIME NOT NULL,
    [DepositAmt]     FLOAT (53)    NOT NULL,
    [Descr]          CHAR (30)     NOT NULL,
    [DrTot]          FLOAT (53)    NOT NULL,
    [EditScrnNbr]    CHAR (5)      NOT NULL,
    [GLPostOpt]      CHAR (1)      NOT NULL,
    [JrnlType]       CHAR (3)      NOT NULL,
    [LedgerID]       CHAR (10)     NOT NULL,
    [LUpd_DateTime]  SMALLDATETIME NOT NULL,
    [LUpd_Prog]      CHAR (8)      NOT NULL,
    [LUpd_User]      CHAR (10)     NOT NULL,
    [Module]         CHAR (2)      NOT NULL,
    [NbrCycle]       SMALLINT      NOT NULL,
    [NoteID]         INT           NOT NULL,
    [OrigBatNbr]     CHAR (10)     NOT NULL,
    [OrigCpnyID]     CHAR (10)     NOT NULL,
    [OrigScrnNbr]    CHAR (5)      NOT NULL,
    [PerEnt]         CHAR (6)      NOT NULL,
    [PerPost]        CHAR (6)      NOT NULL,
    [Rlsed]          SMALLINT      NOT NULL,
    [S4Future01]     CHAR (30)     NOT NULL,
    [S4Future02]     CHAR (30)     NOT NULL,
    [S4Future03]     FLOAT (53)    NOT NULL,
    [S4Future04]     FLOAT (53)    NOT NULL,
    [S4Future05]     FLOAT (53)    NOT NULL,
    [S4Future06]     FLOAT (53)    NOT NULL,
    [S4Future07]     SMALLDATETIME NOT NULL,
    [S4Future08]     SMALLDATETIME NOT NULL,
    [S4Future09]     INT           NOT NULL,
    [S4Future10]     INT           NOT NULL,
    [S4Future11]     CHAR (10)     NOT NULL,
    [S4Future12]     CHAR (10)     NOT NULL,
    [Status]         CHAR (1)      NOT NULL,
    [Sub]            CHAR (24)     NOT NULL,
    [User1]          CHAR (30)     NOT NULL,
    [User2]          CHAR (30)     NOT NULL,
    [User3]          FLOAT (53)    NOT NULL,
    [User4]          FLOAT (53)    NOT NULL,
    [User5]          CHAR (10)     NOT NULL,
    [User6]          CHAR (10)     NOT NULL,
    [User7]          SMALLDATETIME NOT NULL,
    [User8]          SMALLDATETIME NOT NULL,
    [VOBatNbrForPP]  CHAR (10)     NOT NULL,
    [tstamp]         ROWVERSION    NOT NULL
);

