CREATE TABLE [dbo].[cftTMInvcDet] (
    [BatNbr]        CHAR (10)     NOT NULL,
    [BinNbr]        CHAR (6)      NOT NULL,
    [CnvFactOrd]    FLOAT (53)    NOT NULL,
    [Crtd_DateTime] SMALLDATETIME NOT NULL,
    [Crtd_Prog]     CHAR (8)      NOT NULL,
    [Crtd_User]     CHAR (10)     NOT NULL,
    [DateSched]     SMALLDATETIME NOT NULL,
    [InvcNbr]       CHAR (10)     NOT NULL,
    [InvtIdDelv]    CHAR (30)     NOT NULL,
    [InvtIdOrd]     CHAR (30)     NOT NULL,
    [Lupd_DateTime] SMALLDATETIME NOT NULL,
    [Lupd_Prog]     CHAR (8)      NOT NULL,
    [Lupd_User]     CHAR (10)     NOT NULL,
    [OrdNbr]        CHAR (10)     NOT NULL,
    [QtyDelv]       FLOAT (53)    NOT NULL,
    [QtyOrd]        FLOAT (53)    NOT NULL,
    [RefNbr]        CHAR (10)     NOT NULL,
    [Selected]      SMALLINT      NOT NULL,
    [UOMOrd]        CHAR (6)      NOT NULL,
    [User1]         CHAR (30)     NOT NULL,
    [User2]         CHAR (30)     NOT NULL,
    [User3]         FLOAT (53)    NOT NULL,
    [User4]         FLOAT (53)    NOT NULL,
    [User5]         CHAR (10)     NOT NULL,
    [User6]         CHAR (10)     NOT NULL,
    [User7]         SMALLDATETIME NOT NULL,
    [User8]         INT           NOT NULL,
    [tstamp]        ROWVERSION    NULL
);

