CREATE TABLE [dbo].[POReceipt] (
    [APRefno]           CHAR (10)     NOT NULL,
    [BatNbr]            CHAR (10)     NOT NULL,
    [CpnyID]            CHAR (10)     NOT NULL,
    [CreateAD]          SMALLINT      NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [CuryEffDate]       SMALLDATETIME NOT NULL,
    [CuryFreight]       FLOAT (53)    NOT NULL,
    [CuryID]            CHAR (4)      NOT NULL,
    [CuryMultDiv]       CHAR (1)      NOT NULL,
    [CuryRate]          FLOAT (53)    NOT NULL,
    [CuryRateType]      CHAR (6)      NOT NULL,
    [CuryRcptAmt]       FLOAT (53)    NOT NULL,
    [CuryRcptAmtTot]    FLOAT (53)    NOT NULL,
    [CuryRcptCtrlAmt]   FLOAT (53)    NOT NULL,
    [CuryRcptItemTotal] FLOAT (53)    NOT NULL,
    [DfltFromPO]        CHAR (1)      NOT NULL,
    [ExcludeFreight]    CHAR (1)      NOT NULL,
    [Freight]           FLOAT (53)    NOT NULL,
    [InBal]             SMALLINT      NOT NULL,
    [LineCntr]          SMALLINT      NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME NOT NULL,
    [LUpd_Prog]         CHAR (8)      NOT NULL,
    [LUpd_User]         CHAR (10)     NOT NULL,
    [NoteID]            INT           NOT NULL,
    [OpenDoc]           SMALLINT      NOT NULL,
    [PC_Status]         CHAR (1)      NOT NULL,
    [PerClosed]         CHAR (6)      NOT NULL,
    [PerEnt]            CHAR (6)      NOT NULL,
    [PONbr]             CHAR (10)     NOT NULL,
    [ProjectID]         CHAR (16)     NOT NULL,
    [RcptAmt]           FLOAT (53)    NOT NULL,
    [RcptAmtTot]        FLOAT (53)    NOT NULL,
    [RcptCtrlAmt]       FLOAT (53)    NOT NULL,
    [RcptCtrlQty]       FLOAT (53)    NOT NULL,
    [RcptDate]          SMALLDATETIME NOT NULL,
    [RcptItemTotal]     FLOAT (53)    NOT NULL,
    [RcptNbr]           CHAR (10)     NOT NULL,
    [RcptQty]           FLOAT (53)    NOT NULL,
    [RcptQtyTot]        FLOAT (53)    NOT NULL,
    [RcptType]          CHAR (1)      NOT NULL,
    [ReopenPO]          SMALLINT      NOT NULL,
    [Rlsed]             SMALLINT      NOT NULL,
    [RMAID]             CHAR (15)     NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [ServiceCallID]     CHAR (10)     NOT NULL,
    [ShipperID]         CHAR (15)     NOT NULL,
    [Status]            CHAR (1)      NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [VendID]            CHAR (15)     NOT NULL,
    [VendInvcNbr]       CHAR (10)     NOT NULL,
    [VouchStage]        CHAR (1)      NOT NULL,
    [WayBillNbr]        CHAR (10)     NOT NULL,
    [tstamp]            ROWVERSION    NOT NULL
);

