CREATE TABLE [dbo].[potran] (
    [Acct]              CHAR (10)     NOT NULL,
    [AcctDist]          SMALLINT      NOT NULL,
    [AddlCost]          FLOAT (53)    NOT NULL,
    [AddlCostPct]       FLOAT (53)    NOT NULL,
    [AddlCostVouch]     FLOAT (53)    NOT NULL,
    [AlternateID]       CHAR (30)     NOT NULL,
    [AltIDType]         CHAR (1)      NOT NULL,
    [APLineID]          SMALLINT      NOT NULL,
    [APLineRef]         CHAR (5)      NOT NULL,
    [BatNbr]            CHAR (10)     NOT NULL,
    [BMICuryID]         CHAR (4)      NOT NULL,
    [BMIEffDate]        SMALLDATETIME NOT NULL,
    [BMIExtCost]        FLOAT (53)    NOT NULL,
    [BMIMultDiv]        CHAR (1)      NOT NULL,
    [BMIRate]           FLOAT (53)    NOT NULL,
    [BMIRtTp]           CHAR (6)      NOT NULL,
    [BMITranAmt]        FLOAT (53)    NOT NULL,
    [BMIUnitCost]       FLOAT (53)    NOT NULL,
    [BMIUnitPrice]      FLOAT (53)    NOT NULL,
    [BOMLineRef]        CHAR (5)      NOT NULL,
    [BOMSequence]       SMALLINT      NOT NULL,
    [CnvFact]           FLOAT (53)    NOT NULL,
    [CostVouched]       FLOAT (53)    NOT NULL,
    [CpnyID]            CHAR (10)     NOT NULL,
    [Crtd_DateTime]     SMALLDATETIME NOT NULL,
    [Crtd_Prog]         CHAR (8)      NOT NULL,
    [Crtd_User]         CHAR (10)     NOT NULL,
    [CuryAddlCost]      FLOAT (53)    NOT NULL,
    [CuryAddlCostVouch] FLOAT (53)    NOT NULL,
    [CuryCostVouched]   FLOAT (53)    NOT NULL,
    [CuryExtCost]       FLOAT (53)    NOT NULL,
    [CuryID]            CHAR (4)      NOT NULL,
    [CuryMultDiv]       CHAR (1)      NOT NULL,
    [CuryRate]          FLOAT (53)    NOT NULL,
    [CuryTranAmt]       FLOAT (53)    NOT NULL,
    [CuryUnitCost]      FLOAT (53)    NOT NULL,
    [DrCr]              CHAR (1)      NOT NULL,
    [ExtCost]           FLOAT (53)    NOT NULL,
    [ExtWeight]         FLOAT (53)    NOT NULL,
    [FlatRateLineNbr]   SMALLINT      NOT NULL,
    [InvtID]            CHAR (30)     NOT NULL,
    [JrnlType]          CHAR (3)      NOT NULL,
    [Labor_Class_Cd]    CHAR (4)      NOT NULL,
    [LineID]            INT           NOT NULL,
    [LineNbr]           SMALLINT      NOT NULL,
    [LineRef]           CHAR (5)      NOT NULL,
    [LUpd_DateTime]     SMALLDATETIME NOT NULL,
    [LUpd_Prog]         CHAR (8)      NOT NULL,
    [LUpd_User]         CHAR (10)     NOT NULL,
    [NoteID]            INT           NOT NULL,
    [OrigRcptDate]      SMALLDATETIME NOT NULL,
    [OrigRcptNbr]       CHAR (10)     NOT NULL,
    [OrigRetRcptNbr]    CHAR (10)     NOT NULL,
    [PC_Flag]           CHAR (1)      NOT NULL,
    [PC_ID]             CHAR (20)     NOT NULL,
    [PC_Status]         CHAR (1)      NOT NULL,
    [PerEnt]            CHAR (6)      NOT NULL,
    [PerPost]           CHAR (6)      NOT NULL,
    [POLineID]          INT           NOT NULL,
    [POLineNbr]         SMALLINT      NOT NULL,
    [POLIneRef]         CHAR (5)      NOT NULL,
    [PONbr]             CHAR (10)     NOT NULL,
    [POOriginal]        CHAR (1)      NOT NULL,
    [ProjectID]         CHAR (16)     NOT NULL,
    [PurchaseType]      CHAR (2)      NOT NULL,
    [Qty]               FLOAT (53)    NOT NULL,
    [QtyVouched]        FLOAT (53)    NOT NULL,
    [RcptConvFact]      FLOAT (53)    NOT NULL,
    [RcptDate]          SMALLDATETIME NOT NULL,
    [RcptLineRefOrig]   CHAR (5)      NOT NULL,
    [RcptMultDiv]       CHAR (1)      NOT NULL,
    [RcptNbr]           CHAR (10)     NOT NULL,
    [RcptNbrOrig]       CHAR (10)     NOT NULL,
    [RcptQty]           FLOAT (53)    NOT NULL,
    [RcptUnitDescr]     CHAR (6)      NOT NULL,
    [ReasonCd]          CHAR (6)      NOT NULL,
    [Refnbr]            CHAR (10)     NOT NULL,
    [S4Future01]        CHAR (30)     NOT NULL,
    [S4Future02]        CHAR (30)     NOT NULL,
    [S4Future03]        FLOAT (53)    NOT NULL,
    [S4Future04]        FLOAT (53)    NOT NULL,
    [S4Future05]        FLOAT (53)    NOT NULL,
    [S4Future06]        FLOAT (53)    NOT NULL,
    [S4Future07]        SMALLDATETIME NOT NULL,
    [S4Future08]        SMALLDATETIME NOT NULL,
    [S4Future09]        INT           NOT NULL,
    [S4Future10]        INT           NOT NULL,
    [S4Future11]        CHAR (10)     NOT NULL,
    [S4Future12]        CHAR (10)     NOT NULL,
    [ServiceCallID]     CHAR (10)     NOT NULL,
    [SiteID]            CHAR (10)     NOT NULL,
    [SOLineID]          INT           NOT NULL,
    [SOLineRef]         CHAR (5)      NOT NULL,
    [SOOrdNbr]          CHAR (15)     NOT NULL,
    [SOTypeID]          CHAR (4)      NOT NULL,
    [SpecificCostID]    CHAR (25)     NOT NULL,
    [StepNbr]           SMALLINT      NOT NULL,
    [Sub]               CHAR (24)     NOT NULL,
    [SvcContractID]     CHAR (10)     NOT NULL,
    [SvcLineNbr]        SMALLINT      NOT NULL,
    [TaskID]            CHAR (32)     NOT NULL,
    [TaxCat]            CHAR (10)     NOT NULL,
    [TaxIDDflt]         CHAR (10)     NOT NULL,
    [TranAmt]           FLOAT (53)    NOT NULL,
    [TranDate]          SMALLDATETIME NOT NULL,
    [TranDesc]          CHAR (60)     NOT NULL,
    [TranType]          CHAR (2)      NOT NULL,
    [UnitCost]          FLOAT (53)    NOT NULL,
    [UnitDescr]         CHAR (6)      NOT NULL,
    [UnitMultDiv]       CHAR (1)      NOT NULL,
    [UnitWeight]        FLOAT (53)    NOT NULL,
    [User1]             CHAR (30)     NOT NULL,
    [User2]             CHAR (30)     NOT NULL,
    [User3]             FLOAT (53)    NOT NULL,
    [User4]             FLOAT (53)    NOT NULL,
    [User5]             CHAR (10)     NOT NULL,
    [User6]             CHAR (10)     NOT NULL,
    [User7]             SMALLDATETIME NOT NULL,
    [User8]             SMALLDATETIME NOT NULL,
    [VendId]            CHAR (15)     NOT NULL,
    [VouchStage]        CHAR (1)      NOT NULL,
    [WhseLoc]           CHAR (10)     NOT NULL,
    [WIP_COGS_Acct]     CHAR (10)     NOT NULL,
    [WIP_COGS_Sub]      CHAR (24)     NOT NULL,
    [WOBomRef]          CHAR (5)      NOT NULL,
    [WOCostType]        CHAR (2)      NOT NULL,
    [WONbr]             CHAR (10)     NOT NULL,
    [WOStepNbr]         CHAR (5)      NOT NULL
);

