CREATE TABLE [dbo].[PurchOrd] (
    [AckDateTime]     SMALLDATETIME NOT NULL,
    [ASID]            INT           NOT NULL,
    [BatNbr]          CHAR (10)     NOT NULL,
    [BillShipAddr]    SMALLINT      NOT NULL,
    [BlktExprDate]    SMALLDATETIME NOT NULL,
    [BlktPONbr]       CHAR (10)     NOT NULL,
    [Buyer]           CHAR (10)     NOT NULL,
    [BuyerEmail]      CHAR (80)     NOT NULL,
    [CertCompl]       SMALLINT      NOT NULL,
    [ConfirmTo]       CHAR (10)     NOT NULL,
    [CpnyID]          CHAR (10)     NOT NULL,
    [Crtd_DateTime]   SMALLDATETIME NOT NULL,
    [Crtd_Prog]       CHAR (8)      NOT NULL,
    [Crtd_User]       CHAR (10)     NOT NULL,
    [CurrentNbr]      SMALLINT      NOT NULL,
    [CuryEffDate]     SMALLDATETIME NOT NULL,
    [CuryFreight]     FLOAT (53)    NOT NULL,
    [CuryID]          CHAR (4)      NOT NULL,
    [CuryMultDiv]     CHAR (1)      NOT NULL,
    [CuryPOAmt]       FLOAT (53)    NOT NULL,
    [CuryPOItemTotal] FLOAT (53)    NOT NULL,
    [CuryRate]        FLOAT (53)    NOT NULL,
    [CuryRateType]    CHAR (6)      NOT NULL,
    [CuryRcptTotAmt]  FLOAT (53)    NOT NULL,
    [CuryTaxTot00]    FLOAT (53)    NOT NULL,
    [CuryTaxTot01]    FLOAT (53)    NOT NULL,
    [CuryTaxTot02]    FLOAT (53)    NOT NULL,
    [CuryTaxTot03]    FLOAT (53)    NOT NULL,
    [CuryTxblTot00]   FLOAT (53)    NOT NULL,
    [CuryTxblTot01]   FLOAT (53)    NOT NULL,
    [CuryTxblTot02]   FLOAT (53)    NOT NULL,
    [CuryTxblTot03]   FLOAT (53)    NOT NULL,
    [EDI]             SMALLINT      NOT NULL,
    [FOB]             CHAR (15)     NOT NULL,
    [Freight]         FLOAT (53)    NOT NULL,
    [LastRcptDate]    SMALLDATETIME NOT NULL,
    [LineCntr]        INT           NOT NULL,
    [LUpd_DateTime]   SMALLDATETIME NOT NULL,
    [LUpd_Prog]       CHAR (8)      NOT NULL,
    [LUpd_User]       CHAR (10)     NOT NULL,
    [NoteID]          INT           NOT NULL,
    [OpenPO]          SMALLINT      NOT NULL,
    [PC_Status]       CHAR (1)      NOT NULL,
    [PerClosed]       CHAR (6)      NOT NULL,
    [PerEnt]          CHAR (6)      NOT NULL,
    [POAmt]           FLOAT (53)    NOT NULL,
    [PODate]          SMALLDATETIME NOT NULL,
    [POItemTotal]     FLOAT (53)    NOT NULL,
    [PONbr]           CHAR (10)     NOT NULL,
    [POType]          CHAR (2)      NOT NULL,
    [ProjectID]       CHAR (16)     NOT NULL,
    [PrtBatNbr]       CHAR (10)     NOT NULL,
    [PrtFlg]          SMALLINT      NOT NULL,
    [RcptStage]       CHAR (1)      NOT NULL,
    [RcptTotAmt]      FLOAT (53)    NOT NULL,
    [ReqNbr]          CHAR (10)     NOT NULL,
    [S4Future01]      CHAR (30)     NOT NULL,
    [S4Future02]      CHAR (30)     NOT NULL,
    [S4Future03]      FLOAT (53)    NOT NULL,
    [S4Future04]      FLOAT (53)    NOT NULL,
    [S4Future05]      FLOAT (53)    NOT NULL,
    [S4Future06]      FLOAT (53)    NOT NULL,
    [S4Future07]      SMALLDATETIME NOT NULL,
    [S4Future08]      SMALLDATETIME NOT NULL,
    [S4Future09]      INT           NOT NULL,
    [S4Future10]      INT           NOT NULL,
    [S4Future11]      CHAR (10)     NOT NULL,
    [S4Future12]      CHAR (10)     NOT NULL,
    [ServiceCallID]   CHAR (10)     NOT NULL,
    [ShipAddr1]       CHAR (60)     NOT NULL,
    [ShipAddr2]       CHAR (60)     NOT NULL,
    [ShipAddrID]      CHAR (10)     NOT NULL,
    [ShipAttn]        CHAR (30)     NOT NULL,
    [ShipCity]        CHAR (30)     NOT NULL,
    [ShipCountry]     CHAR (3)      NOT NULL,
    [ShipCustID]      CHAR (15)     NOT NULL,
    [ShipEmail]       CHAR (80)     NOT NULL,
    [ShipFax]         CHAR (30)     NOT NULL,
    [ShipName]        CHAR (60)     NOT NULL,
    [ShipPhone]       CHAR (30)     NOT NULL,
    [ShipSiteID]      CHAR (10)     NOT NULL,
    [ShipState]       CHAR (3)      NOT NULL,
    [ShiptoID]        CHAR (10)     NOT NULL,
    [ShiptoType]      CHAR (1)      NOT NULL,
    [ShipVendAddrID]  CHAR (10)     NOT NULL,
    [ShipVendID]      CHAR (15)     NOT NULL,
    [ShipVia]         CHAR (15)     NOT NULL,
    [ShipZip]         CHAR (10)     NOT NULL,
    [Status]          CHAR (1)      NOT NULL,
    [TaxCntr00]       SMALLINT      NOT NULL,
    [TaxCntr01]       SMALLINT      NOT NULL,
    [TaxCntr02]       SMALLINT      NOT NULL,
    [TaxCntr03]       SMALLINT      NOT NULL,
    [TaxID00]         CHAR (10)     NOT NULL,
    [TaxID01]         CHAR (10)     NOT NULL,
    [TaxID02]         CHAR (10)     NOT NULL,
    [TaxID03]         CHAR (10)     NOT NULL,
    [TaxTot00]        FLOAT (53)    NOT NULL,
    [TaxTot01]        FLOAT (53)    NOT NULL,
    [TaxTot02]        FLOAT (53)    NOT NULL,
    [TaxTot03]        FLOAT (53)    NOT NULL,
    [Terms]           CHAR (2)      NOT NULL,
    [TxblTot00]       FLOAT (53)    NOT NULL,
    [TxblTot01]       FLOAT (53)    NOT NULL,
    [TxblTot02]       FLOAT (53)    NOT NULL,
    [TxblTot03]       FLOAT (53)    NOT NULL,
    [User1]           CHAR (30)     NOT NULL,
    [User2]           CHAR (30)     NOT NULL,
    [User3]           FLOAT (53)    NOT NULL,
    [User4]           FLOAT (53)    NOT NULL,
    [User5]           CHAR (10)     NOT NULL,
    [User6]           CHAR (10)     NOT NULL,
    [User7]           SMALLDATETIME NOT NULL,
    [User8]           SMALLDATETIME NOT NULL,
    [VendAddr1]       CHAR (60)     NOT NULL,
    [VendAddr2]       CHAR (60)     NOT NULL,
    [VendAddrID]      CHAR (10)     NOT NULL,
    [VendAttn]        CHAR (30)     NOT NULL,
    [VendCity]        CHAR (30)     NOT NULL,
    [VendCountry]     CHAR (3)      NOT NULL,
    [VendEmail]       CHAR (80)     NOT NULL,
    [VendFax]         CHAR (30)     NOT NULL,
    [VendID]          CHAR (15)     NOT NULL,
    [VendName]        CHAR (60)     NOT NULL,
    [VendPhone]       CHAR (30)     NOT NULL,
    [VendState]       CHAR (3)      NOT NULL,
    [VendZip]         CHAR (10)     NOT NULL,
    [VouchStage]      CHAR (1)      NOT NULL,
    [WSID]            INT           NOT NULL,
    [tstamp]          ROWVERSION    NOT NULL
);

