CREATE TABLE [caredata].[EV_FARROWINGS] (
    [event_id]        INT             NOT NULL,
    [identity_id]     INT             NOT NULL,
    [sexed]           BIT             CONSTRAINT [DF_EV_FARROWINGS_sexed] DEFAULT ((0)) NOT NULL,
    [liveborn_gilts]  TINYINT         NOT NULL,
    [liveborn_boars]  TINYINT         NOT NULL,
    [stillborn]       TINYINT         NULL,
    [mummified]       TINYINT         NULL,
    [litter_weight]   FLOAT (53)      NULL,
    [assisted]        BIT             NULL,
    [induced]         BIT             NULL,
    [litter_identity] VARCHAR (15)    NULL,
    [sow_weight]      FLOAT (53)      NULL,
    [UDF72331]        VARCHAR (30)    NULL,
    [UDF70343]        VARCHAR (30)    NULL,
    [UDF58882]        VARCHAR (30)    NULL,
    [UDF97503]        VARCHAR (30)    NULL,
    [UDF20279]        VARCHAR (30)    NULL,
    [UDF59264]        NUMERIC (20, 1) NULL,
    [UDF64863]        VARCHAR (8)     NULL,
    [UDF49749]        VARCHAR (8)     NULL,
    [UDF39031]        VARCHAR (8)     NULL,
    [UDF19999]        INT             NULL,
    [UDF35005]        INT             NULL,
    [UDF43650]        VARCHAR (30)    NULL,
    [UDF92678]        VARCHAR (30)    NULL,
    [UDF75286]        VARCHAR (30)    NULL,
    [UDF93021]        VARCHAR (30)    NULL,
    [UDF9148]         VARCHAR (30)    NULL,
    [UDF13148]        VARCHAR (30)    NULL,
    [UDF25454]        VARCHAR (30)    NULL,
    [UDF76421]        VARCHAR (8)     NULL,
    [UDF10078]        VARCHAR (8)     NULL,
    [UDF10478]        INT             NULL,
    [UDF65485]        INT             NULL,
    [UDF17770]        VARCHAR (8)     NULL,
    [UDF58751]        VARCHAR (30)    NULL,
    [UDF48901]        VARCHAR (30)    NULL,
    [UDF24616]        VARCHAR (30)    NULL,
    [UDF72533]        VARCHAR (30)    NULL,
    [UDF65931]        VARCHAR (30)    NULL,
    [UDF66964]        VARCHAR (30)    NULL,
    [UDF18763]        INT             NULL,
    [UDF66922]        NUMERIC (20, 2) NULL,
    [UDF5823]         NUMERIC (20, 3) NULL,
    [substandard]     TINYINT         NULL,
    [UDF042270]       INT             NULL,
    [UDF029986]       VARCHAR (36)    NULL,
    CONSTRAINT [PK_EV_FARROWINGS] PRIMARY KEY CLUSTERED ([identity_id] ASC, [event_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EV_FARROWINGS_BH_EVENTS_0] FOREIGN KEY ([event_id]) REFERENCES [caredata].[BH_EVENTS] ([event_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_EV_FARROWINGS_BH_IDENTITIES_1] FOREIGN KEY ([identity_id]) REFERENCES [caredata].[BH_IDENTITIES] ([identity_id])
);

