CREATE TABLE [deleted].[CFT_ANIMAL] (
    [ID]              NVARCHAR (36) NOT NULL,
    [CREATE_DATE]     DATETIME      NOT NULL,
    [LAST_UPDATE]     DATETIME      NOT NULL,
    [CREATED_BY]      BIGINT        NOT NULL,
    [LAST_UPDATED_BY] BIGINT        NOT NULL,
    [DELETED_BY]      BIGINT        NOT NULL,
    [BIRTHDATE]       DATETIME      NULL,
    [GENETICSID]      NVARCHAR (36) NULL,
    [ORIGIN]          NVARCHAR (50) NULL,
    [SEX]             NVARCHAR (10) NULL,
    [ORIGINID]        NVARCHAR (36) NULL,
    [PIGCHAMP_ID]     BIGINT        NULL,
    [PRINTFLAG]       NVARCHAR (1)  NULL,
    [DEVICEFARMID]    NVARCHAR (36) NULL,
    [ACTIVE]          NVARCHAR (1)  NULL,
    CONSTRAINT [CFT_ANIMAL_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

