CREATE TABLE [deleted].[CFT_ANIMALEVENTS] (
    [ID]                   NVARCHAR (36) NOT NULL,
    [CREATE_DATE]          DATETIME      NOT NULL,
    [LAST_UPDATE]          DATETIME      NOT NULL,
    [CREATED_BY]           BIGINT        NOT NULL,
    [LAST_UPDATED_BY]      BIGINT        NOT NULL,
    [DELETED_BY]           BIGINT        NOT NULL,
    [ANIMALID]             NVARCHAR (36) NULL,
    [PARITYNBR]            INT           NULL,
    [EVENTDATE]            DATETIME      NULL,
    [EVENTTHDATE]          NVARCHAR (10) NULL,
    [EVENTTYPEID]          NVARCHAR (36) NULL,
    [GROUPNAME]            NVARCHAR (4)  NULL,
    [QTY]                  INT           NULL,
    [BORNALIVE]            INT           NULL,
    [STILLBORN]            INT           NULL,
    [MUMMY]                INT           NULL,
    [SETNBR]               INT           NULL,
    [LOCATIONID]           NVARCHAR (36) NULL,
    [GESTATIONLENGTH]      INT           NULL,
    [MATINGHOUR]           INT           NULL,
    [BREEDERID]            NVARCHAR (36) NULL,
    [SEMENID]              NVARCHAR (36) NULL,
    [HEATCYCLE]            INT           NULL,
    [MATINGNBR]            INT           NULL,
    [BREEDINGNBR]          INT           NULL,
    [PARITYSERVICENBR]     INT           NULL,
    [SOURCEFARMID]         NVARCHAR (36) NULL,
    [DESTINATIONFARMID]    NVARCHAR (36) NULL,
    [REMOVALREASONID]      INT           NULL,
    [EVENTNBR]             INT           NULL,
    [COMMENT]              TEXT          NULL,
    [ANIMALSTATUS]         INT           NULL,
    [PREVSTATUS]           INT           NULL,
    [SYNCSTATUS]           NVARCHAR (20) NULL,
    [DEVICEID]             NVARCHAR (36) NULL,
    [DEVICEVERSION]        NVARCHAR (10) NULL,
    [ENTEREDDATE]          DATETIME      NULL,
    [LASTUPDATEDEVICEID]   NVARCHAR (36) NULL,
    [LASTUPDATEAPPVERSION] NVARCHAR (10) NULL,
    [LASTUPDATEDATE]       DATETIME      NULL,
    [PIGCHAMP_ID]          BIGINT        NULL,
    [DEVICEFARMID]         NVARCHAR (36) NULL,
    CONSTRAINT [CFT_ANIMALEVENTS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

